Documentation of Activity Feed Notification APIs
microsoftgraph/microsoft-graph-docs pull request #10721
Opened 2020-11-17 22:29 UTC by RamjotSingh

2020-11-17 22:30 UTC, opbld32 commented
Docs Build status updates of commit _[3524bdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3524bdf371babf2473af40d7600ef1aaccce6a75)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-fa8c248c-aa97a6bf)
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-ee5686b2-aa97a6bf)
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) | [Details](#user-content-c97be298-aa97a6bf)
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="fa8c248c-aa97a6bf"></a>
### [api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md)
 - **Line 53, Column 165**: **[Warning-file-not-found]** `````Invalid file link: 'aadusernotificationrecipient.md'.`````

<a id="ee5686b2-aa97a6bf"></a>
### [api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md)
 - **Line 52, Column 165**: **[Warning-file-not-found]** `````Invalid file link: 'aadusernotificationrecipient.md'.`````

<a id="c97be298-aa97a6bf"></a>
### [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 250, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'NotificationSettings' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 250, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'NotificationSettings' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 254, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'NotificationSettings' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172229060319-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BFJnRIn1QyWAcGh6ougI%2BnY%2F4wNKo%2F%2Bq2F9GK%2FNMMIw%3D&st=2020-11-17T22%3A25%3A14Z&se=2020-12-18T22%3A30%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on  [...]

2020-11-17 22:32 UTC, opbld33 commented
Docs Build status updates of commit _[0d7c2f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d7c2f2a74831b7d1e1e6ad771c2c2fed9c07e47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-fa8c248c-653f0218)
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-ee5686b2-653f0218)
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) | [Details](#user-content-c97be298-653f0218)
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="fa8c248c-653f0218"></a>
### [api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md)
 - **Line 53, Column 165**: **[Warning-file-not-found]** `````Invalid file link: 'aadusernotificationrecipient.md'.`````

<a id="ee5686b2-653f0218"></a>
### [api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md)
 - **Line 52, Column 165**: **[Warning-file-not-found]** `````Invalid file link: 'aadusernotificationrecipient.md'.`````

<a id="c97be298-653f0218"></a>
### [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 250, Column 1**: **[Suggestion-alt-text-bad-value]** `````Alt text 'NotificationSettings' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 250, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'NotificationSettings' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 254, Column 1**: **[Suggestion-duplicate-alt-text]** `````Alt text 'NotificationSettings' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172231114350-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=h7cVXIu1hRcZmsys9D2n3AA%2F4FfD%2Bwo52lyhNBGPKWc%3D&st=2020-11-17T22%3A27%3A22Z&se=2020-12-18T22%3A32%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's Gi [...]

2020-11-17 22:37 UTC, opbld31 commented
Docs Build status updates of commit _[41d461e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41d461e739f980d96afc2d276ae9cd67768ab246)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172236246449-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ae81DKJSYatmhNs%2FGvPbAWtgmC3mpvw74p1Pj0Vgros%3D&st=2020-11-17T22%3A32%3A48Z&se=2020-12-18T22%3A37%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:46 UTC, opbld33 commented
Docs Build status updates of commit _[99e6c81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/99e6c81a5dfad9c2e333a44dcf87bf493449a5da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-7d8afd84-8d4884e4)
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="7d8afd84-8d4884e4"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md)
 - **Line 17, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172244529435-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e3N5BC%2FUl6oifC%2FJkxfCUKRb%2FqZnX%2BFFj%2Bpxddq7aHw%3D&st=2020-11-17T22%3A41%3A11Z&se=2020-12-18T22%3A46%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:49 UTC, opbld34 commented
Docs Build status updates of commit _[a8c0ef4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8c0ef4469efb795587466fbad2a1867b2e8d15c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-7d8afd84-3b41b5af)
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="7d8afd84-3b41b5af"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md)
 - **Line 17, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172247459147-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HtylWxL39s7iCy%2FN5BRJSPpcsRYpdg89L7YuApuL3%2Bo%3D&st=2020-11-17T22%3A44%3A11Z&se=2020-12-18T22%3A49%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:50 UTC, opbld33 commented
Docs Build status updates of commit _[6bd7148](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6bd71488e389144c5c2b0d3c55d6198660f49398)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-7d8afd84-f1260924)
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="7d8afd84-f1260924"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md)
 - **Line 17, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172248570417-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GHEBIrgYfpkjV7Vag%2FecA54aZtczy4KHstKojZTecfg%3D&st=2020-11-17T22%3A45%3A37Z&se=2020-12-18T22%3A50%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:52 UTC, opbld34 commented
Docs Build status updates of commit _[65f9f8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65f9f8e11b8523f84f8858303e89cb9650b34fa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-7d8afd84-73b4b5c1)
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="7d8afd84-73b4b5c1"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md)
 - **Line 17, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172249398084-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pkwws5m%2FUgHEBxjMjKyBI5K6Gn4UAA29KcxGDAE3YZ4%3D&st=2020-11-17T22%3A47%3A04Z&se=2020-12-18T22%3A52%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:53 UTC, opbld32 commented
Docs Build status updates of commit _[0d42d98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d42d98f07ed9b4e88a1747c15368fa1091ef5c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) | [Details](#user-content-7d8afd84-939db298)
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

<a id="7d8afd84-939db298"></a>
### [api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md)
 - **Line 17, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172250508207-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Bam5p5Mh1czpHdCUVmd6E6Ta2EwIgsD7PsmdnPuQQ6I%3D&st=2020-11-17T22%3A48%3A22Z&se=2020-12-18T22%3A53%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 22:55 UTC, opbld33 commented
Docs Build status updates of commit _[53ddcc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53ddcc257a2c9c524bb53b2a24e7c759bdfb571c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172253207752-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LiwOZeS7zsdjCJeqEfzgWW%2F0LFiFjVGD1HzeciNuOA0%3D&st=2020-11-17T22%3A49%3A59Z&se=2020-12-18T22%3A54%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 23:01 UTC, opbld32 commented
Docs Build status updates of commit _[4ad12c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ad12c440967be1050926fe6d9b1ad15db13e80f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172300213357-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pk%2F%2Fz%2F0IopAxHQZUNfEvsvsV8iDHfDlmKjp2XCvM79Q%3D&st=2020-11-17T22%3A56%3A54Z&se=2020-12-18T23%3A01%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 23:03 UTC, opbld30 commented
Docs Build status updates of commit _[67ab6ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67ab6eed95c0926313e6eebeae90732035f6b4de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172301414151-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vmyacAqUuzRa2J9avtLByU16tINFvCF0p5kFRPlt3r4%3D&st=2020-11-17T22%3A58%3A37Z&se=2020-12-18T23%3A03%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 23:43 UTC, opbld33 commented
Docs Build status updates of commit _[3c5308f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c5308f5ec8990766fdb207b67063f21d19524fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172342285169-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OYTJ3OsppmzD1ZfGKg2awja6AnXb9NvOBacsQK5rXcA%3D&st=2020-11-17T23%3A38%3A46Z&se=2020-12-18T23%3A43%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 23:49 UTC, opbld31 commented
Docs Build status updates of commit _[db1ba5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db1ba5fb9a2a4b0a295ac08074df79de1bf7b8da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172348214885-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XK3x27Ovq7x3LMjnh%2BCL2anRcsKrnVMGl6wy7a0%2F3ME%3D&st=2020-11-17T23%3A44%3A41Z&se=2020-12-18T23%3A49%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-17 23:55 UTC, opbld34 commented
Docs Build status updates of commit _[0937b5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0937b5aba3997b3a70dfc9a80d06e27522c0aab8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011172354374141-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0lSxNy%2BNy%2FV%2FsgiHbfKMWyx1KIbl%2F55XstVRxhUG4u8%3D&st=2020-11-17T23%3A50%3A56Z&se=2020-12-18T23%3A55%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 00:03 UTC, opbld34 commented
Docs Build status updates of commit _[e4095a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4095a3b78e3a62379bc4389f4bb0b5a74d6de26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011180001452011-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=THSMnkyJP5IipTClZQqDKpnldiEKS1BoMO0Y%2BreTJT4%3D&st=2020-11-17T23%3A58%3A05Z&se=2020-12-19T00%3A03%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +Microsoft Teams Activity feed acts as an excellent way to triage the things which require attention. It is *the* place to inform users of changes or things which require their attention. Activity fee
lower case "activity"

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +Microsoft Teams Activity feed acts as an excellent way to triage the things which require attention. It is *the* place to inform users of changes or things which require their attention. Activity fee
is *the* emphasis absolutely needed?

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +Microsoft Teams Activity feed acts as an excellent way to triage the things which require attention. It is *the* place to inform users of changes or things which require their attention. Activity fee
"notifications APIs" should probably read "notification APIs"

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +![FeedExample](images/teams-activityfeednotifications/examplefeednotification.png)
Can we have a better example? This is too scratchy. Something from Yammer, Jira, etc with a demo tenant user should be fine

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +    "id": "6d1f5132-c2b4-440d-b6e9-bef3fc03123c",
I have seen people use guids in docs for trying out. Just want to understand there wont be any damage with this guid

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +}
We need document all possibilities so developers know about it. Either in this section or the details section below. Eddie should know them.

2020-11-18 00:56 UTC, raghukolluru commented on concepts/teams-send-activityfeednotifications.md
> +|Parameter|Type|Description|
Should you call out which are required vs not?

2020-11-18 00:56 UTC, raghukolluru commented on api-reference/beta/resources/aadusernotificationrecipient.md
> +title: "aadUserNotificationRecipient resource type"
Do we need this page in the left nav when there are no properties?

2020-11-18 01:16 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-sendactivitynotification.md
> +As seen in examples above, you can link to different aspects of the chat. However if you want to link an aspect which is not part of the chat, or is not represented by Microsoft Graph. You can
Remove period between 2nd and 3rd sentences

2020-11-18 01:16 UTC, eddie-lee-msft commented on api-reference/beta/api/team-sendactivitynotification.md
> +        `{
Remove extra `

2020-11-18 01:16 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +- Personal [teams app installation](../resources/teamsappinstallation.md)
Only this and below are true. Above resources aren't supported. We would have to make code changes to make that happen.

2020-11-18 01:16 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +### Example 2 : Notify a user about a task created in a team
This example isn't valid.

2020-11-18 01:16 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +### Example 4 : Notify a user about a approval needed in a chat message
This example is also not valid.

2020-11-18 01:35 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +### Installing the teams app
Just a disambiguation measure, between the product Microsoft Teams and the app. It is a real struggle so this is what I am have settled with.

2020-11-18 01:55 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +}
I think these should be all developer-defined, no?

I remember that userMention, channelMention, and teamMention had different icons, but after testing just now it seems they all use the App icon.

2020-11-18 05:53 UTC, RonMathews commented on api-reference/beta/api/chat-sendactivitynotification.md
> +|chainId|Int64|Optional. Used to override a previous notification. Use the same `chainId` in subsequent requests to override the previous notification.|
Would it be clearer to have a separate required column?

2020-11-18 05:57 UTC, RonMathews commented on api-reference/beta/api/team-sendactivitynotification.md
> +### Example 1 : Notify a user about a pending user add requests in a team
This is confusing - there's a separate tab for pending requests and this seems like it would navigate us to that tab when this is just taking us to the general channel of the team?

2020-11-18 20:41 UTC, AkJo commented on concepts/teams-send-activityfeednotifications.md
> +Activity feed APIs do not work in a standalone fashion, but work in tandem with the [teams app](/microsoftteams/platform/overview). To send activity feed notifications, following requirements must be
Teams

2020-11-18 20:42 UTC, AkJo commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** : You might get an error if multiple teams app in the same scope (team, chat or user) are using the same Azure AD app. Please ensure you are using unique Azure AD apps.
Typo

2020-11-18 20:42 UTC, AkJo commented on concepts/teams-send-activityfeednotifications.md
> +Teams apps can be installed in a team, a chat or for a user personally. Their are multiple ways a teams app can be distributed. You can refer to [teams app distribution methods](/microsoftteams/platf
There

2020-11-18 20:45 UTC, AkJo commented on concepts/teams-send-activityfeednotifications.md
> +POST https://graph.microsoft.com/beta/team/{teamId}/sendActivityNotification
teams

2020-11-19 12:09 UTC, RamjotSingh commented on api-reference/beta/api/chat-sendactivitynotification.md
> +|chainId|Int64|Optional. Used to override a previous notification. Use the same `chainId` in subsequent requests to override the previous notification.|
This format is use by compiler for verifications.

2020-11-19 12:10 UTC, RamjotSingh commented on api-reference/beta/api/chat-sendactivitynotification.md
> +> **Note:** The entity url must be same or child resource of the chat in the url. Additionally, the [teams app](/microsoftteams/platform/overview) must be installed in the chat.
I suppose? I mean if the recipient does not even have access to resource, they won't be able to see resource anyway. So I imagine that is a natural thing.

2020-11-19 12:12 UTC, RamjotSingh commented on api-reference/beta/api/chat-sendactivitynotification.md
> +As seen in examples above, you can link to different aspects of the chat. However if you want to link an aspect which is not part of the chat, or is not represented by Microsoft Graph. You can
The period was right, rewrote a bit for clarity.

2020-11-19 12:14 UTC, RamjotSingh commented on api-reference/beta/api/team-sendactivitynotification.md
> +### Example 1 : Notify a user about a pending user add requests in a team
Rewrote.

2020-11-19 12:15 UTC, RamjotSingh commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +- Personal [teams app installation](../resources/teamsappinstallation.md)
Removed.

2020-11-19 12:17 UTC, RamjotSingh commented on api-reference/beta/resources/aadusernotificationrecipient.md
> +title: "aadUserNotificationRecipient resource type"
This one actually has properties. But I can remove the other one from Nav I suppose.

2020-11-19 12:22 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +Microsoft Teams Activity feed acts as an excellent way to triage the things which require attention. It is *the* place to inform users of changes or things which require their attention. Activity fee
Fixed.

2020-11-19 12:30 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +![FeedExample](images/teams-activityfeednotifications/examplefeednotification.png)
Replaces with Yammer example.

2020-11-19 12:31 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +![FeedTemplate](images/teams-activityfeednotifications/notificationtemplate.png)
Sadly I picked this image from the powerpoint i dont have the source for it.

2020-11-19 12:33 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +    "id": "6d1f5132-c2b4-440d-b6e9-bef3fc03123c",
Replaced with random Guid.

2020-11-19 12:34 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +}
These are developer defined, so just talking about basics here.

2020-11-19 12:35 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +|Parameter|Type|Description|
Everything really is. I have added Optional in front of things which are truly optional.

2020-11-19 12:38 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +This example shows how you can send an activity feed notification for a team. This example notifies the team owner about pending member add requests.
Fixed.

2020-11-19 12:39 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +As seen in examples above, you can link to different aspects of the team. However if you want to link an aspect which is not part of the team, is not represented by Microsoft Graph, or want to custom
Changed a bit.

2020-11-19 12:40 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** `webUrl` must start with the Microsoft Teams domain (teams.microsoft.com for example).
Deeplinks have their docs.

2020-11-19 12:42 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +    "topic": {
Added yammer example and referred it here.

2020-11-19 12:49 UTC, opbld31 commented
Docs Build status updates of commit _[7cce9f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cce9f82a2948b449a026f41248d978dcf045e1f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191248242778-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1VpDcgReuUtLds4G9tYrlpYqPrG21k8Ob%2F9VIVmJgiM%3D&st=2020-11-19T12%3A44%3A41Z&se=2020-12-20T12%3A49%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 15:05 UTC, raghukolluru approved these changes

2020-11-19 18:38 UTC, eddie-lee-msft requested changes

2020-11-19 18:38 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** : You might get an error if multiple Teams app in the same scope (team, chat or user) are using the same Azure AD app. Please ensure you are using unique Azure AD apps.
Double colon after Note

2020-11-19 18:38 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +> **Note:** : You might get an error if multiple Teams app in the same scope (team, chat or user) are using the same Azure AD app. Please ensure you are using unique Azure AD apps.
Multiple teams apps (plural)

2020-11-19 18:38 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +As seen in examples above, you can link to different aspects of a team or a chat. However, if you want to link an aspect which is not part of the team, is not represented by Microsoft Graph, or want
2nd and 3rd sentences need to be combined.

2020-11-19 18:38 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +The Yammer notification shown the example above, uses custom topic since Yammer's resources are not supported by Microsoft Graph.
- shown *in* the example above
- also no comma after 'above'
- I think this sentence would be clearer if you said explicitly that the Yammer screenshot at the start of the doc is a Yammer notification screenshot. Otherwise people who don't user Yammer would not know what the "Yammer notification shown in the example above" would mean

2020-11-19 18:38 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +As a user of Microsoft Teams, user can customize the notifications they see in their feed, as a banner etc. Notifications generated through activity feed APIs follow the same suit. Users can choose h
As a user of Microsoft Teams, *a* user

-or-

As *users* of Microsoft Teams, *users*

2020-11-19 18:38 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-sendactivitynotification.md
> +|previewText|[itemBody](../resources/itembody.md)|Preview text for the notification. Microsoft Teams will only show first 150 characters.|
Should we mention that this is optional also?

2020-11-19 18:38 UTC, eddie-lee-msft commented on api-reference/beta/resources/teamworkactivitytopic.md
> +
Channel is also a resource. I think we should call that out explicitly. Both here and in https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?branch=pr-en-us-10721&view=graph-rest-beta

2020-11-19 18:38 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-sendactivitynotification.md
> +|previewText|[itemBody](../resources/itembody.md)|Preview text for the notification. Microsoft Teams will only show first 150 characters.|
Should we also call out that 'text' contentType is the only one supported right now?

2020-11-19 18:38 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +#### Response
Duplicate response block

2020-11-19 18:38 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +As seen in examples above, you can link to different aspects of the team. However if you want to link an aspect which is not part of the team, is not represented by Microsoft Graph, or want to custom
Let's not mention anything about 'team' here.

2020-11-19 18:51 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +The Yammer notification shown the example above, uses custom topic since Yammer's resources are not supported by Microsoft Graph.
Oh no I literally meant like example 1 and 2 and not yammer. Yammer is custom :).

2020-11-19 18:55 UTC, RamjotSingh commented on api-reference/beta/api/chat-sendactivitynotification.md
> +|previewText|[itemBody](../resources/itembody.md)|Preview text for the notification. Microsoft Teams will only show first 150 characters.|
Intentionally not doing that for now. Absence of preview text is a very corner case, which I would in most cases not recommend.

2020-11-19 18:57 UTC, RamjotSingh commented on api-reference/beta/api/chat-sendactivitynotification.md
> +|previewText|[itemBody](../resources/itembody.md)|Preview text for the notification. Microsoft Teams will only show first 150 characters.|
I am just not mentioning it altogether and examples don't show it either.

2020-11-19 18:58 UTC, RamjotSingh commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +As seen in examples above, you can link to different aspects of the team. However if you want to link an aspect which is not part of the team, is not represented by Microsoft Graph, or want to custom
Done.

2020-11-19 18:59 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +The Yammer notification shown the example above, uses custom topic since Yammer's resources are not supported by Microsoft Graph.
So you  mean shown in the example below?

2020-11-19 19:01 UTC, opbld31 commented
Docs Build status updates of commit _[82c32be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82c32bee9201f9f3b37232789a52f9f1bf8ee6f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191859517260-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bCrNRNUm8aswqN16LQ%2Fc2UHz%2FJyFUk5kro4sRZ0D0jw%3D&st=2020-11-19T18%3A56%3A23Z&se=2020-12-20T19%3A01%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 19:02 UTC, RamjotSingh commented on concepts/teams-send-activityfeednotifications.md
> +The Yammer notification shown the example above, uses custom topic since Yammer's resources are not supported by Microsoft Graph.
Nvm you comment is showing up in wrong place :|. Fixing.

2020-11-19 19:04 UTC, opbld32 commented
Docs Build status updates of commit _[b6cc315](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6cc315765ad77f9ca12388e7ab445fbce4de6f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191903177065-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RJIc5N2tCja9S9vLBGkRQ6OVhdw2OcGU73azoLrKWHQ%3D&st=2020-11-19T18%3A59%3A31Z&se=2020-12-20T19%3A04%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 19:16 UTC, eddie-lee-msft approved these changes

2020-11-19 19:16 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +The Yammer notification shown the section above, uses custom topic since Yammer's resources are not supported by Microsoft Graph.
shown IN the section above.

also you don't need the comma after 'above'!

2020-11-19 19:16 UTC, eddie-lee-msft commented on concepts/teams-send-activityfeednotifications.md
> +Activity feed APIs do not work in a standalone fashion, but work in tandem with a [Teams app](/microsoftteams/platform/overview). To send activity feed notifications, the following requirements must
colon at the end of this.

the following requirements must be met:

2020-11-19 19:16 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +POST https://graph.microsoft.com/beta/team/{teamId}/sendActivityNotification
Shouldn't use team endpoint in this doc

2020-11-19 19:16 UTC, eddie-lee-msft commented on api-reference/beta/api/userteamwork-sendactivitynotification.md
> +    "recipient": {
Subsequently we'll need to remove recipient field

2020-11-19 19:16 UTC, eddie-lee-msft commented on api-reference/beta/api/team-sendactivitynotification.md
> +POST https://graph.microsoft.com/beta/team/{teamId}/sendActivityNotification
teams plural

2020-11-19 19:20 UTC, opbld31 commented
Docs Build status updates of commit _[431cdc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/431cdc025e5bf47c76cc12b79e80784d601a1201)_: 

:clock10: **Pending**: waiting for processors ([14](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 14 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-19 19:22 UTC, opbld34 commented
Docs Build status updates of commit _[431cdc0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/431cdc025e5bf47c76cc12b79e80784d601a1201)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191920201529-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z4WmtOj1vSOyrnjkkvTY0GuD4ho5Iy6bdGcNNp2x%2FJ0%3D&st=2020-11-19T19%3A17%3A01Z&se=2020-12-20T19%3A22%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-19 19:25 UTC, opbld34 commented
Docs Build status updates of commit _[3b3656f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b3656fd32bf167fea14136cbc51b8f581000e08)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-11-19 19:27 UTC, opbld32 commented
Docs Build status updates of commit _[3b3656f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b3656fd32bf167fea14136cbc51b8f581000e08)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011191925176127-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UZ1rF5l01mDI8OmFRLj9M68dttzZFNTr05DGnbuXir0%3D&st=2020-11-19T19%3A22%3A09Z&se=2020-12-20T19%3A27%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 04:27 UTC, opbld34 commented
Docs Build status updates of commit _[4e1cfce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e1cfced0445353d8e66de63b8d06b4da22660a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200426377988-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cIuWowmqlI6qcfvtf7KUg5oijUtSADF9P3M4xfVYZGU%3D&st=2020-11-20T04%3A22%3A55Z&se=2020-12-21T04%3A27%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 04:32 UTC, opbld34 commented
Docs Build status updates of commit _[edf08cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edf08cda945a2efa2a6e5057c0dbc6076ef161e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200431127672-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mEuZh2Y80rTljcBOZ7xFgIrTTGUeSBWwzUDOZLB06Rs%3D&st=2020-11-20T04%3A27%3A47Z&se=2020-12-21T04%3A32%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 04:34 UTC, opbld31 commented
Docs Build status updates of commit _[f3de580](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3de5806d0717300d13c0b58601e4b23aa20e65d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200432105313-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5iv1A%2BVz0aeiwabSXZ4kLXaFw75nC%2FMT8VrhfSQEMs4%3D&st=2020-11-20T04%3A29%3A18Z&se=2020-12-21T04%3A34%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 05:38 UTC, opbld31 commented
Docs Build status updates of commit _[97daac0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97daac09d153c1f555d51511a4e6cdc9eb5d6898)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200537133835-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zZbSRPRzhihCaPhpRed2JKyUH6IqHeM4%2BLBrq0yiONU%3D&st=2020-11-20T05%3A33%3A33Z&se=2020-12-21T05%3A38%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 05:44 UTC, opbld32 commented
Docs Build status updates of commit _[6f6cea6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f6cea6c1c3d1a9577407eb9710a06bf916ba452)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200542286288-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vpryASgfjy%2B8OnMoQlhmoZKVwoBsnuiV0ZCcyY0X%2BhI%3D&st=2020-11-20T05%3A39%3A02Z&se=2020-12-21T05%3A44%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 05:45 UTC, opbld34 commented
Docs Build status updates of commit _[24d29ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24d29eec2bb9359bf25fc32c126aba5314cbb298)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200543145598-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fc0d4npVdD6zTsIhHooWEq%2BzOF8FN5sTkaSUmKbI88w%3D&st=2020-11-20T05%3A40%3A26Z&se=2020-12-21T05%3A45%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-20 05:55 UTC, opbld33 commented
Docs Build status updates of commit _[c165c9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c165c9e64d5ee1332155d25da93f86766880af68)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011200554161746-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HhlNOkg5F8j7wNpTFif1P8u5IXssapVx6oUTSqboPxU%3D&st=2020-11-20T05%3A50%3A39Z&se=2020-12-21T05%3A55%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 00:38 UTC, opbld34 commented
Docs Build status updates of commit _[50f4d39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50f4d39f032b8d844daa3d1f055e12287c4f3249)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-61bd662d)

<a id="61bd662d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210038122849-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=il4318wdpEsjKqRgROxbZpRAKyfnw0Hm3TOTkH1SxIA%3D&st=2020-11-21T00%3A33%3A40Z&se=2020-12-22T00%3A38%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 00:41 UTC, opbld30 commented
Docs Build status updates of commit _[1d61c9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d61c9cea5a930d5df98952a9c85938778012139)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cb530f30)

<a id="cb530f30"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210040443671-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NgOacevrNl97oHe31IrSRGi8TPdcGbljOw3qjJU4Sdw%3D&st=2020-11-21T00%3A36%3A00Z&se=2020-12-22T00%3A41%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 00:46 UTC, opbld32 commented
Docs Build status updates of commit _[cc77771](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc777715490323dc3b398d55881fadb64f2bbf15)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f95621aa)

<a id="f95621aa"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210046098673-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IgvhWZVkyt2I6QGp0FeSeXOLcUfYeivRFODwqXYgjsg%3D&st=2020-11-21T00%3A41%3A36Z&se=2020-12-22T00%3A46%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 00:47 UTC, opbld32 commented
Docs Build status updates of commit _[4832b48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4832b481f432e230ac945c252dea38df3577b3ea)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d468e04c)

<a id="d468e04c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210047078187-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bJVyO4c284d7xfDtsFEgQVBsZQhZoz7Mwco1tPlgois%3D&st=2020-11-21T00%3A42%3A40Z&se=2020-12-22T00%3A47%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:03 UTC, opbld33 commented
Docs Build status updates of commit _[5574518](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5574518b734e8dfe4846c57480cda872b8e9cdc5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210101461061-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jgjOq%2F8yEKQdpmoWjdY5HnZEP%2BzGmj5bSdlPQeh%2BHuQ%3D&st=2020-11-21T00%3A58%3A21Z&se=2020-12-22T01%3A03%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:08 UTC, opbld34 commented
Docs Build status updates of commit _[986e04c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/986e04cae3f6c5dc2c59dd4a6442d274067db00e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210107165098-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ec%2BuS6vun97oAs4rIdi8mDL4k%2FsNmj15da8dmMnH0zo%3D&st=2020-11-21T01%3A03%3A40Z&se=2020-12-22T01%3A08%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 01:15 UTC, opbld33 commented
Docs Build status updates of commit _[cc36e05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc36e0562ca84a47bd5d499d4c5f827ae489883c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210113533381-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F0P6hpwIdGdsc9AAh66z2AK3Hiqo3Sz%2FAza9%2FeWPv%2BA%3D&st=2020-11-21T01%3A10%3A13Z&se=2020-12-22T01%3A15%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 02:30 UTC, opbld31 commented
Docs Build status updates of commit _[43c00cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43c00cc67d3d856cf09e796f7220f445e3dacb43)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210228444840-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pAVwGKeFEfBlfsbdnajn2jP%2BscljPtMGjKWIHt7v7B4%3D&st=2020-11-21T02%3A25%3A07Z&se=2020-12-22T02%3A30%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 02:32 UTC, opbld34 commented
Docs Build status updates of commit _[0895884](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0895884f56eb36701a56ae416d5836e54a7ab348)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/chat-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/team-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/team-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/api/userteamwork-sendactivitynotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/api/userteamwork-sendactivitynotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/aadusernotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/aadusernotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aadusernotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworkactivitytopic.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworkactivitytopic.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkactivitytopic?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/resources/teamworknotificationrecipient.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/resources/teamworknotificationrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworknotificationrecipient?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-sendactivitynotification?view=graph-rest-beta&branch=pr-en-us-10721) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/applevelnotificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/examplefeednotification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/examplefeednotification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationsettings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationsettings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/images/teams-activityfeednotifications/notificationtemplate.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/images/teams-activityfeednotifications/notificationtemplate.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-11-17-ramjsing-feedapis/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-10721) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011210231207724-10721%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HkeWFH1gcrzBNua2OMz7ZnK7GxhDxrypPh%2Bdmq09ydI%3D&st=2020-11-21T02%3A27%3A32Z&se=2020-12-22T02%3A32%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-21 02:42 UTC, Lauragra approved these changes

2020-11-21 02:42 UTC, merged