Add presence to Graph v1.0
microsoftgraph/microsoft-graph-docs pull request #10772
Opened 2020-11-22 23:11 UTC by elvinyang-msft

Adding presence doc for Graph v1.0 and include throttling limits.

2020-11-22 23:12 UTC, opbld30 commented
Docs Build status updates of commit _[b44a8ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b44a8abd57e35af30d285603abeafd71d3788bbd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :x:Error | | [Details](#user-content-94074f58-d376ca8b)
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :x:Error | | [Details](#user-content-6b67f350-d376ca8b)
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | | [Details](#user-content-0ac8db59-d376ca8b)

<a id="94074f58-d376ca8b"></a>
### [api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-presence-multiple-users-objc-snippets.md'.`````
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-presence-multiple-users-java-snippets.md'.`````

<a id="6b67f350-d376ca8b"></a>
### [api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-your-presence-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-your-presence-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-your-presence-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-your-presence-java-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presence-csharp-snippets.md'.`````
 - **Line 126, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presence-javascript-snippets.md'.`````
 - **Line 130, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presence-objc-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presence-java-snippets.md'.`````
 - **Line 178, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presences-csharp-snippets.md'.`````
 - **Line 182, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presences-javascript-snippets.md'.`````
 - **Line 186, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presences-objc-snippets.md'.`````
 - **Line 190, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presences-java-snippets.md'.`````

<a id="0ac8db59-d376ca8b"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/presence?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-23 21:15 UTC, satyakonmsft commented on api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
> +> * The request rate of this API is limited to 1500 API requests per 30 seconds per app/tenant.
per application per tenant

2020-11-23 21:15 UTC, satyakonmsft approved these changes

2020-11-24 03:46 UTC, opbld33 commented
Docs Build status updates of commit _[a0e2eb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0e2eb93996f6f41fac34164107cb7a8e16a9ede)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :x:Error | | [Details](#user-content-94074f58-66645934)
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :x:Error | | [Details](#user-content-6b67f350-66645934)
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | | [Details](#user-content-0ac8db59-66645934)

<a id="94074f58-66645934"></a>
### [api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-presence-multiple-users-objc-snippets.md'.`````
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-presence-multiple-users-java-snippets.md'.`````

<a id="6b67f350-66645934"></a>
### [api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-your-presence-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-your-presence-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-your-presence-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-your-presence-java-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presence-csharp-snippets.md'.`````
 - **Line 126, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presence-javascript-snippets.md'.`````
 - **Line 130, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presence-objc-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presence-java-snippets.md'.`````
 - **Line 178, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presences-csharp-snippets.md'.`````
 - **Line 182, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presences-javascript-snippets.md'.`````
 - **Line 186, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presences-objc-snippets.md'.`````
 - **Line 190, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presences-java-snippets.md'.`````

<a id="0ac8db59-66645934"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/presence?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-24 03:48 UTC, opbld34 commented
Docs Build status updates of commit _[ba5499c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba5499c614a7f50e9f76d6f6b2dd884ecd955612)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :x:Error | | [Details](#user-content-94074f58-fe117903)
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :x:Error | | [Details](#user-content-6b67f350-fe117903)
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | | [Details](#user-content-0ac8db59-fe117903)

<a id="94074f58-fe117903"></a>
### [api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-presence-multiple-users-objc-snippets.md'.`````
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-presence-multiple-users-java-snippets.md'.`````

<a id="6b67f350-fe117903"></a>
### [api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-your-presence-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-your-presence-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-your-presence-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-your-presence-java-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presence-csharp-snippets.md'.`````
 - **Line 126, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presence-javascript-snippets.md'.`````
 - **Line 130, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presence-objc-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presence-java-snippets.md'.`````
 - **Line 178, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presences-csharp-snippets.md'.`````
 - **Line 182, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presences-javascript-snippets.md'.`````
 - **Line 186, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presences-objc-snippets.md'.`````
 - **Line 190, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presences-java-snippets.md'.`````

<a id="0ac8db59-fe117903"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/presence?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-24 03:50 UTC, opbld34 commented
Docs Build status updates of commit _[470651a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/470651a549afed5df8350203399fdcf8ed80eb4b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :x:Error | | [Details](#user-content-94074f58-bb5e7789)
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :x:Error | | [Details](#user-content-6b67f350-bb5e7789)
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | | [Details](#user-content-0ac8db59-bb5e7789)

<a id="94074f58-bb5e7789"></a>
### [api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-presence-multiple-users-objc-snippets.md'.`````
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-presence-multiple-users-java-snippets.md'.`````

<a id="6b67f350-bb5e7789"></a>
### [api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-your-presence-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-your-presence-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-your-presence-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-your-presence-java-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presence-csharp-snippets.md'.`````
 - **Line 126, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presence-javascript-snippets.md'.`````
 - **Line 130, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presence-objc-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presence-java-snippets.md'.`````
 - **Line 178, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presences-csharp-snippets.md'.`````
 - **Line 182, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presences-javascript-snippets.md'.`````
 - **Line 186, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presences-objc-snippets.md'.`````
 - **Line 190, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presences-java-snippets.md'.`````

<a id="0ac8db59-bb5e7789"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/presence?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did [...]

2020-11-24 03:55 UTC, jsandoval-msft requested changes
can we also include a quick update to this: https://docs.microsoft.com/en-us/graph/throttling#cloud-communication-service-limits. We update a patch update earlier, but should adjust to match the 1500 requests per 30 second period mentioned here.

2020-12-04 02:47 UTC, opbld34 commented
Docs Build status updates of commit _[9abe1c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9abe1c16798303d6a11925d42a3f6763086f592d)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 02:47 UTC, opbld34 commented
Docs Build status updates of commit _[9abe1c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9abe1c16798303d6a11925d42a3f6763086f592d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4ad4eae5)

<a id="4ad4eae5"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040247023536-10772%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7qQHFe%2FMCgHgGaCtArYd%2FLV3l71NQnXykATaisuEF9I%3D&st=2020-12-04T02%3A42%3A24Z&se=2021-01-04T02%3A47%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 03:21 UTC, opbld33 commented
Docs Build status updates of commit _[446296a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/446296ad2327221f122c0c690560a575978fa843)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :x:Error | | [Details](#user-content-94074f58-79ba5e42)
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :x:Error | | [Details](#user-content-6b67f350-79ba5e42)
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | | [Details](#user-content-0ac8db59-79ba5e42)
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/throttling.md) | :bulb:Suggestion | | [Details](#user-content-c38f2dd7-79ba5e42)

<a id="94074f58-79ba5e42"></a>
### [api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md)
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-presence-multiple-users-objc-snippets.md'.`````
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-presence-multiple-users-java-snippets.md'.`````

<a id="6b67f350-79ba5e42"></a>
### [api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md)
 - **Line 69, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-your-presence-csharp-snippets.md'.`````
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-your-presence-javascript-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-your-presence-objc-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-your-presence-java-snippets.md'.`````
 - **Line 122, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presence-csharp-snippets.md'.`````
 - **Line 126, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presence-javascript-snippets.md'.`````
 - **Line 130, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presence-objc-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presence-java-snippets.md'.`````
 - **Line 178, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presences-csharp-snippets.md'.`````
 - **Line 182, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presences-javascript-snippets.md'.`````
 - **Line 186, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presences-objc-snippets.md'.`````
 - **Line 190, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presences-java-snippets.md'.`````

<a id="0ac8db59-79ba5e42"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-12-04 03:37 UTC, opbld34 commented
Docs Build status updates of commit _[331532a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/331532a1a7669492d65c10f766d2867be5dbe493)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) | [Details](#user-content-0ac8db59-4530a0c2)
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10772) | [Details](#user-content-c38f2dd7-4530a0c2)
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-user-presence-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-user-presence-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-user-presences-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-user-presences-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-your-presence-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-your-presence-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-presence-multiple-users-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-presence-multiple-users-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-user-presence-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-user-presence-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-user-presences-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-user-presences-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-your-presence-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-your-presence-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-user-presence-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-user-presence-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-user-presences-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-user-presences-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-your-presence-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-your-presence-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-presence-multiple-users-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/objc/get-presence-multiple-users-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-user-presence-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/objc/get-user-presence-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-user-presences-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/objc/get-user-presences-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2020-12-04 19:09 UTC, elvinyang-msft commented on api-reference/v1.0/api/presence-get.md
> +### Example 3: Get the presence information of another user
That's for subscription

2020-12-04 19:12 UTC, opbld33 commented
Docs Build status updates of commit _[6a2554e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a2554ed1bdce09a3bb2ff25586164702ae44d4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) | [Details](#user-content-0ac8db59-98eaf2eb)
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10772) | [Details](#user-content-c38f2dd7-98eaf2eb)
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-user-presence-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-user-presence-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-user-presences-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-user-presences-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-your-presence-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/csharp/get-your-presence-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-presence-multiple-users-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-presence-multiple-users-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-user-presence-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-user-presence-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-user-presences-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-user-presences-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-your-presence-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/java/get-your-presence-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-user-presence-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-user-presence-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-user-presences-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-user-presences-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-your-presence-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/javascript/get-your-presence-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-presence-multiple-users-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/objc/get-presence-multiple-users-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-user-presence-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/objc/get-user-presence-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-user-presences-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/includes/snippets/objc/get-user-presences-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/ [...]

2020-12-04 19:15 UTC, Lauragra commented on api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
> +# [HTTP](#tab/http)
Please remove this H1.

2020-12-04 19:16 UTC, Lauragra commented on api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md
> +# [C#](#tab/csharp)
Global: We don't bring forward the SDK snippets when we promote APIs to v1.0. Those will get autogenerated via the weekly automation after we merge into master. Please remove the snippet links and snippet files from the PR.

2020-12-04 19:18 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|v1.0|Added the [presence](/graph/api/resources/presence?view=graph-rest-1.0&preserve-view=true) resource type|
Please remove this from November and create a new Cloud communications table for December. Also, we need an update to the Skype.Calling.json file in the changelog folder for the new filterable changelog experience.

2020-12-04 19:32 UTC, opbld30 commented
Docs Build status updates of commit _[efd7136](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efd713696cec15fb39a914e684ef9194a263dbb8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md) | :x:Error | | [Details](#user-content-7ad63d16-71b79a0d)
[api-reference/beta/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/beta/api/presence-get.md) | :x:Error | | [Details](#user-content-6f77539f-71b79a0d)
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | | [Details](#user-content-0ac8db59-71b79a0d)
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/throttling.md) | :bulb:Suggestion | | [Details](#user-content-c38f2dd7-71b79a0d)

<a id="7ad63d16-71b79a0d"></a>
### [api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md)
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-presence-multiple-users-csharp-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-presence-multiple-users-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-presence-multiple-users-objc-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-presence-multiple-users-java-snippets.md'.`````

<a id="6f77539f-71b79a0d"></a>
### [api-reference/beta/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/beta/api/presence-get.md)
 - **Line 67, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-your-presence-csharp-snippets.md'.`````
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-your-presence-javascript-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-your-presence-objc-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-your-presence-java-snippets.md'.`````
 - **Line 120, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presence-csharp-snippets.md'.`````
 - **Line 124, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presence-javascript-snippets.md'.`````
 - **Line 128, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presence-objc-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presence-java-snippets.md'.`````
 - **Line 176, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-user-presences-csharp-snippets.md'.`````
 - **Line 180, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-user-presences-javascript-snippets.md'.`````
 - **Line 184, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-user-presences-objc-snippets.md'.`````
 - **Line 188, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-user-presences-java-snippets.md'.`````

<a id="0ac8db59-71b79a0d"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to [...]

2020-12-04 19:35 UTC, opbld33 commented
Docs Build status updates of commit _[5429a55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5429a55fa30f360775bc1a8316520409ad7f2a5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/communications-api-overview?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) | [Details](#user-content-0ac8db59-32d4c7ab)
[concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/throttling.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/throttling?branch=pr-en-us-10772) | [Details](#user-content-c38f2dd7-32d4c7ab)
[api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/cloudcommunications-getpresencesbyuserid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/api/presence-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-1.0&branch=pr-en-us-10772) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10772) |

<a id="0ac8db59-32d4c7ab"></a>
### [api-reference/v1.0/resources/communications-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/api-reference/v1.0/resources/communications-api-overview.md)
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#methods`````
 - **Line 35, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/calls-api-ivr-overview?view=graph-rest-v1.0`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#methods`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/callrecords-callrecord?view=graph-rest-1.0`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhooks?view=graph-rest-1.0`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/presence?view=graph-rest-v1.0`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/call?view=graph-rest-v1.0#properties`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/participant?view=graph-rest-v1.0#properties`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/onlinemeeting?view=graph-rest-v1.0#properties`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/presence?view=graph-rest-v1.0`````

<a id="c38f2dd7-32d4c7ab"></a>
### [concepts/throttling.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presencev1/concepts/throttling.md)
 - **Line 84, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/externalitem?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/profilephoto?view=graph-rest-1.0`````
 - **Line 512, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationassignment?view=graph-rest-beta`````
 - **Line 513, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationsubmission?view=graph-rest-beta`````
 - **Line 514, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationresource?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041933547806-10772%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pZSHRvDXixiMfFTE8aCgl69Aee7R7MY1CDRP2Rqd7Js%3D&st=2020-12-04T19%3A30%3A11Z&se=2021-01-04T19%3A35%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/ [...]

2020-12-04 23:13 UTC, Lauragra approved these changes

2020-12-04 23:13 UTC, merged