Adding Graph Explorer documentation
microsoftgraph/microsoft-graph-docs pull request #10807
Opened 2020-11-24 20:19 UTC by bettirosengugi

Added Graph Explorer documentation under concepts.

2020-11-24 20:20 UTC, opbld31 commented
Docs Build status updates of commit _[e7e3e97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7e3e97836bb6501f77726be5626fef47b7906c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-ca13c4c9-2b8b6a38)
[concepts/graph-explorer/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) | [Details](#user-content-0e74d894-2b8b6a38)
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

<a id="ca13c4c9-2b8b6a38"></a>
### [concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 6, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'bengugi' is not a valid GitHub ID.`````
 - **Line 52, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/toolkit/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 141, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/toolkit/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Use Graph Explorer to try Microsoft Graph APIs - Microsoft Graph' is duplicated [...]

2020-11-24 20:33 UTC, opbld31 commented
Docs Build status updates of commit _[e7c8676](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7c8676c02af0ca38079b67ee2e0b25b971bc157)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-ca13c4c9-5b82b13e)
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |

<a id="ca13c4c9-5b82b13e"></a>
### [concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md)
 - **Line 54, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/toolkit/overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011242031018749-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bjFNwrl6XnlDdndzFW63iyTlMuqScOF8v7cCPuaPddU%3D&st=2020-11-24T20%3A28%3A06Z&se=2020-12-25T20%3A33%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.mi [...]

2020-11-24 20:38 UTC, opbld33 commented
Docs Build status updates of commit _[489d794](https://github.com/microsoftgraph/microsoft-graph-docs/commits/489d794073fb717854195f227daa5a5f7ada4085)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011242036328567-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kZYYks4hqsiPFDR2gcD2cwhOLSBBV3YHGacDc2kyO%2Bo%3D&st=2020-11-24T20%3A33%3A27Z&se=2020-12-25T20%3A38%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 02:43 UTC, opbld30 commented
Docs Build status updates of commit _[11a9967](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11a99676b77d4c62b4d92b44c71b2db61f8029a7)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 02:45 UTC, opbld34 commented
Docs Build status updates of commit _[11a9967](https://github.com/microsoftgraph/microsoft-graph-docs/commits/11a99676b77d4c62b4d92b44c71b2db61f8029a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/overview?branch=pr-en-us-10807) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040243363361-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0tWdP71HAX0Zr5k8pU9A%2B77dGk1F5UqeKDKy%2BdNIAEs%3D&st=2020-12-04T02%3A40%3A02Z&se=2021-01-04T02%3A45%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 06:17 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +[Graph Explorer](https://developer.microsoft.com/graph/graph-explorer/) is a developer tool that you can use make Microsoft Graph API requests and view the responses. You can use Graph Explorer to tr
Line 12:
"...a developer tool that you can use to make Microsoft Graph API requests and view responses."

2020-12-09 06:43 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +[Graph Explorer](https://developer.microsoft.com/graph/graph-explorer/) is a developer tool that you can use make Microsoft Graph API requests and view the responses. You can use Graph Explorer to tr
"... in a sample tenant or your own developer sandbox to explore"
I think you mean one can use the sample tenant that we provide, right? So that's not "a sample tenant", but "the sample tenant".
Also, this part of the sentence - the two things between the "or" - are supposed to be parallel. So if you take away the  thing about sample tenant, and connect the first part of the sentence to the thing about "your own developer sandbox", the sentence becomes:
"You can use Graph Explorer to try new APIs **in** your own developer sandbox to explore the capabilities..."

I think the "in" can be misleading. Even though I think you mean "try new APIs using the customer's own tenant and data, using the term "developer sandbox" is too loose a term. In general, a developer sandbox _can_ be an entire development environment, so the suggestion of using Graph Explorer _in_ a developer's own development environment could be misunderstood as incorporating Graph Explorer as part of that environment, and we don't support that. Graph Explorer can only be accessed on developer.microsoft.com.

Maybe you can say:
"Use Graph Explorer Explorer to try new APIs on the default sample tenant, or on your own tenant as a prototyping tool to explore capabilities and fulfill your app scenarios.".

2020-12-09 06:55 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +
I think the last sentence I suggested already implies one can use Graph Explorer with or without signing in. So perhaps you can remove the first sentence in line 14.

2020-12-09 06:59 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +- Make requests (GET, POST, PUT, PATCH and DELETE) against Microsoft Graph APIs and see responses and response headers.
Line 16:
"Make Microsoft Graph API requests (GET, POST,...) and see responses including response code and any headers and bodies."

"Make requests against Microsoft Graph APIs..." doesn't sound right. These HTTP verbs (GET, POST,....) are part of the requests.

2020-12-10 01:59 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +- Access Microsoft Graph Toolkit components and Adaptive cards for some sample queries.
Line 23:
Please use "adaptive cards" both words start with lower case.

2020-12-10 02:57 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +
GE feedback: 
Regarding "collapsing the sidebar":
You might have got heard this before from other people - how did we choose the top left hamburger icon (the 3 horizontal lines) to collapse or expand the left sidebar?
That hamburger icon is commonly used on other web apps (e.g., iOS apps) to display a drop-down menu for site navigation.

2020-12-10 03:39 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +To try POST, PUT, PATCH and DELETE requests, you need to sign in to Graph Explorer using your Microsoft 365 account. You can use a demo account or your organizational account. To get a free sample Mi
Line 57:
"... using a Microsoft 365 account". "your Microsoft 365 account" implies the reader only has one account available, which is typically not the case. Besides, your next sentence says that account can be a "demo account" or "organizational account".

BTW, for the 2nd sentence, I think we should say "That account can be an organization account for testing or demonstration purpose.". I don't think we should write "demo"; localization may have problems. I also think it's a good idea we stay away from suggesting using a organization production account.

2020-12-10 04:03 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +
Line 60:
"... sign in with an organization account, running a non-GET request can affect the data in the corresponding tenant."

Also, please remove the spaces around !IMPORTANT and the square brackets. Your alert is not displayed properly on the staging site.

2020-12-10 04:06 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +
Line 62:
"For instance, to run a POST request, select POST in the drop-down list for the HTTP verb, and add a request body and request headers as appropriate."

2020-12-10 04:07 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +3. Request query address bar
Lines 34-35:
Please change "dropdown list" to "drop-down list".

2020-12-10 04:14 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +2. Update the Request body e.g. in this case giving the application a name then run the query.
Line 67:
Bold "Request body", since "Request body" is UI text.

2020-12-10 04:21 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +2. Update the Request body e.g. in this case giving the application a name then run the query.
Line 67:
Step #2: Please use correct punctuation: "Update **Request body**, for example, give the application a name.

Separate step #3: "Click **Run query**.

Make the next step #4.

2020-12-10 04:51 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +1. Request headers tab to add key value pairs.
Line 74:
What is this line?
Is that meant to be alt text?

2020-12-10 04:54 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +To view the response in a format other than the default JSON, choose the **Request headers** tab in the request pane, define the key/value pair, and click **Add**.
Line 70:
Do you mean to say:
"To view a response in a format other than the default JSON format, in the **Request headers** tab, enter the desired value for the **Content-Type** request header and click **Add**."

2020-12-10 04:57 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +
For internal efficiency, do you mind renaming this file with a prefix, like graph-explorer-overview.md?

2020-12-10 04:59 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +## Get code snippets that you can use in your application.
GLOBAL:
Please remove the period at the end of a section title, like in lines 40 and 48.

2020-12-10 05:01 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +## Get and copy the Access or Authentication token
GLOBAL and line 32:
Per Microsoft Writing Style Guide, please use sentence case for topic and section titles.

In line 32, I'd suggest simplifying the title as:
"Get an access or authentication token"

2020-12-10 05:08 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Lines 34 and 37:
Bold "Access token", since this is a UI string..

2020-12-10 05:10 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +2.	Copy access token.
Line 38:
"Click the **Copy** icon to copy the access token."

2020-12-10 07:13 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +## Get code snippets that you can use in your application.
Line 40:
Using Microsoft Voice, please make the section title more succinct.
Suggest "Copy code snippets".

2020-12-10 07:25 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Line 42:
You don't actually have to run the REST query. Even as you type a REST query, the Code snippets tab would show the API call in the selected language.
Perhaps you can tighten line 42 and say:
"For each REST API query you select or enter in Graph Explorer, you can find how to call that API in each of the four languages showcased under the **Code snippets** tab - C#, Java, JavaScript, and Objective-C."

2020-12-10 07:32 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Line 84:
Please make this a level 2 section title. This is about customizing the look and feel of Graph Explorer, it doesn't have anything to do with implementing the UI in an app.

2020-12-10 07:34 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Line 84:
Suggest section title: "Customize the theme for Graph Explorer".

2020-12-10 07:36 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +1.	Navigate to the Settings Gear, then select the Change theme option.
Line 90:
Lower-case "Settings Gear".
Apply Microsoft Voice:
"Navigate to the settings gear, then select **Change theme**.

2020-12-10 07:37 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +2.	See the list of available themes and choose your preferred theme.
Line 91:
"Choose your preferred theme from the list of available themes."

2020-12-10 07:52 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +## Get User Interface components to aid your UI implementation.
Line 48:
"Implement user interface conveniently using components"

2020-12-10 07:55 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +Graph Explorer includes several features to help to make your UI implementation process easier. You can reuse these components directly in your applications.
Line 50:
"... features to make implementing user interface easier." You can reuse components in your apps too.

2020-12-10 08:42 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +Graph Explorer includes queries that support Microsoft Graph Toolkit components supported. When you run those queries, you will see a blue dot on the **Toolkit component** tab, and you can get the co
Line 56:
Please remove the last word "supported" from the first sentence.

2020-12-10 08:51 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +Graph Explorer includes queries that support Microsoft Graph Toolkit components supported. When you run those queries, you will see a blue dot on the **Toolkit component** tab, and you can get the co
Rewrite the second sentence:
"A blue dot on the **Toolkit component** tab indicates the Toolkit provides a component for the currently specified REST API query in Graph Explorer. Conveniently copy the code for the component to your app.

2020-12-10 08:57 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +This list will be expanded to include more queries with time as the Microsoft Graph Toolkit team adds more capabilities to the tool.
Line 66:
"This table will include more queries over time when the Microsoft Graph Toolkit supports more capabilities of Microsoft Graph API.

2020-12-11 08:46 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Lines 70 and 71:
Capitalize first 't' in "toolkit".

2020-12-11 08:53 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +[Adaptive Cards](https://adaptivecards.io/) are platform-agnostic snippets of UI, authored in JSON, that apps and services can openly exchange. When you run a query and an adaptive card is available,
GLOBAL:
Please use sentence case for "adaptive cards".
I see in some other sites that document the same feature that use title case. I don't think adaptive cards is an official brand. Therefore please use sentence case.

2020-12-11 09:18 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
You're annotating to make it easier for the vision-impaired. Perhaps you can provide a bit more context assuming the user actually can't see details on the screen. I suggest the following:
Lines 80:
"Select and run a sample query in Graph Explorer."
Line 81:
Since "Adaptive cards" is the UI text here, bold the words.
Line 83:
"The adaptive card displays the query response."

2020-12-11 09:29 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Line 96:
"Queries run in Graph Explorer are saved for 30 days in the **History** tab. You can view, run, export, or delete queries in the history." Is this what you mean?

2020-12-11 09:32 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
FYI when describing UI control that's visible in a screen shot, we usually leave it to the customer to discover the UI control and not further indicate where it is on the screen.

2020-12-11 09:38 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
Image included in line 110:
Wonder why I see the UI text "Expand" and "Share" by the side of the expand and share icons respectively, but your image only shows the icons?

2020-12-11 09:41 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-features.md
> +
So if it's the case that going forward, the "Expand" and "Share" UI text will continue to be displayed, then I think it's not necessary to include such easily discoverable functionality in the docs.

2020-12-11 10:01 UTC, angelgolfer-ms requested changes
Hi @bettirosengugi ,
In general, UI should be discoverable and self-explanatory. Were there specific reasons these 2 topics cover UI exhaustively? Some features are worth highlighting, and some are pretty obvious. Don't feel that we have to document everything just for completeness.

Please see my comments otherwise, if you do decide to keep to this level of detail.

As for the TOC entry point, please do the following:
(a) Add a TOC entry point under Develop >> Use the API, right above "Use Postman". Call it "Use Graph Explorer".
(b) Important: Graph Explorer should have a control (e.g., '?', or "Help") that links to the Graph Explorer overview topic.

IMO, ideally, this help should just be accessible from Graph Explorer. It's pretty disconnected to  have it accessible only through the docs site.

2021-01-12 17:49 UTC, bettirosengugi commented on concepts/graph-explorer/overview.md
> +
Thanks @angelgolfer-ms for this feedback. Will add it to the UI items we need to fix on GE.

2021-01-12 18:48 UTC, bettirosengugi commented on concepts/graph-explorer/overview.md
> +1. Request headers tab to add key value pairs.
No, it's supposed to describe the screenshot, I have rectified it.

2021-01-13 08:50 UTC, opbld31 commented
Docs Build status updates of commit _[3a0ae76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a0ae76a12e063ddeb0bbbde47c2d24ebcca6e6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-b329d26c-d3285765)
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

<a id="b329d26c-d3285765"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml)
 - **Line 491, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-overview'.`````
 - **Line 493, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-features'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130848469956-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a9OYycAwbDtvKegcD6Wo1qsWkBAsYDiqyBMFQMG2eBQ%3D&st=2021-01-13T08%3A45%3A42Z&se=2021-02-13T08%3A50%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&g [...]

2021-01-13 10:12 UTC, opbld34 commented
Docs Build status updates of commit _[e5fb605](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5fb605e1724a940b50fe32496343a82427bc4a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-b329d26c-4748be44)
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

<a id="b329d26c-4748be44"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml)
 - **Line 491, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-overview.md'.`````
 - **Line 493, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-features.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101131011168184-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LKpJIluGGnIjr01b7BJYr5hDlWXYGgzH5wvtkGDfOOk%3D&st=2021-01-13T10%3A07%3A36Z&se=2021-02-13T10%3A12%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011 [...]

2021-01-13 10:22 UTC, opbld31 commented
Docs Build status updates of commit _[0618ce3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0618ce3eb27a8eef183f367f21e65075e218c992)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-b329d26c-32618eb7)
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

<a id="b329d26c-32618eb7"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml)
 - **Line 491, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-overview.md'.`````
 - **Line 493, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-features.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101131021053888-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RP94YSOnY0128e0%2FucJcC%2F3xuJx6Ck72cg5uLEpFI2g%3D&st=2021-01-13T10%3A17%3A13Z&se=2021-02-13T10%3A22%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7c [...]

2021-01-14 04:15 UTC, opbld34 commented
Docs Build status updates of commit _[9a96402](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a96402bfcadf201aa885ebd74267a00450c68bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-b329d26c-68adcde9)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

<a id="b329d26c-68adcde9"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml)
 - **Line 493, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-overview.md'.`````
 - **Line 495, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-features.md'.`````

For more details, please refer to the [build report](ht [...]

2021-01-14 04:16 UTC, opbld30 commented
Docs Build status updates of commit _[206f8c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/206f8c068d3fa1459339409d22d22271c36f3b9b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) | [Details](#user-content-b329d26c-45f9f7f7)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

<a id="b329d26c-45f9f7f7"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml)
 - **Line 493, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-overview.md'.`````
 - **Line 495, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph-explorer-features.md'.`````

For more details, please refer to the [build report](ht [...]

2021-01-14 05:10 UTC, opbld33 commented
Docs Build status updates of commit _[52aba57](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52aba574056a5ab10e5e189c787180db5dce6365)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140509449862-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w4a8e1g8Sb%2B0eMqCPPBaYZrerBQP%2Beewg9A3ZdOH6dg%3D&st=2021-01-14T05%3A05%3A57Z&se=2021-02-14T05%3A10%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, p [...]

2021-01-14 07:52 UTC, angelgolfer-ms reviewed
@bettirosengugi , please take a look at the changes I made on your behalf in the 3 toc.yml files, and see if you have any questions if you were to make similar TOC modifications in the future.

2021-01-14 20:49 UTC, bettirosengugi commented
> @bettirosengugi , please take a look at the changes I made on your behalf in the 3 toc.yml files, and see if you have any questions if you were to make similar TOC modifications in the future.

Thanks @angelgolfer-ms for your help, now I know how to edit the toc next time. Please help merge the PR, it's ready now.

2021-01-16 02:15 UTC, opbld30 commented
Docs Build status updates of commit _[efddfed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efddfed6780ccdfea8013feb5a10464cf4138100)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101160214182765-10807%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BTkIawoX7B0giF4Sljv%2FakQ0SwXOt0gmzt5WGdKpc8A%3D&st=2021-01-16T02%3A10%3A34Z&se=2021-02-16T02%3A15%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, ple [...]

2021-01-20 08:00 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-overview.md
> +[Graph Explorer](https://developer.microsoft.com/graph/graph-explorer/) is a developer tool that lets you conveniently make Microsoft Graph REST API requests and view corresponding responses. Use Gra
Line 12:
Please remove repeated "Explorer" in the second sentence.

2021-01-20 08:08 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-overview.md
> +To try POST, PUT, PATCH and DELETE requests, sign in to Graph Explorer using a Microsoft 365 account. This can be an organizational test or demo account. To get a free sample Microsoft 365 E5 develop
Line 58:
Please rephrase the second sentence; like my original comment for this part of the topic, because "demo" is not technically an English word, Localization would have problem localizing a term like this.
Suggest:
"This can be an organizational account for testing or demonstration purpose. "

2021-01-20 08:18 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +3. Request query address bar
@bettirosengugi , @Lauragra , per the following page, the term should be hyphenated, "drop-down list". "dropdown list" is not appropriate.
https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28800

Please make a consistent change to instances in this PR.

2021-01-20 08:24 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-overview.md
@bettirosengugi , I have a question about the image making-a-non-get-request.png:
What are the "1" and "2" referring to in that image?
They don't seem to map to the step numbers in the numbered list in lines 67-70, right below the image.
Can you clarify?

2021-01-20 08:26 UTC, angelgolfer-ms commented on concepts/graph-explorer/graph-explorer-overview.md
> +![Screenshot that shows the Request headers tab in Graph Explorer](./images/request-header.png)
@bettirosengugi , similar question for the image request-header.png - what is "1" referring to in the image?
"1" doesn't map to any step in any numbered list that describes this image. Line 72 is just a paragraph, not a numbered list. Please fix.

2021-01-20 08:30 UTC, angelgolfer-ms commented on concepts/graph-explorer/overview.md
> +To view the response in a format other than the default JSON, choose the **Request headers** tab in the request pane, define the key/value pair, and click **Add**.
Hm, apparently you didn't agree with being more specific, and point out in this case to change the format of the response, one should set a different value to the Content-Type header?

2021-01-22 10:48 UTC, bettirosengugi commented on concepts/graph-explorer/graph-explorer-overview.md
I have rectified the screenshot

2021-01-22 11:09 UTC, opbld30 commented
Docs Build status updates of commit _[95a40d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95a40d653d48e26f024c25306c47908824578dde)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-26 02:13 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +
We need an introduction to this article that sets the intent for the reader. This can be a quick description of Graph Explorer and a statement like "This article describes some of the important features in Graph Explorer."

2021-01-26 02:14 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +description: "Graph Explorer features documentation"
When you write an introduction, also consider a summary statement here that will help drive traffic from search. This description might show up as text in search results.

2021-01-26 02:34 UTC, opbld32 commented
Docs Build status updates of commit _[e1e49a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1e49a8ccbc270192a91b6acf964fa2397c08341)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-26 02:34 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +## Consent to permissions in Graph Explorer
This seems like how-to type information instead of descriptions of features. Consider whether a different title would better match the intent of the article - i.e. "Working with Graph Explorer".

2021-01-26 02:35 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +Graph Explorer includes several features to make implementing user interface easier. Reuse these components in your apps too.
This section seems like it needs further description. Also, for a developer audience, we can abbreviate user interface as UI, for readability.

2021-01-26 02:38 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +| **Graph Explorer sample query** | **Toolkit sample iFrame URL** |
Why are we included this table and links, when they can get this information from Graph Explorer itself?

2021-01-26 02:39 UTC, opbld30 commented
Docs Build status updates of commit _[bd9b93f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd9b93fe58337a67dada76d502e445027c80705b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-26 02:51 UTC, opbld32 commented
Docs Build status updates of commit _[ebde4fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebde4fac65eeca9aa034503783b17ea62ae2d8d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-26 17:56 UTC, bettirosengugi commented on concepts/graph-explorer/graph-explorer-features.md
> +description: "Graph Explorer features documentation"
@Lauragra not sure I understand this request, please elaborate further

2021-01-26 18:06 UTC, opbld31 commented
Docs Build status updates of commit _[1cef350](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cef350b0250af373bd88b7fbd6ffdf46893f067)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-26 21:57 UTC, Lauragra commented on concepts/graph-explorer/graph-explorer-features.md
> +description: "Graph Explorer features documentation"
The description field specifies what shows up in search results, so you might want a more clear and precise summary. It should be a complete sentence, also, rather than a phrase.

2021-01-27 03:08 UTC, opbld32 commented
Docs Build status updates of commit _[2a3d42e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a3d42eab286a1da6aa5217f821aab4ce0d2a8c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-27 03:12 UTC, opbld30 commented
Docs Build status updates of commit _[dcd3e61](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcd3e618f30eb5c67bacf20d8f27abfbad3c41c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-27 03:14 UTC, opbld34 commented
Docs Build status updates of commit _[c21086e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c21086e01f52e8823aee15d67625be2b26a61c8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-27 03:28 UTC, Lauragra approved these changes

2021-01-27 03:31 UTC, opbld34 commented
Docs Build status updates of commit _[d2b78c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2b78c51c8f9f8d379775b6269f70266147fecb1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-10807) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-10807) (>= graph-rest-1.0) |
[concepts/graph-explorer/graph-explorer-features.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/graph-explorer-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/graph-explorer-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/access-token.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/access-token.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adaptive-cards.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adaptive-cards.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/adding-key-value-pairs.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/adding-key-value-pairs.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/change-theme.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/change-theme.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/code-snippets.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/code-snippets.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-response-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-response-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/expand-collapse-sidebar-component.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/getting-started.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/getting-started.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/graph-toolkit.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/graph-toolkit.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/link-to-m365-dev-program.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/link-to-m365-dev-program.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-non-get-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-non-get-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/making-a-non-get-request.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/making-a-post-request.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/making-a-post-request.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-overview?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/modify-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/modify-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/request-header.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/request-header.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/images/request-header.png?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/select-permissions.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/select-permissions.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/share-query.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/share-query.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/graph-explorer/images/storing-and-sharing-queries.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/graph-explorer/images/storing-and-sharing-queries.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-explorer/graph-explorer-features?branch=pr-en-us-10807) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bengugi/graphexplorer/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/graph-expl [...]

2021-01-27 03:34 UTC, merged