Added details about possible value of capabilityStatus property
microsoftgraph/microsoft-graph-docs pull request #10805
Opened 2020-11-24 18:57 UTC by SumitParikh

2020-11-24 18:59 UTC, opbld32 commented
Docs Build status updates of commit _[6413fa2](https://github.com/SumitParikh/microsoft-graph-docs/commits/6413fa25e5e485acefbaf63bf4539d522c8a15e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-1.0&branch=pr-en-us-10805) (>= graph-rest-1.0) | [Details](#user-content-9d0b062e-6437268d)

<a id="9d0b062e-6437268d"></a>
### [api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011241857590562-10805%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3L%2FW5suSZeVEWHv0zr3PG58SjAoXxNlyrrUr%2FndJwWI%3D&st=2020-11-24T18%3A54%3A26Z&se=2020-12-25T18%3A59%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-24 22:08 UTC, dkershaw10 commented on api-reference/v1.0/resources/assignedplan.md
>  The **assignedPlans** property of both the [user](user.md) entity and the [organization](organization.md) entity is a collection of **assignedPlan**.
You need to add the same update to the same beta topic please.

2020-11-24 22:08 UTC, dkershaw10 commented on api-reference/v1.0/resources/assignedplan.md
>  The **assignedPlans** property of both the [user](user.md) entity and the [organization](organization.md) entity is a collection of **assignedPlan**.
You need to add the same update to the same beta topic please.

2020-11-24 22:08 UTC, dkershaw10 requested changes
Minor update please.  Otherwise LGTM

2020-11-24 23:16 UTC, opbld30 commented
Docs Build status updates of commit _[54a9934](https://github.com/SumitParikh/microsoft-graph-docs/commits/54a9934075a38b0b93aae2c281fb69f5d7d3f0f4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/beta/resources/assignedplan.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-beta&branch=pr-en-us-10805) (graph-rest-beta) | [Details](#user-content-b76d702d-171346c1)
[api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-1.0&branch=pr-en-us-10805) (>= graph-rest-1.0) | [Details](#user-content-9d0b062e-171346c1)

<a id="b76d702d-171346c1"></a>
### [api-reference/beta/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/beta/resources/assignedplan.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9d0b062e-171346c1"></a>
### [api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011242315459369-10805%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OAy0UjrAueVyu2mOIdmDTfQ3mraiCAlTYdVjoR0UewQ%3D&st=2020-11-24T23%3A11%3A54Z&se=2020-12-25T23%3A16%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-11-24 23:17 UTC, SumitParikh commented
Thanks Dan.

I have updated the PR to make sure same change is added in beta assignedplan resource.

Let me know once the review is complete. I can mark the PR for merge ready.

Thanks and Regards,
Sumit Parikh, Senior Program Manager
Microsoft Corporation
M: +1 425.241.5440

From: Dan Kershaw [MSFT] <notifications@github.com>
Sent: Tuesday, November 24, 2020 2:09 PM
To: microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>
Cc: Sumit Parikh <Sumit.Parikh@microsoft.com>; Author <author@noreply.github.com>
Subject: Re: [microsoftgraph/microsoft-graph-docs] Added details about possible value of capabilityStatus property (#10805)


@dkershaw10 requested changes on this pull request.

Minor update please. Otherwise LGTM

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F10805%23pullrequestreview-538007659&data=04%7C01%7CSumit.Parikh%40microsoft.com%7C068df57494874802261f08d890c58116%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418525234013106%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=J5AhQK9uTGeB3WTFW2tdTRCbTtAyiocL0BoFIHdvEgU%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAIYLRGNTTNEI3D42QY2KTZDSRQVGTANCNFSM4UBJAUFQ&data=04%7C01%7CSumit.Parikh%40microsoft.com%7C068df57494874802261f08d890c58116%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637418525234023101%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=qaX5OgwygcbkwUukb56ht4q9cSjal3KOMg45DXjRGqI%3D&reserved=0>.

2020-12-01 19:29 UTC, SumitParikh commented
#sign-off

2020-12-01 19:31 UTC, SumitParikh commented on api-reference/v1.0/resources/assignedplan.md
>  The **assignedPlans** property of both the [user](user.md) entity and the [organization](organization.md) entity is a collection of **assignedPlan**.
Done.

2020-12-01 19:31 UTC, SumitParikh commented on api-reference/v1.0/resources/assignedplan.md
>  The **assignedPlans** property of both the [user](user.md) entity and the [organization](organization.md) entity is a collection of **assignedPlan**.
Done.

2020-12-02 21:05 UTC, opbld32 commented
Docs Build status updates of commit _[60222b0](https://github.com/SumitParikh/microsoft-graph-docs/commits/60222b02dfaf1a978ea4d4b8ebfadfc243276e33)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/beta/resources/assignedplan.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-beta&branch=pr-en-us-10805) (graph-rest-beta) | [Details](#user-content-b76d702d-9acc62a0)
[api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-1.0&branch=pr-en-us-10805) (>= graph-rest-1.0) | [Details](#user-content-9d0b062e-9acc62a0)

<a id="b76d702d-9acc62a0"></a>
### [api-reference/beta/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/beta/resources/assignedplan.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9d0b062e-9acc62a0"></a>
### [api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022104176330-10805%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3hD%2BF%2FOsX0LpzHxmqLjG8jtE7dlQPHLUBG3KX0BMOag%3D&st=2020-12-02T21%3A00%3A45Z&se=2021-01-02T21%3A05%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 21:55 UTC, opbld32 commented
Docs Build status updates of commit _[176ce91](https://github.com/SumitParikh/microsoft-graph-docs/commits/176ce917fda4ce87f9ea286a67c991a1db41ef1d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/beta/resources/assignedplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-beta&branch=pr-en-us-10805) (graph-rest-beta) |
[api-reference/v1.0/resources/assignedplan.md](https://github.com/SumitParikh/microsoft-graph-docs/blob/assigncap/api-reference/v1.0/resources/assignedplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/assignedplan?view=graph-rest-1.0&branch=pr-en-us-10805) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022153457996-10805%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=szsuW7V5MAPcUie0RP63jYxkDYozxFYzOTD%2B8HrHtLo%3D&st=2020-12-02T21%3A50%3A06Z&se=2021-01-02T21%3A55%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 03:28 UTC, angelgolfer-ms approved these changes
Thanks for conforming to guidance!

2020-12-03 04:24 UTC, merged