changes for recurrence properties in V1
microsoftgraph/microsoft-graph-docs pull request #10843
Opened 2020-11-26 17:04 UTC by Bhupesh12Hub

@angelgolfer-ms , please review the PR.

2020-11-26 17:06 UTC, opbld33 commented
Docs Build status updates of commit _[dc998d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc998d88ede624cd137cbd7a73a7c4bdb1243e87)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-a1efde7e)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) |

<a id="de5a61a4-a1efde7e"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C11%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202011261704444777-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zsYwdgHSjbTWxQOa88UOkVXRbZUOMR1vDrjLgHyvD8c%3D&st=2020-11-26T17%3A01%3A08Z&se=2020-12-27T17%3A06%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 05:11 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-get.md
>  ```msgraph-interactive
@Bhupesh12Hub , I think you should keep the original first example which is the basic case, getting a single event by simply specifying its ID. Recurring meetings with these 3 new properties you're GA-ing deserves a more focused example, not convoluting the basic case of getting a single event not as part of a recurring series. 
Then create a separate example that is basically example 4 in the event-get.md topic in beta.

2020-12-03 05:14 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-get.md
>  ```msgraph-interactive
In the separate example, don't forget to mention you're getting an event which is a series master. 
Also your example request should show this query parameter:
$expand=exceptionOccurrences
Without that, what you show in the example response doesn't match the request.

2020-12-03 05:16 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/event.md
> +|cancelledOccurrences|String collection|Contains **occurrenceId** property values of cancelled instances in a recurring series, if the event is the series master. Instances in a recurring series that
Line 67:
Can you please correct the misspelling "cancelledOccurences"? Should be "cancelledOccurrences".
That misspelling is in both the v1 and beta topics.

2020-12-03 05:24 UTC, angelgolfer-ms commented on concepts/changelog.md
GLOBAL:
Please be aware that we are releasing a new changelog experience. For the time being, we're updating both the changelog.md and the corresponding changelog json file for your workload (in your case, that's the Microsoft.Exchange.json file). The changelog json file is in the changelog folder of your branch.
I suggest you search for "cancelledOccurrences" in Microsoft.Exchange.json, see how the ChangeList is specified when the properties were added to beta, and add a similar ChangeList for the v1 version.

CDK topic: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55075/Graph-doc-stub-generator-tool?anchor=update-the-json-changelog

2020-12-03 05:25 UTC, angelgolfer-ms requested changes
Please see my comments, thanks!

2020-12-16 07:17 UTC, opbld33 commented
Docs Build status updates of commit _[6df31ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6df31ab9b6ab63577a4f2755338bb6995b8bfa0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-41d9fee9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-41d9fee9)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |

<a id="de5a61a4-41d9fee9"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-41d9fee9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160715530283-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FA6GXRTr3x2jv0nnxnHnrMn%2B3HJo8RZyGnzokOQki84%3D&st=2020-12-16T07%3A12%3A16Z&se=2021-01-16T07%3A17%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 07:37 UTC, opbld33 commented
Docs Build status updates of commit _[2e5ce25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e5ce2590c420658c496d8f6fcec8d03514e4cce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-634c29af)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-634c29af)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de5a61a4-634c29af"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-634c29af"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160735479581-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RN3m5tFyLPcj0UwSkH58EbHXmjvTqYEN7bLW%2B0kKr9w%3D&st=2020-12-16T07%3A32%3A06Z&se=2021-01-16T07%3A37%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 07:53 UTC, opbld31 commented
Docs Build status updates of commit _[8253271](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82532713ff636537cb6194c36aa94cf72e75f411)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-2a07280a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-2a07280a)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de5a61a4-2a07280a"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-2a07280a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160752020914-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wrDZgblZrkKFAH0jePqDYpTRTFCsFlJKarOY6xDi8MM%3D&st=2020-12-16T07%3A48%3A24Z&se=2021-01-16T07%3A53%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 07:56 UTC, opbld32 commented
Docs Build status updates of commit _[69254e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69254e63c87b18a60b0840c6fa9c8d9f4d639db7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-f363b9b9)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f363b9b9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160755373678-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YOk%2BHj8EINJGu%2FMC755q9phzLRMOkQelFuQzSP4Pqws%3D&st=2020-12-16T07%3A51%3A58Z&se=2021-01-16T07%3A56%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 08:03 UTC, opbld32 commented
Docs Build status updates of commit _[afd1b84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afd1b845610f1cf38c17e92a2b995d3f71eedae9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-9cf39617)
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-9cf39617"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160802054797-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QB8XdZr4tWWDAZj%2BNepXRQBaCJeVN7CqfT8qs1mD8RM%3D&st=2020-12-16T07%3A58%3A22Z&se=2021-01-16T08%3A03%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 08:10 UTC, opbld30 commented
Docs Build status updates of commit _[a01c722](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a01c7228a335760daaaf3a707875595c339cd2d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-6a882359)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-6a882359)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de5a61a4-6a882359"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-6a882359"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160808524236-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qxLiPfZvRS4ZAWrD%2Bq6sHCjbGfJaVnpJ3vjLycrUiIg%3D&st=2020-12-16T08%3A05%3A03Z&se=2021-01-16T08%3A10%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 08:22 UTC, opbld32 commented
Docs Build status updates of commit _[eeeb9b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeeb9b2863c7b056601029f7f929487676b08c5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-394a06b6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-394a06b6)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de5a61a4-394a06b6"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-394a06b6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160821166966-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NTMSvKcw672araGnEbVNBxtiFo6lr0yEd%2FBH%2BwKv1Dc%3D&st=2020-12-16T08%3A17%3A53Z&se=2021-01-16T08%3A22%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 08:27 UTC, opbld33 commented
Docs Build status updates of commit _[54ecc60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54ecc60d0c44152f802c6398074be5dfd6cf33cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-4f03eb9a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-4f03eb9a)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de5a61a4-4f03eb9a"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-4f03eb9a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160826008589-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BATmGPT1%2BRRIl1mTsOCTrxfnAUQofVAtwpkAxTd1ji0%3D&st=2020-12-16T08%3A22%3A10Z&se=2021-01-16T08%3A27%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 08:30 UTC, opbld30 commented
Docs Build status updates of commit _[cd03f76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd03f769e7f2a5cf318f07814e68bd7a65ea68a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-18ab2ee3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) | [Details](#user-content-de0bbbbb-18ab2ee3)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |

<a id="de5a61a4-18ab2ee3"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-18ab2ee3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md)
 - **Line 44, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160828588223-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=etNYLO6ccdWStsQ0DwRRYZkefnUMftQa%2BMX5LEqXYtY%3D&st=2020-12-16T08%3A25%3A08Z&se=2021-01-16T08%3A30%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 12:14 UTC, Bhupesh12Hub commented on api-reference/v1.0/resources/event.md
> +|cancelledOccurrences|String collection|Contains **occurrenceId** property values of cancelled instances in a recurring series, if the event is the series master. Instances in a recurring series that
Done

2020-12-16 12:14 UTC, Bhupesh12Hub commented on concepts/changelog.md
Done

2020-12-16 12:19 UTC, Bhupesh12Hub commented on api-reference/v1.0/api/event-get.md
>  ```msgraph-interactive
Need more clarification, because while performing the above action API doctor is failing.

2020-12-19 02:04 UTC, angelgolfer-ms commented on api-reference/v1.0/api/event-get.md
>  ```msgraph-interactive
@Bhupesh12Hub , what I mean is, in event-get.md in v1:
(1) Revert example 1 to what it is on the live site. 
(2) Add a third example. That example should be essentially the same as [example 4](https://docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-beta&tabs=http#example-4-expand-a-series-master-event) in event-get.md in beta.

Reasons are in my first comment.

2020-12-19 02:27 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +      "CreatedDateTime": "2020-08-01T00:00:00",
Line 17:
Please update the date to reflect more closely when this will get published. The accuracy to the month matters!

2020-12-19 02:31 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +          "Id": "8a32aa94-ac63-42d3-b323-5312bfc80a9d",
Lines 6 and 14:
These 2 GUID values are the same as the ones in lines 42 and 50.
Please use a generator to come up with another GUID and assign the Id in lines 6 and 14 to that GUID.

2020-12-19 02:35 UTC, angelgolfer-ms commented on changelog/Microsoft.Exchange.json
> +          "Description": "Added the **cancelledOccurrences**, **exceptionOccurrences**, and **occurrenceId** properties to the [event](https://docs.microsoft.com/en-us/graph/api/resources/event?view=
Lines 8 and 10:
Even though this approach is technically supported at this point, the owner of the new changelog experience explained that in order for future filtering (which is the reason for the new changelog) to work as designed, technically ChangedApiName should specify only one new property at a time.
That means you'd have 3 changelist records, instead of one, like now.
To give a consistent experience for customers, and let the feature owner determine if there's cause for changing the filtering design, I'd suggest you follow that and break this up to 3 separate changelist records.

2020-12-19 02:36 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | v1 | Added the **cancelledOccurrences**, **exceptionOccurrences**, and **occurrenceId** properties to the [event](/graph/api/resources/event?view=graph-rest-1.0&preserve-view=true) entit
Since this is the last day to publish this year and you still need to fix the example in event-get.md, please update changelog.md to surface this change under January 2021.

2020-12-19 02:39 UTC, angelgolfer-ms requested changes
@Bhupesh12Hub , I responded to your question and gave a few more comments. 
Please take a look. 
Looking back, this is a simple PR, in the future, we should try to tighten the iterations. Feel free to message me on Teams. I do get many Github notifications each day, so relying on Github alone to communicate is not efficient.

2021-01-19 12:56 UTC, opbld33 commented
Docs Build status updates of commit _[0fb9f5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0fb9f5ada9679e378c1b725499526856a1295771)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/event-get?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) | [Details](#user-content-de5a61a4-f4d9bc16)
[api-reference/v1.0/resources/event.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/resources/event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/event?view=graph-rest-1.0&branch=pr-en-us-10843) (>= graph-rest-1.0) |
[changelog/Microsoft.Exchange.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/changelog/Microsoft.Exchange.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10843) |

<a id="de5a61a4-f4d9bc16"></a>
### [api-reference/v1.0/api/event-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/feature/recurrenceProperties/v1/api-reference/v1.0/api/event-get.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Get event - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/event-get.md(2,8), v1.0/api/group-get-event.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Get event' is duplicated with other articles: 'v1.0/api/event-get.md(10,1), v1.0/api/group-get-event.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101191254481283-10843%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XaTAaxBob6MP5T%2FOLfiGOs%2BKtQG4ZBQn84lULpfQ%2Bp8%3D&st=2021-01-19T12%3A51%3A06Z&se=2021-02-19T12%3A56%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 19:01 UTC, closed without merging