Add permission check related enum members
microsoftgraph/microsoft-graph-docs pull request #10871
Opened 2020-12-01 07:11 UTC by AshleyYangSZ

Add 4 permission check related enum members

2020-12-01 07:12 UTC, opbld34 commented
Docs Build status updates of commit _[95ca0e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95ca0e7ca8f45efb35124ef9ead894bcec976f39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012010711111194-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3%2B6MQRFrgHuU2UhMfbYxTPCKjG6nxxte%2BJGehBzv4Ws%3D&st=2020-12-01T07%3A07%3A22Z&se=2021-01-01T07%3A12%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 08:27 UTC, opbld34 commented
Docs Build status updates of commit _[ab0712f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab0712fae5a7955e3683381976c0eb8a7d4042d2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080825218752-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4qW9a6Kf5rBIsYcp5btkivWgNWgXVNiSiAB%2FQP%2BaeDg%3D&st=2020-12-08T08%3A22%3A14Z&se=2021-01-08T08%3A27%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 08:41 UTC, opbld31 commented
Docs Build status updates of commit _[137a269](https://github.com/microsoftgraph/microsoft-graph-docs/commits/137a269bdf67848152c01a0eb72ce5e76917a1e7)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-08 08:42 UTC, opbld34 commented
Docs Build status updates of commit _[137a269](https://github.com/microsoftgraph/microsoft-graph-docs/commits/137a269bdf67848152c01a0eb72ce5e76917a1e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080841346574-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0uHObil688DCy93izgwBUvCZsnBL6EsbN36t6Y8UQFk%3D&st=2020-12-08T08%3A37%3A50Z&se=2021-01-08T08%3A42%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 08:49 UTC, opbld33 commented
Docs Build status updates of commit _[cb1dd2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb1dd2a61a90596d171ae3958295844025a15e72)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-08 08:50 UTC, opbld32 commented
Docs Build status updates of commit _[cb1dd2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb1dd2a61a90596d171ae3958295844025a15e72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-updateaddomainpassword.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-updateaddomainpassword?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080849224477-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XVymardNMC1cPZd1%2Bynlo8hIYJRkQjiE6Toiy9bQ4tM%3D&st=2020-12-08T08%3A45%3A39Z&se=2021-01-08T08%3A50%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 08:31 UTC, opbld32 commented
Docs Build status updates of commit _[8937e48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8937e48f547aef428e34e651b5ba5651a75fe33f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012110830130412-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JMv7TqZjjs4g6JoBCl%2FgDbeOCI2TNkWpsQFvGzcoa8g%3D&st=2020-12-11T08%3A26%3A29Z&se=2021-01-11T08%3A31%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 09:22 UTC, opbld34 commented
Docs Build status updates of commit _[0b3e056](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b3e05619d70943d63c8dabab777c514ac112750)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-d829e687)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d829e687"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 48, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012110921148607-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4qlv%2BQqNEGFHmSL6Yz%2BKdABuhrWEguAeEJKAFziaiy4%3D&st=2020-12-11T09%3A17%3A39Z&se=2021-01-11T09%3A22%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 09:33 UTC, timefrozen19 approved these changes

2020-12-15 02:29 UTC, Lauragra commented on api-reference/beta/resources/enums.md
> +|failed|
Please be sure to update the values listed for this type in the cloudPC resource topic.

2020-12-15 03:03 UTC, Lauragra commented on concepts/changelog.md
> +### Devices and apps | Cloud PC
Please make sure that the H3 sections are alphabetized per month.

2020-12-15 03:04 UTC, Lauragra commented on concepts/changelog.md
> +|Addition|beta|Added the `failed` member to the **cloudPcStatus** enumeration|
It might be more readable to describe this in a single row, listing the added and removed enum values. Please be sure to add the period at the end of the sentence.

2020-12-15 03:05 UTC, Lauragra commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "97ae5c09-3b8e-11eb-822d-0179b911e3f8",
Do you want separate table rows for each value, or one row to list added and removed values? Either way please make sure that you add periods to the end of the sentences.

2020-12-15 06:21 UTC, AshleyYangSZ commented on api-reference/beta/resources/enums.md
> +|failed|
Good catch. Really missed it. Thanks!

2020-12-15 06:21 UTC, opbld31 commented
Docs Build status updates of commit _[76564fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76564fe7590102b108a18d9755efda0451aca379)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9019a92f)

<a id="9019a92f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150620571724-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s0Jq%2BCQRaNJ%2FnuR82r2yEuvb3EbYOZwLX58OO7gZI5E%3D&st=2020-12-15T06%3A16%3A15Z&se=2021-01-15T06%3A21%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 06:23 UTC, AshleyYangSZ commented on concepts/changelog.md
> +### Devices and apps | Cloud PC
Updated.

2020-12-15 06:25 UTC, AshleyYangSZ commented on concepts/changelog.md
> +|Addition|beta|Added the `failed` member to the **cloudPcStatus** enumeration|
Put 4 "remove" row to one row. As it's generated by the tool, I left it as it is. And the period missed issue may be a tool bug?

2020-12-15 06:26 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "97ae5c09-3b8e-11eb-822d-0179b911e3f8",
I prefer one row and already updated.

2020-12-15 06:33 UTC, opbld31 commented
Docs Build status updates of commit _[55e507c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55e507c5a0b112eae74bb316196114191a8d604a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-33494683)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-33494683"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150632166899-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7KeLr9%2FIK2i37BWBwopOI0fLE2g3ZABRRCQMAkaf2Ck%3D&st=2020-12-15T06%3A28%3A43Z&se=2021-01-15T06%3A33%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 18:06 UTC, opbld31 commented
Docs Build status updates of commit _[d17fd19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d17fd1967afe7e22551de8c285a8a757114785c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-0049bff6)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-0049bff6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151805326330-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y6qSps3qWWzy9MoXlD3zAQHpZ%2FZ4CUxt3As%2B3iZkdw4%3D&st=2020-12-15T18%3A01%3A47Z&se=2021-01-15T18%3A06%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 02:58 UTC, Lauragra approved these changes

2020-12-16 04:01 UTC, angelgolfer-ms commented on concepts/changelog.md
> +|Deletion|beta|Removed the `upgradeFailed`,`provisionFailed`, `deprovisionFailed`, `reprovisionFailed` member from the **cloudPcStatus** enumeration.|
Line 48:
Please say plural "members".

2020-12-16 05:56 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Target": "cloudPcStatus"
Line 10:
On a recent email communication with @paulodero , he indicated that the value for "Target" must be a resource name.
To follow that rule, in this PR, I think we need to do this:
"ApiChange": "enum type",
"ChangedApiName": "cloudPcStatus",
"ChangeType": "Addition",
"Description": "Added the enum value `failed` to the **cloudPcStatus** enumeration used in the **cloudPc** entity."
"Target": "cloudPc"

@paulodero , it would be helpful if you can confirm this suggestion. Thanks in advance.

2020-12-16 06:03 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "97b31fed-3b8e-11eb-822d-0179b911e3f8",
Lines 5, 10 and 19:
In other existing changelog json files that were generated, I got the impression that the id values that belong to the same ChangeList collection and the changelog item should all have the same GUID value.
Please do the same here.

2020-12-16 06:05 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +            }],
Lines 13-17:
Depending on @paulodero 's confirmation for lines 6-10, @AshleyYangSZ , you might have to apply a similar approach for this changelog item please.

2020-12-16 06:06 UTC, angelgolfer-ms requested changes
Two comments currently actionable in changelog.md, and in changelog json about the GUID values. Two other comments about specifying the different fields in the changelog json depend on Paul's confirmation. Please keep an eye on the latter and make appropriate adjustments.

2020-12-16 06:07 UTC, AshleyYangSZ commented on changelog/Microsoft.CloudManagedDesktop.json
> +            }],
Got it! Thanks @angelgolfer-ms for helping us confirm this. I just copy the generated changelog here. Will update now.

2020-12-16 06:27 UTC, opbld30 commented
Docs Build status updates of commit _[b9ec617](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9ec61710ce0e7c669716bd546a58ee45a6953ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-4cb2339d)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4cb2339d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160626110596-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MqwpYUF6Ys76cbbZgHFWjHQ5%2FVTG5WAa80TvySFcrfA%3D&st=2020-12-16T06%3A22%3A23Z&se=2021-01-16T06%3A27%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 06:32 UTC, opbld30 commented
Docs Build status updates of commit _[4a0bcef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a0bcef63b440e6d7fb187ca78bf07bee392389b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-3d9d27ff)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3d9d27ff"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160631239554-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dBzVDEEI1hWWJfDMp9%2BRe0g4edgt%2FdbhB8peXBfGn98%3D&st=2020-12-16T06%3A27%3A43Z&se=2021-01-16T06%3A32%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 06:41 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Id": "97b31fed-3b8e-11eb-822d-0179b911e3f8",
@paulodero , can you confirm if lines 5,12, 19 should use the same GUID value?

2020-12-16 11:37 UTC, opbld31 commented
Docs Build status updates of commit _[706c9df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/706c9dfc174ff501cb6e9a2941165b0b4bf42540)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-c62b5ec3)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c62b5ec3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012161136155309-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eL1qwqxzc2mC9o%2FP1YVaumLQuLYv0J0Z%2F93akvNVE38%3D&st=2020-12-16T11%3A32%3A26Z&se=2021-01-16T11%3A37%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 03:37 UTC, opbld30 commented
Docs Build status updates of commit _[c30ec67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c30ec675a267082320b09c1d9ae5d69d23db7908)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10871) | [Details](#user-content-de0bbbbb-7d97f404)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10871) (graph-rest-beta) |
[changelog/Microsoft.CloudManagedDesktop.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/changelog/Microsoft.CloudManagedDesktop.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7d97f404"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/addEnumTypes/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 74, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170335582976-10871%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i2zISpjOkWwpNWx2aPHwHtZvVBEd8bMxcRMz3xDGJQI%3D&st=2020-12-17T03%3A32%3A18Z&se=2021-01-17T03%3A37%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 04:42 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +                "Target": "cloudPcStatus"
Looping back: Paul confirmed that there was miscommunication and "Target" can be a resource name, enum name, or method name, depending on the API update.
So that makes my last comment inappropriate and unnecessary..

2020-12-17 04:42 UTC, angelgolfer-ms commented on changelog/Microsoft.CloudManagedDesktop.json
> +            }],
Looping back: Paul confirmed that there was miscommunication and "Target" can be a resource name, enum name, or method name, depending on the API update.
So that makes my last comment inappropriate and unnecessary..

2020-12-17 04:44 UTC, angelgolfer-ms approved these changes
PR looks good to me!

2020-12-17 05:20 UTC, merged