Add preview boilerplate
microsoftgraph/microsoft-graph-docs pull request #10879
Opened 2020-12-02 06:23 UTC by AshleyYangSZ

2020-12-02 06:25 UTC, opbld32 commented
Docs Build status updates of commit _[39081f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39081f3cf804916cf9b294f4d32bceb7929d61b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-05abcc44-7fb0de17)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-0d1a35ef-7fb0de17)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-7fb0de17)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-607d042d-7fb0de17)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-2a246ca2-7fb0de17)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b58c4631-7fb0de17)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc9bce1c-7fb0de17)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-496333a2-7fb0de17)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b29ee0f7-7fb0de17)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dba05553-7fb0de17)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc8757d1-7fb0de17)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-117b7a2d-7fb0de17)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-5e600f2f-7fb0de17)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9290d014-7fb0de17)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-ab8d5133-7fb0de17)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-44ba799e-7fb0de17)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9cfcf849-7fb0de17)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9d118271-7fb0de17)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review. [...]

2020-12-02 08:06 UTC, opbld34 commented
Docs Build status updates of commit _[8eaa430](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8eaa4307e7b6a3e82e9b502e2eb46d1290803fd0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-05abcc44-e96ffb3f)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-0d1a35ef-e96ffb3f)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-e96ffb3f)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-607d042d-e96ffb3f)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-2a246ca2-e96ffb3f)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b58c4631-e96ffb3f)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc9bce1c-e96ffb3f)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-496333a2-e96ffb3f)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b29ee0f7-e96ffb3f)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dba05553-e96ffb3f)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc8757d1-e96ffb3f)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-117b7a2d-e96ffb3f)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-5e600f2f-e96ffb3f)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9290d014-e96ffb3f)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-ab8d5133-e96ffb3f)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-44ba799e-e96ffb3f)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9cfcf849-e96ffb3f)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9d118271-e96ffb3f)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review. [...]

2020-12-03 02:45 UTC, opbld32 commented
Docs Build status updates of commit _[65154d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65154d53db28ffd767de90b7981aa95a6ba3d786)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-05abcc44-0e134ca0)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-0d1a35ef-0e134ca0)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-0e134ca0)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-607d042d-0e134ca0)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-2a246ca2-0e134ca0)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b58c4631-0e134ca0)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc9bce1c-0e134ca0)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-496333a2-0e134ca0)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b29ee0f7-0e134ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dba05553-0e134ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc8757d1-0e134ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-117b7a2d-0e134ca0)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-5e600f2f-0e134ca0)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9290d014-0e134ca0)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-ab8d5133-0e134ca0)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-44ba799e-0e134ca0)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9cfcf849-0e134ca0)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9d118271-0e134ca0)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review. [...]

2020-12-03 03:17 UTC, Lauragra approved these changes

2020-12-03 03:18 UTC, opbld31 commented
Docs Build status updates of commit _[849669d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/849669dc339ad9535d714cf2b79d5ac6ea990cd7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-05abcc44-1d3f87c3)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-0d1a35ef-1d3f87c3)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-1d3f87c3)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-607d042d-1d3f87c3)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-2a246ca2-1d3f87c3)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b58c4631-1d3f87c3)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc9bce1c-1d3f87c3)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-496333a2-1d3f87c3)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b29ee0f7-1d3f87c3)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dba05553-1d3f87c3)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc8757d1-1d3f87c3)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-117b7a2d-1d3f87c3)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-5e600f2f-1d3f87c3)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9290d014-1d3f87c3)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-ab8d5133-1d3f87c3)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-44ba799e-1d3f87c3)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9cfcf849-1d3f87c3)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9d118271-1d3f87c3)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review. [...]

2020-12-03 03:24 UTC, opbld32 commented
Docs Build status updates of commit _[b7dd159](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7dd15907069e2d15b28404ea561389815bbc975)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-05abcc44-11e6f363)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-0d1a35ef-11e6f363)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-11e6f363)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-607d042d-11e6f363)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-2a246ca2-11e6f363)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b58c4631-11e6f363)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc9bce1c-11e6f363)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-496333a2-11e6f363)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b29ee0f7-11e6f363)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dba05553-11e6f363)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc8757d1-11e6f363)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-117b7a2d-11e6f363)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-5e600f2f-11e6f363)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9290d014-11e6f363)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-ab8d5133-11e6f363)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-44ba799e-11e6f363)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9cfcf849-11e6f363)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9d118271-11e6f363)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review. [...]

2020-12-03 03:54 UTC, angelgolfer-ms commented on api-reference/includes/cloudpc-api-preview.md
> +> The cloud PC API is in private preview and is currently available only to a select group of customers. Please contact your Modern Workplace GBBs for more information.
@AshleyYangSZ , please use this boilerplate and avoid using the term "private preview", because we generally do not publish docs for APIs in private preview.
"The cloud PC API is currently in preview status and is available to selected customers. For more information, please contact your Modern Workplace GBBs."

2020-12-03 03:59 UTC, angelgolfer-ms requested changes
Please see suggested text in my comment. Thanks!

2020-12-03 04:23 UTC, opbld32 commented
Docs Build status updates of commit _[70fe078](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70fe078904fd8489daaa1d84bf3784102f001c09)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudpc-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-05abcc44-0053b4b7)
[api-reference/beta/api/cloudpc-reprovision.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpc-reprovision.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpc-reprovision?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-0d1a35ef-0053b4b7)
[api-reference/beta/api/cloudpcdeviceimage-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dbd6a2cf-0053b4b7)
[api-reference/beta/api/cloudpcdeviceimage-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-607d042d-0053b4b7)
[api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcdeviceimage-getsourceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcdeviceimage-getsourceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-2a246ca2-0053b4b7)
[api-reference/beta/api/cloudpconpremisesconnection-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b58c4631-0053b4b7)
[api-reference/beta/api/cloudpconpremisesconnection-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc9bce1c-0053b4b7)
[api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-runhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-runhealthcheck?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-496333a2-0053b4b7)
[api-reference/beta/api/cloudpconpremisesconnection-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpconpremisesconnection-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpconpremisesconnection-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-b29ee0f7-0053b4b7)
[api-reference/beta/api/cloudpcprovisioningpolicy-assign.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-assign.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-assign?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-dba05553-0053b4b7)
[api-reference/beta/api/cloudpcprovisioningpolicy-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-delete?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-bc8757d1-0053b4b7)
[api-reference/beta/api/cloudpcprovisioningpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-get?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-117b7a2d-0053b4b7)
[api-reference/beta/api/cloudpcprovisioningpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/cloudpcprovisioningpolicy-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudpcprovisioningpolicy-update?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-5e600f2f-0053b4b7)
[api-reference/beta/api/virtualendpoint-geteffectivepermissions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-geteffectivepermissions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-geteffectivepermissions?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9290d014-0053b4b7)
[api-reference/beta/api/virtualendpoint-list-cloudpcs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-cloudpcs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-cloudpcs?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-ab8d5133-0053b4b7)
[api-reference/beta/api/virtualendpoint-list-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-deviceimages.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-deviceimages?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-44ba799e-0053b4b7)
[api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-onpremisesconnections.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-onpremisesconnections?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9cfcf849-0053b4b7)
[api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-list-provisioningpolicies.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/virtualendpoint-list-provisioningpolicies?view=graph-rest-beta&branch=pr-en-us-10879) (graph-rest-beta) | [Details](#user-content-9d118271-0053b4b7)
[api-reference/beta/api/virtualendpoint-post-deviceimages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/addbanner/api-reference/beta/api/virtualendpoint-post-deviceimages.md) | :warning:Warning | [View](https://review. [...]

2020-12-03 04:29 UTC, merged