Adding TAP policy config, get, delete and update
microsoftgraph/microsoft-graph-docs pull request #10886
Opened 2020-12-02 17:49 UTC by InbarckMS

Adding policy details (resource and APIs)

2020-12-02 17:51 UTC, opbld34 commented
Docs Build status updates of commit _[3cd76b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3cd76b8cc9cfde28831891c7ffb47de56376af64)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-ef02ce9f-3b6d0e16)
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-3b6d0e16)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

<a id="ef02ce9f-3b6d0e16"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '*inbarckms' is not a valid GitHub ID.`````

<a id="8d7401bc-3b6d0e16"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON representation') are not allowed. You can only have one top-level heading.`````
 - **Line 42, Column 1**: **[Suggestion-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```). NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012021749376607-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TCTuzb81pVQj%2FyZRXoSRw%2FB0dwq5Fk7k4vUsi06YqJU%3D&st=2020-12-02T17%3A46%3A05Z&se=2021-01-02T17%3A51%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 18:05 UTC, opbld33 commented
Docs Build status updates of commit _[130945e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/130945e074c9b0df0c1674a552cd8d6ba118cf35)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-ef02ce9f-0a517726)
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-0a517726)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

<a id="ef02ce9f-0a517726"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '*inbarckms' is not a valid GitHub ID.`````

<a id="8d7401bc-0a517726"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON representation') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012021804053249-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sn0YkC%2B49yjJFLVPzfzNyitr46L4Xv5QeymNL2cBTz0%3D&st=2020-12-02T18%3A00%3A17Z&se=2021-01-02T18%3A05%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:22 UTC, opbld31 commented
Docs Build status updates of commit _[d00e990](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d00e990ef26a2a5afce62a6daaf06a95180483bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-c38d290a)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

<a id="8d7401bc-c38d290a"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON representation') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022221231121-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FuZ7lF2wTqjF1V0XTs07TpDroCtQZUjqCXnrL4o3uM4%3D&st=2020-12-02T22%3A17%3A50Z&se=2021-01-02T22%3A22%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:28 UTC, opbld33 commented
Docs Build status updates of commit _[30b9917](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30b9917c70f0c49c8a4bb3cb5f9bd42c813d9e2f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-2b931128)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

<a id="8d7401bc-2b931128"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON representation') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022226447201-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5OQ8FFZwYYPEaUzrCJoRBZ5Em9e%2BRowWZ3tOh4lCUj0%3D&st=2020-12-02T22%3A23%3A05Z&se=2021-01-02T22%3A28%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:31 UTC, opbld30 commented
Docs Build status updates of commit _[b5d37e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5d37e6ed54aca2b7f11e29d795bf5c4408a92f9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-258f6611)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

<a id="8d7401bc-258f6611"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON representation') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022230231308-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=53kH%2Fgu86guXjWx9UAYMCbAydKZUWF0Upe9BoaYvQS0%3D&st=2020-12-02T22%3A26%3A41Z&se=2021-01-02T22%3A31%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:41 UTC, andres-canello approved these changes

2020-12-02 22:41 UTC, opbld30 commented
Docs Build status updates of commit _[405a1e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/405a1e7b5bc60d193bff9fba422a0c61883c3c9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-698a8543)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

<a id="8d7401bc-698a8543"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'JSON representation') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022240394893-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wFzpUFzAwe1NQWP37zevGskb66mRFxw0%2FdxUnYU3d0g%3D&st=2020-12-02T22%3A36%3A50Z&se=2021-01-02T22%3A41%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-02 22:44 UTC, andres-canello approved these changes

2020-12-02 22:45 UTC, opbld30 commented
Docs Build status updates of commit _[8b44748](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b44748fa4510134c7f46ab1307e94ff67b1f7c4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012022244425321-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nMUX6EyjGgt7K5iJjP1xj2LCogVmJnNEsvdFKWcvQSQ%3D&st=2020-12-02T22%3A40%3A55Z&se=2021-01-02T22%3A45%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 07:27 UTC, opbld34 commented
Docs Build status updates of commit _[1ac6546](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ac6546ca7df7165c48c487861a27f594df22f85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090726071022-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aZksA%2BTPVymdoWDwRnnK7SKQk2mvEWOK35xDt0jhLZk%3D&st=2020-12-09T07%3A22%3A25Z&se=2021-01-09T07%3A27%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 00:31 UTC, opbld33 commented
Docs Build status updates of commit _[b0d0f72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0d0f72381f3e47a28d2f6df70592d75e460da6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100030174380-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1%2BKtAKRwUxJcXGTDuGOLJn8DlnaXeW4JdvIjUBn2zmY%3D&st=2020-12-10T00%3A26%3A36Z&se=2021-01-10T00%3A31%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 19:46 UTC, opbld33 commented
Docs Build status updates of commit _[42ace37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42ace3753e1682b9150a885bdd9dc11362332429)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f28a89e8)

<a id="f28a89e8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012161945437889-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7sLmhMGh0zT3kWtNNNjqUR%2BdShn6GOuHaVo%2FnSrtnrs%3D&st=2020-12-16T19%3A41%3A01Z&se=2021-01-16T19%3A46%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 21:18 UTC, opbld30 commented
Docs Build status updates of commit _[fcbe727](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fcbe7278e95c2e453534ade5db5754182ba778e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-00685cff-38bc9a7d)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-38bc9a7d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml)
 - **Line 10286, Column 21**: **[Warning-file-not-found]** `````Invalid file link: 'api/temporaryaccesspassauthenticationmethodconfiguration-get.md.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162116598508-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vXB7lja%2BIKmjjspkd4HdZu%2BDvccBohQsXczNkWJiYRc%3D&st=2020-12-16T21%3A13%3A13Z&se=2021-01-16T21%3A18%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 21:45 UTC, opbld32 commented
Docs Build status updates of commit _[edd29ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/edd29ffc4d205cbf418fe81c9846d9060466338c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-00685cff-1602c38d)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-1602c38d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml)
 - **Line 10286, Column 21**: **[Warning-file-not-found]** `````Invalid file link: 'api/temporaryaccesspassauthenticationmethodconfiguration-get.md.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162143518310-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qI2055hN4PqToCpX7AsOji8536AoSK85ESy01P3s4H4%3D&st=2020-12-16T21%3A40%3A01Z&se=2021-01-16T21%3A45%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 21:47 UTC, andres-canello approved these changes

2020-12-17 02:33 UTC, opbld30 commented
Docs Build status updates of commit _[8b3c583](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b3c583de8cfc616a85bd238f7eb987ecdfb8c66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170232045347-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BYfWwYXu3ehkRXDTdoz4IBIpRVhnJiJ4cOgLKbIdR44%3D&st=2020-12-17T02%3A28%3A25Z&se=2021-01-17T02%3A33%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 20:10 UTC, mmcla commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
> +
Extra blank line

2021-01-25 20:13 UTC, mmcla commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md
> +Represents a Temporary Access Pass authentication methods policy. Authentication methods policies define configuration settings and users or groups who are enabled to use the authentication method.
Make "Authentication methods policies" singular - there's only 1 per tenant

2021-01-25 20:14 UTC, mmcla requested changes
Couple minor comments, and please add TAP to the overview too: https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta

2021-01-26 19:56 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
> +* Global admin
If there is only one, it is better to just use a sentence:  For delegated scenarios, the administrator needs the Global admin role. For more information, see [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles).

2021-01-26 19:58 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +Read the properties and relationships of a [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md) object, which represents the Te
I don't think temporary access pass should be capitalized.

2021-01-26 19:58 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-26 19:58 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-26 19:59 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +For delegated scenarios the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Same comment.

2021-01-26 20:00 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +    "defaultLifetimeInMinutes": Integer,
Should be a realistic looking value.

2021-01-26 20:01 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-26 20:01 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +For delegated scenarios, the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Same comment.

2021-01-26 20:02 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +For the list of properties that can be updated, see [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md).
So we are saying that all properties of the object can be updated?

2021-01-26 20:02 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +  "defaultLifetimeInMinutes": "Integer",
Real value.

2021-01-26 20:02 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +  "isUsableOnce": "Boolean"
Real value.

2021-01-26 20:03 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +    "isUsableOnce": Boolean,
Real value.

2021-01-27 17:54 UTC, opbld33 commented
Docs Build status updates of commit _[1d4c364](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d4c36440193fba67b9e2789d8b81ff678b54172)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101271752477090-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=70jZNR2HaGtRN8q39Os1YlIrGWuOVAFzwEYTKSs87JI%3D&st=2021-01-27T17%3A49%3A00Z&se=2021-02-27T17%3A54%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 17:58 UTC, InbarckMS commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +Read the properties and relationships of a [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md) object, which represents the Te
We gone through the naming process and since it is an official name we are using Temporary Access Pass everywhere.

2021-01-27 18:00 UTC, opbld31 commented
Docs Build status updates of commit _[2cbd2e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cbd2e3a824035a9a8eafa06b83e8fedc83d8c4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101271759239743-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vpR%2FoemDeiELDjQgOLbrmDuVuw6Nrd5Qnyagh3zitYk%3D&st=2021-01-27T17%3A55%3A38Z&se=2021-02-27T18%3A00%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 18:02 UTC, opbld34 commented
Docs Build status updates of commit _[cc6deef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc6deefc6856e616a68b094d7676fb1597008355)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101271759348946-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=42Se2Pk76ZDJmzaTecKeyzwuE3mEZWWu21CuVeK4Dxk%3D&st=2021-01-27T17%3A57%3A26Z&se=2021-02-27T18%3A02%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:30 UTC, InbarckMS commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +For the list of properties that can be updated, see [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md).
Yes, should we write this differently?

2021-01-27 23:32 UTC, opbld33 commented
Docs Build status updates of commit _[1b31244](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1b312449a340794b97ddb195a17658851464d299)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272330058165-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UYZVIEPCnahcK9EJfeSCds3FBjOgzJyP9dhBCJGV0Og%3D&st=2021-01-27T23%3A27%3A42Z&se=2021-02-27T23%3A32%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:35 UTC, opbld30 commented
Docs Build status updates of commit _[1c3f492](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c3f492be099d24025429b27c77ae3cf890fb0df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272330224994-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rI%2BOx0HO4EZ8AsqsvhZOgXRPGDFsVVf7bCnVS2iDfPM%3D&st=2021-01-27T23%3A29%3A59Z&se=2021-02-27T23%3A34%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:37 UTC, opbld34 commented
Docs Build status updates of commit _[b03380f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b03380f51139ed7830f543f0c8190b2b44b54cd2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272335515413-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f2rskADrNxFLuBuLNco9RCHb7hYnR5Ot0IN4LRMosk4%3D&st=2021-01-27T23%3A32%3A24Z&se=2021-02-27T23%3A37%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:40 UTC, opbld31 commented
Docs Build status updates of commit _[640e338](https://github.com/microsoftgraph/microsoft-graph-docs/commits/640e33834457c6af00bf49e3a2342c570e14aa5f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272337485478-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F2vXoWPFX8iijk5P9fcb1TAEcjoWGnS31zcPFJtJCEw%3D&st=2021-01-27T23%3A35%3A06Z&se=2021-02-27T23%3A40%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:54 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md
> +Read the properties and relationships of a [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md) object, which represents the Te
ok.

2021-01-27 23:55 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md
> +For the list of properties that can be updated, see [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md).
Might be better to say "All properties of the object can be updated. For a list of properties, see [temporaryAccessPassAuthenticationMethodConfiguration](../resources/temporaryaccesspassauthenticationmethodconfiguration.md).

2021-01-27 23:56 UTC, davidmu1 approved these changes

2021-01-29 01:15 UTC, opbld31 commented
Docs Build status updates of commit _[9bff30f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9bff30fcd1cdbd3bf36ef77be951eb8c1b6f6aad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290113176765-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fh3GaZV483kVgwKze%2F6DME43TQkkBzu7rcHHgYT1%2F1c%3D&st=2021-01-29T01%3A10%3A20Z&se=2021-03-01T01%3A15%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 01:24 UTC, opbld30 commented
Docs Build status updates of commit _[206580c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/206580c46eef43cb71b841aad179c16a4a7e3330)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f369e3f5)

<a id="f369e3f5"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290123277672-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FBkG8RO8OlQkxZQPzqKTkBMUVgZuSWp8K%2FxpJZQ3CY4%3D&st=2021-01-29T01%3A19%3A36Z&se=2021-03-01T01%3A24%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 02:37 UTC, opbld32 commented
Docs Build status updates of commit _[5e73b69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e73b6968bc29e88f735ec1760cd54314dec3eb2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-3703c1da-cbd28be4)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="3703c1da-cbd28be4"></a>
### [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethods-overview.md)
 - **Line 40, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'temporaryaccesspassauthenticationmethod.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290235488442-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gYbTllGlwLrq%2FBjVpWrCRXWqHZfJGkj3njl6%2FooRqt8%3D&st=2021-01-29T02%3A32%3A56Z&se=2021-03-01T02%3A37%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 02:47 UTC, opbld33 commented
Docs Build status updates of commit _[a87cf85](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a87cf8591ee0848e972f7ab443df7fda03fc99e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290246168209-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bN1pWtslUQMAkP9wOExf%2FzhphrC2HBGHAiKsIi58uf4%3D&st=2021-01-29T02%3A42%3A22Z&se=2021-03-01T02%3A47%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 05:29 UTC, andres-canello approved these changes

2021-01-29 05:29 UTC, andres-canello commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
> +
Done

2021-01-29 05:29 UTC, andres-canello commented on api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md
> +|Permission type|Permissions (from most to least privileged)|
Done

2021-01-29 05:30 UTC, opbld33 commented
Docs Build status updates of commit _[92c342c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92c342c48e5aeb96b215df7afbc0f44f36e87469)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290528455617-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FzrykdOX3aUy2vlS9Bh42RNVxzAPxdnJnca4L1lVybM%3D&st=2021-01-29T05%3A25%3A04Z&se=2021-03-01T05%3A30%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 19:57 UTC, mmcla approved these changes

2021-02-12 01:24 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +        {
Instead of adding an item to an existing ChangeList entry, create a new ChangeList entry for this change. Otherwise this change will get added to a list of changes from last October.

2021-02-12 01:31 UTC, opbld32 commented
Docs Build status updates of commit _[05421dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05421dc88aafa6902c13fbd9b5cbb1c95b0b5dee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa55d9df)

<a id="aa55d9df"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delays. You might have content issues that were not reported. To retry validation, close and re-open your PR, or rebuild your branch via Docs Portal (requires admin permissions). If you need admin help or if you continue to see this message, file an issue via https://SiteHelp.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120120477972-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8TcJr18hWwPcGDhIPODnrLJ0In3P0a%2F9ncviWvH9wVk%3D&st=2021-02-12T01%3A26%3A31Z&se=2021-03-15T01%3A31%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-14 23:12 UTC, opbld30 commented
Docs Build status updates of commit _[d14c023](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d14c023893619d5acdf5a1965e994c1acc6d94f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-ef02ce9f-9a46f9ec)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-5bb2eb03-9a46f9ec)
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-3fc96fb3-9a46f9ec)
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-ee3beb28-9a46f9ec)
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) | [Details](#user-content-8d7401bc-9a46f9ec)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="ef02ce9f-9a46f9ec"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5bb2eb03-9a46f9ec"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="3fc96fb3-9a46f9ec"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ee3beb28-9a46f9ec"></a>
### [api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethodspolicies-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="8d7401bc-9a46f9ec"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142311250228-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VJHbLSuOrTBl1mHvVOZvsy%2FPP15ebh3GvXPBZx7X%2Bgo%3D&st=2021-02-14T23%3A07%3A51Z&se=2021-03-17T23%3A12%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</ [...]

2021-02-14 23:17 UTC, opbld31 commented
Docs Build status updates of commit _[b4cf18a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4cf18a10bd2a058d52d68afea50bcbdf87f65a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/api/temporaryaccesspassauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/resources/temporaryaccesspassauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10886) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/TAPPolicyChanges_20201202/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142316025840-10886%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2AQAUw9nG9ctZMBdF0Pz5T12xTqfyKufotvepFAPZHU%3D&st=2021-02-14T23%3A12%3A17Z&se=2021-03-17T23%3A17%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 19:01 UTC, closed without merging