Add todo docs
microsoftgraph/microsoft-graph-docs pull request #10903
Opened 2020-12-03 05:29 UTC by beth-panx

2020-12-03 05:31 UTC, opbld33 commented
Docs Build status updates of commit _[0b8927a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b8927a5707091e45cee1a296771b417c71f3824)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) | [Details](#user-content-d5345b08-51a93c83)
[concepts/data-connect-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/data-connect-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/data-connect-overview?branch=pr-en-us-10903) | [Details](#user-content-278bface-51a93c83)
[api-reference/beta/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/api-reference/beta/api/accesspackagecatalog-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackagecatalog-get?view=graph-rest-beta&branch=pr-en-us-10903) (graph-rest-beta) | [Details](#user-content-0e8edd8c-51a93c83)

<a id="d5345b08-51a93c83"></a>
### [concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md)
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'shweaver-MSFT, beth-panx' is not a valid GitHub ID.`````
 - **Line 97, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../templates.md'.`````
 - **Line 128, Column 78**: **[Warning-file-not-found]** `````Invalid file link: './../providers.md'.`````

<a id="278bface-51a93c83"></a>
### [concepts/data-connect-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/data-connect-overview.md)
 - **Line 0, Column 0**: **[Warning-unhandled-exception]** 
`````
Unhandled exception - report this issue via https://aka.ms/SiteHelp: System.AggregateException: One or more errors occurred. (Requested value 'learningpath' was not found.)
 ---> System.ArgumentException: Requested value 'learningpath' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.<>c__5`1.<Convert>b__5_0(String e)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.Convert[TRule](Rules contentRules, String key)
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.<>c__DisplayClass4_0.<GetActiveValidationRuleSets>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.GetActiveValidationRuleSets(RuleSetRepositoryOptions repositoryOptions)
   at Apex.Validation.Logic.ValidationManager.ValidateContent(TokenizedMarkdown tokenizedMarkdown, RuleSetRepositoryOptions repositoryOptions, Boolean isTestMode, MarkdownDocument markdownDocument)
   at Apex.Validation.Logic.ValidationLogic.ValidateAuthoringRules(TokenizedMarkdown tokenizedMarkdown, RuleSetRepositoryOptions ruleSetRepositoryOptions, Boolean isTestMode, MarkdownDocument markdownDocument)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Validations.DocFx.Adapter.OnlineServiceMarkdownValidatorProvider.<GetValidators>b__8_0(MarkdownDocument document)
`````

<a id="0e8edd8c-51a93c83"></a>
### [api-reference/beta/api/accesspackagecatalog-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/api-reference/beta/api/accesspackagecatalog-get.md)
 - **Line 0, Column 0**: **[Warning-unhandled-exception]** 
`````
Unhandled exception - report this issue via https://aka.ms/SiteHelp: System.AggregateException: One or more errors occurred. (Requested value 'learningpath' was not found.)
 ---> System.ArgumentException: Requested value 'learningpath' was not found.
   at System.Enum.TryParseByName(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, String originalValueString, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.<>c__5`1.<Convert>b__5_0(String e)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.Convert[TRule](Rules contentRules, String key)
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.<>c__DisplayClass4_0.<GetActiveValidationRuleSets>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Apex.Validation.Repositories.Providers.ValidationServiceRepository`1.GetActiveValidationRuleSets(RuleSetRepositoryOptions repositoryOptions)
   at Apex.Validation.Logic.ValidationManager.ValidateContent(TokenizedMarkdown tokenizedMarkdown, RuleSetRepositoryOptions repositoryOptions, Boolean isTestMode, MarkdownDocument markdownDocument)
   at Apex.Validation.Logic.ValidationLogic.ValidateAuthoringRules(TokenizedMarkdown tokenizedMarkdown, RuleSetRepositoryOptions ruleSetRepositoryOptions, Boolean isTes [...]

2020-12-03 18:31 UTC, nmetulev requested changes
Awesome

Make sure to add this to the toc.yaml so it shows up in the navigation pane on the left.

2020-12-03 18:31 UTC, nmetulev commented on concepts/toolkit/components/todo.md
> +The `tasks` component supports several [templates](../templates.md) that allow you to replace certain parts of the component. To specify a template, include a `<template>` element inside a component
The templates link here should be updated to the new location

2020-12-03 20:06 UTC, beth-panx commented on concepts/toolkit/components/todo.md
> +The `tasks` component supports several [templates](../templates.md) that allow you to replace certain parts of the component. To specify a template, include a `<template>` element inside a component
Is there still a template md file?

2020-12-03 20:08 UTC, opbld34 commented
Docs Build status updates of commit _[f9924f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9924f670075cc67eec3ee0a98739835d66265fc)_: 

:clock10: **Pending**: waiting for processors ([13](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 13 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 20:09 UTC, opbld32 commented
Docs Build status updates of commit _[f9924f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9924f670075cc67eec3ee0a98739835d66265fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) | [Details](#user-content-d5345b08-b325fc81)

<a id="d5345b08-b325fc81"></a>
### [concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md)
 - **Line 97, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../templates.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012032008365263-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=32GSxdZKiMxbFnCY%2F0Rqn7mAsfHQ8RpCtD%2BPRAZoqBA%3D&st=2020-12-03T20%3A04%3A47Z&se=2021-01-03T20%3A09%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 21:42 UTC, elisenyang submitted a review, later dismissed

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +# To-do Component in the Microsoft Graph Toolkit
```suggestion
To Do Component in the Microsoft Graph Toolkit
```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +The To-do component enables the user to view, add, remove, complete, or edit tasks. It works with tasks from the Microsoft To-Do API.
```suggestion
The To Do component is used to enable the signed-in user to view, add, remove, complete, and/or edit tasks from Microsoft To Do using the To Do tasks API on Microsoft Graph.
```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +The following example displays the signed-in user's Microsoft To-do tasks using the `mgt-todo` component. You can use the code editor to see how [properties](#properties) change the behavior of the c
```suggestion
The following example displays the signed-in user's Microsoft To Do tasks using the `mgt-todo` component. You can use the code editor to see how [properties](#properties) change the behavior of the component.
```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +
```suggestion

You can use the following attributes and properties to customize the component.

```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +
```suggestion

The `mgt-todo` component defines the following CSS custom properties.

```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +
```suggestion

To learn more, see [styling components](https://docs.microsoft.com/graph/toolkit/style.md).

```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +## Events
```suggestion
## Events

The following events are fired from the component.

```

2020-12-03 21:42 UTC, elisenyang commented on concepts/toolkit/components/todo.md
> +| Resource | Permission |
These should link to the API reference page for the endpoints

2020-12-03 21:47 UTC, opbld32 commented
Docs Build status updates of commit _[2dc05ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2dc05accf6ceeb93f1b37a74fa23f55b22e79bab)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:47 UTC, opbld30 commented
Docs Build status updates of commit _[41bc741](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41bc741a7454c119fad421b9cac506d3c6ffba44)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:47 UTC, opbld33 commented
Docs Build status updates of commit _[698cfb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/698cfb6091d2ab87e9b00f1483156d5284802ed3)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:47 UTC, opbld31 commented
Docs Build status updates of commit _[6454658](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64546586266f32c71d053213ecb73efaec77577a)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:48 UTC, opbld32 commented
Docs Build status updates of commit _[03eae13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03eae13d00aacfee34d0574dd968c1eb17b8d54f)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:48 UTC, opbld33 commented
Docs Build status updates of commit _[4a4a5d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a4a5d39d3854202de199a7f11c2c2f17846a658)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:48 UTC, opbld33 commented
Docs Build status updates of commit _[648956e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/648956e28ea435339fc0290960cfed341d7aa279)_: 

:clock10: **Pending**: waiting for processors ([15](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 15 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 21:48 UTC, opbld31 commented
Docs Build status updates of commit _[2dc05ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2dc05accf6ceeb93f1b37a74fa23f55b22e79bab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) | [Details](#user-content-d5345b08-7b8ee133)

<a id="d5345b08-7b8ee133"></a>
### [concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 97, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../templates.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012032147192847-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lg7AUJ%2BNntiTbRt%2F0kc9FvQyclO644JXEYzsjU44uRQ%3D&st=2020-12-03T21%3A43%3A30Z&se=2021-01-03T21%3A48%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 21:48 UTC, beth-panx commented on concepts/toolkit/components/todo.md
> +| Resource | Permission |
awww.... no suggested commit? Lol I will update this.

2020-12-03 21:49 UTC, opbld32 commented
Docs Build status updates of commit _[41bc741](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41bc741a7454c119fad421b9cac506d3c6ffba44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) | [Details](#user-content-d5345b08-d04072c5)

<a id="d5345b08-d04072c5"></a>
### [concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 97, Column 40**: **[Warning-file-not-found]** `````Invalid file link: '../templates.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012032147289635-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JZqZ9ds5rKkbcIE6UCdxodNz0lZ2%2B3JleaodL5kfYEU%3D&st=2020-12-03T21%3A44%3A52Z&se=2021-01-03T21%3A49%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 22:44 UTC, opbld34 commented
Docs Build status updates of commit _[a0790af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0790afe325413299e632751d43f64c09bf638af)_: 

:clock10: **Pending**: waiting for processors ([20](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 20 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-03 22:45 UTC, opbld34 commented
Docs Build status updates of commit _[a0790af](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0790afe325413299e632751d43f64c09bf638af)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) | [Details](#user-content-d5345b08-83f2a8f1)

<a id="d5345b08-83f2a8f1"></a>
### [concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md)
 - **Line 131, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 132, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 133, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&tabs=http`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&tabs=http`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-1.0&tabs=http`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012032244088334-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5hdIjMlrEqV9RofDX00SnvbmQQBS1eP4HdzUbr%2FSefA%3D&st=2020-12-03T22%3A40%3A28Z&se=2021-01-03T22%3A45%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-03 22:45 UTC, beth-panx commented on concepts/toolkit/components/todo.md
> +| Resource | Permission |
Done! @elisenyang

2020-12-03 22:46 UTC, beth-panx commented on concepts/toolkit/components/todo.md
> +The `tasks` component supports several [templates](../templates.md) that allow you to replace certain parts of the component. To specify a template, include a `<template>` element inside a component
@nmetulev updated!

2020-12-04 01:37 UTC, opbld34 commented
Docs Build status updates of commit _[18a1aec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18a1aecb81f7f0a1401bcb77b807dd83776c02ae)_: 

:clock10: **Pending**: waiting for processors ([12](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 12 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 01:39 UTC, opbld34 commented
Docs Build status updates of commit _[18a1aec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18a1aecb81f7f0a1401bcb77b807dd83776c02ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) | [Details](#user-content-d5345b08-c5bd03a6)

<a id="d5345b08-c5bd03a6"></a>
### [concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md)
 - **Line 131, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 132, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 133, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-1.0&tabs=http' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/todo-list-lists?view=graph-rest-1.0&tabs=http`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/todotasklist-list-tasks?view=graph-rest-1.0&tabs=http`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-1.0&tabs=http`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040137485397-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s0qSBB720pdwMdcXDyAWN55g%2Bk2NTyMSV%2BElYmd15MA%3D&st=2020-12-04T01%3A33%3A59Z&se=2021-01-04T01%3A38%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 01:41 UTC, nmetulev commented on concepts/toolkit/components/todo.md
> +| [/me/todo/lists/{todoTaskListId}/tasks/{taskId}](https://docs.microsoft.com/en-us/graph/api/todotask-get?view=graph-rest-1.0&tabs=http) | Tasks.ReadWrite |
```suggestion
| [/me/todo/lists/](/graph/api/todo-list-lists) | Tasks.ReadWrite |
| [/me/todo/lists/{todoTaskListId}/tasks](/graph/api/todotasklist-list-tasks) | Tasks.ReadWrite |
| [/me/todo/lists/{todoTaskListId}/tasks/{taskId}](/graph/api/todotask-get) | Tasks.ReadWrite |
```

2020-12-04 01:43 UTC, nmetulev requested changes
Need to add the todo to the toc.yaml file so it shows up in the nav

Also add a link to the todo docs from the overview page

2020-12-04 18:56 UTC, opbld31 commented
Docs Build status updates of commit _[49dd019](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49dd0195cf754b91d78135dcac2e6838626b2161)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041855119891-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B7tRbwld%2F5tjYJ5TdZl4kmfrBf6pfTDs%2FksC22EcZ4I%3D&st=2020-12-04T18%3A51%3A37Z&se=2021-01-04T18%3A56%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:01 UTC, opbld33 commented
Docs Build status updates of commit _[e04b608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e04b608a3dac9fd65a1477ae1db32472d3974cdc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041900400686-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mPRPKseKUkV5JCOgn7FQl0jq6Fpf%2BPQ%2F24sSSVdXF%2Fo%3D&st=2020-12-04T18%3A56%3A52Z&se=2021-01-04T19%3A01%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:03 UTC, opbld31 commented
Docs Build status updates of commit _[eb9dc70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb9dc706768bb55eb0d10e2b872205f329e66efe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-10903) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041901518466-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ewynymuH2Rc8c4qxAahKvy8kREdG3KSC3s9hnUHMpys%3D&st=2020-12-04T18%3A58%3A16Z&se=2021-01-04T19%3A03%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:05 UTC, opbld31 commented
Docs Build status updates of commit _[c2f4b81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2f4b81c72aa6f7bfeb07c21aa4d6ce3422b5469)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-10903) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041903400970-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iwT3nPvRrXXO72nhbZ8sjVOBHXAQ8HozjQ9BjXunQhU%3D&st=2020-12-04T19%3A00%3A10Z&se=2021-01-04T19%3A05%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:06 UTC, opbld34 commented
Docs Build status updates of commit _[62e0d2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62e0d2a3b76a5215cb5374757fac1d0257eb96ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-10903) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041905273959-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lbdFnDdRxAAr43xN9vMOJ3w%2FpRnQ7TF2onF88gGTPGQ%3D&st=2020-12-04T19%3A01%3A37Z&se=2021-01-04T19%3A06%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:07 UTC, nmetulev approved these changes

2020-12-04 19:07 UTC, opbld32 commented
Docs Build status updates of commit _[41fc413](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41fc4134c6c4b8317a57fa6f9c8e68cb1d8afb5c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/components/todo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/components/todo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/components/todo?branch=pr-en-us-10903) |
[concepts/toolkit/overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bethpan/mgt-todo/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-10903) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012041906088812-10903%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G1%2BfOM97YT11LLPPh7rZ7cfAmWqUDZdOSlRzIuH0tm8%3D&st=2020-12-04T19%3A02%3A54Z&se=2021-01-04T19%3A07%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 19:08 UTC, merged