2020 12 01 tarkansevilmis planner feature update
microsoftgraph/microsoft-graph-docs pull request #10921
Opened 2020-12-04 02:07 UTC by TarkanSevilmis

Updates for the Planner API.
Adding containers, deprecating owner on plan.
Adding task creation source info.

2020-12-04 02:07 UTC, opbld32 commented
Docs Build status updates of commit _[e45ed95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e45ed95717df201d385258c7d75a3dbb5b33c189)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 02:09 UTC, opbld33 commented
Docs Build status updates of commit _[e45ed95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e45ed95717df201d385258c7d75a3dbb5b33c189)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040207470651-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9avbh16G%2FvwX9JGeNk2rHm2G2%2FyBupU3DG5%2BABz%2F2tU%3D&st=2020-12-04T02%3A04%3A08Z&se=2021-01-04T02%3A09%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 02:24 UTC, opbld31 commented
Docs Build status updates of commit _[89c86d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89c86d9aa0091260c6a074098ff299d7afb21e8b)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-04 02:26 UTC, opbld34 commented
Docs Build status updates of commit _[89c86d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89c86d9aa0091260c6a074098ff299d7afb21e8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012040224393788-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=78I%2BmvOc455NnF901D4XZtzbA%2BZfdrUVrRWwVgbKVJU%3D&st=2020-12-04T02%3A21%3A05Z&se=2021-01-04T02%3A26%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-04 22:51 UTC, opbld32 commented
Docs Build status updates of commit _[70493bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70493bc72fcc3067c25bdab72d4bd8d06b12f850)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012042249394474-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0QLm1vDeRzHrvK6nV3uQ4NlP3eNN63giWd0s2PvCyJM%3D&st=2020-12-04T22%3A45%3A59Z&se=2021-01-04T22%3A50%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 19:46 UTC, opbld31 commented
Docs Build status updates of commit _[aab89f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aab89f0972649ea2b14582ba10372d383722f5b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012141944451404-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7XvLMz5JNIwBK5Gppjlrd1QVu3jZjdHvzcufZoOUor8%3D&st=2020-12-14T19%3A41%3A09Z&se=2021-01-14T19%3A46%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 20:02 UTC, opbld30 commented
Docs Build status updates of commit _[0d98c89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d98c89884858c8528f711df8c36a0a4cacf84ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012142000456710-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0eWPbbA6wdFQZIgYHu7vVDR3XgxLJnpZivfnJ3vxUrM%3D&st=2020-12-14T19%3A57%3A33Z&se=2021-01-14T20%3A02%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 01:48 UTC, Lauragra commented on api-reference/beta/resources/plannerplan.md
> +|owner|String|Deprecated. Please use *container* property instead. ID of the [Group](group.md) that owns the plan. A valid group must exist before this field can be set. After it is set, this propert
Please make sure that you're following the guidance here for deprecated properties: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/73842/Deprecate-docs?anchor=deprecate-content-for-a-property-or-relationship

2020-12-15 01:50 UTC, opbld32 commented
Docs Build status updates of commit _[0057943](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0057943ad887703b24bb89a61f95acbac04f0b01)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150148407898-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ar3SBZcGswHyn2D4N6GdR2zOE%2BSqn9lzy1IuqPBbIQo%3D&st=2020-12-15T01%3A45%3A12Z&se=2021-01-15T01%3A50%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 01:54 UTC, opbld30 commented
Docs Build status updates of commit _[39a277a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39a277a73b3e65a4edaa7ac0645f3dbc480585ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150153224757-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6KgWmabmvdQLHZ4isyNsgkW6AYuq0ILDYxHreQAqkTM%3D&st=2020-12-15T01%3A49%3A33Z&se=2021-01-15T01%3A54%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 02:16 UTC, opbld32 commented
Docs Build status updates of commit _[d61e622](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d61e6224247733e24ad66d0a6100e9ee57c4e566)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150215231238-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FJ7zlx3YOwLZfN00MVC7GQiU%2BM9TFCkMD0rsaMMC%2B1Y%3D&st=2020-12-15T02%3A11%3A47Z&se=2021-01-15T02%3A16%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 02:18 UTC, opbld34 commented
Docs Build status updates of commit _[0150727](https://github.com/microsoftgraph/microsoft-graph-docs/commits/015072758c815314dec7e4e04ecd0350a958eca3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150217355390-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4KijE9fuA465U59a9KJRulNnQXjZXZANuuurWo8RDDc%3D&st=2020-12-15T02%3A13%3A55Z&se=2021-01-15T02%3A18%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 02:37 UTC, opbld33 commented
Docs Build status updates of commit _[9ffb9cf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ffb9cfb87443d4f6e81982946960d0d44cb06b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150235347339-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VDmWYS2o%2BxKhAbKU2O5wvsznXI8c%2FOWAxpNTzjaBrFI%3D&st=2020-12-15T02%3A32%3A00Z&se=2021-01-15T02%3A37%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 02:38 UTC, Lauragra commented on changelog/Microsoft.Office.Tasks.json
> +    {
In addition to the JSON file, we still need to update changelog.md as well, while the new filterable changelog experience is still in preview.

2020-12-15 02:39 UTC, opbld34 commented
Docs Build status updates of commit _[f5299ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5299ad3d824e631f53e14cc374def174b34e63e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012150238099675-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3gW4C9XllwpUme1IVwn9JpOdKu6hKJQSl0Q9a1agi%2FU%3D&st=2020-12-15T02%3A34%3A23Z&se=2021-01-15T02%3A39%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 02:39 UTC, Lauragra requested changes
I left a couple of comments - pls. take a look.

2021-01-08 07:12 UTC, paulodero requested changes

2021-01-08 07:12 UTC, paulodero commented on changelog/Microsoft.Office.Tasks.json
> +          "ChangeType": "Change",
ChangeType for deprecated elements is `Deprecation`

2021-01-08 07:12 UTC, paulodero commented on changelog/Microsoft.Office.Tasks.json
> +          "Description": "Deprecated the **owner** property on the [plannerPlan](https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta) resource.",
This is not the case. The property has not been deprecated in the schema change submitted.

2021-01-08 19:39 UTC, TarkanSevilmis commented on changelog/Microsoft.Office.Tasks.json
> +          "Description": "Deprecated the **owner** property on the [plannerPlan](https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta) resource.",
Added the schema annotation

2021-01-08 19:39 UTC, opbld31 commented
Docs Build status updates of commit _[0859cdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0859cdf2a51ea5fb814ead3fc1261eafe683df6e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10921) | [Details](#user-content-de0bbbbb-8ad5978f)
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8ad5978f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerTask?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerPlanContainer?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerTaskCreation?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerTeamsPublicationInfo?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 26, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/plannerTask?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If s [...]

2021-01-08 19:42 UTC, opbld34 commented
Docs Build status updates of commit _[f357a49](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f357a4940463d5700a7dd75bf4b519da143a7d3a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10921) | [Details](#user-content-de0bbbbb-872b62f6)
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-872b62f6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerTask?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerPlanContainer?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerTaskCreation?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerTeamsPublicationInfo?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 26, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/plannerTask?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/plannerPlan?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If s [...]

2021-01-08 20:51 UTC, opbld34 commented
Docs Build status updates of commit _[3dd6682](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dd66821504f05078d351d5395d5f7b738f1c87c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10921) | [Details](#user-content-de0bbbbb-2873649c)
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2873649c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/plannerTask?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/plannerPlan?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/plannerPlanContainer?view=graph-rest-beta`````
 - **Line 23, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/plannerTaskCreation?view=graph-rest-beta`````
 - **Line 24, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/plannerTeamsPublicationInfo?view=graph-rest-beta`````
 - **Line 26, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/plannerPlan?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082050402710-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qU7xkSJDasXYvCUdA41IDeW0Ql%2B2jgxgDqYtG%2FQ7pHs%3D&st=2021-01-08T20%3A46%3A50Z&se=2021-02-08T20%3A51%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 21:05 UTC, opbld33 commented
Docs Build status updates of commit _[a302b9d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a302b9d58cf37b59bccb7377a93c68ec8065313f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10921) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082103401417-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qMXJZyN16h3gWA8BXaWUaA8oMjEKkfQfR5S%2BdvIkl%2BE%3D&st=2021-01-08T21%3A00%3A24Z&se=2021-02-08T21%3A05%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:16 UTC, opbld34 commented
Docs Build status updates of commit _[14edaf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14edaf1f2a8a1eee32ad27c7c18d096cfecf8339)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-75415c8e)

<a id="75415c8e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132316339858-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5wKqULspZpNjuYMOwTGaSJiqF1BWSgVGlVW3H8cCEDA%3D&st=2021-01-13T23%3A11%3A50Z&se=2021-02-13T23%3A16%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:30 UTC, opbld30 commented
Docs Build status updates of commit _[ba0d6d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba0d6d6d1f256848c0de0fc9d5f97e4311fa5559)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c9f69494)

<a id="c9f69494"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132330316701-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O8uloikLy7GjahdTvYPv5TAQ%2FTHVIcNotgQ4XvMJ%2BgM%3D&st=2021-01-13T23%3A25%3A49Z&se=2021-02-13T23%3A30%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:33 UTC, opbld32 commented
Docs Build status updates of commit _[e3b1424](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3b14248679f3d5ff6504d4a9c27812d9c15cc11)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-56e47b4f)

<a id="56e47b4f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132333100905-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2xI%2Fu5%2FkcFsSJFZVQQwHmYbADP3IlbtsI517xVbE90o%3D&st=2021-01-13T23%3A28%3A29Z&se=2021-02-13T23%3A33%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:36 UTC, opbld34 commented
Docs Build status updates of commit _[b34cd13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b34cd138b2f306cf11d52f3a9aca2b7b85b578ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132335068746-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p7yic1krwIaHQim2sckCF9WPhs32RycdbJaINhINX1k%3D&st=2021-01-13T23%3A31%3A21Z&se=2021-02-13T23%3A36%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:37 UTC, opbld34 commented
Docs Build status updates of commit _[e0c5825](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e0c5825cce35eafd5842c4f0a24dd14e323cc5f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132335297280-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r6i8c63wlARKchT2DoaxFFXCOqQ6xvbMTpWFg%2FyySbI%3D&st=2021-01-13T23%3A32%3A41Z&se=2021-02-13T23%3A37%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 23:59 UTC, opbld31 commented
Docs Build status updates of commit _[39e9580](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39e95808f42cf20ede2587e793ade9d0023eb43d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10921) | [Details](#user-content-de0bbbbb-426860fc)
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-426860fc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md)
 - **Line 49, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 49, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132358367706-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tVH3EWYi0kc2e0fhJbMU6qTDXXvODPUR3F9D5hWG4dk%3D&st=2021-01-13T23%3A54%3A46Z&se=2021-02-13T23%3A59%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf08 [...]

2021-01-14 00:08 UTC, Lauragra approved these changes

2021-01-14 03:08 UTC, opbld31 commented
Docs Build status updates of commit _[f83649c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f83649c16c098dbf32405531cd0396b9745010b4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10921) | [Details](#user-content-de0bbbbb-20b299ed)
[api-reference/beta/api/planner-post-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/planner-post-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/planner-post-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannergroup-list-plans.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannergroup-list-plans.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannergroup-list-plans?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-get?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/api/plannerplan-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/api/plannerplan-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/plannerplan-update?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/planner-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/planner-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/planner-overview?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplan.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplan.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplan?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerplancontainer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerplancontainer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerplancontainer?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertask.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertask?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannertaskcreation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannertaskcreation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannertaskcreation?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[api-reference/beta/resources/plannerteamspublicationinfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/api-reference/beta/resources/plannerteamspublicationinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/plannerteamspublicationinfo?view=graph-rest-beta&branch=pr-en-us-10921) (graph-rest-beta) |
[changelog/Microsoft.Office.Tasks.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/changelog/Microsoft.Office.Tasks.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-20b299ed"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-01-tarkansevilmis-PlannerFeatureUpdate/concepts/changelog.md)
 - **Line 49, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 49, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140306319865-10921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y74D%2Fk3w0sjuvyUILAQD8pgRlTKTgYHRpp%2FTrl%2BE2xs%3D&st=2021-01-14T03%3A03%3A02Z&se=2021-02-14T03%3A08%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed5 [...]

2021-01-16 01:56 UTC, merged