chat member related doc update
microsoftgraph/microsoft-graph-docs pull request #10954
Opened 2020-12-07 17:30 UTC by bhartono

2020-12-07 17:31 UTC, opbld31 commented
Docs Build status updates of commit _[1155269](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1155269ac9a46d19dceb9392fb608dc9b531f9de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-542ae259)
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :warning:Warning | | [Details](#user-content-78e5eaee-542ae259)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :bulb:Suggestion | | [Details](#user-content-62bc66bc-542ae259)
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :bulb:Suggestion | | [Details](#user-content-19903a1c-542ae259)

<a id="00685cff-542ae259"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12581, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

<a id="78e5eaee-542ae259"></a>
### [api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md)
 - **Line 24, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-list.md'.`````
 - **Line 25, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/conversationmember-get.md'.`````

<a id="62bc66bc-542ae259"></a>
### [api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat.' is duplicated in 'beta/api/chat-get-members.md(3,14)', 'beta/api/chat-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="19903a1c-542ae259"></a>
### [api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat.' is duplicated in 'beta/api/chat-get-members.md(3,14)', 'beta/api/chat-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071730335284-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rdH%2FHaBfati3rlTl4MTrVocTGgf5%2BJAud8UJZSqBYNo%3D&st=2020-12-07T17%3A26%3A32Z&se=2021-01-07T17%3A31%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:36 UTC, opbld34 commented
Docs Build status updates of commit _[d7efc66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7efc66f8f141496a9fdbde3a8d293483979fc48)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-c0bb3a4d)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :bulb:Suggestion | | [Details](#user-content-62bc66bc-c0bb3a4d)
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :bulb:Suggestion | | [Details](#user-content-19903a1c-c0bb3a4d)

<a id="00685cff-c0bb3a4d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12581, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

<a id="62bc66bc-c0bb3a4d"></a>
### [api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat.' is duplicated in 'beta/api/chat-get-members.md(3,14)', 'beta/api/chat-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="19903a1c-c0bb3a4d"></a>
### [api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat.' is duplicated in 'beta/api/chat-get-members.md(3,14)', 'beta/api/chat-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071935057351-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jitvecSHiq%2B6e8YRDBNfPQStoOdoIBvWT8nCt6HtP3c%3D&st=2020-12-07T19%3A31%3A04Z&se=2021-01-07T19%3A36%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 19:39 UTC, opbld32 commented
Docs Build status updates of commit _[b1b4e15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1b4e15b5f4ee3529cf59dd3993f15ab788dc06b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-c5c97dee)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :bulb:Suggestion | | [Details](#user-content-62bc66bc-c5c97dee)
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :bulb:Suggestion | | [Details](#user-content-19903a1c-c5c97dee)

<a id="00685cff-c5c97dee"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12581, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

<a id="62bc66bc-c5c97dee"></a>
### [api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat.' is duplicated in 'beta/api/chat-get-members.md(3,14)', 'beta/api/chat-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="19903a1c-c5c97dee"></a>
### [api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve a member of a chat.' is duplicated in 'beta/api/chat-get-members.md(3,14)', 'beta/api/chat-list-members.md(3,14)'. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071938577060-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rVq83EWz4CFVrNv0NDHr3HKTBl6%2F3UoY34f%2BL%2F452po%3D&st=2020-12-07T19%3A34%3A56Z&se=2021-01-07T19%3A39%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 21:54 UTC, opbld34 commented
Docs Build status updates of commit _[f9c90c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9c90c12f33019c5704b830e02ecb913d5a6fed5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-1880a450)

<a id="00685cff-1880a450"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12581, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012072153465385-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zKjykTRWTm3d9cpjEs1Pmvy0i080A05rst%2Bh7dUHF%2BM%3D&st=2020-12-07T21%3A49%3A45Z&se=2021-01-07T21%3A54%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 22:25 UTC, AkJo commented on api-reference/beta/api/chat-delete-members.md
> +title: "Delete conversationMember"
Remove member from chat.

2020-12-07 22:26 UTC, AkJo commented on api-reference/beta/api/chat-delete-members.md
> +DELETE /chats/{id}/members/{id}
DELETE /chats/{chat-id}/members/{membership-id}

2020-12-07 22:27 UTC, AkJo commented on api-reference/beta/api/chat-delete-members.md
> +DELETE https://graph.microsoft.com/beta/chats/{id}/members/{id}
In the examples, please provide actual values instead of placeholders.

2020-12-07 22:27 UTC, AkJo commented on api-reference/beta/api/chat-get-members.md
> +|Delegated (work or school account)| Chat.ReadBasic, Chat.Read, Chat.ReadWrite |
ChatMember.Read

2020-12-07 22:28 UTC, AkJo commented on api-reference/beta/api/chat-get-members.md
>  GET /chats/{id}/members/{id}
GET /chats/{chat-id}/members/{membership-id}
GET /users/{user-id}/chats/{chat-id}/members/{membership-id}

2020-12-07 22:28 UTC, AkJo commented on api-reference/beta/api/chat-get-members.md
>  title: "Get conversationMember"
Get member of chat

2020-12-07 22:29 UTC, AkJo commented on api-reference/beta/api/chat-get-members.md
>  ## Optional query parameters
Also, please update the example request and response with real values.

2020-12-07 22:29 UTC, AkJo commented on api-reference/beta/api/chat-list-members.md
>  title: "List conversationMembers"
List members of chat

2020-12-07 22:30 UTC, AkJo commented on api-reference/beta/api/chat-list-members.md
> +description: "Retrieve members of a chat."
List members of a chat

2020-12-07 22:31 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +POST /chats/{id}/members
chat-id

2020-12-07 22:31 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +POST https://graph.microsoft.com/beta/chat/{id}/members/
Use illustrative values.

2020-12-07 22:31 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +POST https://graph.microsoft.com/beta/chat/{id}/members/
Dangling forward slash.

2020-12-07 22:31 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +POST https://graph.microsoft.com/beta/chat/{id}/members/
Illustrative values.

2020-12-08 19:14 UTC, eddie-lee-msft requested changes

2020-12-08 19:14 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-post-members.md
> +    "visibleHistoryStartDateTime": null
Whole chat history sharing should be this now: 
"visibleHistoryStartDateTime": "0001-01-01T00:00:00Z"

2020-12-08 19:14 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-list-members.md
> +List all [conversation members](../resources/conversationmember.md) in a [chat](../resources/chat.md).
We might want to consider leaving a note somewhere mentioning that the 'tenantId' field in the aadUserConversationMembers returned will (for now) not be populated, despite us making the change to expose tenantId in this addUserConversationMember type. This is a gap from CSA. Check in with Anand and see what he thinks.

2020-12-09 00:46 UTC, opbld33 commented
Docs Build status updates of commit _[0df4eac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0df4eac96017ec5646111892ed1a01793a963664)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-09 00:46 UTC, opbld33 commented
Docs Build status updates of commit _[553eccd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/553eccdf198d6ed3be218c7bd111d5dbb26bc73e)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-09 00:47 UTC, opbld32 commented
Docs Build status updates of commit _[0df4eac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0df4eac96017ec5646111892ed1a01793a963664)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-c19805e4)

<a id="00685cff-c19805e4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12631, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090046035530-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UmnQnQEArmpTRkVosL3d%2Bht3PWFdxGiHpRy5pqdwVvk%3D&st=2020-12-09T00%3A42%3A09Z&se=2021-01-09T00%3A47%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 00:48 UTC, opbld32 commented
Docs Build status updates of commit _[553eccd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/553eccdf198d6ed3be218c7bd111d5dbb26bc73e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-1393cc5b)

<a id="00685cff-1393cc5b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12631, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090046270193-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hFEqISr6wNe8wy%2BU%2Bb54cQco2WfWFy7oh7KeFuggEkk%3D&st=2020-12-09T00%3A43%3A18Z&se=2021-01-09T00%3A48%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 07:11 UTC, bhartono commented on api-reference/beta/api/chat-list-members.md
> +List all [conversation members](../resources/conversationmember.md) in a [chat](../resources/chat.md).
@AkJo what do you think of Eddie's comment ?

2020-12-09 07:17 UTC, opbld30 commented
Docs Build status updates of commit _[38c6fe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38c6fe733b76c03947ad71784cf58980afca6397)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-f67f4ed4)

<a id="00685cff-f67f4ed4"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12631, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090715536707-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RRFc9Zsf%2FmVnoei3i9%2B%2F%2BXdyPX3m4bO3ZvAzNRk4SZk%3D&st=2020-12-09T07%3A12%3A00Z&se=2021-01-09T07%3A17%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 07:20 UTC, opbld31 commented
Docs Build status updates of commit _[e04c038](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e04c038a1142f439b8c50bb1a4db6085b7c71bd8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-91971d9c)

<a id="00685cff-91971d9c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 12629, Column 17**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar, found a tab character that violate indentation.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090719453461-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uul8p97DRAx%2Bd22vOu46EfMjqAWziLxL44qj92KSA30%3D&st=2020-12-09T07%3A15%3A55Z&se=2021-01-09T07%3A20%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 07:22 UTC, opbld32 commented
Docs Build status updates of commit _[1c2bcb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c2bcb186396eefb607d155bf3e63c8fd5fae8f4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-d42a48e0)

<a id="00685cff-d42a48e0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml)
 - **Line 1, Column 1**: **[Error-yaml-syntax-error]** `````While scanning a mapping, found invalid tab as indendation.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090721504633-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7VY9nZ5YS2DdKjT65qvyjd60%2BBQ1YpT8oeSSOGmGNVA%3D&st=2020-12-09T07%3A17%3A54Z&se=2021-01-09T07%3A22%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 07:25 UTC, opbld33 commented
Docs Build status updates of commit _[dede985](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dede9854c9ea7455c642b30f799451f3119e5a16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090724169872-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pd5K6lXMunfO2Qy4hVmpyXhJnuxCen%2Ff0Ap38nlcXeg%3D&st=2020-12-09T07%3A20%3A40Z&se=2021-01-09T07%3A25%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 08:00 UTC, opbld31 commented
Docs Build status updates of commit _[8fc936c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fc936caf2658dca2e9beeba5a1e9f6b84c013f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090759217676-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JyibgxuvvxDt7OGggqNDlyr745iNKBda7N4FvzBSvDw%3D&st=2020-12-09T07%3A55%3A40Z&se=2021-01-09T08%3A00%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 08:25 UTC, opbld31 commented
Docs Build status updates of commit _[cad3f64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cad3f64eb5966bcb2266b5391be73a5b4c20ab4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090824198749-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ySfAUnbeZpsIvsDljgLLXGgO7CyTBU1rTD27GTKBjGY%3D&st=2020-12-09T08%3A20%3A39Z&se=2021-01-09T08%3A25%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 08:30 UTC, opbld30 commented
Docs Build status updates of commit _[a83a537](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a83a537c5707d076a67b0c7b71cedc0038a5e074)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090829205009-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UFsOf%2F6uUcknYgFAcySePb27z6t0dCHS6nv5o4t23pw%3D&st=2020-12-09T08%3A25%3A40Z&se=2021-01-09T08%3A30%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 19:01 UTC, eddie-lee-msft requested changes

2020-12-09 19:01 UTC, eddie-lee-msft commented on api-reference/beta/resources/chat.md
> +|[Delete chat member](../api/chat-delete-members.md) | [conversationMember](conversationmember.md) | Delete a user from the chat.|
Return type should be 'No content' like you have in conversationmember.md file.

2020-12-09 19:01 UTC, eddie-lee-msft commented on api-reference/beta/resources/chat.md
> +|[Add chat member](../api/chat-post-members.md) | [conversationMember](conversationmember.md) | Add a user to the chat.|
Return type should be 'No Content and a Location header' like you have in the conversationmember.md file.

2020-12-09 22:03 UTC, bhartono commented on api-reference/beta/api/chat-post-members.md
> +    "tenantId": "6e5147da-6a35-4275-b3f3-fc069456b6eb",
@eddie-lee-msft i was following your api.md doc sample, the doc is not right ? https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/6094?_a=files&path=%2Freviews%2F6417-teams-surface-visibleHistoryStartDateTime-in-conversationMember%2Fapi.md

2020-12-09 22:09 UTC, eddie-lee-msft commented on api-reference/beta/api/chat-post-members.md
> +    "tenantId": "6e5147da-6a35-4275-b3f3-fc069456b6eb",
@bhartono Yeah that's wrong.

2020-12-09 22:18 UTC, bhartono commented on api-reference/beta/api/chat-get-members.md
this is what Anand came up with for the file name

2020-12-09 23:22 UTC, opbld32 commented
Docs Build status updates of commit _[508a441](https://github.com/microsoftgraph/microsoft-graph-docs/commits/508a4414c02d2efc548e11989ce7551aa58f2fcc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092321264967-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0%2FCjL25TiQzdjFeUxFAYFD23sqsnuwDROA0z3cTqZVA%3D&st=2020-12-09T23%3A17%3A41Z&se=2021-01-09T23%3A22%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 23:58 UTC, opbld33 commented
Docs Build status updates of commit _[7a8f4d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a8f4d474d12134a0d6b32f0f20516733f5b70a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092357175068-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=75wgPvnRD5LshSEDya8pNQ%2FjcuWmlkQGuu6viEQblyM%3D&st=2020-12-09T23%3A53%3A29Z&se=2021-01-09T23%3A58%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 18:27 UTC, eddie-lee-msft approved these changes
Approving, but still think we need a note about tenantId not being populated in GET calls.

2020-12-10 19:02 UTC, opbld31 commented
Docs Build status updates of commit _[ad730c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad730c51526d66ad674cc8c82394eb9a81cddef9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7d013967)

<a id="7d013967"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012101902033906-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TKV%2F5wB%2BcxUY5whtX8EkKoR9AuxBf%2BhrPMGfA9iehr0%3D&st=2020-12-10T18%3A57%3A22Z&se=2021-01-10T19%3A02%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 19:12 UTC, AkJo commented on api-reference/beta/api/channel-get-members.md
> +|Delegated (work or school account)|ChannelMember.Read.All, ChannelMember.ReadWrite.All, Group.Read.All, Group.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All |
The Group/Directory permissions are allowed only for legacy apps. 

We should not add these permissions here. Please revert the permission changes in this doc.

2020-12-10 19:15 UTC, opbld32 commented
Docs Build status updates of commit _[630ac96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/630ac964355a04e8ddbad8d38ec7663d6662cc57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-09d60319)
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-09d60319"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 115, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 116, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 116, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012101913594770-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FDoBEA7WkdfDcaXxWwRD3Qt4lbOXb51b5uDxlBwnFM8%3D&st=2020-12-10T19%3A10%3A12Z&se=2021-01-10T19%3A15%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 19:47 UTC, opbld34 commented
Docs Build status updates of commit _[049aa6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/049aa6a450c6def53c4621be11942f2e40ee6362)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-56045645)
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-56045645"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 115, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 116, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 116, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012101946295536-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VOn9HFIaiU27DiZPWo5zASm5%2F9dMf4SRRiDNui4BDj4%3D&st=2020-12-10T19%3A42%3A56Z&se=2021-01-10T19%3A47%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 20:37 UTC, opbld34 commented
Docs Build status updates of commit _[d9a6fa7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9a6fa763870c85e07fa42d79d53daacbcd01327)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-152aeeea)
[api-reference/beta/api/channel-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/channel-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-152aeeea"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 116, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012102036045155-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gJioeVjOMZu6Vrn0UvnVbSA61Tg53bskG6wSzz7sitY%3D&st=2020-12-10T20%3A32%3A35Z&se=2021-01-10T20%3A37%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 20:39 UTC, eddie-lee-msft commented on changelog/changelog.json
> +          "ChangedApiName": "Create chat, Update chat",
Add chat member and delete chat member?

2020-12-10 20:47 UTC, opbld34 commented
Docs Build status updates of commit _[ac759bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac759bfc3a24a940e072b158665fcce7b0d00347)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-ff225ed5)
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ff225ed5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 116, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012102046104406-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4mwuf%2BNuGy7MTm84W1w%2Bm8Xox%2BNE%2FYbaael9%2FeY4Bvw%3D&st=2020-12-10T20%3A42%3A43Z&se=2021-01-10T20%3A47%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 11:29 UTC, opbld31 commented
Docs Build status updates of commit _[4f05340](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f053401bcd941c8af25d10bf1e9486dd3cfa916)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-07478a82)
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-07478a82"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151127552622-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C185on9Qsr33yiIIipkzDx3LKnkdDReJ7g%2Ffjx7l8%2BM%3D&st=2020-12-15T11%3A24%3A05Z&se=2021-01-15T11%3A29%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 11:43 UTC, opbld31 commented
Docs Build status updates of commit _[4b1638b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4b1638bc0f3ae0313e6650a13a6102714445f562)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-359ee2f8)
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-359ee2f8"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151141509718-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9mNmEJn%2BktnREFwIULI3fRgG%2BZEMcMDrB%2Fovt4yVVU4%3D&st=2020-12-15T11%3A38%3A00Z&se=2021-01-15T11%3A43%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 11:59 UTC, opbld30 commented
Docs Build status updates of commit _[aba5054](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aba50543d19ff1a2cfe8791e29ff439979228171)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-a240f338)
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-a240f338"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151158012306-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FF8zKDANURiH3Pej5uFe4eDYSNJwct2feZ0LCz9Uyjw%3D&st=2020-12-15T11%3A54%3A16Z&se=2021-01-15T11%3A59%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 21:48 UTC, opbld31 commented
Docs Build status updates of commit _[4da64df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4da64dfdf17feac490c7ed895fe03688f61658b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) | [Details](#user-content-84894718-e5714a9b)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-e5714a9b)
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="84894718-e5714a9b"></a>
### [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-e5714a9b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152147331141-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dkk8FogZIlnpZiBcul6La90K%2BTNzWwsLdaD8%2FaTNAEM%3D&st=2020-12-15T21%3A43%3A53Z&se=2021-01-15T21%3A48%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report]( [...]

2020-12-15 23:07 UTC, opbld33 commented
Docs Build status updates of commit _[0278c87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0278c87c606f52640c622fea6c534f0c8f3e31f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-0f4c0c64)
[api-reference/beta/api/chat-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-delete-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-0f4c0c64"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152306121338-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jL2EBQ0MtsXDLlPC0JSWE9%2BAWn%2BD9COJrsl%2FS6HxvJc%3D&st=2020-12-15T23%3A02%3A33Z&se=2021-01-15T23%3A07%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 23:29 UTC, opbld34 commented
Docs Build status updates of commit _[b1f1d0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b1f1d0d0900688578d2f0cef57de5f54e1c5b31e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-7434f634)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-7434f634"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152328356721-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tAY2sxRj50XkVLG9G2uLCN5r%2B0dQwWl7Vz3jur5CmKM%3D&st=2020-12-15T23%3A24%3A44Z&se=2021-01-15T23%3A29%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 23:30 UTC, AkJo approved these changes

2020-12-15 23:32 UTC, bhartono commented
@Lauragra @AkJo  can we please merge this ?

2020-12-16 00:08 UTC, Lauragra commented on api-reference/beta/api/chat-get-members.md
> -# [C#](#tab/csharp)
When you delete snippets, please also delete the # HTTP line; otherwise we get a table with one tab and duplicate HTTP line.

2020-12-16 00:09 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +| Authorization  | Bearer {token}. Required.  |
Add the content-type header line.

2020-12-16 00:10 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +|user|[conversationMember](../resources/conversationmember.md)|The user to add to the chat.|
Please verify - these properties should be included in the request examples?

2020-12-16 00:12 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +### Example 1: Adding a single member to a Microsoft Teams chat while specifying a specific time the conversation history is shared back to
We can make this heading shorter: "Example 1: Add a single member to a chat and specify the timespan for the conversation history". It might be worthwhile to mention in the API summary that sharing the history is part of the functionality, and shouldn't the history property be part of the request body section?

2020-12-16 00:14 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +HTTP/1.1 201 Created with Location header.
Please verify how this response should appear.

2020-12-16 00:17 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +If successful, this method returns a `201 Created` response code and a Location header.
Do you need to explain what the location header is for?

2020-12-16 00:18 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +# [HTTP](#tab/http)
Remove all HTTP H1s - those get added via the automated snippet generation.

2020-12-16 00:27 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +### Example 1: Adding a single member to a Microsoft Teams chat while specifying a specific time the conversation history is shared back to
> We can make this heading shorter: "Example 1: Add a single member to a chat and specify the timespan for the conversation history". It might be worthwhile to mention in the API summary that sharing the history is part of the functionality, and shouldn't the history property be part of the request body section?

The history is specified as part of the conversationMember. That is why you do not see it as a separate entry in the request body section.

+1 on renaming the heading.

2020-12-16 00:28 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +HTTP/1.1 201 Created with Location header.
@bhartono , I am not sure where this sample notation came from, but we should put down the actual location header in the response.

2020-12-16 00:28 UTC, AkJo commented on api-reference/beta/api/chat-post-members.md
> +If successful, this method returns a `201 Created` response code and a Location header.
@bhartono , we can clarify that the location header provider a url path to the newly created member object.

2020-12-16 00:37 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +title: "Add conversationMember"
The title should match the H1 heading. Based on the guidance in this topic, the title should be "Create conversationMember": https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22

2020-12-16 00:39 UTC, Lauragra commented on changelog/changelog.json
> +    {
This is the wrong JSON file to edit. You'll want to add your changelist item to the Teams.Core.json file.

2020-12-16 00:40 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added the **tenantId** property to [aadUserConversationMember](/graph/api/resources/aadUserConversationMember?view=graph-rest-beta&preserve-view=true) resource|
Please add periods to the ends of the sentences.

2020-12-16 00:41 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added the following methods to the [conversationMember](/graph/api/resources/conversationmember?view=graph-rest-beta&preserve-view=true) resource: [Add chat member](/graph/api/cha
The method names should be Create conversationMember, Delete conversationMember.

2020-12-16 00:42 UTC, Lauragra commented on api-reference/beta/resources/chat.md
> +|[Add chat member](../api/chat-post-members.md) | No Content and a Location header | Add a user to the chat.|
The return type is different than the response; pls. update that column.

2020-12-16 00:44 UTC, Lauragra commented on api-reference/beta/api/chat-get-members.md
> -title: "Get conversationMember"
The original title is more accurate based on our topic title conventions.

2020-12-16 00:54 UTC, bhartono commented on api-reference/beta/api/chat-post-members.md
> +|user|[conversationMember](../resources/conversationmember.md)|The user to add to the chat.|
updated

2020-12-16 01:02 UTC, opbld34 commented
Docs Build status updates of commit _[d5df604](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5df604a299a5ed7d4be2d9d092ee3c9662e04f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-ea5adc1c)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-ea5adc1c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160100498692-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vlLDavq9DhPwhlEVdBIsBUBf%2B75Fte%2F5ijCT4LmuGlQ%3D&st=2020-12-16T00%3A57%3A17Z&se=2021-01-16T01%3A02%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 19:33 UTC, bhartono commented on api-reference/beta/api/chat-get-members.md
> -title: "Get conversationMember"
@Lauragra  you want the title to be kept as Get conversationMember ?
fyi @AkJo

2020-12-16 20:09 UTC, bhartono commented on api-reference/beta/api/chat-get-members.md
> -title: "Get conversationMember"
also "Get member of a chat" is more descriptive actually, also if we apply the same rule for channel-get-member.md then we might end up with the same title for 2 different docs. 
@AkJo , what do you think ?

2020-12-16 20:09 UTC, bhartono commented on api-reference/beta/api/chat-post-members.md
> +title: "Add conversationMember"
same comment as for chat-get-members.md

2020-12-16 20:42 UTC, opbld30 commented
Docs Build status updates of commit _[17839b8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17839b881ea9c7ee1f3b3bc41034c7a234842285)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-57bfb58e)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-57bfb58e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162040453450-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a08Rlbb3D%2FTkVstFgpTtx07xGrrhljMYkqTg2S1uxhE%3D&st=2020-12-16T20%3A37%3A05Z&se=2021-01-16T20%3A42%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 20:43 UTC, bhartono commented on concepts/changelog.md
> +| Addition | beta | Added the following methods to the [conversationMember](/graph/api/resources/conversationmember?view=graph-rest-beta&preserve-view=true) resource: [Add chat member](/graph/api/cha
same reason as above.
@AkJo , thought ?

2020-12-16 21:12 UTC, AkJo commented on api-reference/beta/api/chat-get-members.md
> -title: "Get conversationMember"
@Lauragra , this is consistent with the title scheme of channel-get-members.md and team-get-members.md. 

As Benny pointed out, if the file title is changed, it would caused conflicts. Also, in the places where we have separate files per path, we want to title the files based on the name of the navigation property and non the type of the property.

2020-12-16 21:15 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added the following methods to the [conversationMember](/graph/api/resources/conversationmember?view=graph-rest-beta&preserve-view=true) resource: [Add chat member](/graph/api/cha
I don't have a preference for Create vs Add as long as there is consistency across the documentation for our entire workload.

For 'Create/Add conversation member' vs 'Create/Add chat member', that is an artifact of the fact that we want to have separate files for each of the following scenarios, and the method names and file titles reflect that:
Add member to channel
Add member to team
Add member to chat

2020-12-16 22:46 UTC, bhartono commented on api-reference/beta/api/chat-get-members.md
> -title: "Get conversationMember"
@Lauragra @AkJo im resolving this - if the change is required to Get conversationMember in order to get it checked in, please reactivate and i'll change that.

2020-12-16 22:46 UTC, bhartono commented on concepts/changelog.md
> +| Addition | beta | Added the following methods to the [conversationMember](/graph/api/resources/conversationmember?view=graph-rest-beta&preserve-view=true) resource: [Add chat member](/graph/api/cha
@Lauragra @AkJo im resolving this - if the change is required to Create / Delete conversationMember in order to get it checked in, please reactivate and i'll change that.

2020-12-17 03:43 UTC, Lauragra commented on api-reference/beta/api/chat-get-members.md
> +title: "Get member of a chat"
I'm unclear about why we renamed this file and updated the title. The original file name and title conform to our guidelines for file names and topic titles.

2020-12-17 03:45 UTC, Lauragra commented on api-reference/beta/api/chat-list-members.md
> +title: "List members of a chat"
The file name here is okay but the title should be List conversationMembers.

2020-12-17 03:48 UTC, Lauragra commented on api-reference/beta/api/chat-post-members.md
> +title: "Add member to a chat"
See the file naming guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22. The title should be "Create conversationMember".

2020-12-17 03:49 UTC, Lauragra commented on api-reference/beta/resources/aaduserconversationmember.md
> +|tenantId| string  | TenantId which the AAD User belongs to. |
AAD User -> Azure AD user

2020-12-17 03:50 UTC, Lauragra commented on api-reference/beta/resources/aaduserconversationmember.md
> +|userId| String | The guid of the user. |
GUID is an acronym so it should be in all caps, not treated as a regular word.

2020-12-17 03:52 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: List members
We list the CRUD operations in a specific order: List, Create, Get, Update, Delete. These should follow that order.

2020-12-17 04:18 UTC, opbld31 commented
Docs Build status updates of commit _[45a9a72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45a9a729e4b8cf83a1534a354a8d62bb74a25a1a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-6ae03544)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-6ae03544"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 139, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 139, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170417275768-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9zbXQIfF%2Bu3RB9bfPFJ0qaCCKB6xRaCa1ZaZgYkxyLc%3D&st=2020-12-17T04%3A13%3A41Z&se=2021-01-17T04%3A18%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 04:21 UTC, opbld31 commented
Docs Build status updates of commit _[20964f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20964f18b4dfb4f9ddf03b2fbbe85f1bf5c2368e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10954) | [Details](#user-content-de0bbbbb-329cdd6c)
[api-reference/beta/api/chat-get-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-get-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/chat-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/chat-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/api/conversationmember-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-add.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/conversationmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/api/conversationmember-delete.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/aaduserconversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/aaduserconversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get-members?view=graph-rest-beta&branch=pr-en-us-10954) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/known-issues.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/known-issues.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/known-issues?branch=pr-en-us-10954) |

<a id="de0bbbbb-329cdd6c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatMemberRelated/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 138, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 139, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 139, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170420192236-10954%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N1eyE5ZMJ5fwm9o7HqYIN5%2FKnMs5sU6Xm8oE%2BV1r0%2Bo%3D&st=2020-12-17T04%3A16%3A41Z&se=2021-01-17T04%3A21%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 04:27 UTC, Lauragra approved these changes

2020-12-17 04:34 UTC, merged