chat related doc update
microsoftgraph/microsoft-graph-docs pull request #10955
Opened 2020-12-07 17:30 UTC by bhartono

2020-12-07 17:31 UTC, opbld31 commented
Docs Build status updates of commit _[653b03c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/653b03c154b9d1e613862e9ac4beb8d3b55c17bc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4bb6e299)

<a id="4bb6e299"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012071730451518-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5k%2BdHZM9c%2FeiqKDs5v3G%2BlUYRRmCsvWP8kzFRsXAWWs%3D&st=2020-12-07T17%3A26%3A03Z&se=2021-01-07T17%3A31%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-07 22:24 UTC, AkJo approved these changes

2020-12-08 23:26 UTC, opbld32 commented
Docs Build status updates of commit _[709a37f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/709a37f83dbdad1cf30bf2db877f859ecfe24263)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-971cf88c)
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-84894718-971cf88c)
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-chats?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-4823f9d1-971cf88c)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-971cf88c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 62, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 62, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````

<a id="84894718-971cf88c"></a>
### [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="4823f9d1-971cf88c"></a>
### [api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012082325317043-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7WainDtNJKRDgj304ItvkH6vYqVT5H0nu2xC1BYLvF4%3D&st=2020-12-08T23%3A21%3A52Z&se=2021-01-08T23%3A26%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 23:55 UTC, opbld34 commented
Docs Build status updates of commit _[71358e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/71358e2339b226660f78db25df8a73854b867452)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a798db08)

<a id="a798db08"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092355310515-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cWfA4GGAft%2BcV%2Bd22aopxi0EfydZBJUKvML8DJN8TW0%3D&st=2020-12-09T23%3A50%3A56Z&se=2021-01-09T23%3A55%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 03:42 UTC, opbld31 commented
Docs Build status updates of commit _[25806a3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25806a3f56ed19fb529558c045be7837f510a88e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2e633c51)

<a id="2e633c51"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100341444551-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7LDhQBiOj0G%2BfRHOOVhpl8wIm7y9sOzGQZSaIXyMoQY%3D&st=2020-12-10T03%3A37%3A02Z&se=2021-01-10T03%3A42%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 05:14 UTC, opbld32 commented
Docs Build status updates of commit _[924657e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/924657e7aeb1722f8ce5ba8b0a2ad4dd6e679df8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-808c4559-001a83e7)
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-78e5eaee-001a83e7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-001a83e7)
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-84894718-001a83e7)
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-chats?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-4823f9d1-001a83e7)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="808c4559-001a83e7"></a>
### [api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md)
 - **Line 50, Column 11**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#chatType-values' in 'beta/resources/enums.md', did you mean '#chattype-values'?`````

<a id="78e5eaee-001a83e7"></a>
### [api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md)
 - **Line 52, Column 13**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#chatType-values' in 'beta/resources/enums.md', did you mean '#chattype-values'?`````

<a id="de0bbbbb-001a83e7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 117, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

<a id="84894718-001a83e7"></a>
### [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="4823f9d1-001a83e7"></a>
### [api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [bu [...]

2020-12-10 05:23 UTC, opbld33 commented
Docs Build status updates of commit _[7cdbbae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cdbbaeb0ad0e19f203bb2cd99e4dd040bb03410)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-808c4559-14bbd2a3)
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-78e5eaee-14bbd2a3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-14bbd2a3)
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-84894718-14bbd2a3)
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-chats?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) | [Details](#user-content-4823f9d1-14bbd2a3)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="808c4559-14bbd2a3"></a>
### [api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md)
 - **Line 50, Column 11**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#chatType-values' in 'beta/resources/enums.md', did you mean '#chattype-values'?`````

<a id="78e5eaee-14bbd2a3"></a>
### [api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md)
 - **Line 52, Column 13**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#chatType-values' in 'beta/resources/enums.md', did you mean '#chattype-values'?`````

<a id="de0bbbbb-14bbd2a3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

<a id="84894718-14bbd2a3"></a>
### [api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="4823f9d1-14bbd2a3"></a>
### [api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List chats - Microsoft Graph beta' is duplicated in: 'beta/api/chat-list.md(2,8), beta/api/user-list-chats.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List chats' is duplicated with other articles: 'beta/api/chat-list.md(10,1), beta/api/user-list-chats.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [bu [...]

2020-12-10 05:28 UTC, opbld30 commented
Docs Build status updates of commit _[b0affbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0affbfac17432a839cec47336be99d0621ac40f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-e2522011)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e2522011"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100527009138-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f9LnZc2GaJLpu8B5wzd21JzDMKc9F4ZZJBD6MfArwIo%3D&st=2020-12-10T05%3A23%3A20Z&se=2021-01-10T05%3A28%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 05:37 UTC, opbld30 commented
Docs Build status updates of commit _[649c13b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/649c13bded6915dea555a9d4bc0c752e9d3b4d42)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-e930308f)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e930308f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100536429466-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c2s8u0JWsCk9MTK13zNGei6VOD%2F5I59z0xfj5aBGg%2Bc%3D&st=2020-12-10T05%3A32%3A58Z&se=2021-01-10T05%3A37%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 05:51 UTC, opbld33 commented
Docs Build status updates of commit _[3b09ab7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b09ab730ac96695dfe13f6a75b2ab9e8a09e2e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-cfa78cee)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-cfa78cee"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100549460439-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RF5Pj%2Fda9%2BDOx4e9VNbWL8yZ7%2BXh3ThaQ3xiDzbcz%2F8%3D&st=2020-12-10T05%3A46%3A05Z&se=2021-01-10T05%3A51%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 06:05 UTC, opbld31 commented
Docs Build status updates of commit _[ac6f81f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac6f81f5395fcd452ed3e4a047c6cad6b35f7abf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-55eac81b)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-55eac81b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100604037152-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1A8ZwvFTmgvz7FJXi6Fr98%2BQR1rYEVjvA%2FJJrnDGs%2Bc%3D&st=2020-12-10T06%3A00%3A28Z&se=2021-01-10T06%3A05%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 06:17 UTC, opbld34 commented
Docs Build status updates of commit _[5e17143](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e1714372e9c721d2742fdbf1a6f6d82d5201c6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-8b52f330)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8b52f330"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100615530994-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x3qGINxoaXI9PhI%2B730%2FSjcIRo4xo6euKciPFiwYFHo%3D&st=2020-12-10T06%3A12%3A15Z&se=2021-01-10T06%3A17%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 06:41 UTC, opbld32 commented
Docs Build status updates of commit _[e97ead1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e97ead1e18f1fa1665b449bbcbdb6074c3d1a054)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-efaea4cf)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-efaea4cf"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100639482226-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2Ov3UqlJgFg8B7ihwnUeeZ3uOLer6xdGpul%2FVmNt84o%3D&st=2020-12-10T06%3A36%3A01Z&se=2021-01-10T06%3A41%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 06:52 UTC, opbld34 commented
Docs Build status updates of commit _[828c50b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/828c50bb50452d10504d8c917ed6cfe2339361bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-86b61955)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-86b61955"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100651250641-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lNijVlH2S5urNsUWu7%2F%2FBVhi%2BTDOm9qlw%2FlFmFBKeE8%3D&st=2020-12-10T06%3A47%3A43Z&se=2021-01-10T06%3A52%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 07:00 UTC, opbld31 commented
Docs Build status updates of commit _[d7631c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7631c7662fb5f270603fc66dd0a3a4b0b12cd56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-c83f74e6)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-c83f74e6"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100659332686-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ld0Doyh289g8mtiPWzDLgLbUjhb4aaiHoLt%2Bk8pRxak%3D&st=2020-12-10T06%3A55%3A43Z&se=2021-01-10T07%3A00%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 20:23 UTC, opbld31 commented
Docs Build status updates of commit _[adff54a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adff54a1ed373b6e512d2e7d08f09739cf37212f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-76ffd3e2)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-76ffd3e2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012102021373905-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CXJDJ3oGkaWjE4tESablXjmWKS%2BRzAoR4iyg8%2F2kK88%3D&st=2020-12-10T20%3A17%3A59Z&se=2021-01-10T20%3A22%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 21:52 UTC, AkJo commented on api-reference/beta/api/chat-patch.md
> +PATCH /chats/{chat-Id}
chat-id

2020-12-10 22:00 UTC, opbld33 commented
Docs Build status updates of commit _[d808aa2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d808aa2cc56f7a6b7e051493bbc058ea56864c03)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-581f3637)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-581f3637"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012102158466727-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tgP3qCadW9FfHB4Q0CsNwVG1%2Fxjc8cKQ3fRJlOLthZA%3D&st=2020-12-10T21%3A55%3A06Z&se=2021-01-10T22%3A00%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 23:25 UTC, opbld32 commented
Docs Build status updates of commit _[b8622f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8622f3712b0d0f549073b5c091f574332708b02)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-4c82c289)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4c82c289"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 56, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012102323474282-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jRg3A8C3g%2FN2T%2FOfRq0Pb7qWIXmCSN3w%2FMT3UHAI5qE%3D&st=2020-12-10T23%3A20%3A03Z&se=2021-01-10T23%3A25%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 08:52 UTC, opbld31 commented
Docs Build status updates of commit _[7981f4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7981f4b8e8062f635fc30f18b135e05db95e77a7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-85f1602e)

<a id="85f1602e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012110852241874-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pdt88uRmiLirDfWEFJxgk%2Bxx9HYlaXgkF4LMIVofot8%3D&st=2020-12-11T08%3A47%3A42Z&se=2021-01-11T08%3A52%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 08:59 UTC, opbld34 commented
Docs Build status updates of commit _[7f5f77c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f5f77ca66a4b594e83426117425deeecc5173e7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-f4ca925c)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-f4ca925c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 79, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 126, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012110857539609-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kBjCwdSeeMxnQ%2BsC%2B5g0K13EDBkHO%2FUGbGDVJcVgjm8%3D&st=2020-12-11T08%3A54%3A12Z&se=2021-01-11T08%3A59%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab [...]

2020-12-11 09:03 UTC, opbld30 commented
Docs Build status updates of commit _[a53f2ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a53f2ec6fa84d94dac59d508c852cfe5ba0f006f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-fdd352fb)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-fdd352fb"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 79, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 126, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 127, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012110901498900-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9rJr7ffCVJpnnQ1nimqh89llH1DerRW%2BGRB8NiizX7M%3D&st=2020-12-11T08%3A58%3A20Z&se=2021-01-11T09%3A03%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7 [...]

2020-12-12 06:16 UTC, bhartono commented
@Lauragra please merge

2020-12-15 11:08 UTC, AkJo commented on api-reference/beta/api/chat-patch.md
> +PATCH /chats/{chat-Id}
all lowercase

2020-12-15 11:12 UTC, opbld34 commented
Docs Build status updates of commit _[4e3f761](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e3f76132deb322d333067445a42fc3f6e5e0689)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-1ca4be2a)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1ca4be2a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151111037916-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6iYXhnb1Tk1%2BHjvtxsCtGdfHD5hq3uGhffdi2bYujoc%3D&st=2020-12-15T11%3A07%3A48Z&se=2021-01-15T11%3A12%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7 [...]

2020-12-15 12:10 UTC, opbld31 commented
Docs Build status updates of commit _[1fdaddf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fdaddf12b86a78e9cce4dc86e16ef5372004024)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-3b1be523)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3b1be523"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151208556648-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QHrrjAd99qldzzHU1wewOWoRC8Sq9ZCUCBdCn1MtUFY%3D&st=2020-12-15T12%3A05%3A10Z&se=2021-01-15T12%3A10%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd [...]

2020-12-15 12:16 UTC, opbld30 commented
Docs Build status updates of commit _[7ffefe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ffefe78e385015b5a92c933098ff6a1e183ed5f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-96507727)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-96507727"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151214155067-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=guydKsbJeb%2FIN6SM718cqoAQhhpr8%2FAZdESH6HBO66c%3D&st=2020-12-15T12%3A11%3A27Z&se=2021-01-15T12%3A16%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2 [...]

2020-12-15 21:47 UTC, opbld30 commented
Docs Build status updates of commit _[422b152](https://github.com/microsoftgraph/microsoft-graph-docs/commits/422b15288b3f997f0564d27ed1fb6451e3774039)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-a3b049e2)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a3b049e2"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152145329528-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DVQ%2FPam7JxKruBUc%2BwphvJ%2FmSojdITOd7bVLAkh3qbA%3D&st=2020-12-15T21%3A41%3A59Z&se=2021-01-15T21%3A46%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 23:05 UTC, opbld32 commented
Docs Build status updates of commit _[c4581b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4581b69a59a727c3063d93450b6b77be43e10e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-8bbc0c33)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-8bbc0c33"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152304148228-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m%2FB%2BcVxQb4q1nvWW3JlV7NAJ2hU5GlZXylOftX0gYaE%3D&st=2020-12-15T23%3A00%3A34Z&se=2021-01-15T23%3A05%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2 [...]

2020-12-15 23:23 UTC, opbld34 commented
Docs Build status updates of commit _[275a7c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/275a7c87adba98aff7f4be7e603d2b95b978f44e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-2896cf75)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-2896cf75"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152322475163-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=t4iUdemg9Q8MkjvrzzdAbJW0xLcVw4yayj1cSGOOuqM%3D&st=2020-12-15T23%3A18%3A58Z&se=2021-01-15T23%3A23%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd [...]

2020-12-15 23:25 UTC, opbld32 commented
Docs Build status updates of commit _[360cd60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/360cd603d886abb32eda5d189c7dfd882f8e8663)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-3b80b03f)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3b80b03f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152324323857-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xYQdxF27aGRAVuJ9jAAzZeZqa5qkIXv5t3O33sCuY7M%3D&st=2020-12-15T23%3A20%3A57Z&se=2021-01-15T23%3A25%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd [...]

2020-12-15 23:32 UTC, bhartono commented
@Lauragra @AkJo  can we please merge this ?

2020-12-16 21:11 UTC, opbld31 commented
Docs Build status updates of commit _[5454a40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5454a4000bf4c0189697e7cbd5f539f2f53548ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-5744d30e)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5744d30e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162109562789-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gwIjRJsrUgJaBJ39dvWi5cCtsR2HmgDub2V%2F1HKzQbU%3D&st=2020-12-16T21%3A06%3A18Z&se=2021-01-16T21%3A11%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7 [...]

2020-12-16 21:21 UTC, opbld30 commented
Docs Build status updates of commit _[b30ccd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b30ccd03850226fc0be30b18dfc9ca8fb816674e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-db6bd34c)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-db6bd34c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 88, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 137, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162120008196-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qFXbtYn54Y5Tcpb63MSGQ9C9u%2BG6vEWZTjZ9CuDAEGA%3D&st=2020-12-16T21%3A16%3A24Z&se=2021-01-16T21%3A21%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7 [...]

2020-12-16 21:22 UTC, Lauragra commented on api-reference/beta/api/chat-patch.md
> +If successful, this method returns a 200 OK response code and the chatType and the topic for 'group' chatType and members added to the chat in the response body.
Please clarify this sentence. Also, it looks like we need to update the chat resource topic to include the chatType property. Please apply bold formatting to property names.

2020-12-16 21:23 UTC, Lauragra commented on api-reference/beta/api/chat-patch.md
> +|topic|String|The title of the chat. This can only be set for a chat of type `group`.|
We should revise the description to be: "This can only be set for chats with a **chatType** value of `group`.

2020-12-16 21:23 UTC, Lauragra commented on api-reference/beta/api/chat-patch.md
> +If successful, this method returns a `200 OK response` code and the chatType and the topic for `group` chatType and members added to the chat in the response body.
Please clarify this sentence. Also, it looks like we need to update the chat resource topic to include the chatType property. Please apply bold formatting to property names.

2020-12-16 21:25 UTC, Lauragra commented on api-reference/beta/api/chat-post.md
> +The following table shows the properties that can be used with this action.
This is unclear - Post is an operation so this isn't an action topic. Also, generally we list properties when it's an update operation. Probably, what you mean is "The following table lists the properties that are required to create a chat object."

2020-12-16 21:26 UTC, Lauragra commented on api-reference/beta/api/chat-post.md
> +|topic|String|The title of the chat. This can only be set for a 'group' type chat.|
Please clarify the description for the topic property as mentioned earlier.

2020-12-16 21:28 UTC, Lauragra commented on api-reference/beta/api/chat-post.md
> +|chatType|[chatType](../resources/enums.md#chattype-values)| Type of chat entity.|
A better description for this would be: "Specifies the type of chat. Possible values are: ...". Please remove the link to the enums topic; we don't link to that topic, generally the values are defined inline in the table or in an H3 following the Properties table in the resource topic if further description is warranted. Please add this property and description, listing the values, to the chat resource topic as well.

2020-12-16 21:30 UTC, Lauragra commented on api-reference/beta/api/chat-post.md
> +If successful, this method returns a 201 Created response code and a Location header and the chatType and the topic (for 'group' chatType only if any) and members added to the chat in the response bo
This sentence is a bit unclear. Would it be accurate to say that it returns a `201 Created` response code and a Location header with a link to the chat object that was created? Note that the HTTP response code should be formatted with tic marks.

2020-12-16 21:30 UTC, Lauragra commented on api-reference/beta/api/chat-post.md
> +### Example 1: Create oneOnOne chat
In the heading, you can use a "friendly" name - one-on-one.

2020-12-16 21:31 UTC, Lauragra commented on api-reference/beta/api/chat-post.md
> +Content-Type: application/json
The response doesn't show a location header as mentioned in the Response section earlier.

2020-12-16 21:33 UTC, Lauragra commented on api-reference/beta/resources/chat.md
> +| chatType| [chatType](../resources/enums.md#chattype-values) | Type of chat entity.|
Please update the description here and add the possible values inline, formatted with tic marks around the value names.

2020-12-16 21:33 UTC, Lauragra commented on api-reference/beta/resources/chat.md
> +|[Update chat](../api/chat-patch.md) | [chat](chat.md) | Update topic of the chat.|
For readability, add the article "the" before "topic".

2020-12-16 21:34 UTC, Lauragra commented on changelog/changelog.json
> +          "Description": "Added the **chatType** property to [chat](https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta) resource",
Please add periods to the ends of all descriptions.

2020-12-16 21:34 UTC, Lauragra commented on changelog/changelog.json
> +      "CreatedDateTime": "2020-11-03T21:46:49.407Z",
Change the date to 12/16.

2020-12-16 21:35 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added [Get chat between user and app](/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&preserve-view=true) method to the new [userScopeTeamsAppInstallation](
Is this part of this PR or a different one?

2020-12-16 21:48 UTC, bhartono commented on concepts/changelog.md
> +| Addition | beta | Added [Get chat between user and app](/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&preserve-view=true) method to the new [userScopeTeamsAppInstallation](
this is probably due to a merge - leaving it there since it seems to be there

2020-12-16 22:14 UTC, bhartono commented on api-reference/beta/api/chat-post.md
> +|chatType|[chatType](../resources/enums.md#chattype-values)| Type of chat entity.|
updated as per suggestion also added to chat.md

2020-12-16 22:18 UTC, bhartono commented on api-reference/beta/api/chat-post.md
> +The following table shows the properties that can be used with this action.
i actually copy paste part of this sentence from other doc. Will update this as per your suggestion :)

2020-12-17 03:56 UTC, opbld31 commented
Docs Build status updates of commit _[7299b5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7299b5f12d934f2c95d2ccdd6b80901cf4980323)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-e4defb73)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e4defb73"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 93, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170355292910-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kl%2FRbeE3EbCZvkzx3jssePvGf4lfiKiAFCHe3PjQ9CE%3D&st=2020-12-17T03%3A51%3A42Z&se=2021-01-17T03%3A56%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope= [...]

2020-12-17 03:58 UTC, opbld31 commented
Docs Build status updates of commit _[bb2b4df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bb2b4dfae055639c90b5cc7c0467f2121a7d4ba3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-afa487cc)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-afa487cc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 93, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170356530346-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e4lp92AoSe%2BraQwZrcMOboqqCWMLWZ%2BZqpL5letmLTg%3D&st=2020-12-17T03%3A53%3A03Z&se=2021-01-17T03%3A58%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scop [...]

2020-12-17 04:03 UTC, Lauragra commented on api-reference/beta/api/chat-patch.md
> +If successful, this method returns a `200 OK response` code and the chatType and the topic for `group` chatType and members added to the chat in the response body.
I'm still not clear about what this sentence is conveying. Can you simplify it? Is it sufficient to say that it returns an updated **chat** resource in the response body? Or, to be more specific, you can say "... and a **chat** object with an updated **topic** value."

2020-12-17 04:10 UTC, opbld31 commented
Docs Build status updates of commit _[923da92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/923da922c8a1b2b31107c6eccc83a82d628dba0e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-3391c1ec)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3391c1ec"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 93, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 73, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170408543719-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VssFbgUZagFWR7r%2FBcBLDShuAChiCjgc1FOes2Ugbs4%3D&st=2020-12-17T04%3A05%3A06Z&se=2021-01-17T04%3A10%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope= [...]

2020-12-17 04:13 UTC, AkJo commented on api-reference/beta/api/chat-patch.md
> +If successful, this method returns a `200 OK response` code and the chatType and the topic for `group` chatType and members added to the chat in the response body.
:D. I think he meant to say that you will 'get back the updated chat resource in the response body.'

2020-12-17 04:13 UTC, Lauragra commented on changelog/changelog.json
> +    {
This is the wrong changelog file to edit - you want to edit the individual changelog file for the workload, so in this case it's Teams.Core.json.

2020-12-17 04:14 UTC, Lauragra requested changes
Some of my comments hadn't been resolved in this one - pls. take a look.

2020-12-17 04:37 UTC, AkJo commented on api-reference/beta/api/chat-patch.md
> +If successful, this method returns a `200 OK response` code and the chatType and the topic for `group` chatType and members added to the chat in the response body.
Updated.

2020-12-17 05:00 UTC, AkJo commented on api-reference/beta/api/chat-post.md
> +The following table shows the properties that can be used with this action.
Updated.

2020-12-17 05:02 UTC, AkJo commented on api-reference/beta/api/chat-post.md
> +### Example 1: Create oneOnOne chat
Updated.

2020-12-17 05:03 UTC, AkJo commented on api-reference/beta/api/chat-post.md
> +Content-Type: application/json
Updated.

2020-12-17 05:14 UTC, AkJo commented on api-reference/beta/resources/chat.md
> +| chatType| [chatType](../resources/enums.md#chattype-values) | Type of chat entity.|
Updated.

2020-12-17 05:18 UTC, AkJo commented on concepts/changelog.md
> +| Addition | beta | Added [Get chat between user and app](/graph/api/userscopeteamsappinstallation-get-chat?view=graph-rest-beta&preserve-view=true) method to the new [userScopeTeamsAppInstallation](
Updated.

2020-12-17 05:26 UTC, bhartono commented
> Some of my comments hadn't been resolved in this one - pls. take a look.

@Lauragra apologize, somehow my vs didnt push the changes earlier before i left :(. I resolved as i fixed on my local one at a time. @AkJo is making some change at the same docs now.

2020-12-17 05:26 UTC, opbld30 commented
Docs Build status updates of commit _[a5fa9a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5fa9a013e93989ced74b772e39f2a76151ef4d4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a6e134b0)

<a id="a6e134b0"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170526252505-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QvBlUkKluz44cAuNwdMetJS%2BOEI%2BYQ8F2vIA1tMYr3Q%3D&st=2020-12-17T05%3A21%3A45Z&se=2021-01-17T05%3A26%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 05:27 UTC, opbld34 commented
Docs Build status updates of commit _[607db4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/607db4b715e4599a8836b3df53469486d71bb958)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-73f1720a)

<a id="73f1720a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170527107958-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GLNetObreGbhBUgEdl2uiJz3gTBb%2Fvn2AQtEx5v4Obo%3D&st=2020-12-17T05%3A22%3A29Z&se=2021-01-17T05%3A27%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 05:32 UTC, bhartono commented on api-reference/beta/api/chat-post.md
> +|topic|(Optional) String|The title of the chat. The chat title can be provided only if the chat is of 'group' type.|
this should be something like below as per Laura's recommendation (the quote on group seems wrong):

|topic|String|The title of the chat. This can only be set for chats with a **chatType** value of `group`.|

2020-12-17 05:35 UTC, bhartono commented on api-reference/beta/api/chat-post.md
> +If successful, this method returns a 201 Created response code and the newly created **chat** resource in the response body.
it should be updated to:

If successful, this method returns a `201 Created` response code and a Location header and the newly created [chat](../resources/chat.md) in the response body.

2020-12-17 05:40 UTC, opbld34 commented
Docs Build status updates of commit _[8e2c8b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e2c8b6c96870b6dbc440fbe9e5141057e6ff7cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-102b1dbc)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/changelog.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/changelog.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-102b1dbc"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 101, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 79, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 148, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 149, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 149, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170539204304-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=klpg34n9L6Z4YwreMLM6tb%2FfxG2vFZLsyxhfhIoECEc%3D&st=2020-12-17T05%3A35%3A36Z&se=2021-01-17T05%3A40%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope [...]

2020-12-17 05:49 UTC, opbld30 commented
Docs Build status updates of commit _[e2c9d76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2c9d76a46dd57d466502ffdb7113956c921b8eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10955) | [Details](#user-content-de0bbbbb-7d9eb2e3)
[api-reference/beta/api/chat-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/chat-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/chat-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/api/user-list-chats.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/api/user-list-chats.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-get?view=graph-rest-beta&branch=pr-en-us-10955) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7d9eb2e3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/chatRelated/concepts/changelog.md)
 - **Line 101, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 79, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 148, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 149, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 149, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 150, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170548462953-10955%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uYaVX5KTqgJcP22YsFI3JZnm42AGBvEJXiOdXnE8gdY%3D&st=2020-12-17T05%3A44%3A58Z&se=2021-01-17T05%3A49%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;ca [...]

2020-12-17 05:50 UTC, bhartono commented on api-reference/beta/api/chat-post.md
> +>**Note:** The response object shown here might be shortened for readability.
it needs Location header in the sample response

Location: https://graph.microsoft.com/beta/chats('19:82fe7758-5bb3-4f0d-a43f-e555fd399c6f_8c0a1a67-50ce-4114-bb6c-da9c5dbcf6ca@unq.gbl.spaces')

2020-12-17 05:50 UTC, bhartono commented on api-reference/beta/api/chat-post.md
> +>**Note:** The response object shown here might be shortened for readability.
it needs Location header in the sample

Location: https://graph.microsoft.com/beta/chats('19:1c5b01696d2e4a179c292bc9cf04e63b@thread.v2')

2020-12-17 05:54 UTC, bhartono commented on api-reference/beta/api/chat-patch.md
> +If successful, this method returns a `200 OK response` code and the updated **chat** resource in the response body.
this should be something like

If successful, this method returns a `200 OK` response code and the [chat](../resources/chat.md) resource created in the response body.

2020-12-17 05:55 UTC, Lauragra approved these changes

2020-12-17 05:56 UTC, merged