regionalAndLanguageSettings update to add translation preferences
microsoftgraph/microsoft-graph-docs pull request #10961
Opened 2020-12-08 02:33 UTC by netstruc65

Updated regionalAndLanguageSettings resource, get, and update API files, and changelog to reflect new translation preferences schema changes.

2020-12-08 02:34 UTC, opbld31 commented
Docs Build status updates of commit _[c8933c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8933c414cee4b87a06b8bad17ad578be7efd4f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-8b037514)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-8b037514)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-8b037514)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-8b037514)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-8b037514)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-8b037514)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |

<a id="d4ec33d8-8b037514"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'settings'.`````

<a id="b19d64c2-8b037514"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'settings'.`````

<a id="b5af57ee-8b037514"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'settings'.`````

<a id="f04b6964-8b037514"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'settings'.`````

<a id="ff2883f8-8b037514"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'settings'.`````
 - **Line 21, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#translationPreferences-values' in 'beta/resources/translationPreferences.md'.`````
 - **Line 22, Column 24**: **[Warning-file-not-found]** `````Invalid file link: 'translationOverride.md'.`````

<a id="de0bbbbb-8b037514"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080233204026-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Go9up74aNrZtH8eEOlNh2LaldxXgbiaPDgmfzt3yvAQ%3D&st=2020-12-08T02%3A29%3A29Z&se=2021-01-08T02%3A34%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/fa [...]

2020-12-08 02:48 UTC, opbld31 commented
Docs Build status updates of commit _[b0a2882](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0a28825a7233fe72f629627eaf2f1d7b0cfb704)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-a77cd3f4)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-a77cd3f4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-a77cd3f4)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |

<a id="f04b6964-a77cd3f4"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'settings'.`````

<a id="ff2883f8-a77cd3f4"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 21, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#translationBehavior-values' in 'beta/resources/translationPreferences.md', did you mean '#translationbehavior-values'?`````
 - **Line 22, Column 24**: **[Warning-file-not-found]** `````Invalid file link: 'translationLanguageOverride.md'.`````

<a id="de0bbbbb-a77cd3f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080246385378-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WL3cCEWCfTJGpKBfMTNZGZkBYxnUJPRTMseeQJPwupU%3D&st=2020-12-08T02%3A43%3A01Z&se=2021-01-08T02%3A48%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 02:58 UTC, opbld33 commented
Docs Build status updates of commit _[cbc48fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cbc48fa298e1438aaa4ad0427c65ae9ee5b0d122)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-756fbd0c)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-756fbd0c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-756fbd0c)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="89f01f1f-756fbd0c"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 22, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#translationBehavior-values' in 'beta/resources/translationPreferences.md', did you mean '#translationbehavior-values'?`````

<a id="ff2883f8-756fbd0c"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 21, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#translationBehavior-values' in 'beta/resources/translationPreferences.md', did you mean '#translationbehavior-values'?`````

<a id="de0bbbbb-756fbd0c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080256563414-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4Vxjcb3dqxD8IvLz91GYE5Dh7OURzqRmbC75YOeFOVg%3D&st=2020-12-08T02%3A53%3A22Z&se=2021-01-08T02%3A58%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 03:01 UTC, opbld32 commented
Docs Build status updates of commit _[087da30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/087da30c7833d3e4cbba1ce3dbbc6765ca58fa48)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-f89d26e3)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-f89d26e3)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="89f01f1f-f89d26e3"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 22, Column 24**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#translationBehavior-values' in 'beta/resources/translationPreferences.md', did you mean '#translationbehavior-values'?`````

<a id="de0bbbbb-f89d26e3"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080300071210-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7p%2BwyK1j6nIYp%2FpYd%2Bjq9qFJ2bJJzE2pOVF%2FVGBK33c%3D&st=2020-12-08T02%3A56%3A29Z&se=2021-01-08T03%3A01%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 03:05 UTC, opbld34 commented
Docs Build status updates of commit _[82a3d8e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82a3d8e81912410d24a9f48b0c8d4035bec589ef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-52d54f41)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-52d54f41"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080304140260-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FaZxZuN4uG5aooOzIEj90HnvX9XOZl21Elk8lFQbZ3o%3D&st=2020-12-08T03%3A00%3A34Z&se=2021-01-08T03%3A05%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 03:14 UTC, opbld31 commented
Docs Build status updates of commit _[c219a79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c219a79bbbfe5631fbaf6cccd1679a5c9ff0e021)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-26f7b8e4)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-26f7b8e4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080313092697-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fCabz8rF3wORPIDh68DFASEL%2F9owCKgnF%2Fu%2BbNoArTU%3D&st=2020-12-08T03%3A09%3A33Z&se=2021-01-08T03%3A14%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 03:30 UTC, netstruc65 commented
@angelgolfer-ms can you do the tech review for this PR?

2020-12-08 03:36 UTC, opbld30 commented
Docs Build status updates of commit _[b5cc46c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5cc46c2659f0533efd0e0ea8a7b7b1eb90bace1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-ed1e5e62)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-ed1e5e62"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080335130894-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=521fjj90CMbYxdr2CDb061N4MPabOoy8Fifo%2Bs91igY%3D&st=2020-12-08T03%3A31%3A43Z&se=2021-01-08T03%3A36%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 03:56 UTC, opbld31 commented
Docs Build status updates of commit _[8106e0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8106e0d56914c35ef3cb8d53f60f47ffc91c2bfe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-c2eedd5f)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-c2eedd5f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012080355029151-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ctzhf1LNDR69LN8ruT1FfH09qqVCTkZwxdKQ4sBZXfg%3D&st=2020-12-08T03%3A51%3A22Z&se=2021-01-08T03%3A56%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 16:54 UTC, opbld32 commented
Docs Build status updates of commit _[dddd0f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dddd0f55c7f76020a0f874fb9a3905377b882e22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-321d8e4c)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-321d8e4c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012081652407030-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XTz%2BzZ9cdjJ%2BdB%2F9RXdCitOZ64iHWgJLYQ5KTjTpaI4%3D&st=2020-12-08T16%3A49%3A01Z&se=2021-01-08T16%3A54%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-08 16:59 UTC, opbld33 commented
Docs Build status updates of commit _[6cc0287](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6cc02876571c9ad11e7e3b94f46cfca8c21aa193)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-747f48ac)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-747f48ac"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012081657561942-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U0HGevczGCz%2Bl4z579HUotY2ob7DCuPiUD%2BQWzEsYqc%3D&st=2020-12-08T16%3A54%3A14Z&se=2021-01-08T16%3A59%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 17:28 UTC, netstruc65 commented
@angelgolfer-ms can you do the tech review on this PR?

2020-12-17 00:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationPreferences.md
> +|untranslatedLanguages|String collection| The list of languages the user does not need translated. This is computed from [regionalAndLanguageSettings](regionalandlanguagesettings.md) authoring langua
Line 23:
The concept of "neutral language culture" is not necessarily well-known to customers, so it's worth providing some example. Also, the term "neutral" should apply to "culture", not to "language". In this context, language is already neutral. But "culture" can be neutral (without country/region association), or "specific" (that's the term in contrast with "neutral").
Based on your example response in regionalandlanguagesettings-get.md that returns just the 2-letter language ISO code for the French language, the second last sentence of the description should say:
"This property returns one or more neutral culture values that reflect the language and exclude any country or region association. For example, "fr" for the neutral French culture, but not "fr-FR" for the French culture in France."

2020-12-17 00:27 UTC, opbld34 commented
Docs Build status updates of commit _[379c7d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/379c7d70543e029b7d3bddd6282f74916307f9b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-0a2a612f)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-0a2a612f"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 143, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 143, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170026215174-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fsMNJMELRwuRdXdLGcSy%2BgWdsDd%2BRxaxvCXzBqhqE8U%3D&st=2020-12-17T00%3A22%3A50Z&se=2021-01-17T00%3A27%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 01:23 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationLanguageOverride.md
> +---
Please keep filenames all lower case.
This comment applies to all 3 new files in this PR.

2020-12-17 01:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationLanguageOverride.md.txt
> +---
@netstruc65 , please delete this topic from your PR. Was this an accident?

2020-12-17 01:29 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationPreferences.md
> +|translationBehavior  |[String](#translationbehavior-values)  	    |The user's preferred translation behavior.<br><br>Returned by default. Not nullable. |
Line 21:
According to [option 2](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic) in the CDK enumerations topic, the Type column should use the enum name as the link text.
I'm going to try this to see if this triggers API Doctor problem.

2020-12-17 01:29 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationLanguageOverride.md
> +|translationBehavior  |[String](translationPreferences.md#translationbehavior-values)        |The override behavior for the language tag.<br><br>Returned by default. Not nullable.|
Line 22:
Line 21:
According to [option 2](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic) in the CDK enumerations topic, the Type column should use the enum name as the link text.
I'm going to try this to see if this triggers API Doctor problem.

2020-12-17 01:34 UTC, opbld32 commented
Docs Build status updates of commit _[6acfc8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6acfc8fa10c4f4ab48b4eab9aaaa67d677ca29a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-8c3199da)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-8c3199da"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 142, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 143, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 143, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012170133283399-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=70ql8OtnQuTWXGl%2FTsBL57cRIFJ3%2FUQgz64KIwN1R6M%3D&st=2020-12-17T01%3A29%3A41Z&se=2021-01-17T01%3A34%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-17 02:07 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Change | beta | Added the [translationPreferences](/graph/api/resources/translationLanguageOverride) property to the [regionalAndLanguageSettings](/graph/resources/regionalandlanguagesettings) reso
Line 94:
I think the change type is considered an addition. Please update.

2020-12-17 02:10 UTC, angelgolfer-ms commented on concepts/changelog.md
> +
Lines 95 and 96:
Please delete these two rows as they are purely updates to examples in docs.

2020-12-17 02:29 UTC, angelgolfer-ms commented on concepts/changelog.md
> +
Also:
(1) If this PR is publishing in January, then please move it to the January section.
(2) Please create the corresponding changelog json as well.
At the moment, the CDK has the following two topics that contain some info about the changelog json:
https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103186/Graph-doc-stub-generator-tool?anchor=update-the-json-changelog
https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=guidelines-for-workload-changelog-json-files-only

2020-12-17 02:32 UTC, angelgolfer-ms requested changes
@netstruc65 , I applied some of my feedback directly to your PR, just to tighten the turnaround for this PR and save the number of iterations. Please take a look at what my updates in my commit in this PR, and let me know if you see a problem.
There are however other comments that describe open issues for you to follow up. Please take a look at those comments as well.

2020-12-17 02:54 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Change | beta | Added the translationPreference property to the [regionalAndLanguageSettings-get](/graph/api/regionalandlanguagesettings-get) JSON example |
Lines 92-94:
Since all these updates apply to the beta version only, the links in all these lines should go to the beta version. Specifically, please add 2 query parameters to each link, like what you see in the links in the preceding table in changelog.md: ?view=graph-rest-beta&preserve-view=true
OPS linking guidance: https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-specific-versions

If you don't specify the version in your link, when you click the link, you'll see a alert message at the top of the screen about the destination of the link doesn't exist and there's a fallback. The alert is not a good experience for customers.

2020-12-17 11:11 UTC, opbld30 commented
Docs Build status updates of commit _[05cd499](https://github.com/microsoftgraph/microsoft-graph-docs/commits/05cd499941b9f95af4fac01f4b9fd82227e9d275)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) | [Details](#user-content-de0bbbbb-3bc96348)
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

<a id="de0bbbbb-3bc96348"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md)
 - **Line 101, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 107, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/channelModerationSettings2?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-update-configuration?view=graph-rest-beta`````
 - **Line 42, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 79, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 164, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 165, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 165, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 166, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 166, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012171110081236-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7tbAqHCekcseZT%2FXKLD8B%2B%2FAwdfXgISaCT3F%2FD9u2gM%3D&st=2020-12-17T11%3A06%3A23Z&se=2021-01-17T11%3A11%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch [...]

2020-12-17 20:42 UTC, angelgolfer-ms commented on concepts/changelog.md
> +
Update: I added some detailed help content last night to the CDK for authors who have to manually create the changelog JSON. Hope that content will be more helpful to you.
https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=guidelines-for-workload-changelog-json-files-only

2021-01-05 18:04 UTC, opbld31 commented
Docs Build status updates of commit _[710744e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/710744ef4f57fe18651bfcaf3dea54b8b5af543a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-212a6a31)

<a id="212a6a31"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051804055279-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cdu%2B6z1dJc%2F75J%2FZlgrTTnzYXCvb%2BJmVm%2Bxd70HoG%2FM%3D&st=2021-01-05T17%3A59%3A23Z&se=2021-02-05T18%3A04%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[931c662](https://github.com/microsoftgraph/microsoft-graph-docs/commits/931c6623ee094c7e53c5075e4865ab55e2b1cfad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.Users.JSON](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.Users.JSON) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051830049943-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B%2B3PZWr4xpR9%2F4%2FHUN%2F1%2FZ3CgOF6Ub9lIdLNm%2FQX%2BZs%3D&st=2021-01-05T18%3A26%3A24Z&se=2021-02-05T18%3A31%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 18:36 UTC, opbld31 commented
Docs Build status updates of commit _[c237baa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c237baac473e10190d8b78e59b642f14a475d6a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.Users.JSON](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.Users.JSON) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051835205525-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5sXnLRrm8mmBJ2uTm9VBCNyZqtkzosJqNJYpb0nb1eE%3D&st=2021-01-05T18%3A31%3A37Z&se=2021-02-05T18%3A36%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-06 02:52 UTC, angelgolfer-ms commented on changelog/Microsoft.Users.JSON
> +{
Per our Teams chat, please add the JSON changelog items to the Microsoft.DirectoryServices.json file, where the pre-existing user resource changelog items are.

2021-01-06 02:54 UTC, angelgolfer-ms commented on changelog/Microsoft.Users.JSON
> +{
Please also see the CDK topic (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties) to update the ChangedApiName and Target properties in the JSON.

2021-01-06 03:03 UTC, angelgolfer-ms commented on concepts/changelog.md
> +
Line 28: The first link for translationPreferences - shouldn't that also go to the beta version?
As a reminder: you can please verify any MD topics in your PR by going to the staging site. In the case of the markdown changelog, broken links are a common issue. Clicking these links on the staging site will tell whether the links are set up properly or not. (Your build results on Github include the link for each topic that's been updated in your commit to the corresponding topic on the staging site.)

2021-01-06 03:05 UTC, angelgolfer-ms requested changes
Please see my earlier feedback on Teams, and comments in this PR, regarding the changelog files still.

2021-01-08 23:03 UTC, opbld34 commented
Docs Build status updates of commit _[a60d54e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a60d54e4360acdf092a3b66cb36db64ec71644a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.Users.JSON](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.Users.JSON) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082301306103-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yYWFG5cxPc13dY3QJLUbE9rc1NV1bamICqH8uFMVzb8%3D&st=2021-01-08T22%3A58%3A14Z&se=2021-02-08T23%3A03%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 23:26 UTC, opbld30 commented
Docs Build status updates of commit _[43d3e48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43d3e48da192c4cfa8f7e9e7b2660ce64cfbe454)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e4c309de)

<a id="e4c309de"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082326219997-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hOOQRUevbLaqJaEu3669Z2XSdrR8ykt8PxLww3v8L%2FE%3D&st=2021-01-08T23%3A21%3A43Z&se=2021-02-08T23%3A26%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 23:31 UTC, opbld33 commented
Docs Build status updates of commit _[f01ab48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f01ab48f5b049ed84be80d3f7098b23cb18d017a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082329580489-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pDShvZgCOwClJo9HF2MZXPSnIUxv0XseM2Zxmn5vIp8%3D&st=2021-01-08T23%3A26%3A11Z&se=2021-02-08T23%3A31%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 23:33 UTC, opbld30 commented
Docs Build status updates of commit _[1513101](https://github.com/microsoftgraph/microsoft-graph-docs/commits/151310128e71aa27602806d576eeda60d02a8ee9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082332412112-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FDoukHm742HDhzT%2FOgTza%2FEcEJZRSxdeMNll6Wrl0vM%3D&st=2021-01-08T23%3A28%3A47Z&se=2021-02-08T23%3A33%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 23:38 UTC, opbld32 commented
Docs Build status updates of commit _[5258397](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5258397c7939525d3cc6bf3757c2d824cc6ffecb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082337209979-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zZwX1zUilQDfwoVZ6K7KNYBc2CYeI7WSJD5N%2BRuz%2B8k%3D&st=2021-01-08T23%3A33%3A26Z&se=2021-02-08T23%3A38%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 23:44 UTC, opbld33 commented
Docs Build status updates of commit _[391acd4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/391acd4e10d6fc2c0bfb2e585fa86b0ff41d6723)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082343130016-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TrS%2FqE7UB898U6%2BY2ZVxMS3a1Gd%2F0S0W56cACMna07E%3D&st=2021-01-08T23%3A39%3A29Z&se=2021-02-08T23%3A44%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 23:59 UTC, opbld30 commented
Docs Build status updates of commit _[41328a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/41328a524788b0e1f2dee0a0e6118ac81281a68a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101082358288703-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8T%2FYtsGpDnwf4HC%2BBybFoMTYnw3NBy1OSgXpfZ4h%2BpY%3D&st=2021-01-08T23%3A54%3A39Z&se=2021-02-08T23%3A59%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 02:08 UTC, angelgolfer-ms commented on concepts/changelog.md
> +| Addition | beta | Added the [translationPreferences](/graph/api/resources/translationLanguageOverride?view=graph-rest-beta&preserve-view=true) property to the [regionalAndLanguageSettings](/graph/r
Line 40: 2 issues, FYI:

- translationPreferences is a property, so there shouldn't be any link to it.
- The link to regionalAndLanguageSettings is also incorrect, the first part of the link should be /graph/api/resources/..., not /graph/resources/...
For efficiency so that we can wrap this PR up, I am fixing them on your behalf.

2021-01-09 02:51 UTC, angelgolfer-ms commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Addition",
Lines 10, 18, and 26:
Please take a look at the CDK section (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=linking-from-the-json-changelog) to find out how to link from the JSON changelog to a reference topic. Basically that should just be a normal HTTP link, because that new changelog is a regular web page on developer.microsoft.com, it's not an MD file on docs.microsoft.com.

2021-01-09 02:54 UTC, angelgolfer-ms commented on changelog/Microsoft.DirectoryServices.json
> +          "ChangeType": "Addition",
FYI for efficiency so that we can wrap up this PR, I made the fixes on your behalf.

2021-01-09 02:54 UTC, angelgolfer-ms commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "regionalAndLanguageSettings"
Line 24: When adding a new property, the ChangedApiName should be the property name.

Line 26: In general, we can't and shouldn't attempt to link to a property, because it's just documented in a table row. So there shouldn't be a link to translationPreferences.

For efficiency so that we can wrap up this PR, I made the fixes on your behalf.

2021-01-09 03:00 UTC, angelgolfer-ms commented on changelog/Microsoft.DirectoryServices.json
> +    },
Line 35:
As described in the CDK (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=additional-changelog-record-properties), there are specific supported values for the WorkloadArea and SubArea properties. You should please refer to the spreadsheet referenced in that CDK section to verify what you can specify as a value for SubArea.
In this case, there are currently no supported values for SubArea for the "Users" WorkloadArea. 

FYI, for efficiency so that we can wrap up this PR, I set SubArea to "", on your behalf.

2021-01-09 03:20 UTC, opbld31 commented
Docs Build status updates of commit _[f0f1ff9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0f1ff9e9a90084a732535dd89012ec6433158bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101090318486677-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NuhEWD59pkmmVggyqqnrZXZuwx4X%2FQGLVW7uR%2Fgl82M%3D&st=2021-01-09T03%3A15%3A08Z&se=2021-02-09T03%3A20%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 03:21 UTC, opbld32 commented
Docs Build status updates of commit _[83432f5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83432f5a3b6bd4fe5e7bd3f879aaa1d43cdabf84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101090319070971-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q7gnVf2D%2BpTd%2BjFgU43wgPeKMd%2FoCXRnAZVbL4qzj%2BI%3D&st=2021-01-09T03%3A16%3A30Z&se=2021-02-09T03%3A21%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-09 03:24 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>          - name: Get
FYI @netstruc65 , I made this change in the TOC so to get around the default behavior imposed by docs.microsoft.com in all TOCs. It's a better experience to have the TOC title matching more closely the corresponding topic title, in this case in the new lines 436 and 437, matching the actual resource name regionalAndLanguageSettings.

Desirably all partners should apply this work around to their parts of the TOC. The behavior was introduced by the DevRelations team across docs.microsoft.com, when we already have thousands of topics in the reference, that's why it hasn't been done.

2021-01-09 03:25 UTC, angelgolfer-ms approved these changes
@netstruc65 , I added a few comments in the two changelog files about a few remaining issues. I also went ahead to fix them on your behalf, so that we can wrap this PR up. Please take a look at the before and after of my commit https://github.com/microsoftgraph/microsoft-graph-docs/pull/10961/commits/f0f1ff9e9a90084a732535dd89012ec6433158bf, so that in the future, you can do the similar in other PRs.

2021-03-03 23:07 UTC, opbld30 commented
Docs Build status updates of commit _[5bc4711](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5bc47110cb6bbfc9e48ce998bce49f810544cf74)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-066c62bb)

<a id="066c62bb"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103032307133155-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eOc%2BMxvMK%2BmJ0SXc80KDgajZIZxTfC%2BBhj5dy1Ory4g%3D&st=2021-03-03T23%3A02%3A32Z&se=2021-04-03T23%3A07%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 23:36 UTC, opbld33 commented
Docs Build status updates of commit _[506820b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/506820b923bf086a603a3a7ec14ca69303f3b10c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3b011c82)

<a id="3b011c82"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103032336314562-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eJON9DJ8H%2BRMCmy%2BfOQJ7vbcY1S7C9HCzfWWtLkRl%2Bg%3D&st=2021-03-03T23%3A31%3A46Z&se=2021-04-03T23%3A36%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 23:55 UTC, opbld33 commented
Docs Build status updates of commit _[9e123e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e123e065df717a68a89b5c6bfac4ed42c8cf667)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-8bf0a1a9)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-8bf0a1a9)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-8bf0a1a9)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-8bf0a1a9)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-8bf0a1a9)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-8bf0a1a9)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-8bf0a1a9"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-8bf0a1a9"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-8bf0a1a9"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-8bf0a1a9"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-8bf0a1a9"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ff2883f8-8bf0a1a9"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103032354113676-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s1BEuPAsTc68bBD3Pv0BU7Ajt4KoHYcYJlepChk%2FNxA%3D&st=2021-03-03T23%3A50%3A20Z&se=2021-04-03T23%3A55%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or externa [...]

2021-03-04 00:04 UTC, opbld33 commented
Docs Build status updates of commit _[d0606a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d0606a21ca90f45477158ecf1f7e690d3afb8e03)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-edf64141)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-edf64141)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-edf64141)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-edf64141)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-edf64141)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-edf64141)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-edf64141"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-edf64141"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-edf64141"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-edf64141"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-edf64141"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ff2883f8-edf64141"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040003136859-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RvLltfVWF0SfVNw083LiqSZkU9SouZR5SE9Q%2BgALnf8%3D&st=2021-03-03T23%3A59%3A21Z&se=2021-04-04T00%3A04%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or externa [...]

2021-03-04 01:31 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationPreferences.md
> +  "baseType": "",
Line 42:
Please remove this line. We did a fix to the stub generator recently to make sure it doesn't insert this line ("baseType": "") in their JSON representation section, if the resource doesn't have any base type. A line like that actually interfered with SDK generation.

The CDK topic has been correct: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-03-04 01:32 UTC, angelgolfer-ms commented on api-reference/beta/resources/translationLanguageOverride.md.txt
> +  "baseType": "",
Line 31:
Please remove this line. We did a fix to the stub generator recently to make sure it doesn't insert this line ("baseType": "") in their JSON representation section, if the resource doesn't have any base type. A line like that actually interfered with SDK generation.

The CDK topic has been correct: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103189/Set-up-for-API-Doctor?anchor=json-element-descriptions

2021-03-04 01:34 UTC, angelgolfer-ms reviewed
@netstruc65 , in case you haven't taken a look at your latest API Doctor errors - please take a look at my comments. After fixing them, this PR should be good to be published, assuming nothing has changed on the product/API side since my PR approval :-).

2021-03-05 02:06 UTC, Lauragra commented
@netstruc65 , please fix the API Doctor validation error so we can merge this PR.

2021-03-05 03:00 UTC, opbld32 commented
Docs Build status updates of commit _[a1e1ff8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1e1ff8a5f95bb8dd1f89362d247f928253d933d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-c6fa4834)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-c6fa4834)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-c6fa4834)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-c6fa4834)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-c6fa4834)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-c6fa4834)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-c6fa4834"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-c6fa4834"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-c6fa4834"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-c6fa4834"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-c6fa4834"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ff2883f8-c6fa4834"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050259336362-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Sx6fxqMpsWZcCP1fKXj9kBoszOV%2BxAoAjqZ0CrAW5r8%3D&st=2021-03-05T02%3A55%3A46Z&se=2021-04-05T03%3A00%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or externa [...]

2021-03-05 03:11 UTC, opbld32 commented
Docs Build status updates of commit _[c37dc19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c37dc19208fe6c8681a63ae81ad1615266367e53)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-20b37251)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-20b37251)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-20b37251)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-20b37251)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-20b37251)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-20b37251)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-20b37251"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-20b37251"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-20b37251"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-20b37251"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-20b37251"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ff2883f8-20b37251"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050310228651-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CoKP%2F86nxrPvowNP5OXmif0hRfNdvadRhiS3aXHOhHw%3D&st=2021-03-05T03%3A06%3A36Z&se=2021-04-05T03%3A11%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or externa [...]

2021-03-05 03:13 UTC, netstruc65 commented
@Lauragra all checks passed. Ready merge the PR and publish.

2021-03-05 03:14 UTC, netstruc65 commented
Thanks Laura, fixed those two issues, API doctor check passed.

From: Laura Graham <notifications@github.com>
Sent: Thursday, March 4, 2021 6:07 PM
To: microsoftgraph/microsoft-graph-docs <microsoft-graph-docs@noreply.github.com>
Cc: Jason Brown (GSX) <jasonbro@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [microsoftgraph/microsoft-graph-docs] regionalAndLanguageSettings update to add translation preferences (#10961)


@netstruc65<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnetstruc65&data=04%7C01%7Cjasonbro%40microsoft.com%7Ca84d7fa8adb04874cf0a08d8df7b5563%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637505068110745993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=fhe8WvHqKE9cEC11ersy7tMWyfCWeEcn2SDLzyK7wmY%3D&reserved=0> , please fix the API Doctor validation error so we can merge this PR.

-
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoftgraph%2Fmicrosoft-graph-docs%2Fpull%2F10961%23issuecomment-791091322&data=04%7C01%7Cjasonbro%40microsoft.com%7Ca84d7fa8adb04874cf0a08d8df7b5563%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637505068110755986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u27cSiVLHABoOQ2YELD537kjW3lzAHYP5HK4kEBETRE%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAO4D2JCL3QNGNI3KN65BG4TTCA4DPANCNFSM4URKEXHA&data=04%7C01%7Cjasonbro%40microsoft.com%7Ca84d7fa8adb04874cf0a08d8df7b5563%7C72f988bf86f141af91ab2d7cd011db47%7C0%7C0%7C637505068110755986%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Ri%2B8D%2B4ZK2uJ8E2mv481lkaaszJvADym6%2FEcNfFMGCQ%3D&reserved=0>.

2021-03-05 03:52 UTC, opbld30 commented
Docs Build status updates of commit _[c697e0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c697e0ba00555537e011052e56b847129ec85159)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-135c7b91)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-135c7b91)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-135c7b91)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-135c7b91)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-135c7b91)
[api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-ff2883f8-135c7b91)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-135c7b91"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-135c7b91"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-135c7b91"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-135c7b91"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-135c7b91"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ff2883f8-135c7b91"></a>
### [api-reference/beta/resources/translationPreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationPreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050350428936-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q1lfy0IQ8ZcccDdXY%2FZPvRl0sG5FrXW6rda5R8wfE9A%3D&st=2021-03-05T03%3A47%3A03Z&se=2021-04-05T03%3A52%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or externa [...]

2021-03-05 03:55 UTC, opbld34 commented
Docs Build status updates of commit _[8eae8f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8eae8f3b18b747891aa07c954b0b0f6936c472eb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-fbb5ff8f)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-fbb5ff8f)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-fbb5ff8f)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-fbb5ff8f)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-fbb5ff8f)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-fbb5ff8f)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-fbb5ff8f"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-fbb5ff8f"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-fbb5ff8f"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-fbb5ff8f"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-fbb5ff8f"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-fbb5ff8f"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050353441587-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7%2F%2FYRe4r7AFW5wjQ1mays1nubkcuJJooJcWdOZc6WrQ%3D&st=2021-03-05T03%3A50%3A00Z&se=2021-04-05T03%3A55%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or exter [...]

2021-03-05 03:56 UTC, opbld33 commented
Docs Build status updates of commit _[7cdcbb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7cdcbb4a4ee6dead62be70893fda5e209f15bbf4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-007c7691)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-007c7691)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-007c7691)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-007c7691)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-007c7691)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-007c7691)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-007c7691"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-007c7691"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-007c7691"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-007c7691"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-007c7691"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-007c7691"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050354371409-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3ytSWLIfNWmXMYOO9ynepb7uXW00zEWanVYMeiTwVUE%3D&st=2021-03-05T03%3A51%3A20Z&se=2021-04-05T03%3A56%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external  [...]

2021-03-05 03:57 UTC, opbld31 commented
Docs Build status updates of commit _[52455b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52455b9b37d6dc0da05cde885bdd7498ba32d02f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-9b1f0398)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-9b1f0398)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-9b1f0398)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-9b1f0398)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-9b1f0398)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-9b1f0398)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-9b1f0398"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-9b1f0398"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-9b1f0398"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-9b1f0398"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-9b1f0398"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-9b1f0398"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050356007140-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=E%2BZViuz4ZoIgzwgNoD6qb%2FG53X2Mp0i56Ic%2BYYYxtZc%3D&st=2021-03-05T03%3A52%3A44Z&se=2021-04-05T03%3A57%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or ext [...]

2021-03-05 03:59 UTC, opbld32 commented
Docs Build status updates of commit _[650c03d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/650c03d550ed945ea30b11fd894573d02c0564be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-9089713d)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-9089713d)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-9089713d)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-9089713d)
[api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-89f01f1f-9089713d)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-9089713d)
[api-reference/beta/resources/translationLanguageOverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-9089713d"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-9089713d"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-9089713d"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-9089713d"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="89f01f1f-9089713d"></a>
### [api-reference/beta/resources/translationLanguageOverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationLanguageOverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-9089713d"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050357152286-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pACYwX%2BJIFrDk2zMUEmFN0qGNZ2v5wga9Lfp04vfonU%3D&st=2021-03-05T03%3A54%3A09Z&se=2021-04-05T03%3A59%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or externa [...]

2021-03-05 03:59 UTC, Lauragra approved these changes

2021-03-05 04:00 UTC, opbld31 commented
Docs Build status updates of commit _[08d25e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08d25e79f54ac87b41e0add5089a643df37b5ef9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-4325f4f3)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-4325f4f3)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-4325f4f3)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-4325f4f3)
[api-reference/beta/resources/translationlanguagoverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguagoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguagoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-bcc06fb7-4325f4f3)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-4325f4f3)
[api-reference/beta/resources/translationlanguageoverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguageoverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-4325f4f3"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-4325f4f3"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-4325f4f3"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-4325f4f3"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="bcc06fb7-4325f4f3"></a>
### [api-reference/beta/resources/translationlanguagoverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguagoverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-4325f4f3"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 22, Column 24**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'translationLanguageOverride.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050358547074-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d94Ny44pYBFny42DHvaEaiQYl0u4pEJLQ2RvxD4Ae2s%3D&st=2021-03-05T03%3A55%3A25Z&se=2021-04-05T04%3A00%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=15 [...]

2021-03-05 04:02 UTC, opbld32 commented
Docs Build status updates of commit _[4089ab1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4089ab1117da9ec73c42a98400d3dfd0642bcd01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-50e7345e)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-50e7345e)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-50e7345e)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-50e7345e)
[api-reference/beta/resources/translationlanguagoverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguagoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguagoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-bcc06fb7-50e7345e)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-50e7345e)
[api-reference/beta/resources/translationlanguageoverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguageoverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-50e7345e"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-50e7345e"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-50e7345e"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-50e7345e"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="bcc06fb7-50e7345e"></a>
### [api-reference/beta/resources/translationlanguagoverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguagoverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-50e7345e"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 22, Column 24**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'translationLanguageOverride.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050359219376-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RgJYYqv6b9bhn3v9PMuF0dIkQojOyXJkjQx3h9fOm50%3D&st=2021-03-05T03%3A57%3A02Z&se=2021-04-05T04%3A02%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=15 [...]

2021-03-05 04:05 UTC, opbld31 commented
Docs Build status updates of commit _[1e2f5d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e2f5d6fb17c1bc74498bddeea5e3f41f0521221)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-d4ec33d8-e7b6b1e8)
[api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-update?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b19d64c2-e7b6b1e8)
[api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalandlanguagesettings?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-b5af57ee-e7b6b1e8)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f04b6964-e7b6b1e8)
[api-reference/beta/resources/translationlanguageoverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguageoverride.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationlanguageoverride?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f0720a47-e7b6b1e8)
[api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/translationpreferences?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) | [Details](#user-content-f76c80ca-e7b6b1e8)
[api-reference/beta/resources/translationlanguageoverride.md.txt](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguageoverride.md.txt) | :white_check_mark:Succeeded | |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/regionalandlanguagesettings-get?view=graph-rest-beta&branch=pr-en-us-10961) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10961) |

<a id="d4ec33d8-e7b6b1e8"></a>
### [api-reference/beta/api/regionalandlanguagesettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b19d64c2-e7b6b1e8"></a>
### [api-reference/beta/api/regionalandlanguagesettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/api/regionalandlanguagesettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b5af57ee-e7b6b1e8"></a>
### [api-reference/beta/resources/regionalandlanguagesettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalandlanguagesettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f04b6964-e7b6b1e8"></a>
### [api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/regionalformatoverrides.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f0720a47-e7b6b1e8"></a>
### [api-reference/beta/resources/translationlanguageoverride.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationlanguageoverride.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f76c80ca-e7b6b1e8"></a>
### [api-reference/beta/resources/translationpreferences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/netstruc65-translationschemaupdates/api-reference/beta/resources/translationpreferences.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050404295841-10961%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5K6MXj7qxvWzZOwOda497zWppSjBRHsbukkrHid5PCs%3D&st=2021-03-05T04%3A00%3A48Z&se=2021-04-05T04%3A05%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external  [...]

2021-03-05 04:15 UTC, merged