Teams: Team Membership API - Bulk and filtering
microsoftgraph/microsoft-graph-docs pull request #10986
Opened 2020-12-09 09:04 UTC by AkJo

Added function for adding members to a team in bulk.
Also added filtering example for list team membership API.

2020-12-09 09:06 UTC, opbld32 commented
Docs Build status updates of commit _[2c8ccaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c8ccaa2820748e1917d42e994e691589198175d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) | [Details](#user-content-5493f1df-e4c2a284)
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) | [Details](#user-content-ff6d8bfe-e4c2a284)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-e4c2a284)
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="5493f1df-e4c2a284"></a>
### [api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md)
 - **Line 44, Column 3**: **[Warning-file-not-found]** `````Invalid file link: '../api/team-bulkadd-members.md'.`````

<a id="ff6d8bfe-e4c2a284"></a>
### [api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="de0bbbbb-e4c2a284"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090904473667-10986%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1wVY4TBctjpR%2BY3RXtKPH7hjPZtv0Jk%2FMOO2hp5bKAU%3D&st=2020-12-09T09%3A01%3A55Z&se=2021-01-09T09%3A06%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post you [...]

2020-12-09 09:32 UTC, opbld34 commented
Docs Build status updates of commit _[f362c8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f362c8a4a5dafe08daec4bbbf1f0e4f9b957ed56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090930071139-10986%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4dRofU06TlTr%2BRhRn%2FCLOGxInaf2ahBrYa61CGTIITU%3D&st=2020-12-09T09%3A27%3A11Z&se=2021-01-09T09%3A32%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 09:49 UTC, opbld32 commented
Docs Build status updates of commit _[420a561](https://github.com/microsoftgraph/microsoft-graph-docs/commits/420a561957e80d1a1d944731464ab6bd6488148b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012090948429492-10986%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fAl3zFMJEnsWHnmUipWmWgvJvpnUtyc2Pr6lNIh0qYw%3D&st=2020-12-09T09%3A44%3A54Z&se=2021-01-09T09%3A49%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Gui [...]

2020-12-09 10:04 UTC, opbld34 commented
Docs Build status updates of commit _[c7007ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7007acf16770422d3f904204bd6b486981fc3ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012091002473816-10986%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4uCrL9Ay7Vk0ErBrY8LdYhgW27vr%2Fitw46VHYgMn8zs%3D&st=2020-12-09T09%3A59%3A55Z&se=2021-01-09T10%3A04%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin G [...]

2020-12-09 10:06 UTC, opbld30 commented
Docs Build status updates of commit _[a5910fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a5910fe5979b477522325a39fed546385f0f2779)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012091005049905-10986%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SyaqdigIXYhrAjRbuhRfcQRURdNvrnogIU4FNO4I3Ow%3D&st=2020-12-09T10%3A01%3A23Z&se=2021-01-09T10%3A06%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Gui [...]

2020-12-09 10:27 UTC, opbld30 commented
Docs Build status updates of commit _[b69d5f7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b69d5f7231b6ccc8b4434405002fdb09c521a12b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-1.0&branch=pr-en-us-10986) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012091025503322-10986%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ci7BUZXXu8qf7c205J7A%2FzSB1mnG2aHF0WygW%2FfQL1U%3D&st=2020-12-09T10%3A22%3A09Z&se=2021-01-09T10%3A27%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin [...]

2020-12-09 19:39 UTC, opbld30 commented
Docs Build status updates of commit _[d7bd62f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7bd62f169bd271404dab5b6f5b6d18f80403fd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-09 19:50 UTC, opbld32 commented
Docs Build status updates of commit _[27b9afe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27b9afe9b19c48923ea40d89ef519cfbb7c2e8ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-09 21:58 UTC, opbld32 commented
Docs Build status updates of commit _[0d044bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d044bb0e98ba398f0ea2eff8ffd564453a2bf20)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-10 02:55 UTC, opbld30 commented
Docs Build status updates of commit _[c990349](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c990349eec0cc0ac08df9346ea7f5b654661a636)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-10 02:56 UTC, opbld32 commented
Docs Build status updates of commit _[dcc5930](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dcc593091c155362f56ba2e1efc3b8583552a14f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-10 03:06 UTC, Lauragra commented on api-reference/beta/api/team-list-members.md
> +> There are some known issues with this functionality.
We should describe the known issues in the Known issues topic and link to it from here.

2020-12-10 03:07 UTC, opbld33 commented
Docs Build status updates of commit _[d88f340](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d88f340f0409089381aa041f7056a8bbfd84e8af)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-10 03:13 UTC, opbld33 commented
Docs Build status updates of commit _[5efad7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5efad7e0d5a9034fdfe219dcf8655b2b1ab4ec2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-10 03:31 UTC, Lauragra commented on api-reference/beta/api/team-members-add.md
> +---
To follow the standard naming convention, this needs to be conversationmember-add, and the title will be conversationMember: add (singular).

2020-12-10 03:34 UTC, opbld34 commented
Docs Build status updates of commit _[eb93d1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb93d1ac46789cebf8c4bf31e3ffd350b7e7ff3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/v1.0/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/ [...]

2020-12-10 04:05 UTC, opbld32 commented
Docs Build status updates of commit _[57b2e36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57b2e363cf023fcda7eda72f687b0fbc414534c7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-0273acab)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](h [...]

2020-12-10 04:10 UTC, opbld31 commented
Docs Build status updates of commit _[c738bb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c738bb8ec8b71a27bbb3900681ef1b0e3e613599)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-6d0e946c)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](h [...]

2020-12-10 04:12 UTC, opbld32 commented
Docs Build status updates of commit _[aa3fb06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa3fb065f804bc508e9e0b8e7df9e1465e065ba6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-14c6bfe4)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](h [...]

2020-12-10 04:13 UTC, opbld32 commented
Docs Build status updates of commit _[a3240be](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3240bec8d8389a5747487e3a80560e1a0c979d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-37551513)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](h [...]

2020-12-10 04:17 UTC, opbld30 commented
Docs Build status updates of commit _[df9d6a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df9d6a1571080192f14f3aaf7218258cdc892736)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-dae7e21e)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-members-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-members-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-members-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](h [...]

2020-12-10 04:17 UTC, Lauragra requested changes
I think this PR will be good to go after we settle on how to handle the add action.

2020-12-10 09:55 UTC, opbld30 commented
Docs Build status updates of commit _[06d3bf9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06d3bf9c2905ed103e82ddada18609e8b4f0422b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-d271a50a)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark [...]

2020-12-10 10:05 UTC, AkJo commented on api-reference/beta/api/team-list-members.md
> +> There are some known issues with this functionality.
We are being vague over here on purpose (because the range of issues are varied). Adding more details will lead to unnecessary questions for us. 

The main objective of the note is that people can experiment with that request example but should not take a dependency on it yet.

We are debating whether to keep that specific functionality or not based on how many people use this and the problems they might encounter .

2020-12-10 10:06 UTC, AkJo commented on api-reference/beta/api/team-list-members.md
> +> There are some known issues with this functionality.
And we do want the note to say that the issues are still "being investigated" (and have not been finalized in anyway).

2020-12-10 10:11 UTC, opbld32 commented
Docs Build status updates of commit _[83a405f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83a405ff761498e2519a360f8a3583e81f9c346d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-788412dd)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark [...]

2020-12-10 10:26 UTC, opbld33 commented
Docs Build status updates of commit _[3b9a354](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b9a354de7f3f7386adc6ba6f8120407c259d1d5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-999b0296)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark [...]

2020-12-10 10:33 UTC, AkJo commented on api-reference/beta/api/team-list-members.md
> +> There are some known issues with this functionality.
Added a known issue link. Hope the link is working.

2020-12-10 10:54 UTC, AkJo commented
> I think this PR will be good to go after we settle on how to handle the add action.

@Lauragra 

Renaming to conversationmember-add.md is conflicting with the already existing conversationmember-add.md which caters to an entirely different API.

For now, I am renaming this to conversationmembers-add.md, and maintaining parity with chats-getallmessages.md and channels-getallmessages.md. Lets get this in.

(From a pedantic perspective, ideally, the filename for the action should have been conversationmember-collection-add.md or collection-conversationmember-add.md; and the title would have followed suit.)

2020-12-10 10:55 UTC, AkJo commented on api-reference/beta/api/team-members-add.md
> +---
Renaming to conversationmember-add.md is conflicting with the already existing conversationmember-add.md which caters to an entirely different API.

For now, I am renaming this to conversationmembers-add.md, and maintaining parity with chats-getallmessages.md and channels-getallmessages.md. Lets get this in.

(From a pedantic perspective, ideally, the filename for the action should have been conversationmember-collection-add.md or collection-conversationmember-add.md; and the title would have followed suit.)

2020-12-10 17:56 UTC, opbld30 commented
Docs Build status updates of commit _[6692763](https://github.com/microsoftgraph/microsoft-graph-docs/commits/669276386d79590cb98f326d0fa2a2922225e1bb)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2020-12-10 17:58 UTC, opbld32 commented
Docs Build status updates of commit _[6692763](https://github.com/microsoftgraph/microsoft-graph-docs/commits/669276386d79590cb98f326d0fa2a2922225e1bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-4ed63fcf)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark [...]

2020-12-10 23:06 UTC, opbld32 commented
Docs Build status updates of commit _[b552abc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b552abc9b403a4f15eb3b1629c8af97bb4324b9b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-ec541d8a)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappinstallation?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamstab.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamstab.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamstab?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/toc.yml) | :white_check_mark [...]

2020-12-10 23:24 UTC, opbld34 commented
Docs Build status updates of commit _[4c3ed28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c3ed284abce40e0b085233cd2bc2560fd304b80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10986) | [Details](#user-content-de0bbbbb-8939f2ea)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-list-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/api/team-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/api/team-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post-members?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/aaduserconversationmemberresult.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/aaduserconversationmemberresult.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/aaduserconversationmemberresult?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/actionresultpart.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/actionresultpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/actionresultpart?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/channel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/channel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/channel?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/chat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/chat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/conversationmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/conversationmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conversationmember?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicerrordetail.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicerrordetail.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicerrordetail?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/publicinnererror.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/publicinnererror.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/publicinnererror?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-10986) (graph-rest-beta) |
[api-reference/beta/resources/teamsappinstallation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/anandjo/team-membership-bulk/api-reference/beta/resources/teamsappinstallation.md) | [...]

2020-12-10 23:27 UTC, merged