Adding TAP Method - create, list, get, delete,
microsoftgraph/microsoft-graph-docs pull request #10995
Opened 2020-12-10 01:39 UTC by InbarckMS

2020-12-10 01:40 UTC, opbld34 commented
Docs Build status updates of commit _[1296a46](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1296a4632708d32c5a552a67b5ef05a68f175ec2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-e6bf7d63-ac7881db)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |

<a id="e6bf7d63-ac7881db"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'inbarcMS' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100139336181-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UjtaMIGW8ffH4AO3DxYnCnOopRHlE0T5dqLJPd8CaMU%3D&st=2020-12-10T01%3A35%3A53Z&se=2021-01-10T01%3A40%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 07:02 UTC, opbld31 commented
Docs Build status updates of commit _[19bc0b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19bc0b0d8b63e10ab8e6844792d7dd321de5f3a7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100701173282-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YcBa99i%2FUE95mLjgeGdzuCEylreC%2BxahL3am2brJ7Pg%3D&st=2020-12-10T06%3A57%3A37Z&se=2021-01-10T07%3A02%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 07:07 UTC, andres-canello commented
I've made some minor fixes.
@InbarckMS, you need to add the method to the overview page (authenticationmethods-overview.md) and links to the TOC (https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/55084/Create-new-documentation?anchor=add-table-of-contents-entries)

2020-12-11 00:21 UTC, opbld31 commented
Docs Build status updates of commit _[c0b612e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0b612e0ad0ba426c597934535888c6d4661e053)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012110019320870-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Zci9UFbywonjXo%2F0L7lJA6JTV%2BdwWlu2ysduZ1P7bh8%3D&st=2020-12-11T00%3A16%3A06Z&se=2021-01-11T00%3A21%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 19:50 UTC, opbld34 commented
Docs Build status updates of commit _[1797aed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1797aed11f260c323d65b79bc6d23506318d9aa4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-ec1f435c)

<a id="00685cff-ec1f435c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml)
 - **Line 10260, Column 23**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012161949457853-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jAjLjXJ7%2F3ZC%2BzkwXMC%2BYWTljj629tusVSjspnv7O%2Bo%3D&st=2020-12-16T19%3A45%3A43Z&se=2021-01-16T19%3A50%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 21:52 UTC, opbld31 commented
Docs Build status updates of commit _[3310b9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3310b9aecd3e411d77f92aa402be38a8b7c20539)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162151171993-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IsJeInMdzLOXLNLWTvOvhmbBfJVaQ3PJjzcdD2H3N60%3D&st=2020-12-16T21%3A47%3A34Z&se=2021-01-16T21%3A52%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 23:58 UTC, opbld34 commented
Docs Build status updates of commit _[6f21743](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f21743ba54b5a5a534cc8c89e055138bee89588)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162357150615-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f31J5HAr2bN2YhOCyUYxgN%2FB4HrCOXxjT7ihGYXxMuw%3D&st=2020-12-16T23%3A53%3A26Z&se=2021-01-16T23%3A58%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 17:57 UTC, opbld33 commented
Docs Build status updates of commit _[dd7e515](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd7e515988675aa6bfdb8483addb2776f999445a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101041755371569-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UFeLnF1nTJUhvgzctmDL%2BIej%2FygjTAS1ZL2pugjlUrM%3D&st=2021-01-04T17%3A52%3A41Z&se=2021-02-04T17%3A57%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 17:59 UTC, opbld32 commented
Docs Build status updates of commit _[7703fba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7703fba8c516eda372c264747e59e1f84d588306)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101041758032251-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lkNXKB5kxuIykyUEN1emxoPn%2FyJh8TpkE%2F5gl%2BBp%2Bws%3D&st=2021-01-04T17%3A54%3A15Z&se=2021-02-04T17%3A59%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 23:27 UTC, opbld32 commented
Docs Build status updates of commit _[c60c0a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c60c0a6cd2b7f4ce994de69f74f1bc77855e9f0d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042325403847-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=asm6NWuHoq99n9NOwMSb7TPuojljKv02ArBhQoGQVgI%3D&st=2021-01-04T23%3A22%3A03Z&se=2021-02-04T23%3A27%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-18 04:28 UTC, opbld33 commented
Docs Build status updates of commit _[9743246](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9743246ca7954c5e85685408c14f4723eca0fd82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101180427337609-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YbNUYdgins8Z0BCvFjr4q4vj%2BK0LOc3lp7euHg%2B6Qjo%3D&st=2021-01-18T04%3A23%3A42Z&se=2021-02-18T04%3A28%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-18 05:24 UTC, andres-canello approved these changes

2021-01-25 17:29 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
> +Create a new [temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md) object on a user. A user can only have one Temporary Access Pass. The passcode can be u
I don't think Temporary Access Pass should be capitalized. Capitalization should only be used for brand names.

2021-01-25 17:30 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
> +* After the Temporary Access Pass has expired – a new Temporary Access Pass will override the current Temporary Access Pass and will not revoke the user’s sessions.
```suggestion
* After the Temporary Access Pass has expired – a new temporary access pass overrides the current temporary access pass and doesn't revoke the user’s sessions.
```

2021-01-25 17:35 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
> +The following table shows the properties that can be set when you create the [temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md).
Rather than say 'can be set' , it is typical to describe the properties that are required to create the object.

2021-01-25 17:37 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
> +  "@odata.type": "#microsoft.graph.temporaryAccessPassAuthenticationMethod",
The example should show real looking values. For example the response in Graph Explorer using a demo tenant.

2021-01-25 17:38 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
> +  "@odata.type": "#microsoft.graph.temporaryAccessPassAuthenticationMethod",
The response should show real looking values. For example, the response in Graph Explorer using a demo tenant.

2021-01-25 18:26 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md
> +Deletes a [temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md) object.
```suggestion
Delete a [temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md) object.
```

2021-01-25 18:27 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md
> +While the current Temporary Access Pass on the user is valid – it needs to be deleted before a new Temporary Access Pass can be create on the user. Deleting a valid Temporary Access Pass revokes the
```suggestion
While the current temporary access pass on the user is valid, it needs to be deleted before a new temporary access pass can be created on the user. Deleting a valid temporary access pass revokes the user’s sessions.
```

2021-01-25 18:29 UTC, davidmu1 commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md
> +For delegated scenarios where an admin is acting on another user, the admin needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles)
This seems to be duplicated.

2021-01-25 19:54 UTC, mmcla commented on api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md
> +Create a new [temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md) object on a user. A user can only have one Temporary Access Pass. The passcode can be u
We may be treating this as a brand name - we had to run it through marketing. @InbarckMS ?

2021-01-25 19:57 UTC, mmcla commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
> +|[List](../api/temporaryaccesspassauthenticationmethod-list.md)|[temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md) collection|Retrieve a list of a user
Retrieve a list of _the_ user's . . .

2021-01-25 19:57 UTC, mmcla commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
> +|[Get](../api/temporaryaccesspassauthenticationmethod-get.md)|[temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md)|Retrieve the properties  of the user's
Double spaces following "Retrieve the properties"

2021-01-25 19:58 UTC, mmcla commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
> +|[Create](../api/temporaryaccesspassauthenticationmethod-create.md)|[temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md)|Create a user's  temporaryAccess
Double spaces following "Create a user's"

2021-01-25 20:00 UTC, mmcla commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
> +|isUsableOnce|Boolean|Determines if the pass is limited to a one time use. If True – the pass can be used once, if False – the pass can be used multiple times within the temporaryAccessPass life time
put backticks around True and False - e.g. `True` and `False`

2021-01-25 20:04 UTC, mmcla approved these changes
I left some comments of minor things that should get cleared up, but otherwise good to go.

2021-01-25 20:07 UTC, mmcla requested changes
Oh, one more request - please add references to TAP to the authenticationmethods-overview.md doc

2021-01-25 23:43 UTC, opbld34 commented
Docs Build status updates of commit _[5f7b9bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f7b9bb464687ed40cab57042c68e1fc778abd66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101252341517273-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F3gcFy53b2m7%2F2HtoCyWtkgb%2BnJqhVC9kANzeiJrYtY%3D&st=2021-01-25T23%3A38%3A05Z&se=2021-02-25T23%3A43%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 00:00 UTC, opbld33 commented
Docs Build status updates of commit _[3dfe147](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3dfe147ab8ca3a6470b6846e4129619cc672f912)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101252359192208-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A8G8x0DNhI%2F8KGhcAxFvcEJC8ElnXtoEpYnSNPLU%2Bk0%3D&st=2021-01-25T23%3A55%3A33Z&se=2021-02-26T00%3A00%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 00:03 UTC, opbld34 commented
Docs Build status updates of commit _[a290784](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a290784418020366d111d942ed776495f72c7c23)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101260001499163-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XPJHoQPN2a1bUqVwSVmFuF8SsIL5K3%2Bwifa2OqB%2BnX4%3D&st=2021-01-25T23%3A58%3A20Z&se=2021-02-26T00%3A03%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 16:16 UTC, opbld32 commented
Docs Build status updates of commit _[a67ae9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a67ae9b5e2d048c0c5233a337f1d74721760ed12)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101271615031580-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dKTKCrxIQBOTuxrYGYr7E40pRsGJZ7gEjv3J1x%2Fbucg%3D&st=2021-01-27T16%3A11%3A15Z&se=2021-02-27T16%3A16%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:54 UTC, opbld30 commented
Docs Build status updates of commit _[791c404](https://github.com/microsoftgraph/microsoft-graph-docs/commits/791c404cf48014ed46fa472fa36d4c59c6d67db8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0876cab4)

<a id="0876cab4"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272353166683-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r1VEf1AKVb4%2FduFRNIoUMByV0s6zyVrFYVhr94V5Ci0%3D&st=2021-01-27T23%3A49%3A19Z&se=2021-02-27T23%3A54%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 22:39 UTC, opbld33 commented
Docs Build status updates of commit _[765d540](https://github.com/microsoftgraph/microsoft-graph-docs/commits/765d5403c47a108072e45e53962efdeb6f4a6daf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b3bb5599)

<a id="b3bb5599"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282238383130-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G7D37K7ax8ylFiyiJKn4MerbLnyyQ3GwlB8jLZeHALU%3D&st=2021-01-28T22%3A34%3A44Z&se=2021-02-28T22%3A39%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 00:49 UTC, opbld32 commented
Docs Build status updates of commit _[7f7d552](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f7d5526a4666611654ea5479f88d12739053288)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290048315046-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kDzLu9mvcbghwcNYegs6ucTRG3%2F2QYuh%2Fs3YT%2BaGhI0%3D&st=2021-01-29T00%3A44%3A49Z&se=2021-03-01T00%3A49%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 01:18 UTC, mmcla approved these changes

2021-02-10 22:20 UTC, opbld31 commented
Docs Build status updates of commit _[95d9e56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/95d9e5601a772d7e84c97442ccb6f5016f0e195f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102218492758-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xXMU47VRfk6pzf9V8mRllYHv1%2BaYtTV65SoaUJyXTe0%3D&st=2021-02-10T22%3A15%3A10Z&se=2021-03-13T22%3A20%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 22:31 UTC, opbld30 commented
Docs Build status updates of commit _[382bb91](https://github.com/microsoftgraph/microsoft-graph-docs/commits/382bb915bf79ac2f6e20fa36dbfebedb66f993df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102230118908-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bccLt008QwCvyi4VzSYOuyAPejR%2BNrgnc2a1%2FInYTTo%3D&st=2021-02-10T22%3A26%3A53Z&se=2021-03-13T22%3A31%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 22:45 UTC, opbld31 commented
Docs Build status updates of commit _[929b290](https://github.com/microsoftgraph/microsoft-graph-docs/commits/929b290246d709d1dab7542ce301c2095aff403f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102244298706-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W23B22JvC0u5j2AFfoCJrD2%2FEtzRLnRNh7ZxhpIqX2A%3D&st=2021-02-10T22%3A40%3A37Z&se=2021-03-13T22%3A45%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 22:53 UTC, opbld30 commented
Docs Build status updates of commit _[2e97e53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e97e53a5911ab2ea4b8e8d491e79905aa3fe314)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102252527928-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K8eC6B9fsXztJbR%2BaEk3qZ1d03XlOYFOMaoBo%2FdBVdI%3D&st=2021-02-10T22%3A48%3A56Z&se=2021-03-13T22%3A53%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 23:02 UTC, opbld34 commented
Docs Build status updates of commit _[6e50801](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e5080150be921d6dedfe819d78d882671437a61)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102300588263-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4%2BHEfBEQb1Xui3X5hLfIsXQYWmmS1f0FwdMj2Kk27KU%3D&st=2021-02-10T22%3A57%3A26Z&se=2021-03-13T23%3A02%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 16:45 UTC, davidmu1 approved these changes

2021-02-11 22:06 UTC, opbld32 commented
Docs Build status updates of commit _[5eef4c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5eef4c0a79453713ac261183f970d24d0c04a49a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102112205148902-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OuaNDAfoQ3DOK6OAtkQaflVxQVvh72etmV44cvQyI54%3D&st=2021-02-11T22%3A01%3A35Z&se=2021-03-14T22%3A06%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 01:28 UTC, Lauragra commented on api-reference/beta/toc.yml
> +            - name: Add
Why are we call the operation Add here in the TOC, instead of Create? Note that the order of operations is generally List Create, Get, Update, Delete. So we should change the entry to Create and move it to follow List.

2021-02-12 01:28 UTC, Lauragra commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
> +|[Create](../api/temporaryaccesspassauthenticationmethod-create.md)|[temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md)|Create a user's temporaryAccessP
Please change the order of the operations listed here too, to put Create after List.

2021-02-12 01:29 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +        {
You'll want to add a new ChangeList item for these changes that will reflect the date that these APIs go live.

2021-02-14 22:38 UTC, andres-canello commented on api-reference/beta/toc.yml
> +            - name: Add
@Lauragra, we named 'Add' the create operations for the other methods that support it (email, phone), the order aligns with the order of other methods. I'd be happy to change them all to align in a future PR if that's ok?

2021-02-14 22:39 UTC, andres-canello commented on api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md
> +|[Create](../api/temporaryaccesspassauthenticationmethod-create.md)|[temporaryAccessPassAuthenticationMethod](../resources/temporaryaccesspassauthenticationmethod.md)|Create a user's temporaryAccessP
Same as above

2021-02-14 22:42 UTC, opbld31 commented
Docs Build status updates of commit _[414230b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/414230b05f4e0fc8d09e2521c7d64decacf1c5c3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-fe3bedf1-aacf61a6)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-c77b28a6-aacf61a6)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-36a1179b-aacf61a6)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-e6bf7d63-aacf61a6)
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-3703c1da-aacf61a6)
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-87ff9c42-aacf61a6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="fe3bedf1-aacf61a6"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c77b28a6-aacf61a6"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="36a1179b-aacf61a6"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e6bf7d63-aacf61a6"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="3703c1da-aacf61a6"></a>
### [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="87ff9c42-aacf61a6"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142240483977-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NIlAnVUqibpTKpJqvEQGnrKGcJU0y7uHlTdTrUKXwOg%3D&st=2021-02-14T22%3A36%3A59Z&se=2021-03-17T22%3A41%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo l [...]

2021-02-14 22:49 UTC, andres-canello commented on changelog/Microsoft.DirectoryServices.json
> +        {
Done

2021-02-14 22:51 UTC, opbld34 commented
Docs Build status updates of commit _[d25d622](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d25d622ab6ee41f647b87b1c2a639b33c502488c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-fe3bedf1-76e9b9ff)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-c77b28a6-76e9b9ff)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-36a1179b-76e9b9ff)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-e6bf7d63-76e9b9ff)
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-3703c1da-76e9b9ff)
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-87ff9c42-76e9b9ff)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="fe3bedf1-76e9b9ff"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c77b28a6-76e9b9ff"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="36a1179b-76e9b9ff"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e6bf7d63-76e9b9ff"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="3703c1da-76e9b9ff"></a>
### [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="87ff9c42-76e9b9ff"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142249526878-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ydw4I%2F%2ByUdtP0pU5iaQ6RTKJadtqd7fpdTT30hOBaYg%3D&st=2021-02-14T22%3A46%3A12Z&se=2021-03-17T22%3A51%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross re [...]

2021-02-14 22:57 UTC, opbld30 commented
Docs Build status updates of commit _[30bf60d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30bf60d10ddc66aad4b1b91df45bd16d467a72ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-fe3bedf1-641770f2)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-c77b28a6-641770f2)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-36a1179b-641770f2)
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-e6bf7d63-641770f2)
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-3703c1da-641770f2)
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) | [Details](#user-content-87ff9c42-641770f2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="fe3bedf1-641770f2"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md)
 - **Line 4, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'inbarckMS' is not a valid Microsoft alias.`````

<a id="c77b28a6-641770f2"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md)
 - **Line 4, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'inbarckMS' is not a valid Microsoft alias.`````

<a id="36a1179b-641770f2"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md)
 - **Line 4, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'inbarckMS' is not a valid Microsoft alias.`````

<a id="e6bf7d63-641770f2"></a>
### [api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md)
 - **Line 4, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'inbarckMS' is not a valid Microsoft alias.`````

<a id="3703c1da-641770f2"></a>
### [api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md)
 - **Line 5, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'mmcla' is not a valid Microsoft alias.`````

<a id="87ff9c42-641770f2"></a>
### [api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md)
 - **Line 4, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'inbarckms' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142256122530-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xi9mrvxH2tTiS9MnIyls%2BweaOnlOstHCrwpS6JqoE58%3D&st=2021-02-14T22%3A52%3A18Z&se=2021-03-17T22%3A57%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-14 23:01 UTC, opbld33 commented
Docs Build status updates of commit _[37d5e37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37d5e375e768194ef04b8153e56c0ab7d07cd6d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142300151243-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8OebeoV2XjmW9vU7NNKSqG4XSYJtC5op5n9diZ6QaFs%3D&st=2021-02-14T22%3A56%3A41Z&se=2021-03-17T23%3A01%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-14 23:04 UTC, opbld31 commented
Docs Build status updates of commit _[c4c7737](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4c7737b6d8281958bfa3ee04b252bbf630a7306)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-delete?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-get?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/api/temporaryaccesspassauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-list?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/authenticationmethods-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/resources/temporaryaccesspassauthenticationmethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/temporaryaccesspassauthenticationmethod-create?view=graph-rest-beta&branch=pr-en-us-10995) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-02-TAP_method_add/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102142303134011-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3%2BRHePGL56m4VzAQA194DlX%2BlRhXF4hJpSjMQNz7%2BMI%3D&st=2021-02-14T22%3A59%3A20Z&se=2021-03-17T23%3A04%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-24 01:00 UTC, opbld32 commented
Docs Build status updates of commit _[b112a0b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b112a0b7f2b4207c1122f4bc2938d96deb6ee911)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a71ba48b)

<a id="a71ba48b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104240059466629-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yzGnbKRHV4SWkZ%2Fav%2BXq9HaKpBtH%2FfAxiJOzGdst%2Fe0%3D&st=2021-04-24T00%3A55%3A01Z&se=2021-05-25T01%3A00%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 02:27 UTC, opbld32 commented
Docs Build status updates of commit _[5be0a4c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5be0a4c1a8b38dfad6c3572dd65d236f8ce0d816)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-04693713)

<a id="04693713"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104290226344781-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0W2dRW1Os2wG49drQl2%2FDWORwq6opu8SIGyXy%2BKjg2I%3D&st=2021-04-29T02%3A22%3A10Z&se=2021-05-30T02%3A27%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 02:27 UTC, opbld31 commented
Docs Build status updates of commit _[216ef1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/216ef1b2b3ee8f61c674d1de75201ee96066f3df)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a0a45e41)

<a id="a0a45e41"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104290226562205-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6eM%2BGeoSMP8EHzW%2FRcEDsM6OXkimuV7FGgS3BOvrbo4%3D&st=2021-04-29T02%3A22%3A33Z&se=2021-05-30T02%3A27%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-29 02:46 UTC, opbld33 commented
Docs Build status updates of commit _[0525220](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0525220ccce4833eb693e77ed511d9a7af6202d0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-419db730)

<a id="419db730"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104290246120619-10995%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p4QSYQzHjpn4xNNbh8HBAqmm0saj20bqiHnJOPFn6UI%3D&st=2021-04-29T02%3A41%3A30Z&se=2021-05-30T02%3A46%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-25 21:34 UTC, lramosvea commented
@InbarckMS seems like these changes are live already:

https://docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-beta&branch=pr-en-us-10995
https://docs.microsoft.com/en-us/graph/api/resources/temporaryaccesspassauthenticationmethod?view=graph-rest-beta&branch=pr-en-us-10995

Can you confirm this? If so, we can close this PR.

2021-06-16 12:15 UTC, isvargasmsft commented
Author confirmed we can closed this PR since the changes are already live.

2021-06-16 12:15 UTC, closed without merging