Add 2 new, optional properties to educationAssignment Object
microsoftgraph/microsoft-graph-docs pull request #10994
Opened 2020-12-09 23:31 UTC by shravva

Add 2 new, optional properties to educationAssignment object (http://graph.microsoft.com/beta/education/classes(id)/assignments )

addedStudentAction,
notificationChannelUrl

2020-12-09 23:32 UTC, opbld33 commented
Docs Build status updates of commit _[76fe36b](https://github.com/shravva/microsoft-graph-docs/commits/76fe36b798f7a9870c123a3ab2e0f3807a94c0e5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-5016cbb7-27b4a167)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-27b4a167)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |

<a id="5016cbb7-27b4a167"></a>
### [api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md)
 - **Line 53, Column 209**: **[Warning-file-not-found]** `````Invalid file link: 'educationassignmentclassrecipient.md'.`````

<a id="de0bbbbb-27b4a167"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 36, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/educationAssignment?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092331155508-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FdLksB3dyf5B9sRtPCusC17adhcdZvXhQPFbqgK5ni4%3D&st=2020-12-09T23%3A27%3A38Z&se=2021-01-09T23%3A32%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 00:25 UTC, opbld33 commented
Docs Build status updates of commit _[bdbab67](https://github.com/shravva/microsoft-graph-docs/commits/bdbab67be4850449edd5b54ffb311e65c01191cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-ba72e715)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |

<a id="de0bbbbb-ba72e715"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100023580029-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Yu%2FUjGhVdFsS1X5xmqWJYCSHC4q6MeKxh5lhjgfovig%3D&st=2020-12-10T00%3A20%3A18Z&se=2021-01-10T00%3A25%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 00:48 UTC, shravva commented
add tag `do not merge`

2020-12-10 02:35 UTC, opbld34 commented
Docs Build status updates of commit _[e62c721](https://github.com/shravva/microsoft-graph-docs/commits/e62c721df9fba4cdb57a697805faed9cbf97eec1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-cfe9ef10)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |

<a id="de0bbbbb-cfe9ef10"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100234250177-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eUnJWrjKIrZ2pEtp%2B0EPeYAYAZVJiITbiZ56O3%2Fko6g%3D&st=2020-12-10T02%3A30%3A33Z&se=2021-01-10T02%3A35%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 02:37 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added new optional, properties **addedStudentAction**, **notificationChannelUrl** to [educationAssignment](/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-v
Please remove the period after optional. Please also add an entry to the EducationAssignment JSON file for this change.

2020-12-10 02:37 UTC, opbld30 commented
Docs Build status updates of commit _[109ee9e](https://github.com/shravva/microsoft-graph-docs/commits/109ee9e1469140d1cc4cb8371b07a2c800a61e70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-d25d76dd)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |

<a id="de0bbbbb-d25d76dd"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100236278614-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jIimhPeiyRCKJqJBnCwaC6RJD3y2PxzvXj%2Fi2I1uo2Q%3D&st=2020-12-10T02%3A32%3A45Z&se=2021-01-10T02%3A37%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 02:38 UTC, Lauragra requested changes
Please see comment.

2020-12-10 04:26 UTC, shravva commented on concepts/changelog.md
> +| Addition | beta | Added new optional, properties **addedStudentAction**, **notificationChannelUrl** to [educationAssignment](/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-v
>Please remove the period after optional

Do you mean `,` after an optional word or `.` at the end of the sentence?

>Please also add an entry to the EducationAssignment JSON file for this change.

Already mentioned the link `[educationAssignment](/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-view=true)` where JSON repesentation provided with these new fields too.

2020-12-10 04:33 UTC, opbld33 commented
Docs Build status updates of commit _[6d5dae8](https://github.com/shravva/microsoft-graph-docs/commits/6d5dae8cd723b8cf9189bbded7c057b802a17a94)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-32493284)

<a id="32493284"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012100432379211-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZtZfRopTzD%2F60ica0bjGp9ibuCvVC2r6LUYgKcZ5AkI%3D&st=2020-12-10T04%3A27%3A59Z&se=2021-01-10T04%3A32%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 19:27 UTC, opbld32 commented
Docs Build status updates of commit _[02007e0](https://github.com/shravva/microsoft-graph-docs/commits/02007e0c0011a91b3be92fd0950e5fb5cb51368a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1e96fe9d)

<a id="1e96fe9d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012101927301704-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CgSyVyZIRsfNUJNag8rc2%2F627cNNl9hUrNrZ1oB8Fcw%3D&st=2020-12-10T19%3A22%3A51Z&se=2021-01-10T19%3A27%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-10 20:01 UTC, opbld30 commented
Docs Build status updates of commit _[50f6cd5](https://github.com/shravva/microsoft-graph-docs/commits/50f6cd5be9589073da97e22375678b7abf805ad7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-b2eff973-44736dc5)
[api-reference/beta/api/printjob-cancel.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-5c821ddc-44736dc5)
[api-reference/beta/api/printjob-redirect.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printjob-redirect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-redirect?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-8c3451fa-44736dc5)
[api-reference/beta/resources/printer.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-8794bed8-44736dc5)
[api-reference/beta/resources/printerstatus.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-c60d9ccc-44736dc5)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-44736dc5)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/emailauthenticationmethodconfiguration-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/agreement.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/agreement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/agreement?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/emailauthenticationmethodconfiguration.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/emailauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/compliance-concept-overview.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/compliance-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/compliance-concept-overview?branch=pr-en-us-10994) |

<a id="b2eff973-44736dc5"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5c821ddc-44736dc5"></a>
### [api-reference/beta/api/printjob-cancel.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printjob-cancel.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.mi [...]

2020-12-10 20:16 UTC, opbld31 commented
Docs Build status updates of commit _[518ba8d](https://github.com/shravva/microsoft-graph-docs/commits/518ba8dd169c371237c9ba81322ec04e8f2024cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-5016cbb7-0e9bea03)
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-194a7820-0e9bea03)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-0e9bea03)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |

<a id="5016cbb7-0e9bea03"></a>
### [api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md)
 - **Line 53, Column 1**: **[Warning-[merge-conflict](https://aka.ms/merge-conflict)]** `````File contains merge conflict markers.`````
 - **Line 57, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Property	   | Type	|Description|
|:---------------|:--------|:----------|
|addedStudentAction|String| Controls the behavior for students who are added after the assignment is published.|
|allowLateSubmissions|Boolean| Whether submissions can be submitted after the due date.|
|allowStudentsToAddResourcesToSubmission|Boolean| Whether a student can add resources to a submission. Indicated whether the only items on the submission came from the assignment resource list. |
|assignDateTime|DateTimeOffset| Date the assignment should be published to students. |
|assignTo|educationAssignmentRecipient| Students who get the assignment.|
|closeDateTime|DateTimeOffset| Date when the assignment will be closed for submissions. This is an optional field that can be null if the assignment does not allowLateSubmissions or the closeDateTime is the same as the dueDateTime but if specified, it must be greater than or equal to the dueDateTime.|
|displayName|String| Name of assignment. |
|dueDateTime|DateTimeOffset| Date assignment is due. |
|grading|educationAssignmentGradeType| How the assignment will be graded.|
|instructions|itemBody| Instructions to be given to the students along with the assignment. |
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
|notificationChannelUrl|String| Channel to post assignment publish notification. Updating the channel URL is not allowed after the assignment has been published and is only allowed when the assignTo value is educationAssignmentClassRecipient.|') are not allowed. You can only have one top-level heading.
`````
 - **Line 58, Column 209**: **[Warning-file-not-found]** `````Invalid file link: 'educationassignmentclassrecipient.md'.`````
 - **Line 60, Column 9**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '76fe36b798 (Add 2 new, optional properties to educationAssignment Object)') are not allowed. You can only have one top-level heading.`````
 - **Line 63, Column 9**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'bdbab67be4 (fixed broken link and update change log)') are not allowed. You can only have one top-level heading.`````
 - **Line 60, Column 9**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 '76fe36b798 (Add 2 new, optional properties to educationAssignment Object)' is duplicated with other articles: 'beta/api/educationassignment-update.md(60,9), beta/resources/educationassignment.md(50,9), beta/resources/educationassignment.md(75,9)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="194a7820-0e9bea03"></a>
### [api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md)
 - **Line 44, Column 1**: **[Warning-[merge-conflict](https://aka.ms/merge-conflict)]** `````File contains merge conflict markers.`````
 - **Line 47, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '| Property	   | Type	|Description|
|:---------------|:--------|:----------|
|id|String| Read-only.|
<<<<<<< HEAD
<<<<<<< HEAD
|addedStudentAction|String|Optional field to control the assignment behavior for students who are added after the assignment is published. If not specified, defaults to  value. Currently supports only two values:  or .|') are not allowed. You can only have one top-level heading.
`````
 - **Line 50, Column 9**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 '76fe36b798 (Add 2 new, optional properties to educationAssignment Object)') are not allowed. You can only have one top-level heading.`````
 - **Line 72, Column 9**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** 
`````
Multiple H1s(H1 '109ee9e146 (Edit.)
|allowLateSubmissions|Boolean| Identifies whether students can submit after the due date. If this property is not specified during create, it defaults to true. |
|allowStudentsToAddResourcesToSubmission|Boolean| Identifies whether students can add their own resources to a submission or if they can only modify resources added by the teacher. |
|assignDateTime|DateTimeOffset|The date when the assignment should become active.  If in the future, the assignment is not shown to the student until this date.  The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this: |
|assignTo|educationAssignmentRecipient| Which users, or whole class should receive a submission object once the assignment is published. |
|assignedDateTime|DateTimeOffset|The moment that the assignment was published to students and the assignment shows up on the students timeline.  The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 would look like this:  [...]

2020-12-10 20:28 UTC, opbld30 commented
Docs Build status updates of commit _[f79f493](https://github.com/shravva/microsoft-graph-docs/commits/f79f49395676e71cbde30e1ade525d4364e017c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-07132941)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |

<a id="de0bbbbb-07132941"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/todoTask?view=graph-rest-beta`````
 - **Line 61, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 118, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 119, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 120, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012102027399969-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tf2O4906IN5nCp9xSqQGPH4iDSmnE43lwdvmAtgdIW0%3D&st=2020-12-10T20%3A23%3A46Z&se=2021-01-10T20%3A28%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 01:05 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added new optional, properties **addedStudentAction**, **notificationChannelUrl** to [educationAssignment](/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-v
In addition to the changelog.md file, we need a changelist item in this JSON file: https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/changelog/Microsoft.EducationAssignment.json.

2020-12-12 01:29 UTC, opbld34 commented
Docs Build status updates of commit _[ec94c3d](https://github.com/shravva/microsoft-graph-docs/commits/ec94c3db0a9791f11c99b222a4898dec13ed90d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printershare-list-allowedgroups.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printershare-list-allowedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-allowedgroups?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-e5dd887e-aa64e391)
[api-reference/beta/api/printershare-list-allowedusers.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/printershare-list-allowedusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-allowedusers?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-16cd451d-aa64e391)
[api-reference/beta/resources/printershare.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-7f5e5d16-aa64e391)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-aa64e391)
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-aa64e391)
[api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/v1.0/api/userteamwork-teamsappinstallation-upgrade.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-teamsappinstallation-upgrade?view=graph-rest-1.0&branch=pr-en-us-10994) (>= graph-rest-1.0) | [Details](#user-content-34680944-aa64e391)
[concepts/toolkit/get-started/build-a-microsoft-teams-tab.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/toolkit/get-started/build-a-microsoft-teams-tab.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-a-microsoft-teams-tab?branch=pr-en-us-10994) | [Details](#user-content-48910927-aa64e391)
[concepts/toolkit/providers/teams.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/toolkit/providers/teams.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/teams?branch=pr-en-us-10994) | [Details](#user-content-ee8dfa19-aa64e391)
[api-reference/beta/api/chat-delete-installedapps.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-delete-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-installedapps?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-delete-tabs.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-delete-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-delete-tabs?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-list-installedapps.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-installedapps?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-list-tabs.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-list-tabs?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-patch-tabs.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-patch-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-patch-tabs?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-post-installedapps.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-post-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-installedapps?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-post-tabs.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-post-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-post-tabs?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/chat-teamsappinstallation-upgrade.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/chat-teamsappinstallation-upgrade.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chat-teamsappinstallation-upgrade?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/conversationmembers-add.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/conversationmembers-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conversationmembers-add?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/custodian-activate.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/custodian-activate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/custodian-activate?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/custodian-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/custodian-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/custodian-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/custodian-list-sitesources.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/custodian-list-sitesources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/custodian-list-sitesources?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/custodian-list-unifiedgroupsources.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/custodian-list-unifiedgroupsources.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/custodian-list-unifiedgroupsources?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/custodian-post-sitesources. [...]

2020-12-12 01:43 UTC, shravva commented on concepts/changelog.md
> +| Addition | beta | Added new optional, properties **addedStudentAction**, **notificationChannelUrl** to [educationAssignment](/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-v
Updated changelog and also JSON file.

2020-12-12 01:43 UTC, opbld32 commented
Docs Build status updates of commit _[ab3edef](https://github.com/shravva/microsoft-graph-docs/commits/ab3edef98de8ccc9e822964cc9c2baf49fb49820)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-b32dd054)
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-b32dd054)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-b32dd054"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 45, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 46, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta`````
 - **Line 46, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta`````
 - **Line 66, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

<a id="ac11ba7c-b32dd054"></a>
### [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-list-assignments.md(2,8), beta/api/educationuser-list-assignments.md(2,8), beta/api/privilegedrole-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'beta/api/educationclass-list-assignments.md(10,1), beta/api/educationuser-list-assignments.md(10,1), beta/api/privilegedrole-list-assignments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012120141431203-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CSKDd%2B7H%2Bijj8w89NznH123PE58YgcT9v45FuLAVjEw%3D&st=2020-12-12T01%3A38%3A48Z&se=2021-01-12T01%3A43%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830 [...]

2020-12-12 01:46 UTC, opbld33 commented
Docs Build status updates of commit _[d939044](https://github.com/shravva/microsoft-graph-docs/commits/d9390442266d6ab1fe1e5520b4bf638ac4203a07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-abe359c1)
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-abe359c1)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-abe359c1"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 45, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 46, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/educationAssignment?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 66, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

<a id="ac11ba7c-abe359c1"></a>
### [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-list-assignments.md(2,8), beta/api/educationuser-list-assignments.md(2,8), beta/api/privilegedrole-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'beta/api/educationclass-list-assignments.md(10,1), beta/api/educationuser-list-assignments.md(10,1), beta/api/privilegedrole-list-assignments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012120145249709-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yw%2FxJwVFl0pAlVV3023Pw%2BGvG3M9msXkSkZlcUNOoA4%3D&st=2020-12-12T01%3A41%3A48Z&se=2021-01-12T01%3A46%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain [...]

2020-12-12 01:53 UTC, opbld33 commented
Docs Build status updates of commit _[faa03f4](https://github.com/shravva/microsoft-graph-docs/commits/faa03f41c92efe7490f9ee24caf05106b03ee6ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-6b5cd0f0)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-6b5cd0f0)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="ac11ba7c-6b5cd0f0"></a>
### [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-list-assignments.md(2,8), beta/api/educationuser-list-assignments.md(2,8), beta/api/privilegedrole-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'beta/api/educationclass-list-assignments.md(10,1), beta/api/educationuser-list-assignments.md(10,1), beta/api/privilegedrole-list-assignments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-6b5cd0f0"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 66, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012120152101625-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qxn0b%2FCUH3lCmW59amknlIOdrqR%2FEQkDeNF0WdnLJ7I%3D&st=2020-12-12T01%3A48%3A27Z&se=2021-01-12T01%3A53%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-12 02:06 UTC, opbld34 commented
Docs Build status updates of commit _[911a963](https://github.com/shravva/microsoft-graph-docs/commits/911a9630ca56da5482c376503af194cd219c9bae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-35683ee0)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-35683ee0)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="ac11ba7c-35683ee0"></a>
### [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-list-assignments.md(2,8), beta/api/educationuser-list-assignments.md(2,8), beta/api/privilegedrole-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'beta/api/educationclass-list-assignments.md(10,1), beta/api/educationuser-list-assignments.md(10,1), beta/api/privilegedrole-list-assignments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-35683ee0"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 66, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012120205057150-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eRDJHhRPC%2FAnfSOumqjXnDiQ5I0THWplW3IShdfIBr0%3D&st=2020-12-12T02%3A01%3A40Z&se=2021-01-12T02%3A06%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-12 02:36 UTC, opbld31 commented
Docs Build status updates of commit _[f0cb39a](https://github.com/shravva/microsoft-graph-docs/commits/f0cb39a631660cbe62be0d2c6a14cc6932b51b44)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-4ba9c417)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-4ba9c417)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="ac11ba7c-4ba9c417"></a>
### [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-list-assignments.md(2,8), beta/api/educationuser-list-assignments.md(2,8), beta/api/privilegedrole-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'beta/api/educationclass-list-assignments.md(10,1), beta/api/educationuser-list-assignments.md(10,1), beta/api/privilegedrole-list-assignments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-4ba9c417"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 66, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 128, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012120234572094-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i0mamJd9cw0CnFc8vHmtLmQ9Oq3UBwDABoUNkWPrq9c%3D&st=2020-12-12T02%3A31%3A12Z&se=2021-01-12T02%3A36%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-12 02:39 UTC, Lauragra commented
@shravva , are you ready to merge this PR?

2020-12-12 02:41 UTC, Lauragra approved these changes

2020-12-14 20:06 UTC, opbld30 commented
Docs Build status updates of commit _[98ea2db](https://github.com/shravva/microsoft-graph-docs/commits/98ea2dbb2c464b10a040d841a6d014b4d65634f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) | [Details](#user-content-ac11ba7c-80f7e6f3)
[concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-10994) | [Details](#user-content-de0bbbbb-80f7e6f3)
[api-reference/beta/api/educationassignment-get.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-get?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationassignment-update.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationassignment-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationassignment-update?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-post-assignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignment.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignment?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/educationassignmentrecipient.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/educationassignmentrecipient.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/educationassignmentrecipient?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-10994) (graph-rest-beta) |
[changelog/Microsoft.EducationAssignment.json](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/changelog/Microsoft.EducationAssignment.json) | :white_check_mark:Succeeded | |

<a id="ac11ba7c-80f7e6f3"></a>
### [api-reference/beta/api/educationclass-list-assignments.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/api-reference/beta/api/educationclass-list-assignments.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List assignments - Microsoft Graph beta' is duplicated in: 'beta/api/educationclass-list-assignments.md(2,8), beta/api/educationuser-list-assignments.md(2,8), beta/api/privilegedrole-list-assignments.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List assignments' is duplicated with other articles: 'beta/api/educationclass-list-assignments.md(10,1), beta/api/educationuser-list-assignments.md(10,1), beta/api/privilegedrole-list-assignments.md(10,1)'. First level headings must be unique within a docset. NOTE: This Suggestion will become a Warning on 1/29/21.`````

<a id="de0bbbbb-80f7e6f3"></a>
### [concepts/changelog.md](https://github.com/shravva/microsoft-graph-docs/blob/shravva/eduAsgSettingProps/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012142005415805-10994%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=akeq572cTPYunaZlquqmxIjjGiIx0ahgL67VhwUFNyU%3D&st=2020-12-14T20%3A01%3A50Z&se=2021-01-14T20%3A06%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-14 20:09 UTC, shravva commented
Yes, its ready for merge.

2020-12-14 20:11 UTC, shravva commented
> @shravva , are you ready to merge this PR?

Yes, it's ready for merging. May I know when it could deploy then?

2020-12-15 03:10 UTC, merged