Public doc for outOfOfficeSettings in presence
microsoftgraph/microsoft-graph-docs pull request #10993
Opened 2020-12-09 22:20 UTC by elvinyang-msft

2020-12-09 22:21 UTC, opbld34 commented
Docs Build status updates of commit _[b2a6c4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2a6c4f8a579ea964867d43ed06cbd70a3172d84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/cloudcommunications-getpresencesbyuserid?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) |
[api-reference/beta/api/presence-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/presence-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/presence-get?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) |
[api-reference/beta/resources/outOfOfficeSettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/outOfOfficeSettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/outofofficesettings?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) |
[api-reference/beta/resources/presence.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/presence.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/presence?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012092220220426-10993%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=itQx%2FPgTklPVXBw9MlagyAatlrSY4skkeKCdZGJewXc%3D&st=2020-12-09T22%3A16%3A37Z&se=2021-01-09T22%3A21%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-09 23:52 UTC, jsandoval-msft requested changes
the indentation looks off on the first file.

2020-12-09 23:52 UTC, jsandoval-msft commented on api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md
> +      "activity": "InAMeeting",
The indentation looks wrong here.

2020-12-15 19:27 UTC, elvinyang-msft commented on api-reference/beta/api/cloudcommunications-getpresencesbyuserid.md
> +      "activity": "InAMeeting",
Changed from tab to spaces

2020-12-15 19:32 UTC, opbld32 commented
Docs Build status updates of commit _[59dd9cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59dd9cd1b13ba4376881ea1636bbd8beb54562b3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4e2d6064)

<a id="4e2d6064"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151932350805-10993%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yey%2B8gsa0R9P9m20PGj0NLTp6ka89PqIGSpl1X3kWts%3D&st=2020-12-15T19%3A27%3A51Z&se=2021-01-15T19%3A32%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 19:44 UTC, opbld30 commented
Docs Build status updates of commit _[9f7841e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f7841e07dd0c1f35352d34844aab8bc70d4e58e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e63ff364)

<a id="e63ff364"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151943320098-10993%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8l88czZlEwRhyDSgEZ6L6bzj04LMDC65AX0QeKJyRFc%3D&st=2020-12-15T19%3A39%3A35Z&se=2021-01-15T19%3A44%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-16 23:39 UTC, opbld33 commented
Docs Build status updates of commit _[5a1b704](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a1b704b65eaced0f3812b0175fe5424d1e94cf6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4099868f)

<a id="4099868f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012162339037377-10993%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MUn%2BuXakC26xioaQKk1Nkn8ovYGjHvo4T5iDr4J77pk%3D&st=2020-12-16T23%3A34%3A22Z&se=2021-01-16T23%3A39%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 21:45 UTC, opbld31 commented
Docs Build status updates of commit _[5e75b5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e75b5f851d977613fb08e33b4bc62c6699fb5f0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d41d6e8b)

<a id="d41d6e8b"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012212145159945-10993%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n56KaqpSgLN%2BN4GhRe7Qa5Woinygle0ANfsTYaRpPWE%3D&st=2020-12-21T21%3A40%3A34Z&se=2021-01-21T21%3A45%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 21:57 UTC, opbld30 commented
Docs Build status updates of commit _[590a28c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/590a28c6dcb305c90c0f0225786fdd27d3dedcdf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printershare-list-allowedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/printershare-list-allowedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-allowedgroups?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-e5dd887e-9118e810)
[api-reference/beta/api/printershare-list-allowedusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/printershare-list-allowedusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-list-allowedusers?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-16cd451d-9118e810)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-5c821ddc-9118e810)
[api-reference/beta/api/printjob-redirect.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/printjob-redirect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-redirect?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-8c3451fa-9118e810)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-8794bed8-9118e810)
[api-reference/beta/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/printerlocation.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerlocation?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-4ac81575-9118e810)
[api-reference/beta/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/printershare.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printershare?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-7f5e5d16-9118e810)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-c60d9ccc-9118e810)
[api-reference/beta/resources/regionalformatoverrides.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/resources/regionalformatoverrides.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/regionalformatoverrides?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-f04b6964-9118e810)
[concepts/migrate-azure-ad-graph-property-differences.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/concepts/migrate-azure-ad-graph-property-differences.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences?branch=pr-en-us-10993) | [Details](#user-content-600bab16-9118e810)
[concepts/teams-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/concepts/teams-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-concept-overview?branch=pr-en-us-10993) | [Details](#user-content-e5711e5f-9118e810)
[api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2cidentityuserflow-get-apiconnectorconfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-f7d6aab8-9118e810)
[api-reference/beta/api/b2cidentityuserflow-list-languages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2cidentityuserflow-list-languages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-languages?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-d46e88d4-9118e810)
[api-reference/beta/api/b2cidentityuserflow-list-userattributeassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2cidentityuserflow-list-userattributeassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-list-userattributeassignments?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-628e227a-9118e810)
[api-reference/beta/api/b2cidentityuserflow-post-userattributeassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2cidentityuserflow-post-userattributeassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-post-userattributeassignments?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-7d18482e-9118e810)
[api-reference/beta/api/b2cidentityuserflow-put-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2cidentityuserflow-put-apiconnectorconfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2cidentityuserflow-put-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-eb8291c7-9118e810)
[api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2xidentityuserflow-get-apiconnectorconfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-get-apiconnectorconfiguration?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-a922cb61-9118e810)
[api-reference/beta/api/b2xidentityuserflow-list-languages.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2xidentityuserflow-list-languages.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list-languages?view=graph-rest-beta&branch=pr-en-us-10993) (graph-rest-beta) | [Details](#user-content-a042910c-9118e810)
[api-reference/beta/api/b2xidentityuserflow-list-userattributeassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elviny/presenceOOF/api-reference/beta/api/b2xidentityuserflow-list-userattributeassignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/b2xidentityuserflow-list- [...]

2021-01-08 22:08 UTC, closed without merging