Rename DeviceStates to Devices
microsoftgraph/microsoft-graph-docs pull request #11014
Opened 2020-12-11 20:23 UTC by gapalani

2020-12-11 20:25 UTC, opbld33 commented
Docs Build status updates of commit _[9d69198](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d69198b098ebc2b47eaefb5ca9e10f90d4588f2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012112023578251-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N5mPRfN40bjiSL9axt%2FKLgRhgHBcFbliiy5g6H9iEDk%3D&st=2020-12-11T20%3A20%3A17Z&se=2021-01-11T20%3A25%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-11 23:25 UTC, elcarlosadrian approved these changes

2020-12-11 23:54 UTC, opbld34 commented
Docs Build status updates of commit _[942dadb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/942dadb1dfae5f171acbf4e8a6851e469a264f28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-719b12b9)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |

<a id="de0bbbbb-719b12b9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 37, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 38, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 59, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 121, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 122, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 122, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 123, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012112352567745-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LEqLfG9BnUtJOqbsETr%2BnYBNCB8rVhpqvRoBXmMzYso%3D&st=2020-12-11T23%3A49%3A11Z&se=2021-01-11T23%3A54%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 18:34 UTC, opbld33 commented
Docs Build status updates of commit _[fe559d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe559d61c6ba487f019cd163621f812913f78b3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-325a544c)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |

<a id="de0bbbbb-325a544c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151832480590-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Qvujmqz5t6%2BKNwdev9zYwGw01NjGjTYGkfl00Lml%2FUY%3D&st=2020-12-15T18%3A29%3A02Z&se=2021-01-15T18%3A34%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 18:35 UTC, opbld33 commented
Docs Build status updates of commit _[3781873](https://github.com/microsoftgraph/microsoft-graph-docs/commits/378187315bbe7a9b18498c3861d7da296a671d5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-53883b64)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |

<a id="de0bbbbb-53883b64"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151833202781-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oo4uHf%2Bk3%2Bf5GUC7iXWv%2F5R8vGdeM22hddef0wTnkaM%3D&st=2020-12-15T18%3A30%3A18Z&se=2021-01-15T18%3A35%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 18:47 UTC, opbld30 commented
Docs Build status updates of commit _[d5995bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5995bc423623428d60a817e16c0b71b13dc2478)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-94138087)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-94138087"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151845080665-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lz4NI0JwU5R6uOIqZScZA1jdiyBOwhQI1HevzEmGCQQ%3D&st=2020-12-15T18%3A42%3A17Z&se=2021-01-15T18%3A47%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 19:14 UTC, Lauragra commented on concepts/changelog.md
> +| Change | beta | Renamed the properties **includeDeviceStates** and **excludeDeviceStates** to **includeDevices** and **excludeDevices** in [conditionalAccessDevices](/graph/api/resources/conditiona
Please move this Changelog entry into December since we'll be publishing the update this month, I assume?

2020-12-15 19:20 UTC, opbld32 commented
Docs Build status updates of commit _[aa16388](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa163883f2a3aee8b02e70277423b59934c52ea4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-d04b3472)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-d04b3472"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 130, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151918566689-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GcLEm%2FFaaog1g1fC0nc67FnrMVuY7Q0EblSfi4Hc6iQ%3D&st=2020-12-15T19%3A15%3A07Z&se=2021-01-15T19%3A20%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 19:56 UTC, opbld32 commented
Docs Build status updates of commit _[2323373](https://github.com/microsoftgraph/microsoft-graph-docs/commits/232337397c83d7c2ef8700b138073c115b19a3b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-68904748)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-68904748"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 69, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 70, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151955175257-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=03Hq89%2B30kuhFUuwUQTEoCG%2BfbTbwtPPzfLdnE%2BASZ0%3D&st=2020-12-15T19%3A51%3A28Z&se=2021-01-15T19%3A56%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 19:56 UTC, gapalani commented on concepts/changelog.md
> +| Change | beta | Renamed the properties **includeDeviceStates** and **excludeDeviceStates** to **includeDevices** and **excludeDevices** in [conditionalAccessDevices](/graph/api/resources/conditiona
Done.

2020-12-15 19:57 UTC, Lauragra approved these changes

2020-12-15 19:59 UTC, Lauragra commented on changelog/Microsoft.IdentityProtectionServices.json
> +				{
We're not mentioning anywhere the properties that were removed/renamed. Isn't it relevant to mention that as well?

2020-12-15 20:00 UTC, opbld31 commented
Docs Build status updates of commit _[774fce5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/774fce52b806cba6b48e5e846261dac773b5a92e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-82c2360c)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-82c2360c"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 69, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 70, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 132, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 133, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012151959088290-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ozuZaQkZGAG1gfCXBwBeMO2lGpPfsZmKXWJdudRF%2F%2B8%3D&st=2020-12-15T19%3A55%3A43Z&se=2021-01-15T20%3A00%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-15 20:04 UTC, gapalani commented on changelog/Microsoft.IdentityProtectionServices.json
> +				{
Rename was what I had added to changelog md earlier, but this was the content generated by the changelog tool based on my graph schema changes.
https://microsoftgraph.visualstudio.com/onboarding/_git/AGS-OnboardingAutomationPipeline/pullrequest/6941

I haven't removed the old properties from the graph schema yet because our current flow would break until we transition smoothly to the new properties.

2020-12-15 20:07 UTC, gapalani commented on changelog/Microsoft.IdentityProtectionServices.json
> +				{
I would create another PR to publish schema when I remove the old properties. Do you think I could add Remove action to the changelog then?

2020-12-15 21:03 UTC, Lauragra commented on changelog/Microsoft.IdentityProtectionServices.json
> +				{
So the properties aren't getting removed from the schema but the new ones are added? Please see the guidelines for deprecating content, here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/73842/Deprecate-docs?anchor=deprecate-content-for-a-property-or-relationship. Seems like rather than removing the properties from the docs, they should be marked as deprecated until they are removed from the schema?

2020-12-15 22:04 UTC, Lauragra requested changes
Please follow the guidance for deprecated properties.

2020-12-15 22:27 UTC, opbld34 commented
Docs Build status updates of commit _[18cf6e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18cf6e83b0e0cb7a513b008d8d4fc01a1368f475)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-7457e38e)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-7457e38e"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 69, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 70, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 72, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 72, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152226129953-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bs8DfD246sM9JGBhNJSnF2DUsp3Gx1w%2Bx7%2Fw5Uq9J%2BI%3D&st=2020-12-15T22%3A22%3A32Z&se=2021-01-15T22%3A27%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-wo [...]

2020-12-15 22:28 UTC, opbld33 commented
Docs Build status updates of commit _[b30db9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b30db9c85a3df8f0e2d5d279ad7acdafa8531ea7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-ac9f8472)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ac9f8472"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 69, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 70, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 72, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 72, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012152227034564-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VhrXn%2FJgw3JoDKdS5wVllTn56yQZ%2FVQnB0SQ7LzQ7lQ%3D&st=2020-12-15T22%3A23%3A51Z&se=2021-01-15T22%3A28%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-work [...]

2020-12-15 22:35 UTC, gapalani commented on changelog/Microsoft.IdentityProtectionServices.json
> +				{
Updated the properties and changelog as per your recommendation.

2020-12-16 00:49 UTC, Lauragra approved these changes

2020-12-16 00:49 UTC, opbld33 commented
Docs Build status updates of commit _[78c9213](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78c9213ed40b4d659313d4f9dd8cbe8f345f6be4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) | [Details](#user-content-de0bbbbb-64054086)
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-64054086"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md)
 - **Line 69, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 70, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 71, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 72, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 40, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printershare?view=graph-rest-beta`````
 - **Line 68, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/emailauthenticationmethodconfiguration?view=graph-rest-beta`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 70, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 72, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/conditionalAccessDevices?view=graph-rest-beta`````
 - **Line 134, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printer?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-abort?view=graph-rest-beta`````
 - **Line 135, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printjob-redirect?view=graph-rest-beta`````
 - **Line 136, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/printjob?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012160048089149-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OFFwdz1dboequXlK5jRPuZuen0wTHUinGJV%2BADNHork%3D&st=2020-12-16T00%3A44%3A20Z&se=2021-01-16T00%3A49%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-workin [...]

2021-01-08 08:44 UTC, paulodero commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"ChangeType": "Change",
This should be `deprecation` no?

2021-01-08 08:47 UTC, paulodero requested changes

2021-01-08 08:47 UTC, paulodero commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"ChangeType": "Change",
Furthermore, the deprecated elements have not been annotated as deprecated in the docs.

2021-01-08 17:07 UTC, Lauragra commented on changelog/Microsoft.IdentityProtectionServices.json
> +					"ChangeType": "Change",
@paulodero , deprecation is not one of the values for ChangeType, according to our CDK guidance: 

ChangeType | The nature of the change. One of the possible values: addition, deletion or change. Filterable.

Can you please verify whether we should have a filter and ChangeType value for deprecation? @pixieofhugs , FYI.

2021-02-02 18:44 UTC, opbld31 commented
Docs Build status updates of commit _[63636db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63636dbf76d8efd8b16aac7dfc84718207173ddd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102021842466100-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VicDd88bFVFrO%2B%2FfsDrHWtNHK1IsIQUnBJq%2Bb312nDE%3D&st=2021-02-02T18%3A39%3A16Z&se=2021-03-05T18%3A44%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 18:53 UTC, opbld34 commented
Docs Build status updates of commit _[d63d9f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d63d9f67ed93726d4e7dc1b066cbb352cd5ed3ba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102021852203267-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IBj7cz%2FpDMwt%2FsSYXV4aO3vBFEFExuyR6xCTKh1fNv8%3D&st=2021-02-02T18%3A48%3A36Z&se=2021-03-05T18%3A53%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 18:56 UTC, opbld32 commented
Docs Build status updates of commit _[37e170b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37e170b271e6a26a6e5eebd2a246abbec76ff6de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/conditionalaccesspolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccesspolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccesspolicy-get?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/api/conditionalaccessroot-post-policies.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/api/conditionalaccessroot-post-policies.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/conditionalaccessroot-post-policies?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[api-reference/beta/resources/conditionalaccessdevices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/api-reference/beta/resources/conditionalaccessdevices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/conditionalaccessdevices?view=graph-rest-beta&branch=pr-en-us-11014) (graph-rest-beta) |
[changelog/Microsoft.IdentityProtectionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/changelog/Microsoft.IdentityProtectionServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/gapalani-rename-devices/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11014) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102021855353814-11014%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p87L%2FaalTfcdAClIpPtlkJztD7lzZmJG5RGQR6aG78o%3D&st=2021-02-02T18%3A51%3A42Z&se=2021-03-05T18%3A56%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 17:57 UTC, merged