teamwork Tag changes
microsoftgraph/microsoft-graph-docs pull request #11071
Opened 2020-12-17 23:55 UTC by bhartono

teamwork Tag changes

2020-12-17 23:57 UTC, opbld32 commented
Docs Build status updates of commit _[b479e0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b479e0c85f3e920d324cf912c2f5c7b06dcd6c7b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-59a96a0e-23f8a90c)
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-c3da1836-23f8a90c)
[api-reference/beta/api/teamworktag-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-5be677fc-23f8a90c)
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-f45faaa9-23f8a90c)
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-33c11a1e-23f8a90c)
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-deb91fa5-23f8a90c)
[api-reference/beta/api/teamworktagmember-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-8da151b2-23f8a90c)
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-36cf2978-23f8a90c)
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-6a991f15-23f8a90c)
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-1482c713-23f8a90c)
[api-reference/beta/api/teamworktagmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-db00c025-23f8a90c)
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-8e2ebc64-23f8a90c)
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4a8bc3cb-23f8a90c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) | [Details](#user-content-de0bbbbb-23f8a90c)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="59a96a0e-23f8a90c"></a>
### [api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="c3da1836-23f8a90c"></a>
### [api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-m [...]

2020-12-17 23:57 UTC, AkJo commented on api-reference/beta/api/teamworktag-create.md
> +POST /teams/{teamsId}/tags
{team-id}

2020-12-17 23:57 UTC, AkJo commented on api-reference/beta/api/teamworktag-create.md
> +POST https://graph.microsoft.com/beta/teams/{teamsId}/tags
Actual team id

2020-12-18 00:17 UTC, opbld30 commented
Docs Build status updates of commit _[6eb091a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6eb091a941196c8df41add1c0a9b95a578f9e66d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-59a96a0e-5a6e221a)
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-c3da1836-5a6e221a)
[api-reference/beta/api/teamworktag-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-5be677fc-5a6e221a)
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-f45faaa9-5a6e221a)
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-33c11a1e-5a6e221a)
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-deb91fa5-5a6e221a)
[api-reference/beta/api/teamworktagmember-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-8da151b2-5a6e221a)
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-36cf2978-5a6e221a)
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-6a991f15-5a6e221a)
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-1482c713-5a6e221a)
[api-reference/beta/api/teamworktagmember-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-db00c025-5a6e221a)
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-8e2ebc64-5a6e221a)
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4a8bc3cb-5a6e221a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) | [Details](#user-content-de0bbbbb-5a6e221a)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="59a96a0e-5a6e221a"></a>
### [api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````

<a id="c3da1836-5a6e221a"></a>
### [api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-m [...]

2020-12-18 03:17 UTC, opbld32 commented
Docs Build status updates of commit _[1ca21a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1ca21a93a62226c004de92ae58413078550b21a9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-817d8eb7)

<a id="817d8eb7"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012180317124247-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=94qbrHNloN7lycnyOcW6KVpQvMwTVP1b0Gpc6RG5aVM%3D&st=2020-12-18T03%3A12%3A32Z&se=2021-01-18T03%3A17%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-18 08:21 UTC, amitapl approved these changes

2020-12-18 08:21 UTC, amitapl commented on api-reference/beta/api/teamworktag-create.md
> +title: "Create teamworkTag"
teamwork tag? where did this name come from?
cc @anniecolonna

2020-12-18 08:21 UTC, amitapl commented on api-reference/beta/resources/teamworktagmember.md
> +description: "**TODO: Add Description**"
this is for next change?

2020-12-18 09:24 UTC, g2mula commented on changelog/Microsoft.Teams.Core.json
> +        {
Please also add an entry for the tags navigation property added to team entity

2020-12-18 17:46 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-create.md
> +title: "Create teamworkTag"
This name came from the standard Graph API category for Teams. There is also an instance of tags already in the O365 Graph APIs for outlook, so it should help users disambiguate. 

![image](https://user-images.githubusercontent.com/38053723/102644474-bc0cb480-4115-11eb-829f-1d0252adcfe7.png)

2020-12-18 17:57 UTC, anniecolonna commented on api-reference/beta/resources/teamworktag.md
> +Tags provide a flexible way for customers to classify users or groups based on a common attribute.
Added a little bit more detail from our help documentation on tags: 

"Tags provide a flexible way for customers to classify users or groups based on a common attribute within a team. For example, a "Nurse" or "Manager" or Designer" tag will enable users to reach groups of people in Teams without having to type every single name.  

Once a tag is added, users can @mention it in a channel. Everyone who has been assigned that tag will receive a notification just as they would if they were @mentioned individually. Users can also use a tag is to start a new chat with the members of that tag. "

2020-12-18 17:58 UTC, anniecolonna approved these changes
Added a suggestion on the tag definition, but it is also fine as is.

2020-12-18 18:37 UTC, bhartono commented on api-reference/beta/api/teamworktag-create.md
> +|Delegated (work or school account)|TeamworkTagReadWrite|
TeamworkTagReadWrite, this should be TeamworkTag.ReadWrite, not 1 word.
Also, is app context not supported ? I recalled that you guys requested both delegated and app context permission sometime ago.

2020-12-18 18:39 UTC, bhartono commented on api-reference/beta/api/teamworktag-get.md
> +|Delegated (work or school account)|TeamworkTagReadWrite, TeamworkTagRead|
incorrectly written permission, missing . (dot)

2020-12-18 18:43 UTC, bhartono commented on api-reference/beta/api/teamworktag-post-members.md
> +POST /teams/{teamsId}/tags/{teamworkTagId}/members
POST /teams/{**team-Id**}/tags/{teamworkTagId}/members

2020-12-18 18:51 UTC, bhartono commented on api-reference/beta/resources/enums.md
> +|standard|
add value and description as well if possible like chatType above

2020-12-18 18:52 UTC, bhartono commented on api-reference/beta/resources/teamworktagmember.md
> +**TODO: Add Description**
add proper description if any

2021-01-04 19:24 UTC, opbld30 commented
Docs Build status updates of commit _[290b796](https://github.com/microsoftgraph/microsoft-graph-docs/commits/290b796bd1581ebc4f64010721e6cd0a80d05a6f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4a8bc3cb-0e394fab)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) | [Details](#user-content-de0bbbbb-0e394fab)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="4a8bc3cb-0e394fab"></a>
### [api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md)
 - **Line 20, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamworktagmember-create.md'.`````

<a id="de0bbbbb-0e394fab"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md)
 - **Line 140, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamworkTag?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 141, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagMember?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 140, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamworkTag?view=graph-rest-beta`````
 - **Line 141, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/teamworkTagMember?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101041922400411-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6K2FOxXI1ANs8xOaSMso4r65K%2Bz6dsybfPAJlAuhMUg%3D&st=2021-01-04T19%3A19%3A14Z&se=2021-02-04T19%3A24%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account [...]

2021-01-04 21:01 UTC, rasikadhumal commented on api-reference/beta/api/teamworktag-create.md
> +|Delegated (work or school account)|TeamworkTagReadWrite|
app context is not supported yet.

2021-01-04 21:25 UTC, opbld30 commented
Docs Build status updates of commit _[70e4bcd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70e4bcdc25fcacda5bb7bd2cd4c176cfd15d0ca8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042124201223-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lT6386SsjY6ktQ5mb1sbBbk%2BsDrkRfQw%2FGbsHwvjImA%3D&st=2021-01-04T21%3A20%3A38Z&se=2021-02-04T21%3A25%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 22:15 UTC, opbld31 commented
Docs Build status updates of commit _[fe93608](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe93608e00e76709d3e4d79972a654870ea30157)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042213489503-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oTNcltvHja3O5UsbxpXE9lc3OP6AKfuS2rpOiPY9EtQ%3D&st=2021-01-04T22%3A10%3A07Z&se=2021-02-04T22%3A15%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 19:21 UTC, opbld32 commented
Docs Build status updates of commit _[ad2a247](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad2a2472259603aa0a0a7f8f0e02a68e7d02fefa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-3fb90d18)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

<a id="4b33441e61d32f646b88781171f64ffa-3fb90d18"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104011919107517-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z2DLJYmCTHCmwcSDW3HLMJ9NZVLyBCxTLkkj9o2m%2Bis%3D&st=2021-04-01T19%3A16%3A17Z&se=2021-05-02T19%3A21%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 19:31 UTC, opbld33 commented
Docs Build status updates of commit _[25731b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25731b9058c078ef8f6c830aeaf1dce971fcde3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-5fd5c685)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

<a id="4b33441e61d32f646b88781171f64ffa-5fd5c685"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104011930057144-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9j3KzXdgE%2FpgKluyirpjFWcQ3QdqCZiMNduyp1yCAP4%3D&st=2021-04-01T19%3A26%3A14Z&se=2021-05-02T19%3A31%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 19:45 UTC, opbld34 commented
Docs Build status updates of commit _[c851445](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8514455efe3322a5e2e855553bc6a592c57dedb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-57a459df)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

<a id="4b33441e61d32f646b88781171f64ffa-57a459df"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104011944069525-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x%2FrgO7KycdWdxfjVlJ2X3i0hocdWWhj5KTnnKButi38%3D&st=2021-04-01T19%3A40%3A37Z&se=2021-05-02T19%3A45%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 19:57 UTC, opbld34 commented
Docs Build status updates of commit _[169b011](https://github.com/microsoftgraph/microsoft-graph-docs/commits/169b011318d28ceb4b5b85505cb9fb66eacab502)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-0cd40704)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

<a id="4b33441e61d32f646b88781171f64ffa-0cd40704"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104011956030663-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a6tsj2Lq2L5Mt7dWIOL1pmYKYviKaAXpWW5qLyytFJc%3D&st=2021-04-01T19%3A52%3A19Z&se=2021-05-02T19%3A57%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 19:58 UTC, opbld33 commented
Docs Build status updates of commit _[58f2d30](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58f2d30264927ce12918593a910625fcacdd87cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-0d7d7414)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11071) |

<a id="4b33441e61d32f646b88781171f64ffa-0d7d7414"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104011957189798-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jRp6A5hhgAn%2B81gcP%2FQKpEwv9hDHGVm7hbujazR5XAQ%3D&st=2021-04-01T19%3A53%3A51Z&se=2021-05-02T19%3A58%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-04 05:08 UTC, RamjotSingh reviewed
Please add all the API, overview and requires resources (atleast teamworkTag) to the TOC to make the docs discoverable.

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktag-create.md
> +# Create teamworkTag
Create teamworkTag in a team

Doc generation doesnt generate docs with full context. So you can add clarification text.

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktag-get.md
> +# Get teamworkTag
Get teamworkTag in a team

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktag-post-members.md
> +# Create teamworkTagMember
Add member to an existing teamworkTag

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktag-update.md
> +Update the name of a tag in the team. Update the properties of a [teamworkTag](../resources/teamworktag.md) object.
```suggestion
Update an existing [teamworkTag](../resources/teamworktag.md) in a team.
```

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktagmember-delete.md
> +# Delete teamworkTagMember
```suggestion
# Remove member from a teamworkTag
```

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktagmember-get.md
> +# Get teamworkTagMember
```suggestion
# Get member of a teamworkTag
```

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/api/teamworktagmember-list.md
> +# List teamworkTagMembers
```suggestion
# List members in a teamworkTag
```

2021-04-04 05:08 UTC, RamjotSingh commented on api-reference/beta/resources/teamworktag.md
> +
Would be worthwhile to mention the membership operations here as well. That way you can make the teamworkTagMember doc a bit lighter.

2021-04-04 05:08 UTC, RamjotSingh commented on concepts/changelog.md
> +| Addition | beta | Added the [teamworkTag](/graph/api/resources/teamworkTag?view=graph-rest-beta&preserve-view=true) resource type. |
This file should no longer be needed as changelog is now generated using the jsons.

2021-04-05 15:09 UTC, opbld31 commented
Docs Build status updates of commit _[431c533](https://github.com/microsoftgraph/microsoft-graph-docs/commits/431c5337860b78b0f8014f854f7b434a9081c0a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-be89d151)
[api-reference/beta/api/teamworktag-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-create?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="4b33441e61d32f646b88781171f64ffa-be89d151"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051507467773-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4gT99TtbqOU253vRrFsYYBs%2B112Zqs0B20luyeNh9RQ%3D&st=2021-04-05T15%3A04%3A09Z&se=2021-05-06T15%3A09%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 00:31 UTC, Lauragra commented on api-reference/beta/api/teamworktag-create.md
> +# Create teamworkTag
Global: Please add the missing beta disclaimer to all the files.

2021-04-16 00:33 UTC, Lauragra commented on api-reference/beta/api/teamworktag-create.md
> +|Delegated (work or school account)|TeamworkTag.ReadWrite|
Is TeamworkTag a new permission? Pls. make sure that it's documented in the Permissions reference.

2021-04-16 00:37 UTC, Lauragra commented on api-reference/beta/api/teamworktag-create.md
> +# [HTTP](#tab/http)
Remove this H1; it gets added via the snippets generation process.

2021-04-16 00:38 UTC, Lauragra commented on api-reference/beta/api/teamworktag-create.md
> +---
The file name here should be teamworktag-post.

2021-04-16 00:38 UTC, Lauragra commented on api-reference/beta/api/teamworktag-create.md
> +author: "rasikadhumal"
Global: Do you want to put your name as author?

2021-04-16 00:39 UTC, Lauragra commented on api-reference/beta/api/teamworktag-delete.md
> +**Note:** The response object shown here might be shortened for readability.
Delete this note when there's no response body.

2021-04-16 00:43 UTC, Lauragra commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
Is this getting the tags navigation property on a team? If so, then the file name should be team-list-tags, and the topic title is List tags.

2021-04-16 03:05 UTC, Lauragra commented on api-reference/beta/api/teamworktagmember-delete.md
> +**Note:** The response object shown here might be shortened for readability.
Remove note.

2021-04-16 03:15 UTC, Lauragra commented on api-reference/beta/resources/team.md
> +|tags|[teamworkTag](../resources/teamworktag.md) collection|The Tags of the team.|
Would a better description here be "The tags associated with the team." Also note that tags should be lowercase.

2021-04-16 03:16 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +Tags provide a flexible way for customers to classify users or groups based on a common attribute within a team. For example, a "Nurse" or "Manager" or Designer" tag will enable users to reach groups
This should have a summary sentence first, like "Represents a tag associated with a team." Then you can provide the context about how tags are used.

2021-04-16 03:16 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +Tags provide a flexible way for customers to classify users or groups based on a common attribute within a team. For example, a "Nurse" or "Manager" or Designer" tag will enable users to reach groups
Are tag names typically enclosed in quotation marks? Suggest removing the quotes.

2021-04-16 03:17 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +Once a tag is added, users can @mention it in a channel. Everyone who has been assigned that tag will receive a notification just as they would if they were @mentioned individually. Users can also us
The word "once" is often misread by global readers because it means "one time". In this case you mean "when" or "after"; pls. update.

2021-04-16 03:18 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +|id|String|Id of the tag.|
The abbreviation for identifier is ID; please apply to instances where you refer to an ID in text.

2021-04-16 03:19 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the [teamworkTag](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTag?view=graph-rest-beta) resource type",
For the new resource types, you might also want to mention "and associated methods". Also be sure to add periods to the descriptions.

2021-04-16 03:21 UTC, Lauragra requested changes
Please incorporate editorial comments.

2021-04-19 18:09 UTC, opbld32 commented
Docs Build status updates of commit _[8742e9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8742e9fe79733039a78c9de89b9441964641743b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0254ffa9)

<a id="0254ffa9"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104191808485439-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rvHEFwYTNtbtPcr6hKPtBPCeupCCPl%2BlbfAkIJ35qSw%3D&st=2021-04-19T18%3A04%3A12Z&se=2021-05-20T18%3A09%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:12 UTC, opbld31 commented
Docs Build status updates of commit _[455628e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/455628efa677488e36cae2b6faa438a2c534b309)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-02365a1c)

<a id="02365a1c"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230511472989-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eKRkWu1Am5g3HP%2FG0p0dUbX7xEOq0hjOmXpJ5cF8chg%3D&st=2021-04-23T05%3A07%3A03Z&se=2021-05-24T05%3A12%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:12 UTC, opbld32 commented
Docs Build status updates of commit _[24be130](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24be1309e263f771ad00e7dc0b8e4323bb631fa9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-405aef8e)

<a id="405aef8e"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230512036741-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mAFoC2LYETLXh%2BerMzWpqVTBbNdy9sm5J5YCpbodS9Q%3D&st=2021-04-23T05%3A07%3A29Z&se=2021-05-24T05%3A12%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:12 UTC, opbld31 commented
Docs Build status updates of commit _[ffe51e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffe51e42c0db260c7b6ac31d7664dfa09a260b45)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-76a11934)

<a id="76a11934"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230512268549-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SEPBkeON4gKRSIEhYVFcqIfOdQfcTb9%2BLzqZyS3s41k%3D&st=2021-04-23T05%3A07%3A52Z&se=2021-05-24T05%3A12%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:13 UTC, opbld34 commented
Docs Build status updates of commit _[9463c36](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9463c365f79ee7687a136ff644ba9e4f4dfbe43e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-546b6405)

<a id="546b6405"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230512432226-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1ePoydgly5SnOgnuosO0ATCKAY5tSb1o1KBMX0gOoI8%3D&st=2021-04-23T05%3A08%3A12Z&se=2021-05-24T05%3A13%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:13 UTC, opbld30 commented
Docs Build status updates of commit _[9a6ca1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a6ca1a932a012aa7454e648d62d6cd48369a64b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-048cdfcf)

<a id="048cdfcf"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230513046679-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vx%2F38hCPsUJ4oz5OzJmDJZRrWhYLPOuXbLrKMFtclHg%3D&st=2021-04-23T05%3A08%3A28Z&se=2021-05-24T05%3A13%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:13 UTC, opbld31 commented
Docs Build status updates of commit _[caa3809](https://github.com/microsoftgraph/microsoft-graph-docs/commits/caa3809e7ad5c655ea63e3322dcdb52aaacf93d8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a6f49872)

<a id="a6f49872"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230513202513-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CUOHk0Yznxsx%2FjN3xztBiDwVJophF40eX8skICiSOpw%3D&st=2021-04-23T05%3A08%3A51Z&se=2021-05-24T05%3A13%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 05:14 UTC, opbld30 commented
Docs Build status updates of commit _[43a7e14](https://github.com/microsoftgraph/microsoft-graph-docs/commits/43a7e1422de598690bd322dc5b16770d8b65403b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-abd0bf20)

<a id="abd0bf20"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104230513345895-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XYlFi3K0kJRG9LRTgvFs4vqzNDbbOJWqRI3zTVLI28E%3D&st=2021-04-23T05%3A09%3A10Z&se=2021-05-24T05%3A14%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:02 UTC, opbld34 commented
Docs Build status updates of commit _[e04b680](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e04b6807fe80d2f62e8043c18ed0da2f9d52bc1b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-32535940)

<a id="32535940"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270002326087-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MtSIkiGJKbh%2Btz5%2BHJFENFTjRNub2FP3eY4QskmgasM%3D&st=2021-04-26T23%3A57%3A48Z&se=2021-05-28T00%3A02%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:03 UTC, opbld31 commented
Docs Build status updates of commit _[bbd79bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbd79bd80b41588aaa75f46d4ab05d78e39dfbff)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-35376a01)

<a id="35376a01"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270002460813-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qXl4WHRdQq8H6CwbqN1a9qDLTn%2FTp0Kkv4fWD5Kbsw0%3D&st=2021-04-26T23%3A58%3A15Z&se=2021-05-28T00%3A03%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:03 UTC, opbld32 commented
Docs Build status updates of commit _[d65d644](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d65d6443b47d0d6b72430f80b76de1466df140b4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0336cd30)

<a id="0336cd30"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270002591824-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MrGsyqdMGgeG4WwP2k2czVkoYXThUtKZsCLa1cT%2BMzU%3D&st=2021-04-26T23%3A58%3A36Z&se=2021-05-28T00%3A03%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:08 UTC, opbld33 commented
Docs Build status updates of commit _[140b9e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/140b9e06810df44f71282e46abcf6283b3a118e0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-71fb1c8a)

<a id="71fb1c8a"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270007458007-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4COMRWtGMcqKHWyqg5tv5pP28w7yvqvz5hWH%2FVGKqDk%3D&st=2021-04-27T00%3A03%3A04Z&se=2021-05-28T00%3A08%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:08 UTC, opbld32 commented
Docs Build status updates of commit _[a067eae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a067eae6a8b9d8f55b98ca83ab37d5e06afd0450)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a8ea1de6)

<a id="a8ea1de6"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270008205762-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p9ygzLSwaqMQsa0qc%2Bikt15mlSJsMOpIWqsEn%2BFMwtY%3D&st=2021-04-27T00%3A03%3A41Z&se=2021-05-28T00%3A08%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:09 UTC, opbld32 commented
Docs Build status updates of commit _[1f61e89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f61e89e78006108a9fac6f4e3dd1892d1383027)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c7687840)

<a id="c7687840"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270008382316-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z7fDCUArWEnfr8emM%2BBAUymGbdG6HHMMdQFBtyev3mk%3D&st=2021-04-27T00%3A04%3A07Z&se=2021-05-28T00%3A09%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:09 UTC, opbld34 commented
Docs Build status updates of commit _[214c326](https://github.com/microsoftgraph/microsoft-graph-docs/commits/214c326ec6472a2b1ad2130459294af7c4c88a2c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-612d9362)

<a id="612d9362"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270009074999-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p0iOhdRS7NGNgGoqpZERnypDYaAYe2nrcB%2FAj4XPaQ0%3D&st=2021-04-27T00%3A04%3A24Z&se=2021-05-28T00%3A09%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:09 UTC, opbld30 commented
Docs Build status updates of commit _[144ba9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/144ba9c991b5963870e95209f27cc6e04c1e512a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ab7402c5)

<a id="ab7402c5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270009235657-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BgsbukC98L7LmM8%2Bm2QSr21hvYpY9qbT7De%2FFgPdkpE%3D&st=2021-04-27T00%3A04%3A54Z&se=2021-05-28T00%3A09%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:10 UTC, opbld32 commented
Docs Build status updates of commit _[e17a544](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e17a5448579343be24a30ef340631886d42bc828)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1d1a16b2)

<a id="1d1a16b2"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270009349842-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LP71pa0cxdoeDOw1DYJ4BTzQe0Rc%2BLuhgFm9mI8oZLU%3D&st=2021-04-27T00%3A05%3A15Z&se=2021-05-28T00%3A10%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:10 UTC, opbld31 commented
Docs Build status updates of commit _[1e5f8b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1e5f8b588818fc6ee41a66f2ac500ce71cceeeaf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cb4b393a)

<a id="cb4b393a"></a>
###
 - **[Error-CannotMergeCommit]** `````Cannot merge commit 1e5f8b588818fc6ee41a66f2ac500ce71cceeeaf in branch bhartono/teamworkTag of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 34c4b2dce03a64a94ee6ec3f11cce74c577c67d8). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270009569839-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GiANUC8MB6HCE3qsAO20W%2BX9oL2Cegk9k4aSjeKSXzQ%3D&st=2021-04-27T00%3A05%3A37Z&se=2021-05-28T00%3A10%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 00:11 UTC, opbld33 commented
Docs Build status updates of commit _[3d820f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d820f87be6cd226ecf2ca993c76e4ad38cae194)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-db18c596)

<a id="db18c596"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104270010371930-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aotpCA%2B2Tu7zLAvCyfGX8Ln8K3AUSSKqtpE%2FULg68mQ%3D&st=2021-04-27T00%3A06%3A18Z&se=2021-05-28T00%3A11%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 16:54 UTC, opbld31 commented
Docs Build status updates of commit _[acbeda3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/acbeda3afab5600350b8f51034addfc63d0013a3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6a624765)

<a id="6a624765"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061653133144-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nu%2Fq3P573yC6xpuyFxDhDmTyoLXJU%2BsDBEe5dVKKgi4%3D&st=2021-05-06T16%3A49%3A18Z&se=2021-06-06T16%3A54%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 16:54 UTC, opbld32 commented
Docs Build status updates of commit _[92fe73d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92fe73d56bd06795d9e24826902be155808b28bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e46777a5)

<a id="e46777a5"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061653489902-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qylHrEm%2BmZcrHLeNt4mLxOQVRU%2FucDCmwFEoRS8ChZE%3D&st=2021-05-06T16%3A49%3A35Z&se=2021-06-06T16%3A54%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 16:56 UTC, opbld34 commented
Docs Build status updates of commit _[8a02237](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a022374000f15c6e92ae59c4207d548e54e811c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 16:57 UTC, opbld33 commented
Docs Build status updates of commit _[6714965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6714965006ee41778ba5f50a5b18927eb1a0dd5d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-47ec9db2)

<a id="47ec9db2"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061656428141-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bYp536kWecADOOnLAmDyPL1MvnPh6CD67XMUIhew0CA%3D&st=2021-05-06T16%3A52%3A00Z&se=2021-06-06T16%3A57%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 16:57 UTC, opbld30 commented
Docs Build status updates of commit _[6714965](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6714965006ee41778ba5f50a5b18927eb1a0dd5d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7b3c350f)

<a id="7b3c350f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061656532353-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fq7mKmsDC6k4jDAnjuQfn5SelzCkMq9LKufjI6Q3wB8%3D&st=2021-05-06T16%3A52%3A35Z&se=2021-06-06T16%3A57%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-06 16:59 UTC, opbld30 commented
Docs Build status updates of commit _[cad1f42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cad1f423a10827236034e1d53b466245016531f6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0c7edbf4)

<a id="0c7edbf4"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105061657181309-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6Bg0s8W%2BI%2FP6X5xF%2B5qBMMfHCuLvX5UseMtFT4%2BDcpQ%3D&st=2021-05-06T16%3A54%3A08Z&se=2021-06-06T16%3A59%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-10 20:28 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
We don't have navigation properties in v1

2021-05-12 21:51 UTC, Lauragra commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
This is a beta topic - I'm not sure that I understand your comment here. The team resource has a tags navigation property defined in the live beta metadata.

2021-05-12 22:02 UTC, opbld31 commented
Docs Build status updates of commit _[8ca5b25](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ca5b255765d1090a6e43fd61174e8816c6d81c5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-07950241)

<a id="07950241"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105122202036476-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XaKz81LPd5UJyRybXe%2Ft6PH8qljhRZqhkQA1%2FrS9oko%3D&st=2021-05-12T21%3A57%3A19Z&se=2021-06-12T22%3A02%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 22:03 UTC, opbld30 commented
Docs Build status updates of commit _[902683c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/902683c4c2b7e4dadea56efef55f812b73ff707d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-feb78c26)

<a id="feb78c26"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105122202525404-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XfU6%2B7j%2FOLDTsliCmrUGAhs%2BP7nXLMeT1nDtnxUJYB8%3D&st=2021-05-12T21%3A58%3A07Z&se=2021-06-12T22%3A03%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 22:04 UTC, opbld32 commented
Docs Build status updates of commit _[7f17553](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f17553b6c9d3c30ea784e920eb3184367340e20)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bdab6b9b)

<a id="bdab6b9b"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105122203371480-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QUVY3YhHtfKm80k%2Ba%2BqRLy6jXECgTyf6nofkMhN%2B4SA%3D&st=2021-05-12T21%3A59%3A46Z&se=2021-06-12T22%3A04%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 22:05 UTC, opbld30 commented
Docs Build status updates of commit _[0c0bdd8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c0bdd83e35fabf57f5ec205442f97afb3bdc43b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-370c78a7)

<a id="370c78a7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105122204074673-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bhwyayaPGRZM9WFPD5Iu844sgoH1jjlqw35qBJxd8zQ%3D&st=2021-05-12T22%3A00%3A05Z&se=2021-06-12T22%3A05%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 22:29 UTC, opbld34 commented
Docs Build status updates of commit _[c581361](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c581361e3b34c391793c246003347a4d8a01dd50)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-39d42de1)

<a id="39d42de1"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105122227449619-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5BEA3BlvenHne%2FX5uG93hmBu1UBumQCv5DqpCZTIz5s%3D&st=2021-05-12T22%3A23%3A59Z&se=2021-06-12T22%3A28%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-12 22:33 UTC, opbld34 commented
Docs Build status updates of commit _[153517c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/153517c6756fb880b41142b3d822c6d5c1cc6c7b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-59108766b209bdfed6b947b28f4077ca-d264ff09)
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-0dc14476039f775fc5296a4c79b72955-d264ff09)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-d264ff09)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="59108766b209bdfed6b947b28f4077ca-d264ff09"></a>
### [api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md)
 - **Line 2, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````

<a id="0dc14476039f775fc5296a4c79b72955-d264ff09"></a>
### [api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md)
 - **Line 26, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamworktag-create.md'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-d264ff09"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105122232242149-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EFdbPNJOWQuovdPxsuMa6hii8UqbwHOeaZrHPAu1K%2Bo%3D&st=2021-05-12T22%3A28%3A47Z&se=2021-06-12T22%3A33%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external [...]

2021-05-18 20:26 UTC, anniecolonna commented on api-reference/beta/resources/teamworktag.md
> +
@RamjotSingh, does that mean we should move this methods section from https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071 to this part here?



<!--StartFragment--><h2 id="methods" class="heading-anchor" style="box-sizing: inherit; margin: 32px 0px 12px -1.875rem; padding: 0px 0px 0px 1.875rem; font-size: 2.125rem; font-weight: 600; outline-color: inherit; line-height: 1.3; position: relative; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Methods</h2><div class="table-scroll-wrapper" style="box-sizing: inherit; outline-color: inherit; overflow: auto hidden; color: rgb(23, 23, 23); font-family: &quot;Segoe UI&quot;, SegoeUI, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
Method | Return type | Description
-- | -- | --
List teamworkTagMembers | teamworkTagMember&nbsp;collection | Get a list of the&nbsp;teamworkTagMember&nbsp;objects and their properties.
Get teamworkTagMember | teamworkTagMember | Read the properties and relationships of a&nbsp;teamworkTagMember&nbsp;object.
Delete teamworkTagMember | None | Deletes a&nbsp;teamworkTagMember&nbsp;object.

</div><!--EndFragment-->

2021-05-18 20:32 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-delete.md
> +**Note:** The response object shown here might be shortened for readability.
Note removed in my view
![image](https://user-images.githubusercontent.com/38053723/118719623-8dd2f400-b7dd-11eb-9d05-ed214e7e0d86.png)

2021-05-18 20:34 UTC, anniecolonna commented on api-reference/beta/api/teamworktagmember-delete.md
> +**Note:** The response object shown here might be shortened for readability.
Note was removed
![image](https://user-images.githubusercontent.com/38053723/118719806-c541a080-b7dd-11eb-8587-3d73643e5887.png)

2021-05-18 20:39 UTC, anniecolonna commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the [teamworkTag](https://docs.microsoft.com/en-us/graph/api/resources/teamworkTag?view=graph-rest-beta) resource type",
![image](https://user-images.githubusercontent.com/38053723/118720464-78aa9500-b7de-11eb-8a57-0961b2e1ec12.png)

2021-05-18 20:42 UTC, opbld30 commented
Docs Build status updates of commit _[0df974b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0df974bb47ffdedd0fffed5cd0f27f2a41dcfcc5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-59108766b209bdfed6b947b28f4077ca-aa3867e0)
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-0dc14476039f775fc5296a4c79b72955-aa3867e0)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-aa3867e0)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="59108766b209bdfed6b947b28f4077ca-aa3867e0"></a>
### [api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md)
 - **Line 2, Column 1**: **[Warning-[author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-missing?branch=main)]** `````Missing required attribute: 'author'. Add the current author's GitHub ID.`````

<a id="0dc14476039f775fc5296a4c79b72955-aa3867e0"></a>
### [api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md)
 - **Line 26, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/teamworktag-create.md'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-aa3867e0"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182041244045-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JPOR7Vkk6eXvT5SU63ovA6AQsj8oHRymS5Tg5iWOkLg%3D&st=2021-05-18T20%3A37%3A49Z&se=2021-06-18T20%3A42%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external d [...]

2021-05-18 20:52 UTC, opbld31 commented
Docs Build status updates of commit _[fde5297](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fde5297cecf63a327aa0ba95bb00e9783b233a02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-1f25220e)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-1f25220e"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182051112966-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2slPVhstjwaN3PJtbkTqj0a3AE5wtkncj7Gp1Z4GvdI%3D&st=2021-05-18T20%3A47%3A31Z&se=2021-06-18T20%3A52%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 20:59 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-create.md
> +author: "rasikadhumal"
Changes reflected in teamworktag-post.md

2021-05-21 20:20 UTC, opbld32 commented
Docs Build status updates of commit _[a149c97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a149c97076e4562edd4616628b8dc62ad83ec8ac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-49f47ba8)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-49f47ba8"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212019146019-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PEphzPPZwtSTwRW0i6mBup3Eay%2BLMBJ6MiVCSj2VhvM%3D&st=2021-05-21T20%3A15%3A30Z&se=2021-06-21T20%3A20%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 20:31 UTC, opbld33 commented
Docs Build status updates of commit _[25a6337](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25a6337d56fe6ee505f0b208d71c2f2fbc0aec6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-7540eede)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-7540eede"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212029355406-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ggXh6POutrfZVy7zZTFl8r58PplNAvHEpQbo8MsO1do%3D&st=2021-05-21T20%3A26%3A53Z&se=2021-06-21T20%3A31%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 20:32 UTC, Lauragra commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
If this operation is getting the list of tags that are applied to a team, the file name should be team-list-tags and the title and H1 should be "List tags" (the navigation property name).

2021-05-21 20:33 UTC, Lauragra commented on api-reference/beta/api/teamworktag-list.md
> +        "displayName": "Sample tag name 1",
Global: It will make the examples more helpful if you use actual fictitious values.

2021-05-21 20:47 UTC, Lauragra commented on api-reference/beta/api/teamworktag-post-members.md
> +# Add member to an existing teamworkTag
The H1 here should be "Create teamworkTagMember". We wouldn't use add because in the schema, the nav property has containsTarget = true. For details, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title?anchor=when-to-use-%22create%22-vs-%22add%22-and-%22delete%22-vs-%22remove%22

2021-05-21 20:54 UTC, opbld31 commented
Docs Build status updates of commit _[063ceb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/063ceb6a632cea622aeb394f4966af6b7cb00f1b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-3222c1a5)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-3222c1a5"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212052446073-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G9ri%2Fmn0nFm1J%2BPyWsayGwTikws7Zs3fIEI2lax8OME%3D&st=2021-05-21T20%3A49%3A02Z&se=2021-06-21T20%3A54%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:03 UTC, opbld34 commented
Docs Build status updates of commit _[ea317a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea317a7743ce4e495b67ff47b1b963d0baddfc55)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-01aef21a)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-01aef21a"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212100452197-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MaDeLJ4%2B9FpuhRpgfAQF%2F4YTkRTJhtC%2FEJwwtryZjtk%3D&st=2021-05-21T20%3A58%3A09Z&se=2021-06-21T21%3A03%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:04 UTC, opbld34 commented
Docs Build status updates of commit _[c13fb6c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c13fb6c6d9daa5fc1a7528bff070adf55ac3d000)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-f471f052)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-f471f052"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212102500077-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AK%2Bx5z6etb%2BJtNSyZsvUV%2BnxtzivuLXRqzyet0rP5Us%3D&st=2021-05-21T20%3A59%3A32Z&se=2021-06-21T21%3A04%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:06 UTC, opbld30 commented
Docs Build status updates of commit _[2932ef8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2932ef8456061effd1d7d07ce20d9cb1ce696c0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-c5a5077c)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-c5a5077c"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212104149899-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U6%2Bpzu2ZZugTadscn5wb0LMHuo6FbWAo%2FCjK40xVd%2Bs%3D&st=2021-05-21T21%3A01%3A53Z&se=2021-06-21T21%3A06%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:16 UTC, opbld34 commented
Docs Build status updates of commit _[296e1bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/296e1bda8774399c3fa51e1255479c1024c04692)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-f8773462)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-f8773462"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212115272019-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4TaRAI52U%2FQdEg2wCMMhtjVBAcyV4rZ55KgUcUk78HU%3D&st=2021-05-21T21%3A11%3A45Z&se=2021-06-21T21%3A16%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:34 UTC, opbld32 commented
Docs Build status updates of commit _[3f2fb42](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f2fb424ccc7ffedcf2a555f00390c8117b7ab21)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-b8954ce2)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-b8954ce2"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212133083131-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xuQB4gk1YhcZFFqpunIwWYMseKQcfY%2Fy5Si9QQkTI18%3D&st=2021-05-21T21%3A29%3A18Z&se=2021-06-21T21%3A34%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:36 UTC, opbld32 commented
Docs Build status updates of commit _[f05a508](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f05a508615b663e3462a724128d62fe803d780e6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-d74d14bf)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-d74d14bf"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212134595732-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QvXAqfx%2F%2BbwHbxIib7P5ZkhJTD1xv20Vz6DnpQLvXNY%3D&st=2021-05-21T21%3A31%3A14Z&se=2021-06-21T21%3A36%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:36 UTC, Lauragra commented on api-reference/beta/api/teamworktagmember-delete.md
> +# Remove member from a teamworkTag
This H1 title should be "Delete teamworkTagMember".

2021-05-21 21:44 UTC, Lauragra commented on api-reference/beta/api/teamworktagmember-get.md
> +# Get member of a teamworkTag
H1 title here should match the title - "Get teamworkTagMember".

2021-05-21 21:50 UTC, opbld32 commented
Docs Build status updates of commit _[c511352](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c51135282c7412dd0c01a8f77163e3ad82fa672e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-bb42af36)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-bb42af36"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212149026685-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IfC3XM%2BXmzFOBYP%2Bcsyg8EPabR0BvnDd%2FnjRIiPl3BE%3D&st=2021-05-21T21%3A45%3A19Z&se=2021-06-21T21%3A50%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:55 UTC, opbld34 commented
Docs Build status updates of commit _[f71628c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f71628cef0bfafee0788bcea2a0197374a8de652)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-5148e9ac)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-5148e9ac"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212154272875-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g5BipYUh57USDNRkGdVQ2Hibhit8edUF%2Fg6GcOMldS0%3D&st=2021-05-21T21%3A50%3A42Z&se=2021-06-21T21%3A55%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 21:56 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +description: "Tags provide a flexible way for customers to classify users or groups based on a common attribute"
The description here should be the description of the resource, so, "Represents a tag associated with a team."

2021-05-21 22:01 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +|[List teamworkTags](../api/teamworktag-list.md)|[teamworkTag](../resources/teamworktag.md) collection|Get a list of the [teamworkTag](../resources/teamworktag.md) objects and their properties.|
The links in the Description column are self-referencing. Please remove the links. In general in text when we're not linking to a resource, we apply bold formatting to resource names, so please make the teamworkTag resource name bold in the descriptions.

2021-05-21 22:02 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +|[List teamworkTags](../api/teamworktag-list.md)|[teamworkTag](../resources/teamworktag.md) collection|Get a list of the [teamworkTag](../resources/teamworktag.md) objects and their properties.|
The descriptions that you provided were a bit different than the generic generated descriptions - do you want the descriptions here to match those?

2021-05-21 22:02 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +|[Delete teamworkTag](../api/teamworktag-delete.md)|None|Deletes a [teamworkTag](../resources/teamworktag.md) object.|
We always use imperative verbs for the method descriptions, so in this case, please change Deletes to Delete.

2021-05-21 22:05 UTC, Lauragra commented on api-reference/beta/resources/teamworktag.md
> +|id|String|Id of the tag.|
The abbreviation for identifier is ID, please update the casing here.

2021-05-21 22:22 UTC, Lauragra commented on api-reference/beta/resources/teamworktagmember.md
> +Represents a user in the team who has a tag applied to them.
We're not actually talking about a specific team, but any possible team, so we should change the article here and in the description from "the team" to "a team".

2021-05-21 22:27 UTC, Lauragra commented on api-reference/beta/resources/teamworktagmember.md
> +|[List teamworkTagMembers](../api/teamworktagmember-list.md)|[teamworkTagMember](../resources/teamworktagmember.md) collection|Get a list of the [teamworkTagMember](../resources/teamworktagmember.md)
Same comments here - remove the self-referencing links and apply bold, change Deletes to Delete, ensure that the descriptions in the table match the descriptions in the method topics.

2021-05-21 22:27 UTC, Lauragra commented on api-reference/beta/resources/teamworktagmember.md
> +|tenantID|String|The tenantID that the member of the tag is a part of.|
Would this description be more clear: "The ID of the tenant that the tag member is a part of."?

2021-05-21 22:29 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "Description": "Added the **teamworkTagType** enumeration type",
Add a period here.

2021-05-21 22:31 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "teamworkTag,team",
ChangedApiName and Target are single valued, so the value there should just be "team".

2021-05-21 22:38 UTC, Lauragra commented on concepts/permissions-reference.md
> +## Teams Tags permissions
Change the H2 here to "Teams tag permissions".

2021-05-21 22:51 UTC, opbld31 commented
Docs Build status updates of commit _[e353545](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e353545ded5a29a848794b7b7373b8f961a654e7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-ed27a578)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-ed27a578"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212250018017-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YN4KpuRGoo07CEtC%2BhF5lww7sMKHQUwQbwpZhfQEGBU%3D&st=2021-05-21T22%3A46%3A18Z&se=2021-06-21T22%3A51%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 22:53 UTC, opbld34 commented
Docs Build status updates of commit _[86af6f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86af6f6d1b14225e0460f9f9c95ce6eea45e2297)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-bbf8fafa)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-bbf8fafa"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212252123043-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=11FVva4jzbksnzJ124rDb%2BzroSuFThu8ZdLQP80ix0w%3D&st=2021-05-21T22%3A48%3A40Z&se=2021-06-21T22%3A53%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 22:54 UTC, opbld31 commented
Docs Build status updates of commit _[2cae7d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2cae7d4c040b0dc5b4db3d018a043bfdd11d16c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-5344fbb4)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-5344fbb4"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212253331313-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pRYDDf2yxKM96xDMlyJ%2FBGGj2xX6GKvddizisr6UZmU%3D&st=2021-05-21T22%3A49%3A56Z&se=2021-06-21T22%3A54%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 22:56 UTC, opbld30 commented
Docs Build status updates of commit _[8de6dd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8de6dd14ad442a2c2da9e771d1e4ab4ad7ea88c9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-69f6c0be)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-69f6c0be"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212254470394-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aiOCjKKTyVCdRG2M3a3EIgGZTWkBXD4Gq4OCGjFNGgs%3D&st=2021-05-21T22%3A51%3A11Z&se=2021-06-21T22%3A56%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 22:57 UTC, opbld33 commented
Docs Build status updates of commit _[07fb709](https://github.com/microsoftgraph/microsoft-graph-docs/commits/07fb7094a1d068c179407a9cae0b4f1f060409d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-2cdeeb34)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-2cdeeb34"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212255409619-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l8IQAMawIAVxmUcEzO%2F58NIek5u66hXI%2FtZk6Mz9Aew%3D&st=2021-05-21T22%3A52%3A43Z&se=2021-06-21T22%3A57%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 22:59 UTC, opbld34 commented
Docs Build status updates of commit _[a6cd829](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6cd829b6a04ea5b048d6144eef2bf63f03efb86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-27c22bcf)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-27c22bcf"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212256567898-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=31WOpuXQaCMAEGjfGAOwmmBPC6eyQpi9NtqbeFGXk08%3D&st=2021-05-21T22%3A54%3A18Z&se=2021-06-21T22%3A59%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 23:02 UTC, opbld33 commented
Docs Build status updates of commit _[de116b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de116b923b774b6a4b6ef34d31620ada36f1b4b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-80706c5f)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-80706c5f"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212301207063-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZHetl8PsJEcaeXoXlS5k%2FSvTTUvdPm%2F2VEmR%2FFTSrz8%3D&st=2021-05-21T22%3A57%3A37Z&se=2021-06-21T23%3A02%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 23:05 UTC, opbld33 commented
Docs Build status updates of commit _[15a39ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15a39add3a5c3658c1b1770273dcb7c1feb2ba95)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-2318698c)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-2318698c"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212304060946-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fQRCQoAO6jXiE%2BFpKY3Vl6OHwel4ljNIBeR0QtYTPy0%3D&st=2021-05-21T23%3A00%3A23Z&se=2021-06-21T23%3A05%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 23:14 UTC, opbld33 commented
Docs Build status updates of commit _[67138fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67138fe5ddc01ddec735f030c1e17cb7ad603bc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-8e2d1347)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-8e2d1347"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212313308093-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M7M6eVSb5dHR1ObHtUonDJkiyLLK1NcfbkDwTjoDnaU%3D&st=2021-05-21T23%3A09%3A51Z&se=2021-06-21T23%3A14%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 23:19 UTC, anniecolonna commented on api-reference/beta/resources/teamworktag.md
> +|[List teamworkTags](../api/teamworktag-list.md)|[teamworkTag](../resources/teamworktag.md) collection|Get a list of the [teamworkTag](../resources/teamworktag.md) objects and their properties.|
@Lauragra , where can I find the generic generated descriptions?

2021-05-21 23:21 UTC, opbld30 commented
Docs Build status updates of commit _[0ec34a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ec34a2eeef2ba4133ac982be41f0fc83835c5db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-0bc96131)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-0bc96131"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212319430600-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U%2FfpD2zLg9KiIK1KMwlvXtTjtT%2FJlVgi67ZLK4ZFG1s%3D&st=2021-05-21T23%3A16%3A01Z&se=2021-06-21T23%3A21%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 23:24 UTC, opbld34 commented
Docs Build status updates of commit _[e2fda7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e2fda7f7c9582f04c1a3decf8a4384b4ffa26e09)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-3df1eaef)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-3df1eaef"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105212323406463-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sT0N6Dsy%2FpAGhi2gxp9kVPfNDY6XIsVNZgJfA7ZLWlM%3D&st=2021-05-21T23%3A19%3A48Z&se=2021-06-21T23%3A24%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-22 00:07 UTC, opbld32 commented
Docs Build status updates of commit _[14a2249](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14a2249e03eecaa4cdbb59bb0a5668d03ff0c4a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-8e098dbb)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-8e098dbb"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220006071153-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DclO%2BMWTriJmrkc5xplGKxZm8EVMUc66bhrqWNwE9yU%3D&st=2021-05-22T00%3A02%3A20Z&se=2021-06-22T00%3A07%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-22 00:08 UTC, opbld31 commented
Docs Build status updates of commit _[82e378a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/82e378a685194525ae0a72be9f8225356f12d3a4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-9eb34cce)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-9eb34cce"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220006509143-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pB16fj0D7x56oUW%2FoeYKc5qk2MIGZVmiaWZ4%2FoLBi%2Fc%3D&st=2021-05-22T00%3A03%3A23Z&se=2021-06-22T00%3A08%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-22 00:09 UTC, opbld34 commented
Docs Build status updates of commit _[59d78dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59d78dd0a4128bd31f3741ad6e14dff5215fd2b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-14c74b37)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-14c74b37"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105220007380699-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Zhqf3v4KpENIYcE%2F5IA1vOHAk7pgEsKzzD0FRJJotBQ%3D&st=2021-05-22T00%3A04%3A44Z&se=2021-06-22T00%3A09%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 15:40 UTC, opbld30 commented
Docs Build status updates of commit _[6683695](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6683695cd36f1cf2a7903bb5484eb03e8c94e0d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-05e34935)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-05e34935"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021538370604-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y1oBAD5kmoEN0JaSRjzbJ6dsf83MUwvrsGjiNZJM1EI%3D&st=2021-06-02T15%3A35%3A31Z&se=2021-07-03T15%3A40%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 15:42 UTC, opbld34 commented
Docs Build status updates of commit _[a680d88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a680d88f6f05bc07973a50cc27b5ea7a596b99d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-9bb59408)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-9bb59408"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021539287081-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VRMXsU5m%2FgZ23qCYWOJw05hJEuHf536slLFEq5Vk12k%3D&st=2021-06-02T15%3A37%3A14Z&se=2021-07-03T15%3A42%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 15:51 UTC, opbld30 commented
Docs Build status updates of commit _[6f9f3d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f9f3d98d5c515a63a8e998b3cba0144b711b525)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-8cf19085)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-8cf19085"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021549058477-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1yw2Hk9cgHEmFX%2FVza4c3SsMe3%2FL6wzkPPpem9dCNvM%3D&st=2021-06-02T15%3A46%3A08Z&se=2021-07-03T15%3A51%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 15:52 UTC, opbld34 commented
Docs Build status updates of commit _[c79a819](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c79a81980c00f6dba2b30dd895f4c67c54b4f4fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-d9c2f2f0)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-d9c2f2f0"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021550079801-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AvAM75cJRKbiZLI0XH3t0PA%2Fm6OXc%2FOnw%2BcVmqCFFVU%3D&st=2021-06-02T15%3A47%3A38Z&se=2021-07-03T15%3A52%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 15:54 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
@seankeating, can you please help with this one?

2021-06-02 15:54 UTC, opbld34 commented
Docs Build status updates of commit _[573ec53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/573ec533965c83cdfd1cdf58ae7f6d47ccc77759)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-644a4c74)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-644a4c74"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021551393994-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FYaw4%2FMSBXy%2BjN7dIudHOb5EJ%2FoulCYw16SqYVMpyZg%3D&st=2021-06-02T15%3A49%3A20Z&se=2021-07-03T15%3A54%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 15:55 UTC, anniecolonna commented on api-reference/beta/resources/teamworktag.md
> +|[List teamworkTags](../api/teamworktag-list.md)|[teamworkTag](../resources/teamworktag.md) collection|Get a list of the [teamworkTag](../resources/teamworktag.md) objects and their properties.|
Updated

2021-06-02 15:56 UTC, opbld32 commented
Docs Build status updates of commit _[b869383](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b869383fac279bbb910f7cbcac59d574a7b51eba)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-10ee6db2)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-10ee6db2"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021555022485-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=95%2Fx3fntU3nw%2Bq5zc9%2FU2u4hverNQfXi6e9Pv3aUxgo%3D&st=2021-06-02T15%3A51%3A34Z&se=2021-07-03T15%3A56%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 21:23 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
@RamjotSingh , do you know on this one? I don't think we have a plan for navigation properties yet and users won't be able to get from teamID to team from here.

2021-06-07 12:53 UTC, opbld31 commented
Docs Build status updates of commit _[fb435d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb435d2eeb262f26913bb72a417a3d3394bcaf50)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-60977933)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-60977933"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071251306325-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=toaSNSPNF%2BmFQxubeRWyuLkpj9udUnmcKVC8JBSZcwc%3D&st=2021-06-07T12%3A48%3A20Z&se=2021-07-08T12%3A53%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 12:58 UTC, opbld32 commented
Docs Build status updates of commit _[2e245e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e245e37d5e07d60c98b21f31e05939f6b58d4b7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-2a9395d2)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-2a9395d2"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071256359210-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vrhrOf6xABSPvK9CmIFi7MfKcTa2zAHkxfrOUTGLgM0%3D&st=2021-06-07T12%3A53%3A02Z&se=2021-07-08T12%3A58%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 17:10 UTC, anniecolonna commented on api-reference/beta/api/teamworktag-list.md
> +title: "List teamworkTags"
Ramjot suggested 
[6/7/2021 9:13 AM] Ramjot Singh
navigation properties is how tags are built. teams/id/tags makes tags a navigation property (urls are driven by navigation properties)
talk about this thru relationship sections under /beta

2021-06-14 17:22 UTC, opbld34 commented
Docs Build status updates of commit _[d696825](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d696825db898c5b089dba2ad5f64f95e09a094cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-37adc54c)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-37adc54c"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106141721085041-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QXHKm9dbmXahfY7w4460ZbZL6LIdGy6HLbHmxfosMQM%3D&st=2021-06-14T17%3A17%3A45Z&se=2021-07-15T17%3A22%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 23:43 UTC, opbld32 commented
Docs Build status updates of commit _[e8bd5d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8bd5d515c6f39be1790c954ff38ae05c7894076)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-afa51870)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-afa51870"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152342172164-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vRZT7A%2Bwug90%2B095or8EseQC8WfCJnDwKipUMcAXi%2BA%3D&st=2021-06-15T23%3A38%3A46Z&se=2021-07-16T23%3A43%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 23:45 UTC, opbld34 commented
Docs Build status updates of commit _[0b64189](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b6418931cbc9e69cc21afd57c996827cc267632)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-5fedffce)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-5fedffce"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152343129161-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qK7WnBuOs3mpV%2BShVBCxKNomEnSPgRPlFU8%2FuhfDXv4%3D&st=2021-06-15T23%3A40%3A35Z&se=2021-07-16T23%3A45%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 23:58 UTC, opbld30 commented
Docs Build status updates of commit _[49b43a0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/49b43a0db1614d27eb851bde318508f39242100f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-73d94dc7)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-73d94dc7"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106152356599445-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P3pHHe5YcGymUdPz%2BLKm2XE3ab81zDgRn7%2FuBr5caiA%3D&st=2021-06-15T23%3A53%3A33Z&se=2021-07-16T23%3A58%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:06 UTC, opbld32 commented
Docs Build status updates of commit _[e5e212b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5e212bc4b1c2c53dbcf115e41ce4b0404854466)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-b70d42a0)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-b70d42a0"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160004266861-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y5aFH2zEKZ6w%2BN%2B7yE7KlWJt6Va4UpHZe07x1j4leQY%3D&st=2021-06-16T00%3A01%3A21Z&se=2021-07-17T00%3A06%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:08 UTC, opbld30 commented
Docs Build status updates of commit _[a3e9196](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3e91965b1f176ec5868e58b76d68f504e685661)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-f0053ffd)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-f0053ffd"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160007221236-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XB%2B3korQggzscEpiPRve5N5%2BWgWLs%2BZMO6wH9l9xrtY%3D&st=2021-06-16T00%3A03%3A56Z&se=2021-07-17T00%3A08%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:10 UTC, opbld34 commented
Docs Build status updates of commit _[a96f741](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a96f741b9dc8953596206a1431791916d2ae65c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-febc5784)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-febc5784"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160007573596-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7piMRHmOzCDlzQoSqCIB9GtqCsi14XmSx1ueEOzYlnc%3D&st=2021-06-16T00%3A05%3A28Z&se=2021-07-17T00%3A10%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:12 UTC, opbld31 commented
Docs Build status updates of commit _[238fdaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/238fdaa5641afd544543ca6f381e99695701acb9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-cf72cc7a)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-cf72cc7a"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106160009560603-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RlL%2BWgLjdqDgI3uSgrkiAXkTH3feSZS7nGHZB7J2ZH8%3D&st=2021-06-16T00%3A07%3A15Z&se=2021-07-17T00%3A12%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 00:22 UTC, Lauragra requested changes
Please add the new resources and APIs to the TOC so they are discoverable for users.

2021-06-16 14:48 UTC, opbld30 commented
Docs Build status updates of commit _[2951e89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2951e8979014589aba70999af7bc9097ac33673b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-0c659933)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-0c659933"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 76, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106161446464478-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JckzyfBDONsVkgjZcffgxwOEL1gdU9zgMIMvzFIp8YI%3D&st=2021-06-16T14%3A43%3A55Z&se=2021-07-17T14%3A48%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-16 14:49 UTC, anniecolonna commented
> Please add the new resources and APIs to the TOC so they are discoverable for users.
![image](https://user-images.githubusercontent.com/38053723/122241413-5e181a00-ce77-11eb-9835-f1f6343f638d.png)

https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md

2021-06-17 23:46 UTC, anniecolonna commented
Re-opening, closed in error

2021-06-17 23:46 UTC, opbld34 commented
Docs Build status updates of commit _[fbac76d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbac76dfc35716c973cbdaab752e45bdafe94a7d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1c9de46d)

<a id="1c9de46d"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106172346162901-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O%2F3xU%2B1ss3CF1hb5A0je5On2DEH9lvEvfp2AUzsOQ%2FQ%3D&st=2021-06-17T23%3A41%3A38Z&se=2021-07-18T23%3A46%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 23:55 UTC, opbld34 commented
Docs Build status updates of commit _[68e2e55](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68e2e55e150cef6d8579e8d9a8fc6c4dd8113f64)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-e1e83ae8)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-e1e83ae8"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106172353462344-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=md7%2FLSNHEH0V8snW97hmajNFAFhmbwGiIT3DGXhnZZ8%3D&st=2021-06-17T23%3A50%3A20Z&se=2021-07-18T23%3A55%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 15:59 UTC, Lauragra commented on api-reference/beta/resources/teams-api-overview.md
> +|[tag](../resources/teamworktag.md)|[List](../api/teamworktag-list.md), [Create](../api/teamworktag-post.md), [Get](../api/teamworktag-get.md), [Update](../api/teamworktag-update.md), [Delete](../api
We should use the resource name here - teamworkTag.

2021-06-18 16:02 UTC, Lauragra commented on api-reference/beta/resources/teams-api-overview.md
> +|[tag](../resources/teamworktag.md)|[List](../api/teamworktag-list.md), [Create](../api/teamworktag-post.md), [Get](../api/teamworktag-get.md), [Update](../api/teamworktag-update.md), [Delete](../api
Why don't we have a resource that we can link to for line 31? There isn't a resource named activityFeedNotification. I think we need to remove the row in line 31 and move the operations into the other resource rows - chat, team.

2021-06-18 16:04 UTC, Lauragra commented on api-reference/beta/resources/teamworktagmember.md
> +
The resource topic is missing the Methods table with the list of operations that can be performed on the teamworkTagMember object - please add.

2021-06-18 16:05 UTC, Lauragra commented on api-reference/beta/resources/teams-api-overview.md
> +|[tagMember](../resources/teamworktagmember.md)|[List](../api/teamworktagmember-list.md), [Get](../api/teamworktagmember-get.md), [Delete](../api/teamworktagmember-delete.md)|
The resource name here should be teamworkTagMember. Also note my comment that we don't currently list the associated methods in the teamworkTagMember resource topic.

2021-06-21 22:05 UTC, anniecolonna commented on api-reference/beta/resources/teamworktagmember.md
> +
I thought I got feedback to take it out, but might have misread, added it back:

![image](https://user-images.githubusercontent.com/38053723/122833511-f5c79f00-d2a1-11eb-87e5-32c057fa1904.png)

2021-06-21 22:08 UTC, anniecolonna commented on api-reference/beta/resources/teams-api-overview.md
> +|[tag](../resources/teamworktag.md)|[List](../api/teamworktag-list.md), [Create](../api/teamworktag-post.md), [Get](../api/teamworktag-get.md), [Update](../api/teamworktag-update.md), [Delete](../api
Removed line 31

2021-06-21 22:08 UTC, opbld34 commented
Docs Build status updates of commit _[54e4a0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54e4a0a65e7fa9e0dfbc77e70c3b020c8dc39523)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-46d0d6e5)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-46d0d6e5"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106212205328750-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J3wJRRiHFTkIEgEIBmbyc%2F1f9LthrGX2uG048tjr3ts%3D&st=2021-06-21T22%3A03%3A57Z&se=2021-07-22T22%3A08%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 22:11 UTC, anniecolonna commented on api-reference/beta/resources/teams-api-overview.md
> +|[tagMember](../resources/teamworktagmember.md)|[List](../api/teamworktagmember-list.md), [Get](../api/teamworktagmember-get.md), [Delete](../api/teamworktagmember-delete.md)|
Updated 

|[tagMember](../resources/teamworkTagMember.md)|[List](../api/teamworkTagMember-list.md), [Get](../api/teamworkTagMember-get.md), [Delete](../api/teamworkTagMember-delete.md)|

2021-06-21 22:11 UTC, anniecolonna commented on api-reference/beta/resources/teams-api-overview.md
> +|[tag](../resources/teamworktag.md)|[List](../api/teamworktag-list.md), [Create](../api/teamworktag-post.md), [Get](../api/teamworktag-get.md), [Update](../api/teamworktag-update.md), [Delete](../api
|[tag](../resources/teamworkTag.md)|[List](../api/teamworkTag-list.md), [Create](../api/teamworkTag-post.md), [Get](../api/teamworkTag-get.md), [Update](../api/teamworkTag-update.md), [Delete](../api/teamworkTag-delete.md)|

2021-06-21 22:13 UTC, opbld34 commented
Docs Build status updates of commit _[cb58dce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb58dcecca98fee90c59d1b4142781def79d39c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-229a83f9)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-229a83f9"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106212209525223-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bGbtFg4kqDUDmmKoF3O9LcF3eve6QW80oRcqmPOf7%2Fc%3D&st=2021-06-21T22%3A08%3A21Z&se=2021-07-22T22%3A13%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 22:17 UTC, opbld31 commented
Docs Build status updates of commit _[8599dfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8599dfba7758868e0fc2926f2077292389024be6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-cce45760)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-cce45760"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106212211566920-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=npk7p2olAthHYkKMhI8cZkEb1356SQ6%2FOEliJKpqor8%3D&st=2021-06-21T22%3A12%3A02Z&se=2021-07-22T22%3A17%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 00:38 UTC, opbld31 commented
Docs Build status updates of commit _[513cce2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/513cce29e3f6c801acac400bc0a7af3df5159e7b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-73cce5cc)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-73cce5cc)

<a id="0817dce4456c16725d5333633847d38f-73cce5cc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml)
 - **Line 13636, Column 7**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 13615, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-73cce5cc"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220036430794-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=61rkldcPSanYuaJqJxKzdJlfuBI17Bfo9bvS%2FZQ806s%3D&st=2021-06-22T00%3A33%3A30Z&se=2021-07-23T00%3A38%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:12 UTC, opbld34 commented
Docs Build status updates of commit _[a1fa93e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1fa93e7a6f3072498803db28c61907e9f9cb2d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-776dde26)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-776dde26)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="0817dce4456c16725d5333633847d38f-776dde26"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml)
 - **Line 13626, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'teamworktag-delete.md'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-776dde26"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220209155025-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=huHY6f8txapd%2FaG3ZQrlpKuiMcWtBKawkQaMrZ0eCwU%3D&st=2021-06-22T02%3A07%3A48Z&se=2021-07-23T02%3A12%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=broken [...]

2021-06-22 02:16 UTC, opbld30 commented
Docs Build status updates of commit _[66ccad0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66ccad09d682465d5a26c468331be387498df4f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1b4aed5e)
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-1b4aed5e)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="0817dce4456c16725d5333633847d38f-1b4aed5e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml)
 - **Line 13626, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'teamworktag-delete.md'.`````

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-1b4aed5e"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220211142430-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8o7PQ3EFUNll0vJ0Glopopg9c0ffqou7UQXvTP0GeAQ%3D&st=2021-06-22T02%3A11%3A22Z&se=2021-07-23T02%3A16%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenli [...]

2021-06-22 02:21 UTC, opbld32 commented
Docs Build status updates of commit _[aa00047](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa0004756bd73dd2856ae84d71d78848b5650373)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) | [Details](#user-content-14fe87dd5b22e699f3fd2c86bf3a7763-52d62e58)
[api-reference/beta/api/teamworktag-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post-members.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post-members?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-post?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktag-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktag-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-update?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-get?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/api/teamworktagmember-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/api/teamworktagmember-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktagmember-list?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teams-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teams-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teams-api-overview?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktag.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktag.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktag?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/resources/teamworktagmember.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/teamworktagmember.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworktagmember?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworktag-delete?view=graph-rest-beta&branch=pr-en-us-11071) (graph-rest-beta) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/concepts/permissions-reference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11071) |

<a id="14fe87dd5b22e699f3fd2c86bf3a7763-52d62e58"></a>
### [api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/teamworkTag/api-reference/beta/resources/team.md)
 - **Line 77, Column 33**: **[Suggestion-[docs-link-absolute](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams' will be broken in isolated environments. Replace with a relative link.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220219301961-11071%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VpnEOi6ks6pEE2pA5JS%2F55sJG59LjERWWau2WhR8Tf8%3D&st=2021-06-22T02%3A16%3A17Z&se=2021-07-23T02%3A21%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:23 UTC, merged