Updating postman collection steps
microsoftgraph/microsoft-graph-docs pull request #11075
Opened 2020-12-18 04:23 UTC by jthake-msft

Updating the postman collection steps due to improvements to Postman collections capabilities.

2020-12-18 04:25 UTC, opbld30 commented
Docs Build status updates of commit _[4428363](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4428363facdd8169b859a2757631dd770e76e315)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012180424005067-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DPQFO9cEk1JyZjhFxUkFTeL%2Ft1ERywrpr8UJjPwsxfI%3D&st=2020-12-18T04%3A20%3A24Z&se=2021-01-18T04%3A25%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 05:33 UTC, opbld31 commented
Docs Build status updates of commit _[ddb3d75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ddb3d75a146fddf7fbb34e56151189ce2a0fa66d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101220531440376-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z%2FY%2Brz8nCBycifCM324NRAsVz0t5s8bsR%2FQPRkHVty8%3D&st=2021-01-22T05%3A28%3A41Z&se=2021-02-22T05%3A33%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 05:35 UTC, Lauragra approved these changes

2021-01-22 05:38 UTC, Lauragra commented on concepts/use-postman.md
> +> [!VIDEO https://youtu.be/3RTHY3jScmA]
I can't verify that these videos work on the review site; I'm not sure why.

2021-01-22 05:40 UTC, opbld33 commented
Docs Build status updates of commit _[351f43e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/351f43e6eeebac11fb67d3fcecc49f2ee90b4f86)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101220539420548-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qwbFGbBcTyOnCnhuOKsS5vIkQAFB7RjWAGDt1t22sBQ%3D&st=2021-01-22T05%3A35%3A53Z&se=2021-02-22T05%3A40%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 20:30 UTC, opbld30 commented
Docs Build status updates of commit _[210d5f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/210d5f1e09e1656d8930b2907eff65041d24eb47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101222029135985-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TAAl84WspXsXe9ntuMR46o3VQDZn9NF44l9gzzaf3SA%3D&st=2021-01-22T20%3A25%3A27Z&se=2021-02-22T20%3A30%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 20:31 UTC, Lauragra approved these changes

2021-01-23 03:50 UTC, angelgolfer-ms commented on concepts/use-postman.md
> +2. Hover over the **Microsoft Graph** collection on the left side, click the parathensis, and select **Create a fork**.
Line 21:
I am doing this on a new desktop machine, never downloaded anything Postman before. I don't know if there's any other step I should have done, but I don't see any parentheses, and don't see "Create a fork" by hovering or clicking icons in the left pane.

2021-01-23 03:52 UTC, angelgolfer-ms commented on concepts/use-postman.md
> +2. Hover over the **Microsoft Graph** collection on the left side, click the parathensis, and select **Create a fork**.
Is it clicking a single parenthesis, or clicking a set of parentheses?
(You have a typo btw.)

2021-01-23 04:01 UTC, angelgolfer-ms commented on concepts/use-postman.md
>  3. Choose the **eye** icon to the right and then choose **Edit**.
Line 61:
Without being able to see the actual icon, I'd like you to update this if necessary:
If the icon is an image of an eye, then just use plain text, no bolding of the word "eye" necessary.
If the icon is text that says "eye", then yes, leave this as is, bolded text.

2021-01-23 04:14 UTC, opbld33 commented
Docs Build status updates of commit _[de8bc33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de8bc33fb18dc5747d86ad6e4dae0bb2f17726b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230413043691-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hYZJTS9ocElmr2cT0v7OerxAziEcvRWkF1id5oirKIs%3D&st=2021-01-23T04%3A09%3A18Z&se=2021-02-23T04%3A14%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 04:49 UTC, angelgolfer-ms requested changes
Hi @jthake-msft , 
I attempted to verify the first steps but per my comment, I didn't succeed. I trust you must have stepped through the few numbered lists yourself. The remaining part of my review is therefore for readability; that also matters because many customers use Postman!
So please take a look at my comments in a couple of places.

FYI I also went ahead and applied some [Microsoft Voice](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=28939) principles to a number of sentences. In general:
"Get to the point fast
Lead with what’s most important. Front-load keywords for scanning. Make customer choices and next steps obvious..." 
"Revise weak writing
Most of the time, start each statement with a verb. Edit out you can and there is, there are, there were. "
I usually do not apply changes on behalf of the author so that they get a chance to do it right. In the interest of time and saving us another round of review, please see the delta in my main [commit](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11075/commits/de8bc33fb18dc5747d86ad6e4dae0bb2f17726b1), address the inline comments, and I'll gladly consider my content review as complete. Please let me know if you have any questions. Thanks!

2021-01-23 04:49 UTC, opbld34 commented
Docs Build status updates of commit _[3190f5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3190f5b9596ddd906f2b87d5f2d68a13de553788)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230448233181-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=23bBjDNcrMklT1OQxda69uymR5AkBCo4zDdE74teDUQ%3D&st=2021-01-23T04%3A44%3A47Z&se=2021-02-23T04%3A49%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 16:14 UTC, jthake-msft commented on concepts/use-postman.md
> +2. Hover over the **Microsoft Graph** collection on the left side, click the parathensis, and select **Create a fork**.
Directly from thee link in step 1 you should see this @angelgolfer-ms . BTW the YouTube video makes it clearer and thats why i want it embedded (@Lauragra )

![image](https://user-images.githubusercontent.com/6786616/105732436-4995ae00-5ee5-11eb-9a83-b2b4bbadde0a.png)

2021-01-26 04:40 UTC, jthake-msft commented
@Lauragra @angelgolfer-ms  @jasonjoh I have updated the steps now based on your feedback.  Thank you for catching those mistakes. Parenthesis are not ellipsis ;-) 

@angelgolfer-ms  if you have time I'd love you to try this again.

2021-01-26 04:43 UTC, opbld33 commented
Docs Build status updates of commit _[3478217](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3478217a9f04d219a7a2e480153b93a6da77a4c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101260442325949-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=za4kE5eOHdAlsDSqHXJgccnJ69EpX9qEXptVJ9b6fYs%3D&st=2021-01-26T04%3A38%3A44Z&se=2021-02-26T04%3A43%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 05:28 UTC, opbld32 commented
Docs Build status updates of commit _[a610165](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a61016515ae75e5be939a7d1d6cd53876c52b8d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101270527297271-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U3HoNEl8zxpMM2jUNh1S%2BQld%2B8XlC%2F55zyKl0Z6cdQw%3D&st=2021-01-27T05%3A23%3A42Z&se=2021-02-27T05%3A28%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 06:54 UTC, opbld30 commented
Docs Build status updates of commit _[792214d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/792214d527d8b3cb6652d474c4a12d1a6dfad2ec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101270652464991-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vf1wqZYD9wQOhTZYCOsSCeBLNUmySiQLNyoMNMAOzTQ%3D&st=2021-01-27T06%3A49%3A17Z&se=2021-02-27T06%3A54%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 20:39 UTC, NikCharlebois commented on concepts/use-postman.md
> +2. Fill in a label for your own fork. This can be any text.
I would add a step between 1 and 2 that let's the user know they need to login to Postman first otherwise the option to select **My Workspace** is not available.

2021-01-27 20:40 UTC, NikCharlebois commented on concepts/use-postman.md
> +
I would add a step at the end which specifies that the user has to click on the **Fork Collection** button

2021-01-27 20:59 UTC, NikCharlebois commented on concepts/use-postman.md
> +6. Create a new variable called `TenantID` and  set the **Current value** to the Directory (tenant) ID value from the step 3.17.
I think you mean from step 3.15 and not 3.17 for the TenantID

2021-01-27 23:27 UTC, jthake-msft commented on concepts/use-postman.md
> +6. Create a new variable called `TenantID` and  set the **Current value** to the Directory (tenant) ID value from the step 3.17.
thanks for the catch.

2021-01-27 23:29 UTC, jthake-msft commented on concepts/use-postman.md
> +2. Fill in a label for your own fork. This can be any text.
good idea

2021-01-27 23:31 UTC, jthake-msft commented on concepts/use-postman.md
> +
nic etouch

2021-01-27 23:33 UTC, opbld32 commented
Docs Build status updates of commit _[27f2402](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27f24029ebe9cb3262ca2a770f341e1b9dcfe4be)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-27 23:34 UTC, opbld33 commented
Docs Build status updates of commit _[27f2402](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27f24029ebe9cb3262ca2a770f341e1b9dcfe4be)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272333395781-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W%2FyUk9cygMRXydXyhone%2FrJ%2BuUypEmsZukK0%2B5QMJGo%3D&st=2021-01-27T23%3A29%3A58Z&se=2021-02-27T23%3A34%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 22:41 UTC, opbld32 commented
Docs Build status updates of commit _[f6965b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6965b6b2b506a7e0eeb86d8284e51a585ee3383)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101292239466388-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=koK92Zc9X48Ef2UPD0IOtSxGnQ4EPwTfyyBC5kMPH8s%3D&st=2021-01-29T22%3A36%3A00Z&se=2021-03-01T22%3A41%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 23:00 UTC, opbld31 commented
Docs Build status updates of commit _[80fc8dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80fc8dd558fa98c53b966acd8c20839ccf5c0af7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101292258479827-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DHCzf5QItaf3%2F8iAMXYZEc3XeEXjcBkQFDisv%2BRTCMQ%3D&st=2021-01-29T22%3A55%3A04Z&se=2021-03-01T23%3A00%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-30 01:52 UTC, angelgolfer-ms commented on concepts/use-postman.md
> +1. Navigate to [Postman](https://www.postman.com/) and register and sign into Postman.
Line 21:
I will simplify that to say "Navigate to Postman and sign in."
I think for our audience, they'd know if they don't have an account, they should first register and create an account, before signing in.

2021-01-30 02:03 UTC, angelgolfer-ms commented on concepts/use-postman.md
> +2. Navigate to [Microsoft Graph Postman Collection](https://www.postman.com/microsoftgraph/workspace/microsoft-graph/collection/455214-085f7047-1bec-4570-9ed0-3a7253be148c/fork) in your web browser.
Line 22:
FYI I am going to change this to "Navigate to the Postman collection, Microsoft Graph, ...", and make "Microsoft Graph" the link text.
At first I was expecting to see in the Postman UI some string that says "Microsoft Graph Postman Collection", because of the upper-case 'C' for "collection". There isn't, the UI text is "Microsoft Graph", so the link should be applied to "Microsoft Graph". "collection" in this context should be lower case.
Also, to make it less confusing for Loc, I am using "the Postman collection, Microsoft Graph, ..." rather than "the Microsoft Graph Postman collection", because anytime we have 3 or more nouns put together, the phrase can become ambiguous for Loc.

2021-01-30 02:35 UTC, angelgolfer-ms commented on concepts/use-postman.md
> +2. Navigate to [Microsoft Graph Postman Collection](https://www.postman.com/microsoftgraph/workspace/microsoft-graph/collection/455214-085f7047-1bec-4570-9ed0-3a7253be148c/fork) in your web browser.
FYI Laura will merge in my edits; we happened to be updating this PR at the same time!

2021-01-30 03:08 UTC, opbld32 commented
Docs Build status updates of commit _[3f1aa26](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f1aa26d79bcc91dba8fe1fe4d6fee358617d8c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/use-postman.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/postman-v2update/concepts/use-postman.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/use-postman?branch=pr-en-us-11075) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101300307027165-11075%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O5sLMUVHkNzkjTC181h0L7xk14pQzGOBZYIEZf%2Fdk%2BU%3D&st=2021-01-30T03%3A03%3A14Z&se=2021-03-02T03%3A08%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-30 03:14 UTC, merged