Add hostnames to device get and list API
microsoftgraph/microsoft-graph-docs pull request #11097
Opened 2020-12-21 20:35 UTC by praries880

2020-12-21 20:37 UTC, opbld31 commented
Docs Build status updates of commit _[74fd344](https://github.com/praries880/microsoft-graph-docs-1/commits/74fd344d02c46191c4f846dae89c5e2c34aa6532)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/api/device-list.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012212035211062-11097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XBHp3U0LNL2s67WurzuDCvcY5g4b3eGfSxTrNBt82kQ%3D&st=2020-12-21T20%3A32%3A24Z&se=2021-01-21T20%3A37%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-21 20:47 UTC, opbld33 commented
Docs Build status updates of commit _[01f91ab](https://github.com/praries880/microsoft-graph-docs-1/commits/01f91abd35ccdc365a620926f56bafc3505b3a5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/api/device-list.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012212046196561-11097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2Xr3B7TziyMZBaJvV8KaChnzoO0Cy3H8gGgpyXe%2FElM%3D&st=2020-12-21T20%3A42%3A26Z&se=2021-01-21T20%3A47%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 21:52 UTC, opbld33 commented
Docs Build status updates of commit _[107b6c0](https://github.com/praries880/microsoft-graph-docs-1/commits/107b6c0ac0c2450590a0e1f59221352ec8eff618)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/api/device-list.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042151268791-11097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2bJ%2BHVSzccnlqLIppoWokyGoh5rMaVnE9GWltijWba4%3D&st=2021-01-04T21%3A47%3A40Z&se=2021-02-04T21%3A52%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 21:55 UTC, Lauragra commented on api-reference/beta/resources/device.md
> +|hostNames|String collection| List of hostNames for the device.|
We need an update to the changelog.md and JSON files to mention the new property.

2021-01-04 21:56 UTC, Lauragra requested changes
Please add changelog updates for the API change to add the new hostNames property.

2021-01-04 22:51 UTC, opbld32 commented
Docs Build status updates of commit _[23deae3](https://github.com/praries880/microsoft-graph-docs-1/commits/23deae3e6fb4ad741769a1d3b275a8046c33a3a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/api/device-list.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11097) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042250064181-11097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2X6uguVTQr9uSTGZC8naekloKLZkCHkEVp4WJu%2B40MM%3D&st=2021-01-04T22%3A46%3A22Z&se=2021-02-04T22%3A51%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 22:51 UTC, praries880 commented
> Please add changelog updates for the API change to add the new hostNames property.

Done

2021-01-04 22:51 UTC, praries880 commented on api-reference/beta/resources/device.md
> +|hostNames|String collection| List of hostNames for the device.|
Done

2021-01-04 23:00 UTC, opbld34 commented
Docs Build status updates of commit _[b2a26f0](https://github.com/praries880/microsoft-graph-docs-1/commits/b2a26f00daf8cbfe6c94e65b66a511475449a6cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/api/device-list.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11097) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042259018949-11097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DTWXHmssFoBRucYbWUHA6aIfMajimHpvt96QzrUAK1A%3D&st=2021-01-04T22%3A55%3A16Z&se=2021-02-04T23%3A00%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 23:00 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added property for **hostNames** to the [device](/graph/api/resources/device?view=graph-rest-beta&preserve-view=true) entity. Updated **get** and [device-list](/graph/api/device-l
Please simplify this description to just include the API change - so, "Add the **hostNames** property to the [device] entity." In the operation topics, we just updated the examples so that's a content, not an API change.

2021-01-04 23:07 UTC, praries880 commented on concepts/changelog.md
> +| Addition | beta | Added property for **hostNames** to the [device](/graph/api/resources/device?view=graph-rest-beta&preserve-view=true) entity. Updated **get** and [device-list](/graph/api/device-l
done

2021-01-04 23:08 UTC, opbld31 commented
Docs Build status updates of commit _[4e78bf5](https://github.com/praries880/microsoft-graph-docs-1/commits/4e78bf53e1232feed544209fb57d67bb849407d3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-get.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-get?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/api/device-list.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/api/device-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11097) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/praries880/microsoft-graph-docs-1/blob/2020-12-21-paresin-addHostname_to_devices_get_list_API/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11097) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042306563832-11097%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FCYR26JF7SL4TIOLYgRHk1XljIRI8ADwJxlgXYr2ng8%3D&st=2021-01-04T23%3A03%3A06Z&se=2021-02-04T23%3A08%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 23:29 UTC, Lauragra approved these changes

2021-01-04 23:43 UTC, merged