Publish consent request APIs (preview)
microsoftgraph/microsoft-graph-docs pull request #11109
Opened 2020-12-22 18:00 UTC by FaithOmbongi

2020-12-22 18:01 UTC, opbld32 commented
Docs Build status updates of commit _[ac7bf3d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ac7bf3d50fbf3e539475df1f6876a3c2d7136f4d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-7384c331)
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :warning:Warning | | [Details](#user-content-c6cd1afe-7384c331)
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :bulb:Suggestion | | [Details](#user-content-1948dbfe-7384c331)
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :bulb:Suggestion | | [Details](#user-content-038d3f1d-7384c331)
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :bulb:Suggestion | | [Details](#user-content-b6c48a73-7384c331)
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :bulb:Suggestion | | [Details](#user-content-7e2c48c8-7384c331)
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :bulb:Suggestion | | [Details](#user-content-51f11fc6-7384c331)

<a id="00685cff-7384c331"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml)
 - **Line 10956, Column 15**: **[Error-yaml-syntax-error]** `````While parsing a block collection, did not find expected '-' indicator.`````

<a id="c6cd1afe-7384c331"></a>
### [api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md)
 - **Line 38, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/adminconsentrequestpolicy-update'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Azure AD access reviews (Group memberships)' is duplicated with other articles: 'beta/resources/accessreviewsv2-root.md(10,1), beta/resources/consentrequests-root.md(10,1)'. First level headings must be unique within a docset.`````

<a id="1948dbfe-7384c331"></a>
### [api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List appConsentRequestsForApproval' is duplicated with other articles: 'beta/api/user-get-appconsentrequestsforapproval.md(10,1), beta/api/user-list-appconsentrequestsforapproval.md(10,1)'. First level headings must be unique within a docset.`````

<a id="038d3f1d-7384c331"></a>
### [api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List appConsentRequestsForApproval' is duplicated with other articles: 'beta/api/user-get-appconsentrequestsforapproval.md(10,1), beta/api/user-list-appconsentrequestsforapproval.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b6c48a73-7384c331"></a>
### [api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/approval.md(3,14)', 'beta/resources/approvalstep.md(3,14)', 'beta/resources/request.md(3,14)'.`````

<a id="7e2c48c8-7384c331"></a>
### [api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/approval.md(3,14)', 'beta/resources/approvalstep.md(3,14)', 'beta/resources/request.md(3,14)'.`````

<a id="51f11fc6-7384c331"></a>
### [api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value '**TODO: Add Description**' is duplicated in 'beta/resources/approval.md(3,14)', 'beta/resources/approvalstep.md(3,14)', 'beta/resources/request.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012221800151270-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lK1%2BsPLXb7267B%2FW5yPA0FAh7iBtZW9dHGxsBYW31lc%3D&st=2020-12-22T17%3A56%3A19Z&se=2021-01-22T18%3A01%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=ma [...]

2020-12-22 18:05 UTC, opbld33 commented
Docs Build status updates of commit _[e628464](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e628464dc65d394b63e6bc7e314203043d20ac1e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) | [Details](#user-content-c6cd1afe-d500d03e)
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) | [Details](#user-content-1948dbfe-d500d03e)
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) | [Details](#user-content-038d3f1d-d500d03e)
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) | [Details](#user-content-b6c48a73-d500d03e)
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) | [Details](#user-content-7e2c48c8-d500d03e)
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) | [Details](#user-content-51f11fc6-d500d03e)
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

<a id="c6cd1afe-d500d03e"></a>
### [api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md)
 - **Line 38, Column 2**: **[Warning-file-not-found]** `````Invalid file link: '../api/adminconsentrequestpolicy-update'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Azure AD access reviews (Group memberships)' is duplicated with other articles: 'beta/resources/access [...]

2020-12-22 18:16 UTC, opbld30 commented
Docs Build status updates of commit _[3d2910e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d2910e882d4b6f43b9ec53ea6e9335fdacb014c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012221814412079-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Jeyznk8tDFbaCbjtyq7l2ghEqde8bvaGeDu6wTOJOzU%3D&st=2020-12-22T18%3A10%3A59Z&se=2021-01-22T18%3A15%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All [...]

2020-12-22 18:45 UTC, opbld30 commented
Docs Build status updates of commit _[9fe8e7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9fe8e7afe26ab0067126a2d57a1ec2989cf00e60)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012221844109084-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LRGXdzZFtVb%2BP2THBxR7VojUpco%2FLKymK4tXhI1eICo%3D&st=2020-12-22T18%3A40%3A21Z&se=2021-01-22T18%3A45%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category [...]

2020-12-22 19:16 UTC, opbld33 commented
Docs Build status updates of commit _[b5e8df1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5e8df167078b9ce7e13994ed387c53f43af609e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012221915195959-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jnvMHLae2RR1lWK7P0CJkPobXmqzbiTFi70u673eSCg%3D&st=2020-12-22T19%3A11%3A26Z&se=2021-01-22T19%3A16%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All [...]

2020-12-22 19:26 UTC, opbld30 commented
Docs Build status updates of commit _[fd510df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd510dff92dca3ece11cc6fed34de9f99a438688)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012221925269567-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Uqn%2B%2BDw7lDufFzsFGdFe%2FenUg9bjYQQMrADvtDxue3g%3D&st=2020-12-22T19%3A21%3A38Z&se=2021-01-22T19%3A26%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;catego [...]

2020-12-22 20:08 UTC, opbld33 commented
Docs Build status updates of commit _[70dc8e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70dc8e07b8237614d9bcc6fc602da0dd8ac153bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222007172702-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fF%2BuoCjfGdZjR9Dt92K%2BmzqHbmjac%2BB6%2F%2BlyZ044O5w%3D&st=2020-12-22T20%3A03%3A35Z&se=2021-01-22T20%3A08%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;ca [...]

2020-12-22 20:36 UTC, opbld34 commented
Docs Build status updates of commit _[ba5eff5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba5eff563f9a2993990b87236c2b84fb243aedda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222035235203-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z0%2B%2BPLc%2BoO8huEdm0csj%2FwmD89Wl2hRYDrUTy%2BWjjP4%3D&st=2020-12-22T20%3A31%3A42Z&se=2021-01-22T20%3A36%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;ca [...]

2020-12-22 20:59 UTC, opbld34 commented
Docs Build status updates of commit _[e3ba50b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e3ba50b610f4d771dbb73a12866ce41efc4d169b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222057580693-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RzcisX7IQimcBxg2OWAiSHYQH80%2BqjBvsEcxjKwJJN0%3D&st=2020-12-22T20%3A54%3A57Z&se=2021-01-22T20%3A59%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=A [...]

2020-12-22 21:14 UTC, opbld31 commented
Docs Build status updates of commit _[ad53bb1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad53bb11da4ccc024c757288feaed7711cdbc870)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222113416003-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TqaiMyQxFAIi%2FM4xyKd3vdORJ1FQF9cAAY3DfuvigAA%3D&st=2020-12-22T21%3A09%3A57Z&se=2021-01-22T21%3A14%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=A [...]

2020-12-22 21:45 UTC, opbld33 commented
Docs Build status updates of commit _[965d8bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/965d8bb782d5480fc349639c15f2b254ce3c5c0b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222143206046-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D6xIkwJp1ue1TxUhs1Rnr85FF%2FJ%2B4ai3jaAlM9KFdoY%3D&st=2020-12-22T21%3A40%3A17Z&se=2021-01-22T21%3A45%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category [...]

2020-12-22 22:09 UTC, opbld31 commented
Docs Build status updates of commit _[66cb12c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66cb12c3d38254ed6505ab03f3040d688e41e6f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222207432437-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wsiKMUEdWynQilF9vjMlPumJS9x3VkspbONCnU0XnZc%3D&st=2020-12-22T22%3A04%3A42Z&se=2021-01-22T22%3A09%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All [...]

2020-12-22 22:20 UTC, opbld33 commented
Docs Build status updates of commit _[ebef01c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ebef01c5f5dc36bd0ebca4a7cc51eb2cea077fae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222219128477-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w%2FqT2N%2B23hub3bgzmt6ffhqn7xFIayC8obOea2742y0%3D&st=2020-12-22T22%3A15%3A47Z&se=2021-01-22T22%3A20%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category [...]

2020-12-22 22:32 UTC, opbld34 commented
Docs Build status updates of commit _[a53eacc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a53eacc0eb616d0c8e077b6b4614fd015525f2d6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012222231071806-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nMcCwbcCEuWqn3y030iyHaaTIJlS%2B%2FGbbZZ3TqMuOUc%3D&st=2020-12-22T22%3A27%3A16Z&se=2021-01-22T22%3A32%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links [...]

2020-12-22 22:40 UTC, opbld30 commented
Docs Build status updates of commit _[9946256](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9946256038a05e73094c39c0a50d50fffacfcfab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11109) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11109) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows [...]

2020-12-22 23:16 UTC, opbld30 commented
Docs Build status updates of commit _[b5d70ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5d70ede715ad0dba4867d2f7da90f36dc3a67d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2020-12-24 18:30 UTC, Zawad commented
Thank you @FaithOmbongi

2020-12-29 15:20 UTC, opbld31 commented
Docs Build status updates of commit _[766369d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/766369dccef9b39cae606c1f28e44876200e8a00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2020-12-31 16:23 UTC, opbld33 commented
Docs Build status updates of commit _[14b3d72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14b3d7212134fdefca5ed3c252da6c800f2727c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2021-01-02 23:01 UTC, Zawad commented on api-reference/beta/api/directorysetting-get.md
> +      "name": "EnableGroupSpecificConsent",
@psignoret would we want to expose this as an example?

+ @FaithOmbongi  as FYI

2021-01-02 23:02 UTC, Zawad commented on api-reference/beta/api/directorysetting-list.md
> +          "name": "EnableGroupSpecificConsent",
same concern as before I am not sure if we want to expose this as an example as there could be many other types of directory settings objects.

2021-01-02 23:05 UTC, Zawad commented on api-reference/beta/api/userconsentrequest-list.md
> +
I am not sure if this example is necessary. I think we can take this one out. @FaithOmbongi

2021-01-02 23:11 UTC, Zawad commented on api-reference/beta/api/userconsentrequest-list.md
> +
I like this, but I was curious @FaithOmbongi can we some how reiterate that only registered reviewers can obtain the list of pending appConsentRequests that require their review via the /me/ endpoint?

2021-01-02 23:24 UTC, Zawad commented on api-reference/beta/resources/request.md
> +# request resource type
Shubham can you check if this is what the team would like to document publicly?

2021-01-02 23:29 UTC, Zawad reviewed
@FaithOmbongi  thanks for writing this up! I think it is good. I would like Shubham and Philippe to review as well if they can.

2021-01-04 15:42 UTC, FaithOmbongi commented on api-reference/beta/api/directorysetting-get.md
> +      "name": "EnableGroupSpecificConsent",
@psignoret @zawad The examples in [directory settings API](https://review.docs.microsoft.com/en-us/graph/api/resources/directorysetting?view=graph-rest-beta) will resolve another issue where we're replacing "name-value/value-value" placeholders with "real" values. 

The example using **Consent Policy Settings** was to be a placeholder until we can achieve this desired state with another object ex. **Password Rule Settings**

2021-01-04 15:44 UTC, FaithOmbongi commented on api-reference/beta/api/directorysetting-list.md
> +          "name": "EnableGroupSpecificConsent",
Same response as before. It's just a placeholder until I can replace with a call using "real" values.

2021-01-04 15:57 UTC, FaithOmbongi commented on api-reference/beta/api/userconsentrequest-list.md
> +
Noted, I'm on it.

2021-01-04 19:47 UTC, FaithOmbongi commented on api-reference/beta/api/userconsentrequest-list.md
> +
Noted.

2021-01-04 23:22 UTC, davidmu1 commented on api-reference/beta/api/adminconsentrequestpolicy-get.md
> +The work or school account needs to belong to one of the following roles: *Global administrator*, *Global Reader*, *Cloud App Administrator*, or *Application Administrator*.
To be consistent with other pages, please create a bulleted list rather than a sentence.

2021-01-04 23:22 UTC, davidmu1 commented on api-reference/beta/api/adminconsentrequestpolicy-get.md
> +This method supports the `$select` OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```suggestion
This method supports the `$select` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
```

2021-01-04 23:25 UTC, davidmu1 commented on api-reference/beta/api/adminconsentrequestpolicy-update.md
> +|isEnabled|Boolean|Indicates whether the admin consent policy is enabled or disabled.<br><br>Note: this flag manages the policy, while the **EnableAdminConsentRequests** flag of the **Consent Policy
```suggestion
|isEnabled|Boolean|Indicates whether the admin consent policy is enabled or disabled.<br><br>This property manages the policy, while the **EnableAdminConsentRequests** property of the **Consent Policy Settings** object of the [directory settings](../resources/directorysetting.md) resource determines if users are shown the prompt to request access. The **EnableAdminConsentRequests** property must be set to `true`. See [sample request and response](../api/directorysetting-get.md) of the Consent Policy Settings object.|
```

2021-01-04 23:26 UTC, davidmu1 commented on api-reference/beta/api/appconsentrequest-get.md
> +The work or school account needs to belong to one of the following roles: *Global administrator*, *Global Reader*, *Cloud App Administrator*, or *Application Administrator*.
Please use a list.

2021-01-04 23:27 UTC, davidmu1 commented on api-reference/beta/api/appconsentrequest-list.md
> +The work or school account needs to belong to one of the following roles: *Global administrator*, *Global Reader*, *Cloud App Administrator*, or *Application Administrator*.
Please use a list.

2021-01-04 23:29 UTC, davidmu1 commented on api-reference/beta/api/directorysetting-update.md
> +| values | [settingValue](../resources/settingvalue.md) collection | The updated set of values. <br><br>NOTE: You **must** supply the entire collection set. You cannot update a single set of values.
```suggestion
| values | [settingValue](../resources/settingvalue.md) collection | The updated set of values. <br>You **must** supply the entire collection set. You cannot update a single set of values. |
```

2021-01-04 23:32 UTC, davidmu1 commented on api-reference/beta/api/userconsentrequest-get.md
> +The work or school account needs to belong to one of the following roles: *Global administrator*, *Global Reader*, *Cloud App Administrator*, or *Application Administrator*.
Please use a list.

2021-01-04 23:33 UTC, davidmu1 commented on api-reference/beta/api/userconsentrequest-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
If we say "some", we should list what those are.

2021-01-05 00:08 UTC, davidmu1 commented on api-reference/beta/api/userconsentrequest-list.md
> +The work or school account needs to belong to one of the following roles: *Global administrator*, *Global Reader*, *Cloud App Administrator*, or *Application Administrator*.
Please use a list.

2021-01-05 00:09 UTC, davidmu1 commented on api-reference/beta/api/userconsentrequest-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
List the ones that are supported or change the word "some".

2021-01-05 00:12 UTC, davidmu1 commented on api-reference/beta/resources/appconsentrequest.md
> +|appDisplayName|String|The app display name of the app consent request.<br><br>Supports `$filter` (`eq` only) and `$sort`.|
```suggestion
|appDisplayName|String|The app display name of the app consent request. <br>Supports `$filter` (`eq` only) and `$sort`.|
```

2021-01-05 00:13 UTC, davidmu1 commented on api-reference/beta/resources/appconsentrequestscope.md
> +description: "Details of the dynamic permission scopes for which access is being requested"
```suggestion
description: "Details of the dynamic permission scopes for which access is being requested."
```

2021-01-05 00:16 UTC, davidmu1 commented on api-reference/beta/resources/consentrequests-root.md
> +  1. [adminConsentRequestPolicy](../resources/adminconsentrequestpolicy.md): Specifies the policy by which app consent requests can be created and managed for the entire tenant. There is a single adm
This should be a bulleted list.

2021-01-05 00:17 UTC, davidmu1 commented on api-reference/beta/resources/consentrequests-root.md
> +  4. [appConsentRequestScope](../resources/appconsentrequestscope.md): A complex type that contains details of the dynamic permission scopes being requested for a given application.
```suggestion
  4. [appConsentRequestScope](../resources/appconsentrequestscope.md): A resource that contains details of the dynamic permission scopes being requested for a given application.  
```

2021-01-05 00:18 UTC, davidmu1 commented on api-reference/beta/resources/request.md
> +Represents a base request model. ELM, PIM and Admin Consent Requests are derived models for this request. Request also contains a link to the navigation properties associated with approvals.
Acronyms should be spelled out on first use.

2021-01-05 00:20 UTC, davidmu1 commented on concepts/changelog.md
Don't forget the JSON version of the changelog. https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-01-05 00:21 UTC, davidmu1 commented on concepts/whats-new-overview.md
> +- As part of Azure Active Directory [entitlement management](/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&preserve-view=true), when users wishing to access groups, application
```suggestion
- As part of Azure Active Directory [entitlement management](/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&preserve-view=true), when users wishing to access groups, applications, or SharePoint Online sites request an assignment to an [access package](/graph/api/resources/accesspackage?view=graph-rest-beta&preserve-view=true), they can respond to [questions](/graph/api/resources/accesspackagequestion?view=graph-rest-beta&preserve-view=true) represented in [localized content](/graph/api/resources/accesspackagelocalizedcontent?view=graph-rest-beta&preserve-view=true) in the [access package assignment request](/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&preserve-view=true).
```

2021-01-05 15:57 UTC, opbld32 commented
Docs Build status updates of commit _[adf8c6f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/adf8c6f9d94c5197562f2e4f7931b7ba661b12c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5f1de2e5)

<a id="5f1de2e5"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051557265601-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jztNf4A4qXIZAjGBZug3gqFVZvhCmcDceudJj5JBfpY%3D&st=2021-01-05T15%3A52%3A51Z&se=2021-02-05T15%3A57%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 15:59 UTC, opbld34 commented
Docs Build status updates of commit _[34d52e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34d52e7b9b5102a60d15de19899513435802a97e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-da344465)

<a id="da344465"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051558026632-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EjOfgUNlctkK9Y4muiO4JyXxeqJFfZWgHk4xJiDdrEk%3D&st=2021-01-05T15%3A54%3A10Z&se=2021-02-05T15%3A59%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 16:00 UTC, opbld33 commented
Docs Build status updates of commit _[2eaa407](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2eaa4078630539bc664db339cc51f2accf46b334)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8d81990f)

<a id="8d81990f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051559012542-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FagVMyxxZFo1Ur8PpDf12m1v0lWT1LTuTjFiCI72a5A%3D&st=2021-01-05T15%3A55%3A17Z&se=2021-02-05T16%3A00%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 16:00 UTC, opbld30 commented
Docs Build status updates of commit _[37bacf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37bacf114a62e2390624f7618cd193753bf6a110)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1525814d)

<a id="1525814d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051559523677-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nvj9VRjIizT9ev%2FRBL24UqLN6SrI%2FzeaOXFRgWpH2A8%3D&st=2021-01-05T15%3A55%3A47Z&se=2021-02-05T16%3A00%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 17:02 UTC, FaithOmbongi commented on api-reference/beta/api/userconsentrequest-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
@Zawad Please clarify supported query params?

2021-01-05 17:02 UTC, FaithOmbongi commented on api-reference/beta/api/userconsentrequest-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
@Zawad Please clarify the supported query params?

2021-01-05 17:05 UTC, opbld31 commented
Docs Build status updates of commit _[5fa25c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5fa25c59510000ae70c27206832c89c105ac1619)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f7e07cd9)

<a id="f7e07cd9"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051704510984-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ewz62ACE4cU9nLSaNCxISuYz3XEu8tip6oBjge0VHqY%3D&st=2021-01-05T17%3A00%3A12Z&se=2021-02-05T17%3A05%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 17:06 UTC, opbld34 commented
Docs Build status updates of commit _[4e0a017](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e0a0172d1dd1681ae02666fdf54161af82c5a24)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-69370f5a)

<a id="69370f5a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051706344919-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gU%2FpO6cwEli4%2BEYwwkcbp%2FcrC0bQQycl3TFRxLc19d8%3D&st=2021-01-05T17%3A01%3A52Z&se=2021-02-05T17%3A06%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 17:13 UTC, opbld30 commented
Docs Build status updates of commit _[c2b9773](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2b9773aad3c913e36ff211e816b1b0bc0bc63a7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-56a42801)

<a id="56a42801"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101051712442872-11109%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u5LxkWdcnVDzPOqd4Y2xiK%2BRs5r7aPmADUVq7ulAKls%3D&st=2021-01-05T17%3A08%3A06Z&se=2021-02-05T17%3A13%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 17:19 UTC, opbld34 commented
Docs Build status updates of commit _[9792113](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9792113e885823a5162245a76cd1fc92dc12291d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2021-01-05 17:41 UTC, opbld34 commented
Docs Build status updates of commit _[ecfcfaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecfcfaf182026d52606e2669c900e59e4294347a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2021-01-06 17:14 UTC, Zawad commented on api-reference/beta/api/userconsentrequest-list.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
@FaithOmbongi  I believe we included this information in the draft docs for all of the methods. here is what I have from the draft:

This method supports the $skip, and $top OData query parameters to help customize the response. For general information, see OData query parameters.

2021-01-06 17:15 UTC, Zawad commented on api-reference/beta/api/userconsentrequest-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
@FaithOmbongi Here is what I have from the draft docs: 

"This method supports the $skip, and $top OData query parameters to help customize the response. For general information, see OData query parameters."

2021-01-06 17:16 UTC, Zawad commented on api-reference/beta/api/userconsentrequest-list.md
> +
Awesome thank you!

2021-01-07 15:00 UTC, opbld31 commented
Docs Build status updates of commit _[af2efdc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/af2efdceb2ed4743aad4d8e90ac5bd96c779160e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2021-01-07 15:21 UTC, opbld34 commented
Docs Build status updates of commit _[237edce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/237edce54a407fabad6e8f8da5e6127cbc1e4791)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.do [...]

2021-01-14 23:01 UTC, opbld31 commented
Docs Build status updates of commit _[d199ea5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d199ea5d4b91d41b93b1f5e94a4f24d29e2f74de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.micros [...]

2021-01-14 23:06 UTC, opbld31 commented
Docs Build status updates of commit _[621ba0d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/621ba0d4e7787b633732dbffdbf996f8e95767f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/directorysetting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/directorysetting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directorysetting-update?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-get-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-get-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-get-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/user-list-appconsentrequestsforapproval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/user-list-appconsentrequestsforapproval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-appconsentrequestsforapproval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/approvalstep.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/approvalstep.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstep?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/request.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/request.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/request?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-beta&branch=pr-en-us-11109) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2020-12-17-consentRequestAPI/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.micros [...]

2021-01-15 19:21 UTC, shubhamguptacal requested changes

2021-01-15 19:21 UTC, shubhamguptacal commented on api-reference/beta/api/adminconsentrequestpolicy-update.md
> +|isEnabled|Boolean|Indicates whether the admin consent policy is enabled or disabled.<br><br>This property manages the policy, while the **EnableAdminConsentRequests** property of the **Consent Polic
It's not going to be necessary moving forward to set consent policy settings. Can you remove this snippet?

2021-01-15 19:21 UTC, shubhamguptacal commented on api-reference/beta/api/directorysetting-get.md
> +      "name": "EnableGroupSpecificConsent",
One of the things we're working on is to internally get/update directory settings when someone calls consentRequestPolicy API. This would mean that customers don't have to interact with directory settings API in the foreseeable future. Given that, it may not be necessary to document these APIs. Thoughts @psignoret ?

2021-01-15 19:21 UTC, shubhamguptacal commented on api-reference/beta/resources/approval.md
> +|completedSteps|[approvalStep](../resources/approvalstep.md) collection|A collection of decisions from the past steps. Read-only. |
We're in the process of pushing out some breaking changes around this model - converging completedSteps and pendingSteps into a single property called steps. I had discussed with Zawad and David Murray previously and we decided that we'd hold off on pushing this documentation until those breaking changes are in. Is it okay to hold off on this documentation until end of month(that's when we expect breaking changes to be deployed)

2021-01-15 19:21 UTC, shubhamguptacal commented on api-reference/beta/resources/request.md
> +# request resource type
This does not need to be documented publicly. It's just an internal model.

2021-01-18 12:07 UTC, FaithOmbongi commented on api-reference/beta/api/adminconsentrequestpolicy-update.md
> +|isEnabled|Boolean|Indicates whether the admin consent policy is enabled or disabled.<br><br>This property manages the policy, while the **EnableAdminConsentRequests** property of the **Consent Polic
Noted.

2021-01-18 12:38 UTC, FaithOmbongi commented on api-reference/beta/resources/approval.md
> +|completedSteps|[approvalStep](../resources/approvalstep.md) collection|A collection of decisions from the past steps. Read-only. |
Holding off the entire doc set for this API is OK. Because examples in API references like **userconsentrequest-get.md** and **userconsentrequest-list.md** reference `completedSteps` & `pendingSteps`, once you implement these breaking changes, we can rerun & replace the code blocks with current examples.

Unless you meant for this resource file only?

2021-02-06 03:08 UTC, merged