Update search-concept-aggregation.md
microsoftgraph/microsoft-graph-docs pull request #11123
Opened 2020-12-24 02:44 UTC by ZChristine

Enrich aggregation filter format for the scenario that multiple values for the same filter are required

2020-12-24 02:45 UTC, opbld30 commented
Docs Build status updates of commit _[a7bc789](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7bc78982a23861eff93a97bd26999a77f918a6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-11123) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012240244489021-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uW0rW3ikQNbRAaW6MQzJ6sc8MK67r18ORJTxO9VSHB4%3D&st=2020-12-24T02%3A40%3A57Z&se=2021-01-24T02%3A45%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-29 05:34 UTC, opbld33 commented
Docs Build status updates of commit _[9cb0527](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9cb052742b55b52ee58279ac9eb48929a33db3ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-11123) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012290532239110-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6btZk7hergk7jjcr2uMgSysIvj9DRISwtJnlOc6ZOAM%3D&st=2020-12-29T05%3A29%3A08Z&se=2021-01-29T05%3A34%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-29 17:44 UTC, opbld33 commented
Docs Build status updates of commit _[4709f89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4709f8996b76df547506d2ea73a9df8a36ee70bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-11123) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012291743045308-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hn1mMUGnD38K1TEJkixd%2B56tE0VRPny5q80vPECly2Y%3D&st=2020-12-29T17%3A39%3A14Z&se=2021-01-29T17%3A44%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-30 02:05 UTC, opbld32 commented
Docs Build status updates of commit _[865fa15](https://github.com/microsoftgraph/microsoft-graph-docs/commits/865fa15377424bc3bd4e9aadfdc21a129392f42a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-11123) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202012300204433228-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KlV2%2BUY%2FzeLbf0FhBfphO0tzTfBrxWhjPRgcLDO9X6E%3D&st=2020-12-30T02%3A00%3A49Z&se=2021-01-30T02%3A05%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-04 22:47 UTC, Lauragra commented on api-reference/beta/resources/search-api-overview.md
> +|[Search Graph connectors](/graph/search-concept-custom-types)| **contentSources** |
This title doesn't match the title of the link target. We also appear to have the same link in this topic with slightly different link titles. If we want to keep both links, please change the link text to "Search custom types imported using connectors".

2021-01-04 22:48 UTC, Lauragra commented on api-reference/beta/resources/searchrequest.md
> +- Search [Graph Connectors)](/graph/search-concept-custom-types) data
Same comment here - the link title should be "Search custom types imported using connectors".

2021-01-04 22:55 UTC, Lauragra requested changes
Please update the link text per my comments.

2021-01-13 19:57 UTC, opbld33 commented
Docs Build status updates of commit _[88c0ecf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88c0ecf37205b66e9dd3cc9e8826d524dec248ab)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-57cbffd9)

<a id="57cbffd9"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101131957097761-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qRy%2BFZc%2FG74ak%2FcNcCYfT2xtFoVXbwFKcwH0sCjckhY%3D&st=2021-01-13T19%3A52%3A33Z&se=2021-02-13T19%3A57%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 19:58 UTC, opbld33 commented
Docs Build status updates of commit _[09e627c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09e627c24be2736a9952f55dff952a32dd197aa5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b600c10c)

<a id="b600c10c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101131958229496-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P7a%2BKLyAMm%2FPHXcVLPETV9Ce9iRDgC0fW8mbaiFC%2F7A%3D&st=2021-01-13T19%3A53%3A40Z&se=2021-02-13T19%3A58%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 01:53 UTC, nmoreau commented on api-reference/beta/resources/search-api-overview.md
> +|[Search Graph connectors](/graph/search-concept-custom-types)| **contentSources** |
Fixed

2021-01-14 05:24 UTC, opbld33 commented
Docs Build status updates of commit _[b0cf384](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b0cf384e5a7ffb56578f00d95d19f0b7697d63c8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-11123) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140523429863-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8tr6eQtpHidJ1ddzQSUbsnXDkp%2Bym1RipPgKarJVYcM%3D&st=2021-01-14T05%3A19%3A57Z&se=2021-02-14T05%3A24%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 22:09 UTC, opbld34 commented
Docs Build status updates of commit _[c435ac5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c435ac5e34976f02e08ea03e76ec5c53e4a610bb)_: 

:clock10: **Pending**: waiting for processors ([36](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 36 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-15 22:10 UTC, opbld34 commented
Docs Build status updates of commit _[c435ac5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c435ac5e34976f02e08ea03e76ec5c53e4a610bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/search-api-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/search-api-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/search-api-overview?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[api-reference/beta/resources/searchrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/api-reference/beta/resources/searchrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/searchrequest?view=graph-rest-beta&branch=pr-en-us-11123) (graph-rest-beta) |
[concepts/search-concept-aggregation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/ZChristine-patch-3/concepts/search-concept-aggregation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-aggregation?branch=pr-en-us-11123) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101152209052028-11123%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F5qXbfGMwqqMr0rxsJ2JiAfc8XZ%2BO9XFgVQxmCFNbxA%3D&st=2021-01-15T22%3A05%3A52Z&se=2021-02-15T22%3A10%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-16 00:46 UTC, Lauragra approved these changes

2021-01-16 00:46 UTC, merged