Adding userRegistrationFeatureSummary.md file to graph docs reference…
microsoftgraph/microsoft-graph-docs pull request #11174
Opened 2021-01-04 23:48 UTC by danielwood95

…s and will fill in the TODO section later

2021-01-04 23:49 UTC, opbld33 commented
Docs Build status updates of commit _[79f8f5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79f8f5bc72b9b736d0ccbb450fb81f633ba472c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-8ae6410b-a3b0588f)

<a id="8ae6410b-a3b0588f"></a>
### [api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: '**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': '**TODO: Add MS prod. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**'.`````
 - **Line 20, Column 32**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/userregistrationfeaturecount.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101042348059440-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0z72L905FWEnKwLwoT9US0R5cypPnfL0jPLQNyWdCcY%3D&st=2021-01-04T23%3A44%3A19Z&se=2021-02-04T23%3A49%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-07 23:31 UTC, opbld32 commented
Docs Build status updates of commit _[eda2eac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eda2eac87555cc1eb2efbeb0eba1fd1e91243fc2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f1eafc38)

<a id="f1eafc38"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101072331303106-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rYX8f7ih2Z4uknYNHpPXjRwFR%2BxmY6XKNpygBkkJ8gc%3D&st=2021-01-07T23%3A26%3A48Z&se=2021-02-07T23%3A31%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 19:32 UTC, opbld30 commented
Docs Build status updates of commit _[45f1659](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45f165914f278593e5753334252489655db1651a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f1fd5647)

<a id="f1fd5647"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101081931555410-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VS5fHT2M4mdndWyLHT3apJAevn7B0434bO5HjapYnFo%3D&st=2021-01-08T19%3A27%3A13Z&se=2021-02-08T19%3A32%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 19:47 UTC, opbld33 commented
Docs Build status updates of commit _[50468a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50468a504ac17b37590c907a4dfec7e2dd904550)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ef72e01a)

<a id="ef72e01a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101081946512669-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=waz4UHUF5xZ9dZV0m8JZjkaRj9zrNux5K1SpXUU%2BzYg%3D&st=2021-01-08T19%3A42%3A11Z&se=2021-02-08T19%3A47%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 20:25 UTC, davidmu1 commented on api-reference/beta/resources/userregistrationfeaturesummary.md
> +|totalUserCount|Int64|Total number of users accounts, excluding those that are blocked|
Don't forget periods at the ends of sentences

2021-01-08 20:25 UTC, davidmu1 commented on api-reference/beta/resources/userregistrationfeaturesummary.md
> +|userRegistrationFeatureCounts|[userRegistrationFeatureCount](../resources/userregistrationfeaturecount.md) collection|**TODO: Add Description**|
Description needs to be filled in.

2021-01-08 20:27 UTC, davidmu1 commented on api-reference/beta/resources/userregistrationfeaturesummary.md
> +|userRoles|includedUserRoles|Filter for user role type. Possible values are: `all`, `privilegedAdmin` (e.g. Global admin, Security admin, Conditional Access admin, Exchange admin, SharePoint admin, H
The parenthesis makes this harder to scan. I suggest separating the descriptions into a new paragraph.

2021-01-08 20:29 UTC, davidmu1 commented on concepts/changelog.md
Was this change in this PR? Seems like a possible out of sync branch.

2021-01-08 20:31 UTC, davidmu1 commented on concepts/changelog.md
> +|Addition|beta|Added the [userRegistrationFeatureSummary](https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureSummary?view=graph-rest-beta) resource type|
This seems to be the only change in this PR. Where is this complex type used?

2021-01-11 20:22 UTC, opbld34 commented
Docs Build status updates of commit _[7dbdd72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7dbdd722ddf67182663d3353b8c8c440021cd14c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e605c013)

<a id="e605c013"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101112022214097-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QrN%2BWyJAzpTnRZDf5nm1XgNlHIveaPIUOK9Oh689yL0%3D&st=2021-01-11T20%3A17%3A39Z&se=2021-02-11T20%3A22%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 22:08 UTC, opbld34 commented
Docs Build status updates of commit _[ead000b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ead000bef57adf14b4e9b03d7cb0440f83721423)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ba17426a)

<a id="ba17426a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101112208029245-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ugb7Qu8o%2BE2iZXIXJrhmIoTD3ZN8EDwWC%2Fvt31pflj4%3D&st=2021-01-11T22%3A03%3A28Z&se=2021-02-11T22%3A08%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 22:16 UTC, opbld34 commented
Docs Build status updates of commit _[0a693bc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a693bc79c6bfdc513b9f4549e5605e64042a2b4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-40d64706)

<a id="40d64706"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101112215532828-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pru3HjW%2Fveen3k6PRJYnr%2B221Mb0oKsnntnxQkPYJEU%3D&st=2021-01-11T22%3A11%3A16Z&se=2021-02-11T22%3A16%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 22:24 UTC, opbld30 commented
Docs Build status updates of commit _[7f324c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f324c6ce578df603a1644e7116c5394f99f5a8f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2345355d)

<a id="2345355d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101112224321095-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PoLetDx05DBu4Swi2FHm417BtiVvGPi6hfFtZLDLe2k%3D&st=2021-01-11T22%3A19%3A48Z&se=2021-02-11T22%3A24%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 22:39 UTC, opbld32 commented
Docs Build status updates of commit _[c032e93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c032e936ebef7ddb079f1698ec59f916b9017144)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-13db35ae)

<a id="13db35ae"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101112238488299-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=R%2FVpxKvORDasKcuvOjxfqy4BH3gEQGEwu1YOrsq460E%3D&st=2021-01-11T22%3A34%3A06Z&se=2021-02-11T22%3A39%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 22:50 UTC, opbld33 commented
Docs Build status updates of commit _[d9db11e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9db11eb1ee4776725bd0ac10cfecbb0449431bc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8278446d)

<a id="8278446d"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101112249416298-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gzXu%2F8IxNshgVgvsAFtRmg48jH2EVFUw%2BDP09wx4QPc%3D&st=2021-01-11T22%3A44%3A59Z&se=2021-02-11T22%3A49%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 22:56 UTC, opbld31 commented
Docs Build status updates of commit _[77b34ca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77b34ca53bfe8a574c9b6c7c7b72d02bf888a8a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-5d614301)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-9bf7e341-5d614301)
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-143a23c2-5d614301)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5d614301"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 38, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 43, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authenticationMethodsRoot-usersRegisteredByFeature?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 48, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authenticationMethodsRoot-usersRegisteredByMethod?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 48, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' [...]

2021-01-11 23:55 UTC, opbld30 commented
Docs Build status updates of commit _[7e30e62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e30e62a3905c2fb129fcc2e2b93f768de5029ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-1beb5f86)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-9bf7e341-1beb5f86)
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-19c0126e-1beb5f86)
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-143a23c2-1beb5f86)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-1beb5f86"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 38, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 43, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authenticationMethodsRoot-usersRegisteredByFeature?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 48, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** [...]

2021-01-12 00:04 UTC, opbld30 commented
Docs Build status updates of commit _[62dfbfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62dfbfc93c370cb16a96bd6cccfd9b5f1be1cbec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-e1581043)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-9bf7e341-e1581043)
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-19c0126e-e1581043)
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-143a23c2-e1581043)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-e1581043"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 38, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 43, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authenticationMethodsRoot-usersRegisteredByFeature?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 48, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** [...]

2021-01-12 00:13 UTC, opbld30 commented
Docs Build status updates of commit _[08f8278](https://github.com/microsoftgraph/microsoft-graph-docs/commits/08f827834b1766b712fadd7b752a050d0cec7589)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-5f417ed9)
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) | [Details](#user-content-19c0126e-5f417ed9)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5f417ed9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 38, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 39, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 40, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 41, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodSummary?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 42, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodCount?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 43, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authenticationMethodsRoot-usersRegisteredByFeature?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 47, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 48, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authentic [...]

2021-01-12 00:19 UTC, opbld33 commented
Docs Build status updates of commit _[e134293](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e13429390e3954a8f8abc43341083ea3f4157f34)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-934d26da)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-934d26da"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 38, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120018247452-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UtJ1gRENSLoMghJefzsFRhnErrvl%2BoEjNRKhfNLMdlM%3D&st=2021-01-12T00%3A14%3A36Z&se=2021-02-12T00%3A19%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 00:33 UTC, opbld34 commented
Docs Build status updates of commit _[1cdfd08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cdfd08f7678089fe78a00794b7b297be31ef533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-5dc4bb3d)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-5dc4bb3d"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120032315894-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B2T4oTSzUuihLnU9tN2BUFj3Ackh235Xcepe%2BqEtcqc%3D&st=2021-01-12T00%3A28%3A42Z&se=2021-02-12T00%3A33%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 00:52 UTC, opbld33 commented
Docs Build status updates of commit _[a8b84c7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8b84c7fc7307158249cf36dd1da13e6a2e87aa8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-ec9332ce)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-ec9332ce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120051228080-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bP6X51DF1%2FDtEGcTj6jVgPaCZm%2B%2B4SIo7m4zggeQUwk%3D&st=2021-01-12T00%3A47%3A35Z&se=2021-02-12T00%3A52%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 01:36 UTC, opbld31 commented
Docs Build status updates of commit _[38ffc76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/38ffc766d27df5249731623fe7110dc671d62c6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-a8da0efa)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-a8da0efa"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120134504668-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z6EfxN1t2zCN62DsdB4tXCyV5Qdd0CLTxwQokb%2FOfvE%3D&st=2021-01-12T01%3A30%3A59Z&se=2021-02-12T01%3A35%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 01:43 UTC, opbld30 commented
Docs Build status updates of commit _[481b2a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/481b2a578078f2f593e08b613f558e3e1f02e645)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-eca82cf0)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-eca82cf0"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120142245667-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0f63456vf3sZY32gDRGnt25vwXOMFxYli2VHrEeWGNc%3D&st=2021-01-12T01%3A38%3A38Z&se=2021-02-12T01%3A43%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 01:52 UTC, opbld31 commented
Docs Build status updates of commit _[c2c8b44](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2c8b44e35145726e96b405110b857b8abdf6668)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-6d309b32)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6d309b32"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120151065884-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P7t%2FrWEa5RBcJAn7uqZ4h1ZvWL0N9sL7%2BM39%2FJfRe0M%3D&st=2021-01-12T01%3A47%3A14Z&se=2021-02-12T01%3A52%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 02:03 UTC, opbld30 commented
Docs Build status updates of commit _[4cbecc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4cbecc6b22e39c44560394f4a623d0ffcf3d895e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-3decd02b)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-3decd02b"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120201255839-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sYlqmUDgI5VOifdCk8CsunxbEHkZhFg6FaaOK4iqJkY%3D&st=2021-01-12T01%3A58%3A15Z&se=2021-02-12T02%3A03%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 02:16 UTC, opbld34 commented
Docs Build status updates of commit _[7e400a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e400a53b77c41e3313cb8b775aeb81c6d9495a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-bd1800db)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-bd1800db"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101120215034930-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z%2BWW4UMJjjiW3h56qMT03IX4JkHCbaJDleaW9209PpY%3D&st=2021-01-12T02%3A11%3A16Z&se=2021-02-12T02%3A16%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 18:27 UTC, opbld34 commented
Docs Build status updates of commit _[1606b06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1606b066b504352d721b349d51241a1b02817c42)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b07eb3bd)

<a id="b07eb3bd"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121827020023-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=27S1ZefrnN8HuYWzHygdTG3zdPgJrpXpsfRJRwbJxeM%3D&st=2021-01-12T18%3A22%3A32Z&se=2021-02-12T18%3A27%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 18:42 UTC, opbld31 commented
Docs Build status updates of commit _[d56da2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d56da2ef5c565b47e67df505f46060310471e096)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-898f7391)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-898f7391"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121841315690-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=B8ESfsv4o4%2BiVSXxbW0q1AhJVG2TABimpGarxwIM02E%3D&st=2021-01-12T18%3A37%3A53Z&se=2021-02-12T18%3A42%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 18:57 UTC, opbld33 commented
Docs Build status updates of commit _[849aa1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/849aa1eada75b7a0051c8ee13877e7a9208b3355)_: 

:clock10: **Pending**: waiting for processors ([23](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 23 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-12 18:58 UTC, opbld30 commented
Docs Build status updates of commit _[849aa1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/849aa1eada75b7a0051c8ee13877e7a9208b3355)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121857018359-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A%2FgPldheEfqySMLPSPUBXRup2Ao6ljhqXA0MLGnRUf8%3D&st=2021-01-12T18%3A53%3A18Z&se=2021-02-12T18%3A58%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 19:06 UTC, opbld33 commented
Docs Build status updates of commit _[f3cd02c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3cd02c28a0dfb31a6b13db8b25081d92e46beac)_: 

:clock10: **Pending**: waiting for processors ([35](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 35 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-12 19:07 UTC, opbld32 commented
Docs Build status updates of commit _[f3cd02c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3cd02c28a0dfb31a6b13db8b25081d92e46beac)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121905507662-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RDQ%2FmTZ2WXRjoLO8Qbgu2MoLFNrUR5AkLLC7BRJGBIk%3D&st=2021-01-12T19%3A02%3A56Z&se=2021-02-12T19%3A07%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 19:12 UTC, opbld32 commented
Docs Build status updates of commit _[f84b0c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f84b0c04ee019c7001d7deccab55462c2df7e2c5)_: 

:clock10: **Pending**: waiting for processors ([33](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 33 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-12 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[f84b0c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f84b0c04ee019c7001d7deccab55462c2df7e2c5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121912165660-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cUNXdChJdI5NclL4AuXGX%2BVLmtz7amDnFlwZx6evNjA%3D&st=2021-01-12T19%3A08%3A53Z&se=2021-02-12T19%3A13%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 07:32 UTC, opbld31 commented
Docs Build status updates of commit _[a4f2530](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a4f2530f21225c5359d03d61233c507301d41a0a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140730476834-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=i75Q7g%2FrXj7emViyeela77JspY4sodtEpJk7lFPLt80%3D&st=2021-01-14T07%3A27%3A04Z&se=2021-02-14T07%3A32%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 08:24 UTC, opbld34 commented
Docs Build status updates of commit _[c62b093](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c62b093e1b0cbb248eeb2e4b88be7d37888a7f9c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140823058103-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TXdZUk%2By8Cpw7E5fhx09C%2BrcSRhkYBzDLLGd%2BvaYV04%3D&st=2021-01-14T08%3A19%3A19Z&se=2021-02-14T08%3A24%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 17:42 UTC, opbld30 commented
Docs Build status updates of commit _[f235691](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2356912a8afe5052f385ef962bea983c4a2b72d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6dbbd4dd)

<a id="6dbbd4dd"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101141741427339-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FTsKqTuVN2RjqMhVIhu%2BHrhZqSnfFaSegY5cClgHW%2B0%3D&st=2021-01-14T17%3A37%3A01Z&se=2021-02-14T17%3A42%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 18:02 UTC, opbld30 commented
Docs Build status updates of commit _[ab7916c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab7916c1515c9533ea34695f204454713455a64b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5348c34a)

<a id="5348c34a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101141802130242-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F3g4PtVS6wMMxNSPCdp%2FX5gs5q1Yd7q9qjz1FYFjDpc%3D&st=2021-01-14T17%3A57%3A39Z&se=2021-02-14T18%3A02%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 18:35 UTC, opbld31 commented
Docs Build status updates of commit _[8854b83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8854b83ef3623e6ace4c546b69384ea523e0947b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-846ca674)

<a id="846ca674"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101141834519371-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fHwa6JuiQT5YpXfT78RZNW7WQPQ%2FW2y1mM9Mf%2BRszGQ%3D&st=2021-01-14T18%3A30%3A15Z&se=2021-02-14T18%3A35%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 18:40 UTC, opbld34 commented
Docs Build status updates of commit _[804157a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/804157a411b130fa1833420fa32bf269dfb93f17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4bb19b06)

<a id="4bb19b06"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101141840160688-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sDj4BZox2BKlGNt4wFj5xgxISTBbk7Fg7FXq4iARMOg%3D&st=2021-01-14T18%3A35%3A36Z&se=2021-02-14T18%3A40%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 20:42 UTC, opbld34 commented
Docs Build status updates of commit _[c646827](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c64682788d803bcd6e07056729b33787fb0bdadd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-42ec3b50)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-42ec3b50"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureSummary?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationFeatureCount?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodSummary?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 24, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/userRegistrationMethodCount?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 25, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 29, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/authenticationMethodsRoot-usersRegisteredByFeature?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 29, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/authenticationMethodsRoot?view=graph-rest-beta&preserve-view=true' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 30, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/con [...]

2021-01-14 20:47 UTC, opbld32 commented
Docs Build status updates of commit _[fa5bc8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa5bc8c6dbe0dd0f1464bd468d0483b83fe03b54)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) | [Details](#user-content-de0bbbbb-6ebb16f4)
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-6ebb16f4"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md)
 - **Line 66, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 66, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101142045374020-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1ZZfZYXtiswHgw9PoU6ONo0JFHES1hAceB%2Ff3Unhyp4%3D&st=2021-01-14T20%3A42%3A07Z&se=2021-02-14T20%3A47%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:54 UTC, opbld33 commented
Docs Build status updates of commit _[9132dfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9132dfcfeaa715b9f00b91861523cac69181d7a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272353025353-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nYGx4IKS8iAeAQ8CoPxp4p1r8BrZEwN18ONFMG2v4bY%3D&st=2021-01-27T23%3A49%3A42Z&se=2021-02-27T23%3A54%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 00:04 UTC, opbld32 commented
Docs Build status updates of commit _[3b6c027](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b6c027b62ff5eea8a0b727876ce56ea274f68eb)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-28 00:06 UTC, opbld34 commented
Docs Build status updates of commit _[3b6c027](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b6c027b62ff5eea8a0b727876ce56ea274f68eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101280004271495-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1sjcIWdkK8aoJx4Gzn5dNE%2FXQPtZxprFyYhFRVFt5WI%3D&st=2021-01-28T00%3A01%3A15Z&se=2021-02-28T00%3A06%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 03:06 UTC, Lauragra commented on api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
> +
Global: Please add the includes file for the beta disclaimer to all topics.

2021-01-28 03:07 UTC, Lauragra commented on api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
> +Get the number of users capable of Multi-Factor Authentication, Self-Service Password Reset, and Passwordless authentication.
Global: These types of authentication are not proper nouns; please lowercase.

2021-01-28 03:08 UTC, Lauragra commented on api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
> +The following table shows the parameters that can be used with this function.
Please remove one of these two sentences as they appear to say basically the same thing.

2021-01-28 03:09 UTC, Lauragra commented on api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md
> +The following table shows the parameters that can be used with this function.
Same comment here - remove one sentence.

2021-01-28 03:13 UTC, Lauragra commented on api-reference/beta/resources/userregistrationfeaturecount.md
> +Number of users registered or capable for Multi-Factor Authentication, Self-Service Password Reset and Passwordless Authentication.
Global: For these complex types, please start with a verb, i.e. Represents the....

2021-01-28 03:14 UTC, Lauragra commented on concepts/changelog.md
> +### Reports | Authentication Methods
You can discard changes to the changelog.md file; we're no longer using this in favor of the JSON/filterable changelog experience.

2021-01-28 03:15 UTC, Lauragra commented on changelog/Microsoft.AAD.Reporting.json
> +         "WorkloadArea":"Reports and audit",
The name for the WorkLoadArea is Reports.

2021-01-28 03:16 UTC, Lauragra commented on changelog/Microsoft.AAD.Reporting.json
> +               "Description":"Added the **authenticationMethods** relationship to [reportRoot](https://docs.microsoft.com/en-us/graph/api/resources/reportRoot?view=graph-rest-beta) resource",
Please add periods at the end of each sentence.

2021-01-28 03:18 UTC, Lauragra commented on changelog/Microsoft.AAD.Reporting.json
> -  "changelog": [
Why does it appear that the whole file is getting deleted and re-added? Ideally you would just add a new changelist item to the file and not change any other existing entries. It will be hard to verify that nothing is lost due to this volume of changes in the file. Can you please revert the changes and only make an addition to the file?

2021-01-28 03:18 UTC, Lauragra requested changes
Please see content review feedback.

2021-01-28 20:47 UTC, opbld34 commented
Docs Build status updates of commit _[50120e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50120e236f2f59c4ef410875d6f9bf629ad860bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282045062493-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tFms1dBZWs9BzQA1k35Pz%2BlJCmjTP2NbnB%2ByoaqztvE%3D&st=2021-01-28T20%3A42%3A04Z&se=2021-02-28T20%3A47%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 20:53 UTC, opbld33 commented
Docs Build status updates of commit _[826e902](https://github.com/microsoftgraph/microsoft-graph-docs/commits/826e902a272af539c5485d05a26f9601a5273be5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282051450464-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3t1mJ6Ful%2FyCSIpdfdLoJMvi1xiSxWzA6ipFmY3TeHQ%3D&st=2021-01-28T20%3A48%3A49Z&se=2021-02-28T20%3A53%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 20:58 UTC, opbld31 commented
Docs Build status updates of commit _[9f9d036](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f9d036637e5e5318bcc13c5da942a62e0a2bc98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/api/authenticationmethodsroot-usersregisteredbymethod.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbymethod?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethods-usage-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/authenticationmethods-usage-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-usage-insights-overview?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturecount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturecount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturecount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationfeaturesummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationfeaturesummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationfeaturesummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodcount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodcount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodcount?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/resources/userregistrationmethodsummary.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/resources/userregistrationmethodsummary.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userregistrationmethodsummary?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethodsroot-usersregisteredbyfeature?view=graph-rest-beta&branch=pr-en-us-11174) (graph-rest-beta) |
[changelog/Microsoft.AAD.Reporting.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/changelog/Microsoft.AAD.Reporting.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/danielwood95authMethodsActivityPublish1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11174) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282055598278-11174%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VbB4MreOycadekcHZnX3PxnJ4kf3GtofhZronDor1Og%3D&st=2021-01-28T20%3A53%3A06Z&se=2021-02-28T20%3A58%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 20:59 UTC, danielwood95 commented on api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
> +
added

2021-01-28 20:59 UTC, danielwood95 commented on api-reference/beta/api/authenticationmethodsroot-usersregisteredbyfeature.md
> +The following table shows the parameters that can be used with this function.
done

2021-01-29 04:49 UTC, Lauragra approved these changes

2021-01-29 04:51 UTC, merged