Update graph doc for additional scopes
microsoftgraph/microsoft-graph-docs pull request #11192
Opened 2021-01-05 20:54 UTC by jahsu-MSFT

2021-01-05 20:56 UTC, opbld31 commented
Docs Build status updates of commit _[8c6988a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c6988aafec0d57317537c1fa4f52407bd27708b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-a1e092ce)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-a1e092ce)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-a1e092ce)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-a1e092ce)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-a1e092ce)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-a1e092ce)

<a id="40a02138-a1e092ce"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-a1e092ce"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-a1e092ce"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-a1e092ce"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-a1e092ce"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-a1e092ce"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101052054523169-11192%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eSXEb4agQadHtNQwzgWOoZfjbulNH%2FcD9mfL6NzUTdg%3D&st=2021-01-05T20%3A51%3A02Z&se=2021-02-05T20%3A56%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-05 20:58 UTC, braedenp-msft approved these changes

2021-01-05 21:40 UTC, opbld30 commented
Docs Build status updates of commit _[aca6e29](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aca6e299c62b3eb3eebb2d96b29387bf4b92ce83)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-f99f312e)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-f99f312e)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-f99f312e)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-f99f312e)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-f99f312e)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-f99f312e)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-451a6abd-f99f312e)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-704888e3-f99f312e)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-c8d02de1-f99f312e)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-f07dfc2b-f99f312e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-f99f312e)

<a id="40a02138-f99f312e"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-f99f312e"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-f99f312e"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-f99f312e"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-f99f312e"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-f99f312e"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="451a6abd-f99f312e"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contrib [...]

2021-01-05 21:43 UTC, opbld31 commented
Docs Build status updates of commit _[34ae8d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34ae8d45634ad9451aa209657378dd02db9ba77c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-89db1060)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-89db1060)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-89db1060)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-89db1060)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-89db1060)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-89db1060)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-451a6abd-89db1060)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-704888e3-89db1060)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-c8d02de1-89db1060)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-f07dfc2b-89db1060)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-89db1060)

<a id="40a02138-89db1060"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-89db1060"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-89db1060"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-89db1060"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-89db1060"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-89db1060"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="451a6abd-89db1060"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contrib [...]

2021-01-05 21:52 UTC, opbld34 commented
Docs Build status updates of commit _[e38b72a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e38b72a82e76cb764b3523aab4b0f6ba31d8f441)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-7c114344)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-7c114344)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-7c114344)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-7c114344)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-7c114344)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-7c114344)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-451a6abd-7c114344)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-704888e3-7c114344)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-c8d02de1-7c114344)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-f07dfc2b-7c114344)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-7c114344)

<a id="40a02138-7c114344"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-7c114344"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-7c114344"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-7c114344"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-7c114344"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-7c114344"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="451a6abd-7c114344"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contrib [...]

2021-01-08 21:06 UTC, opbld33 commented
Docs Build status updates of commit _[5cad56e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5cad56ec179e510eb63d9084d1d36850cc4aff79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-416f6af6)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-416f6af6)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-416f6af6)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-416f6af6)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-416f6af6)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-416f6af6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-416f6af6)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printer-post-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printjob-start.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |

<a id="40a02138-416f6af6"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-416f6af6"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-416f6af6"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-416f6af6"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-416f6af6"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-416f6af6"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-416f6af6"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Colu [...]

2021-01-08 21:13 UTC, opbld31 commented
Docs Build status updates of commit _[ad3b3fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad3b3fd46c292727617f7739307a8be7dce055bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-3ba186a4)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-3ba186a4)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-3ba186a4)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-3ba186a4)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-3ba186a4)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-3ba186a4)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-3ba186a4)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printer-post-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printjob-start.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-3ba186a4"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-3ba186a4"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-3ba186a4"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-3ba186a4"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-3ba186a4"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-3ba186a4"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-3ba186a4"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gra [...]

2021-01-08 22:27 UTC, nilakhan requested changes

2021-01-08 22:27 UTC, nilakhan commented on api-reference/beta/api/print-get-settings.md
> +|Delegated (work or school account)| PrintSettings.Read.All |
also, PrintSettings.ReadWrite.All

2021-01-08 22:27 UTC, nilakhan commented on api-reference/beta/api/printdocument-createuploadsession.md
> -| Delegated (work or school account)     | PrintJob.Create, PrintJob.ReadWrite, PrintJob.ReadWrite.All |
I think we should preserve the original order as PrintJob.Create is the least privileged scope and PrintJob.ReadWrite.All is the most privileged scope amongst these 3

2021-01-08 22:27 UTC, nilakhan commented on api-reference/beta/api/printer-post-jobs.md
> +|Delegated (work or school account)| PrintJob.ReadWriteBasic, PrintJob.ReadWrite, PrintJob.ReadWriteBasic.All, PrintJob.ReadWrite.All, PrinterJob.Create |
Lets keep the same order which it was before

2021-01-08 22:27 UTC, nilakhan commented on api-reference/beta/api/printjob-start.md
> +|Delegated (work or school account)| PrintJob.ReadWriteBasic, PrintJob.ReadWrite, PrintJob.ReadWriteBasic.All, PrintJob.ReadWrite.All, PrinterJob.Create |
lets keep the same order here as well

2021-01-08 22:27 UTC, nilakhan commented on concepts/changelog.md
> +| Addition | beta | Added new [Delegated permissions](/graph/permissions-reference#universal-print-permissions): <br/><ul><li>PrintJob.Create</li><li>PrinterShare.ReadBasic.All</li><li>PrintConnector
We also need to add Reports.Read.All scope for all reporting endpoints

2021-01-08 22:27 UTC, nilakhan commented on concepts/permissions-reference.md
> +| _PrintConnector.ReadWrite.All_ | Read, update and unregister connectors | Allows the application to read, update and delete (unregister) connectors on behalf of the signed-in user. | Yes | No |
Read, update and unregister connectors => Read and write print connectors. 
Description =>  
Allows the application to read and write print connectors on behalf of the signed-in user.

![image](https://user-images.githubusercontent.com/67128169/104071184-7c3d6800-51bd-11eb-94eb-6bf8f794abad.png)

2021-01-08 22:27 UTC, nilakhan commented on concepts/permissions-reference.md
> +| _PrintConnector.ReadWrite.All_ | Read, update and unregister connectors | Allows the application to read, update and delete (unregister) connectors on behalf of the signed-in user. | Yes | No |
We should use strings that have already been published in Azure Portal (we can see them while trying to configure permissions in portal).

2021-01-08 23:01 UTC, opbld33 commented
Docs Build status updates of commit _[bcfffd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bcfffd006177b29349ee8467d55a949f53eb1107)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-a0744897)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-a0744897)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-a0744897)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-a0744897)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-a0744897)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-a0744897)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-a0744897)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printer-post-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printjob-start.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-a0744897"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-a0744897"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-a0744897"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-a0744897"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-a0744897"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-a0744897"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-a0744897"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /gra [...]

2021-01-08 23:04 UTC, opbld31 commented
Docs Build status updates of commit _[1c5ee06](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c5ee062318dbfc9b2d1061b203b45b9d4710b5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-0a5e15ec)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-0a5e15ec)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-0a5e15ec)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-0a5e15ec)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-0a5e15ec)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-0a5e15ec)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-0a5e15ec)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-0a5e15ec"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-0a5e15ec"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-0a5e15ec"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-0a5e15ec"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-0a5e15ec"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-0a5e15ec"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-0a5e15ec"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Sugg [...]

2021-01-14 22:05 UTC, Lauragra commented on concepts/changelog.md
> +| Addition | beta | Added new [Delegated permissions](/graph/permissions-reference#universal-print-permissions): <br/><ul><li>PrintJob.Create</li><li>PrinterShare.ReadBasic.All</li><li>PrintConnector
Please update the entry in the changelog JSON file for this change as well.

2021-01-14 23:49 UTC, opbld34 commented
Docs Build status updates of commit _[62a6a53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62a6a537883b9831e38baa06a2d8ef6ff5d3a44a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-9ec2fcb6)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-9ec2fcb6)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-9ec2fcb6)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-9ec2fcb6)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-9ec2fcb6)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-9ec2fcb6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-9ec2fcb6)
[changelog/Microsoft.Analytics.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.Analytics.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-9ec2fcb6"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-9ec2fcb6"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-9ec2fcb6"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-9ec2fcb6"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-9ec2fcb6"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-9ec2fcb6"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-9ec2fcb6"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Sugge [...]

2021-01-14 23:51 UTC, opbld32 commented
Docs Build status updates of commit _[30c05aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30c05aa49ebbbbd03670f85eef40e348db36e5b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-4842fb19)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-4842fb19)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-4842fb19)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-4842fb19)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-4842fb19)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-4842fb19)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-4842fb19)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-4842fb19"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-4842fb19"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-4842fb19"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-4842fb19"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-4842fb19"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-4842fb19"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-4842fb19"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Sugg [...]

2021-01-14 23:53 UTC, opbld33 commented
Docs Build status updates of commit _[eaae99b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaae99b9c245d6b3f2550a73b9df85a754a1730c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-7cc1d923)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-7cc1d923)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-7cc1d923)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-7cc1d923)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-7cc1d923)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-7cc1d923)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-7cc1d923)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-7cc1d923"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-7cc1d923"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-7cc1d923"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-7cc1d923"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-7cc1d923"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-7cc1d923"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-7cc1d923"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Sugg [...]

2021-01-14 23:57 UTC, opbld31 commented
Docs Build status updates of commit _[cf8173e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf8173e8574374c443e36d06ffcfbd09e80b4007)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-7994e2c1)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-7994e2c1)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-7994e2c1)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-7994e2c1)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-7994e2c1)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-7994e2c1)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-7994e2c1)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-7994e2c1"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-7994e2c1"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-7994e2c1"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-7994e2c1"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-7994e2c1"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-7994e2c1"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-7994e2c1"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Sugg [...]

2021-01-15 00:11 UTC, nilakhan requested changes

2021-01-15 00:11 UTC, nilakhan commented on changelog/Microsoft.PrintService.json
> +          "ChangedApiName": "printJob, printerShare, connector, printSetting",
printConnector, printSettings

2021-01-15 00:11 UTC, nilakhan commented on concepts/permissions-reference.md
> +| _Reports.Read.All_ | Read all usage reports | Allows the application to read reports on behalf of the signed-in user. | Yes | No |
Reports.Read.All is not a print specific scope. Do we need to add it here as well @braedenp-msft ?

2021-01-15 00:11 UTC, nilakhan commented on concepts/changelog.md
> +| Addition | beta | Added new [Delegated permissions](/graph/permissions-reference#universal-print-permissions): <br/><ul><li>PrintJob.Create</li><li>PrinterShare.ReadBasic.All</li><li>PrintConnector
We need to add this to reporting APIs as well.

2021-01-15 00:46 UTC, opbld31 commented
Docs Build status updates of commit _[643a2b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/643a2b549d23492768d24ea21fe10a9c1378e798)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-fe081e0c)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-fe081e0c)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-fe081e0c)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-fe081e0c)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-fe081e0c)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-fe081e0c)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-fe081e0c)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-fe081e0c"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-fe081e0c"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-fe081e0c"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-fe081e0c"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-fe081e0c"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-fe081e0c"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-fe081e0c"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Sugg [...]

2021-01-15 01:23 UTC, opbld34 commented
Docs Build status updates of commit _[f9099a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9099a8d02cc6a4c8652ab180d447a1fdecdcae6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-40a02138-90695216)
[api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-2aa2f409-90695216)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-1e948d74-90695216)
[api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-e4decd48-90695216)
[api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-3d2fafe2-90695216)
[api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-beta&branch=pr-en-us-11192) (graph-rest-beta) | [Details](#user-content-9d3eafd4-90695216)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11192) | [Details](#user-content-075040e5-90695216)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11192) |

<a id="40a02138-90695216"></a>
### [api-reference/beta/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-get-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2aa2f409-90695216"></a>
### [api-reference/beta/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-list-connectors.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="1e948d74-90695216"></a>
### [api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/print-update-settings.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="e4decd48-90695216"></a>
### [api-reference/beta/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-delete.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="3d2fafe2-90695216"></a>
### [api-reference/beta/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="9d3eafd4-90695216"></a>
### [api-reference/beta/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/api-reference/beta/api/printconnector-update.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-90695216"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-graph-doc-for-additional-scopes/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Sugg [...]

2021-01-15 01:26 UTC, merged

2021-01-15 02:09 UTC, jahsu-MSFT commented on concepts/permissions-reference.md
> +| _Reports.Read.All_ | Read all usage reports | Allows the application to read reports on behalf of the signed-in user. | Yes | No |
Thanks @Lauragra for removing the Reports.Read.All and merging the PR.