Add xps to pdf conversion details, PrintJob.Create and PrinterShare.ReadBasic.All scope and minor fixes
microsoftgraph/microsoft-graph-docs pull request #11191
Opened 2021-01-05 18:13 UTC by nilakhan

Add xps to pdf conversion details, PrintJob.Create and PrinterShare.ReadBasic.All scope and minor fixes

2021-01-05 18:14 UTC, opbld30 commented
Docs Build status updates of commit _[365e21c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/365e21ca218a6acb62bcff9f4781f9a2870d5ba5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-6a11eb5f)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-6a11eb5f)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-6a11eb5f)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-6a11eb5f)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-6a11eb5f)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-6a11eb5f)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-6a11eb5f)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-6a11eb5f)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-6a11eb5f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |

<a id="451a6abd-6a11eb5f"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-6a11eb5f"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-6a11eb5f"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-6a11eb5f"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-6a11eb5f"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-6a11eb5f"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-6a11eb5f"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-6a11eb5f"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cb1163c3-6a11eb5f"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology- [...]

2021-01-05 18:27 UTC, opbld31 commented
Docs Build status updates of commit _[1718231](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17182317ba962223ca1c43e270fe9ec435f6bb45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-67db5f3b)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-67db5f3b)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-67db5f3b)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-67db5f3b)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-67db5f3b)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-67db5f3b)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-67db5f3b)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-67db5f3b)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-67db5f3b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-67db5f3b"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-67db5f3b"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-67db5f3b"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-67db5f3b"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-67db5f3b"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-67db5f3b"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-67db5f3b"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-67db5f3b"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod- [...]

2021-01-05 18:36 UTC, opbld33 commented
Docs Build status updates of commit _[c19a314](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c19a31415e4efbbbafe4ba3bccbba72f1f11cb7b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-fb03de8f)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-fb03de8f)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-fb03de8f)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-fb03de8f)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-fb03de8f)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-fb03de8f)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-fb03de8f)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-fb03de8f)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-fb03de8f)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-fb03de8f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-fb03de8f"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-fb03de8f"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-fb03de8f"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-fb03de8f"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-fb03de8f"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-fb03de8f"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-fb03de8f"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-fb03de8f"></a>
### [api-reference/beta [...]

2021-01-05 18:40 UTC, braedenp-msft approved these changes

2021-01-05 18:41 UTC, opbld34 commented
Docs Build status updates of commit _[f7950f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7950f9376befe8fde9922d483d687cd81293c3a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-19632026)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-19632026)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-19632026)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-19632026)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-19632026)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-19632026)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-19632026)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-19632026)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-19632026)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-19632026)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-19632026"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-19632026"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-19632026"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-19632026"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-19632026"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-19632026"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-19632026"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-19632026"></a>
### [api-reference/beta [...]

2021-01-05 18:54 UTC, opbld31 commented
Docs Build status updates of commit _[6e50d98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e50d98e691287bb12fce8155e813718bd704bc7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-08a51c35)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-08a51c35)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-08a51c35)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-08a51c35)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-08a51c35)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-08a51c35)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-08a51c35)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-08a51c35)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-08a51c35)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-08a51c35)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-08a51c35"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-08a51c35"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-08a51c35"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-08a51c35"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-08a51c35"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-08a51c35"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-08a51c35"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-08a51c35"></a>
### [api-reference/beta [...]

2021-01-05 19:59 UTC, opbld30 commented
Docs Build status updates of commit _[7e866ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e866eafff212df910e37e076a16339d52ba29fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-ff305412)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-ff305412)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-ff305412)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-ff305412)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-ff305412)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-ff305412)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-ff305412)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-ff305412)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-ff305412)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-ff305412)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-ff305412"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-ff305412"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-ff305412"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-ff305412"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-ff305412"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-ff305412"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-ff305412"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-ff305412"></a>
### [api-reference/beta [...]

2021-01-05 20:01 UTC, opbld30 commented
Docs Build status updates of commit _[1a0369d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a0369d2376e2489b1f66c0f178fc1cdc2e2af5d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-f0674b13)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-f0674b13)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-f0674b13)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-f0674b13)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-f0674b13)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-f0674b13)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-f0674b13)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-f0674b13)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-f0674b13)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-f0674b13)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-f0674b13"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-f0674b13"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-f0674b13"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-f0674b13"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-f0674b13"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-f0674b13"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-f0674b13"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-f0674b13"></a>
### [api-reference/beta [...]

2021-01-05 20:01 UTC, Lauragra commented on api-reference/beta/api/printdocument-createuploadsession.md
> +The **contentType** property in the request body should be supported by the printer/printer share (defined in [printerCapabilities](../resources/printercapabilities.md)). The only exception to this i
I'm not sure that this statement is entirely clear. What are we getting at with the link to printerCapabilities, vs. printDocumentUploadProperties? Can you better explain the exception? What is the action for the request if the three conditions are met?

2021-01-05 20:02 UTC, Lauragra commented on api-reference/beta/api/printdocument-get-file.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription and have either the _Printer.Read.All_ or _Printer.ReadWrite.All_ application permi
Global: Although the permission names are italicized in the permissions reference, we don't italicize them in content, in the permissions tables, etc.

2021-01-05 20:08 UTC, opbld32 commented
Docs Build status updates of commit _[ff8c573](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff8c5730d8357072c3eef65b9c67dc6ff0dc4be2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-4cbc01e0)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-4cbc01e0)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-4cbc01e0)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-4cbc01e0)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-4cbc01e0)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-4cbc01e0)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-4cbc01e0)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-4cbc01e0)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-4cbc01e0)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-4cbc01e0)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-4cbc01e0"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-4cbc01e0"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-4cbc01e0"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-4cbc01e0"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-4cbc01e0"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-4cbc01e0"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-4cbc01e0"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-4cbc01e0"></a>
### [api-reference/beta [...]

2021-01-05 20:09 UTC, Lauragra commented on api-reference/beta/api/printer-get.md
> +By default, the response will not contain [printerCapabilities](../resources/printerCapabilities.md). **To get printerCapabilities, use the $select query parameter**. e.g.:
I recommend mentioning this in the query parameters section. Here in the response section you can simply state that if the `$select` parameter is specified, the response will also include printer capabilities. Also, you might want to add an example that shows how to get a printer and its printer capabilities, and what the response looks like.

2021-01-05 20:11 UTC, Lauragra commented on api-reference/beta/api/printershare-get.md
> +By default, the response will not contain [printerCapabilities](../resources/printerCapabilities.md). **To get printerCapabilities, use the $select query option**. e.g.:
Same comment here as previous - add this to the query parameters section and add an example.

2021-01-05 20:12 UTC, opbld33 commented
Docs Build status updates of commit _[84a33bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84a33bb33b1beafdf30368b3ab64767b60de7243)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-50f7b873)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-50f7b873)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-50f7b873)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-50f7b873)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-50f7b873)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-50f7b873)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-50f7b873)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-50f7b873)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-50f7b873)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-50f7b873)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-50f7b873"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-50f7b873"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-50f7b873"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-50f7b873"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-50f7b873"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-50f7b873"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-50f7b873"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-50f7b873"></a>
### [api-reference/beta [...]

2021-01-05 20:13 UTC, opbld30 commented
Docs Build status updates of commit _[44e5b58](https://github.com/microsoftgraph/microsoft-graph-docs/commits/44e5b58cdfd0ff8f6b72c576368744d9b17b4e3d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-ced912c7)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-ced912c7)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-ced912c7)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-ced912c7)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-ced912c7)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-ced912c7)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-ced912c7)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-ced912c7)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-ced912c7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-ced912c7)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-ced912c7"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-ced912c7"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-ced912c7"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-ced912c7"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-ced912c7"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-ced912c7"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-ced912c7"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-ced912c7"></a>
### [api-reference/beta [...]

2021-01-05 20:15 UTC, tomsato-ms approved these changes

2021-01-05 20:18 UTC, opbld34 commented
Docs Build status updates of commit _[ff8d333](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff8d333788e7c0afdf09ebb9110e4e34fde27e31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-6e135484)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-6e135484)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-6e135484)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-6e135484)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-6e135484)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-6e135484)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-6e135484)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-6e135484)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-6e135484)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-6e135484)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-6e135484"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-6e135484"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-6e135484"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-6e135484"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-6e135484"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-6e135484"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-6e135484"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-6e135484"></a>
### [api-reference/beta [...]

2021-01-05 20:20 UTC, Lauragra commented on api-reference/beta/api/printdocument-createuploadsession.md
> +| Delegated (work or school account)     | PrintJob.Create, PrintJob.ReadWrite, PrintJob.ReadWrite.All |
Global: If you want to get rid of the warnings on the PR, you'll eventually want to update your ms.prod values to "cloud-printing".

2021-01-05 20:20 UTC, Lauragra requested changes
Please see comments on the PR.

2021-01-05 21:54 UTC, jahsu-MSFT approved these changes

2021-01-07 16:38 UTC, opbld33 commented
Docs Build status updates of commit _[0a6a1da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a6a1da9f51d91e7b4dcb68d9692f6806345d34c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-184f4793)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-184f4793)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-184f4793)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-184f4793)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-184f4793)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-184f4793)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-184f4793)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-184f4793)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-184f4793)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-184f4793)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-184f4793"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-184f4793"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-184f4793"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-184f4793"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-184f4793"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-184f4793"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-184f4793"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-184f4793"></a>
### [api-reference/beta [...]

2021-01-07 16:48 UTC, opbld31 commented
Docs Build status updates of commit _[c38ec5e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c38ec5e1592cffa7648e6ec4f22004f7c4f65274)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-bc1e5c80)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-bc1e5c80)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-bc1e5c80)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-bc1e5c80)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-bc1e5c80)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-bc1e5c80)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-bc1e5c80)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-bc1e5c80)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-bc1e5c80)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-bc1e5c80)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-bc1e5c80"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-bc1e5c80"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-bc1e5c80"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-bc1e5c80"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-bc1e5c80"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-bc1e5c80"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-bc1e5c80"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-bc1e5c80"></a>
### [api-reference/beta [...]

2021-01-07 16:58 UTC, opbld30 commented
Docs Build status updates of commit _[30ed8ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30ed8ea60ca2771ea2e2a357692094e2ac9a5982)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-c34761c6)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-c34761c6)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-c34761c6)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-c34761c6)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-c34761c6)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-c34761c6)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-c34761c6)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-c34761c6)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-c34761c6)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-c34761c6)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-c34761c6"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-c34761c6"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-c34761c6"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-c34761c6"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-c34761c6"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-c34761c6"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-c34761c6"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-c34761c6"></a>
### [api-reference/beta [...]

2021-01-07 16:59 UTC, nilakhan commented on api-reference/beta/api/printdocument-get-file.md
> +In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription and have either the _Printer.Read.All_ or _Printer.ReadWrite.All_ application permi
Updated. Thanks

2021-01-07 16:59 UTC, nilakhan commented on api-reference/beta/api/printdocument-createuploadsession.md
> +| Delegated (work or school account)     | PrintJob.Create, PrintJob.ReadWrite, PrintJob.ReadWrite.All |
Where can we update this?

2021-01-07 17:00 UTC, opbld33 commented
Docs Build status updates of commit _[b83eebe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b83eebe25d9d45c9da9161fef281bf85a61a8b47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-05d0581e)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-05d0581e)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-05d0581e)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-05d0581e)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-05d0581e)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-05d0581e)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-05d0581e)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-05d0581e)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-05d0581e)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-05d0581e)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-05d0581e"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-05d0581e"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-05d0581e"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-05d0581e"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-05d0581e"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-05d0581e"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-05d0581e"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-05d0581e"></a>
### [api-reference/beta [...]

2021-01-07 18:32 UTC, nilakhan commented on api-reference/beta/api/printdocument-createuploadsession.md
> +The **contentType** property in the request body should be supported by the printer/printer share (defined in [printerCapabilities](../resources/printercapabilities.md)). The only exception to this i
I have updated this documentation. Please let me know if there are any concerns.

2021-01-07 18:32 UTC, opbld34 commented
Docs Build status updates of commit _[8bea4f2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bea4f227e78b44543fe3371be93a4f35483a731)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-fd2389a2)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-fd2389a2)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-fd2389a2)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-fd2389a2)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-fd2389a2)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-fd2389a2)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-fd2389a2)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-fd2389a2)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-fd2389a2)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-fd2389a2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-fd2389a2"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-fd2389a2"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-fd2389a2"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-fd2389a2"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-fd2389a2"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-fd2389a2"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-fd2389a2"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-fd2389a2"></a>
### [api-reference/beta [...]

2021-01-07 18:49 UTC, opbld30 commented
Docs Build status updates of commit _[d58274a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d58274abec073da9758125ccb566602379e9a359)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-0f0d6b5b)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-0f0d6b5b)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-0f0d6b5b)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-0f0d6b5b)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-0f0d6b5b)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-0f0d6b5b)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-0f0d6b5b)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-0f0d6b5b)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-0f0d6b5b)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-0f0d6b5b)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-0f0d6b5b"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-0f0d6b5b"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-0f0d6b5b"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-0f0d6b5b"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-0f0d6b5b"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-0f0d6b5b"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-0f0d6b5b"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-0f0d6b5b"></a>
### [api-reference/beta [...]

2021-01-07 18:51 UTC, nilakhan commented on api-reference/beta/api/printer-get.md
> +By default, the response will not contain [printerCapabilities](../resources/printerCapabilities.md). **To get printerCapabilities, use the $select query parameter**. e.g.:
Updated. thanks!

2021-01-07 18:52 UTC, nilakhan commented on api-reference/beta/api/printershare-get.md
> +By default, the response will not contain [printerCapabilities](../resources/printerCapabilities.md). **To get printerCapabilities, use the $select query option**. e.g.:
Updated. Thanks!

2021-01-07 18:53 UTC, opbld31 commented
Docs Build status updates of commit _[9ec7914](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ec7914a79a663b81a0942341457a308006a19c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-451a6abd-345771e7)
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-345771e7)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-345771e7)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-345771e7)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-345771e7)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-345771e7)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-345771e7)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-345771e7)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-345771e7)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-345771e7)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="451a6abd-345771e7"></a>
### [api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="2c60ef23-345771e7"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-345771e7"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-345771e7"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-345771e7"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-345771e7"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-345771e7"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-345771e7"></a>
### [api-reference/beta [...]

2021-01-07 18:54 UTC, opbld30 commented
Docs Build status updates of commit _[c255e11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c255e113fa9db92342895e8cd930ce0c74662a04)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-2c60ef23-42f97e44)
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-42f97e44)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-42f97e44)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-42f97e44)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-42f97e44)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-42f97e44)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-42f97e44)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-42f97e44)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-42f97e44)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="2c60ef23-42f97e44"></a>
### [api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="8b03a81b-42f97e44"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-42f97e44"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-42f97e44"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-42f97e44"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-42f97e44"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-42f97e44"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cb1163c3-42f97e44"></a>
### [api-reference/beta/resources/printjob.md](https://github.c [...]

2021-01-07 18:55 UTC, opbld30 commented
Docs Build status updates of commit _[a6de6eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6de6ebcd80331867ff5f41bd9d2564fe337439a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-8b03a81b-3efca999)
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-3efca999)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-3efca999)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-3efca999)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-3efca999)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-3efca999)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-3efca999)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-3efca999)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="8b03a81b-3efca999"></a>
### [api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="704888e3-3efca999"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-3efca999"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-3efca999"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-3efca999"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-3efca999"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cb1163c3-3efca999"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-3efca999"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jo [...]

2021-01-07 18:57 UTC, opbld33 commented
Docs Build status updates of commit _[f77f2fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f77f2febe3468ceac9be42e3479190e254ff03dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-704888e3-69b5d919)
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-c8d02de1-69b5d919)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-69b5d919)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-69b5d919)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-69b5d919)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-69b5d919)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-69b5d919)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="704888e3-69b5d919"></a>
### [api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="c8d02de1-69b5d919"></a>
### [api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b2eff973-69b5d919"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-69b5d919"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-69b5d919"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cb1163c3-69b5d919"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-69b5d919"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph [...]

2021-01-07 18:58 UTC, opbld33 commented
Docs Build status updates of commit _[dbc0839](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dbc08391a19a704d18332a921e4e5998b05e1ea5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-b2eff973-6c062d8f)
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-f07dfc2b-6c062d8f)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-5dd27ba9-6c062d8f)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) | [Details](#user-content-cb1163c3-6c062d8f)
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-6c062d8f)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="b2eff973-6c062d8f"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f07dfc2b-6c062d8f"></a>
### [api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="5dd27ba9-6c062d8f"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cb1163c3-6c062d8f"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="075040e5-6c062d8f"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you  [...]

2021-01-07 18:59 UTC, opbld30 commented
Docs Build status updates of commit _[df04803](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df04803ef94cc02f6b27afb6a38c6728d455b7d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-94116919)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="075040e5-94116919"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pre [...]

2021-01-08 04:49 UTC, Lauragra approved these changes

2021-01-08 04:51 UTC, opbld30 commented
Docs Build status updates of commit _[2039429](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2039429b30fa0afd65bf5d2b5397925ed989b939)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11191) | [Details](#user-content-075040e5-d68b52a3)
[api-reference/beta/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-createuploadsession.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printer-post-jobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-post-jobs?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printershare-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printjob-start.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-start.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-start?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/api/printjob-update-configuration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-beta&branch=pr-en-us-11191) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11191) |

<a id="075040e5-d68b52a3"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-jobcreatescope/concepts/permissions-reference.md)
 - **Line 177, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/useranalytics-get-settings?view=graph-rest-beta`````
 - **Line 206, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-list?view=graph-rest-beta`````
 - **Line 207, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-publish?view=graph-rest-beta`````
 - **Line 208, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-update?view=graph-rest-beta`````
 - **Line 209, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/teamsapp-delete?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-list-owners?view=graph-rest-beta`````
 - **Line 238, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/serviceprincipal-list-owners?view=graph-rest-beta`````
 - **Line 346, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 397, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/application-post-calls?view=graph-rest-beta`````
 - **Line 435, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/user?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/group?view=graph-rest-1.0`````
 - **Line 663, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/device?view=graph-rest-1.0`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/orgcontact?view=graph-rest-beta`````
 - **Line 665, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &pre [...]

2021-01-08 04:53 UTC, merged