Documentation for UsageRights Resource Type and Navigational Properties
microsoftgraph/microsoft-graph-docs pull request #11214
Opened 2021-01-06 23:39 UTC by AkshayMSFT

Docs for the introduction of the usageRights resource type and the navigational properties on user/device.

2021-01-06 23:41 UTC, opbld33 commented
Docs Build status updates of commit _[a11cc54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a11cc54957385f5f33ae4310fa412d0929725f8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) | [Details](#user-content-8382d873-5ccc661a)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.Commerce.Licensing.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.Commerce.Licensing.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

<a id="8382d873-5ccc661a"></a>
### [api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101062339458549-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m309MdzsA3ZUrbaKouwCuGc7%2FchI%2F4%2Bux%2Bn4IVbJA34%3D&st=2021-01-06T23%3A36%3A10Z&se=2021-02-06T23%3A41%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 02:50 UTC, opbld33 commented
Docs Build status updates of commit _[5a796d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5a796d0b0bc25f8a54236704bd6e0266863eb060)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-553ed7fe)

<a id="553ed7fe"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101110250066596-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=deOsUERwoJb%2BT9HW4BNzNcEgNFx4ubHH2441nZdBRMc%3D&st=2021-01-11T02%3A45%3A23Z&se=2021-02-11T02%3A50%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 03:03 UTC, opbld32 commented
Docs Build status updates of commit _[55f73f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55f73f0ad68ecc64aee181cac11b19105c2a1ebb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101110301452464-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GeYXnzhWcVOWvqdjRaSWOUPoyG4tmi%2FeiisD8U84l5k%3D&st=2021-01-11T02%3A58%3A13Z&se=2021-02-11T03%3A03%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 03:10 UTC, opbld32 commented
Docs Build status updates of commit _[3a9b1c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a9b1c84b97123be44021458635c6843dd97f801)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101110308509208-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=89PmEFl7Mvkp6E6k4L9bo5s31yKoPCH0Ati1ju%2FQak8%3D&st=2021-01-11T03%3A05%3A07Z&se=2021-02-11T03%3A10%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 03:21 UTC, opbld30 commented
Docs Build status updates of commit _[3fd7c6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fd7c6b81baaf3fb331fcb6d33ebf2d3d6fb63bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101110319444125-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2Bx%2BDcRK04qdJSjR%2BsIZcrSymk%2FILyHzhXnLx9FzbNU%3D&st=2021-01-11T03%3A16%3A05Z&se=2021-02-11T03%3A21%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 07:11 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +author: "AkshayMSFT"
Should author be something more generic?

2021-01-12 07:22 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +|$filter = state eq 'value'|
can we make this align to left?

2021-01-12 07:23 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +|$filter = state eq 'value'|
for other tables also

2021-01-12 07:23 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +|Authorization|Bearer {token}. Required.|
AAD token?

2021-01-12 07:24 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +Do not supply a request body for this method.
can we simply say None?

2021-01-12 07:26 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +      "state": "Active",
should we add a note that state enums are not case sensitive?

2021-01-12 07:28 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
These includes get expanded during build time?

2021-01-12 07:29 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +GET https://graph.microsoft.com/beta/devices/{deviceId}/usageRights
I think we should say that you expect objectId of device because there is a thing called deviceId also in the directory.

2021-01-12 07:32 UTC, jeeshnair commented on api-reference/beta/api/user-list-usagerights.md
> +
same comments are device ones

2021-01-12 07:33 UTC, jeeshnair commented on api-reference/beta/api/user-list-usagerights.md
> +|Delegated (work or school account)|User.Read, User.ReadWrite, User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All|
I think you are missing User.ReadBasic.All ?

2021-01-12 07:34 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +      "serviceIdentifier": "mscrm.f6d23ec7-255c-4bd8-8c99-dc041d5cb8b3.517f7ddd-df45-4f1c-83ec-a081a047f546",
where do we talk about what these fields are?

2021-01-12 07:35 UTC, jeeshnair commented on api-reference/beta/api/device-list-usagerights.md
> +      "serviceIdentifier": "mscrm.f6d23ec7-255c-4bd8-8c99-dc041d5cb8b3.517f7ddd-df45-4f1c-83ec-a081a047f546",
aah in usageright resource. Got it.

2021-01-12 07:37 UTC, jeeshnair commented on api-reference/beta/api/user-list-usagerights.md
> +      "@odata.nextLink": "https://graph.microsoft.com/beta/users/64952b80-51fd-4378-9ba5-589a840afb80/usageRights?$skiptoken=W4diD29cGKX1bX"
This is wrong right? nextlink should be outside the collection.

2021-01-12 07:38 UTC, jeeshnair commented on api-reference/beta/api/user-list-usagerights.md
> +      "@odata.nextLink": "https://graph.microsoft.com/beta/users/64952b80-51fd-4378-9ba5-589a840afb80/usageRights?$skiptoken=W4diD29cGKX1bX"
i think the way you have represented value is wrong.

2021-01-12 07:39 UTC, jeeshnair commented on api-reference/beta/resources/usageright.md
> +|Method|Return type|Description|
can you align this table to left?

2021-01-12 07:40 UTC, jeeshnair commented on changelog/Microsoft.DirectoryServices.json
> +		   "Id": "0a73cfac-4f88-11eb-ae35-ed470c456b69",
these changeIds are all the same?

2021-01-12 07:42 UTC, jeeshnair requested changes
Primarily interested to see corrections to response json schema

2021-01-12 21:46 UTC, AkshayMSFT commented on changelog/Microsoft.DirectoryServices.json
> +		   "Id": "0a73cfac-4f88-11eb-ae35-ed470c456b69",
Yeah they are supposed to be within a change.

2021-01-12 21:47 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +author: "AkshayMSFT"
It says its the name of the person writing it, dev, other ones also have just dev names.

2021-01-12 21:56 UTC, opbld30 commented
Docs Build status updates of commit _[472e234](https://github.com/microsoftgraph/microsoft-graph-docs/commits/472e234f37522c07b8731bebcd0133049be0c92e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) | [Details](#user-content-de0bbbbb-65db942a)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-65db942a"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101122154518629-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BP%2BvDNZ034oQCmW%2BXokQNvjXSf50ni4U%2Boj2J2Awnqk%3D&st=2021-01-12T21%3A50%3A59Z&se=2021-02-12T21%3A55%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 21:57 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +[!INCLUDE [beta-disclaimer](../../includes/beta-disclaimer.md)]
yes, you can see in the preview page it shows the disclaimer.

2021-01-12 22:00 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +|Authorization|Bearer {token}. Required.|
These are pre-generated. And follows pattern such as:
https://docs.microsoft.com/en-us/graph/api/user-list-licensedetails?view=graph-rest-1.0&tabs=http

2021-01-12 22:00 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +Do not supply a request body for this method.
No, this is all pre-generated.

2021-01-12 22:05 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +GET https://graph.microsoft.com/beta/devices/{deviceId}/usageRights
good point

2021-01-12 22:05 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +      "serviceIdentifier": "mscrm.f6d23ec7-255c-4bd8-8c99-dc041d5cb8b3.517f7ddd-df45-4f1c-83ec-a081a047f546",
yup, which is also linked here.

2021-01-12 22:18 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +      "state": "Active",
I don't see other APIs explicitly saying, so leaving off for now. Can see what content reviewer thinks

2021-01-12 22:19 UTC, AkshayMSFT commented on api-reference/beta/api/user-list-usagerights.md
> +
Same reply : )

2021-01-12 22:20 UTC, AkshayMSFT commented on api-reference/beta/api/user-list-usagerights.md
> +|Delegated (work or school account)|User.Read, User.ReadWrite, User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All|
Not in the spec.

2021-01-12 22:20 UTC, AkshayMSFT commented on api-reference/beta/api/user-list-usagerights.md
> +      "@odata.nextLink": "https://graph.microsoft.com/beta/users/64952b80-51fd-4378-9ba5-589a840afb80/usageRights?$skiptoken=W4diD29cGKX1bX"
yes, bad copy paste. Good catch.

2021-01-12 22:56 UTC, AkshayMSFT commented on api-reference/beta/resources/usageright.md
> +|Method|Return type|Description|
it is

2021-01-12 22:56 UTC, AkshayMSFT commented on api-reference/beta/api/user-list-usagerights.md
> +|Delegated (work or school account)|User.Read, User.ReadWrite, User.Read.All, User.ReadWrite.All, Directory.Read.All, Directory.ReadWrite.All|
Sycned with Jeesh, this permission is not supported right now.

2021-01-12 22:59 UTC, opbld33 commented
Docs Build status updates of commit _[c4828b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4828b160b440874a10bda3014cac201b3e1e97e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) | [Details](#user-content-de0bbbbb-01822538)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-01822538"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md)
 - **Line 19, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101122257555586-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xX144EReJuUP8I2Dgg%2FZrxms60PoUZO0mLHcoDNynl8%3D&st=2021-01-12T22%3A54%3A04Z&se=2021-02-12T22%3A59%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 23:05 UTC, AkshayMSFT commented
> * iceSettings.md?view

The suggestion is for a file I did not add.

2021-01-14 07:42 UTC, jeeshnair approved these changes

2021-01-14 08:01 UTC, opbld33 commented
Docs Build status updates of commit _[0414909](https://github.com/microsoftgraph/microsoft-graph-docs/commits/041490942b96c0b9486136f2cbb91a6e9b634a9f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) | [Details](#user-content-de0bbbbb-4c97b4ce)
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="de0bbbbb-4c97b4ce"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md)
 - **Line 58, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 58, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 25, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140759432080-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QESB4s9phKHVWdWd8JhWcnRW145wOCF8twtka%2BY7Jj8%3D&st=2021-01-14T07%3A56%3A27Z&se=2021-02-14T08%3A01%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 18:34 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +author: "AkshayMSFT"
The author value is important. The GitHub alias that is listed there is who the GitHub issues that are submitted are assigned to. Addressing the issues is very important for product adoption.

2021-01-14 18:35 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +|$filter = state eq 'value'|
The format of these pages is strictly defined.

2021-01-14 18:36 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +Do not supply a request body for this method.
We shouldn't change these boiler plate text strings or the structure of the content.

2021-01-14 18:37 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +### Request 1
Should be:

### Example 1: Get all user rights for a device

#### Request

2021-01-14 18:38 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +### Response 1
#### Response

2021-01-14 18:40 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +### Request 2
### Example 2: Get user rights for a device using an identifier and in specific states

#### Request

2021-01-14 18:40 UTC, davidmu1 commented on api-reference/beta/api/device-list-usagerights.md
> +### Response 2
#### Response

2021-01-14 18:41 UTC, davidmu1 commented on api-reference/beta/api/user-list-usagerights.md
> +description: "Retrieve a list of usageRights objects for a user"
```suggestion
description: "Retrieve a list of usageRights objects for a user."
```

2021-01-14 18:43 UTC, davidmu1 commented on api-reference/beta/api/user-list-usagerights.md
> +|Examples|
Not sure why this is a table. It appears that there is only one column. Consider making a bulleted list.

2021-01-14 18:44 UTC, davidmu1 commented on api-reference/beta/api/user-list-usagerights.md
> +### Request 1
### Example 1: Get all usage rights for a user

#### Request

2021-01-14 18:45 UTC, davidmu1 commented on api-reference/beta/api/user-list-usagerights.md
> +### Response 1
#### Response

2021-01-14 18:46 UTC, davidmu1 commented on api-reference/beta/api/user-list-usagerights.md
> +### Request 2
### Example 2: Get usage rights for a user using an identifier and in specific states

2021-01-14 18:46 UTC, davidmu1 commented on api-reference/beta/api/user-list-usagerights.md
> +### Response 2
#### Response

2021-01-14 18:47 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +A Usage Right represents a license that a user or device has for either third party software built on power apps or for device based subscriptions (device only).
```suggestion
A usage right represents a license that a user or device has for either third party software built on power apps or for device based subscriptions (device only).
```

2021-01-14 18:48 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +|[List user usageRights](../api/user-list-usagerights.md)|[UsageRight](../resources/usageright.md) collection|Get the list of usage rights a user has.|
```suggestion
|[List user usageRights](../api/user-list-usagerights.md)|[UsageRight](../resources/usageright.md) collection|Get the list of usage rights for a user.|
```

2021-01-14 18:48 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +|[List device usageRights](../api/device-list-usagerights.md)|[UsageRight](../resources/usageright.md) collection|Get the list of usage rights a device has.|
```suggestion
|[List device usageRights](../api/device-list-usagerights.md)|[UsageRight](../resources/usageright.md) collection|Get the list of usage rights for a device.|
```

2021-01-14 18:49 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +|active            | 0     | Indicates that the usage right is active and can be used for provisioning benefits.|
I don't believe the value column provides anything to the user. Should be removed.

2021-01-14 18:50 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +|unknownFutureValue  | 4    | Sentinel value to indicate future values. |
I would remove this member. It is an internal placeholder and of no use to the user.

2021-01-14 18:50 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +>**Note:** Only the active and warning states represent a usable benefit. All other states should be treated as not resulting in a usable benefit (including any future additions to this enum).
```suggestion
>**Note:** Only the active and warning states represent a usable benefit. All other states should be treated as not resulting in a usable benefit.
```

2021-01-14 18:51 UTC, davidmu1 commented on concepts/changelog.md
> +| Addition          | beta        | Added the **usageRightState** enumeration type. |
```suggestion
| Addition          | beta        | Added the usageRightState enumeration type. |
```

2021-01-14 18:52 UTC, davidmu1 commented on concepts/changelog.md
> +| Addition          | beta        | Added the **usageRightState** enumeration type. |
```suggestion
| Addition          | beta        | Added the usageRightState enumeration type. |
```

2021-01-14 23:11 UTC, AkshayMSFT commented on api-reference/beta/resources/usageright.md
> +|active            | 0     | Indicates that the usage right is active and can be used for provisioning benefits.|
I was following this as an example:
https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta

Should I still remove the value? For enums sometimes clients can take dependencies on numeric values.

2021-01-14 23:20 UTC, AkshayMSFT commented on api-reference/beta/resources/usageright.md
> +|unknownFutureValue  | 4    | Sentinel value to indicate future values. |
I was keeping it in for 2 reasons.

1) For consistency sake, for ex: https://docs.microsoft.com/en-us/graph/api/resources/chat?view=graph-rest-beta

2) https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103144/Evolvable-enums
this is a pattern for dealing with additions to enums without making it breaking. And the incoming API is supposed to react accordingly depending on what preferences the client specifies.

I think this means it should be explicitly documented right?

2021-01-14 23:23 UTC, AkshayMSFT commented on api-reference/beta/resources/usageright.md
> +>**Note:** Only the active and warning states represent a usable benefit. All other states should be treated as not resulting in a usable benefit (including any future additions to this enum).
Hey David, can we leave this suggestion in? I think it will be good for clients to understand what values represent a useable benefit, regardless of what new values may come about. This way they can code defensively when having logic to do with state.

2021-01-14 23:27 UTC, AkshayMSFT commented on api-reference/beta/api/device-list-usagerights.md
> +author: "AkshayMSFT"
Is there a query to see what issues exist?

2021-01-14 23:31 UTC, opbld30 commented
Docs Build status updates of commit _[4a6e0b4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a6e0b4e8485699b484611a0cf410717da558035)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101142330032927-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L0u%2BRyvsY4MmmEfeDUbqYIFPw%2B8CLYiFsGjd4%2Fm60YA%3D&st=2021-01-14T23%3A26%3A14Z&se=2021-02-14T23%3A31%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 23:34 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +|active            | 0     | Indicates that the usage right is active and can be used for provisioning benefits.|
Yes, please remove the column.

2021-01-14 23:36 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +|unknownFutureValue  | 4    | Sentinel value to indicate future values. |
Apis have been published in the past with inconsistent documentation. Go ahead and leave it in, but my opinion it is for internal use and that if the customer can't use it, it should clutter up what can be used.

2021-01-14 23:38 UTC, AkshayMSFT commented on api-reference/beta/resources/usageright.md
> +|unknownFutureValue  | 4    | Sentinel value to indicate future values. |
Makes sense. Let me check with Jeesh and also get his thoughts on it.

2021-01-14 23:40 UTC, davidmu1 commented on api-reference/beta/resources/usageright.md
> +>**Note:** Only the active and warning states represent a usable benefit. All other states should be treated as not resulting in a usable benefit (including any future additions to this enum).
Beside the implication of possible future work, I actually also think that it just repeats what you said in the first sentence. Only active and warning are usable. That statement implies all other existing now or the future in my mind.

2021-01-15 02:56 UTC, AkshayMSFT commented on api-reference/beta/resources/usageright.md
> +|unknownFutureValue  | 4    | Sentinel value to indicate future values. |
Discussed with Jeesh, we will prefer to leave it in now since it is technically part of the semantics.

2021-01-15 02:58 UTC, opbld32 commented
Docs Build status updates of commit _[ad6d5a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad6d5a94766af0be2907c1193ec2e5222034e60d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101150256528476-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F1ZT%2BOLuiFxt23qiqefoi0Iw%2BGJLysgo3uBPATq5pKo%3D&st=2021-01-15T02%3A53%3A10Z&se=2021-02-15T02%3A58%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 01:18 UTC, Lauragra commented on api-reference/beta/api/user-list-usagerights.md
> +## Example 1: Get all usage rights for a user
We need a standard H2 section ## Examples. Then Example 1 and Example 2 become H3s (###) and the Request and Response headings are H4s (####). Please update.

2021-01-23 01:19 UTC, Lauragra commented on api-reference/beta/api/user-list-usagerights.md
> +**Note:** The response object shown here might be shortened for readability.
Global: Please format as a note by adding a ">" character before the word Note.

2021-01-23 01:20 UTC, Lauragra commented on api-reference/beta/api/user-list-usagerights.md
> +If successful, this method returns a `200 OK` response code and a collection of [UsageRight](../resources/usageright.md) objects in the response body.
Please use lower camel case for resource names, so, usageRight.

2021-01-23 01:22 UTC, opbld32 commented
Docs Build status updates of commit _[1af81fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1af81fdf1c9f43338dbd9284569b1d5312e29f18)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230121136401-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aw45t91Jx1l88ANl%2BAsDhbdV2sF6xhreiAyxFzdTpak%3D&st=2021-01-23T01%3A17%3A29Z&se=2021-02-23T01%3A22%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 01:22 UTC, Lauragra commented on api-reference/beta/resources/usageright.md
> +title: "UsageRight resource type"
Global: Please make sure you use lower camel case for resource names.

2021-01-23 01:25 UTC, opbld34 commented
Docs Build status updates of commit _[c558da8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c558da8b5be5d46b62e42e96a0922aecbf306afa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230124177939-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5FttR7l4fqpacKGDHU5q%2B2r0D2lRbB2%2FiV1zMVz4Xt4%3D&st=2021-01-23T01%3A20%3A34Z&se=2021-02-23T01%3A25%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 01:27 UTC, Lauragra commented on concepts/changelog.md
> +### Identity and access | Directory management
FYI, you no longer need to update the changelog.md file; just the JSON changelog update is required now.

2021-01-23 02:59 UTC, opbld34 commented
Docs Build status updates of commit _[4084c5d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4084c5dcde0089622d8ca8d63be81d7cd1c60280)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/device-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/device-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/api/user-list-usagerights.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/api/user-list-usagerights.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/user-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/device.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/device.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/usageright.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/usageright.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usageright?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/device-list-usagerights?view=graph-rest-beta&branch=pr-en-us-11214) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-05-usagerights-init/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11214) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230257472680-11214%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TD2OH65LdOENNz5ns2h2Px9WKpaZfXsl27Hrc%2B26tX8%3D&st=2021-01-23T02%3A53%3A59Z&se=2021-02-23T02%3A58%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 03:06 UTC, Lauragra approved these changes

2021-01-23 03:07 UTC, merged