Notification content type branch
microsoftgraph/microsoft-graph-docs pull request #11217
Opened 2021-01-07 10:42 UTC by Jumaodhiss

2021-01-07 10:44 UTC, opbld33 commented
Docs Build status updates of commit _[3efd861](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3efd86142e7b2aac50eeb0c1867428a4351492c7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-03ee596d)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-03ee596d)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-03ee596d)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |

<a id="8f8d1d71-03ee596d"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-03ee596d"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-03ee596d"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101071043027009-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ThbM%2BSMCyqK4QY3U1EZRJmE1Jokj4%2FL3gkxIfneuV3Y%3D&st=2021-01-07T10%3A39%3A20Z&se=2021-02-07T10%3A44%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help- [...]

2021-01-07 10:48 UTC, opbld32 commented
Docs Build status updates of commit _[b31746d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b31746d624511cbe6f19a358a7af883a4e94807a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-a4faa894)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-a4faa894)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-a4faa894)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |

<a id="8f8d1d71-a4faa894"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-a4faa894"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-a4faa894"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101071047144091-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZXHDSJ%2F5kEFKVziGaXInOvhGq6Pv9HBT4miG8zCEEVg%3D&st=2021-01-07T10%3A43%3A22Z&se=2021-02-07T10%3A48%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-do [...]

2021-01-07 17:13 UTC, opbld30 commented
Docs Build status updates of commit _[e8a8a92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8a8a92ac526335b370f8160eb4fe1a827976174)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-1bdecfa3)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-1bdecfa3)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-1bdecfa3)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |

<a id="8f8d1d71-1bdecfa3"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-1bdecfa3"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-1bdecfa3"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101071711509286-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AezK7PgazGvYQF0ryLclBCY3vra8S78f0sXjIpGq0Ns%3D&st=2021-01-07T17%3A08%3A00Z&se=2021-02-07T17%3A13%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs [...]

2021-01-07 17:24 UTC, opbld31 commented
Docs Build status updates of commit _[78541f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/78541f036bb3ed3c4085b29bc3321f5c90667534)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-69825fde-aaf84124)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-642cd3a0-aaf84124)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-aaf84124)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-aaf84124)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-aaf84124)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |

<a id="69825fde-aaf84124"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="642cd3a0-aaf84124"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-aaf84124"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-aaf84124"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-aaf84124"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md)
 - **Line  [...]

2021-01-07 17:46 UTC, baywet requested changes
On top of the comments I made, the changelog entry is missing

2021-01-07 17:46 UTC, baywet commented on api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md
> +[subscription setNotificationContentType:"application/json"];
@Jumaodhiss no need to update the code sample, just the http snippets. The code samples are generated autoamtically from the http snippets

2021-01-07 17:46 UTC, baywet commented on api-reference/beta/api/subscription-get.md
> +  "notificationContentType": "application/json"
@Jumaodhiss I can't find any reference of this property in the schema. But I'm guessing you're putting this PR together for the API review?

2021-01-07 17:52 UTC, Jumaodhiss commented on api-reference/beta/api/subscription-get.md
> +  "notificationContentType": "application/json"
Yes this is for the API review

2021-01-07 17:54 UTC, Jumaodhiss commented on api-reference/beta/api/subscription-get.md
> +  "notificationContentType": "application/json"
@baywet The API review is already completed. This is required for publishing the schema

2021-01-07 18:21 UTC, Jumaodhiss commented on api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md
> +[subscription setNotificationContentType:"application/json"];
Thanks @baywet. I wasn't aware. Should we remove this change and let it be generated automatically

2021-01-07 19:09 UTC, opbld34 commented
Docs Build status updates of commit _[bf51226](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf5122647da232b4f7c2b42a00297d0220de2c88)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-69825fde-75b58a14)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-642cd3a0-75b58a14)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-75b58a14)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-75b58a14)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-75b58a14)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11217) |

<a id="69825fde-75b58a14"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="642cd3a0-75b58a14"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-75b58a14"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-75b58a14"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://revi [...]

2021-01-07 19:14 UTC, Jumaodhiss commented
I've added the entries into the changelog as well

2021-01-07 19:43 UTC, baywet approved these changes

2021-01-08 12:11 UTC, opbld33 commented
Docs Build status updates of commit _[cc5a151](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc5a15129a40d280cf07dc7cf6430b2fcb0690bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-05fd620a)

<a id="05fd620a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101081210444870-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WvRAyZ6hc8Z0mWf6Ipx%2FiROAox7KSIDqKqr7iLKQyZo%3D&st=2021-01-08T12%3A06%3A06Z&se=2021-02-08T12%3A11%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 12:13 UTC, opbld34 commented
Docs Build status updates of commit _[bd453d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd453d8fe1c11088147af32e824619cc7054ce53)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bd28e636)

<a id="bd28e636"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101081212158586-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hOlLY68oPYKng1qe1Kfjr7OI6LDBBA%2FMLSJe8C%2BwDnc%3D&st=2021-01-08T12%3A08%3A21Z&se=2021-02-08T12%3A13%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-08 13:05 UTC, opbld31 commented
Docs Build status updates of commit _[27d6bc5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/27d6bc5f99abf2efad233a9eb94f3ba5756bcbc2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-69825fde-c6d4dee7)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-642cd3a0-c6d4dee7)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-c6d4dee7)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-c6d4dee7)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-c6d4dee7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11217) | [Details](#user-content-de0bbbbb-c6d4dee7)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="69825fde-c6d4dee7"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="642cd3a0-c6d4dee7"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-c6d4dee7"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-c6d4dee7"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod- [...]

2021-01-11 17:32 UTC, opbld34 commented
Docs Build status updates of commit _[5d9c4a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d9c4a45905c0f3155ab5bd3bafc92d03b96ab81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-69825fde-4b121e83)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-642cd3a0-4b121e83)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-4b121e83)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-4b121e83)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-4b121e83)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11217) |

<a id="69825fde-4b121e83"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="642cd3a0-4b121e83"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-4b121e83"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-4b121e83"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://revi [...]

2021-01-11 19:40 UTC, davidmu1 commented on api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md
>  [subscription setExpirationDateTime: "2016-11-20T18:23:45.9356913Z"];
The code snippets should not be changed. They are automatically generated on a weekly bases.

2021-01-11 19:41 UTC, davidmu1 approved these changes

2021-01-12 15:19 UTC, opbld30 commented
Docs Build status updates of commit _[f88bcb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f88bcb461288a90b4b953aac38bda7d77ef16b56)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-203c1eab)

<a id="203c1eab"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121519018198-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aHXTNleyD153q6mMsC7xxJFv54dYqK5EHhVU5yQW%2Bzc%3D&st=2021-01-12T15%3A14%3A20Z&se=2021-02-12T15%3A19%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-12 15:36 UTC, opbld34 commented
Docs Build status updates of commit _[6b63b5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b63b5a11a1e2dbd23f304009ad6abb9a0476ba2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-69825fde-02309935)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-642cd3a0-02309935)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-8f8d1d71-02309935)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-a8c89eee-02309935)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) | [Details](#user-content-409b84f8-02309935)
[api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/csharp/create-subscription-from-subscriptions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/java/create-subscription-from-subscriptions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/javascript/create-subscription-from-subscriptions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/includes/snippets/objc/create-subscription-from-subscriptions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[api-reference/beta/resources/changenotification.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/resources/changenotification.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/changenotification?view=graph-rest-beta&branch=pr-en-us-11217) (graph-rest-beta) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11217) |
[concepts/changelog.md.bak](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog.md.bak) | :white_check_mark:Succeeded | |
[concepts/changelog.md.orig](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog.md.orig) | :white_check_mark:Succeeded | |
[concepts/changelog_REMOTE_1435.md.bak](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/concepts/changelog_REMOTE_1435.md.bak) | :white_check_mark:Succeeded | |

<a id="69825fde-02309935"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="642cd3a0-02309935"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-02309935"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationContentTypeBranch/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud servic [...]

2021-03-04 18:52 UTC, opbld30 commented
Docs Build status updates of commit _[f0d893c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f0d893c143c7c67944c67ad79465252bca2bfbea)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-3929c360)

<a id="3929c360"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103041851492437-11217%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=neLbvx667xM9%2BbIB761VfadL6EOaz5E1eMWL33cFkqU%3D&st=2021-03-04T18%3A47%3A14Z&se=2021-04-04T18%3A52%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 11:03 UTC, closed without merging