Add and update UP related webhook notification docs
microsoftgraph/microsoft-graph-docs pull request #11226
Opened 2021-01-08 03:01 UTC by jahsu-MSFT

2021-01-08 03:01 UTC, opbld31 commented
Docs Build status updates of commit _[b05b04d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b05b04d4cd2412567399e563cb27917e2291042e)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 03:03 UTC, opbld33 commented
Docs Build status updates of commit _[f2838dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2838dc0351680e1cf5168eaaf09c36bd2fec74c)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 03:03 UTC, opbld33 commented
Docs Build status updates of commit _[b05b04d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b05b04d4cd2412567399e563cb27917e2291042e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-9e0e866c)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-9e0e866c)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-9e0e866c)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-9e0e866c)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-b329d26c-9e0e866c)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11226) | [Details](#user-content-2ec827c4-9e0e866c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-9e0e866c)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-9e0e866c)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |

<a id="69825fde-9e0e866c"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-9e0e866c"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-9e0e866c"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-9e0e866c"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b329d26c-9e0e866c"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml)
 - **Line 197, Column 23**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'universal-print-webhook-notifications.md'.`````

<a id="2ec827c4-9e0e866c"></a>
### [concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-concept-overview.md)
 - **Line 2, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?bran [...]

2021-01-08 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[f584a6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f584a6b72a785281a2c0f81854c150a6e2aff854)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 03:05 UTC, opbld32 commented
Docs Build status updates of commit _[f2838dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f2838dc0351680e1cf5168eaaf09c36bd2fec74c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-61817057)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-61817057)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-61817057)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-61817057)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11226) | [Details](#user-content-2ec827c4-61817057)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-61817057)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-61817057)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-61817057)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-61817057"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-61817057"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-61817057"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-61817057"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2ec827c4-61817057"></a>
### [concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-concept-overview.md)
 - **Line 2, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': ' [...]

2021-01-08 03:06 UTC, opbld34 commented
Docs Build status updates of commit _[f584a6b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f584a6b72a785281a2c0f81854c150a6e2aff854)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-c0b396d0)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-c0b396d0)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-c0b396d0)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-c0b396d0)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-c0b396d0)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-c0b396d0)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-c0b396d0)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-c0b396d0"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-c0b396d0"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-c0b396d0"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-c0b396d0"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-c0b396d0"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 10, Column 1**: **[Warning-[h1-empty](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-empty?branch=main)]** `````H1 is required. Add content to your top-level heading.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal#register-an-application-with-azure-ad-and-create-a-service-principal' contains locale code 'en-us'. For localizability, re [...]

2021-01-08 03:08 UTC, opbld31 commented
Docs Build status updates of commit _[538f4eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/538f4ebf011a6228b6a290f7d72d97b7d3debb9f)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 03:09 UTC, opbld32 commented
Docs Build status updates of commit _[538f4eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/538f4ebf011a6228b6a290f7d72d97b7d3debb9f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-6b05f23a)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-6b05f23a)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-6b05f23a)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-6b05f23a)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-6b05f23a)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-6b05f23a)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-6b05f23a)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-6b05f23a"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-6b05f23a"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-6b05f23a"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-6b05f23a"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-6b05f23a"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'jahsu/saurabhb/nilakhan' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 10, Column 1**: **[Warning-[h1-empty](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-empty?branch=main)]** `````H1 is required. Add content to your top-level heading.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main) [...]

2021-01-08 03:16 UTC, opbld30 commented
Docs Build status updates of commit _[0970be1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0970be1f5cf12f9ec5411997530d903a6c406ca4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-3fb71832)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-3fb71832)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-3fb71832)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-3fb71832)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-3fb71832)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-3fb71832)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-3fb71832)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-3fb71832"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-3fb71832"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-3fb71832"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-3fb71832"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-3fb71832"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'jahsu/saurabhb/nilakhan' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 10, Column 1**: **[Warning-[h1-empty](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-empty?branch=main)]** `````H1 is required. Add content to your top-level heading.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main) [...]

2021-01-08 06:24 UTC, esaurabhb-ms commented on api-reference/beta/resources/subscription.md
> +- A [printer][] in Print Service
Can we be more explicit? Something like:
A printer in Print Service (when a print job for the printer gets to JobFetchable state - ready to be fetched for printing).

2021-01-08 06:34 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +For printTask triggered (JobStarted) event: Same as permissions to [get printTaskDefinition resource](/graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%2
Can this be in bullet (list item)?

2021-01-08 06:35 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +For JobFetchable event: Printer.Read.All or Printer.ReadWrite.All.
Lets have this also as a list item.. Instead of listing the permissions, can we just point to the permissions table in create subscription?

2021-01-08 06:37 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +Authorization: Bearer <Azure AD security token>
In other Graph documentation I noticed they use curly brackets {} instead of <>. Should we just be consistent with other documentation?

2021-01-08 06:40 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +* resource field needs to be set as “print/taskDefinitions/<printTaskDefinition ID>/tasks”.
Can we have highlight field names (resource, changeType, expirationDateTime) as italics or inside ``?

Replace <> with {}

2021-01-08 06:41 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +* [changeType]{/graph/api/resources/subscription?view=graph-rest-beta#properties} field needs to be set as “created”.
Link here doesnt show up correctly in preview - please fix it.

2021-01-08 06:41 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "resource":"print/taskDefinitions/<printTaskDefinition ID>/tasks",
Replace <> with {}

2021-01-08 06:41 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "notificationUrl":"<URL for receiving the event – e.g. https://webhookappexample.azurewebsites.net/api/notifications>",
replace <> with {}

2021-01-08 06:42 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "id": "<Subscription ID>",
replace <> with {}

2021-01-08 06:42 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "resource": "print/taskDefinitions/<printTaskDefinition ID>/tasks",
replace <> with {}

2021-01-08 06:42 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "applicationId": "<application ID>",
replace <> with {}

2021-01-08 06:42 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "notificationUrl": "<URL for receiving the event – e.g. https://webhookappexample.azurewebsites.net/api/notifications>",
replace <> with {}

2021-01-08 06:42 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "creatorId": "<Creator ID>",
replace <> with {}

2021-01-08 06:43 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +* resource field needs to be set as “print/printers/<printer id>/jobs”
highlight field names as mentioned above

2021-01-08 06:44 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "resource":"print/printers/<printer id>/jobs",
replace <> with {}

2021-01-08 06:44 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "notificationUrl":"<URL for receiving the event – e.g. https://webhookappexample.azurewebsites.net/api/notifications>",
replace <> with {}

2021-01-08 06:44 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "id": "<Subscription ID>",
replace <> with {}

2021-01-08 06:44 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "applicationId": "<Application ID>",
replace <> with {}

2021-01-08 06:44 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "resource": "print/printers/<printer ID>/jobs",
replace <> with {}

2021-01-08 06:45 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "notificationUrl": "<URL for receiving the event – e.g. https://webhookappexample.azurewebsites.net/api/notifications>",
replace <> with {}

2021-01-08 06:45 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +    "creatorId": "<Creator ID>",
replace <> with {}

2021-01-08 06:50 UTC, esaurabhb-ms commented on concepts/universal-print-webhook-notifications.md
> +## Renewing notification subscription
I thought of adding one more section - something like FAQ with following questions:
1. Once we send a notification, what is expected? 
2. How should partner acknowledge it? 
3. if they dont acknowledge then how frequently do we resend notification? 
4. How many times do we resend before giving up or until how long do we keep retrying?
5. How to get list of active subscriptions?

2021-01-08 13:16 UTC, baywet requested changes
the printer resource pages are missing links to the webhook page to indicate it supports change notifications. See [this resource supports](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0)

2021-01-08 16:55 UTC, opbld34 commented
Docs Build status updates of commit _[9daea31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9daea313c1c2611921120d1b54bdba8d5e6170ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-4f4ad665)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-4f4ad665)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-4f4ad665)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-4f4ad665)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-4f4ad665)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-4f4ad665)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-4f4ad665)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-4f4ad665"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-4f4ad665"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-4f4ad665"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="409b84f8-4f4ad665"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-4f4ad665"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'jahsu/saurabhb/nilakhan' is not a valid GitHub ID.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 10, Column 1**: **[Warning-[h1-empty](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-empty?branch=main)]** `````H1 is required. Add content to your top-level heading.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main) [...]

2021-01-08 17:01 UTC, opbld31 commented
Docs Build status updates of commit _[dd1e89c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd1e89c75808ef3c3da2f7f9f349226f00f27f86)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-b9f4f93e)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-b9f4f93e)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-b9f4f93e)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-b9f4f93e)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-b9f4f93e)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-b9f4f93e)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-b9f4f93e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-b9f4f93e)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-b9f4f93e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-b9f4f93e"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-b9f4f93e"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-b9f4f93e"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-b9f4f93e"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-b9f4f93e"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-b9f4f93e"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 17:01 UTC, jahsu-MSFT commented
> the printer resource pages are missing links to the webhook page to indicate it supports change notifications. See [this resource supports](https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0)

Added links to the Webhook to indicate the notification support in printer and printTaskDefinition resources. Thanks.

2021-01-08 17:29 UTC, opbld31 commented
Docs Build status updates of commit _[c4dfb7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4dfb7f3d315902ad44a7f087ef9a96733b3dc60)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-29712694)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-29712694)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-29712694)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-29712694)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-29712694)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-29712694)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-29712694)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-29712694)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-29712694)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-29712694"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-29712694"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-29712694"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-29712694"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-29712694"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-29712694"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 17:31 UTC, opbld34 commented
Docs Build status updates of commit _[4493146](https://github.com/microsoftgraph/microsoft-graph-docs/commits/449314605071db6216e07489b58cf4f7e570336a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-fdd60fee)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-fdd60fee)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-fdd60fee)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-fdd60fee)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-fdd60fee)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-fdd60fee)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-fdd60fee)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-fdd60fee)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-fdd60fee)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-fdd60fee"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-fdd60fee"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-fdd60fee"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-fdd60fee"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-fdd60fee"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-fdd60fee"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 17:32 UTC, opbld30 commented
Docs Build status updates of commit _[cfb5ea0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cfb5ea0e9eb63c44bad238da0357d09d2b6470e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-2894c94c)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-2894c94c)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-2894c94c)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-2894c94c)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-2894c94c)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-2894c94c)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-2894c94c)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-2894c94c)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-2894c94c)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-2894c94c"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-2894c94c"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-2894c94c"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-2894c94c"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-2894c94c"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-2894c94c"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 18:15 UTC, opbld33 commented
Docs Build status updates of commit _[7292d93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7292d93f83ebc2177e6d18a3bf185ff245abfacf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-bbde4dc4)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-bbde4dc4)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-bbde4dc4)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-bbde4dc4)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-bbde4dc4)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-bbde4dc4)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-bbde4dc4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-bbde4dc4)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-bbde4dc4)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-bbde4dc4"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-bbde4dc4"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-bbde4dc4"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-bbde4dc4"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-bbde4dc4"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-bbde4dc4"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 18:17 UTC, opbld30 commented
Docs Build status updates of commit _[4673290](https://github.com/microsoftgraph/microsoft-graph-docs/commits/467329098cb9476deeb8486218c3822e0b5072b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-4c422297)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-4c422297)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-4c422297)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-4c422297)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-4c422297)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-4c422297)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-4c422297)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-4c422297)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-4c422297)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-4c422297"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-4c422297"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-4c422297"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-4c422297"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-4c422297"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-4c422297"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 18:18 UTC, opbld34 commented
Docs Build status updates of commit _[d843725](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d843725d2d7edcbed2b7183a8febe09e352d1362)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-445d6368)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-445d6368)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-445d6368)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-445d6368)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-445d6368)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-445d6368)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-445d6368)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-445d6368)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-445d6368)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-445d6368"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-445d6368"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-445d6368"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-445d6368"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-445d6368"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-445d6368"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 18:43 UTC, opbld31 commented
Docs Build status updates of commit _[3fe3a56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fe3a56ee76c92f2a6ed8b353e011664988a2d5b)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 18:45 UTC, opbld30 commented
Docs Build status updates of commit _[5c1e4b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c1e4b9bfb5bac8b7e13b881e32b193f0c10b198)_: 

:clock10: **Pending**: waiting for processors ([11](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 11 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-08 18:46 UTC, opbld31 commented
Docs Build status updates of commit _[3fe3a56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fe3a56ee76c92f2a6ed8b353e011664988a2d5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-eae8c497)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-eae8c497)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-eae8c497)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-eae8c497)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-eae8c497)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-eae8c497)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-eae8c497)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-eae8c497)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-eae8c497)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-eae8c497"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-eae8c497"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-eae8c497"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-eae8c497"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-eae8c497"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-eae8c497"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 18:49 UTC, opbld30 commented
Docs Build status updates of commit _[5c1e4b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c1e4b9bfb5bac8b7e13b881e32b193f0c10b198)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-667693a6)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-667693a6)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-667693a6)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-667693a6)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-667693a6)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-667693a6)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-667693a6)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-667693a6)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-667693a6)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-667693a6"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-667693a6"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-667693a6"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-667693a6"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-667693a6"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-667693a6"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-08 21:45 UTC, Lauragra commented on concepts/toc.yml
> +              - name: Webhook Notifications
The TOC title should be "Change notifications" because that's how we refer to it in the documentation, instead of webhooks.

2021-01-08 21:47 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +#
This article doesn't have an H1 title. How about this: "Subscribe to change notifications on cloud printing APIs using Microsoft Graph".

2021-01-08 21:47 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +author: "jahsu/saurabhb/nilakhan"
Please assign one author value.

2021-01-08 21:47 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +ms.prod: "universal-print"
Please use the new ms.prod value - "cloud-printing".

2021-01-08 22:30 UTC, opbld33 commented
Docs Build status updates of commit _[2d8112e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d8112e8b6347d6e9b9eb8d60e099484f12ca502)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-c50fb617)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-c50fb617)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-c50fb617)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-c50fb617)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-c50fb617)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-c50fb617)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-c50fb617)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-c50fb617)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-c50fb617)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-c50fb617"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-c50fb617"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-c50fb617"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-c50fb617"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-c50fb617"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-c50fb617"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-09 01:20 UTC, opbld30 commented
Docs Build status updates of commit _[2861aa1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2861aa1a4ec3bd477a7c364bfe0a3512df93b277)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-54a53436)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-54a53436)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-54a53436)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-54a53436)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-54a53436)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-54a53436)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-54a53436)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-54a53436)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-54a53436)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-54a53436"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-54a53436"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-54a53436"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-54a53436"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-54a53436"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-54a53436"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-09 01:37 UTC, opbld34 commented
Docs Build status updates of commit _[5347b40](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5347b40f24ca59daa47dece3bf63493d3f24a841)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-fd550d12)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-fd550d12)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-fd550d12)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-fd550d12)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-fd550d12)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-fd550d12)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-fd550d12)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-fd550d12)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-fd550d12)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-fd550d12"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-fd550d12"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-fd550d12"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-fd550d12"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-fd550d12"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-fd550d12"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-09 01:38 UTC, opbld31 commented
Docs Build status updates of commit _[7e8c1da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e8c1dad1e06768b99b9e7a81026820286cad3a7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-526c02a4)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-526c02a4)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-526c02a4)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-526c02a4)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-526c02a4)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-526c02a4)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-526c02a4)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-526c02a4)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-526c02a4)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-526c02a4"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-526c02a4"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-526c02a4"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-526c02a4"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-526c02a4"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-526c02a4"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-09 01:40 UTC, opbld31 commented
Docs Build status updates of commit _[c68b145](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c68b145c0b5f3323151336ca71a62619526ddd28)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-92f33f63)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-92f33f63)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-92f33f63)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-92f33f63)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-92f33f63)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-92f33f63)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-92f33f63)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-92f33f63)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-92f33f63)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-92f33f63"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-92f33f63"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-92f33f63"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-92f33f63"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-92f33f63"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-92f33f63"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-11 13:51 UTC, baywet requested changes

2021-01-11 13:51 UTC, baywet commented on api-reference/beta/resources/printer.md
> +* Subscribing to change notifications.
should include a relative link to the general webhook concept page

2021-01-11 13:51 UTC, baywet commented on api-reference/beta/resources/printtaskdefinition.md
> +* Subscribing to change notifications.
should include a link as well

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +[Use Change Notifications and Track Changes with Microsoft Graph](https://docs.microsoft.com/learn/modules/msgraph-changenotifications-trackchanges/)
@Lauragra shouldn't these links be relative?

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Body:
```suggestion
Content-type: application/json
```

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +```
```suggestion
```http
```
Adding those suggestions so the code generation process picks up the http snippet and generates equivalent snippet for CSharp, Java, Objc...

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Request:
```suggestion
```

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Here is an example code block:
```suggestion
Here is an example of the request.
# [HTTP](#tab/http)
<!-- {
  "blockType": "request",
  "name": "printtask_subscribe"
}--> 
```

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Response:
```suggestion
```
```

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +201 Created.
```suggestion
### Response

Here is an example of the response.

<!-- {
  "blockType": "response",
  "truncated": true
} -->
```http
HTTP/1.1 201 Created
Content-Type: application/json
```

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Body:
```suggestion
```

2021-01-11 13:51 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Request:
please repeat the changes I've made on the previous http snippet

2021-01-11 17:59 UTC, nilakhan requested changes

2021-01-11 17:59 UTC, nilakhan commented on concepts/universal-print-webhook-notifications.md
> +1. PrintTask is triggered (JobStarted): Partner can subscribe to receive notifications when their printTask(hook) is triggered. Currently, printTask can be triggered only for JobStarted event. JobSta
Suggestion: 

1. PrintTask is triggered (JobStarted): Partner can subscribe to receive notifications when their printTask(hook) is triggered.
For details about how to trigger task, see [Extending Universal Print to support pull printing](/graph/universal-print-concept-overview#extending-universal-print-to-support-pull-printing).
Currently, printTask can be triggered only for JobStarted event. JobStarted event is raised when a print job has been successfully created, payload has been uploaded and job processing has started.

2021-01-11 17:59 UTC, nilakhan commented on concepts/universal-print-webhook-notifications.md
> +1. Created a [printTaskDefinition](/graph/api/print-post-taskdefinitions?view=graph-rest-beta&tabs=http)  for the customer’s Azure AD tenant. Single task definition may be associated with one or more
withing => within

2021-01-11 17:59 UTC, nilakhan commented on concepts/universal-print-webhook-notifications.md
> +POST https://graph.microsoft.com/beta//subscriptions
POST https://graph.microsoft.com/beta//subscriptions =>
POST https://graph.microsoft.com/beta/subscriptions

2021-01-11 18:17 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +Body:
A sample header is already provided. Here we are providing a sample request body.

2021-01-11 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[0a2d4c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a2d4c1d0ee972f7e5acfd667ad0369aa5e3bf15)_: 

:clock10: **Pending**: waiting for processors ([7](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 7 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-11 18:33 UTC, opbld30 commented
Docs Build status updates of commit _[6e5d930](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e5d930bc7bb66a7b53330cfefbea3fb3738c297)_: 

:clock10: **Pending**: waiting for processors ([10](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 10 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-11 18:33 UTC, opbld30 commented
Docs Build status updates of commit _[0a2d4c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a2d4c1d0ee972f7e5acfd667ad0369aa5e3bf15)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-190f4444)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-190f4444)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-190f4444)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-190f4444)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-190f4444)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-190f4444)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-190f4444)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-190f4444)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-190f4444)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-190f4444"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-190f4444"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-190f4444"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-190f4444"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-190f4444"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-190f4444"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-11 18:34 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +Body:
Ah I see. These are for the styling. didn't know there are pre-defined formats. Thanks.

2021-01-11 18:35 UTC, baywet requested changes

2021-01-11 18:35 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Body:
```suggestion
Content-Type: application/json
```

2021-01-11 18:35 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +    "includeProperties": null,
```suggestion
```

2021-01-11 18:35 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +    "includeProperties": null,
```suggestion
```

2021-01-11 18:35 UTC, baywet commented on concepts/universal-print-webhook-notifications.md
> +Authorization: Bearer {Azure AD security token}
I don't think it's necessary to include that. The core concepts of the Microsoft Graph documentation already cover auth

2021-01-11 18:39 UTC, opbld32 commented
Docs Build status updates of commit _[6e5d930](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e5d930bc7bb66a7b53330cfefbea3fb3738c297)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-078ac949)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-078ac949)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-078ac949)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-078ac949)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-078ac949)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-078ac949)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-078ac949)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-078ac949)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-078ac949)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-078ac949"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-078ac949"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-078ac949"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-078ac949"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-078ac949"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-078ac949"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-11 18:43 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +Authorization: Bearer {Azure AD security token}
I kinda agree on this.

2021-01-11 18:44 UTC, opbld34 commented
Docs Build status updates of commit _[6435d70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6435d70ec2aa53c2ff5553123481dc99402e1934)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-ac770db9)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-ac770db9)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-ac770db9)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-ac770db9)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-ac770db9)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-ac770db9)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-ac770db9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-ac770db9)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-ac770db9)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-ac770db9"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-ac770db9"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-ac770db9"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-ac770db9"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-ac770db9"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-ac770db9"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-11 19:15 UTC, baywet approved these changes

2021-01-11 19:17 UTC, opbld33 commented
Docs Build status updates of commit _[eae27a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eae27a492864aadd0f79bac1abb1336ebda85267)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-7213240e)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-7213240e)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-7213240e)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-7213240e)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-7213240e)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-7213240e)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-7213240e)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-7213240e)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-7213240e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-7213240e"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-7213240e"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-7213240e"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-7213240e"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-7213240e"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-7213240e"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-11 23:15 UTC, braedenp-msft requested changes
Left some mostly grammatical comments. Looks good!

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +For details about how to trigger task, see [Extending Universal Print to support pull printing](/graph/universal-print-concept-overview#extending-universal-print-to-support-pull-printing). Currently,
"A JobStarted event is raised when a print job has been successfully created, its payload has been uploaded, and job processing has started."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +2. JobFetchable: After the job has started, there might be processing done by third-party print applications or by Universal Print itself (like converting XPS payload to PDF for a PDF printer). Once
"Once processing is complete and the payload is ready to be downloaded by a printer, a JobFetchable event is raised for the corresponding print job."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +For adding the ability to listen to Microsoft Graph notifications, you may refer to the documentation that provides steps and example codes.
"For more information about how to listen for Microsoft Graph notifications, see [Use Change Notifications and Track Changes with Microsoft Graph](https://docs.microsoft.com/learn/modules/msgraph-changenotifications-trackchanges/) and [Set up notifications for changes in user data – Code Samples](https://docs.microsoft.com/graph/webhooks#code-samples)."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +Vendor applications must [generate and use the Azure AD security token](/graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta) in the Microsoft Graph API request header. The security
"Applications" instead of "Vendor applications"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +2. Created [printTaskTrigger](/graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http) for each of the printer queues for which partner wishes to receive notification when a new print job
"Created a..."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +2. Created [printTaskTrigger](/graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http) for each of the printer queues for which partner wishes to receive notification when a new print job
"partner wishes to receive a notification"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +There are cloud applications that need to download print jobs from Universal Print when they are ready. Since these applications are running in cloud and are not behind the customer’s firewall, they
"running in the cloud"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +Please note that print job may not be modified when it is in the JobFetchable state.
"Please note that print jobs may not be modified once they enter the JobFetchable state."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +JobFetchable notification need to be created for each printer queue. While creating the subscription,
"A JobFetchable notification needs to be created for each printer queue"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +Microsoft Graph has a limit on the expiration time. Please refer to the [maximum expiration time](/graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-ty
"To continue receiving notifications, the subscription needs to be renewed periodically by using the..."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +Application may [get](/graph/api/subscription-get?view=graph-rest-beta&tabs=http) details of the subscription or may [delete](/graph/api/subscription-delete?view=graph-rest-beta&tabs=http) a subscrip
"Applications" plural

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +We are happy to help you move your existing solutions to cloud or bring new innovations to the market that will redefine printing for organizations. If you have any new ideas or feedback on the curre
I'd remove the first sentence in this paragraph. Just have:

"If you have any new ideas or feedback on the Universal Print Microsoft Graph API, please reach out via the [Universal Print Tech Community](https://aka.ms/community/UniversalPrint)."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +1. How is notification url validated by Microsoft Graph?
"How does Microsoft Graph validate notification URLs?"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +2. Once we send a notification, what is expected and how should partner acknowledge it?
"What are applications expected to do after receiving a change notification?"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +> Your process should process every change notification it receives. For minimum tasks that the application must perform to process a change notification, refer to [Processing the change notification
"Applications should process and acknowledge every change notification they receive. See [Processing change notifications](/graph/webhooks#processing-the-change-notification) for more details."

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +2. How to get list of active subscriptions?
"How can I get a list of active subscriptions?"

2021-01-11 23:15 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +> Retrieve a list of webhook subscriptions. Refer to the [Processing the change notification](/graph/api/subscription-list?view=graph-rest-beta&tabs=http) for more details.
"See [Processing the change notification](/graph/api/subscription-list?view=graph-rest-beta&tabs=http) for details about listing webhook notifications"

And is the above link correct?

2021-01-12 17:29 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +# Subscribe to change notifications on cloud printing APIs using Microsoft Graph
The name of the title is suggested by @Lauragra and I think "Subscribe to change notifications" is consistent with how it is described in Webhook notification doc or maybe I missed something?

2021-01-12 17:32 UTC, braedenp-msft commented on concepts/universal-print-webhook-notifications.md
> +# Subscribe to change notifications on cloud printing APIs using Microsoft Graph
Ah, GitHub doesn't show the exact word I highlighted like ADO does. I was referring to "from cloud printing APIs" instead of "on cloud printing APIs"

2021-01-12 17:41 UTC, opbld30 commented
Docs Build status updates of commit _[3b132c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b132c55752cc414a0ba0e0364a233896892d925)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-062153e7)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-062153e7)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-062153e7)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-062153e7)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-062153e7)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-062153e7)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-062153e7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-062153e7)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-062153e7)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-062153e7"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-062153e7"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-062153e7"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-062153e7"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-062153e7"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-062153e7"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-12 17:52 UTC, opbld34 commented
Docs Build status updates of commit _[3565472](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3565472a30bd22a733cc92d61e457117f81f9282)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-601dd146)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-601dd146)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-601dd146)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-601dd146)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-601dd146)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-601dd146)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-601dd146)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) | [Details](#user-content-de0bbbbb-601dd146)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-601dd146)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |

<a id="69825fde-601dd146"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-601dd146"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-601dd146"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-601dd146"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-601dd146"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-601dd146"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph [...]

2021-01-15 19:50 UTC, opbld30 commented
Docs Build status updates of commit _[6fa842d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fa842dbbea42427e3416ff366556f0aa649bed3)_: 

:clock10: **Pending**: waiting for processors ([41](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 41 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-15 19:53 UTC, opbld30 commented
Docs Build status updates of commit _[6fa842d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6fa842dbbea42427e3416ff366556f0aa649bed3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-89405117)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-89405117)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-89405117)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-89405117)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-89405117)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-89405117)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-89405117)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-89405117)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11226) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="69825fde-89405117"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-89405117"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-89405117"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-89405117"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-89405117"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-89405117"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/mic [...]

2021-01-20 05:17 UTC, opbld32 commented
Docs Build status updates of commit _[b9f8b7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9f8b7f4a7edfddd5f1660df8697cafe13a85d4f)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-20 05:19 UTC, opbld32 commented
Docs Build status updates of commit _[b9f8b7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9f8b7f4a7edfddd5f1660df8697cafe13a85d4f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-0f0dc9cc)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-0f0dc9cc)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-0f0dc9cc)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-0f0dc9cc)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-0f0dc9cc)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-0f0dc9cc)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-0f0dc9cc)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-0f0dc9cc)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="69825fde-0f0dc9cc"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-0f0dc9cc"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-0f0dc9cc"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-0f0dc9cc"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-0f0dc9cc"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-0f0dc9cc"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webh [...]

2021-01-20 17:26 UTC, nilakhan approved these changes

2021-01-21 03:40 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +title: "Universal Print job notifications using Microsoft Graph APIs"
The title attribute should match the H1 title.

2021-01-21 03:42 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +description: "Universal Print is a modern print solution that organizations can use to manage their print infrastructure through cloud services from Microsoft."
Because this is a concept topic, you might want to tailor your description here to give the intent of the article. This text can show up in search results so you'll want the reader to know the primary intent of the article. For example, "Learn how to subscribe to change notifications for print jobs by using the Microsoft Graph API."

2021-01-21 03:43 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Universal Print helps customers move their print infrastructure to the cloud, and is part of a robust ecosystem of partner solutions that offer advanced print functionality. These solutions can becom
I recommend revising the second sentence as: "These solutions can become even more powerful when you use the cloud printing APIs in Microsoft Graph to integrate with Universal Print."

2021-01-21 03:44 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +In this article, we describe how to subscribe to notifications for various print job events.
Avoid using the first person plural construction (we), per Microsoft Voice guidelines. You can say "This article describes how to...".

2021-01-21 03:45 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +## Getting Started
We use sentence case for headings, so this would be "Get started". Also note that imperatives are generally easier to read and localize than gerunds.

2021-01-21 03:48 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Before leveraging the notification functionality via Microsoft Graph, an application needs to be [registered in Azure](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-ser
Avoid the word "leveraging" as it's jargon. Can we make this an active construction, i.e. "Before you can take advantage of change notifications via Microsoft Graph, you must register your application in Azure and provision your application in the customers Azure Active Directory (Azure AD) tenant. Make sure that the application has the required permission scopes enabled, as described later in this article." It would be helpful to provide a link to the permissions section. Also note that links to articles on Docs should be relative, not absolute, so delete this part of the URL: https://docs.microsoft.com/en-us

2021-01-21 03:49 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +### Notifications and subscriptions
Should this be an H2? It doesn't seem like it's part of Get started.

2021-01-21 03:49 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +1. PrintTask is triggered (JobStarted): An application can subscribe to receive notifications when their printTask(hook) is triggered.
Unless these are ordered steps, this should be a bulleted list.

2021-01-21 03:51 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +For details about how to trigger a task, see [Extending Universal Print to support pull printing](/graph/universal-print-concept-overview#extending-universal-print-to-support-pull-printing). Currentl
Note that resource names are formatted as bold. Please include the article "a" before JobStarted in the second sentence.

2021-01-21 03:52 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +2. JobFetchable: After the job has started, there might be processing done by third-party print applications or by Universal Print itself (like converting XPS payload to PDF for a PDF printer). Once
Revise as: "After the job has started, third-party print applications or Universal Print might do some processing (like...
". After processing...

2021-01-21 03:53 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +### Create an application to listen to notifications
Global: I think all these H3 sections should be elevated to H2s so that they are peers of and not children under Get started.

2021-01-21 03:53 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +For more information about how to listen for Microsoft Graph notifications, see [Use Change Notifications and Track Changes with Microsoft Graph](https://docs.microsoft.com/learn/modules/msgraph-chan
Make these relative links.

2021-01-21 03:54 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +* For printTask triggered (JobStarted) event: Same as permissions to [get printTaskDefinition resource](/graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22
Can/should we list the permissions here instead of linking to the method topics? That way the user can get the required information without having to click, esp if we're adding a link to this section from Get started (then it would be two clicks).

2021-01-21 03:55 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Some applications monitor print queues for incoming jobs and want to be notified as soon as there is a valid job in the queue. Once notified they can collect the relevant job metadata or even perform
Change "Once" to "After" per Microsoft Voice - once has a different meaning (i.e. one time) and it's therefore ambiguous to use it to mean "after".

2021-01-21 03:56 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +With the printTaskDefinition that exists for customer’s Azure AD tenant, application may [create subscription for printTask triggered (JobStarted) event using the printTaskDefinition](/graph/api/subs
Change the comma to a colon; bulleted lists are introduced with a colon.

2021-01-21 03:57 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Refer to [Subscription resource type properties](/graph/api/resources/subscription?view=graph-rest-beta#properties) for more details.
For consistency, please recast as "For more details, see..."

2021-01-21 03:57 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +# [HTTP](#tab/http)
Please remove this H1.

2021-01-21 03:58 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +There are cloud applications that need to download print jobs from Universal Print when they are ready. Since these applications running in the cloud are not behind the customer’s firewall, they can
Revise as "Some cloud applications need to download print jobs from Universal Print when they are ready. Because these applications running in the cloud are not behind the customer's firewall, they can use Microsoft Graph change notifications to be notified when a print job is ready to be downloaded."

2021-01-21 03:59 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Please note that print jobs may not be modified once they enter the JobFetchable state.
Revise as: "Note that print jobs can't be modified when they ender the JobFetchable state." Should this be formatted as a note to call attention to the reader?

2021-01-21 03:59 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +A JobFetchable notification needs to be created for each printer queue. While creating the subscription,
Change the comma to a colon.

2021-01-21 04:00 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +* `resource` field needs to be set as “print/printers/{printer id}/jobs”
Please use the tic formatting instead of quotes, and end each bulleted item with a period.

2021-01-21 04:00 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Refer to [Subscription resource type properties](/graph/api/resources/subscription?view=graph-rest-beta#properties) for more details.
Make the same revision here.

2021-01-21 04:00 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +# [HTTP](#tab/http)
Deleted.

2021-01-21 04:00 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Microsoft Graph has a limit on the expiration time. Please refer to the [maximum expiration time](/graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-ty
Revise the second sentence as "For details, see [maximum expiration time]."

2021-01-21 04:01 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +Applications may [get](/graph/api/subscription-get?view=graph-rest-beta&tabs=http) details of the subscription or may [delete](/graph/api/subscription-delete?view=graph-rest-beta&tabs=http) a subscri
Change may to can - may implies permission. Revise the second sentence for consistency.

2021-01-21 04:02 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +## Other Resources
We use ## See also for this section; please update for consistency.

2021-01-21 04:04 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +To get details on specific print APIs, please start with [Microsoft Graph API documentation for Universal Print](https://aka.ms/UPGraphDocs).
Revise as "To learn more about the cloud printing API in Microsoft Graph, see [cloud printing API overview]."

2021-01-21 04:05 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +If you have any new ideas or feedback on the Universal Print Microsoft Graph API, please reach out via the [Universal Print tech community](https://aka.ms/community/UniversalPrint).
Revise as "For suggestions or feedback about the cloud printing API in Microsoft Graph, visit the [tech community]." Does the tech community target developers?

2021-01-21 04:06 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +## FAQ
Please move the FAQ section to come before the See also section. Name the section "FAQs", and each question should be an H3. The answers can be normal text rather than formatted as a note.

2021-01-21 04:06 UTC, Lauragra requested changes
Please see editorial feedback.

2021-01-21 04:38 UTC, opbld32 commented
Docs Build status updates of commit _[a12e3b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a12e3b631d184d57f870d9328da55cf62c56c4a2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f51ddad2)

<a id="f51ddad2"></a>
###
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101210437373453-11226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D%2BEQhq61P2u%2Bj81LI1ptlqZxTUF5EyIUZ3JNgf%2BIcbU%3D&st=2021-01-21T04%3A33%3A56Z&se=2021-02-21T04%3A38%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 04:51 UTC, opbld31 commented
Docs Build status updates of commit _[6788987](https://github.com/microsoftgraph/microsoft-graph-docs/commits/678898739cdc53e063b779aec94f09fac2913cbb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-61f23e08)

<a id="61f23e08"></a>
###
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101210451268128-11226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q%2FmH3yNBgv5viRC8%2Fe6EsmOgHVCkWB4iN1ck8QBbprY%3D&st=2021-01-21T04%3A46%3A58Z&se=2021-02-21T04%3A51%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 04:53 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +If you have any new ideas or feedback on the Universal Print Microsoft Graph API, please reach out via the [Universal Print tech community](https://aka.ms/community/UniversalPrint).
Yeah, it targets mostly developers or people with technical background.

2021-01-21 04:59 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +* For printTask triggered (JobStarted) event: Same as permissions to [get printTaskDefinition resource](/graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22
Our intention was that, by referring to the resource doc, if we update one place, then we don't need to update these two places and we can avoid potential inconsistency in these two docs as well.

2021-01-21 05:01 UTC, opbld34 commented
Docs Build status updates of commit _[138bda2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/138bda20b8688114f5a140149152b6bdffc98f68)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-76e39dc0)

<a id="76e39dc0"></a>
###
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101210500388773-11226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1K%2BrVRi0ItiFie1vyD4fD4kbNWvRJScaU1ctta27RFw%3D&st=2021-01-21T04%3A56%3A27Z&se=2021-02-21T05%3A01%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 05:07 UTC, opbld33 commented
Docs Build status updates of commit _[8a60c5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a60c5ce7ff957445b544c8e7897ba4c866bf16b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-88ae8196)

<a id="88ae8196"></a>
###
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````
 - **Line 0, Column 0**: **[Error-restore-dependent-repository-failed]** `````Failed to restore dependent repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). If it is not the case, please open a ticket in https://SiteHelp and include URL of the build report.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101210506500956-11226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UQ2bM0IOsyU%2BIfwmDsgl1%2FKFK6Sye9bHacjE8Mq3pB0%3D&st=2021-01-21T05%3A02%3A30Z&se=2021-02-21T05%3A07%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 05:09 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +### Notifications and subscriptions
I think "Notifications and subscriptions", "Create an application to listen to notifications", and "Scopes" sections are more of an overview and prerequisites before creating a Webhook subscription (for subscribing a notification).

2021-01-21 05:10 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +### Create an application to listen to notifications
Same as comment above - I think "Notifications and subscriptions", "Create an application to listen to notifications", and "Scopes" sections are more of an overview and prerequisites before creating a Webhook subscription (for subscribing a notification).

2021-01-21 05:12 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +* `resource` field needs to be set as “print/printers/{printer id}/jobs”
tic formatting?

2021-01-21 17:35 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +For more information about how to listen for Microsoft Graph notifications, see [Use Change Notifications and Track Changes with Microsoft Graph](https://docs.microsoft.com/learn/modules/msgraph-chan
For https://docs.microsoft.com/learn/modules/msgraph-changenotifications-trackchanges/, it's not in graph. Would relative links work?

2021-01-22 01:10 UTC, opbld31 commented
Docs Build status updates of commit _[e7670f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7670f0ce8246d7fb1d1b8fa4d61b6b8e332a155)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b310703f)

<a id="b310703f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101220110079956-11226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QtGhCnuxYbPJwIQYCHl%2BlM0L12UZw8DtE8WPclHJmJc%3D&st=2021-01-22T01%3A05%3A27Z&se=2021-02-22T01%3A10%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 01:10 UTC, opbld30 commented
Docs Build status updates of commit _[e7670f0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e7670f0ce8246d7fb1d1b8fa4d61b6b8e332a155)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1ef2d4c9)

<a id="1ef2d4c9"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101220110185677-11226%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3CPRUD5VsmqYST3%2F2MLd2nNDSIgLViZ6MR6OJ8lFVVY%3D&st=2021-01-22T01%3A05%3A51Z&se=2021-02-22T01%3A10%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 01:24 UTC, opbld33 commented
Docs Build status updates of commit _[48327d6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48327d657640f87d35a2ddfe3b9ca03bb1699c8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-46dc1e40)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-46dc1e40)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-46dc1e40)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-46dc1e40)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-46dc1e40)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-46dc1e40)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-46dc1e40)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-46dc1e40)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="69825fde-46dc1e40"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-46dc1e40"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-46dc1e40"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-46dc1e40"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-46dc1e40"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-46dc1e40"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webh [...]

2021-01-22 01:57 UTC, opbld30 commented
Docs Build status updates of commit _[258702b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/258702b1efd5cacf290715411b79c3695d8c332e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-8f283b0e)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-8f283b0e)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-8f283b0e)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-8f283b0e)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-8f283b0e)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-8f283b0e)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-8f283b0e)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-8f283b0e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="69825fde-8f283b0e"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-8f283b0e"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-8f283b0e"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-8f283b0e"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-8f283b0e"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-8f283b0e"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webh [...]

2021-01-22 02:03 UTC, opbld32 commented
Docs Build status updates of commit _[c85bdbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c85bdbd4152dc1feb37a2db1a1304f6ee06037c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-69825fde-caa3818c)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8f8d1d71-caa3818c)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-caa3818c)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-caa3818c)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-caa3818c)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-caa3818c)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-caa3818c)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-caa3818c)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="69825fde-caa3818c"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-caa3818c"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8c89eee-caa3818c"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-caa3818c"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-caa3818c"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-caa3818c"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webh [...]

2021-01-22 02:05 UTC, opbld30 commented
Docs Build status updates of commit _[1192b60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1192b6046082ef07c56e6b1f23edd15f83c72905)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-a8c89eee-e32dae76)
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-e32dae76)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-e32dae76)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-e32dae76)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-e32dae76)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-e32dae76)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="a8c89eee-e32dae76"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8794bed8-e32dae76"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-e32dae76"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-e32dae76"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-e32dae76"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%20%5C`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a s [...]

2021-01-22 02:07 UTC, opbld30 commented
Docs Build status updates of commit _[6e5d0cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e5d0cb27f350a952d9c9f1defba02226943467f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-8794bed8-72556218)
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-7c1b2c14-72556218)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-72556218)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-72556218)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-72556218)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="8794bed8-72556218"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7c1b2c14-72556218"></a>
### [api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="409b84f8-72556218"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-72556218"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%20%5C`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-post-taskdefinitions?view=graph-rest-beta&tabs=http`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http`````
 - **Line 65, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource [...]

2021-01-22 02:09 UTC, opbld32 commented
Docs Build status updates of commit _[d6e3169](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d6e3169e4f7b0c4ea52c3fa52b596cbfa5287bc6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) | [Details](#user-content-409b84f8-009761b1)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-009761b1)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-009761b1)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="409b84f8-009761b1"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c447f2b8-009761b1"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%20%5C`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-post-taskdefinitions?view=graph-rest-beta&tabs=http`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http`````
 - **Line 65, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 18 [...]

2021-01-22 02:11 UTC, opbld34 commented
Docs Build status updates of commit _[ec85a2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec85a2b0ea266b2edd103b4ee3e2f8b774bd0949)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-27f856e0)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-27f856e0)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="c447f2b8-27f856e0"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%20%5C`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-post-taskdefinitions?view=graph-rest-beta&tabs=http`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http`````
 - **Line 65, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-update?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-get?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-delete?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhook [...]

2021-01-22 02:30 UTC, opbld31 commented
Docs Build status updates of commit _[fbdf63b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbdf63be790dfc7986ed6905907bcd98f4a52d71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-99510831)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-99510831)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="c447f2b8-99510831"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%20%5C`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-post-taskdefinitions?view=graph-rest-beta&tabs=http`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http`````
 - **Line 65, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-update?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-get?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-delete?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhook [...]

2021-01-22 02:32 UTC, opbld33 commented
Docs Build status updates of commit _[31f11ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31f11aefd3326aaa7745545ddfa1576d5e6db998)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) | [Details](#user-content-c447f2b8-1e837507)
[concepts/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/webhooks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/webhooks?branch=pr-en-us-11226) | [Details](#user-content-8c54aee1-1e837507)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/printtaskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/printtaskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printtaskdefinition?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11226) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11226) |

<a id="c447f2b8-1e837507"></a>
### [concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-and-update-webhook-notification-doc/concepts/universal-print-webhook-notifications.md)
 - **Line 45, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printtaskdefinition-get?view=graph-rest-beta&tabs=http%22%20%5Cl%20%22permissions%22%20%5C`````
 - **Line 47, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 49, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/auth-v2-service?context=graph%2Fapi%2Fbeta&view=graph-rest-beta`````
 - **Line 58, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/print-post-taskdefinitions?view=graph-rest-beta&tabs=http`````
 - **Line 60, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/printer-post-tasktriggers?view=graph-rest-beta&tabs=http`````
 - **Line 65, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-post-subscriptions?view=graph-rest-beta&tabs=http`````
 - **Line 69, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 71, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 129, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 131, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#properties`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/subscription?view=graph-rest-beta#maximum-length-of-subscription-per-resource-type`````
 - **Line 183, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-update?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-get?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/subscription-delete?view=graph-rest-beta&tabs=http`````
 - **Line 187, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/webhook [...]

2021-01-22 03:43 UTC, Lauragra approved these changes

2021-01-22 03:43 UTC, merged