Access reviews tutorial
microsoftgraph/microsoft-graph-docs pull request #11247
Opened 2021-01-11 16:57 UTC by FaithOmbongi

2021-01-11 16:58 UTC, opbld34 commented
Docs Build status updates of commit _[e27c248](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e27c248c66118cb289093fc76e84ede3e46e2857)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-7fb4ce8d)
[concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-access-reviews-api?branch=pr-en-us-11247) | [Details](#user-content-1ab52bad-7fb4ce8d)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-7fb4ce8d"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 11, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 27, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/auth-v2-user' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/auth-v2-service' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 44, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/auth-v2-user' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 45, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/auth-v2-service' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Access reviews overview - Microsoft Graph' is duplicated in: 'accessreviews-overview.md(2,8), tutorial-access-reviews-api.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Access reviews API provide programmatic access to access reviews' is duplicated in 'accessreviews-overview.md(3,14)', 'tutorial-access-reviews-api.md(3,14)'.`````

<a id="1ab52bad-7fb4ce8d"></a>
### [concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md)
 - **Line 431, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview#license-requirements' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 432, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview#example-license-scenarios' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 433, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/create-access-review' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 434, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http#request-body' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Access reviews overview - Microsoft Graph' is duplicated in: 'accessreviews-overview.md(2,8), tutorial-access-reviews-api.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Access reviews API provide programmatic access to access reviews' is duplicated in 'accessreviews-overview.md(3,14)', 'tutorial-access-reviews-api.md(3,14)'.`````
 - **Line 434, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http#request-body`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101111657066826-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XnVh2jiLw2JPHqqxeNBdz0byi1YbSAUAKNVuPOPMXzU%3D&st=2021-01-11T16%3A53%3A16Z&se=2021-02-11T16%3A58%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a hr [...]

2021-01-11 19:10 UTC, opbld32 commented
Docs Build status updates of commit _[1fd61cd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fd61cdd61b30b54381e19b6281c056893b7d3fa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-9d91a600)
[concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-access-reviews-api?branch=pr-en-us-11247) | [Details](#user-content-1ab52bad-9d91a600)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-9d91a600"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 45, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/auth-v2-service' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="1ab52bad-9d91a600"></a>
### [concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md)
 - **Line 431, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview#license-requirements' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 432, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview#example-license-scenarios' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 433, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/create-access-review' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 434, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http#request-body' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 434, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http#request-body`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101111908454175-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W%2FryRev8NiZK0JetBY5sVnmGBhsZh2t%2BqbGQ8xdOVZA%3D&st=2021-01-11T19%3A05%3A27Z&se=2021-02-11T19%3A10%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 19:19 UTC, opbld30 commented
Docs Build status updates of commit _[0b82482](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b82482c5574b9d50187ef2fbfc1636c97bf03c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-35c79315)
[concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-access-reviews-api?branch=pr-en-us-11247) | [Details](#user-content-1ab52bad-35c79315)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-35c79315"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 45, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/auth-v2-service' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

<a id="1ab52bad-35c79315"></a>
### [concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md)
 - **Line 431, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview#license-requirements' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 432, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/access-reviews-overview#example-license-scenarios' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 433, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/active-directory/governance/create-access-review' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 434, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http#request-body' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 434, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/accessreviewscheduledefinition-create?view=graph-rest-beta&tabs=http#request-body`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101111917376830-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rCwZdSGR9%2BkRXf08UnX5eQPiapvXMbr1TsXs4D1JBlo%3D&st=2021-01-11T19%3A14%3A40Z&se=2021-02-11T19%3A19%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-11 19:25 UTC, opbld31 commented
Docs Build status updates of commit _[46d204d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/46d204d11248c767b44240d378c1b9c4628efb2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-access-reviews-api?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101111924354013-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lRlP8Ch9aYDzlsxufTFfqVrJbhXFBraFKth%2BD4UwupU%3D&st=2021-01-11T19%3A20%3A41Z&se=2021-02-11T19%3A25%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-18 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[a8ca42b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a8ca42bb7aa056d6f647d60c6dd6183800bb0721)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-access-reviews-api?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101181822187738-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LkZRQ%2B%2BN13TQ1ogbcGwV02bxMMg3bIY4DuyG%2FJq%2BcoQ%3D&st=2021-01-18T18%3A19%3A15Z&se=2021-02-18T18%3A24%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-19 21:03 UTC, isabelleatmsft requested changes

2021-01-19 21:03 UTC, isabelleatmsft commented on concepts/tutorial-access-reviews-api.md
> ++ Apply disable and delete action to denied guest users.
we want to be very clear on what this is as it is a feature with large implications (completely deleting denied guest users from the tenant)

2021-01-19 21:03 UTC, isabelleatmsft commented on concepts/tutorial-access-reviews-api.md
> +                "startDate": "2020-12-28",
is there any way to dynamically change the start date to today's date and the end date to one year from today?

2021-01-20 20:49 UTC, FaithOmbongi commented on concepts/accessreviews-overview.md
> ++ An Access Review *instance*: Represents a review activity that has a scope, reviewers, and a status. An Access Review definition may have multiple instances as is the case in recurring reviews and
Well noted.

2021-01-20 22:27 UTC, opbld30 commented
Docs Build status updates of commit _[bc4bfa5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc4bfa5caba133d1078c75ee6a615d3b409c50a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9ece2a7c)

<a id="9ece2a7c"></a>
###
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101202224466101-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=74gN347xw9TWT4mBKVtxWxiWdRCNONGpU4wAY%2FRF6hc%3D&st=2021-01-20T22%3A21%3A59Z&se=2021-02-20T22%3A26%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 22:40 UTC, opbld30 commented
Docs Build status updates of commit _[a771b2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a771b2c89f84de6efca0bd0928622fcfb5051f86)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-164ee3c2)

<a id="164ee3c2"></a>
###
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-ref&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=master&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````
 - **Line 0, Column 0**: **[Error-download-failed]** `````Download failed for file 'https://ops/buildconfig/?name=microsoft-graph-docs&locale=en-us&repository_url=https://github.com/microsoftgraph/microsoft-graph-docs&branch=master&xref_endpoint=&xref_query_tags='. Try closing and reopening the PR. If you get this Error again, file an issue.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101202237462551-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V2UQ8zu%2BaySdYWdBuxqyQhW5TFOTKKCo7WkZEbuAE40%3D&st=2021-01-20T22%3A35%3A17Z&se=2021-02-20T22%3A40%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 17:24 UTC, FaithOmbongi commented on concepts/tutorial-access-reviews-api.md
> +                "startDate": "2020-12-28",
We'll add a note notifying the user to change these dates

2021-01-21 19:36 UTC, FaithOmbongi commented on concepts/accessreviews-overview.md
> ++ Access reviews schedule *definitions*: is the logical blueprint that contains the settings of an access review and its instances. An access review can have multiple definitions.
Kindly confirm @flofromm, original doc says "you can have N definitions of Access Reviews (one-off as well as series of Access Reviews)"

2021-01-21 19:40 UTC, FaithOmbongi commented on concepts/tutorial-access-reviews-api.md
> +
Missing code block; Please assist @flofromm

2021-02-10 12:59 UTC, opbld32 commented
Docs Build status updates of commit _[51101d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51101d2594463254a0e244d3a8de24d3ca0277f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-access-reviews-api?branch=pr-en-us-11247) | [Details](#user-content-1ab52bad-1371be42)
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="1ab52bad-1371be42"></a>
### [concepts/tutorial-access-reviews-api.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-access-reviews-api.md)
 - **Line 107, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101258018459-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TAxc6crL8AslUlQ9MQmMUYMsiopS%2FMn6RKJ2sZRpLd8%3D&st=2021-02-10T12%3A54%3A10Z&se=2021-03-13T12%3A59%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 13:03 UTC, opbld31 commented
Docs Build status updates of commit _[26c3925](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26c392564092dc2c9f8d66da31e178bc159e4ecc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-c3515b96)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-b329d26c-c3515b96)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-c3515b96)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-c3515b96)

<a id="168ebe2f-c3515b96"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 38, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorial-access-reviews-api.md'.`````

<a id="b329d26c-c3515b96"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml)
 - **Line 234, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorial-access-reviews-api.md'.`````

<a id="ef2c9078-c3515b96"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Using the Access Reviews API in Graph Explorer - Microsoft Graph' is duplicated in: 'tutorial-accessreviews-M365group.md(2,8), tutorial-accessreviews-securitygroup.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 176, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e9e2f66-c3515b96"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Using the Access Reviews API in Graph Explorer - Microsoft Graph' is duplicated in: 'tutorial-accessreviews-M365group.md(2,8), tutorial-accessreviews-securitygroup.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 111, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101302162128-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EOXBfsu5c%2FgSngfk0zNZaX2EcaYFDy12b%2FRF0iozLOg%3D&st=2021-02-10T12%3A58%3A29Z&se=2021-03-13T13%3A03%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:02 UTC, opbld32 commented
Docs Build status updates of commit _[9dfb719](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9dfb719c5bf5a5b1d2cb0b72b88b4f4eaa2b9a35)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-d21d2b16)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-b329d26c-d21d2b16)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-d21d2b16)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-d21d2b16)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |

<a id="168ebe2f-d21d2b16"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 38, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorial-access-reviews-api.md'.`````

<a id="b329d26c-d21d2b16"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml)
 - **Line 234, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorial-access-reviews-api.md'.`````

<a id="ef2c9078-d21d2b16"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 37, Column 4**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Using the Access Reviews API in Graph Explorer - Microsoft Graph' is duplicated in: 'tutorial-accessreviews-M365group.md(2,8), tutorial-accessreviews-securitygroup.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 187, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e9e2f66-d21d2b16"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Using the Access Reviews API in Graph Explorer - Microsoft Graph' is duplicated in: 'tutorial-accessreviews-M365group.md(2,8), tutorial-accessreviews-securitygroup.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 123, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101801170978-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HwZtOGPADoSkyT2DjfwLjSovzgZGD0qeuDiA7aT%2FNhQ%3D&st=2021-02-10T17%3A57%3A47Z&se=2021-03-13T18%3A02%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:05 UTC, opbld31 commented
Docs Build status updates of commit _[6b44a8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b44a8f87ef95398751728b0754aaf8201d50c38)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-ac564e0d)
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-b329d26c-ac564e0d)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-ac564e0d)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-ac564e0d)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |

<a id="168ebe2f-ac564e0d"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 38, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorial-access-reviews-api.md'.`````

<a id="b329d26c-ac564e0d"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml)
 - **Line 234, Column 27**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'tutorial-access-reviews-api.md'.`````

<a id="ef2c9078-ac564e0d"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 37, Column 4**: **[Warning-invalid-note-section]** `````Text in the first line of Note/Section/Video is not valid. Will be rendered to <blockquote>`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Using the Access Reviews API in Graph Explorer - Microsoft Graph' is duplicated in: 'tutorial-accessreviews-M365group.md(2,8), tutorial-accessreviews-securitygroup.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 187, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e9e2f66-ac564e0d"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Using the Access Reviews API in Graph Explorer - Microsoft Graph' is duplicated in: 'tutorial-accessreviews-M365group.md(2,8), tutorial-accessreviews-securitygroup.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 123, Column 99**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101803324432-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pfsihmv1XHCmTJjcf57I6EIBv0KKVSuqkA1veu%2FbX7E%3D&st=2021-02-10T18%3A00%3A52Z&se=2021-03-13T18%3A05%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:15 UTC, opbld32 commented
Docs Build status updates of commit _[2a4ac5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a4ac5b61f97a44616d63f0276bb376f9c7ca711)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101814082406-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L2QozrsYdRaFeTpD7c6Ad9WADFXZxIUPc6IcU9rJY6g%3D&st=2021-02-10T18%3A10%3A24Z&se=2021-03-13T18%3A15%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 18:54 UTC, opbld30 commented
Docs Build status updates of commit _[1907488](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19074880652530d6b5a515ab2bde7ea3d84017b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-f3b96ed4)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-f3b96ed4)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-f3b96ed4)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-f3b96ed4"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ef2c9078-f3b96ed4"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="7e9e2f66-f3b96ed4"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102151851334785-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g%2B3LPy5sTYHWUB7oHS%2FuuwZRqp0tTDGKrjOVB15A7Qw%3D&st=2021-02-15T18%3A49%3A29Z&se=2021-03-18T18%3A54%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 08:24 UTC, opbld31 commented
Docs Build status updates of commit _[061e4ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/061e4ea111d7411b79ac7a083ef40c947ad2b6e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-79139563)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-79139563)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-79139563)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-79139563"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 11, Column 5**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="ef2c9078-79139563"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 488, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/invitation?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e9e2f66-79139563"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102160823384003-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tvmlJHHQAgLryxdeosT8g%2FuzSFJMXJBxlF3COEno9lE%3D&st=2021-02-16T08%3A19%3A55Z&se=2021-03-19T08%3A24%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 08:34 UTC, opbld34 commented
Docs Build status updates of commit _[804794b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/804794b393a91eb99ad2078f5501c46fb5cdfe5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-13703119)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-13703119)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-13703119)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-13703119"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 11, Column 5**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="ef2c9078-13703119"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 488, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/invitation?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e9e2f66-13703119"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102160832573925-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QZp50uqDMCTBhIyYJ1TWDu7VOgnlXYmIIY%2BKFreoobQ%3D&st=2021-02-16T08%3A29%3A07Z&se=2021-03-19T08%3A34%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 08:35 UTC, opbld34 commented
Docs Build status updates of commit _[24fac17](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24fac17cce2a0652aa7b1c12aa11ddf76c7f6ee7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-43935429)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-43935429)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-43935429)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-43935429"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 11, Column 5**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/accessreviewsv2-root?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="ef2c9078-43935429"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 489, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: /graph/api/resources/invitation?view=graph-rest-beta. Otherwise, remove the view parameter.`````

<a id="7e9e2f66-43935429"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102160833297665-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jFT1%2BU41NWnRn2zrlFiuPmXnIvSMHDvb8syKX0FJKp0%3D&st=2021-02-16T08%3A30%3A20Z&se=2021-03-19T08%3A35%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 08:39 UTC, opbld32 commented
Docs Build status updates of commit _[b821c02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b821c02457388d0e20db263cdbc33a2b8456c6f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-8d982672)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-8d982672)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-8d982672)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-8d982672"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ef2c9078-8d982672"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="7e9e2f66-8d982672"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102160838390984-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=syLa%2BVmSaOcrNVMfCYA4ily2x4KMnMajpa31GEqiN9U%3D&st=2021-02-16T08%3A34%3A45Z&se=2021-03-19T08%3A39%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-24 01:21 UTC, isabelleatmsft submitted a review, later dismissed
Great job!! This is awesome. Left a few small comments.

2021-02-24 01:21 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-M365group.md
> ++ A backup reviewer. This can be a fallback user or a group that can review the access in case the group doesn't have any owners assigned even though its group owners are the access review reviewers.
cut "even though its group owners are the access review reviewers"

2021-02-24 01:21 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-M365group.md
> ++ **autoApplyDecisionsEnabled** is set to `true`. In this case, once the reviewer completes the access review, their decisions are applied automatically. If not enabled, a user must, after the review
close but not exactly - the decisions are applied once the access review duration ends, regardless of whether the reviewer completed the review or not

2021-02-24 01:21 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-M365group.md
> +The following query lists all instances of the access review definition. If your test tenant contains other M365 groups with external guests, this request will return more than 1 instance.
"this request will return an instance for every M365 group with guest users in the tenant"

2021-02-24 01:21 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-M365group.md
> +In this response, the **status** of the access review instance is marked as `Applied` because the current review cycle has ended. Because this is a quarterly review, every 3 months time, a new review
for the purpose of the tutorial can we change the status to InProgress?

2021-02-24 01:21 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-M365group.md
> +Congratulations! You have created an access review for the M365 group and the group owners have approved access for the current review cycle. You have also triggered a scheduled quarterly re-evaluati
"Congratulations! You have created an access review scheduled quarterly for the evaluation and attestation of access for all guest users in M365 groups. The group owners will review access during these cycles, choosing either to approve or deny access."

2021-02-24 01:21 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-securitygroup.md
> +2. Complete the access review self-attestation process.
i see #1 below, but do not see #2 where the user actually completes the review on themself?

2021-02-24 19:03 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-securitygroup.md
> +2. Complete the access review self-attestation process.
Updated the doc to group the two steps in H3s. #2 is completed via the https://myaccess.microsoft.com/  portal.

2021-02-24 19:23 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> +These APIs support reviews for groups, such as Microsoft 365 groups and security groups, only.
Actually, we don't want to imply any promise of future work in the docs.

2021-02-24 19:24 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> ++ In a user (delegated) context: an application calls the Access Reviews API on behalf of a user. Typical scenarios include:
```suggestion
+ In a user (delegated) context, an application calls the Access Reviews API on behalf of a user. Typical scenarios include:
```

2021-02-24 19:25 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> ++ In an application context: an application calls the Access Reviews API without a signed-in user present. A typical scenario is a scheduled background script regularly collecting decisions for all a
```suggestion
+ In an application context, an application calls the Access Reviews API without a signed-in user present. A typical scenario is a scheduled background script regularly collecting decisions for all access reviews. To authorize your app in this context, see [get access without a user](/graph/auth-v2-service).
```

2021-02-24 19:26 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> +## Building blocks of the Access Reviews API
```suggestion
## Building blocks of an access review
```

2021-02-24 19:27 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> +The Access Reviews API structures information logically and comprises three major building blocks:
```suggestion
Access reviews are structured logically and are comprised of these building blocks:
```

2021-02-24 19:29 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> ++ Access reviews schedule *definitions*: is the logical blueprint that contains the settings of an access review and its instances.
```suggestion
+ Access reviews schedule definitions are the logical blueprint that contains the settings of an access review and its instances.
```

2021-02-24 19:30 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> ++ An access review *instance*: represents a review activity that has a scope, reviewers, and a status. An access review definition may have multiple instances as is the case in monthly recurring revi
```suggestion
+ **Access review instance** - Represents a review activity that has a scope, reviewers, and a status. An access review definition may have multiple instances as is the case in recurring reviews. One-off reviews have exactly one instance.
```

2021-02-24 19:32 UTC, davidmu1 commented on concepts/accessreviews-overview.md
> ++ *Decision items* recorded for a review: represent a decision a reviewer made on an instance, including the time stamp and justification for the decision. Each review instance has as many decisions
```suggestion
+ **Decision items recorded for a review** - Represent a decision a reviewer made on an instance, including the time stamp and justification for the decision. Each review instance has as many decisions as the number of users under review. If there are no decisions taken, that is, reviewers haven’t responded to the review, there will be no decision objects for the instance.
```

2021-02-24 19:35 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +title: "Using the Access Reviews API for your M365 groups"
```suggestion
title: "Create and read access reviews for your M365 groups using Microsoft Graph APIs."
```

2021-02-24 19:36 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +# Tutorial: Use the Access Reviews API to review access to all your M365 groups with external identities
```suggestion
# Tutorial: Create and read access reviews for M365 groups with guest users using the Microsoft Graph API.
```

2021-02-24 19:40 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +In this tutorial, you will use Graph Explorer to create and read access reviews that targets all M365 Groups with external identities in the tenant. To achieve this, you'll first use Azure AD B2B to
```suggestion
In this tutorial, you use Microsoft Graph Explorer to create and read access reviews that targets all M365 Groups with guest users in the tenant. To achieve this, you first use Azure AD B2B to invite and create a guest user in your tenant. Then, you add this guest user to your M365 group prior to creating and reading the access review.
```

2021-02-24 19:41 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ An account in a different Azure AD tenant or a social identity that you can invite as an external identity (B2B user).
```suggestion
+ An account in a different Azure AD tenant or a social identity that you can invite as a guest user (B2B user).
```

2021-02-24 19:41 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ Log in to [Microsoft Graph Explorer](https://developer.microsoft.com/graph/graph-explorer)  as a user in a global administrator role.
```suggestion
+ Sign in to [Microsoft Graph Explorer](https://developer.microsoft.com/graph/graph-explorer)  as a user in a global administrator role. 
```

2021-02-24 19:49 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ Permissions:
I don't think this list is needed because you are listing them in step 3.

2021-02-24 19:49 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> ++ An account in a different Azure AD tenant or a social identity that you can invite as an external identity (B2B user).
Suggestion accepted and corrected in the remote branch.

2021-02-24 19:50 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +2. Select the settings gear icon to the right of the user account details, and then select **Select permissions**.
```suggestion
2. Select the settings icon to the right of the user account details, and then choose **Select permissions**.
```

2021-02-24 20:02 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> ++ Permissions:
Noted.

2021-02-24 20:05 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +3. Scroll through the list of permissions to find the *AccessReview.ReadWrite.All*, *Directory.AccessAsUser.All*, *Group.ReadWrite.All*, and *User.Invite.All* permissions. To consent to the permissio
These permissions won't be visible unless the category is expanded. For example, to get to the AccessReview.ReadWrite.All permission, the user must first expand **AccessReview (3)**. Suggestion: 

Scroll through the list of permissions to these permissions:
- AccessReviews (3), expand and then select AccessReviews.ReadWrite.All
- Group (2), expand and then select Group.ReadWrite.All
- User (8), expand and then select User.Invite.All
User (8), expand and then select User.ReadWrite.All

2021-02-24 20:18 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +   >[!NOTE]
Please remove the note. Suggestion:

4. Select **Consent**, and then select **Accept** to accept the consent of the permissions. You do not need to consent on behalf of your organization for these permissions.

2021-02-24 20:19 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +Run the following request to invite an external user with the email address **john.doe@outlook.com** to your tenant.
Please move this sentence above the Request header.

2021-02-24 20:20 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +Run the following request to invite an external user with the email address **john.doe@outlook.com** to your tenant.
```suggestion
Invite a guest user with the email address of **john.doe@outlook.com** to your tenant.
```

2021-02-24 20:21 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +## Step 2: Create a new M365 group and add the external guest
```suggestion
## Step 2: Create a new M365 group and add the guest user
```

2021-02-24 20:21 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +3. Add john.doe@outlook.com as a group member. Their access to the group will be the subject of review by you, the group owner.
```suggestion
3. Add john.doe@outlook.com as a group member. Their access to the group is the subject of review by you, the group owner.
```

2021-02-24 20:23 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +Take note of the invited user's id from the response. In this case, john.doe@outlook.com has been assigned user `id` `baf1b0a0-1f9a-4a56-9884-6a30824f8d20` in your tenant.
```suggestion
Record the **id** of the guest user from the response to be used later in this tutorial.
```

2021-02-24 20:31 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ `cdb555e3-b33e-4fd5-a427-17fadacbdfa7` with your `id`.
Where has the user been instructed in how to obtain their own id?

2021-02-24 20:32 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> +3. Scroll through the list of permissions to find the *AccessReview.ReadWrite.All*, *Directory.AccessAsUser.All*, *Group.ReadWrite.All*, and *User.Invite.All* permissions. To consent to the permissio
Confirming about Directory.AccessAsUser.All - I can't delete the guest user with the other permissions. I'll need another permission for that.

2021-02-24 20:32 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ `baf1b0a0-1f9a-4a56-9884-6a30824f8d20` with the `id` john.doe@outlook.com has been assigned in your tenant.
Use the **id** that you recorded for the invited user.

2021-02-24 20:34 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +    "@odata.context": "https://graph.microsoft.com/beta/$metadata#groups/$entity",
In other tutorials, we have a note in the introduction that says that example responses may be shortened. You might want to consider shortening this response a bit and only including properties that are needed for the task.

Note: The response objects shown in this tutorial might be shortened for readability.

2021-02-24 20:34 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +## Step 3: Create an access review for all M365 groups with external identities
```suggestion
## Step 3: Create an access review for all M365 groups with guest users
```

2021-02-24 20:39 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +You have an M365 group and it has an external identity. Now, create a recurring access review series for all M365 groups with external guests. This means that for all M365 groups with external guests
```suggestion
You have an M365 group and it has a guest user. You can then create a recurring access review series for all M365 groups with guest users. This means that for all M365 groups with guest users, you schedule a periodic review of the guests' access to the M365 group.
```

2021-02-24 20:39 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +The access review series will have the following settings:
```suggestion
The access review series uses the following settings:
```

2021-02-24 20:40 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ Its a recurring access review, reviewed quarterly.
```suggestion
+ It's a recurring access review and reviewed quarterly.
```

2021-02-24 20:40 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ The group owners review the external identity's continued access.
```suggestion
+ The group owners review the continued access of the guest user.
```

2021-02-24 20:41 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ The review scope is limited to M365 groups with **Guest users** (external identities) only.
```suggestion
+ The review scope is limited to M365 groups with **Guest users** only.
```

2021-02-24 20:45 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ Apply **removeAccessApplyAction** action to denied guest users. This removes the denied guest user's membership to the group, though they'll still be able to sign in to your tenant.[Learn more abou
```suggestion
+ Apply **removeAccessApplyAction** action to denied guest users. This removes the membership in the group of the denied guest. The guest user can still sign in to your tenant.
```

2021-02-24 20:45 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> +You have an M365 group and it has an external identity. Now, create a recurring access review series for all M365 groups with external guests. This means that for all M365 groups with external guests
Changes made to remote branch.

2021-02-24 20:45 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ Apply **removeAccessApplyAction** action to denied guest users. This removes the denied guest user's membership to the group, though they'll still be able to sign in to your tenant.[Learn more abou
Links that send the user out of the tutorial should be included in the See Also section, not the body of the tutorial.

2021-02-24 20:46 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +For more information about the parameters in the request body of these examples, see the [Access Reviews API Reference](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=tr
This should be moved to the See Also section at the end of the tutorial.

2021-02-24 20:47 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ Value of **displayName** with your preferred value.
Since this is only a learning experience and not for production, we should just provide a display name to use.

2021-02-24 20:49 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> ++ `c9a5aff7-9298-4d71-adab-0a222e0a05e4` with the `id` of the user you are designating as a backup reviewer.
Are we assuming that there are user accounts already created that the customer will know about using? I think it's better to have a section up front that creates the test user accounts needed for the tutorial and deletes them when done.

2021-02-24 20:49 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +This is an access review definition. You can list and read this and any other existing definitions by running `GET` on `https://graph.microsoft.com/beta/identityGovernance/accessReviews/definitions`.
Links should be in the See Also section.

2021-02-24 20:51 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +In this call, replace `c22ae540-b89a-4d24-bac0-4ef35e6591ea` with the `id` of a definition returned in Step 3.
Should be more specific about which id this is.

2021-02-24 20:51 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +In this response, te scope includes a group of `id` `59ab642a-2776-4e32-9b68-9ff7a47b7f6a`. This is the **Feelgood marketing campaign** group created in Step 2.
```suggestion
In this response, the scope includes a group of `id` `59ab642a-2776-4e32-9b68-9ff7a47b7f6a`. This is the **Feelgood marketing campaign** group created in Step 2.
```

2021-02-24 20:52 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +You are interested in the decisions taken for the instance of an access review..
```suggestion
Get the decisions taken for the instance of an access review.
```

2021-02-24 20:53 UTC, davidmu1 commented on concepts/tutorial-accessreviews-M365group.md
> +
A link to all API resources used in the tutorial should be included in this section.

2021-02-25 09:40 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> ++ `c9a5aff7-9298-4d71-adab-0a222e0a05e4` with the `id` of the user you are designating as a backup reviewer.
Adding this step.

2021-03-04 07:10 UTC, opbld30 commented
Docs Build status updates of commit _[3495ef7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3495ef7ba59aa17f6a25837a19208ffb4f1d349a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) | [Details](#user-content-168ebe2f-e13755f9)
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) | [Details](#user-content-ef2c9078-e13755f9)
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) | [Details](#user-content-7e9e2f66-e13755f9)
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |

<a id="168ebe2f-e13755f9"></a>
### [concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="ef2c9078-e13755f9"></a>
### [concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="7e9e2f66-e13755f9"></a>
### [concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040709128650-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=celDz2AZpciIz7d5oymrROhGzn8%2FmgrRpRPdmv2H%2FRM%3D&st=2021-03-04T07%3A05%3A53Z&se=2021-04-04T07%3A10%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 23:33 UTC, isabelleatmsft reviewed
2 small things then we are ready to publish!

2021-03-09 23:33 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-M365group.md
> +            "target": {
Small thing - the structure of the accessReviewDecisionItem changed just slightly to include a new property called principal. Principal will replace target in the future (we will deprecate target). Can you rerun your tutorial and get the response here updated to include the returned parameter principal?

2021-03-09 23:33 UTC, isabelleatmsft commented on concepts/tutorial-accessreviews-securitygroup.md
> +            "target": {
same comment as on the last page - we added a new property principal. please re-run this to get the principal property in the response.

2021-03-15 07:47 UTC, opbld31 commented
Docs Build status updates of commit _[66bd2d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66bd2d30181e58bf32c987b5e67c606b6bd7b81f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103150745542792-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IIHTZw%2BI%2B8Q9Vm93OGyHPv83RmPzHTG9rj6Z6fTH%2FnI%3D&st=2021-03-15T07%3A42%3A23Z&se=2021-04-15T07%3A47%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 06:48 UTC, opbld33 commented
Docs Build status updates of commit _[455907f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/455907f13531c27dc514a486e0f24722728f726d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103160646412413-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bRanZbME4snDeY3LEZ6m%2BuZAZr7iXeSbL8HYFBKLdpA%3D&st=2021-03-16T06%3A43%3A03Z&se=2021-04-16T06%3A48%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-17 15:11 UTC, isabelleatmsft approved these changes

2021-03-26 04:16 UTC, CelesteDG commented
@FaithOmbongi @isabelleatmsft - Is this ready to merge to main then live? Please let me know

2021-03-26 04:44 UTC, Lauragra commented
> @FaithOmbongi @isabelleatmsft - Is this ready to merge to main then live? Please let me know

@CelesteDG , this PR isn't ready to merge yet. I have some open comments for Isabelle. I let her know. We are planning to publish on Monday.

2021-03-26 04:45 UTC, Lauragra commented
> @FaithOmbongi @isabelleatmsft - Is this ready to merge to main then live? Please let me know

Never mind, that was a different PR. This one is not set to ready to merge. Is there urgency in publishing it before next week?

2021-03-26 04:47 UTC, Lauragra commented on concepts/accessreviews-overview.md
> +# Overview of the Access Reviews API for groups
I don't think that access reviews is a proper noun - i.e. it's not an official product name - so please use lowercase. Note that the title attribute and the H1 should match. Can we revise the title to "Overview of the Microsoft Graph access review API"? That will get the Microsoft Graph keyword in there.

2021-03-26 04:48 UTC, Lauragra commented on concepts/accessreviews-overview.md
> +The [Access Reviews Graph API](/graph/api/resources/accessreviewsv2-root?view=graph-rest-beta&preserve-view=true) allows you to programmatically review access to your resources. This includes:
Per branding guidelines, we always refer to "Microsoft Graph" and never "Graph". Please update the link text to "access reviews API" and then add in Microsoft Graph.

2021-03-26 04:50 UTC, Lauragra commented on concepts/toc.yml
> +                  - name: Review access to an M365 group
Please don't ever abbreviate Microsoft or Microsoft 365; it should be spelled out. However, to keep TOC entries concise, can you make the entry "Review access to a group"?

2021-03-26 04:52 UTC, Lauragra commented on concepts/accessreviews-overview.md
> +These APIs support reviews for groups, such as Microsoft 365 groups and security groups, only.
Do you want to revise this to say "These APIs currently support reviews for Microsoft 365 groups and security groups." Removing the word "only" makes it sound less restrictive and adding "currently" implies that there might be broader support in the future, without making any promise of future behavior.

2021-03-26 04:54 UTC, Lauragra commented on concepts/accessreviews-overview.md
> ++ Creating, reading, updating, and deleting access reviews, their settings, and schedules.
The use of "their" here personifies access reviews. Suggest revising to say "... access reviews and access review settings and schedules."

2021-03-26 05:25 UTC, CelesteDG commented on concepts/accessreviews-overview.md
> +# Overview of the Access Reviews API for groups
> I don't think that access reviews is a proper noun - i.e. it's not an official product name - so please use lowercase. Note that the title attribute and the H1 should match. Can we revise the title to "Overview of the Microsoft Graph access review API"? That will get the Microsoft Graph keyword in there.

Agree that we should update the topic title (H1) so that it doesn't use proper nouns for access reviews (aligned with our IT admin docs on the Azure AD doc set). However, rather than adding Microsoft Graph to the H1, let's use the Title metadata instead and set it to "Title: Overview of the access reviews APi for groups - Microsoft Graph". This will make Microsoft Graph show up in search results and also not make the topic title overly long (since this will be done in the metadata). Laura, something we should consider doing for the Graph doc set (adding that "- Microsoft Graph" or "| Microsoft Graph" in the title metadata. We do this in the Azure AD doc set so maybe something to consider for Graph.

2021-03-26 06:51 UTC, FaithOmbongi commented on concepts/toc.yml
> +                  - name: Review access to an M365 group
This is well noted. However, since this tutorial is specific to Microsoft 365 groups—as opposed to security groups—we might have to use Microsoft 365 in the title.

2021-03-26 07:12 UTC, FaithOmbongi commented
> > @FaithOmbongi @isabelleatmsft - Is this ready to merge to main then live? Please let me know
> 
> Never mind, that was a different PR. This one is not set to ready to merge. Is there urgency in publishing it before next week?

@Lauragra @CelesteDG No urgency. It's still under review.

2021-03-26 07:59 UTC, opbld30 commented
Docs Build status updates of commit _[19db43f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/19db43f46b169340fab228fa4635f0dc4fb0c109)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103260757557164-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a927ISPZr0LGm07sbEHyaeYKL5Dv%2Bb3zIv%2Byi0GNs0o%3D&st=2021-03-26T07%3A54%3A11Z&se=2021-04-26T07%3A59%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 02:08 UTC, Lauragra commented on concepts/accessreviews-overview.md
> +title: "Overview of the access reviews API for groups - Microsoft Graph"
The Microsoft Graph is added by default to topics in search results; you can remove it from here. You might want to include the Microsoft Graph keyword in the actual article title, i.e. "Overview of the access reviews API for groups in Microsoft Graph".

2021-04-02 02:09 UTC, Lauragra commented on concepts/accessreviews-overview.md
> +description: "Overview of the access reviews API for groups"
The description should be a complete sentence and not a repeat of the title. This should be a one-sentence summary of the article content and is the description that can show in some search results.

2021-04-02 02:10 UTC, Lauragra commented on concepts/toc.yml
> +                  - name: Overview of the Access Reviews API
Please use title case for the TOC entry - access reviews API.

2021-04-02 02:11 UTC, Lauragra commented on concepts/accessreviews-overview.md
> ++ In a user (delegated) context, an application calls the access reviews API on behalf of a user. Typical scenarios include:
This can just be an introductory sentence and not a bullet. Then you don't have a nested bulleted list, just a regular bulleted list.

2021-04-02 02:12 UTC, Lauragra commented on concepts/accessreviews-overview.md
> ++ In an application context, an application calls the access reviews API without a signed-in user present. A typical scenario is a scheduled background script regularly collecting decisions for all a
This can be a regular sentence and not a bullet.

2021-04-02 02:13 UTC, Lauragra commented on concepts/accessreviews-overview.md
> ++ [Use the access reviews API for groups to create access and read definitions, instances, and decisions.](tutorial-accessreviews-securitygroup.md)
I suggest introducing these links with text like "Try the following tutorials:". Then remove the periods from the link text.

2021-04-02 02:14 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> +title: "Tutorial: Use the access reviews API to review access to all your Microsoft 365 groups with guest users - Microsoft Graph"
Same comments here regarding the title and description. Can we make the title more concise? Is the "with guest users" part something that can be removed?

2021-04-02 02:15 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> +In this tutorial, you will use Graph Explorer to create and read access reviews that targets all Microsoft 365 Groups with guest users in the tenant. To achieve this, you'll first use Azure AD B2B to
Groups > groups

2021-04-02 02:15 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> +>The response objects shown in this tutorial might be shortened for readability. All the properties will be returned from an actual call.
For technical accuracy, we now remove the "All the properties..." sentence from this boilerplate text.

2021-04-02 02:16 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> ++ Sign in to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer)  as a user in a global administrator role.
This third step, is that something they need or just something they do as they complete the tutorial?

2021-04-03 01:23 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> ++ Permission - For this tutorial, you need the following delegated permissions: `User.Invite.All`, `AccessReview.ReadWrite.All`, `Group.ReadWrite.All`, `User.ReadWrite.All`.
Because we're using noun phrases for this list of prerequisites, this can just say: "The following delegated permissions:".

2021-04-03 01:27 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> +Invite a guest user with the email address **john.doe@outlook.com** to your tenant.
Technically you should use an approved fictitious name from the fictitious names list.

2021-04-03 01:28 UTC, Lauragra commented on concepts/tutorial-accessreviews-M365group.md
> +Create a new user and record their **id**. You will assign them a role in the access review later in this tutorial.
Do you mean to refer to an id property, or just a user ID?

2021-04-05 15:32 UTC, davidmu1 approved these changes
Agree with Laura's comments.

2021-04-12 16:39 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> +title: "Tutorial: Use the access reviews API to review access to all your Microsoft 365 groups with guest users - Microsoft Graph"
Unfortunately, the scope is very particular to guest users. How about "Use the access reviews API to review guest access to your Microsoft 365 groups"

2021-04-12 16:48 UTC, FaithOmbongi commented on concepts/tutorial-accessreviews-M365group.md
> ++ Sign in to [Graph Explorer](https://developer.microsoft.com/graph/graph-explorer)  as a user in a global administrator role.
It's a requirement that they run this as a user in a global admin role. Let me remove step 1 below since they'll have done that.

2021-04-12 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[0062266](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0062266dddc648e40237750ccba3a8a38640cae0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/accessreviews-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/accessreviews-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/consentpermissions_M365.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/selfattest.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/selfattest.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |
[concepts/images/tutorial-accessreviews-api/settings.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/images/tutorial-accessreviews-api/settings.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/accessreviews-overview?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-M365group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-M365group.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-m365group?branch=pr-en-us-11247) |
[concepts/tutorial-accessreviews-securitygroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/accessReviewsTutorial/concepts/tutorial-accessreviews-securitygroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/tutorial-accessreviews-securitygroup?branch=pr-en-us-11247) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104121822396031-11247%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2B95sRvI39AQRhwMpaXWm2G8R%2BWa1Gmj7U8rgN1dOxZw%3D&st=2021-04-12T18%3A19%3A12Z&se=2021-05-13T18%3A24%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-21 02:23 UTC, Lauragra approved these changes

2021-04-21 02:23 UTC, merged