Update EM graph docs for My Access APIs
microsoftgraph/microsoft-graph-docs pull request #11258
Opened 2021-01-12 19:47 UTC by sbounouh

Update EM graph docs for My Access APIs

2021-01-12 19:48 UTC, opbld30 commented
Docs Build status updates of commit _[798547b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/798547bdf24b8a8aa719674f109f22c0c440cb66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) | [Details](#user-content-685b3523-3c70e1ce)
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) | [Details](#user-content-c42fa77c-3c70e1ce)
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) | [Details](#user-content-0e8b8866-3c70e1ce)
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

<a id="685b3523-3c70e1ce"></a>
### [api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md)
 - **Line 50, Column 11**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/approval.md'.`````

<a id="c42fa77c-3c70e1ce"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'accessPackageAssignmentRequest: FilterByCurrentUser' is duplicated with other articles: 'beta/api/accesspackageassignmentrequest-cancel.md(10,1), beta/api/accesspackageassignmentrequest-filterbycurrentuser.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0e8b8866-3c70e1ce"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'accessPackageAssignmentRequest: FilterByCurrentUser' is duplicated with other articles: 'beta/api/accesspackageassignmentrequest-cancel.md(10,1), beta/api/accesspackageassignmentrequest-filterbycurrentuser.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101121947127983-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=llRhqvcBFyyCOCXuih4dFJCIDnyClk1xNZkQ0sTmVTQ%3D&st=2021-01-12T19%3A43%3A20Z&se=2021-02-12T19%3A48%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 01:07 UTC, opbld34 commented
Docs Build status updates of commit _[5e538d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e538d17ce89f82cc2ed50b0e1178f8d55f66c4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130105072381-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z%2BPkxvAwnN3TQieoYY1BoY6XgjaWko%2BQMWmfwnNsAoU%3D&st=2021-01-13T01%3A02%3A05Z&se=2021-02-13T01%3A07%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 01:15 UTC, opbld33 commented
Docs Build status updates of commit _[ae1f750](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae1f7504d9d0d519073886bbff007ef9e2e69972)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130114067074-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mzRnfaCNpgFl1Y3aMV2Xd%2BYVUSWWN3nxkXsIOdIF2Jo%3D&st=2021-01-13T01%3A10%3A21Z&se=2021-02-13T01%3A15%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 01:24 UTC, opbld32 commented
Docs Build status updates of commit _[4237566](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42375669452fe1f1cf7f5ebd26ee5487bbdd4e82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130122529903-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9a%2BB5nA5AnIymvlwOf6YuxljQCOXbl31dGyYmhnIFME%3D&st=2021-01-13T01%3A19%3A26Z&se=2021-02-13T01%3A24%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 20:50 UTC, opbld32 commented
Docs Build status updates of commit _[8e642c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8e642c6d09e9ae1b1ee9ec3c482c8e7f96e81106)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132048298778-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nnBLvgySlb8UNOZ8MaFZIUEuz8JKYiHRudbwC3RG6eg%3D&st=2021-01-13T20%3A45%3A36Z&se=2021-02-13T20%3A50%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 21:19 UTC, markwahl-msft requested changes
You should also have a change to entitlementmanagement-root.md and toc.yml to add these new methods.

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +|Delegated (work or school account)|EntitlementManagement.ReadWrite.All|
is the EntitlementManagement.Read.All delegated permission also supported?

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +|on|String|The list of options that can be used to filter on current user. This parameter can take 3 values: `target`, `createdBy` |
only 2 values are shown not 3

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +If successful, this function returns a `200 OK` response code and a [accessPackageAssignment](../resources/accesspackageassignment.md) collection in the response body.
What is the behavior if there are many (100s)?  Does it switch to OData paging or return all the matching objects?  If  requires paging then should call that out in the article so the implementors knows to expect odata.next.

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +GET /identityGovernance/entitlementManagement/accessPackageAssignmentRequests/FilterByCurrentUser
The article title is cancel but this URL looks like filter.

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +This method supports some of the OData query parameters to help customize the response. For example, to retrieve the access package that was requested, include `$expand=accessPackage` in the query. T
This does not appear to be applicable to cancel.

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +|Delegated (work or school account)|EntitlementManagement.ReadWrite.All|
see earlier comment about whether read permission is also supported.

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +`target` is used to get the `accessPackageAssignmentRequest` objects where the currently-logged-in user is the target, `createdBy` is used to get the `accessPackageAssignmentRequest` objects created
Questions -for the 'approvers', is this only for requests that are not yet completed (still pending) or completed as well?  E.g., suppose there was a policy that referenced a group, Alice and Bob were member of the group, and back in December Carol requested and his request was approved by Alice.  Now in January Bob makes a query with 'approver' - will he see Carol's request becaues at the time Bob of Carol's request was a member of the group?

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +`target` is used to get the `accessPackageAssignmentRequest` objects where the currently-logged-in user is the target, `createdBy` is used to get the `accessPackageAssignmentRequest` objects created
Questions - for multi-stage approval,  does approver include users who cannot yet approve because it hsan't reached their stage yet?  E.g., if Alice is a first stage approver and Bob is a second stage approver on a policy, and Carol makes a request, does Bob see Carol's request even if it's still waiting for Alice to approve?

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignment.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of accessPackageAssignmen
i think this is the wrong function, this article is assignment but this is talking about retrieving requests?

2021-01-13 21:19 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +|accessPackageAssignment|[accessPackageAssignment](../resources/accesspackageassignment.md)|The assignments to this access package. Read-only. Nullable.|
accessPackageAssignment is in the property table above this table?

2021-01-13 21:20 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageassignment.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of accessPackageAssignmen
or maybe copy-paste ?

2021-01-13 23:46 UTC, opbld33 commented
Docs Build status updates of commit _[0f505ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0f505ac74490482a818ff432294a9385eb057f89)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132344097561-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5L%2F4ZyLEkBB93lzGWepUL41tOG9itGe6cyiXjdPOtBE%3D&st=2021-01-13T23%3A41%3A09Z&se=2021-02-13T23%3A46%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 00:05 UTC, opbld30 commented
Docs Build status updates of commit _[31a543b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31a543b4d99ea37af2f8b673e369f893f98239a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) | [Details](#user-content-00685cff-d60628bc)
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11258) (graph-rest-beta) |

<a id="00685cff-d60628bc"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-MyAccessAPIs/api-reference/beta/toc.yml)
 - **Line 10976, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 10976, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 10977, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 10977, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11000, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 11000, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 11001, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11001, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101140004078994-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZQ%2BALG%2FF6x1CtbIidOja7lV1VyMbmWrh9%2BL7uIBqWao%3D&st=2021-01-14T00%3A00%3A53Z&se=2021-02-14T00%3A05%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-14 00:35 UTC, markwahl-msft commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +If successful, this function returns a `200 OK` response code and a [accessPackageAssignment](../resources/accesspackageassignment.md) collection in the response body.
For instance you could add to the description something like this:
```
When a result set spans multiple pages, Microsoft Graph returns that page with an `@odata.nextLink` property in the response that contains a URL to the next page of results. If that property is present, continue making additional requests with the `@odata.nextLink` URL in each response, until all the results are returned, as described in [paging Microsoft Graph data in your app](/graph/paging.md).
```

2021-01-14 17:33 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects filtered on currently-l
When referring to the product name, the words should be capitalized:  Azure AD Entitlement Management. 
Also, we use signed-in rather than logged-in.

In [Azure AD Entitlement Management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects filtered on the signed-in user.

2021-01-14 17:34 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +|Permission type|Permissions (from most to least privileged)|
Unfortunately, the stub generator produces incorrect text in the table header. It should be: (from least to most privileged)

2021-01-14 17:35 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +In the request URL, provide the following query parameters with values.
The first sentence isn't  needed.

2021-01-14 17:36 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +- `target` is used to get the `accessPackageAssignment` objects where the currently-logged-in user is the target.The resulting list includes all the assignments, current and expired, that the caller
```suggestion
- `target` is used to get the `accessPackageAssignment` objects where the signed-in user is the target. The resulting list includes all of the assignments, current and expired, that the caller has across all catalogs and access packages.
```

2021-01-14 17:36 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +- `createdBy` is used to get the `accessPackageAssignment` objects created by the currently-logged-in user.The resulting list includes all the assignments that the caller has created for themselves o
```suggestion
- `createdBy` is used to get the `accessPackageAssignment` objects created by the signed-in user. The resulting list includes all of the assignments that the caller has created for themselves or on behalf of others (such as in case of admin direct assignment), across all catalogs and access packages.
```

2021-01-14 17:38 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-list.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects. The resulting list inc
```suggestion
In [Azure AD Entitlement Management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects. The resulting list includes all of the assignments, current and expired, that the caller has access to read, across all catalogs and access packages.
```

2021-01-14 17:39 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), cancel [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) objects that are in a cancell
```suggestion
In [Azure AD Entitlement Management](../resources/entitlementmanagement-root.md), cancel [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) objects that are in a cancellable state: `accepted`, `pendingApproval`, `pendingNotBefore`, `pendingApprovalEscalated`.
```

2021-01-14 17:39 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-14 17:42 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +      "id": "String (identifier)",
The example should show  a real world example of the response. I would suggest calling the operation in Graph Explorer and copy the response here.

2021-01-14 17:42 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-list.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects. The resulting list inc
```suggestion
In [Azure AD Entitlement Management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects. The resulting list includes all the assignments, current and expired, that the caller has access to read, across all catalogs and access packages.
```

2021-01-14 17:43 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +description: "Cancel accessPackageAssignmentRequest objects that are in a cancellable state: `accepted`, `pendingApproval`, `pendingNotBefore`, `pendingApprovalEscalated`."
```suggestion
description: "Cancel accessPackageAssignmentRequest objects that are in a cancellable state.
```

2021-01-14 17:45 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +If successful, this function returns a `200 OK` response code and a [accessPackageAssignment](../resources/accesspackageassignment.md) collection in the response body.
```suggestion
If successful, this method returns a `200 OK` response code and a [accessPackageAssignment](../resources/accesspackageassignment.md) collection in the response body.
```

2021-01-14 17:46 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +If successful, this function returns a `200 OK` response code.  It does not return anything in the response body.
```suggestion
If successful, this method returns a `200 OK` response code.  It does not return anything in the response body.
```

2021-01-14 17:47 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +description: "Retrieve a list of accesspackageassignmentrequest objects filtered on currently-logged-in user."
```suggestion
description: "Retrieve a list of accesspackageassignmentrequest objects filtered on the signed-in user."
```

2021-01-14 17:48 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) objects filtered
```suggestion
In [Azure AD Entitlement Management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) objects filtered on the signed-in user.
```

2021-01-14 17:48 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-14 17:48 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +In the request URL, provide the following query parameters with values.
The first sentence isn't needed.

2021-01-14 17:50 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +|on|String|The list of options that can be used to filter on current user. This parameter can take 3 values: `target`, `createdBy` and `approver` |
```suggestion
|on|String|The list of options that can be used to filter on current user. Possible options are: `target`, `createdBy` and `approver` |
```

2021-01-14 17:58 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +- `target` is used to get the `accessPackageAssignmentRequest` objects where the currently-logged-in user is the target. The resulting list includes all the assignment requests, current and expired,
```suggestion
- `target` is used to get the `accessPackageAssignmentRequest` objects where the signed-in user is the target. The resulting list includes all the assignment requests, current and expired, that were requested by the called or for the caller, across all catalogs and access packages.
```

2021-01-14 17:59 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +- `createdBy` is used to get the `accessPackageAssignmentRequest` objects created by the currently-logged-in user. The resulting list includes all the assignment requests that the caller has created
```suggestion
- `createdBy` is used to get the `accessPackageAssignmentRequest` objects created by the signed-in user. The resulting list includes all the assignment requests that the caller has created for themselves or on behalf of others (such as in case of admin direct assignment), across all catalogs and access packages.
```

2021-01-14 18:01 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +- `approver` is used to get the `accessPackageAssignmentRequest` objects where the currently-logged-in user is an allowed approver in any contained `accessPackageAssignment/accessPackageAssignmentPol
```suggestion
- `approver` is used to get the `accessPackageAssignmentRequest` objects where the signed-in user is an allowed approver in any contained `accessPackageAssignment/accessPackageAssignmentPolicy/requestApprovalSettings/approvalStages` (`primaryApprovers` or `escalationApprovers`). The resulting list includes the assignment requests in *pending* state, across all catalogs and access packages and that need a decision from the caller. This list does not contain assignment requests in states other than *pending* nor assignment requests that do not require action from the signed-in user.
```

2021-01-14 18:02 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +    {
This example should show values rather than types.

2021-01-14 18:05 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to create an assignment for themselves (either *first assignment* or *renew* assignment to the access package), the value of the **requestType** property is `U
```suggestion
For a non-administrator user to request to create an assignment for themselves (either *first assignment* or *renew* assignment), the value of the *requestType* property is `UserAdd`, and the *accessPackageAssignment* property contains the ID of the users, the *assignmentPolicyId* property identifying the [accessPackageAssignmentPolicy](../resources/accesspackageassignmentpolicy.md), and the *accessPackageId* property identifying the [accessPackage](../resources/accesspackage.md). The user making the request must already exist in the directory.
```

2021-01-14 18:11 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +For a non-administrator user to cancel a request for themselves, the body has to contain the request `id` and `requestStatus`. The value of the **requestStatus** property is `cancelled`, and the **id
```suggestion
For a non-administrator user to cancel their own request, the body must contain the request `id` and `requestStatus`. The value of the *requestStatus* property is `cancelled`. The `id` is the identifier of the [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md).
```

2021-01-14 18:17 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to extend an assignment for themselves, the value of the **requestType** property is `UserExtend`, and the **accessPackageAssignment** property contains the `t
```suggestion
For a non-administrator user to request to extend their own assignments, the value of the *requestType* property is `UserExtend`. The *accessPackageAssignment* property contains the `targetId` with the `id` of the users. The *assignmentPolicyId* property identifies the [accessPackageAssignmentPolicy](../resources/accesspackageassignmentpolicy.md). The *accessPackageId* property identifies the [accessPackage](../resources/accesspackage.md). The user making the request must already exist in the directory.
```

2021-01-14 18:21 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +### Example 3: User requests a package and provide a justification
```suggestion
### Example 3: Request a package and provide a justification
```

2021-01-14 18:21 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +The following is an example of a request where the requestor requested an access package and provided a justification to the approver.
```suggestion
The following example shows how to request an access package and provide justification to the approver.
```

2021-01-14 18:23 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageassignment.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of accessPackageAssignmen
```suggestion
|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of accessPackageAssignment objects filtered on the signed-in user. This method supports parameter `on` to retrieve objects corresponding to current user being the `target`, or objects `createdBy` current user.|
```

2021-01-14 18:24 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +|[FilterByCurrentUser](../api/accesspackageassignmentrequest-filterbycurrentuser.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Retrieve the list of a
```suggestion
|[FilterByCurrentUser](../api/accesspackageassignmentrequest-filterbycurrentuser.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Retrieve the list of accessPackageAssignmentRequest objects filtered on the signed-in user. This method supports parameter `on` to retrieve objects corresponding to current user being the `target`, or objects `createdBy` current user, or objects where current user is an allowed `approver`.|
```

2021-01-14 18:25 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +|accessPackage|[accessPackage](../resources/accesspackage.md)|Read-only. Nullable.|
There is no description for this property.

2021-01-14 18:25 UTC, davidmu1 commented on api-reference/beta/resources/approval.md
> +description: "**The approval object associated with the accessPackageAssignmentRequest.**"
```suggestion
description: "The approval object associated with the accessPackageAssignmentRequest."
```

2021-01-14 18:26 UTC, davidmu1 commented on api-reference/beta/resources/approval.md
> +|id|String|ID of the `approval` object|
```suggestion
|id|String|The identifier of the approval object|
```

2021-01-14 18:27 UTC, davidmu1 commented on api-reference/beta/resources/approval.md
> +|steps|[approvalStage](../resources/approvalstage.md) collection|Used for the `approvalStages` property of approval settings in the `requestApprovalSettings` property of an [access package assignment
```suggestion
|steps|[approvalStage](../resources/approvalstage.md) collection|Used for the *approvalStages* property of approval settings in the *requestApprovalSettings* property of an [access package assignment policy](accesspackageassignmentpolicy.md). Specifies the primary, fallback, and escalation approvers of each stage.|
```

2021-01-14 18:27 UTC, davidmu1 commented on api-reference/beta/resources/entitlementmanagement-root.md
> +|[FilterByCurrentUser](../api/accesspackageassignmentrequest-filterbycurrentuser.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Retrieve the list of *
```suggestion
|[FilterByCurrentUser](../api/accesspackageassignmentrequest-filterbycurrentuser.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Retrieve the list of *accessPackageAssignmentRequest* objects filtered on the signed-in user.|
```

2021-01-14 18:28 UTC, davidmu1 commented on api-reference/beta/resources/entitlementmanagement-root.md
> +|[Cancel](../api/accesspackageassignmentrequest-cancel.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Cancel an **accessPackageAssignmentRequest** obj
```suggestion
|[Cancel](../api/accesspackageassignmentrequest-cancel.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Cancel an *accessPackageAssignmentRequest* object that is in a cancellable state: `accepted`, `pendingApproval`, `pendingNotBefore`, `pendingApprovalEscalated`.|
```

2021-01-14 18:28 UTC, davidmu1 commented on api-reference/beta/resources/entitlementmanagement-root.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignm
```suggestion
|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignment** objects filtered on the signed-in user.|
```

2021-01-14 18:29 UTC, davidmu1 commented on api-reference/beta/toc.yml
> +              name: FilterbyCurrentUser
Filter by current user

2021-01-14 18:31 UTC, davidmu1 commented
Don't forget the changelog entries: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-01-20 19:41 UTC, sbounouh reviewed
incorporated the suggested updates in the latest PR

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to create an assignment for themselves (either *first assignment* or *renew* assignment to the access package), the value of the **requestType** property is `U
ok

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to extend an assignment for themselves, the value of the **requestType** property is `UserExtend`, and the **accessPackageAssignment** property contains the `t
aligned with this and the previous paragraph

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +The following is an example of a request where the requestor requested an access package and provided a justification to the approver.
done

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/accesspackageassignment.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of accessPackageAssignmen
done

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/accesspackageassignmentrequest.md
> +|[FilterByCurrentUser](../api/accesspackageassignmentrequest-filterbycurrentuser.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Retrieve the list of a
done

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/approval.md
> +description: "**The approval object associated with the accessPackageAssignmentRequest.**"
ok

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/approval.md
> +|id|String|ID of the `approval` object|
ok

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/approval.md
> +|steps|[approvalStage](../resources/approvalstage.md) collection|Used for the `approvalStages` property of approval settings in the `requestApprovalSettings` property of an [access package assignment
ok

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/entitlementmanagement-root.md
> +|[FilterByCurrentUser](../api/accesspackageassignmentrequest-filterbycurrentuser.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Retrieve the list of *
done

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/entitlementmanagement-root.md
> +|[Cancel](../api/accesspackageassignmentrequest-cancel.md)|[accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md) collection|Cancel an **accessPackageAssignmentRequest** obj
ok

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/resources/entitlementmanagement-root.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignm
done

2021-01-20 19:41 UTC, sbounouh commented on api-reference/beta/toc.yml
> +              name: FilterbyCurrentUser
already added in the file

2021-01-20 19:47 UTC, opbld31 commented
Docs Build status updates of commit _[bec5d9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bec5d9b77b9db3e92447157423311dc5f86b4fcd)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-abef6189)

<a id="abef6189"></a>
###
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101201946312579-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eNI2si5xQ54qL0%2BPaoRgKDqFsWK9yNWoscxYBQrFYI0%3D&st=2021-01-20T19%3A42%3A08Z&se=2021-02-20T19%3A47%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 19:55 UTC, opbld31 commented
Docs Build status updates of commit _[cd97ed0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd97ed002febbcfcaf7b40538c8b10fcd074b5f5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-829c89d9)

<a id="829c89d9"></a>
###
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101201955052620-11258%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vyz%2BcIos6xDNTxyUX%2BbTskwp5xibQEu9mV77EWpt6ug%3D&st=2021-01-20T19%3A50%3A35Z&se=2021-02-20T19%3A55%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 17:00 UTC, closed without merging

2021-01-28 17:00 UTC, sbounouh commented
Created another newer PR: https://github.com/microsoftgraph/microsoft-graph-docs/pull/11361
Therefore closing this one.