Almars/organizationbranding
microsoftgraph/microsoft-graph-docs pull request #11264
Opened 2021-01-13 03:42 UTC by AlexanderMars

Migrating OrganizationalBranding API documentation from beta to v1.0

2021-01-13 03:43 UTC, opbld33 commented
Docs Build status updates of commit _[06a6e52](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06a6e52f0dfc6ddb86ed54f71e9e7d22672e2b04)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :x:Error | | [Details](#user-content-0b973580-528ab347)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :x:Error | | [Details](#user-content-57b46554-528ab347)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :x:Error | | [Details](#user-content-80b407ed-528ab347)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :x:Error | | [Details](#user-content-6fdb4c3b-528ab347)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :x:Error | | [Details](#user-content-f86a8b2d-528ab347)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :x:Error | | [Details](#user-content-cfc9db80-528ab347)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :x:Error | | [Details](#user-content-17d4c9a5-528ab347)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-528ab347)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-528ab347)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-528ab347)

<a id="0b973580-528ab347"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 99, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 103, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````

<a id="57b46554-528ab347"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/delete-organizationalbrandingproperties-java-snippets.md'.`````

<a id="80b407ed-528ab347"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 223, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 227, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 231, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?bra [...]

2021-01-13 03:59 UTC, opbld32 commented
Docs Build status updates of commit _[f778a43](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f778a4371c98d3a48a088fa14d933a7048f096c1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :x:Error | | [Details](#user-content-57b46554-6a7f3ca4)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :x:Error | | [Details](#user-content-80b407ed-6a7f3ca4)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :x:Error | | [Details](#user-content-6fdb4c3b-6a7f3ca4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :x:Error | | [Details](#user-content-f86a8b2d-6a7f3ca4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :x:Error | | [Details](#user-content-cfc9db80-6a7f3ca4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :x:Error | | [Details](#user-content-17d4c9a5-6a7f3ca4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-6a7f3ca4)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-6a7f3ca4)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-6a7f3ca4)

<a id="57b46554-6a7f3ca4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/delete-organizationalbrandingproperties-java-snippets.md'.`````

<a id="80b407ed-6a7f3ca4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 223, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 227, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 231, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 235, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````

<a id="6fdb4c3b-6a7f3ca4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch= [...]

2021-01-13 04:02 UTC, opbld30 commented
Docs Build status updates of commit _[61e0b5f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61e0b5fa5bdf6600e763f1671faac57d74b8bbc3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :x:Error | | [Details](#user-content-80b407ed-def46f57)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :x:Error | | [Details](#user-content-6fdb4c3b-def46f57)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :x:Error | | [Details](#user-content-f86a8b2d-def46f57)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :x:Error | | [Details](#user-content-cfc9db80-def46f57)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :x:Error | | [Details](#user-content-17d4c9a5-def46f57)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-def46f57)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-def46f57)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-def46f57)

<a id="80b407ed-def46f57"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 223, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 227, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 231, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 235, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````

<a id="6fdb4c3b-def46f57"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 135, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 139, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 143, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 147, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 223, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 227, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-pract [...]

2021-01-13 04:03 UTC, opbld34 commented
Docs Build status updates of commit _[981e472](https://github.com/microsoftgraph/microsoft-graph-docs/commits/981e472f866889538db7371da2ecd51df2683a35)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :x:Error | | [Details](#user-content-6fdb4c3b-c1160e03)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :x:Error | | [Details](#user-content-f86a8b2d-c1160e03)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :x:Error | | [Details](#user-content-cfc9db80-c1160e03)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :x:Error | | [Details](#user-content-17d4c9a5-c1160e03)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-c1160e03)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-c1160e03)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-c1160e03)

<a id="6fdb4c3b-c1160e03"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 135, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 139, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 143, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 147, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 223, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 227, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 231, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 235, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````

<a id="f86a8b2d-c1160e03"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md)
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 99, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````

<a id="cfc9db80-c1160e03"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microso [...]

2021-01-13 04:06 UTC, opbld33 commented
Docs Build status updates of commit _[a11df7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a11df7f26c5b3986b5849293c2fbe9d5739e5fec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :x:Error | | [Details](#user-content-f86a8b2d-a2f47af1)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :x:Error | | [Details](#user-content-cfc9db80-a2f47af1)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :x:Error | | [Details](#user-content-17d4c9a5-a2f47af1)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-a2f47af1)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-a2f47af1)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-a2f47af1)

<a id="f86a8b2d-a2f47af1"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md)
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 99, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````

<a id="cfc9db80-a2f47af1"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/delete-organizationalbrandingproperties-java-snippets.md'.`````

<a id="17d4c9a5-a2f47af1"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md)
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 80, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 138, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 142, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 146, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 220, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 224, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 228, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-u [...]

2021-01-13 04:07 UTC, opbld31 commented
Docs Build status updates of commit _[656ae68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/656ae684dfd767e4e24fb9349694569bf0f14ef4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :x:Error | | [Details](#user-content-cfc9db80-b88fddd6)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :x:Error | | [Details](#user-content-17d4c9a5-b88fddd6)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-b88fddd6)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-b88fddd6)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-b88fddd6)

<a id="cfc9db80-b88fddd6"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md)
 - **Line 62, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/delete-organizationalbrandingproperties-java-snippets.md'.`````

<a id="17d4c9a5-b88fddd6"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md)
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 80, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 134, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 138, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 142, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 146, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 220, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 224, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 228, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 232, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-organizationalbrandingproperties-java-snippets.md'.`````

<a id="87d94049-b88fddd6"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes- [...]

2021-01-13 04:09 UTC, opbld32 commented
Docs Build status updates of commit _[9c0a500](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9c0a500d74f1a0a8608edb9de7cdf9ecf9674474)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :x:Error | | [Details](#user-content-87d94049-a321f7be)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | | [Details](#user-content-1ef9a9bd-a321f7be)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | | [Details](#user-content-c0f00fbd-a321f7be)

<a id="87d94049-a321f7be"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 139, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 143, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 147, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 151, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````
 - **Line 236, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-organizationalbrandingproperties-csharp-snippets.md'.`````
 - **Line 240, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-organizationalbrandingproperties-javascript-snippets.md'.`````
 - **Line 244, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-organizationalbrandingproperties-objc-snippets.md'.`````
 - **Line 248, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-organizationalbrandingproperties-java-snippets.md'.`````

<a id="1ef9a9bd-a321f7be"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-a321f7be"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130407315516-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SF0vwl1ttyIYiEjsm2B0OUZyzPWgoROgm32QsggR4Yg%3D&st=2021-01-13T04%3A04%3A14Z&se=2021-02-13T04%3A09%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.mic [...]

2021-01-13 04:10 UTC, opbld31 commented
Docs Build status updates of commit _[10c04b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10c04b2ddc32c3a38dd8b00b9766dd86f3df1156)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-e75fd6a4)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-e75fd6a4)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-e75fd6a4"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-e75fd6a4"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101130408069281-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zgrHON0EcKTbNOn2iOHZNUXwp7iTGLH%2BS1dbFPSt2g4%3D&st=2021-01-13T04%3A05%3A40Z&se=2021-02-13T04%3A10%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668 [...]

2021-01-14 20:33 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +Create an [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md) object. This creates the default branding and optionally a localized branding at the same time. The defa
```suggestion
Create an [organizationalBrandingProperties](../resources/organizationalbrandingproperties.md) object. This creates the default branding and optionally a localized branding. The default branding is loaded when a localized branding set isn't configured for the user's browser language.
```

2021-01-14 20:34 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +If branding is already configured, PUT will overwrite all existing values regardless of what's in the request body. PATCH will only overite the values that are included in the request body, leaving t
```suggestion
If branding is already configured, PUT overwrites all existing values regardless of what's in the request body. PATCH only overwrites the values that are included in the request body, leaving the values not included unchanged.
```

2021-01-14 20:52 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
If you say that only some of the parameters are supported, you need to list them.

2021-01-14 20:52 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +|backgroundColor|String|Color that will appear in place of the background image in low-bandwidth connections. The primary color of your banner logo or your organization color is recommended to be use
```suggestion
|backgroundColor|String|Color that appears in place of the background image in low-bandwidth connections. The primary color of your banner logo or your organization color is recommended to be used here. Specify this in hexadecimal (for example, white is #FFFFFF).|
```

2021-01-14 20:54 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +|backgroundImage|Stream|Image that appears as the background of the sign in page. .png or .jpg not larger than 1920x1080 and smaller than 300kb. A smaller image will reduce bandwidth requirements and
```suggestion
|backgroundImage|Stream|Image that appears as the background of the sign-in page. The image is a .png or .jpg that is not larger than 1920x1080 and smaller than 300kb. A smaller image will reduce bandwidth requirements and make page loads more performant.|
```

2021-01-14 20:55 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +|bannerLogo|Stream|A banner version of your company logo which appears appears on the sign-in page. .png or .jpg no larger than 36x245px. We recommend using a transparent image with no padding around
```suggestion
|bannerLogo|Stream|A banner version of your company logo that appears on the sign-in page. The banner is a .png or .jpg no larger than 36x245px. We recommend using a transparent image with no padding around the logo.|
```

2021-01-14 20:55 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +|squareLogo|Stream|Square version of your company logo. This appears in Windows 10 out-of-box (OOBE) experiences and when Windows Autopilot is enabled for deployment. .png or .jpg no larger than 240x
```suggestion
|squareLogo|Stream|Square version of your company logo. This appears in Windows 10 out-of-box (OOBE) experiences and when Windows Autopilot is enabled for deployment. The logo is a .png or .jpg no larger than 240x240px and no more than 10kb in size. We recommend using a transparent image with no padding around the logo.|
```

2021-01-14 20:56 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +|usernameHintText|String|String that shows as the hint in the username textbox on the sign in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
```suggestion
|usernameHintText|String|The hint in the username textbox on the sign-in screen. This text must be Unicode, without links or code, and can't exceed 64 characters.|
```

2021-01-14 20:58 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +---
Remove line 92.

2021-01-14 20:59 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +# [HTTP](#tab/http)
remove line 73. This comes from an auto-generation of code snippets. It will be automatically added.

2021-01-14 21:01 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +In this case, the default branding object is set. Localized branding for en-US is also set due to the Content-Language in the header, even though the en-US branding set is not returned in the respons
```suggestion
In this case, the default branding object is set. Localized branding for en-US is also set due to the Content-Language header, even though the en-US branding set is not returned in the response. The Content-Language header in the request is optional, and if not present, only sets the default branding.
```

2021-01-14 21:04 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-delete.md
> +# [HTTP](#tab/http)
remove line 52

2021-01-14 21:04 UTC, davidmu1 commented on api-reference/v1.0/api/organizationalbrandingproperties-delete.md
> +---
remove line 63.

2021-02-05 01:01 UTC, opbld31 commented
Docs Build status updates of commit _[b8cf7b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8cf7b6edee80a1a754d4ec93544b24049abca8a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-16034a28)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-16034a28)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-16034a28"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-16034a28"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050059554004-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vCXHrpRnVSXnVS%2FuClZxElWm3t3Wf%2F2SA9Oh2xpa7K8%3D&st=2021-02-05T00%3A56%3A18Z&se=2021-03-08T01%3A01%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-4166 [...]

2021-02-05 01:02 UTC, opbld31 commented
Docs Build status updates of commit _[92abb08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92abb08c420fa1b6f9b07efc8452e85746a41ebb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-f57dc73f)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-f57dc73f)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-f57dc73f"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-f57dc73f"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050101100027-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2NF5hoqHetu1AVwRWrO4PEY3xrr4xxtZbjqCIZ1TLdU%3D&st=2021-02-05T00%3A57%3A35Z&se=2021-03-08T01%3A02%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07 [...]

2021-02-05 01:03 UTC, opbld31 commented
Docs Build status updates of commit _[694a2d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/694a2d73cb0601bbbeee5816ae669a3e27272ee5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-5663a794)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-5663a794)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-5663a794"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-5663a794"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050101424594-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2c6qWvYiWsm43w5%2FXEemfcZusENFvebPf8RaygfeIvw%3D&st=2021-02-05T00%3A58%3A51Z&se=2021-03-08T01%3A03%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-05 01:05 UTC, opbld31 commented
Docs Build status updates of commit _[f7b8dac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7b8dace7e6b7e2ea9ea82378fc795cd4319fa2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-0d190416)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-0d190416)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-0d190416"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-0d190416"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050103555660-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oA7LVvxIpKW80OK%2F7deBGCo97lZJluSkjgSpJi9a1HY%3D&st=2021-02-05T01%3A00%3A03Z&se=2021-03-08T01%3A05%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-05 01:11 UTC, opbld33 commented
Docs Build status updates of commit _[fe438ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fe438ecb6de251121e89456fe3b8eec961841c01)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-033e3029)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-033e3029)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-033e3029"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-033e3029"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050110071520-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PRuBmkXisdyNJKwHTaveqdrbTYoSQ4goOiy5CiuGuXA%3D&st=2021-02-05T01%3A06%3A11Z&se=2021-03-08T01%3A11%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07 [...]

2021-02-05 01:16 UTC, opbld34 commented
Docs Build status updates of commit _[684a55b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/684a55b3190af58408314e5f18635c801537316d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-8ca320c1)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-8ca320c1)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-8ca320c1"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-8ca320c1"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050115542460-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HA%2F8vDtr3wfwBW8xR2AaSGc0zgBTu5RxypXMqM1cmBA%3D&st=2021-02-05T01%3A11%3A54Z&se=2021-03-08T01%3A16%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-05 01:26 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +
We should have an introductory sentence here, like, "In the request body, include a JSON representation of an **organizationalBrandingProperties** object. The following table lists the required properties."

2021-02-05 01:29 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingproperties-update.md
> +# [HTTP](#tab/http)
Delete the stray H1 here.

2021-02-05 01:32 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md
> +# [HTTP](#tab/http)
Delete.

2021-02-05 01:34 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
> +# Update Localized organizationalbrandingproperties
Localized -> localized

2021-02-05 01:35 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
> +# [HTTP](#tab/http)
Global: Delete all HTTP H1s. These will get added when the snippet generation process runs.

2021-02-05 01:35 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md
> +---
Be sure to delete these stray lines as well.

2021-02-05 01:37 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +        {
Instead of adding a new item to an existing ChangeList, add a new ChangeList item. You'll want to use today's date for the CreatedDateTime.

2021-02-05 08:09 UTC, paulodero requested changes
changelog generated is incomplete. All the schema changes made must be reflected in changelog.

2021-02-05 19:25 UTC, opbld32 commented
Docs Build status updates of commit _[729fc7c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/729fc7ca8fbac968928d30ff69f1b91542867005)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-803a97dd)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-803a97dd)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-803a97dd"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-803a97dd"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051923594429-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uVBBjyn9pbHt5MfMu%2BaahLHNXqLniqoeX4lHNXnULKw%3D&st=2021-02-05T19%3A20%3A10Z&se=2021-03-08T19%3A25%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-05 19:26 UTC, opbld31 commented
Docs Build status updates of commit _[ece4eae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ece4eaeb50fa14cd654860c70f4173c32ca81eff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-704e6bdd)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-704e6bdd)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-704e6bdd"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-704e6bdd"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051925175591-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OlBtUkZHwJ20soJ2wXuSYWFmYvdP8c%2Bx3fMpX4BtANw%3D&st=2021-02-05T19%3A21%3A24Z&se=2021-03-08T19%3A26%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-05 19:30 UTC, opbld34 commented
Docs Build status updates of commit _[5271957](https://github.com/microsoftgraph/microsoft-graph-docs/commits/52719570ca0a0e3e6feea05240a28c4d4439d4c6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-41256a0f)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-41256a0f)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-41256a0f"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-41256a0f"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051928572543-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RpPD8owbxSx0N2Z%2FcUx63xUkAmpz4vh7pew8PhzOOvE%3D&st=2021-02-05T19%3A25%3A05Z&se=2021-03-08T19%3A30%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-05 19:31 UTC, opbld30 commented
Docs Build status updates of commit _[0c68521](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c685218359f550a5cb1151a05773b490322b12b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-e3e90c27)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-e3e90c27)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-e3e90c27"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-e3e90c27"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051929537013-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WqjSWP9eBddvrQk6zvdq5%2B928xDg5vMfsnaXCL7kCzo%3D&st=2021-02-05T19%3A26%3A21Z&se=2021-03-08T19%3A31%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-06 02:25 UTC, opbld30 commented
Docs Build status updates of commit _[f15a3b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f15a3b1abeef12e1043aa84a201fa53420cf9fae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-68f90a54)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-68f90a54)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-68f90a54"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c0f00fbd-68f90a54"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060224195325-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jwcG7Pg6KxVsaViiA2wJLQMu7tPqCW%2Fri9MkyqusBhM%3D&st=2021-02-06T02%3A20%3A24Z&se=2021-03-09T02%3A25%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c [...]

2021-02-06 03:54 UTC, opbld31 commented
Docs Build status updates of commit _[21daa74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21daa74f093e7b483b7b7f3e20f0c502c1f2bf46)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-db48da6c)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-db48da6c)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-db48da6c"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-db48da6c"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060353306213-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6cB%2Bau0OxiBIZ83%2Fnfqxe0xu2Sy3FkcXgbpFSGEf1LQ%3D&st=2021-02-06T03%3A49%3A36Z&se=2021-03-09T03%3A54%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https:/ [...]

2021-02-06 03:57 UTC, opbld32 commented
Docs Build status updates of commit _[6e5864a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e5864a0e2a6dd537a78718e709fcae31c6f3a47)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-1d4f0480)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-1d4f0480)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-1d4f0480"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-1d4f0480"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060356071574-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XDdXZHVbEwRAqYtnaw4D8L4Ys8hfATAjsD9QKVMc%2BMc%3D&st=2021-02-06T03%3A52%3A25Z&se=2021-03-09T03%3A57%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://o [...]

2021-02-08 10:23 UTC, opbld34 commented
Docs Build status updates of commit _[f3f3fe7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3f3fe7cd34a3231b49f0a887446557940237b20)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-8d74dd52)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-8d74dd52)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-8d74dd52"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-8d74dd52"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081022352802-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Lqe9NUQp%2FRmwhhZE6DSJ2w%2BK7SsIKb8nhoWvBP0V65Q%3D&st=2021-02-08T10%3A18%3A39Z&se=2021-03-11T10%3A23%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https:/ [...]

2021-02-08 10:25 UTC, opbld32 commented
Docs Build status updates of commit _[2b8b83a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b8b83a24c8d974bc06af39af516ebbed21e1f4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-102d406a)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-102d406a)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-102d406a"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-102d406a"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081022484698-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xw9tqeXhvd4JiKeTczZUUHEEeZaUZzQfxZejfOf1mbo%3D&st=2021-02-08T10%3A20%3A30Z&se=2021-03-11T10%3A25%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops [...]

2021-02-08 10:26 UTC, opbld32 commented
Docs Build status updates of commit _[6e499e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e499e7d8de58cacd12c12ef53591254a4705cd3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-c5d73ed6)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-c5d73ed6)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-c5d73ed6"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-c5d73ed6"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081023592402-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UwwDMNaRf%2FqQVlzGnx%2BNxURjhN3ZMX20K1yNLY%2FlmU4%3D&st=2021-02-08T10%3A21%3A44Z&se=2021-03-11T10%3A26%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https [...]

2021-02-08 10:27 UTC, opbld33 commented
Docs Build status updates of commit _[7f05d34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f05d348d6d4b5d50c3b743a10f78c8c78c11260)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-70886b74)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-70886b74)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-70886b74"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-70886b74"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081026068483-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DfKimYv35bYDxZ8PU%2Bp3z0HK62Y9rLWTkrDrA%2FRsBNk%3D&st=2021-02-08T10%3A22%3A54Z&se=2021-03-11T10%3A27%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https:/ [...]

2021-02-08 10:29 UTC, opbld33 commented
Docs Build status updates of commit _[5500cf5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5500cf5d6ac0ed8aa9c90cdc3fba62fd797c302e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-8133dacd)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-8133dacd)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-8133dacd"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-8133dacd"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081027228130-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MFbDIZe7RUr2%2B64ENv0y64UHLBgUiGPVgvVwLaZxt3Y%3D&st=2021-02-08T10%3A24%3A05Z&se=2021-03-11T10%3A29%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://o [...]

2021-02-08 10:30 UTC, FaithOmbongi reviewed
Updated ms.prod to the new values.

2021-02-16 19:32 UTC, opbld34 commented
Docs Build status updates of commit _[c8c83b3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8c83b356f3d913c55d26477c4e2abc70f88fe1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-0b973580-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-74e66d0e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-74e66d0e)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-74e66d0e)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-74e66d0e)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-74e66d0e)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0b973580-74e66d0e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57b46554-74e66d0e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-74e66d0e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-74e66d0e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-74e66d0e"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organi [...]

2021-02-16 19:37 UTC, opbld30 commented
Docs Build status updates of commit _[7afb690](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7afb69072a0814992b055711e5568d37bc91d4db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-0b973580-f859e651)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-f859e651)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-f859e651)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-f859e651)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-f859e651)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-f859e651)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-f859e651)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-f859e651)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-f859e651)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-f859e651)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-f859e651)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0b973580-f859e651"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 5, Column 1**: **[Warning-yaml-header-syntax-error]** `````While parsing a block mapping, did not find expected key.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="57b46554-f859e651"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-f859e651"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-f859e651"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-refere [...]

2021-02-16 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[db80000](https://github.com/microsoftgraph/microsoft-graph-docs/commits/db8000052093138c2344ffd6bbc1b6a6219f098b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-ebef644b)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-ebef644b)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-ebef644b)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-ebef644b)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-ebef644b)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-ebef644b)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-ebef644b)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-ebef644b)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-ebef644b)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-ebef644b)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="57b46554-ebef644b"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-ebef644b"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-ebef644b"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-ebef644b"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cfc9db80-ebef644b"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbr [...]

2021-02-16 19:39 UTC, opbld30 commented
Docs Build status updates of commit _[f10b400](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f10b400dc74143b761d1e76567d557fd4612d050)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-eac3bc35)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-eac3bc35)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-eac3bc35)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-eac3bc35)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-eac3bc35)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-eac3bc35)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-eac3bc35)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-eac3bc35)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-eac3bc35)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="80b407ed-eac3bc35"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-eac3bc35"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-eac3bc35"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cfc9db80-eac3bc35"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="17d4c9a5-eac3bc35"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api- [...]

2021-02-16 19:41 UTC, opbld32 commented
Docs Build status updates of commit _[b94c83b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b94c83ba54f87f5f8583fd31ca0e43cf881d4b5b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-50e4dabf)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-50e4dabf)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-50e4dabf)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-50e4dabf)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-50e4dabf)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-50e4dabf)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-50e4dabf)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-50e4dabf)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="6fdb4c3b-50e4dabf"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-50e4dabf"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cfc9db80-50e4dabf"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="17d4c9a5-50e4dabf"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="87d94049-50e4dabf"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-refer [...]

2021-02-16 19:43 UTC, opbld33 commented
Docs Build status updates of commit _[c4328cc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4328cc8d95abd363bf6d9cb8f14664e77373d9c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-80b65a24)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-80b65a24)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-80b65a24)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-80b65a24)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-80b65a24)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-80b65a24)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="cfc9db80-80b65a24"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="17d4c9a5-80b65a24"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="87d94049-80b65a24"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ef9a9bd-80b65a24"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c0f00fbd-80b65a24"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/he [...]

2021-02-16 19:44 UTC, opbld34 commented
Docs Build status updates of commit _[ea14303](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea14303897a6aa5e0670fcebd6077770de611e2c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-113a01d5)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-113a01d5)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-113a01d5)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-113a01d5"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

<a id="5cdb7751-113a01d5"></a>
### [api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ef9a9bd-113a01d5"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'dkershaw10' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161942373833-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IXNveajK7Ppv7ISGV [...]

2021-02-16 19:45 UTC, opbld31 commented
Docs Build status updates of commit _[613b3b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/613b3b72d9c93d7304c9aa4c6fe3e96392952883)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-c116a8f2)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-c116a8f2)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-c116a8f2)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="5cdb7751-c116a8f2"></a>
### [api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ef9a9bd-c116a8f2"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 2, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'dkershaw10' is not a valid Microsoft alias.`````

<a id="c0f00fbd-c116a8f2"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'adimitui' is not a valid Microsoft alias.`````
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161943595945-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P9CT8Z02II9UkQOH [...]

2021-02-16 20:02 UTC, opbld34 commented
Docs Build status updates of commit _[53eb791](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53eb7918292333d5e78629756e2edefd7736756d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-b9ae63ab)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-b9ae63ab"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102162000534930-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LWgpEtOMCGf6a83kLcwCKXKeC7DevcqYeN8WUoX3r98%3D&st=2021-02-16T19%3A57%3A37Z&se=2021-03-19T20%3A02%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 20:40 UTC, opbld33 commented
Docs Build status updates of commit _[25c52d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25c52d8ced7a958bdf884e03ca1088cb58aa4737)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-703de605)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-703de605"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102162039062923-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KosRvgqQ6%2F03qOrmyKBn1l7V3nSFQGbrMhk9j3fXkVQ%3D&st=2021-02-16T20%3A35%3A16Z&se=2021-03-19T20%3A40%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 20:41 UTC, opbld32 commented
Docs Build status updates of commit _[4ef23d0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ef23d00bd9170a9f36c95bb138a0c06504a988c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-95e47620)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-95e47620"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102162040159187-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Buqc1CVfpua0EyXbMGoCVIbyGFdaVomPUS3DXQzOaiY%3D&st=2021-02-16T20%3A36%3A34Z&se=2021-03-19T20%3A41%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 02:29 UTC, opbld31 commented
Docs Build status updates of commit _[34b001b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34b001b19dacf13ad159203bc92fec54100258a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-35b0bd6c)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-35b0bd6c"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102162335436917-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u46Rdh9LU9zPsFBhEYOjClGRol5ttCk9yJzcSdgdl0w%3D&st=2021-02-17T02%3A24%3A50Z&se=2021-03-20T02%3A29%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 02:53 UTC, opbld30 commented
Docs Build status updates of commit _[24a2b01](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24a2b018c5be274a922aa24a91b4eff27a4274c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ace1a10f)

<a id="ace1a10f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170244569438-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gDW%2BlveeYmijDG2I03zPOkgL7bFsDVj62WPwe%2FG96C8%3D&st=2021-02-17T02%3A48%3A56Z&se=2021-03-20T02%3A53%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 02:59 UTC, opbld33 commented
Docs Build status updates of commit _[12e6cf7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12e6cf7da5a628fe71c54171db3814871d6e2d78)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-8ecb4a0e)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-8ecb4a0e"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 11, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(11,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170256355039-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w9pOYKidD0bzmEJgPgvVfd6ZI6pqdrn1j2bhWyxX6cg%3D&st=2021-02-17T02%3A54%3A23Z&se=2021-03-20T02%3A59%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 04:45 UTC, opbld34 commented
Docs Build status updates of commit _[f1e5b0f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1e5b0fa898dad3587405c619e471d1012b29d56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-5bd50709)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-5bd50709"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 11, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(11,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170443353209-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w6prqo60UR1WmoppgE2vKHsdgbf9Pe4HkNnrpGFu%2BXY%3D&st=2021-02-17T04%3A40%3A41Z&se=2021-03-20T04%3A45%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 04:59 UTC, opbld30 commented
Docs Build status updates of commit _[5ce425a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5ce425ae26ba2627d95e8f0bc5804a8e54e5110a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-7cc893f1)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="c0f00fbd-7cc893f1"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 3, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(3,8)'. Titles must be unique within a docset.`````
 - **Line 11, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(11,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170458427168-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ycu%2F8fbO0vHYTCDcU3d%2F3c48hwf4bxTVPGEW4AE7Stk%3D&st=2021-02-17T04%3A54%3A53Z&se=2021-03-20T04%3A59%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 06:17 UTC, FaithOmbongi commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +ms.author: "almars"
I believe we're no longer using/exposing the ms.author property. API doctor will flag its absence as a warning but this might be resolved in the near future. cc @Lauragra can confirm.

2021-02-17 06:22 UTC, FaithOmbongi commented on api-reference/v1.0/resources/azure-ad-overview.md
> +ms.prod: "identity-and-sign-in"
I believe the correct ms.prod for the Azure AD overview file is `identity-access` - because this is the overview file for the root node. `identity-and-sign-in` ms.prod is for docs in the **Identity and sign-in** sub-node.

2021-02-17 15:50 UTC, opbld34 commented
Docs Build status updates of commit _[4ba3697](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ba36979c15d019dce282ec25df3afb720a0429f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bc67b8a0)

<a id="bc67b8a0"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171550127710-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1Lt%2Fih%2BZwZWisRLRNlc13lv520qDvp7OUNRaZT3aRsk%3D&st=2021-02-17T15%3A45%3A35Z&se=2021-03-20T15%3A50%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 15:50 UTC, AlexanderMars commented on api-reference/v1.0/resources/azure-ad-overview.md
> +ms.prod: "identity-and-sign-in"
updated

2021-02-17 15:58 UTC, opbld31 commented
Docs Build status updates of commit _[cb752a5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb752a5d79a759ecf88b8b679f14646ab9efe979)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6209ee2a)

<a id="6209ee2a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171558132247-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LcSsGn8ZZVXqmYuy6PYEF1ZH49aWxGk7Dq%2BQT6OfYj0%3D&st=2021-02-17T15%3A53%3A31Z&se=2021-03-20T15%3A58%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 16:00 UTC, opbld31 commented
Docs Build status updates of commit _[4e10615](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e106151e73526aab826e1a515cddb951e97c6c9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4a14d00e)

<a id="4a14d00e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171558283393-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J5w531nd21i0KEfZDXAm7h2dAJAMmYTCJRsfiCOlFp0%3D&st=2021-02-17T15%3A54%3A58Z&se=2021-03-20T15%3A59%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 16:00 UTC, opbld30 commented
Docs Build status updates of commit _[d815dfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d815dfccafb5eeb3729710bb76bee50271478455)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1b6ed13a)

<a id="1b6ed13a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171559498432-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kbD95XzsSQjUM%2BePW4kVu9xZiDkuVhQb4tjdce5JUSA%3D&st=2021-02-17T15%3A55%3A34Z&se=2021-03-20T16%3A00%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 16:01 UTC, opbld31 commented
Docs Build status updates of commit _[436f0f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/436f0f1825485cfc7b77e349927faf4bd4e14534)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b507e37f)

<a id="b507e37f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171600064150-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pp6FFoGSJxpkmT%2FS1Fv7MhLjhuoc9mfn9lCory1Ln0M%3D&st=2021-02-17T15%3A56%3A00Z&se=2021-03-20T16%3A01%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 16:01 UTC, opbld30 commented
Docs Build status updates of commit _[078dd6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/078dd6d2adc91b4f776f057f45452d75d9a2cae4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-887826bd)

<a id="887826bd"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171600534956-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cdQmqY44v8gjYdm5Uprglx1RUVDUtq1JWU%2FcTZ1Ya%2Bw%3D&st=2021-02-17T15%3A56%3A14Z&se=2021-03-20T16%3A01%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 16:01 UTC, opbld30 commented
Docs Build status updates of commit _[8ccd5d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ccd5d3f57586f81a66a3ff1d51b0ce74802d0ed)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d192196c)

<a id="d192196c"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171601288556-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tI6XngtCYMku2hLBJhnanILPJD6lgZaoWKWjdskAHEU%3D&st=2021-02-17T15%3A56%3A49Z&se=2021-03-20T16%3A01%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 16:22 UTC, opbld32 commented
Docs Build status updates of commit _[afd582e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/afd582e900723af670e3ad6a2db3d08ac41444bd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-0b973580-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-d7c2ab3e)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-d7c2ab3e)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-d7c2ab3e)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-d7c2ab3e)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-d7c2ab3e)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0b973580-d7c2ab3e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57b46554-d7c2ab3e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-d7c2ab3e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-d7c2ab3e"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-d7c2ab3e"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organi [...]

2021-02-17 16:23 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +ms.author: "almars"
Updated

2021-02-17 16:41 UTC, opbld32 commented
Docs Build status updates of commit _[8a84cca](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a84cca085863066b7d4e78c92c32b65bcccd2a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-0b973580-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-9d25d2c4)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-9d25d2c4)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-9d25d2c4)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-9d25d2c4)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-9d25d2c4)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0b973580-9d25d2c4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57b46554-9d25d2c4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-9d25d2c4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-9d25d2c4"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-9d25d2c4"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organi [...]

2021-03-03 18:00 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingproperties-get.md
> +# [HTTP](#tab/http)
Global: Please remove these HTTP H1s. They should be removed when snippet links are removed.

2021-03-03 18:01 UTC, Lauragra commented on api-reference/v1.0/api/organizationalbrandingproperties-get.md
> +---
Global: Please remove these stray lines as well.

2021-03-03 18:02 UTC, Lauragra commented
@davidmu1 , @FaithOmbongi , can you please verify and approve this PR? It looks like a large volume of changes in the changelog file; please take a look. Thanks.

2021-03-04 02:08 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingproperties-get.md
> +# [HTTP](#tab/http)
HTTP H1s were removed.

2021-03-04 02:10 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingproperties-get.md
> +---
done

2021-03-04 04:17 UTC, opbld31 commented
Docs Build status updates of commit _[2a8bcb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a8bcb6383c5af65b2f57c7db7add761ffb808b5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-0b973580-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-cfdf247a)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-cfdf247a)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-cfdf247a)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-cfdf247a)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-cfdf247a)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0b973580-cfdf247a"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57b46554-cfdf247a"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-cfdf247a"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-cfdf247a"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-cfdf247a"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organi [...]

2021-03-04 04:19 UTC, opbld33 commented
Docs Build status updates of commit _[f875fa9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f875fa915fd4efa4ff93119465fcf2f2c3f9bbbf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-0b973580-68b577ed)
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-57b46554-68b577ed)
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-80b407ed-68b577ed)
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-6fdb4c3b-68b577ed)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-f86a8b2d-68b577ed)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-cfc9db80-68b577ed)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-17d4c9a5-68b577ed)
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-87d94049-68b577ed)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-68b577ed)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-68b577ed)
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-5cdb7751-68b577ed)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0b973580-68b577ed"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57b46554-68b577ed"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="80b407ed-68b577ed"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6fdb4c3b-68b577ed"></a>
### [api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f86a8b2d-68b577ed"></a>
### [api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organi [...]

2021-03-08 19:38 UTC, AlexanderMars commented
@davidmu1 , @FaithOmbongi , could you please verify and approve this PR? The schema mapping to v.1 was already completed over 1 week ago. Thanks.

2021-03-09 07:49 UTC, opbld32 commented
Docs Build status updates of commit _[5c78f59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c78f59e2d23ddc0022cc117cbc9725efc92a3ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-2c30e7a9)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-2c30e7a9)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-2c30e7a9"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-2c30e7a9"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090748247453-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ukiSnBpSJyXgJxrq%2BAE21HbEXB4qCJyQRfeiJhtKTZs%3D&st=2021-03-09T07%3A44%3A48Z&se=2021-04-09T07%3A49%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external de [...]

2021-03-09 08:41 UTC, opbld34 commented
Docs Build status updates of commit _[ee89df6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ee89df674c4f6e4beb208d5a842cdc66a0a64b90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-9ad4f528)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-9ad4f528)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-9ad4f528"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-9ad4f528"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090839486548-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hGZNKngx%2BT4RIX1vfEJcrNPTFwyzB%2FSqfcjMv0H6iJo%3D&st=2021-03-09T08%3A36%3A03Z&se=2021-04-09T08%3A41%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external  [...]

2021-03-09 09:22 UTC, opbld33 commented
Docs Build status updates of commit _[8d7a67d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d7a67d1ae1cc443fcf242022dc00989cff29fdf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-ef478f64)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-ef478f64)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-ef478f64"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-ef478f64"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090921125406-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7UXbCen2g0B9ouqrw%2FHLwLIa3DS5jTF3e9utL%2BIEmI8%3D&st=2021-03-09T09%3A17%3A21Z&se=2021-04-09T09%3A22%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external  [...]

2021-03-09 19:00 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingproperties-create.md
> +
The section was removed. Marking as resolved.

2021-03-09 19:01 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingproperties-get.md
> +
The section was removed. Marking as resolved.

2021-03-09 19:01 UTC, opbld33 commented
Docs Build status updates of commit _[50688df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50688df872057630f348c2d4fffb16a16eb9a9ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-c427ea16)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-c427ea16)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-c427ea16"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-c427ea16"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103091900151385-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ei7%2BWIkeTQQqlk7PGYRMwGLHmP7jNOS%2BukOAnprDl9M%3D&st=2021-03-09T18%3A56%3A41Z&se=2021-04-09T19%3A01%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external  [...]

2021-03-09 19:02 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md
> +
The section was removed. Marking as resolved.

2021-03-09 19:04 UTC, opbld34 commented
Docs Build status updates of commit _[6913dfc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6913dfcc96e64d98048a19e5664572d3fae52090)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-ef8bb60c)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-ef8bb60c)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-ef8bb60c"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-ef8bb60c"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103091902123308-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HCHlQ1OpMfsYe7FLYL62hBHMa64fXM%2Bv7%2FulWCUWc3w%3D&st=2021-03-09T18%3A59%3A31Z&se=2021-04-09T19%3A04%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external  [...]

2021-03-09 19:05 UTC, opbld31 commented
Docs Build status updates of commit _[b5272ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5272ecaaf6984033f7e34c47137515efce4f589)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-5f998835)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-5f998835)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-5f998835"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-5f998835"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103091903470977-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WhBWI2f%2B2jK%2BChl2JdalByMlbeIo7X33fgSV7Pi8IpM%3D&st=2021-03-09T19%3A00%3A55Z&se=2021-04-09T19%3A05%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external  [...]

2021-03-09 19:10 UTC, AlexanderMars commented on api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md
> +
The section was removed. Marking as resolved.

2021-03-10 00:57 UTC, AlexanderMars commented on changelog/Microsoft.DirectoryServices.json
> +      "ChangeList": [
done

2021-03-10 00:57 UTC, opbld32 commented
Docs Build status updates of commit _[9153151](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9153151bd46769029e3a9994208860cc66e0aa4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-7523aa01)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-7523aa01)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-7523aa01"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-7523aa01"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103100056405643-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PoLAxlOXLBv%2FY1LZ7tgDQJHvGVXCKSqWXm1igWQXksY%3D&st=2021-03-10T00%3A52%3A53Z&se=2021-04-10T00%3A57%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external d [...]

2021-03-10 15:16 UTC, opbld31 commented
Docs Build status updates of commit _[163fc0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/163fc0cb446a14b95cf5ae46092dbfb2813ba82e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-d7c34ae3)
[api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organization?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) | [Details](#user-content-c0f00fbd-d7c34ae3)
[api-reference/v1.0/api/organizationalbrandingproperties-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingproperties-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingproperties-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-delete?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-get?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/api/organizationalbrandingpropertieslocalization-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingpropertieslocalization-update?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/organizationalbrandingproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organizationalbrandingproperties.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/organizationalbrandingproperties?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/organizationalbrandingproperties-create?view=graph-rest-1.0&branch=pr-en-us-11264) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-d7c34ae3"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'identity-access'.`````

<a id="c0f00fbd-d7c34ae3"></a>
### [api-reference/v1.0/resources/organization.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/almars/organizationbranding/api-reference/v1.0/resources/organization.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'organization resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/resources/intune-onboarding-organization.md(2,8), v1.0/resources/organization.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'organization resource type' is duplicated with other articles: 'v1.0/resources/intune-onboarding-organization.md(10,1), v1.0/resources/organization.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103101515054515-11264%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Lrk1cQeJz5ELUZfC6STeSMD4%2FHiOTpwDRSCLRrX9n4E%3D&st=2021-03-10T15%3A11%3A57Z&se=2021-04-10T15%3A16%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external d [...]

2021-03-11 00:01 UTC, merged