Promoting auth method APIs to v1.0
microsoftgraph/microsoft-graph-docs pull request #11274
Opened 2021-01-14 02:31 UTC by mmcla

2021-01-14 02:33 UTC, opbld32 commented
Docs Build status updates of commit _[cd6aa82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd6aa8264dc4775a5f5b2f7f0b8c39ef2b718f83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :x:Error | | [Details](#user-content-4638a7a3-6d87fa16)
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :x:Error | | [Details](#user-content-fb239ed3-6d87fa16)
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :x:Error | | [Details](#user-content-06b807d4-6d87fa16)
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :x:Error | | [Details](#user-content-a9b3baab-6d87fa16)
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :x:Error | | [Details](#user-content-d8cd74c4-6d87fa16)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | | [Details](#user-content-6a3c9664-6d87fa16)
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :warning:Warning | | [Details](#user-content-d6a5127e-6d87fa16)
[api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md) | :warning:Warning | | [Details](#user-content-ba6955f6-6d87fa16)

<a id="4638a7a3-6d87fa16"></a>
### [api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md)
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-methods-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-methods-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-methods-objc-snippets.md'.`````
 - **Line 99, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-methods-java-snippets.md'.`````
 - **Line 14, Column 106**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/phoneauthenticationmethod.md'.`````
 - **Line 14, Column 183**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/passwordauthenticationmethod.md'.`````

<a id="fb239ed3-6d87fa16"></a>
### [api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md)
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-authenticationmethod-csharp-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-authenticationmethod-javascript-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-authenticationmethod-objc-snippets.md'.`````
 - **Line 89, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-authenticationmethod-java-snippets.md'.`````

<a id="06b807d4-6d87fa16"></a>
### [api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md)
 - **Line 66, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/delete-fido2authenticationmethod-csharp-snippets.md'.`````
 - **Line 70, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/delete-fido2authenticationmethod-javascript-snippets.md'.`````
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/delete-fido2authenticationmethod-objc-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/delete-fido2authenticationmethod-java-snippets.md'.`````

<a id="a9b3baab-6d87fa16"></a>
### [api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md)
 - **Line 68, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-fido2authenticationmethod-csharp-snippets.md'.`````
 - **Line 72, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-fido2authenticationmethod-javascript-snippets.md'.`````
 - **Line 76, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-fido2authenticationmethod-objc-snippets.md'.`````
 - **Line 8 [...]

2021-01-20 20:45 UTC, davidmu1 commented on api-reference/v1.0/api/authenticationmethod-get.md
> +| Permission type                        | Permissions acting on self (from least to most privileged) | Permissions acting on others (from least to most privileged)|
Please move the permissions acting on others to a new table below this one.

2021-01-20 20:46 UTC, davidmu1 commented on api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-20 20:47 UTC, davidmu1 commented on api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md
> +* Global admin
When there is just one entry, it should be a sentence: For delegated scenarios, the administrator needs the Global admin role. For more information, see [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles).

2021-01-20 20:48 UTC, davidmu1 commented on api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-20 20:49 UTC, davidmu1 commented on api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md
> +For delegated scenarios the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
For delegated scenarios, the administrator needs the Global admin role. For more information, see roles.

2021-01-20 20:49 UTC, davidmu1 commented on api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-20 20:50 UTC, davidmu1 commented on api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md
> +For delegated scenarios, the administrator needs one of the following [roles](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
For delegated scenarios, the administrator needs the Global admin role. For more information, see roles.

2021-01-20 20:51 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethod-delete.md
> +|Permission type|Permissions acting on self (from most to least privileged)|Permissions acting on others (from least to most privileged)|
Please create separate table for permissions acting on others.

2021-01-20 20:52 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethod-get.md
> +|Permission type|Permissions acting on self (from most to least privileged)|Permissions acting on others (from least to most privileged)|
Please create separate table for permissions acting on others.

2021-01-20 20:52 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethod-list.md
> +|Permission type|Permissions acting on self (from most to least privileged)|Permissions acting on others (from least to most privileged)|
Please create separate table for permissions acting on others.

2021-01-20 20:53 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-20 20:53 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md
> +For delegated scenarios, the administrator needs the following [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Sentence

2021-01-20 20:54 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-20 20:54 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md
> +For delegated scenarios, the administrator needs the following [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Sentence

2021-01-20 20:55 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md
> +|Permission type|Permissions (from most to least privileged)|
```suggestion
|Permission type|Permissions (from least to most privileged)|
```

2021-01-20 20:55 UTC, davidmu1 commented on api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md
> +For delegated scenarios, the administrator needs the following [role](/azure/active-directory/users-groups-roles/directory-assign-admin-roles#available-roles):
Sentence

2021-01-21 22:26 UTC, opbld34 commented
Docs Build status updates of commit _[b57dc4e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b57dc4e254af980113399f980bc20cf6578b788c)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-25 06:27 UTC, andres-canello commented on api-reference/v1.0/api/authenticationmethod-get.md
> +| Permission type                        | Permissions acting on self (from least to most privileged) | Permissions acting on others (from least to most privileged)|
Done

2021-01-25 07:03 UTC, opbld30 commented
Docs Build status updates of commit _[ed4950e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed4950e87074caa679097abee829cea4df715e3a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-922cef87)

<a id="922cef87"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101250703403234-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U%2BoXy0d9cprzM7s2%2BN4Aqn%2FkrZNCfIJ6fDVe9W1hKjU%3D&st=2021-01-25T06%3A58%3A56Z&se=2021-02-25T07%3A03%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 07:45 UTC, opbld30 commented
Docs Build status updates of commit _[e53d235](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e53d235296340097b050c399923dc76054ebeb83)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-62ce258e)

<a id="62ce258e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101250744459550-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7rth82jC6wkE4vb8VLgw%2FsenAAAas9ECL6e6hgjE8hU%3D&st=2021-01-25T07%3A40%3A51Z&se=2021-02-25T07%3A45%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 09:00 UTC, opbld32 commented
Docs Build status updates of commit _[dfb40eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dfb40eb681ded509ccb15c4f955a6e579b21925e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6e1a5628)

<a id="6e1a5628"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101250859423240-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dpHMG2guLXBCncOktD1MbTaEs3pmpWxBSkK7aFyTNjU%3D&st=2021-01-25T08%3A55%3A02Z&se=2021-02-25T09%3A00%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 09:09 UTC, opbld32 commented
Docs Build status updates of commit _[762ced1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/762ced1cff9293ba44ec05563f5370471b298305)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-64a0b3ff)

<a id="64a0b3ff"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101250908499298-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rv2XcB%2F%2Fx42vW%2FA6%2BKX21rV%2FXYbyY8fgzoBkS3ZK8rY%3D&st=2021-01-25T09%3A04%3A14Z&se=2021-02-25T09%3A09%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-25 09:15 UTC, opbld33 commented
Docs Build status updates of commit _[b2706a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b2706a1c1ea04c109f71ebd3178b429bc823ae16)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :x:Error | | [Details](#user-content-4638a7a3-9fb6a607)
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :x:Error | | [Details](#user-content-fb239ed3-9fb6a607)
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | | [Details](#user-content-6a3c9664-9fb6a607)
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :warning:Warning | | [Details](#user-content-d6a5127e-9fb6a607)
[api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md) | :warning:Warning | | [Details](#user-content-ba6955f6-9fb6a607)

<a id="4638a7a3-9fb6a607"></a>
### [api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md)
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-methods-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-methods-javascript-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-methods-objc-snippets.md'.`````
 - **Line 99, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-methods-java-snippets.md'.`````

<a id="fb239ed3-9fb6a607"></a>
### [api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md)
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-authenticationmethod-csharp-snippets.md'.`````
 - **Line 90, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-authenticationmethod-javascript-snippets.md'.`````
 - **Line 94, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-authenticationmethod-objc-snippets.md'.`````
 - **Line 98, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-authenticationmethod-java-snippets.md'.`````

<a id="6a3c9664-9fb6a607"></a>
### [api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethods-overview.md)
 - **Line 31, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'passwordauthenticationmethod.md'.`````
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'phoneauthenticationmethod.md'.`````
 - **Line 35, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'passwordlessmicrosoftauthenticatorauthenticationmethod.md'.`````
 - **Line 36, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'emailauthenticationmethod.md'.`````

<a id="d6a5127e-9fb6a607"></a>
### [api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md)
 - **Line 28, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md'.`````

<a id="ba6955f6-9fb6a607"></a>
### [api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/fido2authenticationmethodconfiguration.md)
 - **Line 31, Column 18**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/fido2keyrestrictions.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101250914180998-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JkZQ08L0aY2LJcNJLknIedn%2BBoF6nL16Etfs1ZezfKU%3D&st=2021-01-25T09%3A10%3A26Z&se=2021-02-25T09%3A15%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q [...]

2021-01-25 09:26 UTC, andres-canello requested changes
Fixed a bunch of things.
To do: 
- add enums
- fix links on tables pointing to methods staying on beta or remove from table
- APIDoctor issues

2021-01-25 09:28 UTC, opbld30 commented
Docs Build status updates of commit _[68335d7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/68335d775a442ca85be09f7c6854b9609e172266)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/authenticationmethods-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethods-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethods-overview?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) | [Details](#user-content-6a3c9664-b19f9ea2)
[api-reference/v1.0/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/authenticationmethodspolicies-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) | [Details](#user-content-d6a5127e-b19f9ea2)
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/micr [...]

2021-02-16 19:34 UTC, mmcla commented
@andres-canello are we waiting on anything for this? Can we remove the do not merge tag?

2021-02-17 08:23 UTC, andres-canello approved these changes
Looks good, left comments on the Overview pages.

2021-02-17 08:23 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethods-overview.md
> +
Do we want all methods here or just the V1.0 ones?

2021-02-17 08:23 UTC, andres-canello commented on api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodtarget.md
> +|isNumberMatchingRequired (Private Preview)|Boolean|Require the user to match the number displayed on the sign-in page to approve the MFA notification.|
This will need to get updated once this PR is approved: https://github.com/microsoftgraph/microsoft-graph-docs/pull/11674

2021-02-17 08:23 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethodspolicies-overview.md
> +|[passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration](passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) (deprecated)|Define users who can use Passwordless Phone
Remove this one?

2021-02-19 04:26 UTC, andres-canello commented on api-reference/v1.0/resources/microsoftauthenticatorauthenticationmethodtarget.md
> +|isNumberMatchingRequired (Private Preview)|Boolean|Require the user to match the number displayed on the sign-in page to approve the MFA notification.|
done

2021-02-19 04:30 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethods-overview.md
> +|Authentication method       | Description |Examples     |
Removed

2021-02-19 04:31 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethods-overview.md
> +
Removed

2021-02-19 04:33 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethodspolicies-overview.md
> +|[passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration](passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration.md) (deprecated)|Define users who can use Passwordless Phone
Done

2021-02-19 07:54 UTC, millicentachieng commented on api-reference/v1.0/resources/authenticationmethodconfiguration.md
> +  "baseType": "",
Remove line if baseType has no value

2021-02-19 07:55 UTC, millicentachieng commented on api-reference/v1.0/resources/authenticationmethod.md
> +  "baseType": "",
Remove line if baseType has no value

2021-02-19 08:19 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethod.md
> +  "baseType": "",
done

2021-02-19 08:20 UTC, andres-canello commented on api-reference/v1.0/resources/authenticationmethodconfiguration.md
> +  "baseType": "",
done

2021-02-19 09:01 UTC, millicentachieng commented
```
### externalEmailOtpState values

|Member|
|:---|
|default|
|enabled|
|disabled|
```
This needs to be defined in the `enums.md` file

2021-02-19 09:10 UTC, millicentachieng commented on api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
> +|keyStrength|authenticationMethodKeyStrength|Key strength of this Windows Hello for Business key. Possible values are: `normal`, `weak`, `unknown`.|
```
### authenticationMethodKeyStrength values

|Member|
|:---|
|normal|
|weak|
|unknown|
```
This needs to be defined in the `enums.md` file in v1.0 folder. Copied this from beta folder.

2021-02-19 09:54 UTC, andres-canello commented on api-reference/v1.0/resources/windowshelloforbusinessauthenticationmethod.md
> +|keyStrength|authenticationMethodKeyStrength|Key strength of this Windows Hello for Business key. Possible values are: `normal`, `weak`, `unknown`.|
Done, thanks!

2021-02-19 10:34 UTC, andres-canello commented
@mmcla This should be ready to go

2021-02-20 02:11 UTC, millicentachieng commented on api-reference/v1.0/resources/enums.md
> +|unknownFutureValue|
This needs to be removed since `extenalEmailOtpState values` was added below.

2021-02-20 05:55 UTC, andres-canello commented on api-reference/v1.0/resources/enums.md
> +|unknownFutureValue|
Done

2021-03-05 02:58 UTC, opbld31 commented
Docs Build status updates of commit _[66aa736](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66aa7360ba7e3af18c9ff7c34854ddf505e367de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-69f00d49)

<a id="69f00d49"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050258207127-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sQWSjLKpFHnxafbiqMQlypHl3pREFB5%2FWc8Zk0FbEIs%3D&st=2021-03-05T02%3A53%3A40Z&se=2021-04-05T02%3A58%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 03:46 UTC, opbld30 commented
Docs Build status updates of commit _[c22a5b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c22a5b2ebf29dee65ee170219860e478e24549a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-09 05:46 UTC, opbld34 commented
Docs Build status updates of commit _[75defba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75defbad320f93d6d04ff108d79409b3c565bf31)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-09 05:53 UTC, andres-canello commented
@Lauragra can you please review and publish?

2021-03-16 05:18 UTC, opbld30 commented
Docs Build status updates of commit _[1433a2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1433a2f0b92c39074bb10a02f960fb447f9ff8ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-18 22:18 UTC, opbld30 commented
Docs Build status updates of commit _[4119bc7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4119bc7e7dc756326565fcc98605a210a725bebe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-18 22:19 UTC, Lauragra commented on api-reference/v1.0/toc.yml
> +        - name: Authentication methods
Please double-check that everything is included in the TOC; I see that authentication-list-methods and authenticationmethod-get are currently missing.

2021-03-18 22:23 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +            "Id": "813a1087-06e7-4281-a897-6b7a4d60e1d4",
Within a ChangeList item, all the IDs should be identical.

2021-03-18 23:11 UTC, Lauragra commented on api-reference/v1.0/api/authentication-list-methods.md
> +# [HTTP](#tab/http)
Global: Make sure you delete these HTTP H1s when moving files from beta to v1.0.

2021-03-19 04:49 UTC, andres-canello commented on api-reference/v1.0/toc.yml
> +        - name: Authentication methods
Modified the TOC to align with the changes we are making to beta as part of another PR. It includes a link to list methods. get is not a valid operation here.

2021-03-19 04:56 UTC, andres-canello commented on api-reference/v1.0/api/authentication-list-methods.md
> +# [HTTP](#tab/http)
Done

2021-03-19 04:57 UTC, andres-canello commented on changelog/Microsoft.DirectoryServices.json
> +            "Id": "813a1087-06e7-4281-a897-6b7a4d60e1d4",
Fixed

2021-03-19 04:59 UTC, opbld31 commented
Docs Build status updates of commit _[890f6a4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/890f6a471c9a846655755e03acb82b758ef2b8a8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ca91ba5a)

<a id="ca91ba5a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103190458524049-11274%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=58O1%2FpRoQQA3ONW%2FyemmzRUDKmfk7MwGmwIyeqG27F4%3D&st=2021-03-19T04%3A54%3A11Z&se=2021-04-19T04%3A59%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 05:32 UTC, opbld34 commented
Docs Build status updates of commit _[3a8c50f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3a8c50f8432bb01ea811aeaab21ac7254b82c8a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) | [Details](#user-content-44812e78b29efdba49c98a86efeb2d4a-21edf8d9)
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmeth [...]

2021-03-19 05:39 UTC, opbld33 commented
Docs Build status updates of commit _[f873721](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f8737212f94dc1b4862a5e995278365f9ee4b4eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-19 05:42 UTC, andres-canello commented
Thanks @Lauragra , all fixed.

2021-03-20 00:14 UTC, opbld31 commented
Docs Build status updates of commit _[5f79c3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f79c3e57fc4effb42be78c4cf1d4ad311438d34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-20 00:14 UTC, Lauragra approved these changes

2021-03-20 00:16 UTC, opbld32 commented
Docs Build status updates of commit _[d03ddfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d03ddfda7ea56bf0e2e8a4a0afb12871fe414894)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/authentication-list-methods.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authentication-list-methods.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authentication-list-methods?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/emailauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/emailauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/fido2authenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/fido2authenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethod-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethod-list?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-delete?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-get?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/microsoftauthenticatorauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/microsoftauthenticatorauthenticationmethodconfiguration-update?view=graph-rest-1.0&branch=pr-en-us-11274) (>= graph-rest-1.0) |
[api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/Jan2021-promote-auth-methods-to-v1/api-reference/v1.0/api/windowshelloforbusinessauthenticationmethod-delete.md) | :white_check_mark:Succeeded | [View](https://review [...]

2021-03-20 00:17 UTC, merged