Channel Application Permission Adjustment
microsoftgraph/microsoft-graph-docs pull request #11279
Opened 2021-01-14 11:26 UTC by YuriySamorodov

Aligned permission description with https://docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&tabs=http

2021-01-16 14:29 UTC, YuriySamorodov commented
@RamjotSingh , could you please kindly take a look?

2021-01-19 08:33 UTC, RamjotSingh requested changes

2021-01-19 08:33 UTC, RamjotSingh commented on api-reference/beta/api/chatmessage-post.md
> +| Application                            | Teamwork.Migrate.All |
Having Teamwork.Migrate.All alone here can be confusing since this permission works only when migration is under progress. below the permission block please add the following
```
> **Note** : Teamwork.Migrate.All permission is *only* used for migration of messages from an external system into Microsoft Teams. Please refer to [migration documentation](/microsoftteams/platform/graph-api/import-messages/import-external-messages-to-teams) for more details.
```
@Lauragra Please check the message wording and positioning.

2021-05-04 19:43 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-05-05 20:36 UTC, opbld33 commented
Docs Build status updates of commit _[d5b337a](https://github.com/YuriySamorodov/microsoft-graph-docs/commits/d5b337a116474c3c079bd199ae09338c1baa399e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-post.md](https://github.com/YuriySamorodov/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/chatmessage-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-beta&branch=pr-en-us-11279) (graph-rest-beta) | [Details](#user-content-2d8cf89182fc122537ab8493d7c325f1-32062499)

<a id="2d8cf89182fc122537ab8493d7c325f1-32062499"></a>
### [api-reference/beta/api/chatmessage-post.md](https://github.com/YuriySamorodov/microsoft-graph-docs/blob/patch-2/api-reference/beta/api/chatmessage-post.md)
 - **Line 180, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/help/contribute/validation-ref/invalid-tab-group?branch=main)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105052035107627-11279%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FeP1zl%2FiF6cRI47bCcGpHFveT3cqwqwe%2BnJ%2FsEVGveA%3D&st=2021-05-05T20%3A31%3A23Z&se=2021-06-05T20%3A36%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-28 01:57 UTC, RamjotSingh commented
I took the change in my PR. Closing this PR.

2021-11-28 01:57 UTC, closed without merging