Add the accessPackageResourceEnvironment resource type
microsoftgraph/microsoft-graph-docs pull request #11273
Opened 2021-01-13 21:43 UTC by FaithOmbongi

2021-01-13 21:44 UTC, opbld31 commented
Docs Build status updates of commit _[882c601](https://github.com/microsoftgraph/microsoft-graph-docs/commits/882c6016c8fe76fe31c2eca6a67e50ee95048f04)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-0368113c-77718767)
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-77718767)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |

<a id="0368113c-77718767"></a>
### [api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'markwahl-msft*' is not a valid GitHub ID.`````

<a id="f138c42d-77718767"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 140, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Duplicate tab id: (http, 2).`````
 - **Line 140, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132143301845-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xBgX4i4aWoFACYKje%2Bqiwb0gmdfFGdGJBVGCuYPAYcA%3D&st=2021-01-13T21%3A39%3A42Z&se=2021-02-13T21%3A44%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 21:59 UTC, opbld34 commented
Docs Build status updates of commit _[a3f697c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a3f697cb63be9e4ca956ffa25aa1432f5e784fe5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-2f4b1a06)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |

<a id="f138c42d-2f4b1a06"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 140, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 198, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 140, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(140,1), beta/api/accesspackageresourcerequest-post.md(198,1)'. First level headings must be unique within a docset.`````
 - **Line 198, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(140,1), beta/api/accesspackageresourcerequest-post.md(198,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132158449406-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jcnd3qGA9N%2FPsopLNowrwIwhT%2F53beuwnlMv1PcqwQY%3D&st=2021-01-13T21%3A54%3A53Z&se=2021-02-13T21%3A59%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-13 22:22 UTC, opbld32 commented
Docs Build status updates of commit _[1fc0dad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1fc0dad87956e7f5fea3403752323cee480f6e85)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-da939aa5)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) | [Details](#user-content-de0bbbbb-da939aa5)
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) | [Details](#user-content-2cb6e14f-da939aa5)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="f138c42d-da939aa5"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 140, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 198, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 140, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(140,1), beta/api/accesspackageresourcerequest-post.md(198,1)'. First level headings must be unique within a docset.`````
 - **Line 198, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(140,1), beta/api/accesspackageresourcerequest-post.md(198,1)'. First level headings must be unique within a docset.`````

<a id="de0bbbbb-da939aa5"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md)
 - **Line 20, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/entitlementManagement?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 21, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessPackageResource?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 22, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/accessPackageResourceEnvironment?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 23, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/api/resources/connectionInfo?view=graph-rest-beta' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 58, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 58, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 20, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/entitlementManagement?view=graph-rest-beta`````
 - **Line 21, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/graph/api/resources/accessPackageResource?view=graph-rest-beta`````
 - **Line 22, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: https://docs.microsoft.c [...]

2021-01-13 22:38 UTC, opbld33 commented
Docs Build status updates of commit _[3abf62b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3abf62becdc89438fa45f408e032762ed6f43967)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-051ddbf7)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) | [Details](#user-content-de0bbbbb-051ddbf7)
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) | [Details](#user-content-2cb6e14f-051ddbf7)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |

<a id="f138c42d-051ddbf7"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 140, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 198, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 140, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(140,1), beta/api/accesspackageresourcerequest-post.md(198,1)'. First level headings must be unique within a docset.`````
 - **Line 198, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(140,1), beta/api/accesspackageresourcerequest-post.md(198,1)'. First level headings must be unique within a docset.`````

<a id="de0bbbbb-051ddbf7"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md)
 - **Line 20, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/entitlementManagement'.`````
 - **Line 21, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResource'.`````
 - **Line 22, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResourceEnvironment'.`````
 - **Line 23, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/connectionInfo'.`````
 - **Line 58, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 58, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

<a id="2cb6e14f-051ddbf7"></a>
### [concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md)
 - **Line 15, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'December 2020: New in preview only''. Each second level heading (H2) in an article must be unique.`````
 - **Line 42, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'December 2020: New in preview only''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132237364856-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lLTv2e0yjqNzU3qI%2BgeSaJaVMx8n904eO%2Bs3a35K5vw%3D&st=2021-01-13T22%3A33%3A47Z&se=2021-02-13T22%3A38%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's [...]

2021-01-13 22:49 UTC, opbld34 commented
Docs Build status updates of commit _[f631e0a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f631e0a0581f3dc9f6f6e683631a7ba491776b2c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-532087f9)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) | [Details](#user-content-de0bbbbb-532087f9)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

<a id="f138c42d-532087f9"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 142, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 200, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 142, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(142,1), beta/api/accesspackageresourcerequest-post.md(200,1)'. First level headings must be unique within a docset.`````
 - **Line 200, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(142,1), beta/api/accesspackageresourcerequest-post.md(200,1)'. First level headings must be unique within a docset.`````

<a id="de0bbbbb-532087f9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md)
 - **Line 20, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/entitlementManagement'.`````
 - **Line 21, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResource'.`````
 - **Line 22, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResourceEnvironment'.`````
 - **Line 23, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/connectionInfo'.`````
 - **Line 58, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 58, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132248250015-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gyM06KIQhsiyVn3%2Bq707rq8oZvTGnxITQ03yP59aCHA%3D&st=2021-01-13T22%3A44%3A37Z&se=2021-02-13T22%3A49%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microso [...]

2021-01-13 22:55 UTC, opbld30 commented
Docs Build status updates of commit _[a722832](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a722832396740ed1dfbf33bf1a64651b86d194b2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-d251b026)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) | [Details](#user-content-de0bbbbb-d251b026)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

<a id="f138c42d-d251b026"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 142, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 200, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 142, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(142,1), beta/api/accesspackageresourcerequest-post.md(200,1)'. First level headings must be unique within a docset.`````
 - **Line 200, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(142,1), beta/api/accesspackageresourcerequest-post.md(200,1)'. First level headings must be unique within a docset.`````

<a id="de0bbbbb-d251b026"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md)
 - **Line 20, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/entitlementManagement'.`````
 - **Line 21, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResource'.`````
 - **Line 22, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResourceEnvironment'.`````
 - **Line 23, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/connectionInfo'.`````
 - **Line 58, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 58, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101132254181761-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Luh6I7yRoDgDbWiFa0ZY2Mi3vVDQr5G4iWPKoY8zSnY%3D&st=2021-01-13T22%3A50%3A26Z&se=2021-02-13T22%3A55%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft [...]

2021-01-14 18:42 UTC, opbld34 commented
Docs Build status updates of commit _[f39de7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f39de7e6cd5dd89592e13a9501b92557f93f1d71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) | [Details](#user-content-f138c42d-2e12fc33)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) | [Details](#user-content-de0bbbbb-2e12fc33)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

<a id="f138c42d-2e12fc33"></a>
### [api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md)
 - **Line 142, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 200, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'HTTP request') are not allowed. You can only have one top-level heading.`````
 - **Line 142, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(142,1), beta/api/accesspackageresourcerequest-post.md(200,1)'. First level headings must be unique within a docset.`````
 - **Line 200, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'HTTP request' is duplicated with other articles: 'beta/api/accesspackageresourcerequest-post.md(142,1), beta/api/accesspackageresourcerequest-post.md(200,1)'. First level headings must be unique within a docset.`````

<a id="de0bbbbb-2e12fc33"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md)
 - **Line 20, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/entitlementManagement'.`````
 - **Line 21, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResource'.`````
 - **Line 22, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accessPackageResourceEnvironment'.`````
 - **Line 23, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/connectionInfo'.`````
 - **Line 59, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 59, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````
 - **Line 34, Column 1**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? If so, add &preserve-view=true to the URL: /graph/api/resources/outOfOfficeSettings.md?view=graph-rest-beta`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101141841175816-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sczCvPrjyu%2FXGf5C7JnHaBa0K0k9dJx5CQXmRqOdp%2BY%3D&st=2021-01-14T1 [...]

2021-01-14 19:25 UTC, opbld31 commented
Docs Build status updates of commit _[22322da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22322daf4a17698733686d0804dac06314a230fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) | [Details](#user-content-de0bbbbb-04f746b9)
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

<a id="de0bbbbb-04f746b9"></a>
### [concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md)
 - **Line 20, Column 80**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/entitlementmanagement-root'.`````
 - **Line 21, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accesspackageresource'.`````
 - **Line 22, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/accesspackageresourceenvironment'.`````
 - **Line 23, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/connectioninfo'.`````
 - **Line 59, Column 26**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/cloudPcOnPremisesConnection-updateAdDomainPassword'.`````
 - **Line 59, Column 167**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'graph/api/resources/cloudPcOnPremisesConnection'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101141924000466-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YD9he6jQVHgUVCijaZE9AWX8Y8tjzwNoUwmcrVTC2zc%3D&st=2021-01-14T19%3A20%3A58Z&se=2021-02-14T19%3A25%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca [...]

2021-01-20 23:58 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresource.md
> +|accessPackageResourceEnvironment|[accessPackageResourceEnvironment](../resources/accesspackageresourceenvironment.md)|Contains the environment information for the environment to which the resource b
Might be good to provide a little information here about the binding that is being done in the example in the post operation.

2021-01-20 23:59 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +In [Azure AD entitlement management](entitlementmanagement-root.md), an access package resource environment is a reference to the geolocation environment in which a resource is located.
```suggestion
In [Azure AD Entitlement Management](entitlementmanagement-root.md), an access package resource environment is a reference to the geolocation environment in which a resource is located.
```

2021-01-21 00:03 UTC, davidmu1 commented on api-reference/beta/resources/connectioninfo.md
> +The connectionInfo object holds the resource locator which will be used by Entitlement Management (ELM) to communicate with a resource.
```suggestion
The connectionInfo object defines the resource locator that is used to communicate with a resource in Azure AD Entitlement Management.
```

2021-01-21 00:04 UTC, davidmu1 commented on concepts/whats-new-overview.md
> +## January 2021: New in preview only
@angelgolfer-ms  should approve this. She usually handles What's New entries.

2021-01-21 01:27 UTC, angelgolfer-ms commented on concepts/whats-new-overview.md
> +## January 2021: New in preview only
Sure, and thanks for drafting the what's new.
Since you both are writers for identity APIs, I am going to assume the what's new list is accurate for this PR.
In the what's new, I usually try to start a bullet point with infinitive without to, to save repeating phrases like "you can now", "apps can now", etc. How about:

```
- Assign geolocation information to an [access package](/graph/api/resources/accesspackage?view=graph-rest-beta&preserve-view=true) resource in the [access package assignment request](/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&preserve-view=true).
- Get a list of all [access package resource environments](/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&preserve-view=true) which represent the geolocations that store Sharepoint Online resources.
```

2021-01-21 12:51 UTC, opbld30 commented
Docs Build status updates of commit _[54268e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54268e755dd2efc3499c4a01d66000c112dd7170)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a3250801)

<a id="a3250801"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101211251228975-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jIg4cC8ia5%2FAagLLo0tahLeaRpxu2FgEgkoAIuucerY%3D&st=2021-01-21T12%3A46%3A38Z&se=2021-02-21T12%3A51%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 12:52 UTC, opbld31 commented
Docs Build status updates of commit _[b57f78b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b57f78bd059322865b25fb7351726c9b079bbab9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-59e29655)

<a id="59e29655"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101211251390109-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ME1OY01ve92k4wkCm06yWrQUHWAmFGd%2FQpQehk2%2FV%2FY%3D&st=2021-01-21T12%3A47%3A05Z&se=2021-02-21T12%3A52%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 12:52 UTC, opbld31 commented
Docs Build status updates of commit _[88d18fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88d18fec6ff30f65807e0ed224720fdfb87cf623)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f8855cb1)

<a id="f8855cb1"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101211252140640-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tK1NNxyxWlQ19nl5ztkA0YmZWFoe2uxXiCZAi4F9gnQ%3D&st=2021-01-21T12%3A47%3A32Z&se=2021-02-21T12%3A52%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 12:52 UTC, opbld32 commented
Docs Build status updates of commit _[926c614](https://github.com/microsoftgraph/microsoft-graph-docs/commits/926c614e33f39da3fcc9eb3df5993a470d9e9ba1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bab3aa68)

<a id="bab3aa68"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101211252250034-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cu%2BKhNpsQR0G8VxDzUl2uFCMCPcf5TArpKW10Bgwoc0%3D&st=2021-01-21T12%3A47%3A52Z&se=2021-02-21T12%3A52%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 12:59 UTC, FaithOmbongi commented on concepts/whats-new-overview.md
> +## January 2021: New in preview only
Thanks Angela. I'll incorporate this feedback.

2021-01-21 22:09 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +In [Azure AD Entitlement Management](entitlementmanagement-root.md), an access package resource environment is a reference to the geolocation environment in which a resource is located. This API supp
Might want to phrase the second as that it's only applicable to SharePoint Online sites.  Other resources are not geo-locatable IIRC.

2021-01-21 22:09 UTC, markwahl-msft commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +In [Azure AD Entitlement Management](entitlementmanagement-root.md), an access package resource environment is a reference to the geolocation environment in which a resource is located. This API supp
Also, would it be useful to say that these are automatically provided as part of Azure AD Entilement Management.  (That's why there's no API to create them)

2021-01-21 22:09 UTC, markwahl-msft commented on api-reference/beta/resources/azure-ad-overview.md
> +| Ensure group memberships and application access rights are correct with access reviews | [access reviews API](../resources/accessreviews-root.md) |[Azure AD access reviews](/azure/active-directory/
why was the period removed?  Don't the other lines have a period?

2021-01-22 09:49 UTC, FaithOmbongi commented on api-reference/beta/resources/azure-ad-overview.md
> +| Ensure group memberships and application access rights are correct with access reviews | [access reviews API](../resources/accessreviews-root.md) |[Azure AD access reviews](/azure/active-directory/
An oversight. I'll fix that.

2021-01-22 16:46 UTC, opbld33 commented
Docs Build status updates of commit _[34c5600](https://github.com/microsoftgraph/microsoft-graph-docs/commits/34c5600c35372a9348d891b26cf8e569d02d12db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11273) |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101221645170706-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qqu7QDkj0e0eGbmnNpiO1IFHXyK7yr5b2qWdav7zscQ%3D&st=2021-01-22T16%3A41%3A23Z&se=2021-02-22T16%3A46%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 18:47 UTC, opbld34 commented
Docs Build status updates of commit _[16888fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16888fa7847b4f2048d216a89eebbda889c65b56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101221846074548-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ClXy1CB9CquxgEsWtjaJGXh1FN%2F7eWPerXpvmbubR1o%3D&st=2021-01-22T18%3A42%3A24Z&se=2021-02-22T18%3A47%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 00:57 UTC, hanki-microsoft commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +In [Azure AD Entitlement Management](entitlementmanagement-root.md), an access package resource environment is a reference to the geolocation environment in which a resource is located. This environm
Please change "SharePoint Online sites" to "Multi-Geo SharePoint Online sites"

2021-01-26 15:19 UTC, opbld30 commented
Docs Build status updates of commit _[30ece02](https://github.com/microsoftgraph/microsoft-graph-docs/commits/30ece02453e404ee5c255b214549ef81fb988294)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101261517160517-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fj9zH%2F%2FG4g7d2NLSXD%2FRGXRwne75vVd8U5f3Z2j3%2BZo%3D&st=2021-01-26T15%3A13%3A59Z&se=2021-02-26T15%3A18%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-31 18:14 UTC, markwahl-msft requested changes
Thanks, some small suggestions.

2021-01-31 18:14 UTC, markwahl-msft commented on api-reference/beta/resources/connectioninfo.md
> +|url|String|The endpoint that is used by ELM to communicate with the access package resource.|
"ELM" is an internal code name from prior to GA.  This should say "Entitlement Management"

2021-01-31 18:14 UTC, markwahl-msft commented on changelog/Microsoft.DirectoryServices.json
> +          "Id": "399dec32-117c-4129-b943-47a6f1d3033b",
This has 4 changelist entries but it seems to me there is only one change - adding the new accessPackageResourceEnvironment resource type - which impacts one existing resource.

2021-01-31 18:14 UTC, markwahl-msft commented on concepts/whats-new-overview.md
> +### Identity and access | Governance
This should be Identity Governance, not Governance.  (See https://www.microsoft.com/en-us/security/business/identity/governance "Grant each person the right level of access to the resources they need with the Azure Active Directory (Azure AD) identity governance.")

2021-02-04 18:18 UTC, davidmu1 commented on api-reference/beta/api/accesspackageresourceenvironment-get.md
> +This method supports the `$filter` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Possibly add an example that shows how the filter parameter is used?

2021-02-04 18:45 UTC, davidmu1 commented on api-reference/beta/api/accesspackageresourcerequest-post.md
> +The following is an example of the request. In this example, we use the `@odata.bind` annotation to assign the `id` of the `accessPackageResourceEnvironment` to an `accessPackageResourceEnvironment`
```suggestion
The following is an example of the request. In this example, the `@odata.bind` annotation is used to assign the `id` of the `accessPackageResourceEnvironment` to an `accessPackageResourceEnvironment` object.
```

2021-02-04 18:46 UTC, davidmu1 commented on api-reference/beta/api/accesspackageresourcerequest-post.md
> +The following is an example of the request. In this example, we specify the parameters of an `accessPackageResourceEnvironment` in an `accessPackageResourceEnvironment` object.
```suggestion
The following is an example of the request. In this example, the parameters of an `accessPackageResourceEnvironment` are specified in an `accessPackageResourceEnvironment` object.
```

2021-02-04 18:49 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresource.md
> +In [Azure AD Entitlement Management](entitlementmanagement-root.md), an access package resource is a reference to a resource associated with an access package catalog, the roles for which can be used
```suggestion
In [Azure AD Entitlement Management](entitlementmanagement-root.md), an access package resource is a reference to a resource associated with an access package catalog. The roles for the access package resource can be used in one or more access packages.  To request to associate a resource with an access package catalog, or remove a resource from a catalog, create an [accessPackageResourceRequest](accesspackageresourcerequest.md).
```

2021-02-04 18:51 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresource.md
> +|accessPackageResourceEnvironment|[accessPackageResourceEnvironment](../resources/accesspackageresourceenvironment.md)|Contains the environment information for the environment to which the resource b
```suggestion
|accessPackageResourceEnvironment|[accessPackageResourceEnvironment](../resources/accesspackageresourceenvironment.md)|Contains the environment information for the resource. This can be set using either the `@odata.bind` annotation or the environment's *originId*.|
```

2021-02-04 18:55 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +|createdDateTime|DateTimeOffset|The date and time that this object was created. <br>The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time. For e
```suggestion
|createdDateTime|DateTimeOffset|The date and time that this object was created. <br>The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `'2014-01-01T00:00:00Z'`.|
```

2021-02-04 18:56 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +|isDefaultEnvironment|Boolean|Determines whether this is default environment or not. It is set to `true` for all static origin systems like Azure AD groups and Azure AD Applications.|
```suggestion
|isDefaultEnvironment|Boolean|Determines whether this is default environment or not. It is set to `true` for all static origin systems, such as Azure AD groups and Azure AD Applications.|
```

2021-02-04 18:56 UTC, davidmu1 commented on api-reference/beta/resources/accesspackageresourceenvironment.md
> +|modifiedDateTime|DateTimeOffset|The date and time that this object was last modified. <br>The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time
```suggestion
|modifiedDateTime|DateTimeOffset|The date and time that this object was last modified. <br>The DateTimeOffset type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is `'2014-01-01T00:00:00Z'`. |
```

2021-02-04 18:59 UTC, davidmu1 approved these changes

2021-02-05 12:22 UTC, FaithOmbongi commented on concepts/whats-new-overview.md
> +### Identity and access | Governance
The term **Governance** is what's currently used to refer to this sub-area in all Graph docs.

2021-02-05 12:25 UTC, opbld30 commented
Docs Build status updates of commit _[1c80ad5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c80ad56995f7299d97cd79476ac706939ad995f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051224001045-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MfYW6wFEDS8bEMvO8mYYXP1nbEjZ92vOjHyUpQGSJ%2FQ%3D&st=2021-02-05T12%3A20%3A08Z&se=2021-03-08T12%3A25%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 12:26 UTC, opbld34 commented
Docs Build status updates of commit _[a186c5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a186c5a0850a2861104df454377873dfbd7a35f8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051224400867-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4y2I2rWkSjxdfVxNX%2Fb3myuDLjiObvUpvC4pbGAfiZo%3D&st=2021-02-05T12%3A21%3A17Z&se=2021-03-08T12%3A26%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 12:27 UTC, opbld33 commented
Docs Build status updates of commit _[b4d3123](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b4d3123e4509f45510ef61090c703ecd8a8c9674)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051226097798-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CPPJI7QWp8mmbmM55h9Nilnq%2B00Wqul2sncNYMz9haU%3D&st=2021-02-05T12%3A22%3A26Z&se=2021-03-08T12%3A27%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 12:29 UTC, opbld30 commented
Docs Build status updates of commit _[b787a12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b787a123d978ae4c541b35d5dab6b95fcc62349c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051227530142-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vnmyz6hBkcoML5RGZoRd8wc0W8APSnVhlNmbqN06gF0%3D&st=2021-02-05T12%3A24%3A09Z&se=2021-03-08T12%3A29%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 12:38 UTC, opbld34 commented
Docs Build status updates of commit _[0e19734](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e19734801b73a4338ae57a4a4edf3a7e032c3a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051237157934-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YwrcdklvBLpT7quNx3uBl8Ofs3iZSyYbY%2FsBy269aUQ%3D&st=2021-02-05T12%3A33%3A18Z&se=2021-03-08T12%3A38%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 12:53 UTC, FaithOmbongi commented on api-reference/beta/api/accesspackageresourceenvironment-get.md
> +This method supports the `$filter` OData query parameter to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
An oversight. This method does not currently support any.

2021-02-05 13:03 UTC, opbld30 commented
Docs Build status updates of commit _[9ab7001](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ab7001aa3bd03fea2de06305b236a9d243d99b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051302015987-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3B4K%2F2lQZxrsp7vMnzo5aoeLWX1dVcvYpbnp0WLSxyU%3D&st=2021-02-05T12%3A58%3A09Z&se=2021-03-08T13%3A03%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 17:34 UTC, hanki-microsoft approved these changes

2021-02-05 17:56 UTC, opbld32 commented
Docs Build status updates of commit _[0d3411b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d3411b5873e3d0a33475fc4378d9442d079b802)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051755239724-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q%2BtGUGb%2Fsx5OBoUgbTgU40NtUAagtbmyWdjOoRbt%2BVI%3D&st=2021-02-05T17%3A51%3A42Z&se=2021-03-08T17%3A56%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:00 UTC, opbld34 commented
Docs Build status updates of commit _[e8605b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8605b7f6179e2c646faa4b2515213f2fff3c175)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourcerequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/api/accesspackageresourcerequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourcerequest-post?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresource.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresource.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresource?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageresourceenvironment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/accesspackageresourceenvironment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageresourceenvironment?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/connectioninfo.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/connectioninfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/connectioninfo?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11273) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |
[concepts/whats-new-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-01-07-accessPackageResourceEnvironment/concepts/whats-new-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/whats-new-overview?branch=pr-en-us-11273) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060259348063-11273%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=42JIWlKD13abOKTelYiKnM0D3KuFOflcbqPIwTtImqA%3D&st=2021-02-06T02%3A55%3A44Z&se=2021-03-09T03%3A00%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:08 UTC, merged