Electron provider with msal
microsoftgraph/microsoft-graph-docs pull request #11289
Opened 2021-01-15 00:21 UTC by amrutha95

MSAL provider for electron applications

2021-01-15 00:22 UTC, opbld34 commented
Docs Build status updates of commit _[8a88652](https://github.com/amrutha95/microsoft-graph-docs/commits/8a88652fa87041cbb7ec1d4a6c3c721a0edea96b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) | [Details](#user-content-25af6bde-037c6ac1)

<a id="25af6bde-037c6ac1"></a>
### [concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md)
 - **Line 5, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'amsrin' is not a valid GitHub ID.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101150021365631-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ALSh0v0fLK7xsP8PM1mX2EOR%2BbdATQeePNmSr1CC%2BtE%3D&st=2021-01-15T00%3A17%3A56Z&se=2021-02-15T00%3A22%3A56Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 00:42 UTC, opbld34 commented
Docs Build status updates of commit _[caf6a2f](https://github.com/amrutha95/microsoft-graph-docs/commits/caf6a2fc4b556f9b9cbf370db79a18a962231849)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101150041090136-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RRom7GR%2BrLW2FRIjy5%2FZ67vWU2Cz7zCzYFn1vrw5eLQ%3D&st=2021-01-15T00%3A37%3A38Z&se=2021-02-15T00%3A42%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-19 23:36 UTC, opbld33 commented
Docs Build status updates of commit _[78d954f](https://github.com/amrutha95/microsoft-graph-docs/commits/78d954fe45a4c123b73eef1f39e22ed12c0cd6f1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101192335173367-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O924Tc11iodZnRpRBSjHpEs3S6NOWPGzenGMXl1QMQM%3D&st=2021-01-19T23%3A31%3A25Z&se=2021-02-19T23%3A36%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-22 21:31 UTC, nmetulev commented
Rebased to target branch `mgt/next` since this is a new feature in future toolkit release

2021-01-22 21:41 UTC, nmetulev requested changes
Awesome.

Add this doc to the `toc.yml` file so it shows up in the navigation.

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +# MSAL provider for electron
Change `MSAL provider for Electron` to `Electron Provider` here and everywhere else

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +To learn more, see [providers](./providers.md).
```suggestion
To learn more about authentication providers, see [providers](./providers.md).
```

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +You need to initialize ElectronProvider in the renderer process (front-end), and ElectronAuthenticator in the main process (back-end).
I think you can expand here and explain the purpose of each class and how they work together

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +| scopes       | Comma separated strings for scopes the user must consent to on sign in. Optional.
Consider adding a note that this is recommended to ensure the user consents to all scopes when they sign in the first time

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +| isIncrementalConsentEnabled | Enable/Disable incremental consent, false by default. Incrememntal consent is currently not fully supported. |
Remove this property since it's not supported.

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +
Add how to install the npm package, eg: `npm install @microsoft/mgt-electron`

2021-01-22 21:41 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +### Enable OAuth implicit flow
I thought we don't need implicit flow for Electron?

2021-01-22 21:47 UTC, amrutha95 commented on concepts/toolkit/providers/electron.md
> +| isIncrementalConsentEnabled | Enable/Disable incremental consent, false by default. Incrememntal consent is currently not fully supported. |
I have mentioned that it is not currently supported, thought it would be nice to at least talk about it here? Keep it a boolean so that some day when we do support it users can have an option to toggle?

2021-01-22 21:59 UTC, nmetulev commented on concepts/toolkit/providers/electron.md
> +| isIncrementalConsentEnabled | Enable/Disable incremental consent, false by default. Incrememntal consent is currently not fully supported. |
I agree it's worth mentioning, but consider doing that as a note somewhere in the docs and not as a property. It's likely that when/if we add support for incremental consent, there won't be a need for a property and it will just be supported.

2021-01-23 00:32 UTC, opbld34 commented
Docs Build status updates of commit _[618dd07](https://github.com/amrutha95/microsoft-graph-docs/commits/618dd0722a7c0ea92e82993b4ead5cd53a70bb8f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230031041450-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2e2NNUIJ8EtHBEzOktVNiFCzI70eH2cG2DaH8Za6pZo%3D&st=2021-01-23T00%3A27%3A21Z&se=2021-02-23T00%3A32%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 00:44 UTC, opbld32 commented
Docs Build status updates of commit _[2d0b01e](https://github.com/amrutha95/microsoft-graph-docs/commits/2d0b01eb714445ec918465f35a8c9024d7846fa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230042435783-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xtw2Crt3Ut8sxmNSv3%2FzEZMdv4aoUor5%2B0bNfkYqU2Q%3D&st=2021-01-23T00%3A39%3A07Z&se=2021-02-23T00%3A44%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 00:47 UTC, opbld30 commented
Docs Build status updates of commit _[c756610](https://github.com/amrutha95/microsoft-graph-docs/commits/c756610396b07a0ae1cb981bfdb706d8afea7f70)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101230046121606-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iW%2FtVI0Ff3IWfYcs1tBRfkKyiObbaC%2BweMnUYIJdEKw%3D&st=2021-01-23T00%3A42%3A40Z&se=2021-02-23T00%3A47%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 01:08 UTC, opbld32 commented
Docs Build status updates of commit _[dfaf994](https://github.com/amrutha95/microsoft-graph-docs/commits/dfaf99427b435f7e5cd542b78a72b4f76700a3ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/use-toolkit-with-electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/use-toolkit-with-electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101280107349066-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H8aEHzuj%2FOJ39vtr3bNM6d6qf8%2Bj4tjWyVPdqjTuY78%3D&st=2021-01-28T01%3A03%3A55Z&se=2021-02-28T01%3A08%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 02:37 UTC, opbld32 commented
Docs Build status updates of commit _[a744451](https://github.com/amrutha95/microsoft-graph-docs/commits/a74445148d6cb0130498e704aceae177b4d6fd51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/use-toolkit-with-electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/use-toolkit-with-electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101280235519034-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3DE%2BIbxdiDzhAfhN1mtVW56ED5SDJDtXMnprPAMo8lg%3D&st=2021-01-28T02%3A32%3A12Z&se=2021-02-28T02%3A37%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 02:38 UTC, opbld33 commented
Docs Build status updates of commit _[10878ba](https://github.com/amrutha95/microsoft-graph-docs/commits/10878ba02f6d6d864dd2878e34ed7622c1d12523)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/use-toolkit-with-electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/use-toolkit-with-electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101280237112203-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s5UQ84IMNftwX7wlT%2FH%2FBSFhiiLLrSuFjgj5xAtyStA%3D&st=2021-01-28T02%3A33%3A53Z&se=2021-02-28T02%3A38%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 02:40 UTC, opbld30 commented
Docs Build status updates of commit _[aad59a9](https://github.com/amrutha95/microsoft-graph-docs/commits/aad59a9b016c75e84a627cb08feca8dcdd161a2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/use-toolkit-with-electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/use-toolkit-with-electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101280237498293-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8TVGgMqBXAN38n5iqN0VQtEpZ4sgFmpZR6MgdCfxO14%3D&st=2021-01-28T02%3A35%3A30Z&se=2021-02-28T02%3A40%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 19:59 UTC, opbld31 commented
Docs Build status updates of commit _[975bc9d](https://github.com/amrutha95/microsoft-graph-docs/commits/975bc9d0ec2e04f487e409e27cdaae74d93de334)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/use-toolkit-with-electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/use-toolkit-with-electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101281956564164-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EQvJFUetsIDPsIVDHhFjhSYVDmo3tSaM9mNM8Am5Uf4%3D&st=2021-01-28T19%3A54%3A07Z&se=2021-02-28T19%3A59%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 22:54 UTC, opbld30 commented
Docs Build status updates of commit _[565bb06](https://github.com/amrutha95/microsoft-graph-docs/commits/565bb060b182cd20b8150ad9526f68ed4defce5a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/use-toolkit-with-electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/use-toolkit-with-electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/use-toolkit-with-electron?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282253146545-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jPkDXTtozSBKTnorIXEupAuQgYwpPTuPf7cFa%2FpTalo%3D&st=2021-01-28T22%3A49%3A22Z&se=2021-02-28T22%3A54%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 22:56 UTC, opbld33 commented
Docs Build status updates of commit _[0f5ba24](https://github.com/amrutha95/microsoft-graph-docs/commits/0f5ba241b9b857810c76c3ce18151fd10594f325)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282255328303-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8lF7qothls4T6bWky3u8R0jmxKi5OPNo%2FCdUpDiZklc%3D&st=2021-01-28T22%3A51%3A41Z&se=2021-02-28T22%3A56%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 22:58 UTC, opbld34 commented
Docs Build status updates of commit _[007b460](https://github.com/amrutha95/microsoft-graph-docs/commits/007b4601e6e6339ac8bfb91f9e28876361ca2ff9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101282257443014-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Tey2dKrYueS1AKOsbBiGaaZxD%2BxK7xwVWIapHkypK%2BU%3D&st=2021-01-28T22%3A53%3A54Z&se=2021-02-28T22%3A58%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 00:30 UTC, opbld34 commented
Docs Build status updates of commit _[4751246](https://github.com/amrutha95/microsoft-graph-docs/commits/4751246fb65f203e270de9cae503a3a44edfcffa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050028512398-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HMdee%2BP8S1%2BfyMx6dnzRtedYgiOx%2BswdEx7q58ZxePQ%3D&st=2021-02-05T00%3A25%3A13Z&se=2021-03-08T00%3A30%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 00:51 UTC, opbld32 commented
Docs Build status updates of commit _[433bcb0](https://github.com/amrutha95/microsoft-graph-docs/commits/433bcb0b65c8751b3b9e8697ef269c7acd9cc4d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) | [Details](#user-content-25af6bde-3e33f376)
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |

<a id="25af6bde-3e33f376"></a>
### [concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md)
 - **Line 81, Column 41**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../toolkit/get-started/build-an-electron-app.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050049583235-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1clRnHHXNbFpRLLHy5Bhd%2BXKKPBZckM4MuXvS1%2FGt5A%3D&st=2021-02-05T00%3A46%3A40Z&se=2021-03-08T00%3A51%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 00:53 UTC, opbld32 commented
Docs Build status updates of commit _[792442a](https://github.com/amrutha95/microsoft-graph-docs/commits/792442a70e3c5a158a3575f795ae7cd65169327b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) | [Details](#user-content-25af6bde-9ae78b4d)
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |

<a id="25af6bde-9ae78b4d"></a>
### [concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md)
 - **Line 80, Column 41**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../toolkit/get-started/build-an-electron-app.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050050114779-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Y1wpIY%2Fb5PF5t8Dn%2By5m7trbuE%2FN0qBIlZ0ZtusNj8g%3D&st=2021-02-05T00%3A48%3A05Z&se=2021-03-08T00%3A53%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 00:58 UTC, opbld31 commented
Docs Build status updates of commit _[64957e5](https://github.com/amrutha95/microsoft-graph-docs/commits/64957e50b674357e85a0313f6f37008069f28e15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050057176551-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hb5GO2zkz96wzNTTXUFXSp08hceQcJrRlGhw3bJcB7w%3D&st=2021-02-05T00%3A53%3A44Z&se=2021-03-08T00%3A58%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 01:42 UTC, opbld33 commented
Docs Build status updates of commit _[e6e038e](https://github.com/amrutha95/microsoft-graph-docs/commits/e6e038e66e194819528a3454efb3cd2f79ece2c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102050140500165-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0ZaX7EJZJ%2FrVMOtzDrbPELu4PmU%2FmaK9WkQze8bgvC8%3D&st=2021-02-05T01%3A37%3A12Z&se=2021-03-08T01%3A42%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 17:49 UTC, opbld31 commented
Docs Build status updates of commit _[8b7c8f6](https://github.com/amrutha95/microsoft-graph-docs/commits/8b7c8f6cb3e780271b283626aa620968335f068d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051748114573-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gv7UHvVv5ceLtPpX5yQpqRzFrZv9iCd2WWqGaO9KrPA%3D&st=2021-02-05T17%3A44%3A49Z&se=2021-03-08T17%3A49%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 17:52 UTC, opbld30 commented
Docs Build status updates of commit _[fdb7598](https://github.com/amrutha95/microsoft-graph-docs/commits/fdb7598bb52f69404c9d149202de74e400b80324)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051750260384-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kEcJOer74EXBK6Up8q1JfBAfcbAVKPobGnOnglp19%2Bc%3D&st=2021-02-05T17%3A46%3A59Z&se=2021-03-08T17%3A51%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 17:53 UTC, opbld33 commented
Docs Build status updates of commit _[ca55612](https://github.com/amrutha95/microsoft-graph-docs/commits/ca556120ec30346e59252322eb097f43d0557fae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051750447906-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x6crVNPPMJJK1r9AjruEigyaQpqIffUtrrsI%2B13Om2s%3D&st=2021-02-05T17%3A48%3A38Z&se=2021-03-08T17%3A53%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 17:55 UTC, opbld32 commented
Docs Build status updates of commit _[b169e88](https://github.com/amrutha95/microsoft-graph-docs/commits/b169e88d6ab5c4c42a404dc2c1ffad29ab5d4b45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) | [Details](#user-content-6e76f498-2a93940c)
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

<a id="6e76f498-2a93940c"></a>
### [concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md)
 - **Line 21, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './providers/electron.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051753392318-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xJii9alWxMYhM9UHWn2XXSGn1mo5DzE6TNI%2F4nmVlv4%3D&st=2021-02-05T17%3A50%3A12Z&se=2021-03-08T17%3A55%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 17:56 UTC, opbld33 commented
Docs Build status updates of commit _[26dd248](https://github.com/amrutha95/microsoft-graph-docs/commits/26dd2481372cd33725de5eebe7d95a391c6ca33a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) | [Details](#user-content-6e76f498-19d96b3d)
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |

<a id="6e76f498-19d96b3d"></a>
### [concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md)
 - **Line 21, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './providers/electron.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051753509404-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vl9gK6HgeUZOXYyLrDd7NSXukfTF0zLhCjpnGIhLgsA%3D&st=2021-02-05T17%3A51%3A36Z&se=2021-03-08T17%3A56%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 18:31 UTC, opbld32 commented
Docs Build status updates of commit _[e314e30](https://github.com/amrutha95/microsoft-graph-docs/commits/e314e30aee03f4adb7a69da9d780444358dd096a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102051830267577-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QYfmqKRTABIxi3cvLZcvsQ%2FeaL77WTQLDdEV4xcb%2F1I%3D&st=2021-02-05T18%3A26%3A47Z&se=2021-03-08T18%3A31%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 20:06 UTC, nmetulev requested changes

2021-02-05 20:06 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> +  cachePlugin: new PersistenceCachePlugin(filePersistence)
what is `filePersisience`?

2021-02-05 21:41 UTC, opbld32 commented
Docs Build status updates of commit _[f8a7d7c](https://github.com/amrutha95/microsoft-graph-docs/commits/f8a7d7c1283d40dde236d23eace8ce3291e99f5e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102052140060399-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xq0ZnSXej2SEtxYwGUepW9aGDO6JbOy%2F4KuAdIj4fwg%3D&st=2021-02-05T21%3A36%3A20Z&se=2021-03-08T21%3A41%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 22:11 UTC, opbld33 commented
Docs Build status updates of commit _[d794547](https://github.com/amrutha95/microsoft-graph-docs/commits/d79454782f8401db35da12d13c501debb9497d46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102052210106674-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rGBWP6s%2Bg91AzkLNi%2F%2FPApTO0wJgRXlMSMaTIYnrM2I%3D&st=2021-02-05T22%3A06%3A26Z&se=2021-03-08T22%3A11%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:18 UTC, opbld30 commented
Docs Build status updates of commit _[c4955aa](https://github.com/amrutha95/microsoft-graph-docs/commits/c4955aae8a9ca5740c94de3999e508c976ba5175)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060016571126-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2%2FAb9LJNuHQQPoDawsAn%2FLWm%2F%2BkEHcxRr8MGaWCPJow%3D&st=2021-02-06T00%3A13%3A11Z&se=2021-03-09T00%3A18%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:21 UTC, opbld34 commented
Docs Build status updates of commit _[ffcad8b](https://github.com/amrutha95/microsoft-graph-docs/commits/ffcad8b472cee463dcfdc2a5ff93166d0900ddf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060020413530-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4J0TIx%2BAhU%2BzbjnwaDWFYTuNWJFpJxuWk%2B%2BvH0I20%2Bo%3D&st=2021-02-06T00%3A16%3A49Z&se=2021-03-09T00%3A21%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:23 UTC, opbld31 commented
Docs Build status updates of commit _[70e0668](https://github.com/amrutha95/microsoft-graph-docs/commits/70e0668a710a33a7ff1286ada228a4668dad9a39)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060021394171-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wEeIvPunFZXgc%2FtuawruHJlIJNveYHIgSBK%2BJGy9SEw%3D&st=2021-02-06T00%3A18%3A03Z&se=2021-03-09T00%3A23%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:24 UTC, opbld31 commented
Docs Build status updates of commit _[7e09c74](https://github.com/amrutha95/microsoft-graph-docs/commits/7e09c74c64abfc63afdf7a9ebe1e0064ee241f56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060023238061-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sMYBxlcR2Ds%2FSAwpvBDo88TLzay135%2FV3sqZo%2FOX55I%3D&st=2021-02-06T00%3A19%3A29Z&se=2021-03-09T00%3A24%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:26 UTC, opbld31 commented
Docs Build status updates of commit _[bc27332](https://github.com/amrutha95/microsoft-graph-docs/commits/bc2733270949d24cd5f2a977dbee6c96fd41ff74)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060025083672-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bz5A7A2bhMSkX%2FnDTS32kTucMGSiK5b9jBjlvXIeyf0%3D&st=2021-02-06T00%3A21%3A19Z&se=2021-03-09T00%3A26%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:29 UTC, opbld32 commented
Docs Build status updates of commit _[76230bd](https://github.com/amrutha95/microsoft-graph-docs/commits/76230bdfe5156cc89c7e62b61c8b11375a9607ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060028276040-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wMUrLmyyHm9XL1n4%2BPgdZ5%2FkDklw0uqspbxEeDNE%2Ba8%3D&st=2021-02-06T00%3A24%3A22Z&se=2021-03-09T00%3A29%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:39 UTC, opbld33 commented
Docs Build status updates of commit _[fc6075c](https://github.com/amrutha95/microsoft-graph-docs/commits/fc6075ca3efd7ce48a47447dc2f23ebfa8dda2ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060037592709-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GpPXO2Bu2Kekjx5vbChcoEgPtQr0qP%2FYRuDMb7%2B6HOQ%3D&st=2021-02-06T00%3A34%3A08Z&se=2021-03-09T00%3A39%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:41 UTC, opbld34 commented
Docs Build status updates of commit _[5184c5f](https://github.com/amrutha95/microsoft-graph-docs/commits/5184c5fd53e092363665fb33900acff02fc043ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060040173892-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0GJntQo9HQuo7%2Byx7dU02E9Q3LcTrcBScYh1Tjd4vQw%3D&st=2021-02-06T00%3A36%3A32Z&se=2021-03-09T00%3A41%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:46 UTC, opbld31 commented
Docs Build status updates of commit _[e235417](https://github.com/amrutha95/microsoft-graph-docs/commits/e235417f6d5d009f6bed51f966733fa84966fbc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060045031541-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dexmP5JjkeyHxh6USUQA1aIL9KYSRpou3f4MpT4mrMc%3D&st=2021-02-06T00%3A41%3A08Z&se=2021-03-09T00%3A46%3A08Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:47 UTC, opbld34 commented
Docs Build status updates of commit _[f890ca4](https://github.com/amrutha95/microsoft-graph-docs/commits/f890ca40f20e54040b683eca8d41e903dc2b3a4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060045573868-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vMYp8yS9v%2FzX7uP8LK%2BkR8yo4eUG3ZSTGsi4X3EFnBA%3D&st=2021-02-06T00%3A42%3A34Z&se=2021-03-09T00%3A47%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 00:49 UTC, opbld33 commented
Docs Build status updates of commit _[e0f9207](https://github.com/amrutha95/microsoft-graph-docs/commits/e0f92073344c38d745c867619846b4cea3c1f795)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060047410657-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MT%2B21XLvfNxhixfYX1wodvBaCVb1pD%2BPWZrOcpYSgEk%3D&st=2021-02-06T00%3A44%3A04Z&se=2021-03-09T00%3A49%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 01:31 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> +
```suggestion
### Initializing ElectronProvider in your renderer process

The `ElectronProvider` is responsible for communicating with `ElectronAuthenticator` (in the main process) to request access tokens and receive information regarding logged in state that are required for the mgt components to work. 

To initialize the `ElectronProvider`, add the following code to the *src/rendered.ts* file:
```

2021-02-10 01:31 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> +import '@microsoft/mgt-components';
```suggestion
// import the mgt components so we can use them in our html
import '@microsoft/mgt-components';
```

2021-02-10 01:31 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> +
```suggestion
### Initializing ElectronAuthenticator in your main process

The `ElectronAuthenticator` is responsible for setting up the configuration variables for MSAL authentication, acquiring access tokens and communicating with the `ElectronProvider`. Let's Initialize the `ElectronAuthenticator` in the main process and set up the configuration variables such as client-id and required scopes. 

First, open *src/main.ts* and import `ElectronAuthenticator` and  `MsalElectronConfig` from `@microsoft/mgt-electron-provider` at the top of the page:

```

2021-02-10 01:31 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> + Here is an example index.html:
```suggestion
Let's add some content to our app. We can now use the Microsoft Graph toolkit components in our *index.html* page and show the user's agenda. Replace the content of the *index.html* page with the following:
```

2021-02-10 01:31 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> + We recommend this step to avoid running into errors by bundling all the modular dependencies in this project.
```suggestion
 Before we can run the app, we will need to bundle our code to ensure all of our modular dependencies are included in the final payload. If you are already bundling your app code, you can skip this step.
```

2021-02-10 01:31 UTC, nmetulev commented on concepts/toolkit/get-started/build-an-electron-app.md
> + #### webpack.config.js
```suggestion
 #### webpack.config.js
 
Create a new *webpack.config.js* file in the root folder of your project, and paste the following configuration:
 
```

2021-02-10 18:22 UTC, opbld32 commented
Docs Build status updates of commit _[4694b99](https://github.com/amrutha95/microsoft-graph-docs/commits/4694b99f74c1b8af9a7e20cdbe4f0cf61df4e659)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101820516224-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PK0x4sNR74WcBEYRnlFO15GDBhtk6n7jBOr24ehTLic%3D&st=2021-02-10T18%3A17%3A54Z&se=2021-03-13T18%3A22%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[32d41b1](https://github.com/amrutha95/microsoft-graph-docs/commits/32d41b169b9ebfd64ecb922371163e648f4a8c73)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101823295850-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eLzGlHutZLz9lMtLDsyQJi5EMfcT3X0hzXiiUNoDGC4%3D&st=2021-02-10T18%3A19%3A40Z&se=2021-03-13T18%3A24%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:52 UTC, opbld34 commented
Docs Build status updates of commit _[48a2d1d](https://github.com/amrutha95/microsoft-graph-docs/commits/48a2d1dcac8fa647554b255d691bb87a738c8107)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101851123555-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=S%2BwQf3cDF5rKZwkyjpDdNzyEUd3EKV4hX9JVZf9GVMs%3D&st=2021-02-10T18%3A47%3A31Z&se=2021-03-13T18%3A52%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 18:57 UTC, opbld34 commented
Docs Build status updates of commit _[6dea9b2](https://github.com/amrutha95/microsoft-graph-docs/commits/6dea9b27cfd803c689f4cd65dcf1e39ef324cf2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101855121871-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dDSt6%2Fhd2%2FiyLQkO%2F5olSS68Ta5atboZO7GI1sZCsvs%3D&st=2021-02-10T18%3A52%3A22Z&se=2021-03-13T18%3A57%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 21:11 UTC, opbld32 commented
Docs Build status updates of commit _[5da614a](https://github.com/amrutha95/microsoft-graph-docs/commits/5da614ae045817547f929ce337c82912a9d42b26)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102109106328-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fuZpcLMfLcWMK4o1kPDhGFUHKBpsQnJSGuqj3rI59gk%3D&st=2021-02-10T21%3A06%3A20Z&se=2021-03-13T21%3A11%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 23:44 UTC, nmetulev approved these changes

2021-02-11 00:43 UTC, opbld30 commented
Docs Build status updates of commit _[eaeb9b7](https://github.com/amrutha95/microsoft-graph-docs/commits/eaeb9b73ed0ce57c65ba23a5c6d91edd0c018183)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110042137276-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8zhv0RRFsfkrW8ANa%2Fgz8gUfBYhdppaYexbxkf04RqA%3D&st=2021-02-11T00%3A38%3A29Z&se=2021-03-14T00%3A43%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 17:20 UTC, elisenyang approved these changes

2021-02-11 17:20 UTC, elisenyang commented on concepts/toolkit/get-started/build-an-electron-app.md
> + ### Add MGT components to your HTML page
```suggestion
### Add components to your HTML page
```

2021-02-11 17:20 UTC, elisenyang commented on concepts/toolkit/get-started/build-an-electron-app.md
> +Install the `@microsoft/mgt-electron-provider` and `@microsoft/mgt-element` npm packages as well. These will allow you to provide authentication for your app using MSAL, and further be able to use th
```suggestion
Install the `@microsoft/mgt-electron-provider` and `@microsoft/mgt-element` npm packages as well. These will allow you to provide authentication for your app using MSAL, and further be able to use the Microsoft Graph Toolkit components.
```

2021-02-11 17:20 UTC, elisenyang commented on concepts/toolkit/providers/electron.md
> +The ElectronProvider is responsible for communicating with ElectronAuthenticator (in the main process) to request access tokens and receive information regarding logged in state that are required for
```suggestion
The ElectronProvider is responsible for communicating with ElectronAuthenticator (in the main process) to request access tokens and receive information regarding logged in state that are required for the components to work. 
```

2021-02-11 18:41 UTC, opbld33 commented
Docs Build status updates of commit _[e51f58f](https://github.com/amrutha95/microsoft-graph-docs/commits/e51f58ff977e1ce377b4a8605100831d9c516d8b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111840318524-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=msoSY7jI%2FsfDIBhtMkIVOoGirFep0o9vUrRYHGowb64%3D&st=2021-02-11T18%3A36%3A41Z&se=2021-03-14T18%3A41%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 19:23 UTC, opbld32 commented
Docs Build status updates of commit _[2376355](https://github.com/amrutha95/microsoft-graph-docs/commits/23763557cf55e55a5ea1525a54c5cd4297024740)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111921489139-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eE9thupj9ruvKrInWkI98b3eUKVqNxjMX8kBuYmJTl4%3D&st=2021-02-11T19%3A18%3A04Z&se=2021-03-14T19%3A23%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 19:26 UTC, opbld33 commented
Docs Build status updates of commit _[9186834](https://github.com/amrutha95/microsoft-graph-docs/commits/91868346b2b21f3da55bb488df4a46490df0b243)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/get-started/build-an-electron-app.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/get-started/build-an-electron-app.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/get-started/build-an-electron-app?branch=pr-en-us-11289) |
[concepts/toolkit/overview.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/overview?branch=pr-en-us-11289) |
[concepts/toolkit/providers/electron.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/electron.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/electron?branch=pr-en-us-11289) |
[concepts/toolkit/providers/providers.md](https://github.com/amrutha95/microsoft-graph-docs/blob/patch-4/concepts/toolkit/providers/providers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/toolkit/providers/providers?branch=pr-en-us-11289) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111924578002-11289%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0H1i%2Bq7Nt%2BvLihmkO0O%2B3FQDhfuqJHR84PvTItjutm4%3D&st=2021-02-11T19%3A21%3A16Z&se=2021-03-14T19%3A26%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 20:04 UTC, merged