[CloudPC]Add description and value for CloudPC enum types
microsoftgraph/microsoft-graph-docs pull request #11291
Opened 2021-01-15 06:38 UTC by AshleyYangSZ

As most of the time customer will just give our support the error value in the ticket. Add more description and value will help them identify the root cause.

2021-01-15 06:39 UTC, opbld30 commented
Docs Build status updates of commit _[875e979](https://github.com/microsoftgraph/microsoft-graph-docs/commits/875e9796bf9428ac36d88f39723989090936882e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcprovisioningpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcprovisioningpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcprovisioningpolicy?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101150638268262-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9Lg9mqZF3Q8SMu3RqqaSP8uH4pys4hlOIe60z1X%2FbKA%3D&st=2021-01-15T06%3A34%3A54Z&se=2021-02-15T06%3A39%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 09:40 UTC, opbld33 commented
Docs Build status updates of commit _[3db087f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3db087f452472e1ae025742826bf232ea49d5b6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-e052fb64-bd96f079)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

<a id="e052fb64-bd96f079"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 31, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpconpremisesconnection.md/'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101150939075210-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZN7bqpE6czFoxKgHHnD0y9m8qL%2BMAg8aCgI%2F2yT8vr0%3D&st=2021-01-15T09%3A35%3A19Z&se=2021-02-15T09%3A40%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 09:53 UTC, opbld31 commented
Docs Build status updates of commit _[fbd4931](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbd493175bdcc877a17cf619161dad8317f8160e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-5b691f94-8a961ec9)
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-e7e31ea0-8a961ec9)
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-d71ffbf9-8a961ec9)
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-e052fb64-8a961ec9)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

<a id="5b691f94-8a961ec9"></a>
### [api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md)
 - **Line 40, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#cloudPcStatus-values' in 'beta/resources/cloudpc.md', did you mean '#cloudpcstatus-values'?`````

<a id="e7e31ea0-8a961ec9"></a>
### [api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md)
 - **Line 41, Column 9**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#cloudPcDeviceImageStatus-values' in 'beta/resources/cloudpcdeviceimage.md', did you mean '#cloudpcdeviceimagestatus-values'?`````
 - **Line 42, Column 16**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#cloudPcDeviceImageStatusDetails-values' in 'beta/resources/cloudpcdeviceimage.md', did you mean '#cloudpcdeviceimagestatusdetails-values'?`````

<a id="d71ffbf9-8a961ec9"></a>
### [api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md)
 - **Line 47, Column 20**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#cloudPcOnPremisesConnectionStatus-values' in 'beta/resources/cloudpconpremisesconnection.md', did you mean '#cloudpconpremisesconnectionstatus-values'?`````

<a id="e052fb64-8a961ec9"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 31, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpconpremisesconnection.md/'.`````
 - **Line 34, Column 12**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#cloudPcOnPremisesConnectionHealthCheckErrorType-values' in 'beta/resources/cloudpconpremisesconnectionhealthcheck.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101150951485024-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FTEyxe8se6WWaZgAGpPU1RiZu%2FaIkicaWzc8jnvMo88%3D&st=2021-01-15T09%3A47%3A59Z&se=2021-02-15T09%3A52%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 10:16 UTC, opbld30 commented
Docs Build status updates of commit _[e8e39df](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8e39df2a75829bcb91a4da5479f4a0aaa1b4987)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-e052fb64-89269936)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

<a id="e052fb64-89269936"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 31, Column 9**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/cloudpconpremisesconnection.md/'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101151015031055-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FnFXWGzLKfeT3MbteBCSv%2BNgbrkiA928VlkAHL8Gmpc%3D&st=2021-01-15T10%3A11%3A10Z&se=2021-02-15T10%3A16%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 10:22 UTC, opbld34 commented
Docs Build status updates of commit _[f9a2e96](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9a2e962bbf226155e0d7d02ca246b60c4d44125)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101151021015419-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jpO9I2VLJ9Q1xA43LxcsqH%2Bswq0J6b%2FflinSvxwGlnU%3D&st=2021-01-15T10%3A17%3A09Z&se=2021-02-15T10%3A22%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 10:40 UTC, opbld31 commented
Docs Build status updates of commit _[31266a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31266a73d62b2f79416a740b3800f72e3a807a7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101151039454591-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LFTJvVU7E%2BT0JPRN17rRENLIsDFR4DTd0hPZTIJ7G94%3D&st=2021-01-15T10%3A35%3A58Z&se=2021-02-15T10%3A40%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 16:25 UTC, opbld32 commented
Docs Build status updates of commit _[dc9de79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dc9de79f086049d1dc46bb1774a5ae84386ad03f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101151624185610-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QRqmKjUuT%2F8VBdDqKOgKrCX6b2SuibpId0WRmNtp7v8%3D&st=2021-01-15T16%3A20%3A31Z&se=2021-02-15T16%3A25%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-15 23:43 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|status|[cloudPcDeviceImageStatus](#cloudpcdeviceimagestatus-values)|The status of the image on cloud PC. Possible status include upload pending, failed to upload, or ready to use. Possible values ar
Line 41:
Since you're providing more details for each possible status, you can please remove the second sentence in the description "Possible status include upload pending, failed to upload, or ready to use." This would be consistent with Microsoft Voice: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25356.

2021-01-15 23:44 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|sourceImageNotFound|The source image is not valid for provisioning a windows VM with it.|
Line 57:
Capitalize 'W' in "windows".

2021-01-15 23:48 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatus|[cloudPcOnPremisesConnectionStatus](#cloudpconpremisesconnectionstatus-values)|The status of the most recent health check done on the on-premises connection. For example, if status
Line 47:
Please list the possible values in camel case.

2021-01-15 23:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
>  |startDateTime|DateTimeOffset|The start time of the health check item. Read-only.|
Line 31:
Please list the possible values in camel case.

2021-01-15 23:56 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckUrlNotWhitelisted|The endpoint connectivity check failed because the url isn’t on the allowlist in the network firewall settings. Please add URLs to whitelisted network fire
Line 49:
Please change 'url" to "URL".
Please change "allowlist" to "allow list".
Please change "whitelisted" to "white-listed". (Checking with @Lauragra if there's an alternative term we should use in place of "white-list".)

2021-01-16 00:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|permissionCheckNoResourceGroupOwnerRole|Cloud PC service principal does not have owner permissions on the specified resource group. Please work with subscription owner to add owner role assignment o
Line 56:
Please add "the", as in "Please work with the subscription owner..."

2021-01-16 00:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|errorType|[cloudPcOnPremisesConnectionHealthCheckErrorType](#cloudpconpremisesconnectionhealthcheckerrortype-values)|The type of error that occurred during this health check. Possible values are: `D
Line 34:
Please update the first 11 possible values to use camel case.

2021-01-16 00:16 UTC, angelgolfer-ms requested changes
Looks good overall in applying the enum guidance! Please take a look at my few comments, incorporate them and we'll be good for publishing.

2021-01-16 02:25 UTC, Lauragra commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckUrlNotWhitelisted|The endpoint connectivity check failed because the url isn’t on the allowlist in the network firewall settings. Please add URLs to whitelisted network fire
Please rename the enum value to remove the term "whitelisted". This term is no longer acceptable in public-facing documentation; we shouldn't use it for value names as well. You can revise the sentence to say "Please add the URLs to the allowlist for the network firewall settings.

2021-01-16 13:04 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|status|[cloudPcDeviceImageStatus](#cloudpcdeviceimagestatus-values)|The status of the image on cloud PC. Possible status include upload pending, failed to upload, or ready to use. Possible values ar
Thanks for reminding. Updated.

2021-01-16 13:07 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatus|[cloudPcOnPremisesConnectionStatus](#cloudpconpremisesconnectionstatus-values)|The status of the most recent health check done on the on-premises connection. For example, if status
It's for link to the enum type section, if change it to camel case will not pass API doctor's check and can't link to the section. See [here](https://docs.microsoft.com/en-us/contribute/how-to-write-links)

2021-01-16 13:08 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
>  |startDateTime|DateTimeOffset|The start time of the health check item. Read-only.|
Same as before, it's for adding link to the below enum type section.

2021-01-16 13:19 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|errorType|[cloudPcOnPremisesConnectionHealthCheckErrorType](#cloudpconpremisesconnectionhealthcheckerrortype-values)|The type of error that occurred during this health check. Possible values are: `D
As I put the cloudPcOnPremisesConnectionHealthCheckErrorType enum values table below, I think should follow your first comment and remove these possible value description here.
>>"Since you're providing more details for each possible status, you can please remove the second sentence in the description "Possible status include upload pending, failed to upload, or ready to use.""

2021-01-16 13:23 UTC, opbld34 commented
Docs Build status updates of commit _[c7e101a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7e101acce08b5bb4ccc69613b42b0e8f8f291e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101161321420722-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=io1j5ci9wtjFbkWHl%2FrS0xotpQjQ9xe3fRcPvCs9uVU%3D&st=2021-01-16T13%3A17%3A59Z&se=2021-02-16T13%3A22%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-16 13:24 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckUrlNotWhitelisted|The endpoint connectivity check failed because the url isn’t on the allowlist in the network firewall settings. Please add URLs to whitelisted network fire
Added link for "here". I don't know if it's the right way to add link to a MS doc. I followed this [guide ](https://docs.microsoft.com/en-us/contribute/how-to-write-links).

2021-01-20 04:26 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatus|[cloudPcOnPremisesConnectionStatus](#cloudpconpremisesconnectionstatus-values)|The status of the most recent health check done on the on-premises connection. For example, if status
@AshleyYangSZ , I mean change to this sentence that uses camel case for the possible values:
"Possible values are: `pending`, `running`, `passed`, `failed`, `unknownFutureValue`."

Are you saying including a sentence like the above with the camel case values would cause an API Doctor error?

2021-01-20 04:28 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
>  |startDateTime|DateTimeOffset|The start time of the health check item. Read-only.|
And same as my last comment above, I mean changing to this sentence that uses camel case for the possible values:
"Possible values are: pending, running, passed, failed, unknownFutureValue."

Are you saying including a sentence like that with the camel case values would cause an API Doctor error?

2021-01-20 05:25 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|endpointConnectivityCheckUrlNotWhitelisted|The endpoint connectivity check failed because the url isn’t on the allowlist in the network firewall settings. Please add URLs to whitelisted network fire
That's a great question, @AshleyYangSZ . It's not a desired practice to use "here" (or something vague of that sort) to be the link text. The general writing guidance for any doc set, not Graph-specific, is to use blend the link text to fit the sentence/context that you're linking from. That's using the Microsoft Voice guidance - our content needs to read smoothly in the context so that it's natural sounding, just like in a conversation, but you don't want to include a lot of excessive words just to create some natural sounding content. In this case, I would suggest "See more information about URLs to allow in order to use Windows Virtual Desktop." and use "URLs to allow in order to use Windows Virtual Desktop" as the link text.

Just to complete answering your question, in general, if using the above approach is not obvious to the author, then you can just use the destination topic title to be the link text. If we use this approach here, the sentence would be "See required URL list for URL information." and the link text would be "required URL list". IMO, the topic title "required URL list" is not quite the same as the context in your topic. Your topic is about the URLs that should be allowed, and "allowed" in general is not the same as "required".

2021-01-20 05:29 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|errorType|[cloudPcOnPremisesConnectionHealthCheckErrorType](#cloudpconpremisesconnectionhealthcheckerrortype-values)|The type of error that occurred during this health check. Possible values are: `D
Ok, I think in this case (the errorType property), it's ok that you don't list the possible values in the property description, even though our [CDK guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic) is:
"Specifying the possible values in the description is not required but convenient for customers."

This is because the values are so long, it's hard for customers to scan and parse at a glance that many long strings in a table cell anyway.

2021-01-20 05:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcdeviceimage.md
> +|status|[cloudPcDeviceImageStatus](#cloudpcdeviceimagestatus-values)|The status of the image on cloud PC. Possible status include upload pending, failed to upload, or ready to use. Possible values ar
@AshleyYangSZ , I think you misunderstood my last comment. 
Originally you had this, 3 sentences:
"The status of the image on cloud PC. Possible status include upload pending, failed to upload, or ready to use. Possible values are: `pending`, `ready`, `failed`."
I meant/mean you don't have to have both the 2nd and the 3rd sentences. So I suggested you to remove the 2nd, because the enum table (https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291#cloudpcdeviceimagestatus-values) has descriptions that overlap with the info in the 2nd sentence.
But I think it's a good idea to include the 3rd sentence in the property description, which lists the possible enum values.
Like our CDK (https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic) says for the second enum option:
"Specifying the possible values in the description is not required but convenient for customers."

2021-01-20 05:55 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpc.md
>  |statusDetails|[cloudPcStatusDetails](../resources/cloudpcstatusdetails.md)|The details of the cloud PC status.|
Line 40:
I think you misunderstood one of my comments (https://github.com/microsoftgraph/microsoft-graph-docs/pull/11291#discussion_r560694803).
In general, it's a good idea to include the possible values, as described in the second enum option in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).

The only exception in this PR that I think is better (time saving for you to maintain, less text for customers to scan) not to list in the property description the supported enum values for a property of the enum type cloudPcOnPremisesConnectionHealthCheckErrorType.

2021-01-20 05:56 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpcdeviceimage.md
Lines 41, 42:
I think you misunderstood one of my comments (https://github.com/microsoftgraph/microsoft-graph-docs/pull/11291#discussion_r560694803).
In general, it's a good idea to include the possible values, as described in the second enum option in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).

The only exception in this PR that I think is better (time saving for you to maintain, less text for customers to scan) not to list in the property description the supported enum values for a property of the enum type cloudPcOnPremisesConnectionHealthCheckErrorType.

2021-01-20 05:56 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatus|[cloudPcOnPremisesConnectionStatus](#cloudpconpremisesconnectionstatus-values)|The status of the most recent health check done on the on-premises connection. For example, if status
Line 47:
I think you misunderstood one of my comments (https://github.com/microsoftgraph/microsoft-graph-docs/pull/11291#discussion_r560694803).
In general, it's a good idea to include the possible values, as described in the second enum option in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).

The only exception in this PR that I think is better (time saving for you to maintain, less text for customers to scan) not to list in the property description the supported enum values for a property of the enum type cloudPcOnPremisesConnectionHealthCheckErrorType.

2021-01-20 05:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatus|[cloudPcOnPremisesConnectionStatus](#cloudpconpremisesconnectionstatus-values)|The status of the most recent health check done on the on-premises connection. For example, if status
One thing to note:
Please put the sentence for the possible values before and the sentence "Read-only."

2021-01-20 05:57 UTC, angelgolfer-ms commented on api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md
> +|status|[cloudPcOnPremisesConnectionStatus](../resources/cloudpconpremisesconnection.md#cloudpconpremisesconnectionstatus-values)|The status of the health check item. Read-only.|
Line 31:
I think you misunderstood one of my comments (https://github.com/microsoftgraph/microsoft-graph-docs/pull/11291#discussion_r560694803).
In general, it's a good idea to include the possible values, as described in the second enum option in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).

The only exception in this PR that I think is better (time saving for you to maintain, less text for customers to scan) not to list in the property description the supported enum values for a property of the enum type cloudPcOnPremisesConnectionHealthCheckErrorType.

2021-01-20 06:00 UTC, angelgolfer-ms requested changes
Hm, @AshleyYangSZ , thanks for incorporating the last set of feedback.
As noted in my comments, I think you misunderstood one of my comments:
(https://github.com/microsoftgraph/microsoft-graph-docs/pull/11291#discussion_r560694803).
In general, it's a good idea to include the possible values, as described in the second enum option in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).

The only exception in this PR that I think is better (time saving for you to maintain, less text for customers to scan) not to list in the property description the supported enum values for a property of the enum type cloudPcOnPremisesConnectionHealthCheckErrorType.

Would you mind adding the possible values sentence back to most of the enums (except for properties of this type: cloudPcOnPremisesConnectionHealthCheckErrorType?

2021-01-20 06:06 UTC, AshleyYangSZ commented on api-reference/beta/resources/cloudpconpremisesconnection.md
> +|healthCheckStatus|[cloudPcOnPremisesConnectionStatus](#cloudpconpremisesconnectionstatus-values)|The status of the most recent health check done on the on-premises connection. For example, if status
No, I misunderstand. I suppose you asked me to update "(#cloudpconpremisesconnectionstatus-values)" this string to camel case.

2021-01-20 06:30 UTC, opbld30 commented
Docs Build status updates of commit _[cb52332](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cb52332e3fe8b4370568446b2e5426ec914fd327)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) | [Details](#user-content-e052fb64-d12e27b6)
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

<a id="e052fb64-d12e27b6"></a>
### [api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md)
 - **Line 49, Column 1**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/azure/virtual-desktop/safe-url-list' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101200629145407-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T0PU%2FGEwbZV3ebrAWO8cwEkTK4Y%2BupLE8OUPN8mEFXE%3D&st=2021-01-20T06%3A25%3A24Z&se=2021-02-20T06%3A30%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 06:33 UTC, AshleyYangSZ commented
> Hm, @AshleyYangSZ , thanks for incorporating the last set of feedback.
> As noted in my comments, I think you misunderstood one of my comments:
> ([#11291 (comment)](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11291#discussion_r560694803)).
> In general, it's a good idea to include the possible values, as described in the second enum option in the [CDK](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations?anchor=second-option%3A-in-parent-resource-topic).
> 
> The only exception in this PR that I think is better (time saving for you to maintain, less text for customers to scan) not to list in the property description the supported enum values for a property of the enum type cloudPcOnPremisesConnectionHealthCheckErrorType.
> 
> Would you mind adding the possible values sentence back to most of the enums (except for properties of this type: cloudPcOnPremisesConnectionHealthCheckErrorType?

Sure, already updated. Add possible values for other enums except cloudPcOnPremisesConnectionHealthCheckErrorType. Also made them camel case. Update the see here sentence and link. Hope you can have a look again.

2021-01-20 07:27 UTC, opbld34 commented
Docs Build status updates of commit _[d1bff62](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d1bff62da16e5a4fdcd08174ad1965fbc5a55a7f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101200725050849-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OWSxGWF%2FcLb2cvFeA7LAs9SUEmwsr%2Bo4EvkviLGsWoc%3D&st=2021-01-20T07%3A22%3A07Z&se=2021-02-20T07%3A27%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 08:02 UTC, opbld33 commented
Docs Build status updates of commit _[b3a6230](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3a62302b25cf9abea3986c16967fd245abf9c14)_: 

:clock10: **Pending**: waiting for processors ([6](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 6 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-20 08:03 UTC, opbld34 commented
Docs Build status updates of commit _[b3a6230](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3a62302b25cf9abea3986c16967fd245abf9c14)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa0c5411)

<a id="aa0c5411"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101200801517269-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gO6Ap3nuWryktCvdpoWe2BZ%2BhfnyUXGQbsDNnhrLx7w%3D&st=2021-01-20T07%3A58%3A54Z&se=2021-02-20T08%3A03%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 08:08 UTC, opbld30 commented
Docs Build status updates of commit _[832b677](https://github.com/microsoftgraph/microsoft-graph-docs/commits/832b677566bfaf17dbf34acee39c921b94af4353)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-20 08:08 UTC, opbld34 commented
Docs Build status updates of commit _[832b677](https://github.com/microsoftgraph/microsoft-graph-docs/commits/832b677566bfaf17dbf34acee39c921b94af4353)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-64ba375f)

<a id="64ba375f"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101200808077259-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VDjIMkUB%2B3Z6PwlKFMtrQm3VFBoEoJkijgPd8W8nWQk%3D&st=2021-01-20T08%3A03%3A58Z&se=2021-02-20T08%3A08%3A58Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 08:46 UTC, opbld33 commented
Docs Build status updates of commit _[de872d4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de872d4c89c9dc44ae802825ba29e0aa503026cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e4b3db6b)

<a id="e4b3db6b"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101200845446219-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=N6v2vpuCY7KqjBWtTAK1IEzN2pMYfO4QXkraCvf84r4%3D&st=2021-01-20T08%3A41%3A31Z&se=2021-02-20T08%3A46%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-20 16:41 UTC, opbld34 commented
Docs Build status updates of commit _[40554d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/40554d9c15eae878256dd802f5ab2083570c774b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-44fde4c2)

<a id="44fde4c2"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101201640338203-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9osvinCACNNvgy5QSS5lJAUboghv0qn8keN2FGTkONI%3D&st=2021-01-20T16%3A36%3A21Z&se=2021-02-20T16%3A41%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-23 15:28 UTC, opbld34 commented
Docs Build status updates of commit _[3ff51d2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ff51d22a652d05f1adff7b63f1e0a3c2a925515)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101231527398608-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FroroZ82Vr00lzxDHKI93UpTEVZOPbDmWZlD3vub0cY%3D&st=2021-01-23T15%3A23%3A50Z&se=2021-02-23T15%3A28%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 09:46 UTC, opbld32 commented
Docs Build status updates of commit _[04a230f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04a230f6a9f6397f42a49074605b8bc689d62aee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/cloudpc.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpc?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpcdeviceimage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpcdeviceimage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpcdeviceimage?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnection.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnection.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnection?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/cloudpconpremisesconnectionhealthcheck.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/cloudpconpremisesconnectionhealthcheck?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/jiajyang/Add_enum_Description/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-11291) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101260945062669-11291%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pc1q43BQ6hea4KCafthSrkee7s5oKlrAhD37ALG0XAc%3D&st=2021-01-26T09%3A41%3A15Z&se=2021-02-26T09%3A46%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 09:24 UTC, angelgolfer-ms approved these changes
Thanks, PR looks good to me!

2021-01-28 03:05 UTC, merged