Update Universal Print Reporting APIs
microsoftgraph/microsoft-graph-docs pull request #11312
Opened 2021-01-16 00:55 UTC by karandaei

* Rename daily and monthly user/printer usage report entities according to latest review with Graph
* Rename **periodStart** and **periodEnd** arguments for retrieving archived jobs to **startDateTime** and **endDateTime** respectively.

2021-01-16 00:55 UTC, opbld30 commented
Docs Build status updates of commit _[5218ef0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5218ef0f33e0b00ecc2ac735fbf45152757c78ac)_: 

:clock10: **Pending**: waiting for processors ([18](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 18 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-16 00:56 UTC, opbld34 commented
Docs Build status updates of commit _[5218ef0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5218ef0f33e0b00ecc2ac735fbf45152757c78ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-c373dc2c-a02132af)
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-f470fd14-a02132af)
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-55e266d4-a02132af)
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-0ff92d39-a02132af)
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-cfd25b7d-a02132af)
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-14407558-a02132af)
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-87660d4f-a02132af)
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-360246be-a02132af)
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-68749861-a02132af)
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyprinter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-bba43cb4-a02132af)
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-bf66f254-a02132af)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-00685cff-a02132af)
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11312) |

<a id="c373dc2c-a02132af"></a>
### [api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyprinter-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f470fd14-a02132af"></a>
### [api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyuser-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="55e266d4-a02132af"></a>
### [api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="0ff92d39-a02132af"></a>
### [api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cfd25b7d-a02132af"></a>
### [api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="14407558-a02132af"></a>
### [api-reference/beta/api/reportroo [...]

2021-01-16 01:01 UTC, opbld32 commented
Docs Build status updates of commit _[5d5bbe6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d5bbe6db8ea93ee4462741e3e8438ad4e4b2410)_: 

:clock10: **Pending**: waiting for processors ([9](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 9 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-16 01:03 UTC, opbld33 commented
Docs Build status updates of commit _[5d5bbe6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5d5bbe6db8ea93ee4462741e3e8438ad4e4b2410)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-c373dc2c-58727810)
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyuser-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-f470fd14-58727810)
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-55e266d4-58727810)
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-0ff92d39-58727810)
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-cfd25b7d-58727810)
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-14407558-58727810)
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-87660d4f-58727810)
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-360246be-58727810)
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-68749861-58727810)
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyprinter.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-bba43cb4-58727810)
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) | [Details](#user-content-bf66f254-58727810)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11312) |

<a id="c373dc2c-58727810"></a>
### [api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyprinter-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f470fd14-58727810"></a>
### [api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyuser-get.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="55e266d4-58727810"></a>
### [api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="0ff92d39-58727810"></a>
### [api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="cfd25b7d-58727810"></a>
### [api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="14407558-58727810"></a>
### [api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.m [...]

2021-01-16 01:23 UTC, opbld30 commented
Docs Build status updates of commit _[65905b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65905b603e4c2ada717b346308057f2e5066d1d0)_: 

:clock10: **Pending**: waiting for processors ([5](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 5 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-16 01:24 UTC, opbld32 commented
Docs Build status updates of commit _[65905b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/65905b603e4c2ada717b346308057f2e5066d1d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11312) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101160123086304-11312%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2xvFJ3QKSWjFvnf0MmYn2nhMN3QU16lk1FgDjGyRmOE%3D&st=2021-01-16T01%3A19%3A20Z&se=2021-02-16T01%3A24%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-16 01:31 UTC, braedenp-msft requested changes

2021-01-16 01:31 UTC, braedenp-msft commented on api-reference/beta/api/printusagebyprinter-get.md
> +GET /reports/monhtlyPrintUsageByPrinter/{id}
Typo

2021-01-16 01:31 UTC, braedenp-msft commented on concepts/changelog.md
> +| Change | beta | Renamed [printusagesummarybyprinter](/graph/api/resources/printusagesummarybyprinter) resource to **printusagebyprinter**. |
Update `changelog.json` instead of `changelog.md`. This file is no longer being used.

2021-01-16 01:32 UTC, braedenp-msft commented
Note to Laura: These changes are being made to reflect what's already been deployed in the service for awhile (fixing a gap in the docs) so there's no breaking change being made on the wire.

2021-02-02 02:17 UTC, opbld33 commented
Docs Build status updates of commit _[96e26ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96e26eda55e9490763cff544d5cc613353cb95ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bcf21eb8)

<a id="bcf21eb8"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102020216333436-11312%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RQCjnT%2FmE9VdE%2BHY92%2Bm%2FfEkrTqx6UDLlBKrJ%2BH1mt8%3D&st=2021-02-02T02%3A12%3A06Z&se=2021-03-05T02%3A17%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 18:24 UTC, opbld32 commented
Docs Build status updates of commit _[705585e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/705585ec93249a68ccb6e6f12ed3434bcfd033fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printusagebyprinter-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyprinter-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/printusagebyuser-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/printusagebyuser-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyuser-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-dailyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-dailyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reportroot-list-monthlyprintusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reportroot-list-monthlyprintusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reports-getgrouparchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getgrouparchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getgrouparchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reports-getprinterarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getprinterarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getprinterarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/api/reports-getuserarchivedprintjobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/api/reports-getuserarchivedprintjobs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/reports-getuserarchivedprintjobs?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyprinter.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyprinter?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/resources/printusagebyuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printusagebyprinter-get?view=graph-rest-beta&branch=pr-en-us-11312) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/karandaei/upreports/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102021823012836-11312%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PRUqh2rL3nnoxMnlEBIuMocbuP%2BZz1eWidenaJAO5SQ%3D&st=2021-02-02T18%3A19%3A17Z&se=2021-03-05T18%3A24%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 19:48 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-05-04 20:28 UTC, nilakhan approved these changes

2021-06-04 01:29 UTC, merged