Update attachment-get.md
microsoftgraph/microsoft-graph-docs pull request #11331
Opened 2021-01-18 20:47 UTC by abheek-das

Updates attachment-get.md to add new property "attachments" for nested attachments.

2021-01-18 20:48 UTC, opbld31 commented
Docs Build status updates of commit _[7a15c53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a15c5324dc7698d924a0eda6d20b8c7a0ddd2f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101182047160190-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4DCIMawbwbOhL75zA4ijlu%2BEDQ0hxIzX2BuNBhrclL8%3D&st=2021-01-18T20%3A43%3A27Z&se=2021-02-18T20%3A48%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-31 18:57 UTC, opbld30 commented
Docs Build status updates of commit _[7b974bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b974bfef263e33d6985855dc44ff149bc739b6c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101311855556521-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HSa4%2FpIXsQ9IkmKiM478Fag4P6NflXkreEUnmY91AvM%3D&st=2021-01-31T18%3A52%3A10Z&se=2021-03-03T18%3A57%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-31 19:02 UTC, opbld32 commented
Docs Build status updates of commit _[37f5cc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/37f5cc255aeed6356f138412abb84e25483b21b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101311900566642-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JVUbNmA2qFUa9%2FKNIyIt8Xol25MzGxbQbMakscLrJL0%3D&st=2021-01-31T18%3A57%3A26Z&se=2021-03-03T19%3A02%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 22:08 UTC, angelgolfer-ms reviewed
Hi @abheek-das ,
Thanks for opening this PR. Can you please first clarify the following about example 3:
(1) Example 3 was set up with this scenario: Message A has an attachment which is message B. Get the properties of A and B. Is that approach shown on the [live site](https://docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&tabs=http#example-3-expand-and-get-the-properties-of-the-item-attached-to-a-message) still correct (other than missing the bodyPreview and internetMessageHeaders properties)?

(2) If (1) is still correct (other than the missing properties), then is the purpose to show what happens, if message B also has a file attachment X, and that same $expand example request would expand both B and X?

2021-02-02 07:16 UTC, abheek-das commented
Hello @angelgolfer-ms ,
For (1): Yes the scenario is the same and the request is unchanged. I checked that all the missing properties are added in the PR.
For (2): Yes that's exactly correct - with the $expand the same example request would expand both B and X (if it exists). Hence, the name nested attachments. You can view up 30 levels of nested attachments using this approach.

Please let me know if you need more context! Thanks!

2021-02-04 06:32 UTC, opbld31 commented
Docs Build status updates of commit _[66f2ab8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66f2ab813d9d41777480b9c323cae4d5295502a8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102040631350783-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ilvn9dT5tukhk21V0EY4J14LmGWmARt%2FR2b6VK%2FaBlA%3D&st=2021-02-04T06%3A27%3A41Z&se=2021-03-07T06%3A32%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 09:44 UTC, opbld31 commented
Docs Build status updates of commit _[c616ff0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c616ff0208db38a9ddc34d7fd9093a41fa745d26)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) | [Details](#user-content-8ca9333e-9b0eef03)
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) | [Details](#user-content-ae28627f-9b0eef03)
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

<a id="8ca9333e-9b0eef03"></a>
### [api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md)
 - **Line 420, Column 46**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#example-3' in 'beta/api/attachment-get.md', did you mean '#examples'?`````

<a id="ae28627f-9b0eef03"></a>
### [api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md)
 - **Line 417, Column 46**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#example-3' in 'v1.0/api/attachment-get.md', did you mean '#examples'?`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102040943471244-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fH6R2haiS%2BH1MBhk3BaN98%2BP1WSlV3yqpxEvCMkKYOg%3D&st=2021-02-04T09%3A39%3A54Z&se=2021-03-07T09%3A44%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 09:57 UTC, opbld32 commented
Docs Build status updates of commit _[ae2ac97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae2ac9785fdb129a7dfdfd7f9adfb90e82082801)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102040956066246-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WvVGJwoTAfnfkyy4ZFQuNFaaZQ02zDYmU0iW0lHvSUc%3D&st=2021-02-04T09%3A52%3A16Z&se=2021-03-07T09%3A57%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 10:10 UTC, angelgolfer-ms requested changes
Hi @abheek-das ,
Thanks for the confirmation for the purpose of this PR.

For clarity, can you please add your example as example 4, and restore example 3 to the simpler case? So example 3 would show expanding an item attachment (a message attached to another message), and example 4 would show expanding the item attachment (a message) together with its file attachment. I recall customers asking about the simpler case (example 3) before we documented it, so it would be useful to keep that separate from the nesting case (example 4).

I know that would be a bit of overhead in addition to what you originally intended (building on top of example 3). I also wanted to try out spec-ing the description of example 4 and see the experience, so I went ahead and added the sub-section title for example 4, and fixed all the related links including links to the new example 4 and pre-existing links to examples 5-8, shifting them by 1 as examples 6-9 respectively.

So your task is to restore example 3 to what it used to be (but add the bodyPreview and internetMessageHeaders properties), insert your example as example 4, under the example 4 sub-section I already added to each of the v1 and beta attachment-get.md topic.

Also, per our communication some weeks ago, I understand you're basically now the PM owner for the mail-related APIs that used to be owned by Siva, so I went ahead to change the Author name from Siva to your Github name in the 3 MD files currently in this PR. At your earliest convenience, please complete that update of the author field in other doc files :-)

Just to be clear, can you please take a look at my last 2 commits ([commit 1](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11331/commits/c616ff0208db38a9ddc34d7fd9093a41fa745d26) and [commit 2](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11331/commits/ae2ac9785fdb129a7dfdfd7f9adfb90e82082801), so that you know exactly what I have done and where you should please insert your example (in example 4)?

Thanks.

2021-02-05 20:25 UTC, opbld31 commented
Docs Build status updates of commit _[889b6e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/889b6e33323c78e85a6023a1fa53aa0fcf6b7878)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102052024007844-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rxLinQI2Jefex4WCX1uVSWM9Leq6feA4%2BJVtu61YcYs%3D&st=2021-02-05T20%3A20%3A06Z&se=2021-03-08T20%3A25%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 20:29 UTC, opbld31 commented
Docs Build status updates of commit _[9cb5247](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9cb524740cbc4985b6a5fddaedc5e6f89f00c6ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102052028309204-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0QlUfztaIb%2BcJICxL7cc5LUyyYJNbh51GfKr1lfeyHA%3D&st=2021-02-05T20%3A24%3A48Z&se=2021-03-08T20%3A29%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 20:31 UTC, opbld32 commented
Docs Build status updates of commit _[e492fea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e492feadddbce94b68546cbc40c0f8fbaccf30dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102052030252711-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vutfebm6XklnLSZJ3b8j1gmrl4BsYxI6E08mtkNI0lc%3D&st=2021-02-05T20%3A26%3A49Z&se=2021-03-08T20%3A31%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 20:47 UTC, abheek-das commented
Hi @angelgolfer-ms ,

Thanks for the feedback. I've:
1. Reviewed your last 2 commits. They look great!
2. Added the response for the newly inserted Example 4, where the original attached item has another attachment of pdf format. The description of the example looks good as well.

Also, acknowledging the request for author name update in the mail API graph pages. I had a draft PR where I think I had made this change, will dig it up, ,review it and float it for review soon :)

Thanks again for helping make the changes!

2021-02-06 05:12 UTC, angelgolfer-ms commented on api-reference/beta/api/attachment-get.md
> +#### Request
After line 405:
You actually needed to add the request again, for 2 reasons: 
(1) Clarity
(2) API Doctor - surprised that API Doctor didn't hickup! I recall definitely it would have before - requests and responses need to be paired, I learned that a harder way but got the API Doctor creator Ryan (who's now back in our group!) to point that out to me.

I added the request back to both the v1 and beta topics.

Also, in line 476, I suppose the ID that follows attachments should be consistent with that ID in the request? I changed it. It's also truncated like the other IDs, for readability.

2021-02-06 05:17 UTC, opbld32 commented
Docs Build status updates of commit _[0a4e7c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a4e7c181c2ba2559d47b7452a35d39810e27e27)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060516077606-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0V9FBNVZ0RMF4tOMFEo6Md4tW%2B2LUQBBiciFCbrYd8g%3D&st=2021-02-06T05%3A12%3A20Z&se=2021-03-09T05%3A17%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 05:18 UTC, opbld32 commented
Docs Build status updates of commit _[891d14d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/891d14dcc7694f73d0f0ee3e0ab8564d25e44032)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060516437987-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=j5bwPGH4rkDAaVzsGh2sMMNNqfbfMXRkXu31Rt%2BWEDg%3D&st=2021-02-06T05%3A13%3A50Z&se=2021-03-09T05%3A18%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 05:21 UTC, angelgolfer-ms approved these changes
I made a couple more changes, please see my last [commit ](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11331/commits/0a4e7c181c2ba2559d47b7452a35d39810e27e27).

Next week as soon as you confirm that the API is available in v1 WW, please follow the process and set the PR to Ready to merge. Laura can then merge and publish the PR.

2021-02-09 02:29 UTC, Lauragra commented on api-reference/beta/api/attachment-get.md
> +* A file. Programmatically, this is a [fileAttachment](../resources/fileattachment.md) resource. See an [example](#example-1-get-the-properties-of-a-file-attachment) below.
Global: Please avoid using the term "below" to refer to something later in the current article. In line 22, you can be more specific and simply say "See example 1." In line 24, you can change the text to "See example 5." Please remove all occurrences of below. For reference, see this guidance: https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/b/below.

2021-02-09 02:29 UTC, Lauragra commented on api-reference/beta/api/attachment-get.md
> +| **contact** | [vCard](http://www.faqs.org/rfcs/rfc2426.html) MIME format. See [example](#example-7-get-the-mime-raw-contents-of-a-contact-attachment-on-a-message). |
It will help to guide the reader and also help non-sighted readers if you include the example number in the link text. Otherwise there are many links on the page with the same generic link title "example".

2021-02-09 07:21 UTC, opbld34 commented
Docs Build status updates of commit _[eb6402a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb6402a83af62dbf0bc30ca57828628ec3591156)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090720260122-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aVjWu5e2H9M1G4t0Di2jbgyU%2BorAVtN2nqRuHwJKizw%3D&st=2021-02-09T07%3A16%3A30Z&se=2021-03-12T07%3A21%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 08:06 UTC, opbld31 commented
Docs Build status updates of commit _[8ff5502](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ff5502fa6ce5c64127a28ea24a8eb68b2fb3450)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090805191430-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c1FKx%2F%2BvqgO5J4uu%2Bw463M7qkXBwPVYU5Pko3ogRLTc%3D&st=2021-02-09T08%3A01%3A24Z&se=2021-03-12T08%3A06%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 08:13 UTC, opbld30 commented
Docs Build status updates of commit _[ea025a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea025a9f675c86a063565c8b370d44ad17941996)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090811568782-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GDmXyGOZw4DUyGYXBAR0melEhayougMmF0yoKxGhbRE%3D&st=2021-02-09T08%3A08%3A00Z&se=2021-03-12T08%3A13%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 08:13 UTC, abheek-das commented on api-reference/beta/api/attachment-get.md
> +* A file. Programmatically, this is a [fileAttachment](../resources/fileattachment.md) resource. See an [example](#example-1-get-the-properties-of-a-file-attachment) below.
@Lauragra Removed all occurrences of below in the context of meaning later from the article in both beta & v1.0 version of the article.

2021-02-09 08:15 UTC, abheek-das commented on api-reference/beta/api/attachment-get.md
> +| **contact** | [vCard](http://www.faqs.org/rfcs/rfc2426.html) MIME format. See [example](#example-7-get-the-mime-raw-contents-of-a-contact-attachment-on-a-message). |
Add the example number explicitly in all links as suggested.

2021-02-09 08:15 UTC, opbld32 commented
Docs Build status updates of commit _[1d4e2d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d4e2d92b3fc36a3f7131c530192cd44b90d5a3a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090812213993-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uOQxuW29SwZlyJKhFWrQyN%2B0Sl9mkMwvE%2Fn5ZOAyT6c%3D&st=2021-02-09T08%3A10%3A04Z&se=2021-03-12T08%3A15%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 19:58 UTC, opbld30 commented
Docs Build status updates of commit _[ad237ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad237ee391b4f8aa10395aceaec060c4ba725de4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102091956462643-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kDVCohS7SbP3C25koObC4uTB8xJg9RAhDkq%2F0990Ou8%3D&st=2021-02-09T19%3A53%3A44Z&se=2021-03-12T19%3A58%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 03:06 UTC, Lauragra approved these changes

2021-02-10 04:25 UTC, opbld30 commented
Docs Build status updates of commit _[c55e4f3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c55e4f38fdf458e9b42085b73591c309414f2811)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/beta/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-beta&branch=pr-en-us-11331) (graph-rest-beta) |
[api-reference/v1.0/api/attachment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/api-reference/v1.0/api/attachment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/attachment-get?view=graph-rest-1.0&branch=pr-en-us-11331) (>= graph-rest-1.0) |
[concepts/outlook-large-attachments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/abheek-das-nested-attachments/concepts/outlook-large-attachments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/outlook-large-attachments?branch=pr-en-us-11331) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102100306379592-11331%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ox75ol15IlhVZv7cXiHCn31FTRVgKb39KkWkfTXvlCU%3D&st=2021-02-10T04%3A20%3A47Z&se=2021-03-13T04%3A25%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 04:28 UTC, merged