Pr/9423
microsoftgraph/microsoft-graph-docs pull request #11343
Opened 2021-01-19 19:31 UTC by hamiltonha

2021-01-19 19:31 UTC, opbld34 commented
Docs Build status updates of commit _[638a083](https://github.com/hamiltonha/microsoft-graph-docs/commits/638a0839c5abca52795d88fd58e6695a8b2b890d)_: 

:clock10: **Pending**: waiting for processors ([33](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 33 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-01-19 19:32 UTC, opbld33 commented
Docs Build status updates of commit _[638a083](https://github.com/hamiltonha/microsoft-graph-docs/commits/638a0839c5abca52795d88fd58e6695a8b2b890d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8fe1ae4f)

<a id="8fe1ae4f"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101191931525119-11343%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eH46T6eKWa5gma8ir3Us5tR7Yj1kUtTTTqgi2wJ8%2BjM%3D&st=2021-01-19T19%3A27%3A17Z&se=2021-02-19T19%3A32%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 19:49 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-06-24 14:35 UTC, isvargasmsft commented on api-reference/v1.0/api/application-update.md
> +| spa                     | [spaApplication](../resources/spaapplication.md)                                         | Specifies settings for a single-page application. `spa` type redirect URIs notif
Is this addition for beta or both beta and v1? If the addition applies to both, please include the changes in beta as well.

2021-06-24 14:37 UTC, isvargasmsft commented on api-reference/v1.0/resources/spaapplication.md
> +description: "Specifies settings for a spa application."
The description in line 3 should match the one in line 14. In this case, I'd appreciate if you use "single-page application" in both lines.

2021-06-24 14:47 UTC, isvargasmsft commented on changelog/Microsoft.DirectoryServices.json
> +          "Target": "updateApplication"
Please see the guidelines here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelist-record-properties

ChangedApiName should be spaApplication. 
Description: Added the [spaApplication] (please check the typo in the link: "spa**apl**ication") resource type.
Target: spaApplication.

Typo in link: there is a 'p' missing.

2021-06-24 14:54 UTC, isvargasmsft commented on api-reference/v1.0/resources/application.md
> +| spa |[spaApplication](spaapplication.md)| Specifies settings for a single-page application. `spa` type redirect URIs notify the server to enable CORS and use the authorization code flow. |
In beta, the description is: "Specifies settings for a single-page application, including sign out URLs and redirect URIs for authorization codes and access tokens."

Can we use this description for consistency?

2021-06-24 14:57 UTC, isvargasmsft requested changes
Hello @hamiltonha, 

I noticed the changes you propose in this PR are already live in both beta and v1. 

Could you please confirm? If so, may I close this PR?

Kind regards, 

Isaac Vargas

2021-06-29 20:30 UTC, isvargasmsft commented
Author confirmed on the side that these changes are already live and this PR can be closed.

2021-06-29 20:30 UTC, closed without merging