Doc updates for My Access - new PR incorporating all feedback from previous reviews
microsoftgraph/microsoft-graph-docs pull request #11361
Opened 2021-01-21 00:39 UTC by sbounouh

2021-01-21 00:40 UTC, opbld34 commented
Docs Build status updates of commit _[6829fc8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6829fc8e916efe0af4077e03c382e66e7a8ec4b9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ba1d05b8)

<a id="ba1d05b8"></a>
###
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101210039272451-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tlNoH%2BGfrmChhNZfhhUC6SgWSW8jrtjWGvgnovMeuMw%3D&st=2021-01-21T00%3A35%3A00Z&se=2021-02-21T00%3A40%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-21 00:51 UTC, opbld30 commented
Docs Build status updates of commit _[1cf2eaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1cf2eaaa803628ae6ef0278f519fe55f7df9acb0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-195db9ab)

<a id="195db9ab"></a>
###
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````
 - **Line 0, Column 0**: **[Error-git-clone-failed]** `````Failure to clone the repository `https://github.com/Microsoft/templates.docs.msft#master`. This could be caused by an incorrect repository URL, please verify the URL on the Docs Portal (https://ops.microsoft.com). This could also be caused by not having the proper permission the repository, please confirm that the GitHub group/team that triggered the build has access to the repository.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101210051153695-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Oa%2BVAbZWY%2BCPYTYgEW728kTQh4Cv7vhD7p%2FJDUd0%2B3Y%3D&st=2021-01-21T00%3A46%3A44Z&se=2021-02-21T00%3A51%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 22:49 UTC, opbld33 commented
Docs Build status updates of commit _[297e95e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/297e95e04445a43ee7847c80ae352f569f8dedf5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-18201d60)

<a id="18201d60"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101262248416168-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U%2FiesEinGfT1NmTl2wtwUDq93M0ZddsqbPkCTjMTI7I%3D&st=2021-01-26T22%3A44%3A01Z&se=2021-02-26T22%3A49%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-26 22:54 UTC, opbld31 commented
Docs Build status updates of commit _[598a2b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/598a2b991e6d1632b95f317a35307a075a679795)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-00685cff-e04c0e0a)
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-3954429f-e04c0e0a)
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-0e8b8866-e04c0e0a)
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

<a id="00685cff-e04c0e0a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml)
 - **Line 10956, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 10956, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 10957, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 10957, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 10980, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 10980, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'name' is already defined, remove the duplicate key.`````
 - **Line 10981, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 10981, Column 15**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="3954429f-e04c0e0a"></a>
### [api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'accessPackageAssignmentRequest: FilterByCurrentUser' is duplicated with other articles: 'beta/api/accesspackageassignmentrequest-filterbycurrentuser.md(10,1), beta/api/accesspackage-filterbycurrentuser.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0e8b8866-e04c0e0a"></a>
### [api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'accessPackageAssignmentRequest: FilterByCurrentUser' is duplicated with other articles: 'beta/api/accesspackageassignmentrequest-filterbycurrentuser.md(10,1), beta/api/accesspackage-filterbycurrentuser.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C26%5 [...]

2021-01-27 00:57 UTC, opbld30 commented
Docs Build status updates of commit _[848b94b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/848b94b0fe0825db46de126243cd20951ac8cc51)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101270056281089-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HP3sribHM946uL6KghTdyCAePdxVJD91UOendnn3Z6M%3D&st=2021-01-27T00%3A52%3A55Z&se=2021-02-27T00%3A57%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 01:04 UTC, opbld33 commented
Docs Build status updates of commit _[0437862](https://github.com/microsoftgraph/microsoft-graph-docs/commits/043786246dbb8077101278896e36938f35f98e71)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101270102538251-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NEKkCABPBZsWFgZRMCew93OVabZSloUjEwJcSaMhzFc%3D&st=2021-01-27T00%3A59%3A14Z&se=2021-02-27T01%3A04%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 18:11 UTC, opbld32 commented
Docs Build status updates of commit _[c31bc3b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c31bc3b0d88e509cad52b9424a643b15f86fe5ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101281809351684-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KFp%2BSE%2BG2o6ijC1cwoOkLNPp%2FDqavihzrEnjIME4lTk%3D&st=2021-01-28T18%3A06%3A38Z&se=2021-02-28T18%3A11%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 19:01 UTC, Lauragra commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +
Global: All beta topics need to include the beta disclaimer includes file link; this should be placed on a new line following the namespace line. Please add that to all new beta files.

2021-01-29 04:33 UTC, Lauragra commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +title: "accessPackage: FilterByCurrentUser"
Please verify the method name - generally, in Graph we use lower camel case, so this should be filterByCurrentUser (lowercase f).

2021-01-29 04:33 UTC, opbld34 commented
Docs Build status updates of commit _[b41e755](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b41e7551b4b731fd200e0eeec39802473bdb62b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290431447644-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=92GnfhSI7pqgD7fw%2BvznUgRMYXRsNYlDVfAOwm2DmpE%3D&st=2021-01-29T04%3A28%3A49Z&se=2021-03-01T04%3A33%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:33 UTC, Lauragra commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +title: "accessPackageAssignment: FilterByCurrentUser"
Same comment here - verify that this should be a lowercase f.

2021-01-29 04:36 UTC, opbld33 commented
Docs Build status updates of commit _[7da220e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7da220e87e908bdcc844b1e4b52ec9adddd8b0d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290435307205-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=k4OOh1bwMxWfN5f8SMjPET6pSt0VrQ4J5Sc74C1ivp0%3D&st=2021-01-29T04%3A31%3A45Z&se=2021-03-01T04%3A36%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:37 UTC, Lauragra commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +#### Request
FYI - I fixed this while making edits to the topic. When we have one example in the Examples section, we don't add an H3 with a title for the example, the Request and Response subheadings can be H3s. We add H3s with unique titles when we include multiple examples that show different scenarios.

2021-01-29 04:38 UTC, opbld31 commented
Docs Build status updates of commit _[c7b7327](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c7b73278dfe358585ebaba8b9eab144be7ff7756)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290435556462-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tnUo%2BinG8yWcwZpax9%2FWX5RxPjKcPM3df7vy5J55N0k%3D&st=2021-01-29T04%3A33%3A01Z&se=2021-03-01T04%3A38%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:38 UTC, Lauragra commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +title: "accessPackageAssignmentRequest: Cancel"
Please make Cancel lowercase here to be consistent with the H1 title.

2021-01-29 04:39 UTC, Lauragra commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +title: "accessPackageAssignmentRequest: FilterByCurrentUser"
Same point here - likely should be lowercase f.

2021-01-29 04:40 UTC, opbld34 commented
Docs Build status updates of commit _[92ffe79](https://github.com/microsoftgraph/microsoft-graph-docs/commits/92ffe79de3df9cdf8c6cdd8fd6252a530e8d0429)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290438589850-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PFEwLOhHNUYaiDOE1eeWnNs4NAXonmuL994IC9uDNy0%3D&st=2021-01-29T04%3A35%3A20Z&se=2021-03-01T04%3A40%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:41 UTC, Lauragra commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to create their own assignment for (either *first assignment* or *renew* assignment), the value of the *requestType* property is `UserAdd`. The *accessPackageA
Global - please apply bold formatting instead of italics on property names.

2021-01-29 04:41 UTC, opbld33 commented
Docs Build status updates of commit _[9551b90](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9551b9031a13f1843042c6981555bde415d4801e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.IGAELM.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.IGAELM.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290440407523-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sDtzG%2B8%2BbCi7NphGOqyQ0JcOSPOeYM7Ix5Apw1B%2B%2BG8%3D&st=2021-01-29T04%3A36%3A55Z&se=2021-03-01T04%3A41%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:42 UTC, Lauragra commented on api-reference/beta/resources/accesspackageassignment.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignm
Pls. also fix the casing in the Methods tables.

2021-01-29 04:45 UTC, Lauragra commented on changelog/Microsoft.IGAELM.json
> +{"changelog":[{
This doesn't look like the right JSON file to update - I think you want to add a changelist item to the DirectoryServices.json file in the changelog folder. Please follow the same formatting used for the other entries when you add your ChangeList item there.

2021-01-29 04:46 UTC, Lauragra commented on api-reference/beta/toc.yml
> +            - name: FilterbyCurrentUser
Please use "friendly" TOC entries - i.e. Filter by current user.

2021-01-29 04:46 UTC, Lauragra requested changes
Please take a look at the comments and make the updates and this should be good to go!

2021-02-01 17:57 UTC, sbounouh commented on api-reference/beta/toc.yml
> +            - name: FilterbyCurrentUser
done

2021-02-01 18:05 UTC, sbounouh commented on changelog/Microsoft.IGAELM.json
> +{"changelog":[{
done

2021-02-01 18:07 UTC, sbounouh commented on api-reference/beta/resources/accesspackageassignment.md
> +|[FilterByCurrentUser](../api/accesspackageassignment-filterbycurrentuser.md)|[accessPackageAssignment](../resources/accesspackageassignment.md) collection|Retrieve the list of **accessPackageAssignm
done

2021-02-01 18:11 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to create their own assignment for (either *first assignment* or *renew* assignment), the value of the *requestType* property is `UserAdd`. The *accessPackageA
done

2021-02-01 18:11 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +title: "accessPackageAssignmentRequest: FilterByCurrentUser"
done

2021-02-01 18:14 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +title: "accessPackageAssignmentRequest: Cancel"
done

2021-02-01 18:15 UTC, sbounouh commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +title: "accessPackage: FilterByCurrentUser"
done

2021-02-01 18:15 UTC, sbounouh commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +title: "accessPackageAssignment: FilterByCurrentUser"
done

2021-02-01 19:13 UTC, opbld31 commented
Docs Build status updates of commit _[d50c9e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d50c9e3c1d1840e860e016f155a3c6483b2237c6)_: 

:clock10: **Pending**: waiting for processors ([38](https://ops.microsoft.com/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 38 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://ops.microsoft.com/#/statistic).

2021-02-01 19:16 UTC, opbld31 commented
Docs Build status updates of commit _[d50c9e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d50c9e3c1d1840e860e016f155a3c6483b2237c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102011913282501-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uq6EHMXCCInEdZlixPlCDNn3uCUVWB5dYoEcYiJkuek%3D&st=2021-02-01T19%3A11%3A34Z&se=2021-03-04T19%3A16%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 19:17 UTC, sbounouh reviewed
merged

2021-02-04 19:03 UTC, davidmu1 commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +|on|String|The list of options that can be used to filter on current user. Possible option is: `allowedRequestor`. filterByCurrentUser|
```suggestion
|on|String|The values that can be used to filter on current user. Possible values: `allowedRequestor`. filterByCurrentUser|
```

2021-02-04 21:21 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +title: "accessPackageAssignment: s"
I think this should be: accessPackageAssignment: filterByCurrentUser

2021-02-04 21:22 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +## Query parameters
This should be: Function parameters

2021-02-04 21:22 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +The following table shows the parameters that can be used with this method.
```suggestion
The following table shows the parameters that can be used with the function.
```

2021-02-04 21:23 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +|on|String|The list of options that can be used to filter on current user. Possible options are: `target`, `createdBy`. Additional options may be available in the future.|
```suggestion
|on|String|The list of options that can be used to filter on current user. Possible values: `target`, `createdBy`.|
```

2021-02-04 21:24 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +- `target` is used to get the `accessPackageAssignment` objects where the signed-in user is the target. The resulting list includes all of the assignments, current and expired, that the caller has ac
```suggestion
- `target` is used to get the `accessPackageAssignment` objects where the signed-in user is the target. The resulting list includes all of the assignments, current and expired, for the caller across all catalogs and access packages.
```

2021-02-04 21:25 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +- `createdBy` is used to get the `accessPackageAssignment` objects created by the signed-in user. The resulting list includes all of the assignments that the caller has created for themselves or on b
```suggestion
- `createdBy` is used to get the `accessPackageAssignment` objects created by the signed-in user. The resulting list includes all of the assignments that the caller created for themselves or on behalf of others, such as in case of admin direct assignment, across all catalogs and access packages.
```

2021-02-04 21:27 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md
> +When a result set spans multiple pages, Microsoft Graph returns that page with an `@odata.nextLink` property in the response that contains a URL to the next page of results. If that property is prese
```suggestion
When a result set spans multiple pages, Microsoft Graph returns that page with an `@odata.nextLink` property in the response that contains a URL to the next page of results. If that property is present, continue making additional requests with the `@odata.nextLink` URL in each response, until all the results are returned. For more information, see [paging Microsoft Graph data in your app](/graph/paging.md).
```

2021-02-04 21:28 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignment-list.md
> +In [Azure AD entitlement management](../resources/entitlementmanagement-root.md), retrieve a list of [accessPackageAssignment](../resources/accesspackageassignment.md) objects. For directory-wide adm
To be consistent: Azure AD Entitlement Management

2021-02-04 21:31 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-cancel.md
> +For a non-administrator user to cancel their own request, the body must contain the request `id` and `requestStatus`. The value of the **requestStatus** property is `cancelled`. The `id` is the ident
```suggestion
For a non-administrator user to cancel their own request, the body must contain the request *id* and *requestStatus*. The value of *requestStatus* is `cancelled`. The *id* is the identifier of the [accessPackageAssignmentRequest](../resources/accesspackageassignmentrequest.md).
```

2021-02-04 21:40 UTC, davidmu1 commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +## Query parameters
Function parameters

2021-02-04 21:41 UTC, davidmu1 commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +The following table shows the parameters that can be used with this method.
```suggestion
The following table shows the parameters that can be used with the function.
```

2021-02-04 21:45 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +## Query parameters
Should be: Function parameters

2021-02-04 21:47 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +The following table shows the parameters that can be used with this method.
```suggestion
The following table shows the parameters that can be used with the function.
```

2021-02-04 21:47 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +|on|String|The list of options that can be used to filter on current user. Possible options are: `target`, `createdBy` and `approver`. Additional options may be available in the future.|
```suggestion
|on|String|The list of options that can be used to filter on current user. Possible values: `target`, `createdBy` , `approver`.|
```

2021-02-04 21:49 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +- `target` is used to get the `accessPackageAssignmentRequest` objects where the signed-in user is the target. The resulting list includes all the assignment requests, current and expired, that were
```suggestion
- `target` is used to get the `accessPackageAssignmentRequest` objects where the signed-in user is the target. The resulting list includes all of the assignment requests, current and expired, that were requested by the caller or for the caller, across all catalogs and access packages.
```

2021-02-04 21:50 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +- `createdBy` is used to get the `accessPackageAssignmentRequest` objects created by the signed-in user. The resulting list includes all the assignment requests that the caller has created for themse
```suggestion
- `createdBy` is used to get the `accessPackageAssignmentRequest` objects created by the signed-in user. The resulting list includes all of the assignment requests that the caller has created for themselves or on behalf of others , such as in case of admin direct assignment, across all catalogs and access packages.
```

2021-02-04 21:53 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md
> +- `approver` is used to get the `accessPackageAssignmentRequest` objects where the signed-in user is an allowed approver in any contained `accessPackageAssignment/accessPackageAssignmentPolicy/reques
```suggestion
- `approver` is used to get the `accessPackageAssignmentRequest` objects where the signed-in user is an allowed approver in any contained `accessPackageAssignment/accessPackageAssignmentPolicy/requestApprovalSettings/approvalStages` (`primaryApprovers` or `escalationApprovers`). The resulting list includes the assignment requests in *pending* state, across all catalogs and access packages and that need a decision from the caller. This list does not contain assignment requests in states other than `pending`. The list only contains assignment requests that require action from the the signed-in user.
```

2021-02-04 22:03 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +For a non-administrator user to request to create their own assignment for (either *first assignment* or *renew* assignment), the value of the **requestType** property is `UserAdd`. The **accessPacka
```suggestion
For a non-administrator user to request to create their own assignment for either a first assignment or renew assignment, the value of the **requestType** property is `UserAdd`. The **accessPackageAssignment** property contains the `targetId` with the `id` of the users. The **assignmentPolicyId** property identifies the [accessPackageAssignmentPolicy](../resources/accesspackageassignmentpolicy.md). The **accessPackageId** property identifies the [accessPackage](../resources/accesspackage.md). The user making the request must already exist in the directory.
```

2021-02-04 22:05 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +The following example shows how to request an access package and provide justification to the approver.
This should probably go between the previous headings.

2021-02-04 22:05 UTC, davidmu1 commented on api-reference/beta/api/accesspackageassignmentrequest-post.md
> +---
This line isn't needed.

2021-02-04 22:07 UTC, davidmu1 commented on api-reference/beta/resources/approval.md
> +|steps|[approvalStage](../resources/approvalstage.md) collection|Used for the *approvalStages* property of approval settings in the *requestApprovalSettings* property of an [access package assignment
```suggestion
|steps|[approvalStage](../resources/approvalstage.md) collection|Used for the **approvalStages** property of approval settings in the **requestApprovalSettings** property of an [access package assignment policy](accesspackageassignmentpolicy.md). Specifies the primary, fallback, and escalation approvers of each stage.|
```

2021-02-11 19:16 UTC, g2mula commented on changelog/Microsoft.DirectoryServices.json
> +    "ChangeList": [
These changes are from the `Microsoft.IGAELM` workload, should they be in this `Microsoft.DirectoryServices` changelog?

2021-02-11 19:22 UTC, markwahl-msft commented on changelog/Microsoft.DirectoryServices.json
> +    "ChangeList": [
Guidance from earlier comment was to use Microsoft.DirectoryServices.  IGAELM is an internal code name and not customer visible.

2021-03-12 18:37 UTC, opbld34 commented
Docs Build status updates of commit _[1da7ecd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1da7ecdf7a1261c8da97ce4f51224031a6cc8bbc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1aa88989)

<a id="1aa88989"></a>
###
 - **[Error-[CannotMergeCommit](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot merge commit 1da7ecdf7a1261c8da97ce4f51224031a6cc8bbc in branch sbounouh-myaccessapisdocs2 of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 2e2b44094f181d9e004581a4c2b01643b7881570). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103121836257189-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EW0KaOLqOmkSh4ZPVM%2FV5ei37%2BWqrekeqW5LnBSyN7k%3D&st=2021-03-12T18%3A31%3A35Z&se=2021-04-12T18%3A36%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 18:43 UTC, opbld31 commented
Docs Build status updates of commit _[1da7ecd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1da7ecdf7a1261c8da97ce4f51224031a6cc8bbc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5c81f83f)

<a id="5c81f83f"></a>
###
 - **[Error-[CannotMergeCommit](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot merge commit 1da7ecdf7a1261c8da97ce4f51224031a6cc8bbc in branch sbounouh-myaccessapisdocs2 of repository https://github.com/microsoftgraph/microsoft-graph-docs into branch main (commit 2e2b44094f181d9e004581a4c2b01643b7881570). Please follow this documentation: https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/ to use git.exe to resolve you content conflicts locally and then push to remote.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103121842479728-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g6Zyf4UiKUZBai%2FoaC0l%2Fv7iJzGg7GebFQISIDylgxs%3D&st=2021-03-12T18%3A37%3A57Z&se=2021-04-12T18%3A42%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 18:56 UTC, opbld31 commented
Docs Build status updates of commit _[4e47963](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e47963473dd456e3c222cdbeac123d31a36fd50)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-00685cff-82dee2f8)
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-82dee2f8"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml)
 - **Line 5774, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-raimportcerts-onpremencryptedpayload.md'.`````
 - **Line 5777, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-list.md'.`````
 - **Line 5779, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-get.md'.`````
 - **Line 5781, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-create.md'.`````
 - **Line 5783, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-delete.md'.`````
 - **Line 5785, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-update.md'.`````
 - **Line 5793, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-raimportcerts-pfxrecryptionrequest.md'.`````
 - **Line 5796, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-list.md'.`````
 - **Line 5798, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-get.md'.`````
 - **Line 5800, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-create.md'.`````
 - **Line 5802, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-delete.md'.`````
 - **Line 5804, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-update.md'.`````
 - **Line 5806, Column 19**: **[Warning-[file-not-found](https://review.docs.microsof [...]

2021-03-12 19:57 UTC, opbld31 commented
Docs Build status updates of commit _[d4f28fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4f28fada7db302f152ff407436a56c2acdb3d45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-00685cff-b920279b)
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-b920279b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml)
 - **Line 5774, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-raimportcerts-onpremencryptedpayload.md'.`````
 - **Line 5777, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-list.md'.`````
 - **Line 5779, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-get.md'.`````
 - **Line 5781, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-create.md'.`````
 - **Line 5783, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-delete.md'.`````
 - **Line 5785, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-update.md'.`````
 - **Line 5793, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-raimportcerts-pfxrecryptionrequest.md'.`````
 - **Line 5796, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-list.md'.`````
 - **Line 5798, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-get.md'.`````
 - **Line 5800, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-create.md'.`````
 - **Line 5802, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-delete.md'.`````
 - **Line 5804, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-pfxrecryptionrequest-update.md'.`````
 - **Line 5806, Column 19**: **[Warning-[file-not-found](https://review.docs.microsof [...]

2021-03-12 20:03 UTC, opbld33 commented
Docs Build status updates of commit _[d871d73](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d871d73b206b196c30f7ecc8232710cfeceab9a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-00685cff-6052fe6c)
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="00685cff-6052fe6c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml)
 - **Line 5774, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-raimportcerts-onpremencryptedpayload.md'.`````
 - **Line 5777, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-list.md'.`````
 - **Line 5779, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-get.md'.`````
 - **Line 5781, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-create.md'.`````
 - **Line 5783, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/intune-raimportcerts-onpremencryptedpayload-delete.md'.`````
 - **Line 5785, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid fil [...]

2021-03-26 19:38 UTC, lramosvea commented
I added the schema live label since I can see the accessPackageAssignmentRequests nav property in the live metadata for accessPackageAssignment. For the accesspackageassignmentrequest resource, I can see in the live metadata the accesspackage nav property but I don't see approval and see accessPackageAssignment instead.

2021-04-16 22:09 UTC, opbld32 commented
Docs Build status updates of commit _[7a9bc89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a9bc898d308ae4a9fde83e49d4566c5dba26cbe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104162208207748-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c57DZwETEDxdLMUyMUgRRZHFWEXYqZtCX5b6Hny6pxs%3D&st=2021-04-16T22%3A04%3A44Z&se=2021-05-17T22%3A09%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 22:49 UTC, opbld31 commented
Docs Build status updates of commit _[ea82c71](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea82c713708e1bb2b192261bb83edd09a8c9d151)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104162247437541-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ilJ%2Bsf1P9J%2B7rg%2FbsF8739X8cUATPkbqAA3Ov0OZmsU%3D&st=2021-04-16T22%3A44%3A01Z&se=2021-05-17T22%3A49%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 16:03 UTC, opbld32 commented
Docs Build status updates of commit _[502fd13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/502fd13278654a80868ec59b1fe1329dc673ba53)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104191602370410-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iU0iu%2Fx8h58TMi1IWquiTJZtKVYADq7IfixL55u9S%2Fk%3D&st=2021-04-19T15%3A58%3A51Z&se=2021-05-20T16%3A03%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 18:03 UTC, opbld33 commented
Docs Build status updates of commit _[7a18306](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7a18306d47af6c54aec9e1b530037b58595b6759)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104191802152698-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vr2XT%2F%2BI9AQYeZaYyujLznZSUkI7%2FwBuD7lszbe0Vb0%3D&st=2021-04-19T17%3A58%3A21Z&se=2021-05-20T18%3A03%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-19 23:00 UTC, opbld33 commented
Docs Build status updates of commit _[5c86ad4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c86ad4b4443067f32d41c9977138c3e956dd14a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104192259261158-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r%2Fw9b0dLEtRR1ozTRyV2Y%2BHwB44wgnxd5T6iwxWj%2BBE%3D&st=2021-04-19T22%3A55%3A40Z&se=2021-05-20T23%3A00%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-21 20:23 UTC, opbld33 commented
Docs Build status updates of commit _[a6b8a31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6b8a31e6bf35081c7d2549d94921b80de0140e3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104212022208116-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3iwG2ERooD%2FAkpVgdidSUmYvXGr9XrSOJaZCWi6EZIM%3D&st=2021-04-21T20%3A18%3A39Z&se=2021-05-22T20%3A23%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-23 14:44 UTC, opbld32 commented
Docs Build status updates of commit _[3576ab8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3576ab89125247e2267028fc221ec5df54c5f9a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104231443130045-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qfSgq%2FiLLRx0beEgcJFCjY3iqYck0NXxJx37EfHg8W0%3D&st=2021-04-23T14%3A39%3A21Z&se=2021-05-24T14%3A44%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 22:41 UTC, opbld30 commented
Docs Build status updates of commit _[140c19d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/140c19d9c48ffe497d60da51d044dbd5118af419)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104262239571243-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=l3pmazKIteyXHD3upG1qn4FpfMrJ4yWvZoqgdqYlSCM%3D&st=2021-04-26T22%3A36%3A26Z&se=2021-05-27T22%3A41%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-30 17:47 UTC, Lauragra commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +**Note:** The response object shown here might be shortened for readability.
Global: We had a bug in the tool and it didn't generate this note text correctly; we need to add the ">" so that it's formatted as a note.

2021-05-04 22:26 UTC, davidmu1 approved these changes

2021-05-07 22:02 UTC, opbld31 commented
Docs Build status updates of commit _[10267b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10267b1509eb998a6496d57097a9e9a14dc64bec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-512caa0a)
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-512caa0a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml)
 - **Line 11238, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105072200524220-11361%5Cworkflow_rep [...]

2021-05-07 22:11 UTC, markwahl-msft commented on api-reference/beta/api/accesspackage-filterbycurrentuser.md
> +**Note:** The response object shown here might be shortened for readability.
Added ">" to those access package API files which were missing it.

2021-05-08 02:01 UTC, opbld32 commented
Docs Build status updates of commit _[9ba9d87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ba9d879a09cec1d17663f01541c6592e5dea81e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accesspackage-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackage-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackage-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignment-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentpolicy-update?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-cancel.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-cancel?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageassignmentrequest-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageassignmentrequest-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignmentrequest-post?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageresourceenvironment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-get?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/api/accesspackageresourceenvironment-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/api/accesspackageresourceenvironment-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageresourceenvironment-list?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage-accesspackagefilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage-accesspackagefilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackage?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment-accesspackageassignmentfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignment?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest-accesspackageassignmentrequestfilterbycurrentuseroptions?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/accesspackageassignmentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/accesspackageassignmentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accesspackageassignmentrequest?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/resources/entitlementmanagement-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/resources/entitlementmanagement-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/entitlementmanagement-root?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-filterbycurrentuser?view=graph-rest-beta&branch=pr-en-us-11361) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/sbounouh-myaccessapisdocs2/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105080159503283-11361%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jnAX1GB20VF%2BbqyDhExQgeEyXy7DSmOlwcNQWKY%2BAqs%3D&st=2021-05-08T01%3A56%3A14Z&se=2021-06-08T02%3A01%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.micros [...]

2021-05-08 02:04 UTC, merged