Add permissions to site
microsoftgraph/microsoft-graph-docs pull request #11427
Opened 2021-01-27 02:31 UTC by BarryShehadeh

2021-01-27 02:32 UTC, opbld33 commented
Docs Build status updates of commit _[d6c037c](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/d6c037c3973e8898e33f248bce6e3c97ecd37545)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-9eb0a4c3)
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |

<a id="52f341fc-9eb0a4c3"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101270231098189-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uFje3DtJUQ8U%2BZ6Bl86CeYZIvAZYyzYnURe%2FEghLMBU%3D&st=2021-01-27T02%3A27%3A49Z&se=2021-02-27T02%3A32%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 20:48 UTC, opbld33 commented
Docs Build status updates of commit _[04ae487](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/04ae4875b5b3425f365c932bd62a42447d7c7df2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-cad244ab)
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-cad244ab"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101292046583305-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=21%2FfH%2FyBzj59pET5TuL1u2%2BbUxfj9EUBZAB%2Fx57Nalk%3D&st=2021-01-29T20%3A43%3A21Z&se=2021-03-01T20%3A48%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 20:56 UTC, opbld31 commented
Docs Build status updates of commit _[7d5f189](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/7d5f1890e722a1023921297ca28606d123b4b99e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-44f1241b)
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-44f1241b"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101292054313683-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FNFAea%2FBgH7TaCoZ%2BzEDlW%2Fa7De1%2FcGccbhjheuKK9Y%3D&st=2021-01-29T20%3A50%3A59Z&se=2021-03-01T20%3A55%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[c03f239](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/c03f2395e680580ebd263ba865602c4d8c1729b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-c37c699e)
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-c37c699e"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101292057584837-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Lb0eQY6IdMOlEaqqLbRIPAHT7Lo3uaRrmJODJ0t7ItM%3D&st=2021-01-29T20%3A54%3A15Z&se=2021-03-01T20%3A59%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 00:09 UTC, opbld34 commented
Docs Build status updates of commit _[62b5cd2](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/62b5cd2cb0793f675b145c3462c6b8e36eb10bce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-86880f7d)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-86880f7d"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102020008258482-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eT3MpssLjjOa9yW1BvjKvBSQXmb222Jp8Dsxc%2B6PE0E%3D&st=2021-02-02T00%3A04%3A40Z&se=2021-03-05T00%3A09%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 00:16 UTC, opbld34 commented
Docs Build status updates of commit _[8ffcd01](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/8ffcd01a32c527aee39b204d4db03df90c6477d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-699f760e)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-699f760e"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102020014376093-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BeJDkPn4YB%2FD%2F21gx3R62CBuUc8JKqrwkhqNqz%2FNK6M%3D&st=2021-02-02T00%3A10%3A59Z&se=2021-03-05T00%3A15%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 00:24 UTC, JeremyKelley requested changes
Not sure if there's a Vroom -> Graph discrepancy but at least on the direct endpoint there are two changes needed.  In the POST method grantedTo should be grantedToIdentities and it should take an array rather than a single object.

2021-02-03 20:59 UTC, opbld30 commented
Docs Build status updates of commit _[700bc67](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/700bc67946face74b9320b92c445cbe5b588db5b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-5bb81459)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-5bb81459"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032058408909-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SYOJo6aSriRP%2FCWXi3iuDcorzBqylpke8ovfCVs2W5E%3D&st=2021-02-03T20%3A54%3A57Z&se=2021-03-06T20%3A59%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:07 UTC, JeremyKelley approved these changes

2021-02-06 03:03 UTC, opbld33 commented
Docs Build status updates of commit _[94a8a91](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/94a8a91b481ae1aa33b5065279d56c369a1fdfc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-02ae8588)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-02ae8588"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060302223099-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=knhOJP%2FHEFmevVBVBUS6Hs2PW%2FzJSIVCPxVNeeffnhA%3D&st=2021-02-06T02%3A58%3A35Z&se=2021-03-09T03%3A03%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[e9626f0](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/e9626f065946a1eddb4ab1d4c948bc23b10e9894)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-d21d7654)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-d21d7654"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060303323769-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KbTulTYHZgwEb5bx8dcqcY2KcG9wyAwtaDWMLTk9OVo%3D&st=2021-02-06T02%3A59%3A47Z&se=2021-03-09T03%3A04%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:06 UTC, opbld30 commented
Docs Build status updates of commit _[b5d556a](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/b5d556ac0d7ce95e3b2c40f897a7429ef45e14f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-0472901f)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-0472901f"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060304185755-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AZvZwei58ho1BncIC%2Fwtr1OOBQEqvieAYj%2BClwLarsQ%3D&st=2021-02-06T03%3A01%3A02Z&se=2021-03-09T03%3A06%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:07 UTC, opbld34 commented
Docs Build status updates of commit _[3876266](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/3876266515dff1f082437f59775edb7267adc572)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-e860b4c3)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-e860b4c3"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060305454965-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4to16NqkXM5aHuTpQ8CToQPQEORIByJd1A2JBTuywcA%3D&st=2021-02-06T03%3A02%3A16Z&se=2021-03-09T03%3A07%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:08 UTC, opbld34 commented
Docs Build status updates of commit _[ea3e42e](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/ea3e42e5445fd96ded311d19de92fa2d7fe8943e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-81efe7f9)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-81efe7f9"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060306174016-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Zsi71VrhY0L%2BxlS9fnJr%2BeiWQlfxmbXPO0Aw7yWmym0%3D&st=2021-02-06T03%3A03%3A33Z&se=2021-03-09T03%3A08%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:09 UTC, opbld33 commented
Docs Build status updates of commit _[b8a1e9f](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/b8a1e9fcfa9258e966c78ce4df5e5b9eb936d4bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-9e92921b)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-9e92921b"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102060307427807-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eCSCbnaPlhBR%2FiRMmp%2F7wluYx%2FzHNJoDkjcjQOeVxps%3D&st=2021-02-06T03%3A04%3A56Z&se=2021-03-09T03%3A09%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-06 03:27 UTC, Lauragra commented on api-reference/beta/api/site-delete-permission.md
> +Delete a permission object on a site.
Global: In the summary statements where you mention permission object, please also link to the permission resource topic.

2021-02-06 03:29 UTC, Lauragra commented on changelog/Microsoft.FileServices.json
> +      "WorkloadArea": "Files",
The WorkloadArea here should be "Sites and lists" - confirm?

2021-02-06 03:30 UTC, Lauragra requested changes
Please add TOC entry points for the new operation topics.

2021-02-08 18:51 UTC, opbld31 commented
Docs Build status updates of commit _[abb0735](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/abb07358613bf1726744f54a899cef0d0b00f7fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-52bdbf58)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-52bdbf58"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081849134609-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ACKZiI1EIpbw4c3Ahf59XoKl06OarpO7Cg3TZ9M%2FijM%3D&st=2021-02-08T18%3A46%3A28Z&se=2021-03-11T18%3A51%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[9d311ba](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/9d311ba12e61040a8d443897205bc5c29e297583)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-e882d948)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-e882d948"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081852095431-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UgHL%2FoXeSsQQ16e5rtX9YuCSTqyZCKJYyNw3p0YuV7M%3D&st=2021-02-08T18%3A48%3A29Z&se=2021-03-11T18%3A53%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 18:54 UTC, BarryShehadeh commented on changelog/Microsoft.FileServices.json
> +      "WorkloadArea": "Files",
Correct.

2021-02-08 20:08 UTC, opbld33 commented
Docs Build status updates of commit _[967e2f6](https://github.com/BarryShehadeh/microsoft-graph-docs/commits/967e2f69c603988a80808166e1956d4300bcb236)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) | [Details](#user-content-52f341fc-7877c032)
[api-reference/beta/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-beta&branch=pr-en-us-11427) (graph-rest-beta) |
[api-reference/v1.0/api/site-delete-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-delete-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-get-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-get-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-get-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-list-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-list-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-post-permissions.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-post-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-permissions?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/api/site-update-permission.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/api/site-update-permission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-update-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-delete-permission?view=graph-rest-1.0&branch=pr-en-us-11427) (>= graph-rest-1.0) |
[changelog/Microsoft.FileServices.json](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="52f341fc-7877c032"></a>
### [api-reference/v1.0/resources/site.md](https://github.com/BarryShehadeh/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/site.md)
 - **Line 3, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'JeremyKelley' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102082006396386-11427%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fPHXm1TZ9vlrjs65GMeTWKULMss0BreqxXjF5zK0X0Q%3D&st=2021-02-08T20%3A03%3A06Z&se=2021-03-11T20%3A08%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 02:11 UTC, Lauragra approved these changes

2021-02-09 02:20 UTC, merged