Update app permission for get printer endpoint
microsoftgraph/microsoft-graph-docs pull request #11435
Opened 2021-01-27 17:45 UTC by jahsu-MSFT

2021-01-27 17:46 UTC, opbld31 commented
Docs Build status updates of commit _[f1f0a8a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f1f0a8a7857cb9244cf9b18be8e7648c6cc3cfda)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11435) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101271745306552-11435%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uKlHk6NkOiOwJ%2B2kDWKMcTOWPKllxE0svqoFuYwTAEI%3D&st=2021-01-27T17%3A41%3A40Z&se=2021-02-27T17%3A46%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 18:05 UTC, nilakhan requested changes

2021-01-27 18:05 UTC, nilakhan commented on api-reference/beta/api/printer-get.md
Also, in printdocument-get-file.md
We need to add this: 
"In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription and have a permission that grants [Get printer](printer-get.md) access."

By replacing this: 
In addition to the following permissions, the user or app's tenant must have an active Universal Print subscription and have a permission that grants [Get printer](printer-get.md) access in case of user's access tokens and either the Printer.Read.All or Printer.ReadWrite.All application permission in case of app-only access tokens.

2021-01-27 18:13 UTC, opbld30 commented
Docs Build status updates of commit _[c243d95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c243d9597a5d9ecc7910fc7b3110be6b6823eefa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11435) (graph-rest-beta) |
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11435) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101271811424217-11435%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bY0c4BsX3Z0hGt5YVehC7vfYvn5WuTTKCaq3EX8KN48%3D&st=2021-01-27T18%3A08%3A12Z&se=2021-02-27T18%3A13%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 23:24 UTC, nilakhan approved these changes

2021-01-27 23:40 UTC, opbld34 commented
Docs Build status updates of commit _[9f3668b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f3668bc78636390d4c9fc08e7a139daecf6285c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/api-reference/beta/api/printdocument-get-file.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-beta&branch=pr-en-us-11435) (graph-rest-beta) |
[api-reference/beta/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/api-reference/beta/api/printer-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-get?view=graph-rest-beta&branch=pr-en-us-11435) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/update-get-printer-permission/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101272337409975-11435%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gBeGlqpLyUfkJ8fZTVw5o6KI6JGE2AlPApJxkK8ZIYw%3D&st=2021-01-27T23%3A35%3A07Z&se=2021-02-27T23%3A40%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-28 02:21 UTC, Lauragra approved these changes

2021-01-28 02:22 UTC, merged