AndresC-AuthMethodsPolicy-SMS
microsoftgraph/microsoft-graph-docs pull request #11445
Opened 2021-01-28 07:27 UTC by andres-canello

2021-01-28 07:28 UTC, opbld34 commented
Docs Build status updates of commit _[cad555e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cad555ec9c3f2431db629e6a4b2551cfd3bdf4ca)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) | [Details](#user-content-721ddcea-bef5e03b)
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) | [Details](#user-content-11041a8f-bef5e03b)
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |

<a id="721ddcea-bef5e03b"></a>
### [api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A collection of users or groups enabled to use Text Message authentication methods policy.' is duplicated in 'beta/resources/smsauthenticationmethodconfiguration.md(3,14)', 'beta/resources/smsauthenticationmethodtarget.md(3,14)'.`````

<a id="11041a8f-bef5e03b"></a>
### [api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A collection of users or groups enabled to use Text Message authentication methods policy.' is duplicated in 'beta/resources/smsauthenticationmethodconfiguration.md(3,14)', 'beta/resources/smsauthenticationmethodtarget.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101280727056029-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kcTZDZG3uj1NC69k4OXqoBtMOKs09M27R2fGF1jDytY%3D&st=2021-01-28T07%3A23%3A35Z&se=2021-02-28T07%3A28%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:44 UTC, opbld33 commented
Docs Build status updates of commit _[a98ec2c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a98ec2c34f8823a1c66980044cb53e5e1300cbdc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290443167996-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cKnwrM2%2BWlmTDQxJ3lhUTqthlPiQv5GTI2J%2FC5CqUz4%3D&st=2021-01-29T04%3A39%3A29Z&se=2021-03-01T04%3A44%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 04:48 UTC, opbld33 commented
Docs Build status updates of commit _[83b2eea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83b2eea465cd861942779c96a1d78cf48b12e017)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290447341476-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zIfvOd4AcQ1YeZffXhn8D6nHM8aNItk5jxlwM4efYBY%3D&st=2021-01-29T04%3A43%3A56Z&se=2021-03-01T04%3A48%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 05:06 UTC, opbld30 commented
Docs Build status updates of commit _[8c8c7e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8c8c7e884cdc11fa82c96e8f18ff1b7ce575e796)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290505260229-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CvcGW6Qc3DXhi9rID9MyFE%2BALO0P1phXjiHt6WBNnVY%3D&st=2021-01-29T05%3A01%3A41Z&se=2021-03-01T05%3A06%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-29 05:38 UTC, opbld32 commented
Docs Build status updates of commit _[2256c54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2256c548834783e7f7900cc770f1994fdbaa0d57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202101290537356720-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hbt6d%2Bumj5CQ6fDwfZIpqaa5xVV8wSiPtBADRYYdDs4%3D&st=2021-01-29T05%3A33%3A49Z&se=2021-03-01T05%3A38%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:59 UTC, mmcla approved these changes

2021-02-04 02:08 UTC, opbld32 commented
Docs Build status updates of commit _[15110e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/15110e9dbd97827a01f6341023d4caa05d8a0924)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11445) | [Details](#user-content-075040e5-8c0637ad)
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="075040e5-8c0637ad"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md)
 - **Line 348, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 437, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102040207178490-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4FOxuRPoxxBoTEEgR4sc%2FU7cQ8hUq9gmPK8RzrgUGcg%3D&st=2021-02-04T02%3A03%3A32Z&se=2021-03-07T02%3A08%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 22:17 UTC, davidmu1 commented on api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
> +  "@odata.type": "#microsoft.graph.smsAuthenticationMethodConfiguration",
These should be realistic looking values.

2021-02-04 22:19 UTC, davidmu1 commented on api-reference/beta/resources/smsauthenticationmethodtarget.md
> +|isRegistrationRequired|Boolean|Determines whether the user is enforced to register the authentication method. *Not supported*.|
```suggestion
|isRegistrationRequired|Boolean|Determines whether the user is enforced to register the authentication method. **Not supported**.|
```

2021-02-04 22:20 UTC, davidmu1 commented on api-reference/beta/resources/smsauthenticationmethodtarget.md
> +|isUsableForSignIn|Boolean|Determines if the users or groups can use this authentication method to sign in to Azure AD. *Must always be True*|
```suggestion
|isUsableForSignIn|Boolean|Determines if the users or groups can use this authentication method to sign in to Azure AD. The value is always `true`.|
```

2021-02-04 22:21 UTC, davidmu1 approved these changes

2021-02-11 01:54 UTC, andres-canello commented on api-reference/beta/api/smsauthenticationmethodconfiguration-update.md
> +  "@odata.type": "#microsoft.graph.smsAuthenticationMethodConfiguration",
Done

2021-02-11 01:56 UTC, andres-canello commented on api-reference/beta/resources/smsauthenticationmethodtarget.md
> +|isUsableForSignIn|Boolean|Determines if the users or groups can use this authentication method to sign in to Azure AD. *Must always be True*|
done

2021-02-11 01:56 UTC, andres-canello commented on api-reference/beta/resources/smsauthenticationmethodtarget.md
> +|isRegistrationRequired|Boolean|Determines whether the user is enforced to register the authentication method. *Not supported*.|
done

2021-02-11 01:58 UTC, opbld31 commented
Docs Build status updates of commit _[bbe6391](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbe63916f7acaae1a5358f1404581a63d669d2cf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-94158d53)

<a id="94158d53"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110158111873-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w%2BdAmty%2FpbIFblGR6xod8mBKQV5i06rVmTg3u6LeVqU%3D&st=2021-02-11T01%3A53%3A32Z&se=2021-03-14T01%3A58%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 02:03 UTC, opbld34 commented
Docs Build status updates of commit _[3353a89](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3353a8965a6d2c30a616fc57ba8f707ba172e819)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11445) | [Details](#user-content-075040e5-da78ec98)
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |

<a id="075040e5-da78ec98"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md)
 - **Line 348, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 437, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110201362069-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cqeClXsvGuMVkAa47LnIoAjkhcUirYjawR0k4L4f7PM%3D&st=2021-02-11T01%3A58%3A04Z&se=2021-03-14T02%3A03%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 02:06 UTC, opbld30 commented
Docs Build status updates of commit _[bca932d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bca932d2adaa5c2a6e7c0ff65df8051611c0bf8c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11445) | [Details](#user-content-075040e5-bc49d3aa)
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |

<a id="075040e5-bc49d3aa"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md)
 - **Line 348, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 437, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110205073696-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a8aL%2BqDiqLM09Wky6aQQ1i%2Bfc%2FYplUfjigsaqZj9J0k%3D&st=2021-02-11T02%3A01%3A09Z&se=2021-03-14T02%3A06%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 02:09 UTC, opbld30 commented
Docs Build status updates of commit _[f99fb8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f99fb8bebc2e94df92bb3678f1437bef3d8f8586)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11445) | [Details](#user-content-075040e5-2199f2ec)
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="075040e5-2199f2ec"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md)
 - **Line 348, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 437, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110208523375-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X%2Bawx9uRd6giKMGKR1i6xvl7foMHxgTI60SaUJzqG3M%3D&st=2021-02-11T02%3A04%3A57Z&se=2021-03-14T02%3A09%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 03:14 UTC, Lauragra requested changes
Please add the new methods to the beta TOC file. Thanks!

2021-02-11 03:31 UTC, opbld34 commented
Docs Build status updates of commit _[cd146ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd146ec71a80b4716155f3feb4fcf1010305150d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/permissions-reference?branch=pr-en-us-11445) | [Details](#user-content-075040e5-2119bdd6)
[api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-get?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/api/smsauthenticationmethodconfiguration-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/api/smsauthenticationmethodconfiguration-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-update?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/authenticationmethodspolicies-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/authenticationmethodspolicies-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/authenticationmethodspolicies-overview?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodconfiguration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodconfiguration?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/resources/smsauthenticationmethodtarget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/resources/smsauthenticationmethodtarget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/smsauthenticationmethodtarget?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/smsauthenticationmethodconfiguration-delete?view=graph-rest-beta&branch=pr-en-us-11445) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="075040e5-2119bdd6"></a>
### [concepts/permissions-reference.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/AndresC-AuthMethodsPolicy-SMS/concepts/permissions-reference.md)
 - **Line 348, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````
 - **Line 437, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Channel permissions''. Each second level heading (H2) in an article must be unique.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110330109362-11445%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=brwsEEsYStDuJWftjC%2FFRZrUBIZH71EpXe9BmEJDYmM%3D&st=2021-02-11T03%3A26%3A23Z&se=2021-03-14T03%3A31%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 03:32 UTC, andres-canello commented
> Please add the new methods to the beta TOC file. Thanks!

Thanks for catching that @Lauragra , done. Andres

2021-02-11 19:09 UTC, Lauragra approved these changes

2021-02-11 19:09 UTC, merged