Support policy-based app token scenarios in v1.0
microsoftgraph/microsoft-graph-docs pull request #11492
Opened 2021-02-02 06:22 UTC by frankpeng7

Pushing #9726 to v1.0

@Lauragra since this one does not include any CSDL changes, please let me know if changelog update is still needed and if so which changelog (md/json) should be updated

2021-02-02 06:24 UTC, opbld34 commented
Docs Build status updates of commit _[789790a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/789790a23358b2326567a611896be1f3b4cce956)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102020622509356-11492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XJT2SFjFGmufhHw6yIh%2BAExagzy%2BzVVByAm0tEkcQWc%3D&st=2021-02-02T06%3A19%3A07Z&se=2021-03-05T06%3A24%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 06:43 UTC, opbld34 commented
Docs Build status updates of commit _[16a34b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16a34b2d02915be86ad08651e4ee711921b38131)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102020641507174-11492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=40T2Fh%2FJFlT7GpUQXX49KPqhvxgiNFoN%2BYrL%2FYJfIAc%3D&st=2021-02-02T06%3A37%3A59Z&se=2021-03-05T06%3A42%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-02 06:52 UTC, opbld30 commented
Docs Build status updates of commit _[12117d9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/12117d925e9de5ace94879a7c01791fb67c2ffc3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) |
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102020651231218-11492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n54tlbNqUs65iWLM4wU270S%2BlBEWElsaxlAjffoTd8c%3D&st=2021-02-02T06%3A47%3A32Z&se=2021-03-05T06%3A52%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 10:34 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-get.md
> +You can retrieve meeting information via meeting ID with either a user or application token. The meeting ID is provided in the response object when creating an [onlineMeeting](../resources/onlinemeet
Line 224:
Please rephrase for proper branding, punctuation, grammar, and Microsoft Voice:
"...created using Graph API first then user/app retrieves meeting information..."
As:
"...created using the Microsoft Graph API first, then the user or app gets meeting information..."

In case you wonder about Microsoft Voice, it's the guideline about using conversational language in docs that I am applying. More info here:  https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25356

2021-02-11 10:45 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-get.md
> +GET https://graph.microsoft.com/beta/me/onlineMeetings/MSpkYzE3Njc0Yy04MWQ5LTRhZGItYmZiMi04ZjZhNDQyZTQ2MjIqMCoqMTk6bWVldGluZ19NelEyTURrNU9EY3RNakJsTWkwME5ESTRMV0poTWpZdFpHRTNaR1F6WTJRd056QTBAdGhyZWFk
Lines 231 nd 237:
FYI in general, for readability/ scannability of examples in the docs, we truncate long resource IDs.

2021-02-11 10:48 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-get.md
> +You can retrieve meeting information via meeting ID with either a user or application token. The meeting ID is provided in the response object when creating an [onlineMeeting](../resources/onlinemeet
Line 186:
Please see my comment in the beta topic.

2021-02-11 10:50 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-get.md
> +GET https://graph.microsoft.com/beta/me/onlineMeetings/MSpkYzE3Njc0Yy04MWQ5LTRhZGItYmZiMi04ZjZhNDQyZTQ2MjIqMCoqMTk6bWVldGluZ19NelEyTURrNU9EY3RNakJsTWkwME5ESTRMV0poTWpZdFpHRTNaR1F6WTJRd056QTBAdGhyZWFk
Lines 193, 199, 208:
Please truncate long IDs (while still keeping them consistent within the example), for readability and scannability of examples.

2021-02-11 10:59 UTC, angelgolfer-ms requested changes
Hi @frankpeng7 , that's an overall good quality PR! Please see my comments and let me know if you have any questions :-)
BTW I removed the Ready to merge label. FYI, in general, authors set that label only after content review is complete and, the PR is ready for publishing, to make sure the docs sync with any API release.

2021-02-11 11:05 UTC, angelgolfer-ms commented
> Hi @frankpeng7 , that's an overall good quality PR! Please see my comments and let me know if you have any questions :-)
> BTW I removed the Ready to merge label. FYI, in general, authors set that label only after content review is complete and, the PR is ready for publishing, to make sure the docs sync with any API release.

Regarding the changelog - you do need a changelog item since you're enabling policy-based application permissions in v1.
@paulodero , @brianbusolo , we discussed this a week ago - how should our partners specify the changlog JSON for permissions-related updates? What should they assign ApiChange and Target as in the ChangeList item?

2021-02-12 18:36 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +You can retrieve meeting information via meeting ID with either a user or application token. The meeting ID is provided in the response object when creating an [onlineMeeting](../resources/onlinemeet
> Is there a reason you changed to use the passive voice and adds "using Graph API"?

Changing it to passive voice is not intentional - I can change it back. 
For adding the sentence - Yes, since if the meeting has been created via Outlook/Teams client or Graph Calendar Event API, the user won't have the meeting ID

2021-02-12 18:54 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +GET https://graph.microsoft.com/beta/me/onlineMeetings/MSpkYzE3Njc0Yy04MWQ5LTRhZGItYmZiMi04ZjZhNDQyZTQ2MjIqMCoqMTk6bWVldGluZ19NelEyTURrNU9EY3RNakJsTWkwME5ESTRMV0poTWpZdFpHRTNaR1F6WTJRd056QTBAdGhyZWFk
We recently changed the format of the meeting ID so was updating them in doc/examples to reflect that. Is there a good way to truncate the long ID?

2021-02-17 18:24 UTC, opbld30 commented
Docs Build status updates of commit _[ed8f9b9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ed8f9b91289b432aae0dbce0d27ef13d0a287ea7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-98057f49-7fb48db6)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-4e311bd1-7fb48db6)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-81d219b4-7fb48db6)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-c3251e69-7fb48db6)
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-6d3f843f-7fb48db6)
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-f368bbe5-7fb48db6)
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-688e5765-7fb48db6)
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="98057f49-7fb48db6"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4e311bd1-7fb48db6"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="81d219b4-7fb48db6"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c3251e69-7fb48db6"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6d3f843f-7fb48db6"></a>
### [api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f368bbe5-7fb48db6"></a>
### [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="688e5765-7fb48db6"></a>
### [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171822501550-11492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hFKTovsdxrxupKNYJIneQHhwTIoT0rcdroFQn3gspeA%3D&st=2021-02-17T18%3A19%3A15Z&se=2021-03-20T18%3A24%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validat [...]

2021-02-17 20:51 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-get.md
>  | Delegated (work or school account)     | Not Supported.                                        |
@frankpeng7 , if we have line 31 (syntax to show using delegated token), then line 23 shouldn't be "Not supported"?

2021-02-17 22:23 UTC, frankpeng7 commented on api-reference/v1.0/api/onlinemeeting-get.md
>  | Delegated (work or school account)     | Not Supported.                                        |
Updated in new revision

2021-02-17 22:25 UTC, opbld32 commented
Docs Build status updates of commit _[eb4ee67](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb4ee67f6344a9b2d1f6c07002110fc1207fcd95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-98057f49-24142663)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-4e311bd1-24142663)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-81d219b4-24142663)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-c3251e69-24142663)
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-6d3f843f-24142663)
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-f368bbe5-24142663)
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-688e5765-24142663)
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="98057f49-24142663"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4e311bd1-24142663"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="81d219b4-24142663"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c3251e69-24142663"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6d3f843f-24142663"></a>
### [api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f368bbe5-24142663"></a>
### [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="688e5765-24142663"></a>
### [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172223596138-11492%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AfLGDnuA%2B0%2FKteCF91tqpqoU43sCFiuFt4lIIn%2BuWJE%3D&st=2021-02-17T22%3A20%3A10Z&se=2021-03-20T22%3A25%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-v [...]

2021-02-17 22:38 UTC, angelgolfer-ms requested changes

2021-02-17 22:38 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
>    "changelog": [
In reviewing the actual descriptions for the changelog, I took a look at the perms for the API set in the published topics and got 2 new questions (sorry didn't occur to me to look at that last time):

- In the beta version of "create onlineMeeting" (application-post-onlinemeetings.md), the "Application" row of the permissions table includes OnlineMeetings.Read.All. That seems inappropriate for a create operation; should we delete that from that table row?

- Should we update the v1 version of application-post-onlinemeetings.md as well, in this PR?

2021-02-17 22:38 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
> +      "ChangeList": [
For the changelog items, aren't the changes in this PR mainly to support OnlineMeetings.Read.All and OnlineMeetings.ReadWrite.All as policy-based application permissions for the few applicable operations in v1?

v1 already supports OnlineMeetings.Read and OnlineMeetings.ReadWrite in the published docs.

I'd suggest the following, for each of the two OnlineMeetings.Read.All and OnlineMeetings.ReadWrite.All permissions:

Line 8: ChangedApiName is OnlineMeetings.Read.All
Line 10: Description is something like "Added support for the policy-based application permission of OnlineMeetings.Read.All to the read operations of the onlineMeeting resource."

Line 16: ChangedApiName is OnlineMeetings.ReadWrite.All
Line 18: Description is something like "Added support for the policy-based application permission of OnlineMeetings.ReadWrite.All to the read and write operations of the onlineMeeting resource."

Technically, permissions are relevant at the method level. IMHO depending on the API set, it may not be precise or very helpful to generalize such and such resource supports this permission.

2021-02-17 22:52 UTC, angelgolfer-ms reviewed
One more comment, @frankpeng7 , that applies to all the onlineMeeting API topics: Can you please work with your feature crew (PMs, devs) to identify the GitHub name that should now be in the author field of these topics?
You noticed some of the topics have an empty author field. Other topics like onlinemeeting.md still have ananmishr.
Generally the recommendation is one Github name for the entire set of reference topics for the feature or API. That person would get email notifications of any Github issues customers open. Github issues are primarily for doc-related issues. That person can then reassign to appropriate folks on the team, or address the issues directly. We can talk more about this offline.

2021-02-18 00:17 UTC, frankpeng7 commented on changelog/Microsoft.Skype.Calling.json
>    "changelog": [
This is a good point. I never discovered that before and yea I think we should remove that

2021-02-18 00:42 UTC, frankpeng7 commented on changelog/Microsoft.Skype.Calling.json
> +      "ChangeList": [
Thanks for the advice. Updated in next revision.

2021-02-18 00:48 UTC, opbld30 commented
Docs Build status updates of commit _[0d07dc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d07dc67347bb238d3227d54b7c99d48cbe89099)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-fb5dd14f-e8311150)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-98057f49-e8311150)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-4e311bd1-e8311150)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-81d219b4-e8311150)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-c3251e69-e8311150)
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-9d47e387-e8311150)
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-6d3f843f-e8311150)
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-f368bbe5-e8311150)
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-688e5765-e8311150)
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="fb5dd14f-e8311150"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="98057f49-e8311150"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4e311bd1-e8311150"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="81d219b4-e8311150"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c3251e69-e8311150"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="9d47e387-e8311150"></a>
### [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6d3f843f-e8311150"></a>
### [api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f368bbe5-e8311150"></a>
### [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="688e5765-e8311150"></a>
### [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/poli [...]

2021-02-18 04:04 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added support for the policy-based application permission of **OnlineMeetings.Read.All** to the read o and write perations of the [onlineMeeting](https://docs.microsoft.com/
Oh, line 18 should say OnlineMeeting.ReadWrite.All. There's also a typo.
I'll update this line and approve this PR.

2021-02-18 04:07 UTC, opbld30 commented
Docs Build status updates of commit _[9d6422b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d6422b3928a0d6824adc2252fcb236ef099ad45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-fb5dd14f-2576a6e9)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-98057f49-2576a6e9)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-4e311bd1-2576a6e9)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-81d219b4-2576a6e9)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-c3251e69-2576a6e9)
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-9d47e387-2576a6e9)
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-6d3f843f-2576a6e9)
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-f368bbe5-2576a6e9)
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-688e5765-2576a6e9)
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="fb5dd14f-2576a6e9"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="98057f49-2576a6e9"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4e311bd1-2576a6e9"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="81d219b4-2576a6e9"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c3251e69-2576a6e9"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="9d47e387-2576a6e9"></a>
### [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6d3f843f-2576a6e9"></a>
### [api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f368bbe5-2576a6e9"></a>
### [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="688e5765-2576a6e9"></a>
### [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/poli [...]

2021-02-18 04:08 UTC, opbld31 commented
Docs Build status updates of commit _[75c89fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/75c89fa8014e0525621f65c7808f7eb2a947eec8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-fb5dd14f-ed25ad3e)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-98057f49-ed25ad3e)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-4e311bd1-ed25ad3e)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-81d219b4-ed25ad3e)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11492) (graph-rest-beta) | [Details](#user-content-c3251e69-ed25ad3e)
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-9d47e387-ed25ad3e)
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-6d3f843f-ed25ad3e)
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-f368bbe5-ed25ad3e)
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11492) (>= graph-rest-1.0) | [Details](#user-content-688e5765-ed25ad3e)
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="fb5dd14f-ed25ad3e"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="98057f49-ed25ad3e"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4e311bd1-ed25ad3e"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="81d219b4-ed25ad3e"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="c3251e69-ed25ad3e"></a>
### [api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/beta/api/onlinemeeting-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="9d47e387-ed25ad3e"></a>
### [api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="6d3f843f-ed25ad3e"></a>
### [api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f368bbe5-ed25ad3e"></a>
### [api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/policy-based-app-token-v1/api-reference/v1.0/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="688e5765-ed25ad3e"></a>
### [api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/poli [...]

2021-02-18 04:09 UTC, angelgolfer-ms commented
> One more comment, @frankpeng7 , that applies to all the onlineMeeting API topics: Can you please work with your feature crew (PMs, devs) to identify the GitHub name that should now be in the author field of these topics?
> You noticed some of the topics have an empty author field. Other topics like onlinemeeting.md still have ananmishr.
> Generally the recommendation is one Github name for the entire set of reference topics for the feature or API. That person would get email notifications of any Github issues customers open. Github issues are primarily for doc-related issues. That person can then reassign to appropriate folks on the team, or address the issues directly. We can talk more about this offline.

Ok, per our offline chat, please work with your feature crew, identify a contact person, and update this set of API files with the GitHub name of that person. It would be good if you guys can settle and update asap, otherwise meanwhile when customers open GitHub issues, the issues likely get ignored.

2021-02-18 04:10 UTC, merged