GA chatMessageHostedContent for channel chatMessage
microsoftgraph/microsoft-graph-docs pull request #11508
Opened 2021-02-03 00:12 UTC by satadrubiswasmsft

GA chatMessageHostedContent for channel chatMessage

2021-02-03 00:13 UTC, opbld34 commented
Docs Build status updates of commit _[33481e9](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/33481e928c75047dda1bf5c390135107e911b42e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md) | :x:Error | | [Details](#user-content-58f4f6dc-8bc81fff)
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :x:Error | | [Details](#user-content-f27d1b72-8bc81fff)
[api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md) | :warning:Warning | | [Details](#user-content-3a23dc44-8bc81fff)

<a id="58f4f6dc-8bc81fff"></a>
### [api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md)
 - **Line 73, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-hostedcontents-csharp-snippets.md'.`````
 - **Line 77, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-hostedcontents-javascript-snippets.md'.`````
 - **Line 81, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-hostedcontents-objc-snippets.md'.`````
 - **Line 85, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-hostedcontents-java-snippets.md'.`````
 - **Line 14, Column 22**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/chatmessagehostedcontent.md'.`````
 - **Line 55, Column 81**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/chatmessagehostedcontent.md'.`````

<a id="f27d1b72-8bc81fff"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md'.`````
 - **Line 128, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md'.`````
 - **Line 14, Column 46**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/chatmessagehostedcontent.md'.`````
 - **Line 55, Column 79**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/chatmessagehostedcontent.md'.`````

<a id="3a23dc44-8bc81fff"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md)
 - **Line 15, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'chatmessageattachment.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102030012547962-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DSPVFAGroWizLb71B1S8%2BRrHBktUVXEd%2B%2F383LrYJ7s%3D&st=2021-02-03T00%3A08%3A53Z&se=2021-03-06T00%3A13%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href=" [...]

2021-02-03 19:51 UTC, opbld30 commented
Docs Build status updates of commit _[08f6a25](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/08f6a25dd73c1a5024bf17c929dc6e7fd6f7060f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :x:Error | | [Details](#user-content-f27d1b72-6c38d8fd)
[api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md) | :warning:Warning | | [Details](#user-content-3a23dc44-6c38d8fd)
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :bulb:Suggestion | | [Details](#user-content-0d646d63-6c38d8fd)

<a id="f27d1b72-6c38d8fd"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md'.`````
 - **Line 128, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md'.`````

<a id="3a23dc44-6c38d8fd"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md)
 - **Line 15, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'chatmessageattachment.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'chatMessageHostedContent resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/chatmessagehostedcontent.md(2,8), v1.0/resources/chatmessagehostedcontent.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A content hosted in a chat message' is duplicated in 'v1.0/api/chatmessagehostedcontent.md(3,14)', 'v1.0/resources/chatmessagehostedcontent.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'chatMessageHostedContent resource type' is duplicated with other articles: 'v1.0/api/chatmessagehostedcontent.md(10,1), v1.0/resources/chatmessagehostedcontent.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0d646d63-6c38d8fd"></a>
### [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'chatMessageHostedContent resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/chatmessagehostedcontent.md(2,8), v1.0/resources/chatmessagehostedcontent.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A content hosted in a chat message' is duplicated in 'v1.0/api/chatmessagehostedcontent.md(3,14)', 'v1.0/resources/chatmessagehostedcontent.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'chatMessageHostedContent resource type' is duplicated with other articles: 'v1.0/api/chatmessagehostedcontent.md(10,1), v1.0/resources/chatmessagehostedcontent.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102031950314069-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UQHI4OqdUpXztXm7RvmR%2Bc8DOWn%2B2p1VAKrqQNNuoaM%3D&st=2021-02-03T19%3A46%3A27Z&se=2021-03-06T19%3A51%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to [...]

2021-02-03 19:55 UTC, opbld30 commented
Docs Build status updates of commit _[ea7d784](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/ea7d7841328d0709624d2a0948f27290486d3094)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :x:Error | | [Details](#user-content-f27d1b72-233985f9)
[api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md) | :warning:Warning | | [Details](#user-content-3a23dc44-233985f9)
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :bulb:Suggestion | | [Details](#user-content-0d646d63-233985f9)

<a id="f27d1b72-233985f9"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md'.`````
 - **Line 128, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md'.`````
 - **Line 132, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md'.`````
 - **Line 136, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md'.`````
 - **Line 140, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md'.`````

<a id="3a23dc44-233985f9"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md)
 - **Line 15, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'chatmessageattachment.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'chatMessageHostedContent resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/chatmessagehostedcontent.md(2,8), v1.0/resources/chatmessagehostedcontent.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A content hosted in a chat message' is duplicated in 'v1.0/api/chatmessagehostedcontent.md(3,14)', 'v1.0/resources/chatmessagehostedcontent.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'chatMessageHostedContent resource type' is duplicated with other articles: 'v1.0/api/chatmessagehostedcontent.md(10,1), v1.0/resources/chatmessagehostedcontent.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0d646d63-233985f9"></a>
### [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'chatMessageHostedContent resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/chatmessagehostedcontent.md(2,8), v1.0/resources/chatmessagehostedcontent.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A content hosted in a chat message' is duplicated in 'v1.0/api/chatmessagehostedcontent.md(3,14)', 'v1.0/resources/chatmessagehostedcontent.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'chatMessageHostedContent resource type' is duplicated with other articles: 'v1.0/api/chatmessagehostedcontent.md(10,1), v1.0/resources/chatmessagehostedcontent.md(10,1)'. First level headings must be unique within a docset.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102031954172887-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=STSGJpxkVgqKVQ5YX7PiwJRroegRBGJ3AB%2FcvdCZioM%3D&st=2021-02-03T19%3A50%3A16Z&se=2021-03-06T19%3A55%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-t [...]

2021-02-03 20:04 UTC, opbld31 commented
Docs Build status updates of commit _[6d8a325](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/6d8a325ad442ba937b8d26de2e8ba36eb55ab149)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-3a23dc44-e634ed1f)
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-0d646d63-e634ed1f)
[api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |

<a id="3a23dc44-e634ed1f"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent.md)
 - **Line 15, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'chatmessageattachment.md'.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'chatMessageHostedContent resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/chatmessagehostedcontent.md(2,8), v1.0/resources/chatmessagehostedcontent.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'A content hosted in a chat message' is duplicated in 'v1.0/api/chatmessagehostedcontent.md(3,14)', 'v1.0/resources/chatmessagehostedcontent.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'chatMessageHostedContent resource type' is duplicated with other articles: 'v1.0/api/chatmessagehostedcontent.md(10,1), v1.0/resources/chatmessagehostedcontent.md(10,1)'. First level headings must be unique within a docset.`````

<a id="0d646d63-e634ed1f"></a>
### [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'chatMessageHostedContent resource type - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/chatmessagehostedcontent.md(2,8), v1.0/resources/chatmessagehostedcontent.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with  [...]

2021-02-03 20:09 UTC, opbld31 commented
Docs Build status updates of commit _[55d1429](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/55d142957256d7f4e39f0c9a40e0b22368e45797)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032007557281-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C%2FcZXVboLYtPUMCMgIPW9vYu6UWmmzY3eqZUH%2FssrPQ%3D&st=2021-02-03T20%3A04%3A09Z&se=2021-03-06T20%3A09%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:18 UTC, Lauragra commented on api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md
> +title: "List chatMessageHostedContents"
The file name here should be chatmessage-list-hostedcontents, and the title field should be List hostedContents, to match the H1. Please fix this in the beta topic as well.

2021-02-03 21:20 UTC, Lauragra commented on api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md
> +# [HTTP](#tab/http)
Global: Please delete all the H1s here and the include links to the snippets (line 63 and lines 73-88). Those will get added via the weekly automation when this PR is merged into master.

2021-02-03 21:21 UTC, Lauragra commented on api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
Global: Please remove the snippet files; these will be added via automation.

2021-02-03 21:23 UTC, opbld33 commented
Docs Build status updates of commit _[ae2d2f3](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/ae2d2f38600cac39140db7731a7a00c12500387b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032122347269-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WPQO9yy2IYRpMGsYfUgEXOcWpMCuKt7%2Fr9u%2BH7prCxs%3D&st=2021-02-03T21%3A18%3A48Z&se=2021-03-06T21%3A23%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:24 UTC, Lauragra requested changes
Please see comments and include an update to the changelog JSON file with this PR.

2021-02-03 21:25 UTC, opbld33 commented
Docs Build status updates of commit _[4d1d5a9](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/4d1d5a9ef7bf06d58c795e784c128bb205c2a7de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-chatmessagehostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032124313189-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lviRqB%2BaAON4Z9yMZUXv%2BP9wGiI8LVkVhMn1%2BMVVyo4%3D&st=2021-02-03T21%3A20%3A47Z&se=2021-03-06T21%3A25%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 23:50 UTC, satadrubiswasmsft commented on api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md
> +title: "List chatMessageHostedContents"
> The file name here should be chatmessage-list-hostedcontents, and the title field should be List hostedContents, to match the H1. Please fix this in the beta topic as well.

@Lauragra  should the name be `chatmessage-list-hostedcontents` (suggested by you) OR `chatmessage-list-chatmessagehostedcontents` (the actual filename)?

2021-02-04 00:02 UTC, satadrubiswasmsft commented on api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md
> +title: "List chatMessageHostedContents"
Ignore my comment. I see what you mean

2021-02-04 00:05 UTC, opbld33 commented
Docs Build status updates of commit _[73c6966](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/73c6966eb0ad94ab57d3f72b21c34bc459b305ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-0d646d63-d2e5ce8c)
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-00685cff-d2e5ce8c)
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-afc44d33-d2e5ce8c)
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-97ee62ac-d2e5ce8c)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/csharp/get-hostedcontents-csharp-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-chatmessagehostedcontent-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/java/get-hostedcontents-java-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-chatmessagehostedcontent-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/javascript/get-hostedcontents-javascript-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-chatmessagehostedcontent-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/includes/snippets/objc/get-hostedcontents-objc-snippets.md) | :white_check_mark:Succeeded | |

<a id="0d646d63-d2e5ce8c"></a>
### [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md)
 - **Line 22, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-list-chatmessagehostedcontents.md'.`````

<a id="00685cff-d2e5ce8c"></a>
### [api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml)
 - **Line 12821, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-list-chatmessagehostedcontents.md'.`````

<a id="afc44d33-d2e5ce8c"></a>
### [api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md)
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-list-chatmessagehostedcontents.md'.`````

<a id="97ee62ac-d2e5ce8c"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md)
 - **Line 44, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-list-chatmessagehostedcontents.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102040004345277-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=F3hp2Dr82rkxqQSZZOsIBRfWf%2FagLwir0IxEVFOtzcM%3D&st=2021-02-04T00%3A00%3A56Z&se=2021-03-07T00%3A05%3A56Z&sp=r).

If you see build warnings/errors with permission issues,  [...]

2021-02-04 00:08 UTC, satadrubiswasmsft commented on api-reference/v1.0/api/chatmessage-list-chatmessagehostedcontents.md
> +title: "List chatMessageHostedContents"
fixed

2021-02-04 00:08 UTC, satadrubiswasmsft commented on api-reference/v1.0/includes/snippets/csharp/get-chatmessagehostedcontent-csharp-snippets.md
> +description: "Automatically generated file. DO NOT MODIFY"
fixed

2021-02-04 00:08 UTC, opbld33 commented
Docs Build status updates of commit _[cb6cfe2](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/cb6cfe253f6467af6d5be32c3c1c15f8620c124a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-0d646d63-54001834)
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-00685cff-54001834)
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-afc44d33-54001834)
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-97ee62ac-54001834)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |

<a id="0d646d63-54001834"></a>
### [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md)
 - **Line 22, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-list-chatmessagehostedcontents.md'.`````

<a id="00685cff-54001834"></a>
### [api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml)
 - **Line 12821, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-list-chatmessagehostedcontents.md'.`````

<a id="afc44d33-54001834"></a>
### [api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md)
 - **Line 24, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-list-chatmessagehostedcontents.md'.`````

<a id="97ee62ac-54001834"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md)
 - **Line 44, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/chatmessage-list-chatmessagehostedcontents.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102040007047464-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BdozKxEMMPClvLHPSV0b82jMK1fancQYTdBe2ZYqH7w%3D&st=2021-02-04T00%3A03%3A24Z&se=2021-03-07T00%3A08%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 18:41 UTC, opbld30 commented
Docs Build status updates of commit _[5e2ffda](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/5e2ffdaa62a01e98e78ab1e1966cd05f886d119b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-00685cff-64f4c6c8)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |

<a id="00685cff-64f4c6c8"></a>
### [api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml)
 - **Line 12821, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-list-chatmessagehostedcontents.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041840282180-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7PjLxqM%2FndEkxwEu709nHI%2BVCBGBB37mJMEHvDz%2BSZs%3D&st=2021-02-04T18%3A36%3A35Z&se=2021-03-07T18%3A41%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 19:26 UTC, satadrubiswasmsft commented
> Please see comments and include an update to the changelog JSON file with this PR.

@Lauragra Should the `changelog/Microsoft.Teams.Core.json` updated by hand? Or is there a script that will append the changes to it?

2021-02-04 19:34 UTC, opbld34 commented
Docs Build status updates of commit _[50192dd](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/50192dd63cc07feff44334c9574bbc83005890a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-00685cff-0b4006f6)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="00685cff-0b4006f6"></a>
### [api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml)
 - **Line 12821, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-list-chatmessagehostedcontents.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041933232162-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2anYutO8Ihjnyyqv7USi4CiaDn8iicFxO5n6r99BUjA%3D&st=2021-02-04T19%3A29%3A31Z&se=2021-03-07T19%3A34%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 02:06 UTC, opbld31 commented
Docs Build status updates of commit _[2e0459d](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/2e0459ddb9bc1e043fab2a6bd6f3ad64febc35a2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-00685cff-aee1aa53)
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="00685cff-aee1aa53"></a>
### [api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml)
 - **Line 12830, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/chatmessage-list-chatmessagehostedcontents.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090205021861-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1QsnJGTog0JZ3RPA7LtP5uNYxQVd74WVTRS%2B3u%2Bq148%3D&st=2021-02-09T02%3A01%3A25Z&se=2021-03-12T02%3A06%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 02:07 UTC, Lauragra requested changes
Please surface these APIs in the TOC. It looks like they are not exposed in the beta TOC and need to be added to v1.0 as well.

2021-02-09 23:11 UTC, satadrubiswasmsft commented
> Please surface these APIs in the TOC. It looks like they are not exposed in the beta TOC and need to be added to v1.0 as well.

Updated the TOC. The beta was updated but the file name was different. Fixed that

2021-02-09 23:11 UTC, opbld33 commented
Docs Build status updates of commit _[3a2efc7](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/3a2efc7f71bfb1fd59cd17a867e8fc078933a135)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102092310029439-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qAi59FWeXRgZEhDu49%2FEdtfe53GE%2BbrLGw0VuHQcjRc%3D&st=2021-02-09T23%3A06%3A54Z&se=2021-03-12T23%3A11%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 01:30 UTC, Lauragra approved these changes

2021-02-10 03:50 UTC, opbld30 commented
Docs Build status updates of commit _[cc8a5de](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/cc8a5de8db910f06a3b05109f74f036014b578bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102100129586340-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qENiAeg19RhLli55SANXtydkFLZMnjMvv9hsUF7xrw0%3D&st=2021-02-10T03%3A45%3A22Z&se=2021-03-13T03%3A50%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 04:06 UTC, AkJo commented on api-reference/beta/resources/chatmessagehostedcontent.md
> +| [List chatMessageHostedContent](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the list of **chatMessageHostedContent** for a messag
[chatMessageHostedContent](chatmessagehostedcontent.md) collection

2021-02-10 04:07 UTC, AkJo commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +GET /teams/{id}/channels/{id}/messages/{id}/hostedContents
/teams/{team-id}/channels/{channel-id}/messages/{message-id}/hostedContents

2021-02-10 04:08 UTC, AkJo commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +GET https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/messages/{id}/hostedContents
Please use illustrative values in examples.

Replace place holders with real values.

2021-02-10 04:08 UTC, AkJo commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +  "value": [
Same comment. Please provide a real response payload.

2021-02-10 04:09 UTC, AkJo commented on api-reference/v1.0/api/chatmessagehostedcontent-get.md
> +GET /teams/{id}/channels/{id}/messages/{id}/hostedContents/{id}
Same comment.

2021-02-10 04:09 UTC, AkJo commented on api-reference/v1.0/api/chatmessagehostedcontent-get.md
> +GET /teams/{id}/channels/{id}/messages/{id}/hostedContents/{id}
/teams/{team-id}/channels/{channel-id}/messages/{message-id}/hostedContents/{hosted-content-id}

2021-02-10 04:09 UTC, AkJo commented on api-reference/v1.0/api/chatmessagehostedcontent-get.md
> +GET https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/messages/{id}/hostedContents/{id}
Illustrative values.

2021-02-10 04:09 UTC, AkJo commented on api-reference/v1.0/api/chatmessagehostedcontent-get.md
> +GET https://graph.microsoft.com/v1.0/teams/{id}/channels/{id}/messages/{id}/hostedContents/{id}
Illustrative values.

2021-02-10 04:09 UTC, AkJo commented on api-reference/v1.0/api/chatmessagehostedcontent-get.md
> +  "id": "id-value"
Illustrative values.

2021-02-10 04:11 UTC, AkJo commented on api-reference/v1.0/resources/chatmessagehostedcontent.md
> +| [List chatMessageHostedContent](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the list of **chatMessageHostedContent** for a messag
collection

2021-02-10 04:12 UTC, AkJo commented on api-reference/v1.0/resources/chatmessagehostedcontent.md
> +| [List chatMessageHostedContent](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the list of **chatMessageHostedContent** for a messag
List hosted content

2021-02-10 04:12 UTC, AkJo commented on api-reference/v1.0/resources/chatmessagehostedcontent.md
> +| [List chatMessageHostedContent](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the list of **chatMessageHostedContent** for a messag
Please make this change in the beta doc as well.

2021-02-10 04:14 UTC, AkJo commented on api-reference/v1.0/resources/chatmessagehostedcontent.md
> +| [Get chatMessageHostedContent](../api/chatmessagehostedcontent-get.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Read the properties and relationships of a **chatMessageHostedCont
Get content hosted in chat message

Please make this change in beta documentation too.

2021-02-10 04:15 UTC, AkJo commented on api-reference/v1.0/resources/chatmessagehostedcontent.md
> +| @microsoft.graph.temporaryId      | string | Represents the temporaryId for the hosted content while posting a message to refer to the hosted content in **chatMessage** resource being sent. Write-o
Please add deeplink to chatMessage page.

2021-02-10 04:16 UTC, AkJo commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +title: "List hostedContents"
List content hosted in chat message

2021-02-10 04:16 UTC, AkJo commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +# List hostedContents
List content hosted in chat message

2021-02-10 04:17 UTC, AkJo commented on api-reference/beta/api/chatmessage-list-hostedcontents.md
> +title: "List hostedContents"
List content hosted inside chat message

2021-02-10 04:18 UTC, AkJo commented on api-reference/beta/api/chatmessage-list-hostedcontents.md
>  author: "clearab"
Please change this to "AkJo"

2021-02-12 21:30 UTC, satadrubiswasmsft commented on api-reference/beta/resources/chatmessagehostedcontent.md
> +| [List chatMessageHostedContent](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the list of **chatMessageHostedContent** for a messag
This is contradicting what @Lauragra had suggested

2021-02-15 19:29 UTC, satadrubiswasmsft commented on api-reference/beta/resources/chatmessagehostedcontent.md
> +| [List chatMessageHostedContent](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the list of **chatMessageHostedContent** for a messag
also the file name was changed to `chatmessage-list-hostedcontents.md`

2021-02-15 19:52 UTC, opbld34 commented
Docs Build status updates of commit _[19b1cba](https://github.com/satadrubiswasmsft/microsoft-graph-docs/commits/19b1cbaefe60372c10d5ceeebb48c308e7bbc547)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-fa943651-2119fea7)
[api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessage?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-97ee62ac-2119fea7)
[api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) | [Details](#user-content-afc44d33-2119fea7)
[api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-77f71d32-2119fea7)
[api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-f27d1b72-2119fea7)
[api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/chatmessagehostedcontent?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) | [Details](#user-content-0d646d63-2119fea7)
[api-reference/beta/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessage-list-hostedcontents?view=graph-rest-beta&branch=pr-en-us-11508) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chatmessagehostedcontent-get?view=graph-rest-1.0&branch=pr-en-us-11508) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="fa943651-2119fea7"></a>
### [api-reference/beta/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/api/chatmessage-list-hostedcontents.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="97ee62ac-2119fea7"></a>
### [api-reference/beta/resources/chatmessage.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessage.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="afc44d33-2119fea7"></a>
### [api-reference/beta/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/beta/resources/chatmessagehostedcontent.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="77f71d32-2119fea7"></a>
### [api-reference/v1.0/api/chatmessage-list-hostedcontents.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessage-list-hostedcontents.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="f27d1b72-2119fea7"></a>
### [api-reference/v1.0/api/chatmessagehostedcontent-get.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/api/chatmessagehostedcontent-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="0d646d63-2119fea7"></a>
### [api-reference/v1.0/resources/chatmessagehostedcontent.md](https://github.com/satadrubiswasmsft/microsoft-graph-docs/blob/sabiswa/wi-1507157/ga-read-hostedcontents/api-reference/v1.0/resources/chatmessagehostedcontent.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102151950447541-11508%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hYSxs7eqAis338LRnWH01%2B4snmJ5%2Bvl3hzRqToJCskA%3D&st=2021-02-15T19%3A47%3A06Z&se=2021-03-18T19%3A52%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or wa [...]

2021-05-04 19:49 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-06-01 15:58 UTC, lramosvea commented
@satadrubiswasmsft have all comments from the reviewers been addressed? If so, please add the "content review" label to this PR.

2021-08-18 02:03 UTC, Lauragra commented on api-reference/beta/api/chatmessage-list-hostedcontents.md
> +title: "List content hosted inside chat message"
This title should be List hostedContents; it should match the H1.

2021-08-18 02:03 UTC, Lauragra commented on api-reference/beta/resources/chatmessagehostedcontent.md
> +| [List content hosted in chat message](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the collection of **chatMessageHostedContent**
This should be List hostedContents.

2021-08-18 02:04 UTC, Lauragra commented on api-reference/beta/resources/chatmessagehostedcontent.md
> +| [Get content hosted in chat message](../api/chatmessagehostedcontent-get.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Read the properties and relationships of a **chatMessageHost
This should be Get chatMessageHostedContent.

2021-08-18 02:04 UTC, Lauragra commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +title: "List content hosted inside chat message"
Change the title and H1 to List hostedContents.

2021-08-18 02:06 UTC, Lauragra commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +> The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
Global: Please change the note formatting to >**Note:** and remove the second sentence from the boilerplate text.

2021-08-18 02:06 UTC, Lauragra commented on api-reference/v1.0/api/chatmessage-list-hostedcontents.md
> +| Authorization | Bearer {code} |
Please add Required to the description.

2021-08-18 02:07 UTC, Lauragra commented on api-reference/v1.0/resources/chatmessagehostedcontent.md
> +| [List content hosted in chat message](../api/chatmessage-list-hostedcontents.md) | [chatMessageHostedContent](chatmessagehostedcontent.md) | Retrieve the collection of **chatMessageHostedContent**
Please update the method names here per previous comments.

2022-01-08 02:15 UTC, closed without merging