Update usersettings.md
microsoftgraph/microsoft-graph-docs pull request #11518
Opened 2021-02-03 20:38 UTC by elmakhmu

add itemInsights as new relationship

2021-02-03 20:39 UTC, opbld34 commented
Docs Build status updates of commit _[5c46352](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c463528a34546c0dc3b70760437f4682ef6e0dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-3e047f90)

<a id="1ebb9a6c-3e047f90"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 58, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'userInsightsSettings.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032038451942-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RA6FBhvgWezuHe3QZdwpRouO5Z8St95BHcogGqQQ4%2Fo%3D&st=2021-02-03T20%3A34%3A52Z&se=2021-03-06T20%3A39%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:00 UTC, opbld31 commented
Docs Build status updates of commit _[94aa21e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94aa21e361ced7af16874b4741d3691fb12d5f59)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-5d22d87b)
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

<a id="57415194-5d22d87b"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 25, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userinsightssettings-get.md'.`````
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userinsightssettings-update.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032059050624-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VkOGBIf0co3YQfcxfVB37W%2BuiKcvoDVMSDCj7q1%2Bqvk%3D&st=2021-02-03T20%3A55%3A24Z&se=2021-03-06T21%3A00%3A24Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:08 UTC, opbld32 commented
Docs Build status updates of commit _[8ecc661](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8ecc66118cbd28e89846e2223719d368e56b950a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-e99038e0)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

<a id="57415194-e99038e0"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/userinsightssettings-update.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032107157554-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=COi5wGoqR56tk%2F8WTMDNev6oOck5%2FxDXkFgAPDeuxYc%3D&st=2021-02-03T21%3A03%3A36Z&se=2021-03-06T21%3A08%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-03 21:15 UTC, opbld34 commented
Docs Build status updates of commit _[348a54c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/348a54c173869c313fe853fdecb5c53fc2cd636e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102032114446543-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oyvuyTVMxrMMW35rwfUW9ga%2BUsGDbWPjs%2BaZVhAxBhU%3D&st=2021-02-03T21%3A10%3A54Z&se=2021-03-06T21%3A15%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 13:42 UTC, opbld32 commented
Docs Build status updates of commit _[53331e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53331e6efb14b2b54e743110d5ddef2ab4b533c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041340188585-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Oxop3r0euN7bO0z9Bu%2FSRPgsyF1mDEOg4D6eS6MXKlQ%3D&st=2021-02-04T13%3A37%3A06Z&se=2021-03-07T13%3A42%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 13:49 UTC, opbld33 commented
Docs Build status updates of commit _[727ae98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/727ae98c5ee1ee4bb85d06944a56e20f11424efc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041347403034-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YXBnqgbR9wfB6UnA9qA9yLfc4%2BryAMyRx7X4JnhkSfY%3D&st=2021-02-04T13%3A44%3A40Z&se=2021-03-07T13%3A49%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 13:54 UTC, opbld32 commented
Docs Build status updates of commit _[f38a8a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f38a8a75c780e0d9f715a606b3473483e672e846)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041352220091-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SImaeCoQ%2FPiNUPHdkHbPVFPD5oZptBooi9VoYmM3ReA%3D&st=2021-02-04T13%3A49%3A20Z&se=2021-03-07T13%3A54%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 14:04 UTC, opbld33 commented
Docs Build status updates of commit _[7fad422](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fad4220599ee93394f7619b55628ea495ea5b38)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-c3bf1680)

<a id="4922f918-c3bf1680"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041402406515-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dC036r4owCLTptZzLzGpmk3nf1Psn0bsf182F4XDpGo%3D&st=2021-02-04T13%3A59%3A33Z&se=2021-03-07T14%3A04%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 14:05 UTC, opbld33 commented
Docs Build status updates of commit _[5b8f473](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b8f4733bba94b47eb3f51c9e11f6e7532a34d26)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :x:Error | | [Details](#user-content-ca7625d0-3c879287)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-3c879287)

<a id="ca7625d0-3c879287"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-userInsightsSettings-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-userInsightsSettings-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-userInsightsSettings-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-userInsightsSettings-java-snippets.md'.`````

<a id="4922f918-3c879287"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041404326011-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5306cbXUG4qkouH2z0S0KpUp1f38d22%2BDcdn%2BaKlxHU%3D&st=2021-02-04T14%3A00%3A40Z&se=2021-03-07T14%3A05%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 14:18 UTC, opbld33 commented
Docs Build status updates of commit _[e52fa7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e52fa7f74571e2ce721f8d72829c802f290df526)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :x:Error | | [Details](#user-content-ca7625d0-dda1b1a2)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-dda1b1a2)

<a id="ca7625d0-dda1b1a2"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-userInsightsSettings-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-userInsightsSettings-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-userInsightsSettings-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-userInsightsSettings-java-snippets.md'.`````

<a id="4922f918-dda1b1a2"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041415574777-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GcIGd3hWDuqFD9IdAjT%2BCIOl5A1%2FDXQjxzoE9otOFkQ%3D&st=2021-02-04T14%3A13%3A00Z&se=2021-03-07T14%3A18%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 14:24 UTC, opbld33 commented
Docs Build status updates of commit _[c059c00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c059c00bba8accfe094c5987947e083fdfadb026)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :x:Error | | [Details](#user-content-ca7625d0-61a8a741)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-61a8a741)

<a id="ca7625d0-61a8a741"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-userinsightssettings-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-userinsightssettings-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-userinsightssettings-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-userinsightssettings-java-snippets.md'.`````

<a id="4922f918-61a8a741"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041423506353-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FQ4dFwbspj6S4IgTYPbAxsV5Jc9BR2Rh%2Bu6YGE3DwhI%3D&st=2021-02-04T14%3A19%3A52Z&se=2021-03-07T14%3A24%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 14:34 UTC, opbld30 commented
Docs Build status updates of commit _[9a70241](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a7024142a5533b26a313d8f42e5537348f7c66c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :x:Error | | [Details](#user-content-ca7625d0-5b8135cf)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-5b8135cf)

<a id="ca7625d0-5b8135cf"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-userinsightssettings-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-userinsightssettings-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-userinsightssettings-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-userinsightssettings-java-snippets.md'.`````

<a id="4922f918-5b8135cf"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041433036991-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Cx%2FisEAbDcC7z0mMOhquj6YGPbkwOXqFVMM1GKfwx18%3D&st=2021-02-04T14%3A29%3A28Z&se=2021-03-07T14%3A34%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 15:07 UTC, opbld32 commented
Docs Build status updates of commit _[e1590fd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1590fd0ae06f0da3e8671f24c21aa6c2d7adf6f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :x:Error | | [Details](#user-content-ca7625d0-3c911a1c)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-3c911a1c)

<a id="ca7625d0-3c911a1c"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 71, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-userinsightssettings-csharp-snippets.md'.`````
 - **Line 75, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-userinsightssettings-javascript-snippets.md'.`````
 - **Line 79, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-userinsightssettings-objc-snippets.md'.`````
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-userinsightssettings-java-snippets.md'.`````

<a id="4922f918-3c911a1c"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041505293460-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=oHNK48%2Ffy6BxNZnqJr%2BsWzO%2FNV1z76PqZ5paNunnF%2Fw%3D&st=2021-02-04T15%3A02%3A34Z&se=2021-03-07T15%3A07%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 16:17 UTC, opbld34 commented
Docs Build status updates of commit _[5530225](https://github.com/microsoftgraph/microsoft-graph-docs/commits/55302252f6465b0678d720bdd925ffa4552c5519)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :x:Error | | [Details](#user-content-ca7625d0-beef89bb)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-beef89bb)

<a id="ca7625d0-beef89bb"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 74, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/get-userinsightssettings-csharp-snippets.md'.`````
 - **Line 78, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/get-userinsightssettings-javascript-snippets.md'.`````
 - **Line 82, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/get-userinsightssettings-objc-snippets.md'.`````
 - **Line 86, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/get-userinsightssettings-java-snippets.md'.`````

<a id="4922f918-beef89bb"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102041615066762-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H7%2FBA3IlTjl%2B%2BEsUvZMZFmrK9egG1d64DB0LP1Ymvag%3D&st=2021-02-04T16%3A12%3A00Z&se=2021-03-07T16%3A17%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 20:21 UTC, elmakhmu commented
@Lauragra could you, please, help me to sort out that error with 
api-reference/beta/api/userinsightssettings-get.md
api-reference/beta/api/userinsightssettings-update.md

As I understood right the automatic process should create ...snippets.md , but it didn't. Could you point me to the appropriate documentation (which I couldn't find) I would really appreciate that?

2021-02-08 09:20 UTC, elmakhmu commented
@angelgolfer-ms could you, please, help me to sort out that error with
api-reference/beta/api/userinsightssettings-get.md
api-reference/beta/api/userinsightssettings-update.md

As I understood right the automatic process should create ...snippets.md , but it didn't. Could you point me to the appropriate documentation (which I couldn't find) I would really appreciate that?

2021-02-08 18:19 UTC, Lauragra commented
> @Lauragra could you, please, help me to sort out that error with
> api-reference/beta/api/userinsightssettings-get.md
> api-reference/beta/api/userinsightssettings-update.md
> 
> As I understood right the automatic process should create ...snippets.md , but it didn't. Could you point me to the appropriate documentation (which I couldn't find) I would really appreciate that?

@elmakhmu , please remove the snippet links from your topics. The snippets get generated and inserted during the weekly snippet automation run. That process runs on the master branch, so it won't run until we merge the PR into master.

2021-02-08 18:20 UTC, Lauragra commented on api-reference/beta/api/userinsightssettings-get.md
> +# [HTTP](#tab/http)
Delete line 64.

2021-02-08 18:20 UTC, Lauragra commented on api-reference/beta/api/userinsightssettings-get.md
> +# [C#](#tab/csharp)
Delete lines 73-89.

2021-02-08 19:18 UTC, opbld31 commented
Docs Build status updates of commit _[48c7f11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48c7f11082545543dca1a46c623fa0eb6e86a947)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :x:Error | | [Details](#user-content-4922f918-edc6c2ff)

<a id="4922f918-edc6c2ff"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 83, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/javascript/update-userinsightssettings-javascript-snippets.md'.`````
 - **Line 87, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/csharp/update-userinsightssettings-csharp-snippets.md'.`````
 - **Line 91, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/objc/update-userinsightssettings-objc-snippets.md'.`````
 - **Line 95, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../includes/snippets/java/update-userinsightssettings-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081916153793-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SJsJhF8aSxU6BnYez14eQJ4E6q2Q41q0ssM41DqzIGw%3D&st=2021-02-08T19%3A13%3A05Z&se=2021-03-11T19%3A18%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 19:19 UTC, opbld31 commented
Docs Build status updates of commit _[c6f073f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6f073fc6947093c093421c4b5b860259037e664)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081916512885-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PjVoF1VpHXmLSiBwOTSGOfusLe8188pN3Lpp%2FAusxCs%3D&st=2021-02-08T19%3A14%3A18Z&se=2021-03-11T19%3A19%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 19:26 UTC, opbld33 commented
Docs Build status updates of commit _[da36691](https://github.com/microsoftgraph/microsoft-graph-docs/commits/da3669113ec78b37a4c9aed44c9a072bd8227341)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081924517995-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xNMpCO19sYvyQOywMyrYMZLdYRDdYXOv2OvpSKlq1hU%3D&st=2021-02-08T19%3A21%3A52Z&se=2021-03-11T19%3A26%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 19:47 UTC, opbld33 commented
Docs Build status updates of commit _[17a1658](https://github.com/microsoftgraph/microsoft-graph-docs/commits/17a1658547c8946142efb0f50806b792064ab347)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102081946175686-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8ihmHt9omIaLYPjIRzGe5k16QNnYCvEKoiWzgp8BH7Q%3D&st=2021-02-08T19%3A42%3A21Z&se=2021-03-11T19%3A47%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-08 19:52 UTC, elmakhmu commented
@Lauragra woohoo! it worked, thanks a lot! Could you, please, review that documents?

2021-02-09 02:51 UTC, opbld34 commented
Docs Build status updates of commit _[32d03ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32d03ec9a862907e6f6d8ca85d6de47472ff9f04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090250139776-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9Dr62OpdhLl2p16A0v4MS7UcFZ4%2FMhGwYNIaqHcO96A%3D&st=2021-02-09T02%3A46%3A24Z&se=2021-03-12T02%3A51%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 02:52 UTC, opbld32 commented
Docs Build status updates of commit _[7404b0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7404b0c332576f0a9e370cc28f4abeac1a622285)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090250556584-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aWJz4iTqVbNB8AsEi0YWkbgpfzTAiDQW8Xd9XCpp5tY%3D&st=2021-02-09T02%3A47%3A35Z&se=2021-03-12T02%3A52%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 02:56 UTC, opbld32 commented
Docs Build status updates of commit _[873fa4f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/873fa4f938ed6633b67efac71057b23fb1b64429)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090255338206-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BwQ3pCTkcyLU1IlQXTL%2FpUht5o5Wv%2FDeV%2BaekGDldEw%3D&st=2021-02-09T02%3A51%3A42Z&se=2021-03-12T02%3A56%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 03:00 UTC, opbld30 commented
Docs Build status updates of commit _[3e25032](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e250329c1f07866311dab7b05e0b1a633725039)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102090259175735-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=npA3c8apUlk0TaqWMT5Ve%2Fvf2tNlTi7P9EgyCihSlaQ%3D&st=2021-02-09T02%3A55%3A23Z&se=2021-03-12T03%3A00%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 03:03 UTC, Lauragra commented on concepts/changelog.md
> +## February 2021
We no longer update the changelog.md file. Please add an entry to the Microsoft.Analystics.json file in the changelog folder. For details, see: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-02-09 03:05 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: Control access to user item insights
This TOC entry should be "User insight settings". For the entry above, please change it to "Item insight settings".

2021-02-09 03:07 UTC, Lauragra commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
In the itemInsightsSettings topic, we mention that meeting hours insights are rolling out in November 2020. Are they rolled out now? It seems odd to mention meeting hours insights if they haven't rolled out yet, unless you need to update the timeline/add a note here.

2021-02-09 03:07 UTC, Lauragra requested changes
Please see comments. Thanks.

2021-02-09 08:47 UTC, angelgolfer-ms commented
> @angelgolfer-ms could you, please, help me to sort out that error with
> api-reference/beta/api/userinsightssettings-get.md
> api-reference/beta/api/userinsightssettings-update.md
> 
> As I understood right the automatic process should create ...snippets.md , but it didn't. Could you point me to the appropriate documentation (which I couldn't find) I would really appreciate that?

@elmakhmu , the topic about the snippet generator is here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103162/Generate-code-snippets

2021-02-09 08:58 UTC, elmakhmu commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
@PollyNincevic do you know the last updates here?

2021-02-09 09:07 UTC, elmakhmu commented on api-reference/beta/toc.yml
> +          - name: Control access to user item insights
Entry  "User insight settings" is placed lowed by one position, I just wanted to emphasize the moment that item insights can be controllable by 2 entities (admin can use _Item insights settings_, and user can use _User insights settings)_
I can delete "_- name: Control access to user item insights_" and toc will look

        - name: Control access to item insights
          items:
          - name: Item insights settings
            href: resources/iteminsightssettings.md
          - name: Get
            href: api/iteminsightssettings-get.md
          - name: Update
            href: api/iteminsightssettings-update.md
          - name: User insights settings
            href: resources/userinsightssettings.md
          - name: Get
            href: api/userinsightssettings-get.md
          - name: Update
            href: api/userinsightssettings-update.md


Will it be ok?

2021-02-09 22:19 UTC, opbld33 commented
Docs Build status updates of commit _[a0a14f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0a14f80832860c90f4f7ffa654378ec034aef34)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102092217570343-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MPK4DHzuqiZxHmb51UfvZ3cY0EHL9XNp16RkIRPDp%2FU%3D&st=2021-02-09T22%3A14%3A18Z&se=2021-03-12T22%3A19%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-09 22:26 UTC, opbld30 commented
Docs Build status updates of commit _[9e23a23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e23a23afedbab9769769f696a211e9b9a9b50c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102092224588708-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cf%2B0cCrKgEowb6fesm4TnHIJlepqazEa3CpJENiqgOA%3D&st=2021-02-09T22%3A21%3A05Z&se=2021-03-12T22%3A26%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 08:31 UTC, angelgolfer-ms commented on api-reference/beta/resources/usersettings.md
> +Configure the visibility of [insights](../resources/iteminsights.md) derived from Microsoft Graph, between users and other items (such as documents or sites) in Microsoft 365:
Line 30:
@elmakhmu , please change the link text from "insights" to "itemInsights". 
Just a few lines above (line 26) talks about another concept involving insights, so I think it's better to be as explicit as possible, in such context.

2021-02-10 08:45 UTC, angelgolfer-ms commented on api-reference/beta/resources/usersettings.md
> +|itemInsights|[userInsightsSettings](userinsightssettings.md)| The user's settings for the visibility of Microsoft Graph-derived insights, between a user and other items in Microsoft 365, such as doc
Line 58:
Because "userInsightSettings" is actually about user-controlled settings for item insights (itemInsights), I would suggest again making it as clear as possible. Would I be understating some idea, if I rephrase the description without "Microsoft Graph"? That is: "The user's settings for the visibility of insights derived between a user and other items in Microsoft 365, such as documents or sites."

BTW, the next link text should use camel case "Get userInsightsSettings", not all lower case.

2021-02-10 09:03 UTC, angelgolfer-ms commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
Yes, @elmakhmu , was there a special circumstance when you added this note?
For the future, if an API or feature hasn't become available world-wide, please don't include its documentation or notes of this kind promising the feature by some time or time period. We may forget about removing the note. Notes of this kind can lend doubt to the expectations we build for customers: APIs are released <-> docs are published.

2021-02-10 09:13 UTC, angelgolfer-ms commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
Line 16:
It's good that you point out this pertains at a user level. On the other hand, instead of "Use this API to disable/enable...", please say "Use this resource to disable/enable..."

For contrast, please add after line 19 in a separate paragraph, to bring up itemInsightSettings which are for the org level, something to the effect of:

"Use the itemInsightsSettings {add link} resource to disable/enable calculation and visibility of item insights and meeting hours insights at an organization level."

And then in iteminsightssettings.md, please apply a similar pattern in the top part of the topic, and add a sentence to contrast with userInsightsSettings:
"Use the userInsightsSettings {add link} resource to disable/enable calculation and visibility of item insights and meeting hours insights of a user. "

2021-02-10 09:14 UTC, angelgolfer-ms commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
Please don't forget to remove the note about meeting hours in iteminsightssettings.md as well.

2021-02-10 09:17 UTC, angelgolfer-ms commented on api-reference/beta/resources/userinsightssettings.md
> +| isEnabled     | Boolean  |  `true` if user's item insights are enabled; `false` if user's item insights are disabled. Default is `true`. Optional.|
Line 31:
I would suggest not to use the friendly term "item insights" (2 occurrences) here. Please use itemInsights and bold the terms, to make it clear we're referring to the resource itemInsights. (You've got a first reference in line 16 with a link, so just bolding is sufficient, per Microsoft style guide.)

2021-02-10 09:27 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
> +          - name: Control access to user item insights
I'm going to suggest a TOC structure like this:

      - name: Insights
        items:
        - name: Item insights
          href: resources/iteminsights.md
          items:
          - name: List shared
            href: api/insights-list-shared.md
          - name: List trending
            href: api/insights-list-trending.md
          - name: List used
            href: api/insights-list-used.md
        - name: Organization control
          items:
          - name: Item insights settings
            href: resources/iteminsightssettings.md
          - name: Get
            href: api/iteminsightssettings-get.md
          - name: Update
            href: api/iteminsightssettings-update.md
        - name: User control
          items:
          - name: User insights settings
            href: resources/userinsightssettings.md
          - name: Get
            href: api/userinsightssettings-get.md
          - name: Update
            href: api/userinsightssettings-update.md     

Don't forget there's another reference to itemInsights API in the beta TOC, around line 11848. That's under the "People and workplace intelligence" node.

2021-02-10 09:33 UTC, angelgolfer-ms commented on api-reference/beta/api/userinsightssettings-update.md
> +Update the properties of the specified [userInsightsSettings](../resources/userinsightssettings.md) resource.
Line 16:
Should this be "Update the properties of the userInsightsSettings {include link} of the specified user."?

There isn't technically a specific userInsightSettings resource, as in indexing into a collection. Indirectly yes, this operation specifies a user who has one such resource.

2021-02-10 09:37 UTC, angelgolfer-ms commented on api-reference/beta/api/userinsightssettings-get.md
> +|Application | Not supported. |
Line 26:
Just double-checking - no application perm support?  (contrary to api.md file)

2021-02-10 09:42 UTC, angelgolfer-ms commented on api-reference/beta/api/userinsightssettings-get.md
> +Get the properties of a [userInsightsSettings](../resources/userinsightssettings.md) object.
Line 16:
I suspect this description is the generic description for a GET operation (sentence structure doesn't convey any extra meaning other than what a GET {resource} does).
If we want to make this description more helpful, I'd suggest:
"Get the user-customizable privacy settings for itemInsights {add link} and meeting hours insights."

2021-02-10 09:44 UTC, angelgolfer-ms commented on api-reference/beta/api/userinsightssettings-update.md
> +|isEnabled|Boolean| `true` if user's item insights are enabled; `false` if user's item insights are disabled. Default is `true`. Optional.|
Line 51:
Should the description include meeting hour insights, since userInsightSettings is defined to include that?

2021-02-10 09:45 UTC, angelgolfer-ms commented on api-reference/beta/api/userinsightssettings-update.md
> +The following is an example request on how user updates "**isEnabled**" privacy setting in order to disable his item insights.
Line 61:
Should the description include meeting hour insights, since userInsightSettings is defined to include that?

2021-02-10 09:46 UTC, angelgolfer-ms commented on api-reference/beta/api/userinsightssettings-get.md
> +The following is an example of the request to get user insight settings.
Line 56:
Should the description include meeting hour insights, since userInsightSettings is defined to include that?

2021-02-10 09:53 UTC, elmakhmu commented on concepts/changelog.md
> +## February 2021
@Lauragra @angelgolfer-ms  I deleted .md file and added json. But because it was added automatically first time it created lots of others entities (not just related to this PR), hope it's the right thing that I excluded them? And secondly, under userSettings entity the process hasn't added new nav property "itemInsights". Should it be added manually?

2021-02-10 09:58 UTC, angelgolfer-ms requested changes
Hi @elmakhmu , I added some clarification because I suspected some confusion in some TOC suggestions you had got. I think newer customers may overlook the differentiation between  organization-level and user-level control for itemInsightsSettings and userInsightsSettings respectively. 
Please let me know if I actually got confused :-)

2021-02-10 19:17 UTC, elmakhmu commented on api-reference/beta/resources/usersettings.md
> +Configure the visibility of [insights](../resources/iteminsights.md) derived from Microsoft Graph, between users and other items (such as documents or sites) in Microsoft 365:
fixed

2021-02-10 19:20 UTC, elmakhmu commented on api-reference/beta/resources/usersettings.md
> +|itemInsights|[userInsightsSettings](userinsightssettings.md)| The user's settings for the visibility of Microsoft Graph-derived insights, between a user and other items in Microsoft 365, such as doc
fixed

2021-02-10 19:26 UTC, elmakhmu commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
fixed

2021-02-10 19:28 UTC, elmakhmu commented on api-reference/beta/resources/userinsightssettings.md
> +| isEnabled     | Boolean  |  `true` if user's item insights are enabled; `false` if user's item insights are disabled. Default is `true`. Optional.|
fixed

2021-02-10 19:30 UTC, elmakhmu commented on api-reference/beta/api/userinsightssettings-update.md
> +Update the properties of the specified [userInsightsSettings](../resources/userinsightssettings.md) resource.
fixed

2021-02-10 19:32 UTC, elmakhmu commented on api-reference/beta/api/userinsightssettings-get.md
> +|Application | Not supported. |
no, this is not supported at the backend level (shortcoming of api.md file)

2021-02-10 19:34 UTC, elmakhmu commented on api-reference/beta/api/userinsightssettings-get.md
> +Get the properties of a [userInsightsSettings](../resources/userinsightssettings.md) object.
fixed

2021-02-10 19:35 UTC, elmakhmu commented on api-reference/beta/api/userinsightssettings-update.md
> +|isEnabled|Boolean| `true` if user's item insights are enabled; `false` if user's item insights are disabled. Default is `true`. Optional.|
fixed

2021-02-10 19:36 UTC, elmakhmu commented on api-reference/beta/api/userinsightssettings-update.md
> +The following is an example request on how user updates "**isEnabled**" privacy setting in order to disable his item insights.
fixed

2021-02-10 19:36 UTC, elmakhmu commented on api-reference/beta/api/userinsightssettings-get.md
> +The following is an example of the request to get user insight settings.
fixed

2021-02-10 19:45 UTC, elmakhmu commented on api-reference/beta/toc.yml
> +          - name: Control access to user item insights
fixed

2021-02-10 19:47 UTC, opbld30 commented
Docs Build status updates of commit _[d85e4dc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d85e4dc5f706045c44fd8148c7b77d001876412c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101946397010-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AoYVz%2F39p16kHNuVxKbsaJn8v0uYFpirSu8XgsCtwIU%3D&st=2021-02-10T19%3A42%3A47Z&se=2021-03-13T19%3A47%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 19:48 UTC, opbld30 commented
Docs Build status updates of commit _[66d8b5a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/66d8b5a0939fc72ae4953af45bc35b22e274d641)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101946593084-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MRzG4kDf1CTPFVZYwR3P%2FZxDPQFmn3juihXBJT%2Fp8WY%3D&st=2021-02-10T19%3A43%3A53Z&se=2021-03-13T19%3A48%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 19:49 UTC, elmakhmu commented
@angelgolfer-ms Thanks for all of your valuable feedback, I fixed everything including TOC. 

About changelog:
 I deleted .md file and added json. But because it was added automatically first time it created lots of others entities (not just related to this PR), hope it's the right thing that I excluded them? And secondly, under userSettings entity the process hasn't added new nav property "itemInsights". Should it be added manually?

2021-02-10 20:11 UTC, PollyNincevic commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
@elmakhmu @angelgolfer-ms @Lauragra the meeting hours insights on the profile card is not 100% in prod yet, but started rolling out. We published the topic once a few customers had it. I have asked PM for dates to confirm when it is 100%. I removed the date from the topic on SMC, but it still says that the feature is not yet generally available.

2021-02-10 20:16 UTC, PollyNincevic commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
@angelgolfer-ms should we remove the note completely from iteminsightssettings.md even if meeting hours are not yet generally available, but only to some?

2021-02-11 05:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/usersettings.md
> +|itemInsights|[userInsightsSettings](userinsightssettings.md)| The user's settings for the visibility of insights derived between a user and other items in Microsoft 365, such as documents or sites.
Line 58:
@elmakhmu , I just noticed we missed this one - since the itemInsights nav property is of the userInsightSettings type which includes control for both itemInsights and meeting hours insights, then the description for the itemInsights nav property should include meeting hours insights too. 

BTW, you probably would agree naming this nav property as itemInsights can be misleading? It's about privacy settings for exposing those item insights and meeting hour insights. This is just a comment, not requesting an API name change at this point.

2021-02-11 07:10 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +{
@elmakhmu , where did you get the file name Microsoft.OfficeGraph.json? 
It seems that the pre-existing changelog items for the features under the "People and workplace intelligence" node are all in microsoft.analytics.json. Can you use that file instead?

2021-02-11 07:14 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +      "SubArea": ""
Line 27:
Please add the SubArea - "Insights". This will display the section title "People and workplace intelligence | Insights" on the changelog page.

2021-02-11 07:16 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +          "Description": "Added the [userSettings](https://docs.microsoft.com/en-us/graph/api/resources/userSettings?view=graph-rest-beta) resource type.",
Line 10:
This changelist item is not applicable, you didn't add the userSettings resource, right? 
Instead, you added the itemInsights nav property to the pre-existing userSettings resource.
You can see example titled "Example: Add a navigation property to a resource" in the CDK topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=changelog-json-file-structure

2021-02-11 07:20 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +        },
Line 20:
Please make sure the last item in the changeList doesn't have a trailing comma.

2021-02-11 07:24 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +        },
You also need to add 2 ChangeList records for each of the GET and PATCH operations of userInsightsSettings. 
Each record would be similar to that for the nav property, except ApiChange should be Method.

2021-02-11 07:32 UTC, angelgolfer-ms requested changes
Thanks for incorporating the last set of feedback.
3 remaining things:
(1) Changelog JSON - please see my comments.
(2) Description for the new itemInsights nav property in usersettings.md.
(3) Technically, it would be helpful if you update the insights-customize-item-insights-privacy.md concept topic, and make it clear in the first topic there's the org-level customization, and user-level customization. Then add a section to describe the user-level customization.
If for some reason you're not updating that concept topic, then please update the topic title and make it clear in the first paragraph it's possible to customize at the organization level and user level, and this topic focuses on the former, and for the latter, see the itemInsights nav property in the userSettings resource, and the userItemInsights resource.

2021-02-11 08:27 UTC, angelgolfer-ms commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
@PollyNincevic , @elmakhmu ,
Did you find out the estimated number of days to saturation?
For Exchange APIs, I think we look for >= 95% saturation (world wide availability) before we ever publish the docs for a new API or feature. The reason this is important is documenting a feature that's not yet available breaks the expectations that we have built for customers: APIs are released and available <-> API docs are published. Customers finding the docs but not being able to get the API to work, in Graph Explorer for example, would be confusing, and for those who have premium support, they may call Support and that's one thing we generally want to avoid as much as we can.

If you guys don't estimate that level of saturation by early next week (2/15), then please remove all mentions of meeting hours insights! If you could do it within the next day (2/11), that would be good, because Laura is going to be OOF on 2/12, and the US has 2/15 as holiday too (Sigh.)

2021-02-11 11:08 UTC, elmakhmu commented on changelog/Microsoft.OfficeGraph.json
> +{
this files is machine generated based on our schema changes, because we're the first one who generated that json files that is why it's a new file. 
https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog 

![image](https://user-images.githubusercontent.com/54312959/107629060-d9678600-6c61-11eb-944f-d34c48d77018.png)

2021-02-11 11:10 UTC, elmakhmu commented on changelog/Microsoft.OfficeGraph.json
> +      "SubArea": ""
fixed

2021-02-11 11:12 UTC, elmakhmu commented on changelog/Microsoft.OfficeGraph.json
> +          "Description": "Added the [userSettings](https://docs.microsoft.com/en-us/graph/api/resources/userSettings?view=graph-rest-beta) resource type.",
but what about automatically generated GUID? Would it be ok to copy nav property example but keep the ID from userSettings?

2021-02-11 11:14 UTC, elmakhmu commented on changelog/Microsoft.OfficeGraph.json
> +        },
what about the GUID again? where will it come from?

2021-02-11 11:26 UTC, opbld33 commented
Docs Build status updates of commit _[d744f19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d744f198e591967f4fc210c2cad800d9a2d0a7c6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111125273261-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KXP0fbIBa0s7kd3uI%2Bl3DQxvxfOn75EcRk3jSGnW3BA%3D&st=2021-02-11T11%3A21%3A36Z&se=2021-03-14T11%3A26%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 18:17 UTC, elmakhmu commented on api-reference/beta/resources/userinsightssettings.md
> +Represents user privacy settings for [itemInsights](iteminsights.md) and meeting hours insights. Use this API to disable/enable calculation and visibility of item insights and meeting hours insights
Polly contacted with feature owners and we found out that Meeting Hours Insights are indeed rolled out WW recently, so I will delete that note from all docs.

2021-02-11 18:34 UTC, elmakhmu commented on api-reference/beta/resources/usersettings.md
> +|itemInsights|[userInsightsSettings](userinsightssettings.md)| The user's settings for the visibility of insights derived between a user and other items in Microsoft 365, such as documents or sites.
@angelgolfer-ms when we discussed with @PollyNincevic back in November how to put meeting hours insights dependencies in docs we had 2 options:
1. "itemInsightsSettings resource type represents privacy settings for **itemInsights** and privacy setting for **meeting hours insights.**". In that option we split up that 2 definitions and mean that only privacy settings is joining them together. but from the root those 2 feature are completely different. Disadvantage of that approach is what you brought - users might get confused of settings/iteminsights control meetings hours insights.
2. "itemInsightsSettings resource type represents privacy settings for **item Insights**, where **item insights** include files and meeting hours insights." In that case meeting hours insights is included in the definition of itemInsights (item in that case can be anything - files, meetings etc.) and users shouldn't be confused. But then users might get an impression that /insights API (which has nothing to do with meeting hours) also affect calculating calendar events.  

So we picked up the 1 option as the least risky. what do you think?

2021-02-11 18:37 UTC, elmakhmu commented
@angelgolfer-ms many-many thanks for super quick feedback, really appreciate it since the time matters for that PR.
There are 2 open questions left in comments
1. how to outplay meeting hours insights dependencies under itemInsights object
2. questions about changelog.
Looking forward of your ideas.

2021-02-13 01:36 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +{
Ok, I believe what you say, but it's surprising to me why the same folks ported your earlier changelog items from changelog.md to Microsoft.Analytics.json, and now the generator would generate changelog items for your service in Microsoft.OfficeGraph.json.
@Lauragra , is there anywhere that Dan et al defined which services should use which changelog JSON file?

I see this as a potential point of confusion for partners and content reviewers. 

In terms of the external customer experience, it doesn't matter which of the two changelog JSON file is used, as long as the changelog tool knows about that changelog JSON file.

2021-02-13 01:39 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +          "Description": "Added the [userSettings](https://docs.microsoft.com/en-us/graph/api/resources/userSettings?view=graph-rest-beta) resource type.",
Oh yes, the Id values in a changelog record should be all the same value. In your Microsoft.OfficeGraph.json, those are the values in lines 6, 14, 22.

2021-02-13 01:39 UTC, angelgolfer-ms commented on changelog/Microsoft.OfficeGraph.json
> +        },
All Id properties within the same changelog record should have the same value.

2021-02-13 02:11 UTC, angelgolfer-ms commented on api-reference/beta/resources/usersettings.md
> +|itemInsights|[userInsightsSettings](userinsightssettings.md)| The user's settings for the visibility of insights derived between a user and other items in Microsoft 365, such as documents or sites.
HI @elmakhmu , I am sending you an email to give a suggestion.

2021-02-13 03:50 UTC, angelgolfer-ms requested changes
Hi @elmakhmu , there are actually 5 things to follow up; I implemented 1 of the 5, so 4 are for your follow up. I listed them in an email so that we need to track one place (in this case email), instead of both GitHub and email. Can you please take a look?

2021-02-17 00:31 UTC, Lauragra commented on changelog/Microsoft.OfficeGraph.json
> +{
> Ok, I believe what you say, but it's surprising to me why the same folks ported your earlier changelog items from changelog.md to Microsoft.Analytics.json, and now the generator would generate changelog items for your service in Microsoft.OfficeGraph.json.
> @Lauragra , is there anywhere that Dan et al defined which services should use which changelog JSON file?
> 
> I see this as a potential point of confusion for partners and content reviewers.
> 
> In terms of the external customer experience, it doesn't matter which of the two changelog JSON file is used, as long as the changelog tool knows about that changelog JSON file.

@angelgolfer-ms , it technically doesn't matter which JSON file they add their entries into because they are combined into a single JSON file in the content repo. We do have this mappings file that we used to map workloads to services: https://microsoft.sharepoint.com/teams/MicrosoftGraph18/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x012000C4D315DBD83CA642A648AD5604EC492B&id=%2Fteams%2FMicrosoftGraph18%2FShared%20Documents%2FDocs%20%2D%20Change%20Log%2Fnew%2Dmapping%2Ejson&parent=%2Fteams%2FMicrosoftGraph18%2FShared%20Documents%2FDocs%20%2D%20Change%20Log

2021-02-17 05:39 UTC, opbld31 commented
Docs Build status updates of commit _[372fed7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/372fed7dd0bf04bc8de114be26411c0c3a7123e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-ca7625d0-91ae9504)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-4922f918-91ae9504)
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-0a13b16b-91ae9504)
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-91ae9504)
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-91ae9504)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

<a id="ca7625d0-91ae9504"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4922f918-91ae9504"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="0a13b16b-91ae9504"></a>
### [api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57415194-91ae9504"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ebb9a6c-91ae9504"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170536515963-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K6g%2FGGp7uytab0k3rmteNQOrYKzqyLu9wJ08Vz%2Bqe1Y%3D&st=2021-02-17T05%3A34%3A18Z&se=2021-03-20T05%3A39%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 05:40 UTC, opbld34 commented
Docs Build status updates of commit _[feca87d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/feca87d2586d8e75b94ff38c0a18f2ccd8c5547c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-ca7625d0-ac5d7685)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-4922f918-ac5d7685)
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-0a13b16b-ac5d7685)
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-ac5d7685)
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-ac5d7685)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

<a id="ca7625d0-ac5d7685"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4922f918-ac5d7685"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="0a13b16b-ac5d7685"></a>
### [api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57415194-ac5d7685"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ebb9a6c-ac5d7685"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170537527925-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lPJBfBs4wDKYsQBut%2BfR6jC7A19rgyjdIQabfzyPNHI%3D&st=2021-02-17T05%3A35%3A29Z&se=2021-03-20T05%3A40%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 10:19 UTC, opbld31 commented
Docs Build status updates of commit _[d8aa511](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d8aa5118bf988929e881211efcef4104a6f5e1f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-ca7625d0-640c658f)
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-4922f918-640c658f)
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-0a13b16b-640c658f)
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-640c658f)
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-640c658f)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-b6eecee3-640c658f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

<a id="ca7625d0-640c658f"></a>
### [api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4922f918-640c658f"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="0a13b16b-640c658f"></a>
### [api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57415194-640c658f"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ebb9a6c-640c658f"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b6eecee3-640c658f"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171017484003-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dEogjebA8am0q85nQ9xFAsCOOq5amJ1WSlHLFMmWzP4%3D&st=2021-02-17T10%3A14%3A02Z&se=2021-03-20T10%3A19%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li> [...]

2021-02-17 10:54 UTC, opbld31 commented
Docs Build status updates of commit _[8a091bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a091bb243ed1c38b9b77741c217bd99b01094f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-4922f918-e445bb51)
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-0a13b16b-e445bb51)
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-e445bb51)
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-e445bb51)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-b6eecee3-e445bb51)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

<a id="4922f918-e445bb51"></a>
### [api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="0a13b16b-e445bb51"></a>
### [api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57415194-e445bb51"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ebb9a6c-e445bb51"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b6eecee3-e445bb51"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171053449635-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6Ij8O3AeKwHhBCxh9D8c0ssoPE44CkM%2BbathFj6oK1o%3D&st=2021-02-17T10%3A49%3A55Z&se=2021-03-20T10%3A54%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87e [...]

2021-02-17 11:08 UTC, opbld34 commented
Docs Build status updates of commit _[139af59](https://github.com/microsoftgraph/microsoft-graph-docs/commits/139af599c7cf98ab5c782f7b3d21c1f01bb2ef23)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-0a13b16b-fd071c9f)
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-57415194-fd071c9f)
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-fd071c9f)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-b6eecee3-fd071c9f)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

<a id="0a13b16b-fd071c9f"></a>
### [api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="57415194-fd071c9f"></a>
### [api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1ebb9a6c-fd071c9f"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b6eecee3-fd071c9f"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171107240174-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wnBqtlwj7HQpIawcjHDK7RrbVJvaKXv4vjGaHCFJn%2BU%3D&st=2021-02-17T11%3A03%3A43Z&se=2021-03-20T11%3A08%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 11:10 UTC, opbld33 commented
Docs Build status updates of commit _[c5ad83d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c5ad83d9d47430dbe89b65bccac4cbed1ea6ac86)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-1ebb9a6c-98ac1b9c)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-b6eecee3-98ac1b9c)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |

<a id="1ebb9a6c-98ac1b9c"></a>
### [api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="b6eecee3-98ac1b9c"></a>
### [concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171107463247-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DQYFYIdybdtltGghJr9uUUeTqv1GU88UnZypZIAZBSQ%3D&st=2021-02-17T11%3A05%3A55Z&se=2021-03-20T11%3A10%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 11:21 UTC, opbld34 commented
Docs Build status updates of commit _[2276929](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2276929aa23c1f4d1bc1100a5dc2676e8a1da938)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171120054627-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=H%2BzBoZ%2BIVws5Z2vIJRndq2Pob%2Bn5RgBFRf9tcS%2Fe3tc%3D&st=2021-02-17T11%3A16%3A22Z&se=2021-03-20T11%3A21%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 11:22 UTC, opbld34 commented
Docs Build status updates of commit _[f9e7ff5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9e7ff5a2edbb31e8df67468480193d3e12f522d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171120284836-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zZbxrmxYy%2BEdsfyIj5kmjWw9WiYx6OEBO8nQbBe3m%2Bo%3D&st=2021-02-17T11%3A17%3A34Z&se=2021-03-20T11%3A22%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 11:37 UTC, elmakhmu commented on api-reference/beta/resources/usersettings.md
> +|itemInsights|[userInsightsSettings](userinsightssettings.md)| The user's settings for the visibility of insights derived between a user and other items in Microsoft 365, such as documents or sites.
@angelgolfer-ms I replied on email.

2021-02-17 11:41 UTC, elmakhmu commented on changelog/Microsoft.OfficeGraph.json
> +{
so, I guess it's ok to have file named Microsoft.OfficeGraph.json?

2021-02-18 09:09 UTC, opbld33 commented
Docs Build status updates of commit _[2f68d1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f68d1ecd60c4d5499731908542d8d381645aef9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102180908454979-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=41HabtUKsswWuNBF4RoY7wFKO4fzB20oXOXoeMmNLas%3D&st=2021-02-18T09%3A04%3A58Z&se=2021-03-21T09%3A09%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-18 09:11 UTC, elmakhmu commented
@angelgolfer-ms I've updated changelog/Microsoft.OfficeGraph.json, but reused existing generated GUIDs for nav property and GET-PATCH methods.

+send an email with other open questions. Could you, please, have a look?

2021-02-20 10:26 UTC, angelgolfer-ms approved these changes
@elmakhmu , I made some final fixes and edits as described in my email. Since we have addressed my feedback, I am approving this PR.
Separately, I have requested @Lauragra to confirm if we should add ms.author. Please follow up with her.

2021-02-24 19:23 UTC, elmakhmu commented
Changed author: "simonhul" -> "simonhul**t**" to adjust it to his GitHub name (not Microsoft alias)

2021-04-07 15:27 UTC, Lauragra commented
@elmakhmu , have you incorporated all comments on this PR? If so, can you please address the merge conflict and set **ready to merge** when ready so we can publish? Thanks.

2021-04-08 06:41 UTC, elmakhmu commented
@Lauragra  although all comments have been incorporated, due to some obstacles we faced from backend side we're not ready to publish this documentation (settings values has no effect on our service today). Can we postpone publishing for 1 month?

2021-05-21 09:53 UTC, opbld32 commented
Docs Build status updates of commit _[21fe3c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/21fe3c69a581cbb53ffa4a37ad87401409763257)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-30536e4d)

<a id="30536e4d"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105210951565512-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z62X4griuWF07CqBM8nFuzdlMfdhBZ9hXmaIz%2BSaVus%3D&st=2021-05-21T09%3A48%3A32Z&se=2021-06-21T09%3A53%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 10:03 UTC, opbld34 commented
Docs Build status updates of commit _[2798e51](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2798e51295d12702738d5937fdd49db3e42ec432)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ef67a539)

<a id="ef67a539"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211002395903-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BBsgIgNPO5%2F9aK8T%2FEHOq1E0uow%2F5WB5tBBZ%2FWwQoB0%3D&st=2021-05-21T09%3A58%3A41Z&se=2021-06-21T10%3A03%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 10:10 UTC, opbld34 commented
Docs Build status updates of commit _[60b9ccd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60b9ccde370dda9fc88a0336e4739d9c003a2c8f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9be1cc17)

<a id="9be1cc17"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211009108100-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HIz0v235Fxm%2BoOX0qkFHTFL7otHeiqPM86boC7t7i0k%3D&st=2021-05-21T10%3A05%3A32Z&se=2021-06-21T10%3A10%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 10:43 UTC, opbld31 commented
Docs Build status updates of commit _[dd7cc9f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd7cc9faa453e4c4c7b4fd8a3849e8c62b6c20f0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-67203e9f)

<a id="67203e9f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211042258710-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dzNI3pw7g6Je9a8fabahZcPBzLijSF%2Brv5exCyh7RK4%3D&st=2021-05-21T10%3A38%3A46Z&se=2021-06-21T10%3A43%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 11:02 UTC, opbld30 commented
Docs Build status updates of commit _[3bbfbb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bbfbb20b0596833e8bb1e3c11c2419f4e7c95ec)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a8f15296)

<a id="a8f15296"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211101308977-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hq3ZC1ZOOZ%2BdPajX%2BVQxZ1gfgDpig39v%2Bn8mK%2F0KeSQ%3D&st=2021-05-21T10%3A57%3A45Z&se=2021-06-21T11%3A02%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 12:32 UTC, opbld31 commented
Docs Build status updates of commit _[3f695ac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f695acbbba49a73b1c92617b79ce00cca870433)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-674c3340)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in%20card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/recent-files-in%20card-based-interfaces.png?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office.com](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office.com) | :white_check_mark:Succeeded | |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="3577f03000bf8c5ecd840f860e25d5b7-674c3340"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md)
 - **Line 11, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Computation of item insights'.`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Item insights in Microsoft 365') are not allowed. You can only have one top-level heading.`````
 - **Line 37, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Microsoft runs on trust') are not allowed. You can only have one top-level heading.`````
 - **Line 46, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Disabling item insights') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211230225392-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c0jIyZFUeS10G5rupvVUVLP2JwRxqz1gdV780Of90lU%3D&st=2021-05-21T12%3A27%3A40Z&se=2021-06-21T12%3A32%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/Gener [...]

2021-05-21 12:36 UTC, opbld32 commented
Docs Build status updates of commit _[0c3ba2a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c3ba2a4fbb974a3b3d698489b7f6fc60a396ee5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-6ea8f567)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in%20card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/recent-files-in%20card-based-interfaces.png?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="3577f03000bf8c5ecd840f860e25d5b7-6ea8f567"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md)
 - **Line 11, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Computation of item insights'.`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Item insights in Microsoft 365') are not allowed. You can only have one top-level heading.`````
 - **Line 37, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Microsoft runs on trust') are not allowed. You can only have one top-level heading.`````
 - **Line 46, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Disabling item insights') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211235021192-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Kxq%2BBEdMpDEGj5%2Fi4ddvoiajR4NS77lJVhojameY%2B8Q%3D&st=2021-05-21T12%3A31%3A15Z&se=2021-06-21T12%3A36%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-21 12:58 UTC, opbld31 commented
Docs Build status updates of commit _[29c6508](https://github.com/microsoftgraph/microsoft-graph-docs/commits/29c6508e9c953371d0e62734ac32beebcd2f4643)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-f0c7195e)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in%20card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/recent-files-in%20card-based-interfaces.png?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-delve.png?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-office.png?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-persona-card.png?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="3577f03000bf8c5ecd840f860e25d5b7-f0c7195e"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md)
 - **Line 11, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Computation of item insights'.`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Item insights in Microsoft 365') are not allowed. You can only have one top-level heading.`````
 - **Line 37, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Microsoft runs on trust') are not allowed. You can only have one top-level heading.`````
 - **Line 46, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Disabling item insights') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211256214931-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3E17HEhM5NbIP2Cw8rrdLOa52P01GMzryrO6mlJ0gKI%3D&st=2021-05-21T12%3A53%3A27Z&se=2021-06-21T12%3A58%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/rep [...]

2021-05-21 13:02 UTC, opbld34 commented
Docs Build status updates of commit _[1c4cdde](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c4cdde89e861cf53ab083fc0f0b6f43b9cd4889)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-6eca6c8c)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-delve.png?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-office.png?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-persona-card.png?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="3577f03000bf8c5ecd840f860e25d5b7-6eca6c8c"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md)
 - **Line 11, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Computation of item insights'.`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Item insights in Microsoft 365') are not allowed. You can only have one top-level heading.`````
 - **Line 37, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Microsoft runs on trust') are not allowed. You can only have one top-level heading.`````
 - **Line 46, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Disabling item insights') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211300549498-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ekf3c3FNCbZ%2Fq8Y44LhmDnwXQ4tYgXvx1auVGKlUsUw%3D&st=2021-05-21T12%3A57%3A37Z&se=2021-06-21T13%3A02%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master& [...]

2021-05-21 13:04 UTC, opbld33 commented
Docs Build status updates of commit _[f898a9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f898a9cfcbbb7f38fcd3564cd2642072c3b10cd1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-6658f323)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/recent-files-in-card-based-interfaces.png?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-delve.png?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-office.png?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/disabled-item-insights-in-persona-card.png?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="3577f03000bf8c5ecd840f860e25d5b7-6658f323"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md)
 - **Line 11, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Computation of item insights'.`````
 - **Line 23, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Item insights in Microsoft 365') are not allowed. You can only have one top-level heading.`````
 - **Line 37, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Microsoft runs on trust') are not allowed. You can only have one top-level heading.`````
 - **Line 46, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Disabling item insights') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211301320531-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=23cPKVXwRYkCRcJpSFghgnOiX1opmtIJGJiUCi8EL7Y%3D&st=2021-05-21T12%3A59%3A09Z&se=2021-06-21T13%3A04%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/7 [...]

2021-05-21 13:36 UTC, opbld32 commented
Docs Build status updates of commit _[a72d2bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a72d2bd641dafa1ae9bcc323f0acd17761d21d19)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) | [Details](#user-content-3577f03000bf8c5ecd840f860e25d5b7-bcfe79db)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="3577f03000bf8c5ecd840f860e25d5b7-bcfe79db"></a>
### [concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md)
 - **Line 11, Column 1**: **[Warning-[h1-not-first](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-not-first?branch=main)]** `````Markdown content is not allowed before H1 'Computation of item insights'.`````
 - **Line 19, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Item insights in Microsoft 365') are not allowed. You can only have one top-level heading.`````
 - **Line 32, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Microsoft runs on trust') are not allowed. You can only have one top-level heading.`````
 - **Line 40, Column 1**: **[Warning-[multiple-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/multiple-h1s?branch=main)]** `````Multiple H1s(H1 'Disabling item insights') are not allowed. You can only have one top-level heading.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211335217009-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FH3u3iFKQM9KPscE8z3VHs7%2FxY2isAtZpXM947wZ27E%3D&st=2021-05-21T13%3A31%3A54Z&se=2021-06-21T13%3A36%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain err [...]

2021-05-21 13:44 UTC, opbld33 commented
Docs Build status updates of commit _[1bd3e4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bd3e4ad151cb446f6e194ba274b84e26d69611f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105211343329360-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZWuKZoTR8JaVfrTw5%2B8nALtaKQhcucubIiv3DfO19iM%3D&st=2021-05-21T13%3A39%3A44Z&se=2021-06-21T13%3A44%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 06:18 UTC, opbld34 commented
Docs Build status updates of commit _[1810edd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1810edd7b29cc070dab136b90e5200273594f39b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105280616303016-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MC%2FT5wgOj3nJyuBXcRHhhjiPrKzJBb8DQHxmo%2FgesB8%3D&st=2021-05-28T06%3A13%3A58Z&se=2021-06-28T06%3A18%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-28 07:43 UTC, angelgolfer-ms reviewed
@elmakhmu , I reviewed the topic item-insights-overview.md and left two comments. Please take a look.
Also, please remember when it's time to publish this PR, you should reduce the introductory section added by PR 12596 to the top of insights-customize-item-insights-privacy.md, which is also overview kind of content for item insights. This item-insights-overview.md topic should be the one that contains that kind of content.

2021-05-28 07:43 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +3. Experiences that show content trending around you is blocked for you and inaccessible for others, in places such as Delve and Outlook mobile’s **discover** section. The lack of the trending-insigh
Lines 55, 57, 59:
Should this be a bullet list instead of numbered list?
The biggest difference between the two is that for a numbered lists, we're implying an order for the numbered items to happen.
Please  confirm or change the lists into a bullet list if appropriate.

2021-05-28 07:43 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +
Line 62:
Do you mean this section: https://docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy#item-insights-privacy?
I rephrased the sentence to point to that particular section. Please correct if that's not what you mean.

2021-05-28 12:48 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +3. Experiences that show content trending around you is blocked for you and inaccessible for others, in places such as Delve and Outlook mobile’s **discover** section. The lack of the trending-insigh
well, to be honest I prefer more numbered list instead of bullet because it's easier to refer to the specific item "look [here ](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md#disable-or-re-enable-item-insights) 2 item"
but I can change, not a problem

2021-05-28 12:51 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +
@angelgolfer-ms I meant this paragraph https://docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy#behavior-changes-in-ui-and-apis 
But taking into account our conversation about admin topics, might be relevant to move ["Behavior changes in UI and APIs"](https://docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy#behavior-changes-in-ui-and-apis) into the overview topic https://docs.microsoft.com/en-us/graph/item-insights-overview?

2021-05-28 12:54 UTC, opbld30 commented
Docs Build status updates of commit _[342a080](https://github.com/microsoftgraph/microsoft-graph-docs/commits/342a0800e34fcfc1da0c5e23bb79428059c427f4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105281252022525-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AxuR%2Ffw1cGr9xCpwtxGfPWQryFbqQKpBazCCjfvtglA%3D&st=2021-05-28T12%3A49%3A31Z&se=2021-06-28T12%3A54%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-31 06:30 UTC, opbld31 commented
Docs Build status updates of commit _[24a3281](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24a32819b23d8316be81361f46fa4d8d1a4a29c0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105310628395117-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OHmrDgTRb9zEmPowG1pZyj7h8iEqKrdAS53nv4eRpQE%3D&st=2021-05-31T06%3A25%3A09Z&se=2021-07-01T06%3A30%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-31 06:31 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +# Overview of item insights
@angelgolfer-ms I've added "Item insights overview" under "People and workplace intelligence", but also dared to change from "insights" to "**item** insights" both for "insights overview" and "customize insights (preview)". I though that since there are some many _insights_ services in M365 would be nice to put into TOC that we're talking specifically about item insights.

2021-05-31 06:32 UTC, elmakhmu commented
@angelgolfer-ms I 've incorporated all you comments. Please, have a look if everything is ok

2021-05-31 08:14 UTC, opbld32 commented
Docs Build status updates of commit _[fee5124](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fee51242f1b2ac989e602b3be0ff463a4a1c5aa7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105310813207839-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LicStbemrj7iiBDYj%2Fcs4ow1XRIoy0towvM%2FCqHEVcM%3D&st=2021-05-31T08%3A09%3A44Z&se=2021-07-01T08%3A14%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-31 08:16 UTC, opbld31 commented
Docs Build status updates of commit _[387b283](https://github.com/microsoftgraph/microsoft-graph-docs/commits/387b283b313b8ba5267c434042313bc6957f95ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105310813403461-11518%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TdQB7%2BjqEzV1%2FG0X2OJPbbKXrfYh1NJq9pNSjMVRgMY%3D&st=2021-05-31T08%3A11%3A26Z&se=2021-07-01T08%3A16%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 16:04 UTC, lramosvea commented
@elmakhmu have you addressed all comments from Angela? If so, please add the "content review" label to this PR. Thanks.

2021-06-03 10:17 UTC, elmakhmu commented
not all of them, there are 2 open comments, required Angela's attention.

2021-06-09 14:52 UTC, opbld34 commented
Docs Build status updates of commit _[0cb2d87](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0cb2d87a339c575a0a843231452018958a22dbdb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-0ba90488)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-0ba90488"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3066, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3317, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-mam-conceptual.md'.`````
 - **Line 3645, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resourc [...]

2021-06-09 14:57 UTC, opbld32 commented
Docs Build status updates of commit _[54dc3c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/54dc3c6036b6f04ce8ad4dc4445da7b535ffb033)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-b44b6d9a)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-b44b6d9a"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3066, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3317, Column 17**: **[Warning-[file-not-found](htt [...]

2021-06-09 15:02 UTC, elmakhmu commented
@angelgolfer-ms  is it possible to change https://support.microsoft.com/en-us/office/why-does-the-discover-feature-not-show-on-my-search-page-3933448f-8b52-4e88-8d15-4ad07699b541 this doc within that PR somehow?

2021-06-22 07:05 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +# Overview of item insights
Oh that's fine, that's a good idea, also because under the same parent node "People and workplace intelligence" in the TOC, there are concept topics for other sets of API too.
Seems to me "Item insights overview" should come before the "Customize item insights privacy" in the TOC though?

2021-06-22 07:27 UTC, angelgolfer-ms commented on concepts/item-insights-overview.md
> +
Yeah, moving that section to the overview topic makes sense.

BTW, just noticed a grammar error in the 5th bullet point in that section:
"For a user who has disabled item insights, querying the trending and used resources in Microsoft Graph API return HTTP 403 Forbidden."

Can you change "return" to "returns" please, when you move that section over?

2021-06-22 08:57 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +
done

2021-06-22 09:00 UTC, opbld31 commented
Docs Build status updates of commit _[c9438b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9438b28f7642c515ce7ab484ebb08b98f9442e6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-ff2d291e)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-ff2d291e"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3066, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - **Line 3317, Column 17**: **[Warning-[file-not-found](htt [...]

2021-06-22 09:02 UTC, opbld34 commented
Docs Build status updates of commit _[20d4933](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20d49330093b1d8ddedb1af7041f93a59457fb98)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-404be571)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-404be571)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-404be571"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptual.md'.`````
 - **Line 3066, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-mgt-conceptual.md'.`````
 - * [...]

2021-06-22 09:11 UTC, opbld31 commented
Docs Build status updates of commit _[a51a412](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a51a4124c5264c848c596c7faebd33d9fae3e0cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-calls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/application-post-calls.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-calls?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-4d37fe3bbd7dab4ea10684785d4764da-a6781992)
[api-reference/beta/api/call-transfer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/call-transfer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/call-transfer?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-234a29cf329358729967c6889b75b879-a6781992)
[api-reference/beta/api/connectorgroup-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/connectorgroup-post-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/connectorgroup-post-members?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-2d8bc9068ae783a1c9d31c13eaa09d3c-a6781992)
[api-reference/beta/api/filter-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/filter-apply.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-apply?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-7d4abc8f6907681545f4bfbb647b6ba1-a6781992)
[api-reference/beta/api/filter-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/filter-clear.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/filter-clear?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-d7dcede355200062001d83fe70dcd47d-a6781992)
[api-reference/beta/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-597a77c0137be805312a999ab497bc9c-a6781992)
[api-reference/beta/api/printdocument-uploaddata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/printdocument-uploaddata.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-uploaddata?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-d75fb4b8ed74d1ff9ca1392d88183bff-a6781992)
[api-reference/beta/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/printer-restorefactorydefaults.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-restorefactorydefaults?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-e4af142571b35850edb64b0626a913ba-a6781992)
[api-reference/beta/api/printershare-post-allowedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/printershare-post-allowedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-allowedgroups?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-990184154b9286886f318873b15f00de-a6781992)
[api-reference/beta/api/printershare-post-allowedusers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/printershare-post-allowedusers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-post-allowedusers?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-06137ea92785ffc9e0665631edad9a5a-a6781992)
[api-reference/beta/api/printjob-cancel.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/printjob-cancel.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-cancel?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-d31001825558b6df562feeea7182b7c3-a6781992)
[api-reference/beta/api/profilephoto-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/profilephoto-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/profilephoto-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-61deddea09f79f7372efdf04fd701ab5-a6781992)
[api-reference/beta/api/securescorecontrolprofiles-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/securescorecontrolprofiles-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/securescorecontrolprofiles-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-c1394b85d8468b9b6388c8b2948251e8-a6781992)
[api-reference/beta/resources/accessreviewnotificationrecipientscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/accessreviewnotificationrecipientscope.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewnotificationrecipientscope?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-54974c7a126366e7915039e1a4dc49ee-a6781992)
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-a6781992)
[api-reference/beta/resources/rbacapplicationmultiple.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/rbacapplicationmultiple.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplicationmultiple?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-a7ac7d293ea34d4691824a0886205d18-a6781992)
[api-reference/beta/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-f81f934e67f6ce3812d54d8f97883c6d-a6781992)
[api-reference/v1.0/api/administrativeunit-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/api/administrativeunit-list-members.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/administrativeunit-list-members?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-e573695f8d1f418fbec7a768a1f5bd0a-a6781992)
[api-reference/v1.0/api/application-delete-owners.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/api/application-delete-owners.md) | :warning:Warning | [View](https:/ [...]

2021-06-22 09:21 UTC, opbld31 commented
Docs Build status updates of commit _[c74b34b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c74b34b6d86984a45ff61bf993808881d34b46ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/printerstatus.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) | [Details](#user-content-a5de560d9c6f4e2a27499d7f0e61a89a-8ca30f20)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-8ca30f20)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-8ca30f20)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/resources/printerstatus.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printerstatus?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="a5de560d9c6f4e2a27499d7f0e61a89a-8ca30f20"></a>
### [api-reference/beta/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/printerstatus.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/co [...]

2021-06-22 10:01 UTC, opbld34 commented
Docs Build status updates of commit _[d068aa0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d068aa07208c2afc4fa7e05ecd68f6d2cd76e858)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-15c1486e)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-15c1486e)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-15c1486e"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 1 [...]

2021-06-22 10:04 UTC, opbld34 commented
Docs Build status updates of commit _[c6af3e2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c6af3e287de19e78b5253d3044df2a715a0bdb3f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-1dbaffb3)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-1dbaffb3)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-1dbaffb3"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptu [...]

2021-06-22 10:17 UTC, elmakhmu commented on concepts/item-insights-overview.md
> +# Overview of item insights
done

2021-06-22 10:18 UTC, opbld32 commented
Docs Build status updates of commit _[e440ed4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e440ed47698a38ec95ce12eb33b3e606360c0c32)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-f6dbceb7)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-f6dbceb7)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-f6dbceb7"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptu [...]

2021-06-23 20:07 UTC, opbld31 commented
Docs Build status updates of commit _[2ca8524](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ca8524dcc8eca91593460ea5e9d6f08d2d30961)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-61d14262)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-61d14262)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-61d14262"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-enrollment-conceptual.md'.`````
 - **Line 2169, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-device-cfg-conceptu [...]

2021-06-23 20:34 UTC, opbld32 commented
Docs Build status updates of commit _[f6befdf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6befdf2c365a268a9236a94aae15fea739c4d79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-47923547)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-47923547)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/social-intel-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/social-intel-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-47923547"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found? [...]

2021-06-23 20:36 UTC, opbld34 commented
Docs Build status updates of commit _[ba9bf48](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba9bf489e313bb6e918cc5da6c1db5bdffaa2744)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-843e95b5)
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) | [Details](#user-content-25f5577e9853acc2648990df5c8a6d5c-843e95b5)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/social-intel-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/social-intel-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-843e95b5"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found? [...]

2021-06-23 20:50 UTC, opbld32 commented
Docs Build status updates of commit _[9ce8eee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ce8eeec4844a8f14466b6fc3cebfd7eb5965288)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/1.0.json?view=graph-rest-1.0&branch=pr-en-us-11518) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-4a5309d2)
[api-reference/beta/api/userinsightssettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/userinsightssettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/userinsightssettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/api/usersettings-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/api/usersettings-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/usersettings-update?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/iteminsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/iteminsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/iteminsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/userinsightssettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/userinsightssettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userinsightssettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/resources/usersettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/resources/usersettings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/usersettings?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userinsightssettings-get?view=graph-rest-beta&branch=pr-en-us-11518) (graph-rest-beta) |
[changelog/Microsoft.OfficeGraph.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/changelog/Microsoft.OfficeGraph.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11518) |
[concepts/images/Recent-files-in-card-based-interfaces.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recent-files-in-card-based-interfaces.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/Recommended-Office-com.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/Recommended-Office-com.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-delve.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-delve.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-office.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-office.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/disabled-item-insights-in-persona-card.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/disabled-item-insights-in-persona-card.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/discover-Delve-OutlookMobile.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/discover-Delve-OutlookMobile.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/images/item-insights-toggle-in-MyAccount.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/images/item-insights-toggle-in-MyAccount.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/insights-customize-item-insights-privacy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/insights-customize-item-insights-privacy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |
[concepts/item-insights-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/item-insights-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/item-insights-overview?branch=pr-en-us-11518) |
[concepts/social-intel-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/social-intel-concept-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/social-intel-concept-overview?branch=pr-en-us-11518) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/insights-customize-item-insights-privacy?branch=pr-en-us-11518) |

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-4a5309d2"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/elmakhmu-patch-7/api-reference/v1.0/toc.yml)
 - **Line 1460, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-graph-overview.md'.`````
 - **Line 1464, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-app-conceptual.md'.`````
 - **Line 2070, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intune-company-conceptual.md'.`````
 - **Line 2119, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/intun [...]

2021-06-23 20:56 UTC, merged