Universal Print Graph v1.0 documentation
microsoftgraph/microsoft-graph-docs pull request #11544
Opened 2021-02-05 17:41 UTC by nilakhan

2021-02-05 17:42 UTC, opbld31 commented
Docs Build status updates of commit _[219d950](https://github.com/microsoftgraph/microsoft-graph-docs/commits/219d950689c6b09441027b7629a755492d54b4ad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-1370313a)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-1370313a)
[api-reference/v1.0/api/printjob-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printjob-get.md) | :warning:Warning | | [Details](#user-content-f0b25621-1370313a)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | | [Details](#user-content-7df83b98-1370313a)
[api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md) | :warning:Warning | | [Details](#user-content-b86266e7-1370313a)
[api-reference/v1.0/resources/print.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/print.md) | :warning:Warning | | [Details](#user-content-190f7c59-1370313a)
[api-reference/v1.0/resources/printcertificatesigningrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printcertificatesigningrequest.md) | :warning:Warning | | [Details](#user-content-7df7bc1c-1370313a)
[api-reference/v1.0/resources/printconnector.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printconnector.md) | :warning:Warning | | [Details](#user-content-d205963a-1370313a)
[api-reference/v1.0/resources/printdocument.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printdocument.md) | :warning:Warning | | [Details](#user-content-cef02361-1370313a)
[api-reference/v1.0/resources/printdocumentuploadproperties.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printdocumentuploadproperties.md) | :warning:Warning | | [Details](#user-content-c263f645-1370313a)
[api-reference/v1.0/resources/printercapabilities.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printercapabilities.md) | :warning:Warning | | [Details](#user-content-575997d4-1370313a)
[api-reference/v1.0/resources/printercreateoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printercreateoperation.md) | :warning:Warning | | [Details](#user-content-5fce93e5-1370313a)
[api-reference/v1.0/resources/printerdefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printerdefaults.md) | :warning:Warning | | [Details](#user-content-13aae3f0-1370313a)
[api-reference/v1.0/resources/printerlocation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printerlocation.md) | :warning:Warning | | [Details](#user-content-4124eaf7-1370313a)
[api-reference/v1.0/resources/printershare.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printershare.md) | :warning:Warning | | [Details](#user-content-2f188ef5-1370313a)
[api-reference/v1.0/resources/printerstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printerstatus.md) | :warning:Warning | | [Details](#user-content-59befd52-1370313a)
[api-reference/v1.0/resources/printjobconfiguration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printjobconfiguration.md) | :warning:Warning | | [Details](#user-content-4b9ad442-1370313a)
[api-reference/v1.0/resources/printjobstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printjobstatus.md) | :warning:Warning | | [Details](#user-content-cd2a0b94-1370313a)
[api-reference/v1.0/resources/printmargin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printmargin.md) | :warning:Warning | | [Details](#user-content-f5c7988e-1370313a)
[api-reference/v1.0/resources/printoperation.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printoperation.md) | :warning:Warning | | [Details](#user-content-205a3029-1370313a)
[api-reference/v1.0/resources/printoperationstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printoperationstatus.md) | :warning:Warning | | [Details](#user-content-17ff4015-1370313a)
[api-reference/v1.0/resources/printservice.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printservice.md) | :warning:Warning | | [Details](#user-content-a991d2b4-1370313a)
[api-reference/v1.0/resources/printserviceendpoint.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printserviceendpoint.md) | :warning:Warning | | [Details](#user-content-64a7f843-1370313a)
[api-reference/v1.0/resources/printsettings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printsettings.md) | :warning:Warning | | [Details](#user-content-94c72b68-1370313a)
[api-reference/v1.0/resources/printtask.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printtask.md) | :warning:Warning | | [Details](#user-content-66e811f7-1370313a)
[api-reference/v1.0/resources/printtaskstatus.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printtaskstatus.md) | :warning:Warning | | [Details](#user-content-70eb24f8-1370313a)
[api-reference/v1.0/resources/printtasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printtasktrigger.md) | :warning:Warning | | [Details](#user-content-f12cbc2f-1370313a)
[api-reference/v1.0/resources/printusagebyprinter.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printusagebyprinter.md) | :warning:Warning | | [Details](#user-content-a327fcac-1370313a)
[api-reference/v1.0/resources/printusagebyuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/printusagebyuser.md) | :warning:Warning | | [Details](#user-content-dab707b4-1370313a)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print [...]

2021-02-17 04:04 UTC, opbld32 commented
Docs Build status updates of commit _[6650a08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6650a084ae1c5f99896b377dbce8c3ae63f90116)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-ab6912ac)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-ab6912ac)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-ab6912ac)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-ab6912ac)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-ab6912ac)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-ab6912ac)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-ab6912ac)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-ab6912ac)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-ab6912ac)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-ab6912ac)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-ab6912ac)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-ab6912ac)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-ab6912ac)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-ab6912ac)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-ab6912ac)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-ab6912ac)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-ab6912ac)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-ab6912ac)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-ab6912ac)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-ab6912ac)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-ab6912ac)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-ab6912ac)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-ab6912ac)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-ab6912ac)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-ab6912ac)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-ab6912ac)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-ab6912ac)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-ab6912ac)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-ab6912ac)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 00:37 UTC, opbld31 commented
Docs Build status updates of commit _[3f61065](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3f61065e4d9c302a80704cc43a159338012904bb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-6835a029)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-6835a029)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-6835a029)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-6835a029)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-6835a029)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-6835a029)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-6835a029)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-6835a029)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-6835a029)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-6835a029)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-6835a029)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-6835a029)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-6835a029)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-6835a029)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-6835a029)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-6835a029)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-6835a029)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-6835a029)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-6835a029)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-6835a029)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-6835a029)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-6835a029)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-6835a029)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-6835a029)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-6835a029)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-6835a029)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-6835a029)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-6835a029)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-6835a029)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 00:58 UTC, opbld32 commented
Docs Build status updates of commit _[62fd648](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62fd64835a2d4ae5ffbb6bce710b6d432911f186)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-436a9298)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-436a9298)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-436a9298)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-436a9298)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-436a9298)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-436a9298)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-436a9298)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-436a9298)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-436a9298)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-436a9298)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-436a9298)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-436a9298)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-436a9298)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-436a9298)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-436a9298)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-436a9298)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-436a9298)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-436a9298)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-436a9298)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-436a9298)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-436a9298)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-436a9298)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-436a9298)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-436a9298)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-436a9298)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-436a9298)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-436a9298)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-436a9298)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-436a9298)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 01:11 UTC, opbld30 commented
Docs Build status updates of commit _[9d44724](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d44724ad62338d055ba7c8104f799dd68c60dfb)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-99dc5f0c)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-99dc5f0c)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-99dc5f0c)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-99dc5f0c)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-99dc5f0c)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-99dc5f0c)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-99dc5f0c)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-99dc5f0c)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-99dc5f0c)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-99dc5f0c)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-99dc5f0c)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-99dc5f0c)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-99dc5f0c)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-99dc5f0c)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-99dc5f0c)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-99dc5f0c)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-99dc5f0c)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-99dc5f0c)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-99dc5f0c)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-99dc5f0c)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-99dc5f0c)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-99dc5f0c)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-99dc5f0c)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-99dc5f0c)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-99dc5f0c)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-99dc5f0c)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-99dc5f0c)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-99dc5f0c)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-99dc5f0c)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 01:25 UTC, opbld33 commented
Docs Build status updates of commit _[762e019](https://github.com/microsoftgraph/microsoft-graph-docs/commits/762e0196b2d6a197945a0253246a4feb12ffdb38)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-dd63def2)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-dd63def2)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-dd63def2)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-dd63def2)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-dd63def2)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-dd63def2)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-dd63def2)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-dd63def2)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-dd63def2)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-dd63def2)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-dd63def2)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-dd63def2)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-dd63def2)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-dd63def2)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-dd63def2)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-dd63def2)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-dd63def2)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-dd63def2)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-dd63def2)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-dd63def2)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-dd63def2)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-dd63def2)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-dd63def2)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-dd63def2)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-dd63def2)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-dd63def2)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-dd63def2)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-dd63def2)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-dd63def2)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 01:35 UTC, opbld33 commented
Docs Build status updates of commit _[b52b21e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b52b21e01395a07939edc29333396129db8a31c6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-3274c65a)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-3274c65a)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-3274c65a)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-3274c65a)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-3274c65a)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-3274c65a)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-3274c65a)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-3274c65a)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-3274c65a)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-3274c65a)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-3274c65a)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-3274c65a)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-3274c65a)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-3274c65a)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-3274c65a)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-3274c65a)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-3274c65a)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-3274c65a)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-3274c65a)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-3274c65a)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-3274c65a)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-3274c65a)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-3274c65a)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-3274c65a)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-3274c65a)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-3274c65a)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-3274c65a)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-3274c65a)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-3274c65a)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 02:10 UTC, opbld32 commented
Docs Build status updates of commit _[1574245](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1574245627ccffadfc21f315d2a69e1141471d17)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-e839201f)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-e839201f)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-e839201f)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-e839201f)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-e839201f)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-e839201f)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-e839201f)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-e839201f)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-e839201f)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-e839201f)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-e839201f)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-e839201f)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-e839201f)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-e839201f)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-e839201f)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-e839201f)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-e839201f)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-e839201f)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-e839201f)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-e839201f)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-e839201f)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-e839201f)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-e839201f)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-e839201f)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-e839201f)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-e839201f)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-e839201f)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-e839201f)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-e839201f)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 02:24 UTC, opbld33 commented
Docs Build status updates of commit _[90ce2a9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90ce2a90eb46ba0ea7cab1d1280035732323096a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-94374490)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-94374490)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-94374490)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-94374490)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-94374490)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-94374490)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-94374490)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-94374490)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-94374490)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-94374490)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-94374490)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-94374490)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-94374490)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-94374490)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-94374490)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-94374490)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-94374490)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-94374490)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-94374490)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-94374490)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-94374490)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-94374490)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-94374490)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-94374490)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-94374490)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-94374490)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-94374490)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-94374490)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-94374490)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 02:33 UTC, opbld32 commented
Docs Build status updates of commit _[191400e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/191400e77cb6639c8940f7ef90e2b366f915d675)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-3d28b883)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-3d28b883)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-3d28b883)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-3d28b883)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-3d28b883)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-3d28b883)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-3d28b883)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-3d28b883)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-3d28b883)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-3d28b883)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-3d28b883)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-3d28b883)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-3d28b883)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-3d28b883)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-3d28b883)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-3d28b883)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-3d28b883)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-3d28b883)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-3d28b883)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-3d28b883)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-3d28b883)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-3d28b883)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-3d28b883)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-3d28b883)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-3d28b883)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-3d28b883)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-3d28b883)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-3d28b883)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-3d28b883)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 02:37 UTC, opbld31 commented
Docs Build status updates of commit _[6aa755c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6aa755c3fe99438c5941d1d131ebc13e50acdedf)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-4d28c71b)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-4d28c71b)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-4d28c71b)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-4d28c71b)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-4d28c71b)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-4d28c71b)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-4d28c71b)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-4d28c71b)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-4d28c71b)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-4d28c71b)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-4d28c71b)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-4d28c71b)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-4d28c71b)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-4d28c71b)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-4d28c71b)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-4d28c71b)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-4d28c71b)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-4d28c71b)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-4d28c71b)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-4d28c71b)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-4d28c71b)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-4d28c71b)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-4d28c71b)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-4d28c71b)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-4d28c71b)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-4d28c71b)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-4d28c71b)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-4d28c71b)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-4d28c71b)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 02:39 UTC, opbld31 commented
Docs Build status updates of commit _[2351df4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2351df4b196b830b8175b387b78ffb4cdc26a6ba)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-65f2194a)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-65f2194a)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-65f2194a)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-65f2194a)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-65f2194a)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-65f2194a)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-65f2194a)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-65f2194a)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-65f2194a)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-65f2194a)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-65f2194a)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-65f2194a)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-65f2194a)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-65f2194a)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-65f2194a)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-65f2194a)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-65f2194a)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-65f2194a)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-65f2194a)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-65f2194a)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-65f2194a)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-65f2194a)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-65f2194a)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-65f2194a)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-65f2194a)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-65f2194a)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-65f2194a)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-65f2194a)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-65f2194a)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 02:46 UTC, opbld32 commented
Docs Build status updates of commit _[904d600](https://github.com/microsoftgraph/microsoft-graph-docs/commits/904d600136c79850e458fad49bd57af6fa0e6f96)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/toc.yml) | :x:Error | | [Details](#user-content-77cfd98e-a0f8e037)
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | | [Details](#user-content-b6b8c1e1-a0f8e037)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | | [Details](#user-content-697cb69c-a0f8e037)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | | [Details](#user-content-4a47b586-a0f8e037)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | | [Details](#user-content-5ae3cf32-a0f8e037)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | | [Details](#user-content-644db80c-a0f8e037)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | | [Details](#user-content-1246a3d3-a0f8e037)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-02068607-a0f8e037)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | | [Details](#user-content-93df513d-a0f8e037)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-a0f8e037)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | | [Details](#user-content-08a07bd1-a0f8e037)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | | [Details](#user-content-37811e4f-a0f8e037)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | | [Details](#user-content-92ea8203-a0f8e037)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | | [Details](#user-content-ba5867a2-a0f8e037)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | | [Details](#user-content-f53e70ca-a0f8e037)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | | [Details](#user-content-6befe2cc-a0f8e037)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | | [Details](#user-content-844b6af6-a0f8e037)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | | [Details](#user-content-0ee8e622-a0f8e037)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | | [Details](#user-content-787a42f5-a0f8e037)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | | [Details](#user-content-a61a05de-a0f8e037)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-get.md) | :warning:Warning | | [Details](#user-content-86dbcaa9-a0f8e037)
[api-reference/v1.0/api/printer-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-connectors.md) | :warning:Warning | | [Details](#user-content-81394226-a0f8e037)
[api-reference/v1.0/api/printer-list-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-jobs.md) | :warning:Warning | | [Details](#user-content-1694a057-a0f8e037)
[api-reference/v1.0/api/printer-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-shares.md) | :warning:Warning | | [Details](#user-content-dcbe4e06-a0f8e037)
[api-reference/v1.0/api/printer-list-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-list-tasktriggers.md) | :warning:Warning | | [Details](#user-content-12fec215-a0f8e037)
[api-reference/v1.0/api/printer-post-jobs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-jobs.md) | :warning:Warning | | [Details](#user-content-9a18232a-a0f8e037)
[api-reference/v1.0/api/printer-post-tasktriggers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-post-tasktriggers.md) | :warning:Warning | | [Details](#user-content-09336b0d-a0f8e037)
[api-reference/v1.0/api/printer-restorefactorydefaults.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-restorefactorydefaults.md) | :warning:Warning | | [Details](#user-content-f2603bf9-a0f8e037)
[api-reference/v1.0/api/printer-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-update.md) | :warning:Warning | | [Details](#user-content-b96e665c-a0f8e037)
[api-reference/v1.0/api/printershare-delete-allowedgroup.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/ap [...]

2021-02-18 18:36 UTC, jahsu-MSFT commented on api-reference/v1.0/api/print-post-shares.md
> +|allowAllUsers|Boolean|	If true, all users and groups will be granted access to this printer share. This supersedes the allow lists defined by the allowedUsers and allowedGroups navigation properties
Format seems to be off here

2021-02-18 18:42 UTC, jahsu-MSFT commented on api-reference/v1.0/api/print-get-settings.md
> +GET https://graph.microsoft.com/beta/print/settings
v1.0?

2021-02-18 18:42 UTC, jahsu-MSFT commented on api-reference/v1.0/api/printershare-list-allowedgroups.md
> +  "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(microsoft.graph.group)",
v1.0?

2021-02-18 18:42 UTC, jahsu-MSFT commented on api-reference/v1.0/api/printershare-list-allowedusers.md
> +  "@odata.context": "https://graph.microsoft.com/beta/$metadata#Collection(microsoft.graph.user)",
v1.0?

2021-02-23 20:58 UTC, Lauragra commented on api-reference/v1.0/api/print-delete-taskdefinition.md
> +# [HTTP](#tab/http)
Global: Please remove this HTTP H1 from all topics. This will get added back when the snippets are generated for the v1.0 examples.

2021-02-24 02:23 UTC, jahsu-MSFT approved these changes

2021-02-24 02:37 UTC, nilakhan commented on api-reference/v1.0/api/print-delete-taskdefinition.md
> +# [HTTP](#tab/http)
Removed. thanks

2021-02-26 22:17 UTC, Lauragra commented on api-reference/v1.0/api/printer-get.md
> +The following is an example of the response to a request that includes the `$select=id,displayName,capabilities` parameter.
Technically we should have a second example in this topic that shows the request with the parameter, and the response, rather than showing two response examples for the same request. So you would have two H3s, "Example 1: Get a printer", and "Example 2: Get a printer and its capabilities", and Request and Response H4s for each.

2021-02-26 23:01 UTC, Lauragra commented on api-reference/v1.0/api/printershare-get.md
> +The following is an example of the response to a request that includes the `$select=id,displayName,capabilities` parameter.
Same comment here; ideally you can make this two separate request/response examples.

2021-02-27 08:42 UTC, angelgolfer-ms commented on concepts/universal-print-concept-overview.md
> +1. [Create a print job](/graph/api/printershare-post-jobs?view=graph-rest-1.0) and store the resulting document ID.
GLOBAL:
Please make sure if your links specify view=graph-rest-beta, include the preserve-view=true parameter, or else down the road you'll get into problems.
If you're changing the links to point to v1, you actually don't need to specify view=graph-rest-1.0, as a link without the view parameter would default to v1 anyway.
On the other hand, if you choose to explicitly specify view=graph-rest-1.0, then you should include the preserve-view=true parameter.
More info: https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master#links-to-specific-versions

2021-02-27 08:53 UTC, angelgolfer-ms requested changes
Thanks for the PR. While Laura remains your main reviewer for this PR, please see the following comments from me:
(a) Please update toc.yml in the concepts folder: 
Line 187: remove "(preview)"
Line 188: remove the expanded: true line. Expanding the parent folder "Devices and apps" is meant to be a limited time only for initial discoverability; we shouldn't have been expanding the "Cloud printing" subfolder itself by default, this has been an oversight :-(

(b) Please update overview-major-services.md:
Line 83 - remove "(preview") in the first table column.

(c) One global comment inline about links that include the view parameter.

Thanks.

2021-03-01 04:27 UTC, Lauragra commented on changelog/Microsoft.PrintService.json
> +          "Description": "Added the [printerBase](https://docs.microsoft.com/en-us/graph/api/resources/printerBase?view=graph-rest-1.0) resource type",
These descriptions should all technically end in periods. There was a bug in the stub generator tool that has since been fixed to add periods to the descriptions. Unfortunately this is a long list of entries so I leave it to you to fix if you have the time. :)

2021-03-02 23:09 UTC, nilakhan commented on concepts/universal-print-concept-overview.md
> +1. [Create a print job](/graph/api/printershare-post-jobs?view=graph-rest-1.0) and store the resulting document ID.
Thanks. fixed this.

2021-03-02 23:10 UTC, nilakhan commented
> Thanks for the PR. While Laura remains your main reviewer for this PR, please see the following comments from me:
> (a) Please update toc.yml in the concepts folder:
> Line 187: remove "(preview)"
> Line 188: remove the expanded: true line. Expanding the parent folder "Devices and apps" is meant to be a limited time only for initial discoverability; we shouldn't have been expanding the "Cloud printing" subfolder itself by default, this has been an oversight :-(
> 
> (b) Please update overview-major-services.md:
> Line 83 - remove "(preview") in the first table column.
> 
> (c) One global comment inline about links that include the view parameter.
> 
> Thanks.

[nilakhan] Thanks. I have fixed these comments.

2021-03-02 23:10 UTC, nilakhan commented on changelog/Microsoft.PrintService.json
> +          "Description": "Added the [printerBase](https://docs.microsoft.com/en-us/graph/api/resources/printerBase?view=graph-rest-1.0) resource type",
Fixed. Thanks.

2021-03-02 23:12 UTC, nilakhan commented on concepts/universal-print-concept-overview.md
> +1. [Create a print job](/graph/api/printershare-post-jobs?view=graph-rest-1.0) and store the resulting document ID.
Fixed.

2021-03-02 23:13 UTC, nilakhan commented on changelog/Microsoft.PrintService.json
> +          "Description": "Added the [printerBase](https://docs.microsoft.com/en-us/graph/api/resources/printerBase?view=graph-rest-1.0) resource type",
Fixed.

2021-03-03 02:19 UTC, nilakhan commented on api-reference/v1.0/api/printershare-get.md
> +The following is an example of the response to a request that includes the `$select=id,displayName,capabilities` parameter.
Fixed.

2021-03-03 02:19 UTC, nilakhan commented on api-reference/v1.0/api/printer-get.md
> +The following is an example of the response to a request that includes the `$select=id,displayName,capabilities` parameter.
fixed.

2021-03-04 12:28 UTC, opbld31 commented
Docs Build status updates of commit _[7b97bbd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7b97bbd67919af2df41b7cf80bd5a0037f3568be)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b093b81e)

<a id="b093b81e"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103041228186055-11544%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ye6Bhrq3S25%2FDsxSXdjz7iBlRqR97zbGVqF90KFWfU4%3D&st=2021-03-04T12%3A23%3A39Z&se=2021-04-04T12%3A28%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 12:29 UTC, opbld34 commented
Docs Build status updates of commit _[8fa8f4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fa8f4a9ccb66753f1ebe2d3d482a68d28654cf3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa0f4ccf)

<a id="aa0f4ccf"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103041229237843-11544%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Oh4KQMwuC0B9b6lR%2FzULygJ%2FWug7A3TFxDtMOJYCZFY%3D&st=2021-03-04T12%3A24%3A42Z&se=2021-04-04T12%3A29%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 13:04 UTC, opbld33 commented
Docs Build status updates of commit _[de1fc11](https://github.com/microsoftgraph/microsoft-graph-docs/commits/de1fc117a74273dbd0307ec3827e03dfaede9bf6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b6b8c1e1-22bf10ea)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-697cb69c-22bf10ea)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-4a47b586-22bf10ea)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-5ae3cf32-22bf10ea)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-644db80c-22bf10ea)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-1246a3d3-22bf10ea)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-02068607-22bf10ea)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-93df513d-22bf10ea)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-22bf10ea)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-08a07bd1-22bf10ea)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-37811e4f-22bf10ea)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-92ea8203-22bf10ea)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-ba5867a2-22bf10ea)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f53e70ca-22bf10ea)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-6befe2cc-22bf10ea)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-844b6af6-22bf10ea)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-create?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-0ee8e622-22bf10ea)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete-tasktrigger?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-787a42f5-22bf10ea)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-a61a05de-22bf10ea)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan [...]

2021-03-04 13:08 UTC, opbld32 commented
Docs Build status updates of commit _[22b4f9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22b4f9a66ab85116bd58ac4256b5d7ebae6c3b18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b6b8c1e1-364f4bd1)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-697cb69c-364f4bd1)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-4a47b586-364f4bd1)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-5ae3cf32-364f4bd1)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-644db80c-364f4bd1)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-1246a3d3-364f4bd1)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-02068607-364f4bd1)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-93df513d-364f4bd1)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-364f4bd1)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-08a07bd1-364f4bd1)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-37811e4f-364f4bd1)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-92ea8203-364f4bd1)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-ba5867a2-364f4bd1)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f53e70ca-364f4bd1)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-6befe2cc-364f4bd1)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-844b6af6-364f4bd1)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-create?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-0ee8e622-364f4bd1)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete-tasktrigger?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-787a42f5-364f4bd1)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-a61a05de-364f4bd1)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan [...]

2021-03-05 03:15 UTC, opbld30 commented
Docs Build status updates of commit _[02a0733](https://github.com/microsoftgraph/microsoft-graph-docs/commits/02a073311466874de3f710fe09b829dd3f90094a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b6b8c1e1-2ca51a0a)
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-697cb69c-2ca51a0a)
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-4a47b586-2ca51a0a)
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-5ae3cf32-2ca51a0a)
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-644db80c-2ca51a0a)
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-1246a3d3-2ca51a0a)
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-02068607-2ca51a0a)
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-93df513d-2ca51a0a)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-2ca51a0a)
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-08a07bd1-2ca51a0a)
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-37811e4f-2ca51a0a)
[api-reference/v1.0/api/printconnector-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-92ea8203-2ca51a0a)
[api-reference/v1.0/api/printconnector-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-ba5867a2-2ca51a0a)
[api-reference/v1.0/api/printconnector-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printconnector-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-update?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f53e70ca-2ca51a0a)
[api-reference/v1.0/api/printdocument-createuploadsession.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-createuploadsession.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-createuploadsession?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-6befe2cc-2ca51a0a)
[api-reference/v1.0/api/printdocument-get-file.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printdocument-get-file.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printdocument-get-file?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-844b6af6-2ca51a0a)
[api-reference/v1.0/api/printer-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-create?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-0ee8e622-2ca51a0a)
[api-reference/v1.0/api/printer-delete-tasktrigger.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete-tasktrigger.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete-tasktrigger?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-787a42f5-2ca51a0a)
[api-reference/v1.0/api/printer-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printer-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printer-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-a61a05de-2ca51a0a)
[api-reference/v1.0/api/printer-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan [...]

2021-03-05 22:34 UTC, opbld33 commented
Docs Build status updates of commit _[45aa444](https://github.com/microsoftgraph/microsoft-graph-docs/commits/45aa4447d9ed4404b5a04ebfd20d32d9052fb0b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-ace2d7b2)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-7df83b98-ace2d7b2)
[api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/integerrange?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b86266e7-ace2d7b2)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544) | [Details](#user-content-2ec827c4-ace2d7b2)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-11544) | [Details](#user-content-3e780b05-ace2d7b2)
[api-reference/v1.0/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printershare-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f607c0e0-ace2d7b2)
[api-reference/v1.0/api/printtaskdefinition-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printtaskdefinition-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printtaskdefinition-list-tasks?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-cf435376-ace2d7b2)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-11544) | [Details](#user-content-f985040c-ace2d7b2)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11544) | [Details](#user-content-c447f2b8-ace2d7b2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11544) (graph-rest-beta) |
[api-reference/includes/cloudprinting-pricing-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/includes/cloudprinting-pricing-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printusagebyuser?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-taskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.mic [...]

2021-03-05 22:51 UTC, opbld30 commented
Docs Build status updates of commit _[3ceba63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ceba6339031aaeab531ceaf4a8c68ccaa2faa27)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-concept-overview.md) | :x:Error | | [Details](#user-content-2ec827c4-8ca75074)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/upload-data-to-upload-session.md) | :x:Error | | [Details](#user-content-3e780b05-8ca75074)
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | | [Details](#user-content-2da05e49-8ca75074)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | | [Details](#user-content-7df83b98-8ca75074)
[api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md) | :warning:Warning | | [Details](#user-content-b86266e7-8ca75074)
[api-reference/v1.0/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printershare-get.md) | :bulb:Suggestion | | [Details](#user-content-f607c0e0-8ca75074)
[api-reference/v1.0/api/printtaskdefinition-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printtaskdefinition-list-tasks.md) | :bulb:Suggestion | | [Details](#user-content-cf435376-8ca75074)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/overview-major-services.md) | :bulb:Suggestion | | [Details](#user-content-f985040c-8ca75074)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | | [Details](#user-content-c447f2b8-8ca75074)

<a id="2ec827c4-8ca75074"></a>
### [concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-concept-overview.md)
 - **Line 12, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../../includes/cloudprinting-pricing-disclaimer.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Universal Print is a modern print solution that organizations can use to manage their print infrastructure through cloud services from Microsoft.' is duplicated in 'universal-print-concept-overview.md(3,14)', 'upload-data-to-upload-session.md(3,14)'.`````

<a id="3e780b05-8ca75074"></a>
### [concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/upload-data-to-upload-session.md)
 - **Line 12, Column 1**: **[Error-[include-not-found](https://review.docs.microsoft.com/en-us/help/contribute/includes-best-practices?branch=master)]** `````Invalid include link: '../../includes/cloudprinting-pricing-disclaimer.md'.`````
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Universal Print is a modern print solution that organizations can use to manage their print infrastructure through cloud services from Microsoft.' is duplicated in 'universal-print-concept-overview.md(3,14)', 'upload-data-to-upload-session.md(3,14)'.`````

<a id="2da05e49-8ca75074"></a>
### [api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="7df83b98-8ca75074"></a>
### [api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="b86266e7-8ca75074"></a>
### [api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'universal-print'.`````

<a id="f607c0e0-8ca75074"></a>
### [api-reference/v1.0/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printershare-get.md)
 - **Line 58, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Response''. Each second level heading (H2) in an article must be unique.`````
 - **Line 62, Column 1**: **[Suggestion-[duplicate-headings](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-headings?branch=main)]** `````Duplicate heading: 'H2 'Response''. Each second level heading (H2) in an article must be unique.`````

<a id="cf435376-8ca75074"></a>
### [api-reference/v1.0/api/printtaskdefinition-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printtaskdefinition-list-tasks.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List tasks - Microsoft Graph v1.0' is duplicated in: 'v1.0/api/plannerbucket-list-tasks.md(2,8), v1.0/api/planner-list-tasks.md(2,8), v1.0/api/plannerplan-list-tasks.md(2,8), v1.0/api/planneruser-list-tasks.md(2,8), v1.0/api/printtaskdefinition-list-tasks.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List tasks' is duplicated with other articles: 'v1.0/api/plannerbucket-list-tasks.md(10,1), v1.0/api/planner-list-tasks.md(10,1), v1.0/api/plannerplan-list-tasks.md(10,1), v1.0/api/ [...]

2021-03-05 23:02 UTC, opbld30 commented
Docs Build status updates of commit _[6141d75](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6141d75997e704234aed01e2c835c52bb75746b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-1890f9f8)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-7df83b98-1890f9f8)
[api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/integerrange?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b86266e7-1890f9f8)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544) | [Details](#user-content-2ec827c4-1890f9f8)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-11544) | [Details](#user-content-3e780b05-1890f9f8)
[api-reference/v1.0/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printershare-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f607c0e0-1890f9f8)
[api-reference/v1.0/api/printtaskdefinition-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printtaskdefinition-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printtaskdefinition-list-tasks?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-cf435376-1890f9f8)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-11544) | [Details](#user-content-f985040c-1890f9f8)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11544) | [Details](#user-content-c447f2b8-1890f9f8)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11544) (graph-rest-beta) |
[api-reference/includes/cloudprinting-pricing-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/includes/cloudprinting-pricing-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-refe [...]

2021-03-06 01:25 UTC, angelgolfer-ms commented on concepts/toc.yml
> -        expanded: true
Per my comment:
"...Line 188: remove the expanded: true line. Expanding the parent folder "Devices and apps" is meant to be a limited time only for initial discoverability; we shouldn't have been expanding the "Cloud printing" subfolder itself by default, this has been an oversight :-("
Sorry it was not clear. There were 2 parts to that comment. The first part - expanding the "Devices and apps" node by default, even though it is meant to be for a limited time, as we reach this major milestone of GA, we can keep this for perhaps another 3 months to give cloud printing the initial exposure as a GA'd service. The second part of the comment - "Cloud printing" subfolder - that was an oversight, we shouldn't have done that even initially.

So I can update the PR to keep line 188 :-)
I'll do the similar in the v1 TOC as well. Beta has already got the line and it's still there.

2021-03-06 01:27 UTC, opbld33 commented
Docs Build status updates of commit _[ceb228a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ceb228ae5b460206636b18c2e15a4e5bfe51e58e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-bd68f22f)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-7df83b98-bd68f22f)
[api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/integerrange?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b86266e7-bd68f22f)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544) | [Details](#user-content-2ec827c4-bd68f22f)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-11544) | [Details](#user-content-3e780b05-bd68f22f)
[api-reference/v1.0/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printershare-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f607c0e0-bd68f22f)
[api-reference/v1.0/api/printtaskdefinition-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printtaskdefinition-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printtaskdefinition-list-tasks?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-cf435376-bd68f22f)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-11544) | [Details](#user-content-f985040c-bd68f22f)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11544) | [Details](#user-content-c447f2b8-bd68f22f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11544) (graph-rest-beta) |
[api-reference/includes/cloudprinting-pricing-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/includes/cloudprinting-pricing-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-refe [...]

2021-03-06 01:31 UTC, angelgolfer-ms reviewed
@nilakhan , thanks for [incorporating](https://github.com/microsoftgraph/microsoft-graph-docs/pull/11544#issuecomment-789289739) my feedback from earlier comments. 

There was a slight misunderstanding, please see my comment in the conceptual TOC, but it's good now, I fixed the conceptual and v1 TOC directly in this PR.

2021-03-06 01:38 UTC, opbld32 commented
Docs Build status updates of commit _[0e53f1e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e53f1e1a8f144f19a2acef613a863dc2eb0ae45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/print-post-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-taskdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-2da05e49-cfb53121)
[api-reference/v1.0/resources/archivedprintjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/archivedprintjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/archivedprintjob?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-7df83b98-cfb53121)
[api-reference/v1.0/resources/integerrange.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/resources/integerrange.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/integerrange?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-b86266e7-cfb53121)
[concepts/universal-print-concept-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-concept-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544) | [Details](#user-content-2ec827c4-cfb53121)
[concepts/upload-data-to-upload-session.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/upload-data-to-upload-session.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/upload-data-to-upload-session?branch=pr-en-us-11544) | [Details](#user-content-3e780b05-cfb53121)
[api-reference/v1.0/api/printershare-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printershare-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printershare-get?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-f607c0e0-cfb53121)
[api-reference/v1.0/api/printtaskdefinition-list-tasks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/printtaskdefinition-list-tasks.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printtaskdefinition-list-tasks?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) | [Details](#user-content-cf435376-cfb53121)
[concepts/overview-major-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/overview-major-services.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/overview-major-services?branch=pr-en-us-11544) | [Details](#user-content-f985040c-cfb53121)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11544) | [Details](#user-content-c447f2b8-cfb53121)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-11544) (graph-rest-beta) |
[api-reference/includes/cloudprinting-pricing-disclaimer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/includes/cloudprinting-pricing-disclaimer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-concept-overview?branch=pr-en-us-11544)<br/> [View](https://review.docs.microsoft.com/en-us/graph/api/printconnector-delete?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-delete-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-delete-taskdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-delete-taskdefinition?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-get-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-get-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-get-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-connectors.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-connectors.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-connectors?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-printers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-printers.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-printers?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-services.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-services.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-services?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-list-taskdefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-list-taskdefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-list-taskdefinitions?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-post-shares.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-post-shares.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-post-shares?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-settings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-reference/v1.0/api/print-update-settings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/print-update-settings?view=graph-rest-1.0&branch=pr-en-us-11544) (>= graph-rest-1.0) |
[api-reference/v1.0/api/print-update-taskdefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-02-nilakhan-print-graph/api-refe [...]

2021-03-06 01:39 UTC, nilakhan commented on concepts/toc.yml
> -        expanded: true
Thanks!

2021-03-06 02:26 UTC, Lauragra approved these changes

2021-03-06 02:28 UTC, merged