Doc update for app staging.
microsoftgraph/microsoft-graph-docs pull request #11594
Opened 2021-02-09 20:39 UTC by subray2014

Updating v1.0 docs for teams app staging from beta.

2021-02-09 20:41 UTC, opbld31 commented
Docs Build status updates of commit _[eac3d2a](https://github.com/subray2014/microsoft-graph-docs/commits/eac3d2a15855604ec32e0118d2181edffff28fa8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-aa0d4180)
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-a10c28a8-aa0d4180)
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-2060d3e0-aa0d4180)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-bots-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-bots-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-filter-expand-appdefinitions-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-filter-expand-appdefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/list-teamsapp-with-bots-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/list-teamsapp-with-bots-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/list-teamsapp-with-filter-expand-appdefinitions-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/list-teamsapp-with-filter-expand-appdefinitions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/create-teamsapp-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/create-teamsapp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-bots-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-bots-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-filter-expand-appdefinitions-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-filter-expand-appdefinitions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/update-teamsapp-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/update-teamsapp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/create-teamsapp-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/create-teamsapp-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-bots-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-bots-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |

<a id="c1828b28-aa0d4180"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 453, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'chat-list-installedapps.md'.`````

<a id="a10c28a8-aa0d4180"></a>
### [api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microso [...]

2021-02-09 20:55 UTC, opbld31 commented
Docs Build status updates of commit _[610588d](https://github.com/subray2014/microsoft-graph-docs/commits/610588d1660c3332f89c365b4bc8c9d4edf9f8f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-d3e3ee5c)
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-cad5a528-d3e3ee5c)
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-a10c28a8-d3e3ee5c)
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-2060d3e0-d3e3ee5c)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-teamworkbot-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/get-teamworkbot-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-bots-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-bots-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-filter-expand-appdefinitions-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-filter-expand-appdefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-teamworkbot-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/get-teamworkbot-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/list-teamsapp-with-bots-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/list-teamsapp-with-bots-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/list-teamsapp-with-filter-expand-appdefinitions-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/list-teamsapp-with-filter-expand-appdefinitions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/create-teamsapp-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/create-teamsapp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-teamworkbot-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/get-teamworkbot-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-bots-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-bots-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-filter-expand-appdefinitions-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-filter-expand-appdefinitions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/update-teamsapp-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/update-teamsapp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/create-teamsapp-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/create-teamsapp-objc-snippets.md) | :white_check_mar [...]

2021-02-09 22:13 UTC, opbld32 commented
Docs Build status updates of commit _[718d47d](https://github.com/subray2014/microsoft-graph-docs/commits/718d47d6897cb52838a9d3bcca2b5c6e6451aabf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-e81973f3)
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-cad5a528-e81973f3)
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-721b178e-e81973f3)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-teamworkbot-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/get-teamworkbot-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-bots-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-bots-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-filter-expand-appdefinitions-csharp-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/csharp/list-teamsapp-with-filter-expand-appdefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/get-teamworkbot-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/get-teamworkbot-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/list-teamsapp-with-bots-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/list-teamsapp-with-bots-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/java/list-teamsapp-with-filter-expand-appdefinitions-java-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/java/list-teamsapp-with-filter-expand-appdefinitions-java-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/create-teamsapp-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/create-teamsapp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/get-teamworkbot-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/get-teamworkbot-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-bots-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-bots-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-filter-expand-appdefinitions-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/list-teamsapp-with-filter-expand-appdefinitions-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/javascript/update-teamsapp-javascript-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/javascript/update-teamsapp-javascript-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/create-teamsapp-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/create-teamsapp-objc-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/get-teamworkbot-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/get-teamworkbot-objc-snippets.md) | :wh [...]

2021-02-11 00:56 UTC, opbld32 commented
Docs Build status updates of commit _[cb3127e](https://github.com/subray2014/microsoft-graph-docs/commits/cb3127e006c73bbdebbac2ce084911c8b37a7903)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-79bb937a)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |

<a id="c1828b28-79bb937a"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 255, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 312, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110055233483-11594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FL6YVHvuQzj07dHLrQ5kzssU%2F674jBZiHmWdQBmUk5Y%3D&st=2021-02-11T00%3A51%3A32Z&se=2021-03-14T00%3A56%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 01:50 UTC, opbld34 commented
Docs Build status updates of commit _[1a53777](https://github.com/subray2014/microsoft-graph-docs/commits/1a537779ec43b17c76f72224d40c448170495e52)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b1d78488)

<a id="b1d78488"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110150218746-11594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Fu%2B23Wtt1WhlOQRG2Naz7NxWrY1k3VfkPayttQ1kOFY%3D&st=2021-02-11T01%3A45%3A37Z&se=2021-03-14T01%3A50%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 01:54 UTC, opbld34 commented
Docs Build status updates of commit _[0e80d72](https://github.com/subray2014/microsoft-graph-docs/commits/0e80d729cf352937e1a3bb990b24a9f6d60e4f28)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-098da55a)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11594) |

<a id="c1828b28-098da55a"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 255, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 312, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110153034523-11594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e2mm3aLmSfC%2FcPliHqQMJPc2Aa%2FFhZU6ikWECIjNXUI%3D&st=2021-02-11T01%3A49%3A08Z&se=2021-03-14T01%3A54%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 08:49 UTC, opbld34 commented
Docs Build status updates of commit _[21f9747](https://github.com/subray2014/microsoft-graph-docs/commits/21f974739b49dc64c1d4872d4a62b5af263ad2b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-f0b66a6f)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11594) |

<a id="c1828b28-f0b66a6f"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 255, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 312, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120847597780-11594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iInsex4%2B4OT%2BJUlYFCTV8S9D3CzskZ9cAG%2FkD6SFDDk%3D&st=2021-02-12T08%3A44%3A14Z&se=2021-03-15T08%3A49%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 08:52 UTC, opbld34 commented
Docs Build status updates of commit _[932a586](https://github.com/subray2014/microsoft-graph-docs/commits/932a58694a59d3bdef17cc97e8bdb143b4b13e39)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-92110533)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11594) |

<a id="c1828b28-92110533"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 255, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 312, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120851186833-11594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pT8m0kjVMd2Qr9inSfuBZOaVclmrlz7qFNwUgcXC6Ws%3D&st=2021-02-12T08%3A47%3A23Z&se=2021-03-15T08%3A52%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 08:55 UTC, opbld34 commented
Docs Build status updates of commit _[1881a7b](https://github.com/subray2014/microsoft-graph-docs/commits/1881a7b25e1efbf53dd00746c7d784a4c5a5b802)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-5b8d8d66)
[api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/includes/snippets/objc/list-teamsapp-with-filter-expand-appdefinitions-objc-snippets.md) | :white_check_mark:Succeeded | |
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11594) |
[concepts/search-concept-custom-types.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-11594) |

<a id="c1828b28-5b8d8d66"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 255, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````
 - **Line 312, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120854447121-11594%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lZoulti4XP3iXJf1x9rE0j5%2FSbwFzPlM3QdUkbIRmwA%3D&st=2021-02-12T08%3A50%3A52Z&se=2021-03-15T08%3A55%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-25 03:43 UTC, AkJo commented on api-reference/v1.0/api/appcatalogs-list-teamsapps.md
> +- [List apps installed in a team](team-list-installedapps.md) <!-- - [List apps installed in a chat](chat-list-installedapps.md) -->
why is this commented out?

We have v1 app crud APIs for chats.

2021-02-25 03:44 UTC, AkJo commented on api-reference/v1.0/api/teamsapp-publish.md
> +# [HTTP](#tab/http)
Please remove this line.

This is autogenerated by the snipped generator.

2021-02-25 03:45 UTC, AkJo commented on api-reference/v1.0/api/teamsapp-publish.md
> +# [HTTP](#tab/http)
Please remove this line. This is autogenerated by the snippet generator.

2021-02-25 03:45 UTC, AkJo commented on api-reference/v1.0/api/teamsapp-update.md
>  # [HTTP](#tab/http)
Please remove this line. This is autogenerated by the snippet generator.

2021-02-25 03:46 UTC, AkJo commented on api-reference/v1.0/api/teamworkbot-get.md
> +# [HTTP](#tab/http)
Please remove this line. This is autogenerated by the snippet generator.

2021-02-25 03:47 UTC, AkJo commented on api-reference/v1.0/resources/teamworkbot.md
> +- To get bots installed in a team, see example 2 in [List apps in team](../api/team-list-installedapps.md). <!-- - To get bots installed in a chat, see example 2 in [List apps in chat](../api/chat-li
We have v1ed this already

2021-02-25 04:02 UTC, AkJo approved these changes
Please fix the "# [HTTP](#tab/http)" for the sections where the code snippet needs to be generated before merging this file.

2021-02-25 19:27 UTC, subray2014 commented on api-reference/v1.0/api/appcatalogs-list-teamsapps.md
> +- [List apps installed in a team](team-list-installedapps.md) <!-- - [List apps installed in a chat](chat-list-installedapps.md) -->
There is a circular dependency right now with Benny's PR. I will add this back once we have both the PRs checked in.

2021-02-25 19:42 UTC, subray2014 commented on api-reference/v1.0/resources/teamworkbot.md
> +- To get bots installed in a team, see example 2 in [List apps in team](../api/team-list-installedapps.md). <!-- - To get bots installed in a chat, see example 2 in [List apps in chat](../api/chat-li
There is a circular dependency with Benny's PR. We will uncomment this once both go in.

2021-03-02 19:44 UTC, Lauragra commented on api-reference/v1.0/api/teamsapp-update.md
> +If successful, this method returns a `204 No Content` response code.
Please show the HTTP response instead of repeating the text in the Response H2 section earlier.

2021-03-02 19:48 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the **publishingState** property to [teamsAppDefinition](https://docs.microsoft.com/en-us/graph/api/resources/teamsAppDefinition?view=graph-rest-1.0) resource",
Global: please make sure that all descriptions end with a period.

2021-03-02 19:52 UTC, Lauragra requested changes
Please update the beta and v1.0 TOCs with this PR to surface the new resource and method topic.

2021-03-05 01:01 UTC, subray2014 commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the **publishingState** property to [teamsAppDefinition](https://docs.microsoft.com/en-us/graph/api/resources/teamsAppDefinition?view=graph-rest-1.0) resource",
Will do. However, please note that this was generated by the doc generator tool. Might be good to take a fix in that as well.

2021-03-05 01:07 UTC, subray2014 commented on api-reference/v1.0/api/teamsapp-update.md
> +If successful, this method returns a `204 No Content` response code.
Not sure what you mean. There is no content in the response body. Can you clarify what to add?

2021-03-05 01:21 UTC, opbld30 commented
Docs Build status updates of commit _[c28b742](https://github.com/subray2014/microsoft-graph-docs/commits/c28b74226779bf21a64a3d2fd3ac007d393521c5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-5e4036ad)
[api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-e097c7ca-5e4036ad)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-60a67f37-5e4036ad)
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-7f63a574-5e4036ad)
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-1dcc5bfd-5e4036ad)
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-cad5a528-5e4036ad)
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-d27baf58-5e4036ad)
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-a10c28a8-5e4036ad)
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-2060d3e0-5e4036ad)
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-721b178e-5e4036ad)
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-custom-types.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-11594) |

<a id="c1828b28-5e4036ad"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e097c7ca-5e4036ad"></a>
### [api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="60a67f37-5e4036ad"></a>
### [api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="7f63a574-5e4036ad"></a>
### [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1dcc5bfd-5e4036ad"></a>
### [api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cad5a528-5e4036ad"></a>
### [api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="d27baf58-5e4036ad"></a>
### [api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a10c28a8-5e4036ad"></a>
### [api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-grap [...]

2021-03-05 01:36 UTC, subray2014 commented on api-reference/v1.0/api/teamsapp-update.md
> +If successful, this method returns a `204 No Content` response code.
you probably mean something like this:
```http
HTTP/1.1 204 No Content
```
Please let me know if I misunderstood.

2021-03-05 01:38 UTC, opbld30 commented
Docs Build status updates of commit _[d2357f1](https://github.com/subray2014/microsoft-graph-docs/commits/d2357f152b6941861db68a520b325ce000cdc05c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-67665d5b)
[api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-e097c7ca-67665d5b)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-60a67f37-67665d5b)
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-7f63a574-67665d5b)
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-1dcc5bfd-67665d5b)
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-cad5a528-67665d5b)
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-d27baf58-67665d5b)
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-a10c28a8-67665d5b)
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-2060d3e0-67665d5b)
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-721b178e-67665d5b)
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-custom-types.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-11594) |

<a id="c1828b28-67665d5b"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e097c7ca-67665d5b"></a>
### [api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="60a67f37-67665d5b"></a>
### [api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="7f63a574-67665d5b"></a>
### [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1dcc5bfd-67665d5b"></a>
### [api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cad5a528-67665d5b"></a>
### [api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="d27baf58-67665d5b"></a>
### [api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a10c28a8-67665d5b"></a>
### [api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-grap [...]

2021-03-05 02:33 UTC, Lauragra commented on api-reference/v1.0/api/teamsapp-update.md
> +If successful, this method returns a `204 No Content` response code.
Yes, that is what I mean.

2021-03-05 02:33 UTC, Lauragra commented on changelog/Microsoft.Teams.GraphSvc.json
> +          "Description": "Added the **publishingState** property to [teamsAppDefinition](https://docs.microsoft.com/en-us/graph/api/resources/teamsAppDefinition?view=graph-rest-1.0) resource",
Yes, I was told that this bug was fixed in the generator. Thanks.

2021-03-05 02:34 UTC, Lauragra approved these changes

2021-03-05 02:36 UTC, opbld34 commented
Docs Build status updates of commit _[cb054f2](https://github.com/subray2014/microsoft-graph-docs/commits/cb054f256ba8b141e3854cd048cccdf99ce49731)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/appcatalogs-list-teamsapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-c1828b28-c787bb54)
[api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/team-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-e097c7ca-c787bb54)
[api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-delete?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-60a67f37-c787bb54)
[api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-publish?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-7f63a574-c787bb54)
[api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamsapp-update?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-1dcc5bfd-c787bb54)
[api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/teamworkbot-get?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-cad5a528-c787bb54)
[api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userteamwork-list-installedapps?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-d27baf58-c787bb54)
[api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsapp.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsapp?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-a10c28a8-c787bb54)
[api-reference/v1.0/resources/teamsappdefinition.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamsappdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamsappdefinition?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-2060d3e0-c787bb54)
[api-reference/v1.0/resources/teamworkbot.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/resources/teamworkbot.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/teamworkbot?view=graph-rest-1.0&branch=pr-en-us-11594) (>= graph-rest-1.0) | [Details](#user-content-721b178e-c787bb54)
[changelog/Microsoft.Teams.GraphSvc.json](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/changelog/Microsoft.Teams.GraphSvc.json) | :white_check_mark:Succeeded | |
[concepts/search-concept-custom-types.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/concepts/search-concept-custom-types.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/search-concept-custom-types?branch=pr-en-us-11594) |

<a id="c1828b28-c787bb54"></a>
### [api-reference/v1.0/api/appcatalogs-list-teamsapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/appcatalogs-list-teamsapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e097c7ca-c787bb54"></a>
### [api-reference/v1.0/api/team-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/team-list-installedapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="60a67f37-c787bb54"></a>
### [api-reference/v1.0/api/teamsapp-delete.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="7f63a574-c787bb54"></a>
### [api-reference/v1.0/api/teamsapp-publish.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-publish.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="1dcc5bfd-c787bb54"></a>
### [api-reference/v1.0/api/teamsapp-update.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamsapp-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cad5a528-c787bb54"></a>
### [api-reference/v1.0/api/teamworkbot-get.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/teamworkbot-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="d27baf58-c787bb54"></a>
### [api-reference/v1.0/api/userteamwork-list-installedapps.md](https://github.com/subray2014/microsoft-graph-docs/blob/users/subray/AppStagingV1/api-reference/v1.0/api/userteamwork-list-installedapps.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a10c28a8-c787bb54"></a>
### [api-reference/v1.0/resources/teamsapp.md](https://github.com/subray2014/microsoft-grap [...]

2021-03-05 02:39 UTC, merged