[NotificationAPIGuidelines][Create][1529165]
microsoftgraph/microsoft-graph-docs pull request #11609
Opened 2021-02-10 14:17 UTC by KirtiPereira

Create new document for Notification API guidelines / best practices.

2021-02-10 14:18 UTC, opbld30 commented
Docs Build status updates of commit _[b8e04e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8e04e8e7afc52743bfdc719c6f04f4f5a1b1138)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-5c55589d)

<a id="eacddabb-5c55589d"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'notification'.`````
 - **Line 25, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102101417081491-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aSch%2FT2jHOTGFROiRhrCAxbrn%2F7u2OueVqBNSr24Fqw%3D&st=2021-02-10T14%3A13%3A23Z&se=2021-03-13T14%3A18%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 08:15 UTC, opbld30 commented
Docs Build status updates of commit _[d3a2bd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d3a2bd128fb4a025bf49a7d50b84e448cb24c902)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-abab1e0c)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-abab1e0c"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 6, Column 10**: **[Warning-[ms-prod-technology-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-technology-invalid?branch=main)]** `````Invalid value for 'ms.prod': 'notification'.`````
 - **Line 46, Column 90**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#best-practices-to-use-the-bot-framework-and-the-notification-api' in 'notifications-api-best-practices.md', did you mean '#best-practices-to-use-the-bot-framework-and-notification-api'?`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110813571491-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VcjY4SmXxrp3jgNdUGX92vYo423CkkFVKdAw8tMIyBY%3D&st=2021-02-11T08%3A10%3A17Z&se=2021-03-14T08%3A15%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 08:48 UTC, opbld30 commented
Docs Build status updates of commit _[b38e237](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b38e237810be6079d91f7da98f407f91277f8feb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-ca1bed48)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-ca1bed48"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 46, Column 90**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#best-practices-to-use-the-bot-framework-and-the-notification-api' in 'notifications-api-best-practices.md', did you mean '#best-practices-to-use-the-bot-framework-and-notification-api'?`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110846580877-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uicDsN1wp1AUlFcDMVXKtXB%2FZ3vOo%2BNLmEoj75WmOtM%3D&st=2021-02-11T08%3A43%3A16Z&se=2021-03-14T08%3A48%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 09:38 UTC, opbld34 commented
Docs Build status updates of commit _[761c30c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/761c30c2b588508c4a5e99edd9c4ea4e944ec957)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110937193957-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MWZtsAScu1HsehSTUz2SkEgK8FIPE5XswnTYfFXglpM%3D&st=2021-02-11T09%3A33%3A38Z&se=2021-03-14T09%3A38%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 09:48 UTC, opbld34 commented
Docs Build status updates of commit _[f27e22d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f27e22d352c034146153954585392b7efe04ec15)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-55a295b5)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-55a295b5"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 23, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110947376229-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FINBPxwtDCHGTJ9o1zhPs8sFNqq%2FuLrEceeAGbo1KvI%3D&st=2021-02-11T09%3A43%3A41Z&se=2021-03-14T09%3A48%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 09:58 UTC, opbld33 commented
Docs Build status updates of commit _[c702f35](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c702f353c9ddc7eab77ca401638b47b53aed60f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-9689f1c9)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-9689f1c9"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 23, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110956498889-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0HB61X6PPnkahMj%2FEe8Gnp9L0VzYwH0SauI6IjsnLug%3D&st=2021-02-11T09%3A52%3A59Z&se=2021-03-14T09%3A57%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 10:03 UTC, opbld33 commented
Docs Build status updates of commit _[8f4774e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f4774e174692cf5749bd7a27b57f13ab5cc999f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-191870df)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-191870df"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 46, Column 90**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#best-practices-to-use-the-bot-framework-and-notification-api' in 'notifications-api-best-practices.md'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111002252595-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0DZs7gKbdvzc80BRi7f3ys9UMGAmFsStffHpGNv5JBY%3D&st=2021-02-11T09%3A58%3A31Z&se=2021-03-14T10%3A03%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 10:12 UTC, opbld34 commented
Docs Build status updates of commit _[91d9af6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91d9af6b8e5a49c74b5751385597d93f1bdcc1d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-3c06cf26)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-3c06cf26"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 25, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111011127224-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YWr%2FcykXCaFA7J%2F%2FbneAAdDprmqOLqEBJVjl%2BlgxCII%3D&st=2021-02-11T10%3A07%3A20Z&se=2021-03-14T10%3A12%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 10:23 UTC, opbld31 commented
Docs Build status updates of commit _[4eb37fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4eb37fe199c00d1fb034e8e909f5eae6e8812f6f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) | [Details](#user-content-eacddabb-b8a7aadf)
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

<a id="eacddabb-b8a7aadf"></a>
### [concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md)
 - **Line 25, Column 1**: **[Suggestion-table-syntax-invalid]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111022266500-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HrjdGpGw4PxY9T65GKdelIJC4Rcrwu6EHKfqpYJrWpM%3D&st=2021-02-11T10%3A18%3A36Z&se=2021-03-14T10%3A23%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 11:48 UTC, opbld34 commented
Docs Build status updates of commit _[583b104](https://github.com/microsoftgraph/microsoft-graph-docs/commits/583b104f28741d6a70321c5a1a46fe4e1916011c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111147421891-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZpcJEUBO4wHXvYW7ILZVjfFFBkibHOenpcE18mtJfYE%3D&st=2021-02-11T11%3A43%3A46Z&se=2021-03-14T11%3A48%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 12:59 UTC, opbld33 commented
Docs Build status updates of commit _[929b531](https://github.com/microsoftgraph/microsoft-graph-docs/commits/929b531a537758370cb55af5271aa3f53401f8da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/notifications-api-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/notifications-api-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/notifications-api-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102111258042515-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IqpJS2Rcb7B2yCrWvdjKeejf3aVMqvVZd3qBjNvnfUg%3D&st=2021-02-11T12%3A54%3A14Z&se=2021-03-14T12%3A59%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-13 11:37 UTC, opbld30 commented
Docs Build status updates of commit _[b58b4e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b58b4e960489c13e2f110e29e5dd1e78605c88c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :x:Error | | [Details](#user-content-b329d26c-efe5db64)
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | | [Details](#user-content-f6d9d1f1-efe5db64)

<a id="b329d26c-efe5db64"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml)
 - **Line 392, Column 11**: **[Error-yaml-syntax-error]** `````While parsing a block collection, did not find expected '-' indicator.`````

<a id="f6d9d1f1-efe5db64"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102131136274584-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=om2fohFAWw5BR1mAy0LQ6oVMSNLo93xkPUevnkjTo00%3D&st=2021-02-13T11%3A32%3A42Z&se=2021-03-16T11%3A37%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-13 11:46 UTC, opbld34 commented
Docs Build status updates of commit _[f4b4d19](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f4b4d1923c4aa0ae39b34c30b842cc1d1755daa6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-f6a979d2)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-f6a979d2"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102131145271094-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HiQh9uAcMxoet9YQiPBZp4Z8Ber4m9VogpUbvsNUPmc%3D&st=2021-02-13T11%3A41%3A43Z&se=2021-03-16T11%3A46%3A43Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 10:17 UTC, opbld33 commented
Docs Build status updates of commit _[d9f7e04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9f7e040f9cd6f3a82eb102b122cbad71cbb89a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b329d26c-adcc8055)
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |

<a id="b329d26c-adcc8055"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml)
 - **Line 392, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'displayName' is already defined, remove the duplicate key.`````
 - **Line 393, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161016307389-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m7nIioyqmNLnqaiZqcrkejsv5dPLFU92b8Vcsu8mlng%3D&st=2021-02-16T10%3A12%3A37Z&se=2021-03-19T10%3A17%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 10:52 UTC, opbld34 commented
Docs Build status updates of commit _[0a7ca1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0a7ca1bc4429bde1341904bf01202fa38407b189)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b329d26c-e6e5e116)
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-e6e5e116)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b329d26c-e6e5e116"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml)
 - **Line 392, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'displayName' is already defined, remove the duplicate key.`````
 - **Line 393, Column 9**: **[Warning-yaml-duplicate-key]** `````Key 'items' is already defined, remove the duplicate key.`````

<a id="f6d9d1f1-e6e5e116"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 34, Column 340**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Screenshot of Activity Types' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 237**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Screenshot of Activity Types' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161051262765-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UWZNpyPfVrIYzQK1AHIQmJQmVdm5d%2FqcCYRMuTh58B8%3D&st=2021-02-16T10%3A47%3A37Z&se=2021-03-19T10%3A52%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 11:30 UTC, opbld34 commented
Docs Build status updates of commit _[6b5f889](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b5f889e310327ae73fbb04541d44b1a913c30cd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-73fc1e22)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-73fc1e22"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 34, Column 340**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Screenshot of Activity Types' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 237**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Screenshot of Activity Types' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161129154699-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=G%2BXT20TBAgEXVZy%2FgA%2FUMuz6fSiHBRpuJMsny2YVuV0%3D&st=2021-02-16T11%3A25%3A25Z&se=2021-03-19T11%3A30%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 11:37 UTC, opbld34 commented
Docs Build status updates of commit _[5eb4e98](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5eb4e98eb96f23f106505facc28e6784a9852798)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-eee331ef)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-eee331ef"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 34, Column 340**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Screenshot of Activity Types' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 34, Column 237**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Screenshot of Activity Types' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161135588950-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1dg%2FVAYNPUT%2BmQ8ZrjxlTswDYr2qS%2B4lVDUZGT9VBrE%3D&st=2021-02-16T11%3A32%3A07Z&se=2021-03-19T11%3A37%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 12:34 UTC, opbld33 commented
Docs Build status updates of commit _[97902ee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97902ee7a163067b44c4b28995e14fca3f25897b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161232503310-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FKpbCGl7zkv7e3T%2FZ%2Fs0eUMEUV104137T95S9L3LV4k%3D&st=2021-02-16T12%3A29%3A11Z&se=2021-03-19T12%3A34%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 12:50 UTC, opbld32 commented
Docs Build status updates of commit _[d102604](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d10260454676e5eb03fafc2578b8922c20268dee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) | [Details](#user-content-c97be298-185290b0)
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="c97be298-185290b0"></a>
### [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161248130614-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NTS4lkjMVCLCThNUfLqnnQ81MVWKX%2F%2FYMKktdtjav6Y%3D&st=2021-02-16T12%3A45%3A10Z&se=2021-03-19T12%3A50%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:10 UTC, opbld30 commented
Docs Build status updates of commit _[8bea353](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bea353b7bd1d3c12265fa573172ce4ff02c6e68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) | [Details](#user-content-c97be298-cca72f1e)
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="c97be298-cca72f1e"></a>
### [concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md)
 - **Line 4, Column 9**: **[Warning-[author-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/author-missing?branch=main)]** `````Invalid value for author: 'Ramjot Singh' is not a valid GitHub ID.`````
 - **Line 5, Column 12**: **[Suggestion-[ms-author-invalid](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/ms-author-invalid?branch=main)]** `````Invalid value for 'ms.author', 'RamjotSingh' is not a valid Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161309273608-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GHLjl2dPnyfpt0qDwmI9BFAUG6yNS66VPSkUBGDbDOc%3D&st=2021-02-16T13%3A05%3A34Z&se=2021-03-19T13%3A10%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:14 UTC, opbld30 commented
Docs Build status updates of commit _[3fcb8da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fcb8da99ad87e0f3e67b894c8ff6fac859e2934)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161313155364-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=23Jet6yHBZo44AluYbtK2RyiKG2pj5SsFYUfIVArWdk%3D&st=2021-02-16T13%3A09%3A37Z&se=2021-03-19T13%3A14%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:20 UTC, opbld31 commented
Docs Build status updates of commit _[6558bf1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6558bf1e0f51cc3469347508027d943e0c279fad)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :x:Error | | [Details](#user-content-b329d26c-9b757b79)

<a id="b329d26c-9b757b79"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml)
 - **Line 394, Column 26**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161319072604-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ReiOSb3q%2FSL9zsIFM1flW6dVLyRmaEtVPa9tyi39u4Q%3D&st=2021-02-16T13%3A15%3A18Z&se=2021-03-19T13%3A20%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:25 UTC, opbld33 commented
Docs Build status updates of commit _[6f2f9ba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f2f9bab549da3272f4963af1cdcad4f1cd19af6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161323457189-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bYA0omnypcGqX44sRH88llsi4obU8LBUJ2ouUlhI1%2Fk%3D&st=2021-02-16T13%3A20%3A03Z&se=2021-03-19T13%3A25%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:29 UTC, opbld34 commented
Docs Build status updates of commit _[ffd7b9b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffd7b9b162c6a5cd38a57e7ce5b9cb60cfb31769)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :x:Error | | [Details](#user-content-b329d26c-f52da8c0)

<a id="b329d26c-f52da8c0"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml)
 - **Line 395, Column 20**: **[Error-yaml-syntax-error]** `````While scanning a plain scalar value, found invalid mapping.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161328107906-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1nFkgdvUDSQe6y41TyfNXrQiabM5s0qV5SAQtsHcd7M%3D&st=2021-02-16T13%3A24%3A15Z&se=2021-03-19T13%3A29%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:31 UTC, opbld30 commented
Docs Build status updates of commit _[01ba392](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01ba3928107b7e89dd92e7f728a5785abeb0bf28)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161330393928-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ooFw1OD6OV1Uy6KNI3nBRHmA9ukEBXqXcahnVgDeVeE%3D&st=2021-02-16T13%3A26%3A47Z&se=2021-03-19T13%3A31%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 13:50 UTC, opbld33 commented
Docs Build status updates of commit _[42ebd86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/42ebd86404903ecdbf2a1ce5c449271aeb2f99a5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161349292005-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KYediUa6960XaG35nobXRWZ9dCmGkSRRoyzWJXbiAuo%3D&st=2021-02-16T13%3A45%3A45Z&se=2021-03-19T13%3A50%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 14:00 UTC, opbld30 commented
Docs Build status updates of commit _[a370065](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a370065a33d35de16bf1fa409bf02ac2e25a272e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161359289860-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4gwQ1mgUZkSpBdBvPvG1FkoJUXOJZFyi%2BB1fli8OsRM%3D&st=2021-02-16T13%3A55%3A23Z&se=2021-03-19T14%3A00%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 14:11 UTC, opbld34 commented
Docs Build status updates of commit _[03a8698](https://github.com/microsoftgraph/microsoft-graph-docs/commits/03a86985491bf9e174235ca306c2aef6311a163c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161411007548-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jwinA24ly5sCbIBh5U8vBy62Snhh7o7LLzlMPmjuU70%3D&st=2021-02-16T14%3A06%3A58Z&se=2021-03-19T14%3A11%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 14:20 UTC, opbld34 commented
Docs Build status updates of commit _[9b794ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9b794ad6bbb1fa6c610e2e9f2db780883fafd12b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :x:Error | | [Details](#user-content-b329d26c-09639c38)

<a id="b329d26c-09639c38"></a>
### [concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml)
 - **Line 394, Column 12**: **[Error-yaml-syntax-error]** `````While parsing a block collection, did not find expected '-' indicator.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161419529587-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qzDlm5%2BZHGeNLluu%2FASX8g3FGQxATIYMHvElAeoAu9s%3D&st=2021-02-16T14%3A15%3A53Z&se=2021-03-19T14%3A20%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 14:24 UTC, opbld33 commented
Docs Build status updates of commit _[76a80ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76a80ff641091c61cbb732f828d7255e27c329fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161423304421-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C9Ku43X%2FPnxryBYZ20qEQnGSAyQ2aTZ8rSuG8XoqqKQ%3D&st=2021-02-16T14%3A19%3A39Z&se=2021-03-19T14%3A24%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 06:40 UTC, opbld34 commented
Docs Build status updates of commit _[50f54fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/50f54fabfa75ed2c6bdad2ddbd8b055af845c4a6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170639383044-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qPlms6LTDsEyNWemkLGA895a3FxwDow3p5WdSiaQJy8%3D&st=2021-02-17T06%3A35%3A52Z&se=2021-03-20T06%3A40%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 06:44 UTC, opbld34 commented
Docs Build status updates of commit _[636bfee](https://github.com/microsoftgraph/microsoft-graph-docs/commits/636bfee0943573c6ed3bbe446afdd8b71a281e35)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170643289462-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wv7wrNlELsyTYYdxqDUkHzDDgRHGM9kBAAq7gVVEj%2BQ%3D&st=2021-02-17T06%3A39%3A40Z&se=2021-03-20T06%3A44%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 07:16 UTC, opbld31 commented
Docs Build status updates of commit _[264f31e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/264f31e65e650cbfae30e65e0909b7ddd0d761fb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170715144617-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PXoO2d8YjB%2BQVkRMuyqovcxh4MRDDuI0t6jGl3fegi0%3D&st=2021-02-17T07%3A11%3A23Z&se=2021-03-20T07%3A16%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 07:22 UTC, opbld31 commented
Docs Build status updates of commit _[2f5c217](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2f5c217f178a1cf8420b77d60e5c5fdad3c804df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170720335273-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YNUs8xags09Xv5rgY4IGskbo4Y7LMcBEHnLu8Hs8SE4%3D&st=2021-02-17T07%3A17%3A36Z&se=2021-03-20T07%3A22%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-22 17:22 UTC, srmunaka requested changes
Would be helpful if some of these changes can be incorporated. Would be good to understand how the last section should be phrased.

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +This document consolidates the best practices that you and Microsoft partners are expected to adhere to, as you build experiences using the activity feed notifications across visual elements and noti
I think we can exclude 'and Microsoft partners' since every developer accessing this page will be a partner. Might be confusing to some.

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you select a toast notification to lead to the activity feed. To switch to an activity, select a notification in the activity feed.
This was meant to be a comment for awareness. The developer cannot control the fact that a toast notification will lead to the activity feed. This is more of an FYI since some developers might not realize this.

This may be better phrased as 'understand that a user clicking on a toast notification will lead to the activity feed'.

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you create the settings based on the **Activity Types** defined in the app manifest. The setting titles read from the description field must be named appropriately to convey what settin
The settings are automatically populated, the developer has not control. The guidance for developers should be something along the lines of:

'Ensure that you title and describe your activity types appropriately since the setting titles read from the app manifest'

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Inform the user that the notification icon cannot be customized. Every notification from an app has the same icon, as included in the app manifest.
This is also for awareness. 

'Understand that the setting will appear only when the notification is received from the app in question'
'Understand that the app cannot be customized'

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +  > The 30 days storage limit applies to all notifications and is not specific to activity feed notifications.
not specific to notifications sent via the activity feed notification API

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
I realize it might be better to remove the word broadcast since it might be confusing (because notifications are sent to each user only today via this API)

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure there is no *period* at the end of the notification title to achieve parity with all other notifications in Teams.
all other 'notification settings' in Teams

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Deliver bot messages by turning on a chat or a channel notification, such that the users receive a notification alert in the chat or channel. You must *@mention* the name of the user for the notifi
'Deliver bot messages by turning on' - suggests developers can do something here. Instead, this is for their awareness:

Bot messages trigger notifications as chat notifications, or as channel notifications if the user's notifications for chat/channel are turned on. You must @mention ...

2021-02-22 17:22 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Deliver bot messages by turning on a chat or a channel notification, such that the users receive a notification alert in the chat or channel. You must *@mention* the name of the user for the notifi
many of these have been rephrased, but are largely so that developers can understand the differences:

![image](https://user-images.githubusercontent.com/78961095/108744625-2865c300-7560-11eb-8085-f0ccb1024f56.png)

For example, 'Ensure that the activity feed notification lands in the activity feed and deep links to various locations.' is confusing because an activity feed notification landing in the feed isn't something that they control, it's a part of the feature. 

Should this section be rephrased?

2021-02-24 06:20 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +This document consolidates the best practices that you and Microsoft partners are expected to adhere to, as you build experiences using the activity feed notifications across visual elements and noti
Incorporated the comment

2021-02-24 06:25 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you select a toast notification to lead to the activity feed. To switch to an activity, select a notification in the activity feed.
Incorporated the comment.

2021-02-24 06:32 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you create the settings based on the **Activity Types** defined in the app manifest. The setting titles read from the description field must be named appropriately to convey what settin
Incorporated the comment.

2021-02-24 06:38 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +* Inform the user that the notification icon cannot be customized. Every notification from an app has the same icon, as included in the app manifest.
Incorporated the comment.

2021-02-24 06:40 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
Incorporated the comment.

2021-02-24 06:42 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +  > The 30 days storage limit applies to all notifications and is not specific to activity feed notifications.
Incorporated the comment.

2021-02-24 06:43 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure there is no *period* at the end of the notification title to achieve parity with all other notifications in Teams.
Incorporated the comment.

2021-03-04 05:55 UTC, srmunaka commented
Thanks for the edits, this looks good to me.

2021-03-04 05:57 UTC, srmunaka approved these changes

2021-03-04 08:00 UTC, opbld30 commented
Docs Build status updates of commit _[69c82a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/69c82a801c7c818f8d95fe4128b9c4d1916e834e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-a5e3dce5)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-a5e3dce5"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 47, Column 88**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#understand-activity-feed-notifiations-and-bot-framework-notifications' in 'activity-feed-notifications-best-practices.md', did you mean '#understand-activity-feed-notifications-and-bot-framework-notifications'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040759330890-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=imD6NM3uj%2FRogit3Gr6emDTeeUxIVD2cEDccjWmRSAI%3D&st=2021-03-04T07%3A55%3A47Z&se=2021-04-04T08%3A00%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 08:08 UTC, opbld30 commented
Docs Build status updates of commit _[8b239c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b239c86e580ae9b9ba8637e7db2d7cc11663dbd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-61f097bf)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-61f097bf"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 47, Column 88**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#understand-activity-feed-notifiations-and-bot-framework-notifications' in 'activity-feed-notifications-best-practices.md', did you mean '#understand-activity-feed-notifications-and-bot-framework-notifications'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040807183030-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v4MGw8KpbovLRIP106dHaOLQl7MOuGek8AogM58O2dU%3D&st=2021-03-04T08%3A03%3A29Z&se=2021-04-04T08%3A08%3A29Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 08:14 UTC, opbld30 commented
Docs Build status updates of commit _[58a747d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/58a747dbaa8f54e3f43d8a1b686f136e3ebb48f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-2ccd8444)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-2ccd8444"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 48, Column 88**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#understand-activity-feed-notifiations-and-bot-framework-notifications' in 'activity-feed-notifications-best-practices.md', did you mean '#understand-activity-feed-notifications-and-bot-framework-notifications'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040813203049-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OUCxQFfaeXr9jPoMEQQIIxCJ5w0zwCUgm1RP1MzGEX0%3D&st=2021-03-04T08%3A09%3A31Z&se=2021-04-04T08%3A14%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 08:16 UTC, opbld30 commented
Docs Build status updates of commit _[8043470](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80434702e7395051593d657a46469e1522763e28)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-f6d9d1f1-04cdc00a)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="f6d9d1f1-04cdc00a"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 48, Column 88**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '##understand-activity-feed-notifications-and-bot-framework-notifications' in 'activity-feed-notifications-best-practices.md', did you mean '#understand-activity-feed-notifications-and-bot-framework-notifications'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040815074132-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3B9Yp%2FMdmBabsQwQkLSLOoV8tl8ctrC7N7L%2BrcOvzss%3D&st=2021-03-04T08%3A11%3A20Z&se=2021-04-04T08%3A16%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 08:34 UTC, opbld33 commented
Docs Build status updates of commit _[c9d0ef9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9d0ef96db529f5488ac68056eb06f18ba9bde48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103040833170474-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4uj6kqPPJfZDFDXFNAsSLfU%2BmQsWvFlcKS2nZmgYz%2F0%3D&st=2021-03-04T08%3A29%3A32Z&se=2021-04-04T08%3A34%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-11 19:36 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +This document consolidates the best practices that you are expected to adhere to, as you build experiences using the activity feed notifications across visual elements and notification behavior.
Please review the Microsoft voice guidelines: https://docs.microsoft.com/en-us/style-guide/brand-voice-above-all-simple-human. You'll want to avoid an overly formal tone in your articles. Suggested revision for the introductory sentence: "This article covers best practices to help you build experiences using Microsoft Teams activity feed notifications in Microsoft Graph." Note that you'll also want to include important keywords in your introduction, such as teams and Graph.

2021-03-11 19:37 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +title: "Best practices for Activity Feed Notification in Microsoft Graph"
The title attribute and the H1 title should match. Also note the difference in capitalization. Activity feed notification is not a proper noun so should not be captilatized. Should the title also include Microsoft Teams?

2021-03-11 19:39 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +description: "List best practices and examples for Activity Feed Notification in Microsoft Graph"
This is the description that can show in search results, it should be written as a complete sentence, i.e. "This article provides best practices and examples for working with activity feed notifications in Microsoft Graph."

2021-03-11 19:40 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +ms.author: "lajanuar"
Please use the author attribute instead of ms.author and put your GitHub name here.

2021-03-11 19:40 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +ms.prod: "notifications"
If this article is intended to be about Microsoft Teams, you should use the Teams service value teamwork here.

2021-03-11 19:46 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +At a high-level the best practices are as follows:
I suggest removing this. Note that when your article is published, the H2s will show as In this article links in the right rail: https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609#understand-activity-feed-notifications-and-bot-framework-notifications. Users can use those links to navigate to the main section. The link text here doesn't quite match the H2 titles they link to so I'm not sure exactly what the intent is. Anyway, it's cleaner to get straight into the content.

2021-03-12 02:32 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +The **Activity Feed Notification** is a platform that enables partner apps to send notifications to users. These notifications are sent as toast items and activity feed items that point users to rele
The feature name does not need to be bold or capitalized. Is activity feed notification a platform? That term is a bit overloaded. Maybe it's a feature? I would revise as: "Activity feed notifications enable partner apps to send notifications to users."

2021-03-12 02:33 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Following is the list of best practices:
Suggest revising the introduction here to something like "Apply the following best practices in your partner app".

2021-03-12 02:34 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Activity feed notifications partner scenarios
Is this the right heading here? Is this section about "Best practices for partner apps"? It doesn't appear to be covering scenarios.

2021-03-12 02:35 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Understand the direct relationship between a notification toast or feed, and the content it is deep linked to.
I'm not sure if "Understand" is a best practice. What is the action here vs. general knowledge?

2021-03-12 02:39 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +    * If the notification pertains to removal or deletion of scenarios, direct users to the content indicating the action, so that they understand the outcome before taking action. For example, remov
Revise "deletion of" to "deletion", so this isn't read as the scenarios getting deleted.

2021-03-12 02:42 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +### Utilize features in partner scenarios
I'm not clear about this subheading. What features are you referring to?

2021-03-12 02:43 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Understand that selecting a toast notification leads to the activity feed. To switch to an activity, select a notification in the activity feed.
Add an introduction to the bulleted list to set the context for the reader.

2021-03-12 02:44 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).<br/> ![
I suggest removing the image, it's not necessary and it's going to be strange in the localized content. Also, Please add images on new lines instead of using /br tags. On the review site, the content does not have the right spacing.

2021-03-12 02:45 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that apps are not sending more than 10 notifications per minute, per user.
Instead of using "Ensure that", can you rephrase as an action, i.e. "Don't send more than 10... "?

2021-03-12 02:45 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).<br/> ![
Instead of "Ensure that", just say "Localize the content". It's easier for readers to understand and easier for localization if you use direct imperative verbs.

2021-03-12 02:46 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you provide appropriate titles and descriptions for your **Activity Types**, since the setting titles are read from the app manifest. For example:<br/>![Screenshot of correct Activity T
"Provide appropriate..." Also, change since to because: https://docs.microsoft.com/en-us/style-guide/word-choice/use-simple-words-concise-sentences.

2021-03-12 02:48 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you provide appropriate titles and descriptions for your **Activity Types**, since the setting titles are read from the app manifest. For example:<br/>![Screenshot of correct Activity T
Don't rely heavily on images to convey meaning because the text in the images doesn't get localized and isn't consumable for non-sighted readers. Instead of saying "For example:" here, which conveys that the image is required to understand the text, you can say "as shown in the following example", which conveys that the example illustrates what the text explains.

2021-03-12 02:50 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that you provide appropriate titles and descriptions for your **Activity Types**, since the setting titles are read from the app manifest. For example:<br/>![Screenshot of correct Activity T
Actually, looking at the image, I strongly encourage you to replace the image with text that a screen reader can read. The green check and red x in the image to convey meaning is not accessible. Just use a convention like "Do/Don't" with the strings.

2021-03-12 02:52 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that the notifications are not promotional in nature. They must convey something important that the user must be aware about. For example:<br/>*Try the new feature in the Cycling app!* ❌<br/
Replace the br tags with new lines. The X and check mark might not be clear; you should clearly state which one is the Do vs. Don't.

2021-03-12 02:53 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Understand that the setting appears for the user  only when the selected app sends a notification.
Global to these three bullet points - understand is not a best practice, it's learning/awareness. You can provide some conceptual information but don't mix it in with a list of actual best practices. Or recast these to clarify what the best practice is.

2021-03-12 02:54 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* **Bot messages**:
Consider whether this bulleted and sub-bulleted list would be more readable in a table format with the text side-by-side.

2021-03-12 02:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Minimize noise and build high quality notification experiences
Will non-English speaking readers understand what you mean by "minimize noise"? Also "high quality" is vague. Would it make sense to revise this heading as "Streamline the notification experience", or "Simplify the notification experience"?

2021-03-12 02:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
Introduce the bulleted list to set context.

2021-03-12 02:58 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
Same suggestion here to clarify the examples as do/don't. Also remove the /br tags.

2021-03-12 02:59 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure there is no *period* at the end of the notification title to achieve parity with all other notification settings in Teams.
Revise as "Do not add a period at the end...".

2021-03-12 03:00 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Understand activity feed notifications and bot framework notifications
Again, "understanding" is not a best practice. Is there a best practice that's an action for the user? What should the user take away from knowing the difference between these two, from an implementation standpoint?

2021-03-22 07:53 UTC, opbld34 commented
Docs Build status updates of commit _[c68f187](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c68f187ffe5817f69a103c78188b3f29279ff841)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103220751425910-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2T6EVpSiGMe1YtTNCtz%2FIUH9zgatyeTWFO0uKU7wCco%3D&st=2021-03-22T07%3A48%3A00Z&se=2021-04-22T07%3A53%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 08:43 UTC, opbld34 commented
Docs Build status updates of commit _[0d2f379](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0d2f379ec50a3e8152c69c2dd39bf5a201225bb2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-6368461c)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-6368461c"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 47, Column 110**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#understand-activity-feed-notifications-and-bot-framework-notifications' in 'activity-feed-notifications-best-practices.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103220841452898-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LIFi3ChesDggeDwhHeXMdj5OCdxAVMqpwkQr%2FIm1cXs%3D&st=2021-03-22T08%3A38%3A02Z&se=2021-04-22T08%3A43%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 10:15 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that apps are not sending more than 10 notifications per minute, per user.
Have modified to "Check if the apps are sending more than 10 notifications per minute, per user.", as this is something that is not controlled by the user. The scenario is, if an app sends more than 10 notifications then the notifications are throttled.
Please let me know your thoughts.

2021-03-22 11:02 UTC, opbld34 commented
Docs Build status updates of commit _[b453fbf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b453fbfd99b2887e1f6addcf1781f57b206a2ccb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103221100480088-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ssAUgzCzMMBE%2BkogrtSnPZNa7cYBnCXrMBbvURMt%2FK0%3D&st=2021-03-22T10%3A57%3A21Z&se=2021-04-22T11%3A02%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 12:12 UTC, opbld33 commented
Docs Build status updates of commit _[ae071c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae071c801fee50d13d132eaaed0df56db3da746b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103221210455089-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D4Dh8YTJHbOWwbFKYglZw5wPefONWMoIMzkk3zOgPtw%3D&st=2021-03-22T12%3A07%3A15Z&se=2021-04-22T12%3A12%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 11:53 UTC, opbld34 commented
Docs Build status updates of commit _[464937c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/464937ccbc4b63dbd6fa65be2221b953c9353985)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103261152378724-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YQJegqlbmdEWzNCkT%2F76XIXdkXamTWWnGOZP%2FLbvquI%3D&st=2021-03-26T11%3A48%3A55Z&se=2021-04-26T11%3A53%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-26 12:10 UTC, KirtiPereira commented
Hi @Lauragra - I have incorporated your comments. Kindly let me know your comments / approval.
Thank you.

2021-03-30 01:46 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Best practices for partner apps
Do we need this H2 heading? Seems that the intent of the entire article is to cover best practices. Maybe we can remove this H2.

2021-03-30 01:47 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Activity feed notifications enable partner apps to send notifications to users. These notifications are sent as toast items and activity feed items that point users to relevant content that can be co
Do we have to refer to them as "partner apps" or are they just apps? Seems like they are "partner apps" only from the Microsoft perspective but this content should reflect the developer's perspective.

2021-03-30 01:55 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Have knowledge of the direct relationship between a notification toast or feed, and the content it is deep linked to.
For the first bullet point, is the best practice: "Make the relationship between the notification and the content it is linking to clear to the user." ("Have knowledge" is vague and not really a best practice.) I also don't find the examples in the sub-bullets clear. Maybe an actual example would help, or else can you explain them more clearly?

2021-03-30 01:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that the right pane experience in the feed is self-contained and does not break the feed experience. For example, if the notification leads to a modal or pop-up dialog, the modal must exist
Is the feed always in the right pane? What is the difference between "right pane experience" and "feed experience", or are those the same thing? Make sure this is clear. I wonder if a screen shot would help.

2021-03-30 01:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Verify that the apps are not sending more than 10 notifications per minute, per user.
Is it multiple apps? I think you can say "Verify that your app does not send more than 10 notifications...."

2021-03-30 02:00 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Ensure that the apps are performing. The time taken for an app to load is measured and can impact the user experience when a user switches between notifications in the activity feed.
Can you revise this to be more clear: "Ensure that the load time of your app does not negatively affect the experience for users when they switch between notifications in the feed."

2021-03-30 02:03 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +### Guide on feature behavior
What is the intent for this section? It's unclear. The phrase "Guide on feature behavior" doesn't quite make sense. Is this something like "Guidelines for activity feed features"?

2021-03-30 02:04 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +This section covers feature behavior that you must be aware of when working with partner apps.
This is still unclear. Is this just general things they need to be aware of, or specific actions/best practices? What do you mean by "working with partner apps"? Do you mean "developing your app"?

2021-03-30 02:05 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Understand that selecting a toast notification leads to the activity feed. To switch to an activity, select a notification in the activity feed.
What do you mean by "leads to"? Is this the user behavior or the developer? Do you mean "When a user selects a toast notification, they access the activity feed. To switch to an activity, the users selects a notification in the activity feed."

2021-03-30 02:10 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +  > The notification selection will not switch to the app.
I don't understand what this note is trying to convey, or why it's a note. I think you might be getting at something like, when the user selects a notification, they don't automatically switch to the activity feed app? Can you make this point more clear and explain why it's relevant/what the developer action should be? Note that passive voice constructions can be difficult to interpret; when possible, try to write in active voice.

2021-03-30 05:25 UTC, opbld34 commented
Docs Build status updates of commit _[d5b302f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5b302fca7ba045cb4aa4640f8366705af01d6a9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103300523366751-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nbiKNeCSGXmaV9Tm%2FODaopvjdflMzSMdf3gp12a2AfY%3D&st=2021-03-30T05%3A20%3A00Z&se=2021-04-30T05%3A25%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 07:11 UTC, opbld30 commented
Docs Build status updates of commit _[c4ceaba](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c4ceabaa1f9148476c6b19ce615fed898e77058c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103300710216830-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3wt1grvh1n9kgfd7jMTN8ZJz7A8C%2Fk5PWtvUY3Bhu00%3D&st=2021-03-30T07%3A06%3A37Z&se=2021-04-30T07%3A11%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 07:38 UTC, opbld31 commented
Docs Build status updates of commit _[efe5ae8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/efe5ae88eac2c3af8a309a55a5b41ff47c372a91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103300737446128-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HIom9ToK5QdzGld5wp8TGL%2B1JLaUra6a7AU0gbXLgdk%3D&st=2021-03-30T07%3A33%3A56Z&se=2021-04-30T07%3A38%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 12:16 UTC, opbld34 commented
Docs Build status updates of commit _[f6da9c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f6da9c8205fee0d415cd6b77224d74c066758194)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061215231615-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nRo3iK3IsxieR8%2Fm5XdCMu%2FPiL5Y8jMZ1CjIbQWsaVE%3D&st=2021-04-06T12%3A11%3A43Z&se=2021-05-07T12%3A16%3A43Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 12:19 UTC, KirtiPereira commented
@Lauragra - Thank you for your comments. I have incorporated your suggestions and am in the process of self-reviewing the document. Have also requested Nihit to review the document once before re-sharing with you. Will keep you posted.
Thank you.

2021-04-06 14:11 UTC, opbld33 commented
Docs Build status updates of commit _[a333072](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a333072088f5f95d4263f0b705ba5044bd37adc2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061410088376-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3PhVEUFdemmxIGv%2BUO%2BBJEKWv0jgcrQRIJ4TNQXk904%3D&st=2021-04-06T14%3A06%3A28Z&se=2021-05-07T14%3A11%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 10:01 UTC, srmunaka requested changes
Thanks Kirti, added a few comments about some minor edits.

2021-04-09 13:12 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
>      * The notification must not confuse the user about what they need to address or triage. For example, when a user receives a notification for approving a leave, then the notification must *@mentio
Removed the following from the sentence ... and display the requisite action buttons, such as *Approve* and *Reject*.

2021-04-09 13:20 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
>      * If the notification pertains to removal or deletion, direct users to the content indicating the action, so that they understand the outcome before taking action. For example, when removing a me
Have modified the example.

2021-04-09 13:22 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +  * The setting appears for the user only when the selected app sends a notification.
Added **notification** to the sentence.

2021-04-09 13:43 UTC, KirtiPereira commented on concepts/activity-feed-notifications-best-practices.md
> +> Design your notification such that when the users select a toast notification they access the activity feed and not the app. To switch to another activity, the user must select a notification in th
Reworded

2021-04-09 14:00 UTC, opbld31 commented
Docs Build status updates of commit _[baa2834](https://github.com/microsoftgraph/microsoft-graph-docs/commits/baa283474197891a03027a69389c31ad579b855f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104091359052093-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8WMtKCHXQtLB%2BwQrx8YGqa87YoBSExP4Fh8KWYt9M08%3D&st=2021-04-09T13%3A55%3A25Z&se=2021-05-10T14%3A00%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-09 14:02 UTC, opbld30 commented
Docs Build status updates of commit _[baa2834](https://github.com/microsoftgraph/microsoft-graph-docs/commits/baa283474197891a03027a69389c31ad579b855f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104091359161270-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q6O80kV6GHu48XjKycykb91FF8VSQArGJaYPBM799U0%3D&st=2021-04-09T13%3A57%3A47Z&se=2021-05-10T14%3A02%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 10:48 UTC, opbld32 commented
Docs Build status updates of commit _[33dca72](https://github.com/microsoftgraph/microsoft-graph-docs/commits/33dca72f3189d2f107509ed923536c7656b60e85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104121047053163-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SW25ZwdOz%2BJ1gVkchbHVjQSm9pJB7UNm2Yvif%2FvYOW4%3D&st=2021-04-12T10%3A43%3A51Z&se=2021-05-13T10%3A48%3A51Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 14:25 UTC, opbld32 commented
Docs Build status updates of commit _[8106b84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8106b8460eee590a949f60e9b9de667c01a8a116)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104121423481511-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=L7idF2xkxXbb8N31C1tJ81HWtVLhXf2Nt62TGW7m1ck%3D&st=2021-04-12T14%3A20%3A06Z&se=2021-05-13T14%3A25%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 04:51 UTC, srmunaka approved these changes

2021-04-23 12:58 UTC, KirtiPereira commented
Hi @Lauragra  - we've incorporated all your comments. Nihit has also reviewed and approved the PR. Kindly approve.
Thank you.

2021-05-12 06:18 UTC, KirtiPereira commented
@Lauragra - gentle reminder on the PR. Thanks.

2021-05-13 22:37 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Make the relationship between the notification and the content it is linking to clear to the user.
Line 15: Could you please re-phrase so its easier to understand for non-native speakers? Specially the phrase "the content it is linking to". Could you say the same in fewer words?
For instance: "its content". 
Make the relationship between the notification and its content clear to the user. 

This way its easier for non native speakers to understand and scan the doc.

2021-05-13 22:54 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience in the feed is self-contained and does not break the feed experience. For example, if the notification leads to a modal or pop-up dialog, the modal must exist onl
Line 18: Let's improve the first sentence. Could you re-phrase it to be more explicit and concise? In addition, please use **bold letters** when referring to a Graph feature, entity, method or resource and always include the link if it is the first mention.
For instance: Pop-ups and modals must not lead to the **activity feed**.

2021-05-14 00:39 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  > [!NOTE]
Let's remove the note and add the information in a sentence. We try to avoid Notes inside lists.

Suggestion:
* Verify that your app does not send more than 10 notifications per minute, per user. Notifications are throttled if the per user notification count exceeds 10.

2021-05-14 01:32 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +ms.prod: "teamwork"
Please confirm whether this should be "microsoft-teams" instead

2021-05-14 01:45 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * When the users select a toast notification they access the activity feed and not the app. To switch to another activity, they must select a notification in the activity feed.
Line 31: The prerequisite is not quite clear and it uses the user as subject. Please re-phrase using the product as subject. For instance:
"Toast notifications re-direct users to the activity feed and not to the app. To see another activity, users must select the proper notification in the activity feed."

We try to explain how the product works, so we use the product as subject.

2021-05-14 01:56 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * The notifications setting appears for the user only when the selected app sends a notification.
We avoid using verbs such as "appear" or "show up" with non-alive subjects. In this case, please re-phrase to avoid using "appears" and focusing on clarifying how the product works. Suggestion:
Users can manage notification settings only after the selected app sends a notification.

2021-05-14 02:00 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * The app icon for each notification cannot be customized, and is the one that is included in the app manifest.
Line 33: we avoid using passive voice. Please re-phrase in active voice:
The icon for each notification is included in the app manifest. Graph does not support customizing it.

2021-05-14 02:09 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * Currently, notifications can only be sent at a user level, and not at a group or a team level.
Line 34: Two observations here:
1. Using the word "currently" gives a sense of temporality. Please avoid providing such expectations in docs. 
2. Passive voice: please re-phrase using active voice:
Example:
Apps can only send notifications to users. Do not include Groups or teams as recipients.

2021-05-14 02:10 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +    > Currently, priority notifications are not supported.
Please include this in a regular bullet in the list and remove the note.

2021-05-14 02:17 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).
Line 39: please add an introduction to the bulleted list. Always set the context before a list.

2021-05-14 02:54 UTC, opbld30 commented
Docs Build status updates of commit _[190c6b0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/190c6b0dccc812b2530e351abd08ae95514c364c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105140252495466-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=P7jODooWjsDNHNbLONT6pl%2FmHwwhebEuxpGTsZyIn1E%3D&st=2021-05-14T02%3A49%3A12Z&se=2021-06-14T02%3A54%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-14 03:15 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Provide appropriate titles and descriptions for your **Activity Types**, because the setting titles are read from the app manifest. The following table provides examples of appropriate and inapprop
Line 41, second sentence: passive voice. Who reads the setting titles from the app manifest? This is the kind of misunderstandings we want to avoid. Suggestion: "The app manifest provides the setting titles to the app", or "The API reads the setting titles from the app manifest." Please re-phrase it maintaining technical accuracy, but using active voice.

2021-05-14 03:18 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +   |Use short titles, such as **@mention** and **Announcements**. | Do not use long titles, such as **User at-mentioned activity** and **Post creation activity**. |
According to [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36413), tables should have at least 2 rows. 
Suggestion: Remove the table and use an indented list instead. 
- Use short titles, such as **@mention** and **Announcements**.
- Do not use long titles, such as **User at-mentioned activity** and **Post creation activity**.

2021-05-14 03:20 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +   |Use short titles, such as **@mention** and **Announcements**. | Do not use long titles, such as **User at-mentioned activity** and **Post creation activity**. |
Please update the 3rd sentence in line 41 as well. Depending on the update you make in 2nd sentence, this 3rd one can be removed.

2021-05-14 03:23 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  | Lynne mentioned you in a message. | Try the new feature in the Cycling app! |
Same observation here, the table has only 1 item. I'd suggest an indented list as well:
- Important message: Lynne mentioned you in a conversation.
- Promotional message: Try the new feature in the Cycling app!

2021-05-14 03:24 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  > [!NOTE]
Please include a blank line between the last bullet and the Note to improve readability.

2021-05-14 03:26 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +You can simplify the user's notification experience by applying best practices that will send only the important information through your notifications.
Please re-phrase to use less words. Example:
Simplify the user's notification experience sending only important information through notifications.

2021-05-14 03:27 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  |---------------------|-------------------------|
Similar to observations above. Please change this table for an indented list and update the 3rd sentence in line 61.

2021-05-14 03:37 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Utilize the third line for the preview to give users information that allows them to gauge the importance and take action. Select a toast or mark for follow-up.
It is not clear what the "third line for the preview" is. If you are referring to a feature, property or such, please include the link. In addition, please re-phrase with less and easier words. An example could be:
"Use the third-lines in previews and provide information to determine importance and take action.

2021-05-14 03:41 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Utilize the third line for the preview to give users information that allows them to gauge the importance and take action. Select a toast or mark for follow-up.
Checking at the image, it would be better if you re-phrase:
Use the **Text Preview** section in notifications. Provide information to determine importance and take action.

2021-05-14 03:46 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  ![Notification text preview](../concepts/images/notification-preview.png)
I'd prefer if you can avoid images as screen readers cannot read them. In this case, the image is a bit blurry and the content would be already clarified with the message above.

2021-05-14 03:54 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +Activity feed notifications enable your apps to send notifications to users. These notifications are sent as toast items and activity feed items that point users to relevant content that can be consu
Top paragraphs should provide a brief explanation of what the article is about. I'd suggest moving line 13 and the list under a new subtitle (## General best practices, or such), so it is easier to scan. Users usually overlook top paragraphs when scanning.

2021-05-14 04:00 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).
Please also check the link in [localized]. It is broken in the preview tool.

2021-05-14 04:02 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +## See also
We try to avoid "See also" sections because those are usually overlooked. My advise would be to include these in a sentence after the first paragraph of the article (line 11).

You can also [send activity feed notifications](link here) to users in Microsoft Teams and [design your Microsoft Teams app](link here). 

Please check the second link as it is broken in the preview tool.

2021-05-14 04:36 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +| Bot messages are delivered as chat or channel messages. If the user's notifications for chat or channel is turned on, they trigger notifications as chat or channel notifications. </br> * *@mention*
Let's improve this table. If you are using a table to compare options or list differences, the ideal way would be adding equal amount of characteristics in each column, contrasting a similar functionality in each line.

Also, in this case, the first column has just a single row, so it is not quite following [Microsoft Writing Style](https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36413) guidelines. 

Please try to list equal amounts of characteristics and contrast a similar capacity in each line, if possible.
In addition, please avoid lists inside the table, and if you really need to use lists, please use dashes (-) instead of asterisks (*).

I strongly encourage you to invest time and re-design the table. I understand this is a significant improvement following Laura's recommendation, so let's move from better to best.

2021-05-14 04:55 UTC, isvargasmsft requested changes
@KirtiPereira great work implementing Laura's advice. 

I added more comments on top to refine some details that need attention. Main ideas:
- Please avoid using passive voice. 
- Please use less and easier words. A friendly writing helps non native speakers better understand the article and improves scannability. 
- Pay attention to broken links.
- Invest time in designing a better visual experience, specially when using tables and lists. 

Please review and feel free to ping me on the side if you have any questions. Here to help!

Kind regards, 

Isaac Vargas

2021-06-01 05:24 UTC, opbld31 commented
Docs Build status updates of commit _[2fb0b88](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fb0b88fada012ab92d99e536b9bf9efed8be0ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106010522411582-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3Tn51sGRknDdwXibn1%2BQ6Ucy5WoC%2FlDK5bFnPP%2FOtRo%3D&st=2021-06-01T05%3A19%3A15Z&se=2021-07-02T05%3A24%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 05:33 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Make the relationship between the notification and the content it is linking to clear to the user.
Thank you for the suggestion, it has been addressed.

2021-06-01 05:55 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience in the feed is self-contained and does not break the feed experience. For example, if the notification leads to a modal or pop-up dialog, the modal must exist onl
Thank you for the suggestion, it has been addressed.

2021-06-01 06:01 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * The notifications setting appears for the user only when the selected app sends a notification.
Thank you for the suggestion, it has been addressed.

2021-06-01 06:06 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * The app icon for each notification cannot be customized, and is the one that is included in the app manifest.
Thank you for the suggestion, it has been addressed.

2021-06-01 06:07 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * When the users select a toast notification they access the activity feed and not the app. To switch to another activity, they must select a notification in the activity feed.
Thank you for the suggestion, it has been addressed.

2021-06-01 06:10 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * Currently, notifications can only be sent at a user level, and not at a group or a team level.
Thank you for the suggestion, it has been addressed.

2021-06-01 06:16 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  > [!NOTE]
Thank you for the suggestion, it has been addressed.

2021-06-01 06:18 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +    > Currently, priority notifications are not supported.
Updated bullet.

2021-06-01 06:53 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  | Lynne mentioned you in a message. | Try the new feature in the Cycling app! |
Updated as suggested. Thank you.

2021-06-01 06:53 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  > [!NOTE]
Done.

2021-06-01 06:57 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +You can simplify the user's notification experience by applying best practices that will send only the important information through your notifications.
Updated.

2021-06-01 06:59 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Provide appropriate titles and descriptions for your **Activity Types**, because the setting titles are read from the app manifest. The following table provides examples of appropriate and inapprop
Updated.

2021-06-01 07:16 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  |---------------------|-------------------------|
Changes made.

2021-06-01 07:17 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +   |Use short titles, such as **@mention** and **Announcements**. | Do not use long titles, such as **User at-mentioned activity** and **Post creation activity**. |
I have updated the indented list as suggested.

2021-06-01 07:21 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Utilize the third line for the preview to give users information that allows them to gauge the importance and take action. Select a toast or mark for follow-up.
Updated as suggested.

2021-06-01 07:23 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).
Updated the sentence to set context for the indented list.

2021-06-01 07:50 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  ![Notification text preview](../concepts/images/notification-preview.png)
Removed image.

2021-06-01 07:54 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Activity feed notifications enable your apps to send notifications to users. These notifications are sent as toast items and activity feed items that point users to relevant content that can be consu
Added ##header.

2021-06-01 07:58 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +## See also
Updated the first paragraph.

2021-06-01 10:01 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +| Bot messages are delivered as chat or channel messages. If the user's notifications for chat or channel is turned on, they trigger notifications as chat or channel notifications. </br> * *@mention*
Update tab switches.

2021-06-01 10:26 UTC, opbld33 commented
Docs Build status updates of commit _[9babb4b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9babb4b0d4edd484eacac2ebadb9923ace45d0e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-ff4da835)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-ff4da835"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 61, Column 110**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#difference-between-bot-framework-messages-and-activity-feed-notifications' in 'activity-feed-notifications-best-practices.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106011023284235-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uqz14CLQIl4FksN47eTGUNmElHy7dOoH5Qt9wMuw0lk%3D&st=2021-06-01T10%3A21%3A17Z&se=2021-07-02T10%3A26%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 10:38 UTC, opbld34 commented
Docs Build status updates of commit _[b8ede9e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8ede9e15f156c88251c2f553842cdc0bf27c1b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106011035339756-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xNSqX9vlKJun4jMVgjZ6Na5hq%2FyPwt7amBwfIBzx5gA%3D&st=2021-06-01T10%3A33%3A13Z&se=2021-07-02T10%3A38%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 10:47 UTC, opbld32 commented
Docs Build status updates of commit _[e8bfdc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8bfdc66b751e253e5c95f5d7301645878c33481)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106011044383768-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=w6KX3KLGzOBijUybv7tFORuFWUC%2BDJz0sf%2Fgp0sXoac%3D&st=2021-06-01T10%3A42%3A17Z&se=2021-07-02T10%3A47%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 10:53 UTC, v-abirade commented
Hello @isvargasmsft,

Thank you for your valuable feedback. I have incorporated all your comments. 
Please note the following links would only work, once the document is merged, as they are pointing to a different repo:

- Designing your Microsoft Teams app
- Localized

Request you to please review and approve the PR.

2021-06-01 17:25 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +This article covers best practices to help you build experiences using Microsoft Teams activity feed notifications in Microsoft Graph. These best practices help you to create notifications as per the
Let's re-organize this first paragraph for scannability. My suggestion:

This article covers best practices to use Microsoft Teams activity feed notifications in Microsoft Graph. 

Use these recommendations to:
- Create call-to action notifications. 
- Request for a response. 
- Create notifications about an external event. 

You can also [send activity feed notifications] (link here ) and [design your Microsoft Teams app] (link here as well ).

2021-06-01 17:53 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +Activity feed notifications enable your apps to send notifications to users. These notifications are sent as toast items and activity feed items that point users to relevant content that can be consu
Let's re-phrase in active voice and simple words. In addition, when you have warnings it is nice to use a note. My suggestion:

Use Microsoft Teams activity feed to send notification to users and apply the following best practices:
(list of best practices here )

//At the end:

> [!NOTE]
> Microsoft Teams displays notifications in both activity feed and toast formats.

2021-06-01 20:00 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience in the feed is self-contained and does not break the feed experience. For instance any pop-ups and modals must remain in the app and never take the user to the **
Line 20: Let's re-phrase this line for clarity. Could you clarify the intention of this line? It is not clear with the current phrasing.

2021-06-01 20:42 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Verify that your app does not send more than 10 notifications per minute, per user. Notifications are throttled if the per user notification count exceeds 10.
Lets use less words in the second sentence:
Notifications will be automatically throttled if the count exceeds 10.

2021-06-02 03:19 UTC, opbld30 commented
Docs Build status updates of commit _[90f898a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90f898a823d65f5935e44b873f7af74ab16d74bc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106020318035731-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CngE7xDRk%2BXx2QiQWxTfFHS1Csy6xBXccy24MEEcybc%3D&st=2021-06-02T03%3A14%3A26Z&se=2021-07-03T03%3A19%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 03:25 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +This article covers best practices to help you build experiences using Microsoft Teams activity feed notifications in Microsoft Graph. These best practices help you to create notifications as per the
Addressed suggestion.

2021-06-02 03:28 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Verify that your app does not send more than 10 notifications per minute, per user. Notifications are throttled if the per user notification count exceeds 10.
Addressed suggestion.

2021-06-02 03:33 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Activity feed notifications enable your apps to send notifications to users. These notifications are sent as toast items and activity feed items that point users to relevant content that can be consu
Addressed suggestion.

2021-06-02 03:34 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience in the feed is self-contained and does not break the feed experience. For instance any pop-ups and modals must remain in the app and never take the user to the **
Re-phrased sentence.

2021-06-02 03:43 UTC, opbld32 commented
Docs Build status updates of commit _[036831c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/036831c2e733131b4d1525fb7795438132b39195)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106020340408694-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gnMqYiM0tySfXrMslEbLCEyRPpKZRQDOI4IMpQcjgDg%3D&st=2021-06-02T03%3A38%3A14Z&se=2021-07-03T03%3A43%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 03:48 UTC, v-abirade commented
Hello @isvargasmsft,

I have incorporated the changes as suggested. Could you please look into it and approve the same.
Thank you so much for your valued inputs.

2021-06-02 15:26 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +The requirements to use the activity feed notification API, are as follows:
Line 41: Let's re-phrase to:
Note the following requirements to use activity feed notifications API:

2021-06-02 15:30 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * The users can manage notification settings only after the selected app sends a notification.
Line 43: Same observation here. Please remove the article "the":
- Users can manage notification settings only...

2021-06-02 15:32 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * At present, the priority notifications are not supported.
Please remove "at present" as it gives the expectation that the feature will be available one day. We avoid expectations in or docs. In the future, if the feature is available, then we'll change this documentation. 

- Priority notifications are not supported.

2021-06-02 15:36 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Provide appropriate titles and descriptions for your **Activity Types** as the API reads the setting titles from the app manifest. The following list provides examples of appropriate and inappropri
Let's remove the 2nd sentence: "The following list provides examples...". I think it is not completely necessary and affects scannability.

2021-06-02 15:38 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  * Do not use long titles, such as **User at-mentioned activity** and **Post creation activity**
Don't instead of Do not. We try to keep the voice friendly. Guidance here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36389

2021-06-02 15:42 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Avoid sending notifications that are promotional in nature unless required. The notification must convey something important that the user must be aware about. The following list provides an exampl
1. ... in nature, unless require. //Add a coma, please. 
2. Notifications must convey important information for the user. // let's re-phrase for clarity.
3. Let's remove the 3rd sentence.

2021-06-02 15:57 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +The requirements to use the activity feed notification API, are as follows:
Addressed change.

2021-06-02 15:58 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * The toast notifications re-direct users to the activity feed and not to the app. To see another activity, users must select the proper notification in the activity feed.
Addressed change.

2021-06-02 15:59 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * The users can manage notification settings only after the selected app sends a notification.
Addressed change.

2021-06-02 16:00 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * At present, the priority notifications are not supported.
Addressed change.

2021-06-02 16:03 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Provide appropriate titles and descriptions for your **Activity Types** as the API reads the setting titles from the app manifest. The following list provides examples of appropriate and inappropri
Addressed.

2021-06-02 16:03 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * Do not use long titles, such as **User at-mentioned activity** and **Post creation activity**
Addressed.

2021-06-02 16:06 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Avoid sending notifications that are promotional in nature unless required. The notification must convey something important that the user must be aware about. The following list provides an exampl
Addressed.

2021-06-02 16:07 UTC, v-abirade commented
Hello @isvargasmsft,

I have incorporated the changes as suggested. Could you please look into it and approve the same.
Thank you so much for your valued inputs.

2021-06-02 16:09 UTC, opbld33 commented
Docs Build status updates of commit _[b6a0e65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b6a0e65dfe43782df2825aceb63a6abb76f71907)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021608119523-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zV%2F19YA1psF5DvtioGzBbyKcx77frrRboJA6r6%2Bw2yQ%3D&st=2021-06-02T16%3A04%3A40Z&se=2021-07-03T16%3A09%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 16:12 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Notify the user that the notifications are stored in the activity feed for 30 days.
Line 59: Are those 30 days fixed or can the developer change it? 
Let's re-phrase:
- Inform the user about the notifications storage period in the activity feed. 

If this is a fixed number, then we can include an additional sentence:
In Microsoft Teams, the storage period is 30 days.

2021-06-02 16:14 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +  > The 30 days storage limit applies to all notifications and is not specific to notifications sent through the activity feed notifications API.
Line 62: ... notifications and it's not specific...//Please add "its" instead of "is".

2021-06-02 16:17 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Notify the user that the notifications are stored in the activity feed for 30 days.
Hello @isvargasmsft,

It is a fixed number. I will make the change and keep you posted.

Thank you.

2021-06-02 16:21 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  > The 30 days storage limit applies to all notifications and is not specific to notifications sent through the activity feed notifications API.
Changed.

2021-06-02 16:23 UTC, opbld33 commented
Docs Build status updates of commit _[8b6c772](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b6c7725a1490651fc859790de698ca811ac6bd9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021622280682-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C1th3yRL4ip%2FbqdJaYVb6B2OrTo%2BLwJITJCTK20xgLs%3D&st=2021-06-02T16%3A18%3A54Z&se=2021-07-03T16%3A23%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 16:32 UTC, opbld34 commented
Docs Build status updates of commit _[16dd244](https://github.com/microsoftgraph/microsoft-graph-docs/commits/16dd2445526f6061a2f049585f62792895c3bee0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106021630339373-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8UQ0cv0tymvEbUz5304%2Bqmdp2trm95ISiMrlyIOsL58%3D&st=2021-06-02T16%3A27%3A11Z&se=2021-07-03T16%3A32%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-02 16:40 UTC, v-abirade commented
Hello @isvargasmsft,

I have incorporated your suggestions. Could you please approve the same.
Thank you so much for your time and inputs.

2021-06-02 17:04 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
Line 68: Let's improve this line for scannability:
Send directed notifications and avoid noisy messages. Users receive notifications from multiple sources across chats, channels, meetings, or other apps, therefore, don't send large volumes of non-directed notifications.

2021-06-02 17:06 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Use the third-lines in previews and provide information to determine importance and take action. Use the **Text Preview section** in notifications. Provide information to determine importance and t
Please remove the very first sentence. This was recommended previously. The second and thirst sentences are enough.

2021-06-02 17:06 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* Do not add a *period* at the end of the notification title to achieve parity with all other notification settings in Teams.
Don't instead of Do not.

2021-06-02 17:07 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +## Characteristics of activity feed notifications and bot framework messages
Let's remove "Characteristics of":
Activity feed notifications and bot framework messages

2021-06-02 17:15 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +Based on the need, the user can either use activity feed notifications or bot framework messages to notify the user. The following tabs provide the key characteristics of activity feed notifications
I think it is better to use second person here:
You can use either activity feed notifications or bot framework messages to notify users.

2021-06-02 17:41 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* allow the user to take action or triage the notification.
We avoid lists where an introductory fragment is completed by the list items below it. This can be difficult to translate. Details here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36412

In addition, please use caps to start each sentence.

2021-06-02 17:52 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +* are currently directed at a user level and are not posted broadly in a channel for all channel members to see. However, if the notification is deep linked to a channel message, then it is posted br
Please re-phrase in passive voice and break different ideas into separate sentences. In addition, please explain in which scenarios a notification will be sent to a channel. For example:

- Microsoft Teams sends activity feed notifications to users, not to channels. However, if a notification mentions or tags a channel, all channel members will see it.

2021-06-02 17:58 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +The activity feed notification API allows users to configure notifications for each **Notification type** from the app. The capability to configure a notification allows the user to customize. The us
1. "...allows users to configure preferences for each notification type from the app."
2. By user do you mean the developer or the end user? 
3. Customize what? 
4. What are double notifications?
5. "activity feed notifications API notifications" is not clear. Can we just say API notifications?

Please invest time in improving this section. Remember to write with simple words and avoid passive voice.

2021-06-02 19:29 UTC, isvargasmsft commented on concepts/activity-feed-notifications-best-practices.md
> +# [Bot framework messages ](#tab/botframeworkmessages)
If the goal is to compare the 2 features, I don't think using tabs is the best way. Please re-think this follwing Microsoft Writing Style: https://styleguides.azurewebsites.net/Styleguide/Read?id=2700&topicid=36376

2021-06-02 19:30 UTC, isvargasmsft requested changes
Hello!

Please invest more time and pay attention to details. 
1. Avoid passive voice in general. 
2. Please implement previous comments carefully, reviewing all scenarios in the doc where that comment applies. 
3. Take a detailed look at Microsoft Writing Style for ideas and reference. 

Kind regards,

Isaac Vargas

2021-06-03 04:09 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
Hi @isvargasmsft,

This is an outdated commit. Please check the latest commit and provide your feedback.
Thanks

2021-06-03 04:11 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Do not add a *period* at the end of the notification title to achieve parity with all other notification settings in Teams.
Hi @isvargasmsft,

This is an outdated commit. Please check the latest commit and provide your feedback. This comment has already been incorporated.

2021-06-03 14:31 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Improve chances of users acting on your notifications by sending relevant notifications directly. Users receive notifications from multiple sources across chats, channels, meetings, or other apps,
Updated.

2021-06-03 14:35 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Use the third-lines in previews and provide information to determine importance and take action. Use the **Text Preview section** in notifications. Provide information to determine importance and t
Updated.

2021-06-03 14:40 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Based on the need, the user can either use activity feed notifications or bot framework messages to notify the user. The following tabs provide the key characteristics of activity feed notifications
Updated.

2021-06-03 14:41 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +## Characteristics of activity feed notifications and bot framework messages
Updated as deemed fit.

2021-06-03 14:56 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* allow the user to take action or triage the notification.
Updated.

2021-06-03 15:01 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* are currently directed at a user level and are not posted broadly in a channel for all channel members to see. However, if the notification is deep linked to a channel message, then it is posted br
Updated as deemed fit.

2021-06-03 15:13 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +# [Bot framework messages ](#tab/botframeworkmessages)
Hi @isvargasmsft,

We are not comparing two features. The tabs provide usage of activity feed notifications and bot framework messages. Either of them, can be used to notify the users.

Thanks,
Abira

2021-06-03 15:15 UTC, v-abirade commented
Hello @isvargasmsft,

I have incorporated the changes, keeping in mind the purpose of the document as seems fit. Please provide your inputs. 

Thanks,
Abira

2021-06-03 15:17 UTC, opbld33 commented
Docs Build status updates of commit _[8eca853](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8eca8531b09fddfde7c4e1810a2cd3d41b6bf5d7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106031516054276-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QrqVQi5in%2FmHRAGabY%2FzgzVkNgBEcwJ5MVKXU13cayY%3D&st=2021-06-03T15%3A12%3A31Z&se=2021-07-04T15%3A17%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 15:32 UTC, opbld33 commented
Docs Build status updates of commit _[10dc906](https://github.com/microsoftgraph/microsoft-graph-docs/commits/10dc906d439de2c75471308e79862f48b759dfff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106031530520153-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=REmx3Tq4pRf%2B6CH2yQ7HyvSgNBbic2x22J%2FsBFAQRS4%3D&st=2021-06-03T15%3A27%3A20Z&se=2021-07-04T15%3A32%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 16:44 UTC, opbld33 commented
Docs Build status updates of commit _[322b9a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/322b9a2af3c005e69c0de5a98b8cf796f717b084)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106031643147107-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fh8OzrVGVSm9bLzYr54RSd3WIIwFu8Wp7PRwc0iPrEw%3D&st=2021-06-03T16%3A39%3A32Z&se=2021-07-04T16%3A44%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-03 16:51 UTC, opbld33 commented
Docs Build status updates of commit _[fa9b484](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fa9b484b3888666cac2c32c6b62f38fa0f04e875)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106031649349880-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XVs3bz9JMOPT2UBC8OoWXl9d5UGKMWwHgGfxU4jIADc%3D&st=2021-06-03T16%3A46%3A03Z&se=2021-07-04T16%3A51%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 01:34 UTC, opbld30 commented
Docs Build status updates of commit _[837512a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/837512ac0e26a44eaf2af3c97742a57218d3b6b5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106040133308804-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jNYUJaQ9sT4h6fIU15XKaPWpDdLMUOkQIDhkdl0Fpxw%3D&st=2021-06-04T01%3A29%3A54Z&se=2021-07-05T01%3A34%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-05 00:52 UTC, opbld33 commented
Docs Build status updates of commit _[f83beb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f83beb92480c86a810552656ae9d3c0d1c154533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106050051309973-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VNjIKWHjwbiKa2NuLKddDc5g%2B7TJBbZdZagRp6JheCw%3D&st=2021-06-05T00%3A47%3A57Z&se=2021-07-06T00%3A52%3A57Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-05 01:18 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Request for a response.
This second bullet point doesn't seem clear - can you provide more context? Is this about a user responding to an activity feed notification?

2021-06-05 01:20 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Use the following recommendations to:
I'm not sure that they're using the recommendations to do these things; is it more accurate that they apply the best practices to them? A possible revision would be:

These best practices apply to:
- Creating call-to-action notifications.
- Requesting responses to notifications.
- Creating notifications about external events.

In general though, I'm not sure exactly why we need this bulleted list

2021-06-05 01:25 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +You can also [send activity feed notifications](teams-send-activityfeednotifications.md) to users in Microsoft Teams and [design your Microsoft Teams app](/platform/concepts/design/design-teams-app-o
Do the best practices also apply to sending activity feed notifications? Not sure why we have a link to designing the app - how is that relevant to the article subject matter? See if this suggested revision would work here:

For details about activity feed notifications, see [send activity feed notifications]. For general app design best practices, see [design your Microsoft Teams app].

Or consider removing the second link, especially given that it takes them out of the context of Microsoft Graph.

2021-06-05 01:27 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience in the feed is self-contained. For example, any pop-ups and modals must remain in the app and not take the user to the **Activity** feed.
Do we need to say "in the feed" or is that self-explanatory? I suggest removing to eliminate repetition. Why is Activity bold and capitalized? It's not a proper noun, we can refer to it as an "activity feed".

2021-06-05 01:28 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +> Microsoft Teams displays notifications in both activity feed and toast formats.
Not sure how this is relevant and why it's being called out as a note. Do the best practices apply to both formats?

2021-06-05 01:32 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Recommendations for using activity feed notification API
How are recommendations different than best practices? Can you help to better clarify the difference between the content in this section and the previous list of "general best practices"?

2021-06-05 01:33 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +You can select one or all the recommendations to create an effective notification.
Do you really mean to say that the user only has to choose one recommendation? Would it be more clear to say something like "To create the best activity feed notification experience for your users, apply the following recommendations."?

2021-06-05 01:38 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Note the following requirements to use activity feed notifications API:
I don't know why this content is included in the Recommendations section. These seem like general points about the function and limitations of activity feed notifications. Maybe you can include this information in the introduction to the article, in this context:

When you implement activity feed notifications, keep the following points in mind:

2021-06-05 01:38 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +  * The icon for each notification is included in the app manifest. Graph does not support customizing it.
Change Graph to Microsoft Graph.

2021-06-05 01:38 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +  * Apps can only send notifications to users. Do not include Groups or teams as recipients.
Groups should be lowercase.

2021-06-05 01:40 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +### Recommendations
I wonder if we can have one consolidated list of recommendations and best practices, the list of recommendations seem like best practices.

2021-06-05 01:44 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Activity feed notifications or bot framework messages
How is this related to best practices? Is this possibly a separate article about choosing which type of notification to provide?

2021-06-05 01:46 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +The following list provides the recomended actions:
Revise the introduction to the list to give more motivation to the reader: "To ensure the best activity feed notification experience for your users, apply the following recommendations:".

2021-06-05 01:51 UTC, opbld34 commented
Docs Build status updates of commit _[209f661](https://github.com/microsoftgraph/microsoft-graph-docs/commits/209f66111927eb8ade37e8d1c05307c62fe18cce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106050149355644-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ELhTNzmYAfqEYxP5wKhRAFrxiqA9fDV0GU6%2FgfV%2Bvok%3D&st=2021-06-05T01%3A46%3A00Z&se=2021-07-06T01%3A51%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-05 01:51 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Simplify the notification experience
Why is this in a separate section and not part of the recommendation or best practices list?

2021-06-05 01:59 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Send directed notifications and avoid noisy messages. Users receive notifications from multiple sources across chats, channels, meetings, or other apps, therefore, don't send large volumes of non-d
"noisy messages" will not globalize well. Will users understand what you mean by "directed notifications"? Maybe what you mean by this bullet point is:

Send only notifications that are directly relevant to the users. For example, "Diego assigned a sales ticket to you" is a relevant message; "Joni left the sales team" is not a relevant message.

Also note that you essentially say this in the previous introductory sentence, but without the example. I recommend moving the part about the multiple introductory sources to the intro sentence: "Users receive notifications from multiple sources across chats, channels, meetings, or other apps. To simply the user experience, apply the following recommendations:"

2021-06-05 01:59 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Use the **Text Preview section** in notifications. Provide information to determine importance and take action.
Revise the second sentence: "Provide information to help the user determine the importance of the notification and take action, if necessary."

2021-06-05 02:01 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Don't add a *period* at the end of the notification title to achieve parity with all other notification settings in Teams.
Remove the italics from the word period - that should be a word that is well understood. Instead of "achieve parity", you can use simpler words "...title, to be consistent with...".

2021-06-07 11:06 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Don't add a *period* at the end of the notification title to achieve parity with all other notification settings in Teams.
Updated as suggested.

2021-06-07 12:05 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Use the **Text Preview section** in notifications. Provide information to determine importance and take action.
Updated as suggested.

2021-06-07 12:11 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Send directed notifications and avoid noisy messages. Users receive notifications from multiple sources across chats, channels, meetings, or other apps, therefore, don't send large volumes of non-d
Updated as suggested.

2021-06-07 12:14 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +The following list provides the recomended actions:
Updated as suggested.

2021-06-07 12:16 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * Apps can only send notifications to users. Do not include Groups or teams as recipients.
Updated.

2021-06-07 12:16 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +  * The icon for each notification is included in the app manifest. Graph does not support customizing it.
Updated.

2021-06-07 12:21 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +You can select one or all the recommendations to create an effective notification.
Updated.

2021-06-07 12:26 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Note the following requirements to use activity feed notifications API:
Updated as suggested.

2021-06-07 12:29 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience in the feed is self-contained. For example, any pop-ups and modals must remain in the app and not take the user to the **Activity** feed.
Addressed.

2021-06-07 12:32 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Use the following recommendations to:
Updated as suggested.

2021-06-07 12:33 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +You can also [send activity feed notifications](teams-send-activityfeednotifications.md) to users in Microsoft Teams and [design your Microsoft Teams app](/platform/concepts/design/design-teams-app-o
Updated.

2021-06-07 12:34 UTC, v-abirade commented
Edits

2021-06-07 12:37 UTC, opbld34 commented
Docs Build status updates of commit _[04ace1f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04ace1f3d1282743cb4f3ac272e756ed77245523)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071236182619-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=A%2B5HgTuIBCRk%2FNL2tvXMTGQziZrawuSEEyeS6p2cpyY%3D&st=2021-06-07T12%3A32%3A44Z&se=2021-07-08T12%3A37%3A44Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 16:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Creating call-to-action notifications.
Please restore the bulleted list here. The bulleted items don't need to end in periods.

2021-06-07 16:58 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +For more details about activity feed notifications, see [send activity feed notifications].
Please restore the actual link here, you need the file path in parentheses after the brackets.

2021-06-07 17:02 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Toast notifications re-direct users to the activity feed, not to the app. To see another activity, users must select the proper notification in the activity feed.
FYI, it is not Microsoft style to use a hyphen with the "re" prefix: https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/hyphens#prefixes. Can you clarify the word "proper" in the second sentence? Do you mean something like "correct"? Or do you mean "associated", perhaps?

2021-06-07 17:34 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Toast notifications re-direct users to the activity feed, not to the app. To see another activity, users must select the proper notification in the activity feed.
updated.

2021-06-07 17:34 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +For more details about activity feed notifications, see [send activity feed notifications].
Updated

2021-06-07 17:35 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Creating call-to-action notifications.
Updated

2021-06-07 17:39 UTC, opbld32 commented
Docs Build status updates of commit _[1f844aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f844aa4d813d2683109d9f7b3d86ae1661d72b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071738213265-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SKhwB897CUCpX9y2GmDMjya%2F80Cb%2BpBq69ch3Uop2cA%3D&st=2021-06-07T17%3A34%3A50Z&se=2021-07-08T17%3A39%3A50Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 17:54 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +For more details about activity feed notifications, see [send activity feed notifications](#activity-feed-notifications).
Was the intent to link to something external? This link is currently going to a section of the article. If you're just linking to a section within the article, I suggest removing this cross-reference.

2021-06-07 17:56 UTC, opbld31 commented
Docs Build status updates of commit _[cf6eb66](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf6eb6639fec8e1298caa652c25272a5c949a822)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071755162951-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K3ILsJ2%2FYSlT0NIw0T6EonLCBS%2FMaXiFLorrGTDIPyc%3D&st=2021-06-07T17%3A51%3A46Z&se=2021-07-08T17%3A56%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 17:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +## Recommendations
I still am not clear about why we are separating "best practices" from "recommendations". Can these be covered in one section? I don't see best practices as being different than recommendations.

2021-06-07 17:57 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +> Microsoft Teams displays notifications in both activity feed and toast formats.
I still don't know why this note is here, it does not seem to apply to the previous bullet?

2021-06-07 18:00 UTC, opbld32 commented
Docs Build status updates of commit _[73eceb2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73eceb25be71b65f719c8e2fda31a4bf86c92a03)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071758519542-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Rp%2FoTDe7mYltPCfc1dRoAVdOiuFUixWyCI1iGF63vaw%3D&st=2021-06-07T17%3A55%3A36Z&se=2021-07-08T18%3A00%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-07 18:01 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Based on the need, you can use either activity feed notifications or bot framework messages to notify users.
To better relate this to the bullet point in the previous section, should you reiterate that they should not use both types of notifications, and they should choose the right type of message?

2021-06-07 18:02 UTC, opbld34 commented
Docs Build status updates of commit _[8827420](https://github.com/microsoftgraph/microsoft-graph-docs/commits/88274204c50b62849d927f789eb447d9cae71d91)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106071800288749-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AJm0asS1DRUBgXe7Laa5cnuJV4T6glWRJyD5fm7RvRw%3D&st=2021-06-07T17%3A57%3A24Z&se=2021-07-08T18%3A02%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-09 12:13 UTC, srmunaka requested changes

2021-06-09 12:13 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience is self-contained. For example, any pop-ups and modals must remain in the app and not take the user to the **activity feed**.
Can we remove 'and must not take the user to the activity feed'? This will be confusing for developers. Can we stop at ' ... must remain in the app'.

2021-06-09 12:13 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +> Microsoft Teams displays notifications in both activity feed and toast formats.
I don't see any specific to reason to make this a note either, it is something that developers should be aware of and we see that it's not obvious to them sometimes.

2021-06-09 12:13 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +## Recommendations
The intent in the original draft from December (where these sections were titled differently) was to highlight that the first set were requirements and necessary, and the second set were optional but good practices. 

@v-abirade I agree that this can be consolidated now as the messaging and the content has changed over iterations.

2021-06-09 12:13 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Provide appropriate titles and descriptions for your **Activity Types**. Use short titles, such as **@mention** and **Announcements**. Avoid long titles, such as **User at-mentioned activity** and
Is there a reason this image was removed?

![image](https://user-images.githubusercontent.com/78961095/121351928-e9f6e700-c949-11eb-8a71-91c2c828ffef.png)

2021-06-09 12:13 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* Make the relationship between the notification and its content clear to the user. For example, when a user receives a notification for approving a leave, the notification should redirect them to th
Is there a reason this image was removed? [or am I just not seeing it?]

2021-06-13 08:18 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Make sure that the feed experience is self-contained. For example, any pop-ups and modals must remain in the app and not take the user to the **activity feed**.
Updated suggestion.

2021-06-13 08:19 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Apps can only send notifications to users. Do not include groups or teams as recipients.
Updated suggestion

2021-06-13 08:41 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +For more details about activity feed notifications, see [send activity feed notifications](#activity-feed-notifications).
Updated suggestion.

2021-06-13 08:48 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +## Recommendations
Updated suggestion.

2021-06-13 08:56 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Based on the need, you can use either activity feed notifications or bot framework messages to notify users.
Updated suggestion

2021-06-13 10:16 UTC, opbld31 commented
Docs Build status updates of commit _[7c125b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c125b74564fe2f372b3e097d8095614fb53041d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-6474f029)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-6474f029"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 26, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'concepts/images/notificationsapibestpractice2.PNG'.`````
 - **Line 30, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'concepts/images/notificationsapibestpractice3.PNG'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131015038543-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WWreYuq1dMR1sW%2BDAaeKa%2BAEBqBc106Tu1yXpOABdQw%3D&st=2021-06-13T10%3A11%3A50Z&se=2021-07-14T10%3A16%3A50Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 10:18 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Make the relationship between the notification and its content clear to the user. For example, when a user receives a notification for approving a leave, the notification should redirect them to th
Updated images. Need to discuss the preceding image.

2021-06-13 10:31 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Provide appropriate titles and descriptions for your **Activity Types**. Use short titles, such as **@mention** and **Announcements**. Avoid long titles, such as **User at-mentioned activity** and
Added image

2021-06-13 10:32 UTC, opbld32 commented
Docs Build status updates of commit _[4d53956](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d53956c470942980a920875cd915799be1116ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-8f165e2e)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-8f165e2e"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 30, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/images/notificationsapibestpractice3.PNG'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131030301048-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FRa2M0weSkZFmUbw54NUIJt9fAFjhpzswK7zFh%2FmJ00%3D&st=2021-06-13T10%3A27%3A08Z&se=2021-07-14T10%3A32%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 10:36 UTC, opbld32 commented
Docs Build status updates of commit _[79a3ea5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/79a3ea59f8a7b8c641794681af1bf0350b262690)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131034275050-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=TAfZqJgmpr6CmcqhPh2GKiKaO2BLPqH2IMUmGY%2BFFAM%3D&st=2021-06-13T10%3A31%3A10Z&se=2021-07-14T10%3A36%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 10:43 UTC, opbld32 commented
Docs Build status updates of commit _[c2ccc3c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2ccc3cbe56228dd59a523f83ebd229ee1902717)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131042005147-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yRtftVhtyeJCiZZABVElS20AA8qiPEAkVpZrJBT%2FMWY%3D&st=2021-06-13T10%3A38%3A39Z&se=2021-07-14T10%3A43%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 10:48 UTC, opbld34 commented
Docs Build status updates of commit _[6b76115](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b76115765678133d04fdcb8a694fd246188dbc6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-c2c37a79)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-c2c37a79"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/notificationsapibestpractice2.PNG'.`````
 - **Line 30, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../images/notificationsapibestpractice3.PNG'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131046535792-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GIdLOtCUTt6qXxjlJkBD9o5eSBcME3xRnWIe2i0pCF0%3D&st=2021-06-13T10%3A43%3A22Z&se=2021-07-14T10%3A48%3A22Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 10:51 UTC, opbld33 commented
Docs Build status updates of commit _[3bf91a7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3bf91a72fee3788767617973f366068cffa6cd66)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131050083463-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qqcEhFIgV3ET1YDu85pR6zp%2FukvyioOBTUpyGfcbcDc%3D&st=2021-06-13T10%3A46%3A22Z&se=2021-07-14T10%3A51%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 11:11 UTC, opbld32 commented
Docs Build status updates of commit _[5f66d7e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f66d7e0a10c39c410b1259e41e0382146c1af14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131109286765-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Nant1VfD2IvMjtpzkbI%2BYzOU9RF0DzWX0iC%2FUsy4g6Q%3D&st=2021-06-13T11%3A06%3A09Z&se=2021-07-14T11%3A11%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 11:18 UTC, opbld32 commented
Docs Build status updates of commit _[d2906bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d2906bbe8de0ecfc28c38b9906c8c22098d2f500)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131116458323-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hbmflH9F%2BjvJioP8SCrDRspc37OKtLdhFubRvK5HPng%3D&st=2021-06-13T11%3A13%3A15Z&se=2021-07-14T11%3A18%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 11:22 UTC, opbld30 commented
Docs Build status updates of commit _[a839a92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a839a9283d2343bdffe071251698fa60dc0c7b99)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.PNG) | :white_check_mark:Succeeded | |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131120424572-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lCZW0RyTGxWDbxIg9oZhC7YNI9j2Y%2BoaS8ca087zlqs%3D&st=2021-06-13T11%3A17%3A18Z&se=2021-07-14T11%3A22%3A18Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-13 11:27 UTC, opbld31 commented
Docs Build status updates of commit _[4dbfafb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4dbfafb7d2c18c8fb3b7c5b13e52186e2d48685b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106131125565169-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2C84XwjbBisl4gOoEokuUxEvWW396BQuXf7dzqgungk%3D&st=2021-06-13T11%3A22%3A22Z&se=2021-07-14T11%3A27%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 04:16 UTC, opbld30 commented
Docs Build status updates of commit _[0ba7e9a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ba7e9a50a613280551451663e039730e2856f8b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-d87e4497)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-d87e4497"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 26, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'images/notificationsapibestpractice2.png'.`````
 - **Line 30, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'images/notificationsapibestpractice3.PNG'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106140414349142-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ej0xvGaC%2FHtJZDzlq6vcSvvLbIaZcLKTIsspd%2Ft31uU%3D&st=2021-06-14T04%3A11%3A17Z&se=2021-07-15T04%3A16%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 04:28 UTC, opbld30 commented
Docs Build status updates of commit _[e580eaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e580eaa9244a1bfbfb0b2b051c0bc089c0d57cc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106140427311251-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ym5PGRNCje6nX%2B70VhsPa1R53vPuwt75XWE%2FYCE3K0k%3D&st=2021-06-14T04%3A23%3A55Z&se=2021-07-15T04%3A28%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 04:42 UTC, opbld30 commented
Docs Build status updates of commit _[83aed23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83aed231dd2b55abdd1b0be64e5b667b9615c9ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-0d2cc4db)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-0d2cc4db"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 26, Column 14**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '~/images/notificationsapibestpractice2.png'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106140441320947-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mWygdqEMzYarCuc2x8J0uq%2F4b47H92XxaATnwLoQ2eY%3D&st=2021-06-14T04%3A37%3A48Z&se=2021-07-15T04%3A42%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-14 04:46 UTC, opbld31 commented
Docs Build status updates of commit _[aa45e28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa45e28682e5e106b1d5e71f3faa0abab1e907b3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106140445245596-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f7JLm%2F%2BmDGANdJaYhClfs1MlFZMc57n%2BI6uAouN7gds%3D&st=2021-06-14T04%3A41%3A47Z&se=2021-07-15T04%3A46%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 12:31 UTC, opbld33 commented
Docs Build status updates of commit _[0990bb3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0990bb3647dfed6d1a260cf218657daadf129d07)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151229354476-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yfC%2B9yJnZ9HJJe35BySxg59lPPO4gCHGhfN4ik1dz6M%3D&st=2021-06-15T12%3A26%3A07Z&se=2021-07-16T12%3A31%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 12:32 UTC, opbld32 commented
Docs Build status updates of commit _[b25bdb6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b25bdb66d0fc4b46c9c0b8ec6cc0b7056a726462)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-b1941877)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-b1941877"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 18, Column 1**: **[Warning-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````
 - **Line 30, Column 1**: **[Warning-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````
 - **Line 34, Column 1**: **[Warning-[code-block-indented](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Indented code blocks aren't allowed. Use a Markdown code block surrounded by triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151231189523-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KqbzN8mO%2B7bs1BjugWS44GLsazyfYOokQM9079YDOmY%3D&st=2021-06-15T12%3A27%3A46Z&se=2021-07-16T12%3A32%3A46Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 12:46 UTC, opbld30 commented
Docs Build status updates of commit _[d92a84b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d92a84b71a79b7f87d2568940a66c6777a16fd90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151245004157-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yog0suu02b3p1kLkEnWnVHgaVrbvuGbROF48zgTfEAk%3D&st=2021-06-15T12%3A41%3A17Z&se=2021-07-16T12%3A46%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 12:51 UTC, opbld34 commented
Docs Build status updates of commit _[855a7b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/855a7b669eff8e0ffd675a0af10adfaad802bc48)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151250095811-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nORt%2Bf3fRv%2FDrcljabcg4OOrOjgmmyUMRWf5BjowGyQ%3D&st=2021-06-15T12%3A46%3A40Z&se=2021-07-16T12%3A51%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 12:56 UTC, opbld33 commented
Docs Build status updates of commit _[8a40f8b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a40f8bc36f5ecbff38ce11556d229cac0630928)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-f681dc81)
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-f681dc81"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 18, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/activityfeednotification.PNG'.`````
 - **Line 30, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/notificationsapibestpractice2.png'.`````
 - **Line 34, Column 5**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/notificationsapibestpractice3.PNG'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151255051851-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yZwwUWhyvHvCbArLIZnwvNJ69eIhvS89qelHv00LdL0%3D&st=2021-06-15T12%3A51%3A26Z&se=2021-07-16T12%3A56%3A26Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 13:20 UTC, opbld33 commented
Docs Build status updates of commit _[ae2d0eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae2d0eb039154c5adc05934b8f1b3fec9990f0a4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-d40c96b0)
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/activity-feed-notification.png?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-d40c96b0"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 18, Column 1**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/activityfeednotification.PNG'.`````
 - **Line 30, Column 15**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/notificationsapibestpractice2.png'.`````
 - **Line 34, Column 5**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './images/notificationsapibestpractice3.PNG'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151318262481-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XJWn6rTESjBmUSbHYK7faZe2JjFVLxr%2Bh1NtnBg0zpM%3D&st=2021-06-15T13%3A15%3A03Z&se=2021-07-16T13%3A20%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 13:26 UTC, opbld33 commented
Docs Build status updates of commit _[4c5f395](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4c5f3955ced11ed5f4042f9e01b2ba3b07fc0909)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151325186053-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=osKiJST2H6F1THYDwFsEqo0RoUkh1PhFJzYoPqflL00%3D&st=2021-06-15T13%3A21%3A46Z&se=2021-07-16T13%3A26%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-15 13:29 UTC, v-abirade commented
Hi @srmunaka,

Please review the document. I have incorporated the changes.

2021-06-15 14:28 UTC, srmunaka approved these changes
Thanks Abira, I have some minor suggestions (a typo and a minor edit) but this looks good to me otherwise.

2021-06-15 14:28 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +These notifications address users, not channels, unless the nofication includes a mention to a channel.
This appears to be a typo 'notification'. 
Additionally, since channel targeting is being launched as a feature I suggest removing this line since it will have to be modified in 2-3 weeks anyway.

2021-06-15 14:28 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +The activity feed notifications API allows users to configure notifications for each **Notification type** from the app. The capability to configure, allows the user to customize a notification.
from notification settings. 

This should suffice, the rest of the bullet can be removed.

2021-06-15 14:59 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +These notifications address users, not channels, unless the nofication includes a mention to a channel.
Terribly sorry for the typographical error, thank you.
Suggestion updated.

2021-06-15 15:01 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +The activity feed notifications API allows users to configure notifications for each **Notification type** from the app. The capability to configure, allows the user to customize a notification.
Suggestion updated

2021-06-15 15:07 UTC, opbld30 commented
Docs Build status updates of commit _[707cd00](https://github.com/microsoftgraph/microsoft-graph-docs/commits/707cd0039a5a36b1115c0d0b8bfd1b3942e4ea75)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106151505361573-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Otc5zyFeF7st88YY4OiHj1rHCdxcOfNGjZzbXrVUwyM%3D&st=2021-06-15T15%3A02%3A09Z&se=2021-07-16T15%3A07%3A09Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 02:57 UTC, opbld31 commented
Docs Build status updates of commit _[c180da1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c180da17279aaa5489a632430da24e65414c0533)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106170255497132-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OEejhNi%2BMwffpZ5SUyoPQ7dksnnEGfMiyOITEz3AgmY%3D&st=2021-06-17T02%3A52%3A54Z&se=2021-07-18T02%3A57%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-17 02:59 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +     ![best practices](./images/best-practices.png)
This was not an image before. Why is it an image now? Note that content in images is not accessible. You need to ensure that you convey the content in such a way that it can be consumed by a screen reader. I recommend that you restore the original text which had the examples as text and not images. Also a general comment about alt text - it needs to clearly describe the meaning that is conveyed in the image. If you really wanted to use an image here, your alt text would need to say something like: "An image showing titles that apply the best practices and titles that don't. @mentions and Announcements are appropriate titles, User at-mentioned activity and ... are not appropriate titles." I don't think you want to say all that in alt text so you should just say it in text. ;)

2021-06-17 13:29 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +     ![best practices](./images/best-practices.png)
I have removed the image. Please approve the PR.

2021-06-17 13:30 UTC, opbld32 commented
Docs Build status updates of commit _[b645fc1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b645fc17fc60d6e07ba322d20e60940023747aa5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106171328585511-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wiUuXeMEhP2aalD4BqD7rL8NJn%2BDVGz6i0VJiXDcTjM%3D&st=2021-06-17T13%3A25%3A52Z&se=2021-07-18T13%3A30%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 04:09 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* Localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).
Please check the localized link and verify that it's correct - I can't verify it on the review site or by going to live site.

2021-06-18 04:10 UTC, opbld34 commented
Docs Build status updates of commit _[e4b6ecc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e4b6ecc329e7ce8cf07aa9f0fa4d210bb75e615c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106180408342228-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ySHwfiMeeUqea38Mq%2FfgQY2HTjt5LO12ZAxYvdX0X3s%3D&st=2021-06-18T04%3A05%3A10Z&se=2021-07-19T04%3A10%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 04:11 UTC, opbld32 commented
Docs Build status updates of commit _[2d89b65](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d89b65e859f668a5ad5a2f02d8e996b8af78aad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-fbae4f2a)
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-fbae4f2a"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 42, Column 110**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#activity-feed-notifications-or-bot-framework-messages' in 'activity-feed-notifications-best-practices.md', did you mean '#activity-feed-notifications-vs-bot-framework-messages'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106180409104225-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mzcKs1KWNdpS4tILYybDTMPx0clwe%2FY6iOkMjIvt2tc%3D&st=2021-06-18T04%3A06%3A36Z&se=2021-07-19T04%3A11%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 04:12 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Apply the following best practices to your activity feed notifications:
I separated these into a different bulleted list because they read like actual best practices, not 'points to keep in mind." I'm not clear, however, why these points are here and not in the section "Enhance the notification experience". Can we move these bullets into that section and rename the section "Notification best practices"?

2021-06-18 04:14 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +The activity feed notifications API allows users to configure notifications for each **Notification type** from notification settings.
Do you need to explain what Notification types are? Is that text bold because it's referring to something the UI? Or can it just be a generic reference to notification types?

2021-06-18 04:17 UTC, opbld31 commented
Docs Build status updates of commit _[23f3361](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23f3361111d227c8d8eafc303de75f48ee7276ce)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) | [Details](#user-content-b344a0ed4809803eb0de207b8d4b549d-c281fe7f)
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

<a id="b344a0ed4809803eb0de207b8d4b549d-c281fe7f"></a>
### [concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md)
 - **Line 42, Column 110**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#activity-feed-notifications-or-bot-framework-messages' in 'activity-feed-notifications-best-practices.md', did you mean '#activity-feed-notifications-vs-bot-framework-messages'?`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106180415387068-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=n%2BRaI5PNVa2uJHuAFkib2YOYjz98Nwf96Wj2QYkSiNg%3D&st=2021-06-18T04%3A12%3A32Z&se=2021-07-19T04%3A17%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-18 04:18 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Users could receive double notifications from the app. The app can send bot notifications to chats or channels and also to activity feed notifications API. *Send double notifications only if the scen
I'm unclear about this section - is it a caution, i.e. don't send double notifications? What scenarios require the app to send double notifications? How does this information help the developer decide whether to implement an activity feed notification instead of a bot framework message? Do you mean to say something like: "If you use activity feed notifications, be aware that your app might send double notifications, if it sends bot notifications to chats or channels and also to the activity feed."

2021-06-18 04:19 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +You can update an existing activity feed notification instead of creating a new notification by using the `chainId` parameter.
Not sure if this is relevant from the context of best practices - is there a recommendation to do this? Do you need to provide a link for more details?

2021-06-18 04:19 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +The activity feed notifications API allows users to configure notifications for each **Notification type** from notification settings.
Developers have to define each notification type in he manifest when on-boarding. Details here: https://docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications
We could also call it _Activity Types_ if necessary. cc. @v-abirade 

![image](https://user-images.githubusercontent.com/78961095/122505667-71171f80-d01a-11eb-8ea6-31e7072bdc9c.png)

2021-06-18 04:21 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +Bot messages are delivered as chat or channel messages. If the users' notifications for chat or channel are turned on, they trigger notifications as chat or channel notifications:
I wonder if we can reduce the number of occurrences of "notifications" in the second sentence. Maybe this is what you mean to say: "If the user turns on chat or channel notifications, the notifications are sent as chat or channel messages."

2021-06-18 04:22 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* *@mention* the name of the user for the notification to appear in the activity feed.
The preceding sentence does not introduce this bulleted list. Is this first bullet a best practice/recommendation?

2021-06-18 04:24 UTC, Lauragra commented on concepts/activity-feed-notifications-best-practices.md
> +* It is useful if the alert is consumed as a chat or channel message or is consumed broadly. For example, message is consumed by all channel members.
It's hard to tell how this bullet point is related. Can you please clarify what you mean to say here? Is this a recommendation that chat and channel bot messages go to all chat and channel messages? In general, can you add any text here that helps users decide when to use bot messages instead of activity feed notifications?

2021-06-18 04:30 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +Users could receive double notifications from the app. The app can send bot notifications to chats or channels and also to activity feed notifications API. *Send double notifications only if the scen
@v-abirade this phrasing makes sense to me:

""If you use activity feed notifications, be aware that your app might send double notifications, if it sends bot notifications to chats or channels and also to the activity feed."

2021-06-18 04:34 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +You can update an existing activity feed notification instead of creating a new notification by using the `chainId` parameter.
"The activity feed notification API can send either delegated or application-only calls. In delegated calls, the sender of the notification appears as the user who initiated the notification, for example, *John Doe*, and in application-only the sender appears as the app, for example, *Contoso*."

@v-abirade we can strengthen this by adding a line to the effect of "Use delegated notifications create a superior notification experience".

2021-06-18 04:47 UTC, srmunaka commented on concepts/activity-feed-notifications-best-practices.md
> +* *@mention* the name of the user for the notification to appear in the activity feed.
This is intended to help developers understand how bot notifications differ from activity feed notifications.

2021-06-21 14:24 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +The activity feed notifications API allows users to configure notifications for each **Notification type** from notification settings.
Changed to **Activity Types**

2021-06-21 14:26 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* Localize the content in a notification toast or feed. The localization happens only if the app’s content is [localized](/platform/concepts/build-and-test/apps-localization).
This link will not appear in the review site. We can check the link post it gets merged.

2021-06-21 14:40 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Apply the following best practices to your activity feed notifications:
Edited

2021-06-21 14:47 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Users could receive double notifications from the app. The app can send bot notifications to chats or channels and also to activity feed notifications API. *Send double notifications only if the scen
Updated as suggested.

2021-06-21 14:51 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +You can update an existing activity feed notification instead of creating a new notification by using the `chainId` parameter.
Updated.

2021-06-21 14:57 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +Bot messages are delivered as chat or channel messages. If the users' notifications for chat or channel are turned on, they trigger notifications as chat or channel notifications:
Updated

2021-06-21 15:03 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* It is useful if the alert is consumed as a chat or channel message or is consumed broadly. For example, message is consumed by all channel members.
The users can use either activity feed notifications or bot framework messages. The bullets highlights characteristics of bot framework messages. Hence not making any changes.

2021-06-21 15:05 UTC, v-abirade commented on concepts/activity-feed-notifications-best-practices.md
> +* *@mention* the name of the user for the notification to appear in the activity feed.
Not making any amends.

2021-06-21 15:15 UTC, opbld31 commented
Docs Build status updates of commit _[791b14e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/791b14e8d4bfec8d31d377d00022ce5fb3120dd4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106211512298314-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YVJ9OTJe6E7eHfdfePEhQ1pqVd236ZAga9g3APPJ%2FB0%3D&st=2021-06-21T15%3A10%3A34Z&se=2021-07-22T15%3A15%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:02 UTC, opbld34 commented
Docs Build status updates of commit _[c2f3f7b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c2f3f7bf6eddb310b70f9329e0cb63b5b6774d90)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220159086183-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=iFxCx000gn3jDXr307bX03dFm5%2BkhSqlPqEb0qIsMXY%3D&st=2021-06-22T01%3A57%3A03Z&se=2021-07-23T02%3A02%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:03 UTC, Lauragra approved these changes

2021-06-22 02:03 UTC, opbld31 commented
Docs Build status updates of commit _[2c41322](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2c41322d88acffbd40e512d07179b925f39b37c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220201590940-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zgQIUPhGLakHRYiPudgs06XYCrbrxSzOC8Seo%2BN7PSA%3D&st=2021-06-22T01%3A58%3A56Z&se=2021-07-23T02%3A03%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:06 UTC, opbld30 commented
Docs Build status updates of commit _[c138d81](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c138d8120706246b0445919139cf42a4fc45d585)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220202568627-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DoohCVodqkaP5wE7vPXfnlOFTqDsIlLsLFLuhQjuT60%3D&st=2021-06-22T02%3A01%3A39Z&se=2021-07-23T02%3A06%3A39Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:08 UTC, opbld31 commented
Docs Build status updates of commit _[1058deb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1058deb0cd6dc58ba1c649f62a06b33e620175b0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/activity-feed-notifications-best-practices.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/activity-feed-notifications-best-practices.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/activity-feed-notification.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/activity-feed-notification.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |
[concepts/images/best-practices.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/best-practices.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/best-practices.png?branch=pr-en-us-11609) |
[concepts/images/notification-preview.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notification-preview.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notification-preview.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice1.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice1.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice1.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice2.png](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice2.png) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice2.png?branch=pr-en-us-11609) |
[concepts/images/notifications-api-best-practice3.PNG](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/images/notifications-api-best-practice3.PNG) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/images/notifications-api-best-practice3.png?branch=pr-en-us-11609) |
[concepts/teams-send-activityfeednotifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/teams-send-activityfeednotifications.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/teams-send-activityfeednotifications?branch=pr-en-us-11609) |
[concepts/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/notificationAPIguidelines/concepts/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/activity-feed-notifications-best-practices?branch=pr-en-us-11609) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106220200076211-11609%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fgk%2Fjxqro4pWGzNmwKNQW4BfpU3r3iRNbgKnhKthhV0%3D&st=2021-06-22T02%3A03%3A21Z&se=2021-07-23T02%3A08%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-22 02:09 UTC, merged