Update print job update documentation
microsoftgraph/microsoft-graph-docs pull request #11616
Opened 2021-02-10 22:10 UTC by nilakhan

2021-02-10 22:11 UTC, opbld33 commented
Docs Build status updates of commit _[0ce0eaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0ce0eaa609505dce723e188ad5ffaf0dd11ef943)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-b3695e24)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-b3695e24)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-b3695e24"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-b3695e24"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102210144968-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NSGbRdPSitihUSG0zyw%2FRmijvu7PGHV8q%2BgvO%2FMx7pQ%3D&st=2021-02-10T22%3A06%3A21Z&se=2021-03-13T22%3A11%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 23:14 UTC, opbld34 commented
Docs Build status updates of commit _[d54f8d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d54f8d59ecac810b90eeb915a934c0cd40cfc111)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-130a8900)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-130a8900)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-130a8900"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-130a8900"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102313217211-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HF%2BX2f9UfQmLCGUv6rgZijTwUMLEZUjtPhK2hdIcfxU%3D&st=2021-02-10T23%3A09%3A29Z&se=2021-03-13T23%3A14%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-10 23:15 UTC, opbld31 commented
Docs Build status updates of commit _[4faa4e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4faa4e5b9286658ab66b51a1a26e6e91aaf9ab22)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-d8dbcf62)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-d8dbcf62)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-d8dbcf62"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-d8dbcf62"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102102314467616-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BDCkZAnHIil3Je3OG%2BDvs0618dR2COBbZFxtt510zgQ%3D&st=2021-02-10T23%3A10%3A49Z&se=2021-03-13T23%3A15%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 03:12 UTC, opbld32 commented
Docs Build status updates of commit _[22461bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22461bb5f9274ceab292abe78c70dc7719e04465)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-3ec63d0e)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-3ec63d0e)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-3ec63d0e"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-3ec63d0e"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110311140565-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VCjcLVKnW%2FP%2FW3CsbzgFhU0DrAXgNrW%2F0BfViKIpU6M%3D&st=2021-02-11T03%3A07%3A20Z&se=2021-03-14T03%3A12%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 03:14 UTC, opbld33 commented
Docs Build status updates of commit _[04068f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/04068f88062100fa0bebf819892839ab4b47a7ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-1022a05c)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-1022a05c)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-1022a05c"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-1022a05c"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110313015435-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1A14Z5nv65cZMW0LTr7CW3v87WMyI7d0JEGHE%2FryTME%3D&st=2021-02-11T03%3A09%3A12Z&se=2021-03-14T03%3A14%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-11 05:33 UTC, opbld33 commented
Docs Build status updates of commit _[e97feb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e97feb8d59c548a289cf234dd426ce62d83b4860)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-be8ae97d)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-be8ae97d)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-be8ae97d"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-be8ae97d"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102110532069402-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=22qnRVqD677cHITd38MHd6H8hK20HAjCxl9h%2FcK05LA%3D&st=2021-02-11T05%3A28%3A23Z&se=2021-03-14T05%3A33%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 02:13 UTC, opbld33 commented
Docs Build status updates of commit _[cf51541](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cf51541a6cba5978ff174ff2c1e78a734ab6e6e9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f6c90cbe)

<a id="f6c90cbe"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delays. You might have content issues that were not reported. To retry validation, close and re-open your PR, or rebuild your branch via Docs Portal (requires admin permissions). If you need admin help or if you continue to see this message, file an issue via https://SiteHelp.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120205434339-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aVHxLIvp1XCTa5vlDS3GlUQ4ZPyBio5B8S0Jbctm%2BPk%3D&st=2021-02-12T02%3A08%3A33Z&se=2021-03-15T02%3A13%3A33Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 02:21 UTC, opbld31 commented
Docs Build status updates of commit _[6e47873](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e4787328785778329c560e5b651a6699112947e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-20deaaaf)

<a id="20deaaaf"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delays. You might have content issues that were not reported. To retry validation, close and re-open your PR, or rebuild your branch via Docs Portal (requires admin permissions). If you need admin help or if you continue to see this message, file an issue via https://SiteHelp.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120206414543-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ulfRlVlpx%2B1nBHmQApQb6IfXpza2t1Bw03oRL%2F%2BpraQ%3D&st=2021-02-12T02%3A16%3A08Z&se=2021-03-15T02%3A21%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 04:40 UTC, opbld33 commented
Docs Build status updates of commit _[bf0a0fb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf0a0fb2e6f5901d92b9359d7f79711b78f3ef72)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-f2c22ee3)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-f2c22ee3)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-f2c22ee3"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-f2c22ee3"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120439382436-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FkOzG26ihgwqmvCJ1C4jZIJapjC3HLwRrkPhMwhGiXw%3D&st=2021-02-12T04%3A35%3A49Z&se=2021-03-15T04%3A40%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 04:46 UTC, opbld34 commented
Docs Build status updates of commit _[f9be86a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9be86a752f7103d2e765c347e7d7404b692ecc2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-6fd1989a)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-6fd1989a)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="5dd27ba9-6fd1989a"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-6fd1989a"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102120444585598-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BsZzn3lrKVDbmsKrAk0wBxl8Ym0AouPNHIGYUC%2FfxSg%3D&st=2021-02-12T04%3A41%3A14Z&se=2021-03-15T04%3A46%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-12 20:19 UTC, tomsato-ms approved these changes

2021-02-15 20:25 UTC, opbld31 commented
Docs Build status updates of commit _[816dac0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/816dac0e37fff70c45de3b0181b079fc87cd362b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-794b2948)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-794b2948)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-794b2948)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="b2eff973-794b2948"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-794b2948"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

<a id="dfa51fe2-794b2948"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Update printJob configuration - Microsoft Graph beta' is duplicated in: 'beta/api/printjob-update.md(2,8), beta/api/printjob-update-configuration.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Update the configuration of a print job' is duplicated in 'beta/api/printjob-update-configuration.md(3,14)', 'beta/api/printjob-update.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102152024421144-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1hROVnZdacxiUDcXqQ3Q5F2qSYnvxy7bRYIyULF4Lw8%3D&st=2021-02-15T20%3A20%3A52Z&se=2021-03-18T20%3A25%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 20:29 UTC, Lauragra commented on api-reference/beta/api/printjob-update-configuration.md
> +Updating a print job configuration will only succeed if a [printTask](../resources/printTask.md) in a `processing` state, started by a trigger that the requesting app created, is associated with the
This topic should be removed; we don't create separate method topics for performing an operation on a property of a resource. We should remove this file in favor of the new printjob-update file that you're adding here.

2021-02-15 20:32 UTC, Lauragra commented on api-reference/beta/api/printjob-update.md
> +In the request body, supply the values of the relevant [printJob](../resources/printjob.md) fields. Existing properties that are not included in the request body will maintain their previous values.
You might want to mention here that they can only include the configuration property?

2021-02-15 20:33 UTC, Lauragra requested changes
Please see comments. Also, does this update merit a mention in the changelog?

2021-02-15 20:34 UTC, opbld31 commented
Docs Build status updates of commit _[0e668d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e668d8da44956c064c7ca8da9338ad9ec8eecf3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-d4016815)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-d4016815)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-d4016815)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="b2eff973-d4016815"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-d4016815"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-d4016815"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102152031575126-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=aLntUwplyu6wPSQtr2jBHFIfQUZrVzGqP9X3%2BJPe82U%3D&st=2021-02-15T20%3A29%3A01Z&se=2021-03-18T20%3A34%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 21:35 UTC, opbld33 commented
Docs Build status updates of commit _[b208d12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b208d126cadfc432332e88482dee737586f449ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-9dc41495)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-9dc41495)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-9dc41495)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |

<a id="b2eff973-9dc41495"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-9dc41495"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-9dc41495"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102162134063886-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mL9u3KVb7R94Z1R%2F%2B4NcqDvrAtsKHqG0iHwsZu60snc%3D&st=2021-02-16T21%3A30%3A01Z&se=2021-03-19T21%3A35%3A01Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 21:49 UTC, opbld30 commented
Docs Build status updates of commit _[76d64e3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76d64e3ec51e34149195115f0e4e5e9ff8f48a86)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-550e2634)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-550e2634)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-550e2634)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11616) |

<a id="b2eff973-550e2634"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-550e2634"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-550e2634"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102162148034583-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2vNnI3%2BQzS1oRB2nc3KZX3Z7p237P5Fd9nqR1GsmBfQ%3D&st=2021-02-16T21%3A44%3A23Z&se=2021-03-19T21%3A49%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 02:50 UTC, opbld31 commented
Docs Build status updates of commit _[ffbde27](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ffbde274257c1ef8dacba361275873661d71decf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-746958b9)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-746958b9)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-746958b9)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11616) |

<a id="b2eff973-746958b9"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-746958b9"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-746958b9"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170155594288-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=M43ns18tOM9AkFs4szNzx5iwwOB8TJRyEy9gQGMrTtU%3D&st=2021-02-17T02%3A45%3A40Z&se=2021-03-20T02%3A50%3A40Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 03:37 UTC, nilakhan commented on api-reference/beta/api/printjob-update-configuration.md
> +Updating a print job configuration will only succeed if a [printTask](../resources/printTask.md) in a `processing` state, started by a trigger that the requesting app created, is associated with the
In general, we don't enable specific property updates on a resource.
If we don't publish this topic, how can we communicate to partners that they can update the "configuration" property as well?

2021-02-17 06:04 UTC, Lauragra commented on api-reference/beta/api/printjob-update-configuration.md
> +Updating a print job configuration will only succeed if a [printTask](../resources/printTask.md) in a `processing` state, started by a trigger that the requesting app created, is associated with the
That is covered in the Update printJob topic.

2021-02-17 20:48 UTC, opbld30 commented
Docs Build status updates of commit _[706672a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/706672a899e640844039f5876c50c5d1ca9b08b7)_: 

### :white_check_mark: Validation status: partially passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0a43bb10)
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-0a43bb10)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-0a43bb10)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-0a43bb10)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11616) |

<a id="0a43bb10"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

<a id="b2eff973-0a43bb10"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-0a43bb10"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-0a43bb10"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172046459827-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1FjD6o4KQsL3NXC2ecrmiFoES%2B%2B8A%2FWt8DnxhnmZfGU%3D&st=2021-02-17T20%3A43%3A52Z&se=2021-03-20T20%3A48%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 20:50 UTC, opbld32 commented
Docs Build status updates of commit _[4cf6dc2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4cf6dc2a0be310513d33371dfe35bf6dde7545bf)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-8c8b5211)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-8c8b5211)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-8c8b5211)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-cb1163c3-8c8b5211)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11616) |

<a id="b2eff973-8c8b5211"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-8c8b5211"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-8c8b5211"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cb1163c3-8c8b5211"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/resources/printjob.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172048196396-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NEP5SqtvyWNzcajMVDzcrejbjeGqLph%2FuPWn2N6AS78%3D&st=2021-02-17T20%3A45%3A07Z&se=2021-03-20T20%3A50%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 20:52 UTC, opbld31 commented
Docs Build status updates of commit _[87c59b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87c59b69aae51336d05a1e4c2fb4caf57af906d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-b2eff973-10ae7b69)
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update-configuration?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-5dd27ba9-10ae7b69)
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-dfa51fe2-10ae7b69)
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/resources/printjob.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) | [Details](#user-content-cb1163c3-10ae7b69)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |
[concepts/changelog.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/concepts/changelog.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/changelog?branch=pr-en-us-11616) |

<a id="b2eff973-10ae7b69"></a>
### [api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="5dd27ba9-10ae7b69"></a>
### [api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="dfa51fe2-10ae7b69"></a>
### [api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="cb1163c3-10ae7b69"></a>
### [api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/resources/printjob.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102172051179642-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=REpHCoSE%2F16S%2Fv8263%2BB80RSzpIk7zPToMJ%2F6UrP0y8%3D&st=2021-02-17T20%3A47%3A38Z&se=2021-03-20T20%3A52%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 18:53 UTC, Lauragra commented
@nilakhan , can you please revert the update to changelog.md? It has a merge conflict and we don't need that file.

2021-03-06 02:28 UTC, opbld34 commented
Docs Build status updates of commit _[eeed13d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eeed13d977da9865d27737fcadc145ca3029360d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103060227274625-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7KYBK%2B4OTz32bLiYT69%2Br%2Ffc%2B%2FUkYYJNnB5KuC5I9UQ%3D&st=2021-03-06T02%3A23%3A38Z&se=2021-04-06T02%3A28%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-06 02:39 UTC, opbld33 commented
Docs Build status updates of commit _[612e5ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/612e5cecc2d4b4cbdd905ad6569a24bd4c73ee16)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/printjob-abort.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-abort.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/api/printjob-update-configuration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update-configuration.md) | :white_check_mark:Succeeded | |
[api-reference/beta/api/printjob-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/api/printjob-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-update?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/resources/printjob.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/resources/printjob.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printjob?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/printjob-abort?view=graph-rest-beta&branch=pr-en-us-11616) (graph-rest-beta) |
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/nilakhan-printjob-update/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103060238137532-11616%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0e%2FO88V2YcjaeBPvRxqlzfeLd%2BhM%2BHZRRhR%2BTTrTDc0%3D&st=2021-03-06T02%3A34%3A40Z&se=2021-04-06T02%3A39%3A40Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-06 02:44 UTC, Lauragra approved these changes

2021-03-06 02:44 UTC, merged