Add lastSeenDateTime property
microsoftgraph/microsoft-graph-docs pull request #11672
Opened 2021-02-16 17:31 UTC by jahsu-MSFT

2021-02-16 17:33 UTC, opbld33 commented
Docs Build status updates of commit _[bbd6cc6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bbd6cc6d92391faaad06a0fbc2ee0a717dcadfb4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11672) (graph-rest-beta) | [Details](#user-content-8794bed8-635cb569)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

<a id="8794bed8-635cb569"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161732026857-11672%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hRR%2BE7U8E%2FR4AEpb6wMf41W4%2FbJyw7jPV%2Fpq6pmArUc%3D&st=2021-02-16T17%3A28%3A11Z&se=2021-03-19T17%3A33%3A11Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-16 17:34 UTC, opbld32 commented
Docs Build status updates of commit _[e5a7989](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5a7989ed50e3e9230668a3600e94993ff7c5395)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11672) (graph-rest-beta) | [Details](#user-content-8794bed8-f90b3be3)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

<a id="8794bed8-f90b3be3"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102161733202918-11672%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mhwVbod%2BzTW%2BGMFq%2BJhhs1Phptb%2Fpb1%2FMv9%2FQ%2FOoR04%3D&st=2021-02-16T17%3A29%3A37Z&se=2021-03-19T17%3A34%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 02:54 UTC, nilakhan requested changes

2021-02-17 02:54 UTC, nilakhan commented on api-reference/beta/resources/printer.md
> +|lastSeenDateTime|DateTimeOffset|The dateTimeOffset when a printer interacted with Universal Print. Read-only.|
The most recent dateTimeOffset when a printer interacted with Universal Print

2021-02-17 02:54 UTC, nilakhan commented on changelog/Microsoft.PrintService.json
> +      "CreatedDateTime": "2021-01-27T00:00:00",
Why this is changed?

2021-02-17 02:59 UTC, jahsu-MSFT commented on changelog/Microsoft.PrintService.json
> +      "CreatedDateTime": "2021-01-27T00:00:00",
The year for this change is actually wrong.

2021-02-17 05:59 UTC, Lauragra commented on changelog/Microsoft.PrintService.json
> +      "CreatedDateTime": "2021-01-27T00:00:00",
The changelog entry will show the date on which the docs are published. When we publish this PR, we'll change the CreatedDateTime value to the current date.

2021-02-17 06:00 UTC, Lauragra commented on changelog/Microsoft.PrintService.json
> +      "CreatedDateTime": "2021-01-27T00:00:00",
Never mind, this was a comment that wasn't about the entry associated with the actual PR.

2021-02-17 06:01 UTC, Lauragra approved these changes

2021-02-17 06:02 UTC, opbld30 commented
Docs Build status updates of commit _[f62cf54](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f62cf540c2a15839e758b51ca6ae5599d4f90dc8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11672) (graph-rest-beta) | [Details](#user-content-8794bed8-4f4e3877)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

<a id="8794bed8-4f4e3877"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102170601314710-11672%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WCf4tkh85HqEVMMi%2Fvfa6wp6MKwuYISREYxSu1OFDvk%3D&st=2021-02-17T05%3A57%3A51Z&se=2021-03-20T06%3A02%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-17 17:09 UTC, jahsu-MSFT commented
@Lauragra Thanks for updating it!

2021-02-17 17:17 UTC, opbld32 commented
Docs Build status updates of commit _[accf499](https://github.com/microsoftgraph/microsoft-graph-docs/commits/accf499d7aef6abec9c6300234964ee935fc3b84)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11672) (graph-rest-beta) | [Details](#user-content-8794bed8-df4277a2)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

<a id="8794bed8-df4277a2"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202102171716200881-11672%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=y4v8WvR%2FyGYPtjxtqzYOmZQNkdsL0eW45w%2BPKD%2B%2FIo4%3D&st=2021-02-17T17%3A12%3A34Z&se=2021-03-20T17%3A17%3A34Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-03 22:04 UTC, opbld33 commented
Docs Build status updates of commit _[e35165a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e35165a25b8f12b2b156caed74b50ed93f3665ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/printer?view=graph-rest-beta&branch=pr-en-us-11672) (graph-rest-beta) | [Details](#user-content-8794bed8-16274296)
[changelog/Microsoft.PrintService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/changelog/Microsoft.PrintService.json) | :white_check_mark:Succeeded | |

<a id="8794bed8-16274296"></a>
### [api-reference/beta/resources/printer.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/users/jahsu/add-lastSeenDateTime-property/api-reference/beta/resources/printer.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103032202501273-11672%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=89dQ9t0OCfly%2F8D4J08oO2Ecyut5%2F2j0U9T2cEugBLI%3D&st=2021-03-03T21%3A59%3A19Z&se=2021-04-03T22%3A04%3A19Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-04 02:50 UTC, merged