Update intune-devices-userexperienceanalyticsapphealthapplicationperf…
microsoftgraph/microsoft-graph-docs pull request #11700
Opened 2021-02-18 21:14 UTC by zdvorak

…ormance.md

Clarification that the allOrgsHealthScore property is not currently in use.

2021-05-04 19:49 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-06-09 16:14 UTC, lramosvea commented
Hi @zhushanms could you please take a look at this PR?

2021-06-24 16:08 UTC, opbld30 commented
Docs Build status updates of commit _[817c2a5](https://github.com/zdvorak/microsoft-graph-docs/commits/817c2a535fe5c2fc5cbfd4dbbf52cbf03d4dca80)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/intune-devices-userexperienceanalyticsapphealthapplicationperformance.md](https://github.com/zdvorak/microsoft-graph-docs/blob/patch-1/api-reference/beta/resources/intune-devices-userexperienceanalyticsapphealthapplicationperformance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/intune-devices-userexperienceanalyticsapphealthapplicationperformance?view=graph-rest-beta&branch=pr-en-us-11700) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106241606441815-11700%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5RekEFNFNl1gwZjroBU2SS95Ge0q9m6FwGzbTJ0NpO4%3D&st=2021-06-24T16%3A03%3A11Z&se=2021-07-25T16%3A08%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-24 17:59 UTC, isvargasmsft commented on api-reference/beta/resources/intune-devices-userexperienceanalyticsapphealthapplicationperformance.md
> +  "allOrgsHealthScore": "0.0",
Please reproduce this change in any other example when this property is returned, For example Get, List and Update topics.

2021-06-24 18:00 UTC, isvargasmsft commented on api-reference/beta/resources/intune-devices-userexperienceanalyticsapphealthapplicationperformance.md
> +|allOrgsHealthScore|Double|This property is not currently in use. If called, this property will always return a value of 0.0|
PM (Dave Randall) approved this change on the side.

2021-06-24 18:02 UTC, isvargasmsft requested changes
Hello @zdvorak, 

Thank you for bringing this into the docs. I pinged Dave (Intune PM) on the side and he is ok with this change. 

Just 1 additional request: could you please reproduce this update in all the topics where this property is returned? 

Kind regards, 

Isaac Vargas

2021-09-01 15:00 UTC, closed without merging