Added PATCH method to onlineMeeting v1.0
microsoftgraph/microsoft-graph-docs pull request #11714
Opened 2021-02-19 20:28 UTC by frankpeng7

2021-02-20 00:16 UTC, frankpeng7 commented
Meant TOC instead of POC in the commit message

2021-02-23 19:47 UTC, frankpeng7 commented
@Lauragra @angelgolfer-ms can I get some review on this one?

2021-02-25 04:42 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +- The **startDateTime** and **endDateTime** must appear in pairs.
Line 69:
Do you mean if you update one, you should specify the other as well?
I'm going to assume so in my comment above after line 56. 
Please clarify if that's not what you mean.

2021-02-25 04:56 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-update.md
> +- The **startDateTime** and **endDateTime** must appear in pairs.
L#69 was moved from original L#53 and I think you got it right.
btw I'm not seeing any comment above after L#56

2021-02-25 05:05 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +
Lines 68-71:
I suggest integrating the info in the notes for the corresponding property, under the Description column as a separate paragraph for discoverability.
Alternatively, if you want to call them out outside of the Description column, then list the info in a separate paragraphs after line 55. 
This is because tables tend to visually pull attention away from normal text. When customers scan, they may not notice content right below a table.

Something like this, for the second choice:
The next table lists the properties that can be updated. In the request body, include only the properties that need updating, with the following exceptions:
- Adjusting the start or end date/time of an online meeting always requires both **startDateTime** and **endDateTime** properties in the request body. 
- Adjusting the **attendees** field of the **participants** property, such as adding or removing an attendee to the meeting, always requires the full list of attendees in the request body.

2021-02-25 05:10 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +- The **startDateTime** and **endDateTime** must appear in pairs.
Because I was still composing the comment :-) Now you see it.

2021-02-25 05:12 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +- The **startDateTime** and **endDateTime** must appear in pairs.
To reduce confusion for you, you may wait till I submit review comments for the PR before looking at them? Sometimes I may go back to adjust my comments before submitting the review... so not to waste your time. :-)

2021-02-25 05:20 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-update.md
> +
Thanks for the advice @angelgolfer-ms. I'd prefer calling them out in a separate paragraph and have updated the PR.

2021-02-25 07:33 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-update.md
> +In the request body, supply the values for relevant properties that need updating.
Request body section:
Please make the similar updates as commented in the beta version of this topic.

2021-02-25 07:44 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-update.md
> +**Notes:**
Lines 69-72:
Please remove these lines since you already mentioned this above the table.

2021-02-25 08:18 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +<!-- { "blockType": "ignored" } -->
Hey @frankpeng7 ,
Is there a specific reason you think it's necessary for the examples in this topic to each show calling with delegated permission and with application permission?
Let me know if there is, and that I am missing it.
From my perspective: many of the Graph APIs support both delegated and application permissions. The Permissions section is supposed to indicate that; the Examples section doesn't call that out. So that's one inconsistency.
But the bigger loss is disabling API Doctor (setting "blockType" to "ignored") for the examples. API Doctor is supposed to work in request/response pairs, so one would have to disable API Doctor when there are 2 example requests mapping to 1 example response.
Perhaps if you feel so inclined, you can choose one example to use delegated permission, and the other to use application permission, and state that in the example section title, line 76 and 159 respectively? Then for each example, you need to just show the request syntax for the kind of permission you state in the example title, keep a 1:1 mapping for the example request and response, and enable API Doctor?

2021-02-25 08:27 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
>  Content-Type: application/json
Line 85:
Please change the endpoint version to beta.

2021-02-25 08:30 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +Content-Type: application/json
Line 165 or 178:
Please change the endpoint version to beta.

2021-02-25 09:08 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-update.md
> +**Notes:**
Lines 69-72:
Please delete these lines as the ideas are in lines 55 and 56.

2021-02-25 09:09 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-update.md
> +### Example 1: Update the startDateTime, endDateTime and subject
Please see my comments in the beta topic regarding showing only 1 example request in each example.

2021-02-25 09:12 UTC, angelgolfer-ms commented on changelog/Microsoft.Skype.Calling.json
> +          "Description": "Added PATCH method to the [onlineMeeting](https://docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-v1.0) resource.",
Line 10:
It would be useful to provide a link to the "PATCH method" as well, to point to the PATCH operation topic.

2021-02-25 09:21 UTC, angelgolfer-ms commented on api-reference/beta/api/onlinemeeting-update.md
> +### Properties that allows updating
Line 60:
I'd recommend removing this custom section title. Technically, a table in the "Request body" section of a PATCH operation topic typically exists and hence listing a table is not custom.
That's to set and follow the same expectations in the PATCH operation topics for other entities as well. Those topics don't use a H3 custom section title, as the table typically exists in PATCH topics.

2021-02-25 09:22 UTC, angelgolfer-ms commented on api-reference/v1.0/api/onlinemeeting-update.md
> +### Properties that allows updating
Line 58:
I'd recommend removing this custom section title.

2021-02-25 09:24 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/onlinemeeting.md
> +| [Create or get onlineMeeting](../api/onlinemeeting-createorget.md) | [onlineMeeting](onlinemeeting.md) | Create an **onlineMeeting** object with a custom, external ID. If the meeting already exists
Line 24:
For parity and better experience, would you mind moving the row in line 24 to after line 21? Similar to the beta topic?

2021-02-25 20:52 UTC, angelgolfer-ms requested changes
Just a few relatively minor comments inline in the topics.
And one more that's starting to pose as a usability and consistency issue - would you mind reorganizing the Properties table in the onlinemeeting.md topic, and the table in the "Request body" section that shows updateable properties, to use alphabetical order?

If you take a look at the branches generated by the stub topic generator, and existing entities like user, group, event, message, and so on, properties in a properties table should be in alphabetical order.
Thanks!

2021-02-28 21:51 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-update.md
> +<!-- { "blockType": "ignored" } -->
ok removed app token request sample

2021-02-28 21:58 UTC, frankpeng7 commented on api-reference/v1.0/resources/onlinemeeting.md
> +| [Create or get onlineMeeting](../api/onlinemeeting-createorget.md) | [onlineMeeting](onlinemeeting.md) | Create an **onlineMeeting** object with a custom, external ID. If the meeting already exists
Actually quite the opposite. I can update beta table order to align with this one. CreateOrGet is an action and should come after the basic CRUD operations - unless they are required to be in alphabetically order. Please let me know if that's the case.

2021-02-28 22:02 UTC, frankpeng7 commented
> Just a few relatively minor comments inline in the topics.
> And one more that's starting to pose as a usability and consistency issue - would you mind reorganizing the Properties table in the onlinemeeting.md topic, and the table in the "Request body" section that shows updateable properties, to use alphabetical order?
> 
> If you take a look at the branches generated by the stub topic generator, and existing entities like user, group, event, message, and so on, properties in a properties table should be in alphabetical order.
> Thanks!

@angelgolfer-ms done. Please take a look at the only unresolved comment and let me know if any changes are advised. Thanks.

2021-03-01 21:51 UTC, angelgolfer-ms commented on api-reference/v1.0/resources/onlinemeeting.md
> +| [Create or get onlineMeeting](../api/onlinemeeting-createorget.md) | [onlineMeeting](onlinemeeting.md) | Create an **onlineMeeting** object with a custom, external ID. If the meeting already exists
Hi @frankpeng7 , I see what you're saying, and the general guidance is to list the CRUD operations first (most entities have some CRUD), followed by any actions or functions in alphabetical order. When I first saw that ordering in the beta TOC months ago, I was also taken aback... 
IMHO now, to optimize your case for customers looking into a "create" operation in the Methods table, having "create or get" in the vicinity (one row down) from the "create" operation would make the choices ("create" vs "create or get") more discoverable. Especially because most entities do not support a single-call method "create or get", customers who are not aware of this action may not browse through the Methods table to see this method. The similar considerations apply to the TOC ordering, under the "Online meeting" parent node.

There are a few entities that support a PUT operation for "create or update/replace" (yes these are operations, not actions :-)). In those cases, we list them higher up in the CRUD ordering like a "create" operation, so that customers notice them when they're looking into a "create" use case. We wouldn't list such an operation after a PATCH operation, if one exists.

One other thought to share - the general guidance is good for stub topic generation and automation based on the CSDL. There are limits for such generation because the CSDL doesn't contain certain level of info, and generators do not parse the semantics of an action description, so where we can still manually customize and optimize on the customer's discoverability, we can consider doing that. :-)

2021-03-02 20:46 UTC, angelgolfer-ms commented on api-reference/v1.0/toc.yml
>          - name: Create
@frankpeng7 , please order the TOC the way you have it in the Methods table in onlinemeeting.md.

2021-03-02 20:46 UTC, angelgolfer-ms commented on api-reference/beta/toc.yml
>          - name: Create
@frankpeng7 , please order the TOC the way you have it in the Methods table in onlinemeeting.md.

2021-03-02 20:49 UTC, angelgolfer-ms requested changes
@frankpeng7 , just 2 more comments in the toc.yml files, and we can wrap up the content review for this PR.
For our records in case anyone looks back at this PR in the future: 
We exchanged our POVs over how to order "create or get", whether to keep that method after "Create" and "Get" as in the current beta version, vs "Create", "Get", "Update", "Delete", "Create or get". The first optimizes on discoverability for customers. The second follows the existing guidance for the majority of entities that support the usual CRUD operations without related methods like "Create or get". 
In a limited set of a total of 5 methods, choosing one or the other may not make a big difference, so I am happy to leave it at that for now. We'll update the order if we get any feedback from internal or external customers in the future. Information architecture and TOC evolve.

2021-03-03 01:09 UTC, angelgolfer-ms approved these changes
In light of the OPS publishing tool problem, please continue to follow up with Laura about merging this PR.

2021-03-05 18:37 UTC, opbld33 commented
Docs Build status updates of commit _[1a00737](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a0073784e6a8a3fe08be453f5c71df65c47fde6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-fb5dd14f-6e7fe318)
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-98057f49-6e7fe318)
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-4e311bd1-6e7fe318)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-81d219b4-6e7fe318)
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-c3251e69-6e7fe318)
[api-reference/beta/resources/audioconferencing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/resources/audioconferencing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audioconferencing?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-494d5e6b-6e7fe318)
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/resources/onlinemeeting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) | [Details](#user-content-db024c0d-6e7fe318)
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-9d47e387-6e7fe318)
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-6d3f843f-6e7fe318)
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-f368bbe5-6e7fe318)
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-688e5765-6e7fe318)
[api-reference/v1.0/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-bed0f9ae-6e7fe318)
[api-reference/v1.0/resources/audioconferencing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/resources/audioconferencing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audioconferencing?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-44c100c1-6e7fe318)
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/resources/onlinemeeting.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) | [Details](#user-content-6f95ed72-6e7fe318)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="fb5dd14f-6e7fe318"></a>
### [api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/application-post-onlinemeetings.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="98057f49-6e7fe318"></a>
### [api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-createorget.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="4e311bd1-6e7fe318"></a>
### [api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attri [...]

2021-03-06 02:16 UTC, opbld32 commented
Docs Build status updates of commit _[ae62049](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ae620495954080f12a2478c36c34914dbadb3bec)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/resources/audioconferencing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/resources/audioconferencing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audioconferencing?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-beta&branch=pr-en-us-11714) (graph-rest-beta) |
[api-reference/v1.0/api/application-post-onlinemeetings.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/application-post-onlinemeetings.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-createorget.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-createorget.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-createorget?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-delete?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/api/onlinemeeting-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/api/onlinemeeting-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-update?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/audioconferencing.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/resources/audioconferencing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/audioconferencing?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/onlinemeeting.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/application-post-onlinemeetings?view=graph-rest-1.0&branch=pr-en-us-11714) (>= graph-rest-1.0) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/onlineMeeting-Patch-v1/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103060215377176-11714%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BGYIR917fgTNrx9uCEUzE4DRK6EyD9LnFMmto6XqgmA%3D&st=2021-03-06T02%3A11%3A42Z&se=2021-04-06T02%3A16%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-06 02:22 UTC, merged