Identity provider API refresh
microsoftgraph/microsoft-graph-docs pull request #11735
Opened 2021-02-23 06:08 UTC by namkedia

Refresh documentation to represent the identity provider API changes.

2021-02-23 17:47 UTC, saraswatshantanu reviewed
Don’t we need to document the new IdentityProviderBase? I think that is where the new API path will be documented - graph.microsoft.com/Beta/identity/identityProviders

2021-03-05 06:05 UTC, opbld33 commented
Docs Build status updates of commit _[7531d6c](https://github.com/namkedia/microsoft-graph-docs/commits/7531d6c1f953197836ec9af3bdd453696b3c47a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-ca9a1ad1)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-ca9a1ad1)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-ca9a1ad1)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-ca9a1ad1"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-ca9a1ad1"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-ca9a1ad1"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050603581202-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Wh5EkK2vuJmyRoDHSa4uJnjz649NM1lBpl2D%2Be%2BEG%2FQ%3D&st=2021-03-05T06%3A00%3A13Z&se=2021-04-05T06%3A05%3A13Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 06:09 UTC, opbld33 commented
Docs Build status updates of commit _[d67a7e0](https://github.com/namkedia/microsoft-graph-docs/commits/d67a7e04b2a8ed64377ad5cc3b19e70440c6909d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-0c613bbc)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-0c613bbc)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-0c613bbc)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-0c613bbc"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-0c613bbc"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-0c613bbc"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050608376684-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1sHsQxMQRx7RCngqSQ3GOM4I08Wk0ty%2FtYiFh2hI5Pg%3D&st=2021-03-05T06%3A04%3A41Z&se=2021-04-05T06%3A09%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 06:11 UTC, opbld34 commented
Docs Build status updates of commit _[567914d](https://github.com/namkedia/microsoft-graph-docs/commits/567914dc6cf01b67e5fefedf4a9e580e8684712b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-f1ea0661)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-f1ea0661)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-f1ea0661)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-f1ea0661"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-f1ea0661"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-f1ea0661"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103050609444524-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=hIwrjf6d4H1WLW8UROSbaPruFyw8JOl1osMxHudPbMQ%3D&st=2021-03-05T06%3A06%3A06Z&se=2021-04-05T06%3A11%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 06:13 UTC, FaithOmbongi commented on api-reference/beta/resources/builtInIdentityProvider.md
> +## Properties
If any of the properties support query parameters, please add this in the property descriptions.

2021-03-05 06:13 UTC, FaithOmbongi commented on api-reference/beta/resources/openidconnectIdentityProvider.md
> +## Properties
Same comment on query parameters

2021-03-05 06:14 UTC, FaithOmbongi commented on api-reference/beta/resources/socialIdentityProvider.md
> +## Properties
Same comment on query parameters

2021-03-05 10:38 UTC, opbld33 commented
Docs Build status updates of commit _[2114649](https://github.com/namkedia/microsoft-graph-docs/commits/211464906ec95b9f7f5c649887bcbb7e68ad53a3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-d35352bb)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-d35352bb)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-d35352bb)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-d35352bb"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-d35352bb"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-d35352bb"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103051037390713-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MPNmfWNZ3HoQ8Kx7rVd5AV4SOb7c94gzojVJyYmPGOw%3D&st=2021-03-05T10%3A33%3A54Z&se=2021-04-05T10%3A38%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 11:11 UTC, opbld32 commented
Docs Build status updates of commit _[001ab37](https://github.com/namkedia/microsoft-graph-docs/commits/001ab37e22e43eb3ec7504e1769f9b22d1112752)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-01efa3f4)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-01efa3f4)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-01efa3f4)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-01efa3f4"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-01efa3f4"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-01efa3f4"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103051110220740-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Dd6shBietGEgbi8rYim28Nw65pKAfDH%2BfnGfKRIElhs%3D&st=2021-03-05T11%3A06%3A52Z&se=2021-04-05T11%3A11%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 11:24 UTC, opbld30 commented
Docs Build status updates of commit _[022c8af](https://github.com/namkedia/microsoft-graph-docs/commits/022c8af9ab2f70198ccf67f5ccfa21eedcb9ec96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-acdba5a6)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-acdba5a6)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-acdba5a6)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-acdba5a6"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-acdba5a6"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-acdba5a6"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103051123189177-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mAw%2BcgQD4wgqbXsT0UhFIpL9CqUSjlogBfftTWT%2FjfM%3D&st=2021-03-05T11%3A19%3A45Z&se=2021-04-05T11%3A24%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 11:27 UTC, opbld32 commented
Docs Build status updates of commit _[bc40479](https://github.com/namkedia/microsoft-graph-docs/commits/bc404796cd04bf2e1505c2edf3fad404a7887278)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-308de583-4feb3850)
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-4feb3850)
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-f19b79f1-4feb3850)
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="308de583-4feb3850"></a>
### [api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="085c8d3a-4feb3850"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="f19b79f1-4feb3850"></a>
### [api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103051123279459-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zinWZJtwXg%2Bn3%2BTfEwl%2BJ9xB6wE62wCIEUj6ZIC3rtQ%3D&st=2021-03-05T11%3A22%3A12Z&se=2021-04-05T11%3A27%3A12Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 02:51 UTC, opbld32 commented
Docs Build status updates of commit _[a8ee4d4](https://github.com/namkedia/microsoft-graph-docs/commits/a8ee4d4e41f08baa68d867074c3ad71cde96dbef)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-38b51da5)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-38b51da5)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | |

<a id="085c8d3a-38b51da5"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="5dc3749f-38b51da5"></a>
### [api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090249534528-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bu%2FAhNeCPz9K74IGymp7lMOMg%2F1OGU8iOk0pu8XAxZ0%3D&st=2021-03-09T02%3A46%3A13Z&se=2021-04-09T02%3A51%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 03:04 UTC, opbld30 commented
Docs Build status updates of commit _[184de8c](https://github.com/namkedia/microsoft-graph-docs/commits/184de8cd417429dcdd00a6e486c24b94f3076719)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-6dc10c55)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-6dc10c55)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="085c8d3a-6dc10c55"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="5dc3749f-6dc10c55"></a>
### [api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090303260887-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tXm5QX8G5DwLTP%2FsCvWmkwiIBysIrD11MMs0nCxdBY4%3D&st=2021-03-09T02%3A59%3A49Z&se=2021-04-09T03%3A04%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 07:05 UTC, opbld30 commented
Docs Build status updates of commit _[4bf6afe](https://github.com/namkedia/microsoft-graph-docs/commits/4bf6afebf054001034c53be21a7ff33142325467)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-085c8d3a-18bcc78b)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-18bcc78b)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtInIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtInIdentityProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/socialIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialIdentityProvider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="085c8d3a-18bcc78b"></a>
### [api-reference/beta/resources/openidconnectIdentityProvider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectIdentityProvider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="5dc3749f-18bcc78b"></a>
### [api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectIdentityProvider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090704103703-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LpLH0pVpvgj%2BWjweVpeL%2FzLZtQZnWOb08Dt6crzl%2Bgw%3D&st=2021-03-09T07%3A00%3A26Z&se=2021-04-09T07%3A05%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 07:10 UTC, opbld34 commented
Docs Build status updates of commit _[5d485bb](https://github.com/namkedia/microsoft-graph-docs/commits/5d485bb12948f78269db8835d559b76e906a7b19)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-00685cff-26b062b2)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="00685cff-26b062b2"></a>
### [api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml)
 - **Line 10601, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/builtinidentityprovider.md'.`````
 - **Line 10603, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/socialidentityprovider.md'.`````
 - **Line 10605, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/openidconnectidentityprovider.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090709342628-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jguipdzom5A44Nwfr26Ih70gEJN5JFcykVmk3%2B0oPi8%3D&st=2021-03-09T07%3A05%3A55Z&se=2021-04-09T07%3A10%3A55Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 07:12 UTC, opbld32 commented
Docs Build status updates of commit _[e3ef15f](https://github.com/namkedia/microsoft-graph-docs/commits/e3ef15f92138be391fec660877a06fbe8020c1de)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-ca2e3542)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-ca2e3542)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="2dc431a5-ca2e3542"></a>
### [api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectidentityprovider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="5dc3749f-ca2e3542"></a>
### [api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectidentityprovider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090710393173-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9HsjVtlEXBOsHD2huiyrLhBKVd2P3byhM2B1Vfpja1Q%3D&st=2021-03-09T07%3A07%3A22Z&se=2021-04-09T07%3A12%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-09 07:48 UTC, opbld30 commented
Docs Build status updates of commit _[dc3d9bf](https://github.com/namkedia/microsoft-graph-docs/commits/dc3d9bf457f93d23fd25935373697afd8df0c5ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b183a4e1-93924768)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-93924768)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-93924768)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="b183a4e1-93924768"></a>
### [api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="2dc431a5-93924768"></a>
### [api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectidentityprovider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="5dc3749f-93924768"></a>
### [api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectidentityprovider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103090746555760-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=e4hWLeeeWHqyti%2BCyw2Exae9L%2F9V6edzC1RJYtI4IqY%3D&st=2021-03-09T07%3A43%3A10Z&se=2021-04-09T07%3A48%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) [...]

2021-03-09 21:38 UTC, davidmu1 commented on api-reference/beta/resources/builtinidentityprovider.md
> +Represents built in identity providers with [External Identities](/azure/active-directory/external-identities/) for an Azure Active Directory tenant.
```suggestion
Represents built-in identity providers with [External Identities](/azure/active-directory/external-identities/) for an Azure Active Directory tenant.
```

2021-03-09 21:39 UTC, davidmu1 commented on api-reference/beta/resources/builtinidentityprovider.md
> +|id|String|The ID of the identity provider.|
```suggestion
|id|String|The identifier of the identity provider.|
```

2021-03-09 21:42 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +Configuring an OpenID Connect provider in B2C tenant enables users to sign up and sign in using their custom identity provider in an application.
```suggestion
Configuring an OpenID Connect provider in a B2C tenant enables users to sign up and sign in using their custom identity provider in an application.
```

2021-03-09 21:43 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|clientId|String|The client ID for the application obtained when registering the application with the identity provider. Inherited from [identityProvider](../resources/identityprovider.md). Required.
```suggestion
|clientId|String|The client identifier for the application obtained when registering the application with the identity provider. Inherited from [identityProvider](../resources/identityprovider.md). Required.|
```

2021-03-09 21:45 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|clientSecret|String|The client secret for the application obtained when registering the application with the identity provider. The clientSecret has a dependency on **responseType**. <ul><li>When **
```suggestion
|clientSecret|String|The client secret for the application obtained when registering the application with the identity provider. The clientSecret has a dependency on **responseType**. When **responseType** is `code`, a secret is required for the auth code exchange. When **responseType** is `id_token` the secret is not required because there is no code exchange, the `id_token` is returned directly from the authorization response. This is write-only. A read operation returns "\*\*\*\*". Inherited from [identityProvider](../resources/identityprovider.md).|
```

2021-03-09 21:45 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|id|String|The ID of the identity provider. Read-only. Required.|
```suggestion
|id|String|The identifier of the identity provider. Read-only. Required.|
```

2021-03-09 21:46 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|domainHint|String|The domain hint can be used to skip directly to the sign in page of the specified identity provider, instead of having the user make a selection among the list of available identit
```suggestion
|domainHint|String|The domain hint can be used to skip directly to the sign-in page of the specified identity provider, instead of having the user make a selection among the list of available identity providers.|
```

2021-03-09 21:48 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|responseMode|String|The response mode defines the method used to send data back from the custom identity provider to Azure AD B2C. The following response modes can be used: <ul><li>`form_post` : Thi
```suggestion
|responseMode|String|The response mode defines the method used to send data back from the custom identity provider to Azure AD B2C. Possible values: `form_post`, `query`. Required.|
```

2021-03-09 21:49 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|responseMode|String|The response mode defines the method used to send data back from the custom identity provider to Azure AD B2C. The following response modes can be used: <ul><li>`form_post` : Thi
If descriptions are needed for values, add a table after the properties table. See the second option here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations

2021-03-09 21:51 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|responseType|String|The response type describes the type of information sent back in the initial call to the authorization_endpoint of the custom identity provider. The following response types can
```suggestion
|responseType|String|The response type describes the type of information sent back in the initial call to the authorization_endpoint of the custom identity provider. Possible values: `code` , `id_token` , `token`.  Required.|
```

2021-03-09 21:51 UTC, davidmu1 commented on api-reference/beta/resources/openidconnectidentityprovider.md
> +|responseType|String|The response type describes the type of information sent back in the initial call to the authorization_endpoint of the custom identity provider. The following response types can
If descriptions are needed for values, add a table after the properties table. See the second option here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103158/Enumerations

2021-03-09 21:54 UTC, davidmu1 commented on api-reference/beta/resources/socialidentityprovider.md
> +|clientSecret|String|The client secret for the application obtained when registering the application with the identity provider. This is write-only. A read operation will return "\*\*\*\*". Required.
```suggestion
|clientSecret|String|The client secret for the application that is obtained when the application is registered with the identity provider. This is write-only. A read operation returns "\*\*\*\*". Required.|
```

2021-03-09 21:54 UTC, davidmu1 commented on api-reference/beta/resources/socialidentityprovider.md
> +|id|String|The ID of the identity provider.|
```suggestion
|id|String|The identifier of the identity provider.|
```

2021-03-09 21:57 UTC, davidmu1 commented on api-reference/beta/resources/socialidentityprovider.md
> +### Where to get the client ID and secret
```suggestion
### Where to get the client identifier and secret
```

2021-03-09 21:58 UTC, davidmu1 commented on api-reference/beta/resources/socialidentityprovider.md
> +Each identity provider has a process for creating an app registration. For example, users create an app registration with Facebook at [developers.facebook.com](https://developers.facebook.com/). The
```suggestion
Each identity provider has a process for creating an app registration. For example, users create an app registration with Facebook at [developers.facebook.com](https://developers.facebook.com/). The resulting client identifier and client secret can be passed to [create identityProvider](../api/identityprovider-post-identityproviders.md). Then, each user object in the directory can be federated to any of the tenant's identity providers for authentication. This enables the user to sign in by entering credentials on the identity provider's sign-in page. The token from the identity provider is validated by Azure AD before the tenant issues a token to the application.
```

2021-03-09 21:58 UTC, davidmu1 commented on api-reference/includes/identityprovider-deprecate.md
> +> This identity provider API is deprecated and will stop returning data on March, 2023. Please use the new [document]().
Is a link missing for the document to go to?

2021-03-11 04:30 UTC, opbld31 commented
Docs Build status updates of commit _[3ae54c7](https://github.com/namkedia/microsoft-graph-docs/commits/3ae54c7cf69f7c4f99a1015c3336de5f2c415ad5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-c2dd0271-c97b5759)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4d18ab3c-c97b5759)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-412f1b63-c97b5759)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b183a4e1-c97b5759)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-c97b5759)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-c97b5759)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-94bb57a9-c97b5759)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="c2dd0271-c97b5759"></a>
### [api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md)
 - **Line 15, Column 20**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/identityproviderbase.md'.`````

<a id="4d18ab3c-c97b5759"></a>
### [api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List availableProviderTypes - Microsoft Graph beta' is duplicated in: 'beta/api/identityproviderbase-list-availableprovidertypes.md(2,8), beta/api/identityprovider-list-availableprovidertypes.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve all available identity provider types in the directory.' is duplicated in 'beta/api/ [...]

2021-03-11 04:36 UTC, opbld30 commented
Docs Build status updates of commit _[41c7140](https://github.com/namkedia/microsoft-graph-docs/commits/41c7140f9ffa43871878311ee47347752591d44f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-00685cff-28019f79)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | | [Details](#user-content-c2dd0271-28019f79)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | | [Details](#user-content-4d18ab3c-28019f79)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | | [Details](#user-content-412f1b63-28019f79)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :bulb:Suggestion | | [Details](#user-content-b183a4e1-28019f79)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | | [Details](#user-content-2dc431a5-28019f79)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | | [Details](#user-content-5dc3749f-28019f79)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :bulb:Suggestion | | [Details](#user-content-94bb57a9-28019f79)

<a id="00685cff-28019f79"></a>
### [api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml)
 - **Line 10623, Column 15**: **[Error-yaml-syntax-error]** `````While parsing a block collection, did not find expected '-' indicator.`````

<a id="c2dd0271-28019f79"></a>
### [api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md)
 - **Line 15, Column 20**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/identityproviderbase.md'.`````

<a id="4d18ab3c-28019f79"></a>
### [api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List availableProviderTypes - Microsoft Graph beta' is duplicated in: 'beta/api/identityproviderbase-list-availableprovidertypes.md(2,8), beta/api/identityprovider-list-availableprovidertypes.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve all available identity provider types in the directory.' is duplicated in 'beta/api/identityprovider-list-availableprovidertypes.md(3,14)', 'beta/api/identityproviderbase-list-availableprovidertypes.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List availableProviderTypes (deprecated)' is duplicated with other articles: 'beta/api/identityproviderbase-list-availableprovidertypes.md(10,1), beta/api/identityprovider-list-availableprovidertypes.md(10,1)'. First level headings must be unique within a docset.`````

<a id="412f1b63-28019f79"></a>
### [api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List availableProviderTypes - Microsoft Graph beta' is duplicated in: 'beta/api/identityproviderbase-list-availableprovidertypes.md(2,8), beta/api/identityprovider-list-availableprovidertypes.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Retrieve all available identity provider types in the directory.' is duplicated in 'beta/api/identityprovider-list-availableprovidertypes.md(3,14)', 'beta/api/identityproviderbase-list-availableprovidertypes.md(3,14)'.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List availableProviderTypes (deprecated)' is duplicated with other articles: 'beta/api/identityproviderbase-list-availableprovidertypes.md(10,1), beta/api/identityprovider-list-availableprovidertypes.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b183a4e1-28019f79"></a>
### [api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents social identity providers in an Azure Active Directory tenant and an Azure AD B2C tenant.' is duplicated in 'beta/resources/appleidentityprovider.md(3,14)', 'beta/resources/socialidentityprovider.md(3,14)'.`````

<a id="2dc431a5-28019f79"></a>
### [api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectidentityprovider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="5dc3749f-28019f79"></a>
### [api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Represents OpenIDConnect identity providers in an Azure Active Directory B2C tenant.' is duplicated in 'beta/resources/openidconnectidentityprovider.md(3,14)', 'beta/resources/openidconnectprovider.md(3,14)'.`````

<a id="94bb57a9-28019f79"></a>
### [api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md)
 - **Line 3, Column 14**: **[Suggestion-duplicate-descriptions]** `````Attribute 'description' with value 'Rep [...]

2021-03-11 04:57 UTC, opbld33 commented
Docs Build status updates of commit _[fda0a79](https://github.com/namkedia/microsoft-graph-docs/commits/fda0a79def0f0655ede0690b1a2d4d1c60dd5379)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-a6cb8809-abd5d0a4)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-00685cff-abd5d0a4)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4d18ab3c-abd5d0a4)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-412f1b63-abd5d0a4)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b183a4e1-abd5d0a4)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-abd5d0a4)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-abd5d0a4)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-94bb57a9-abd5d0a4)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="a6cb8809-abd5d0a4"></a>
### [api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 1, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="00685cff-abd5d0a4"></a>
### [api-reference/beta/toc.yml](https://github.com [...]

2021-03-11 05:11 UTC, opbld30 commented
Docs Build status updates of commit _[9adc6b0](https://github.com/namkedia/microsoft-graph-docs/commits/9adc6b085aa76e5eb69601766cb5add694dcbca5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-a6cb8809-f8567208)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-00685cff-f8567208)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4d18ab3c-f8567208)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-412f1b63-f8567208)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-7e8c4506-f8567208)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b183a4e1-f8567208)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-f8567208)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-f8567208)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-94bb57a9-f8567208)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="a6cb8809-f8567208"></a>
### [api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md)
 - **Line 30, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/identityproviderbase-post-identityproviders.md'.`````
 - **Line 31, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/identityproviderbase-get.md'.`````
 - **Line 32, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/identityproviderbase- [...]

2021-03-11 08:32 UTC, opbld32 commented
Docs Build status updates of commit _[2d9b0f4](https://github.com/namkedia/microsoft-graph-docs/commits/2d9b0f41be92ac72238febc0621ac48d2657776d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-412f1b63-1c04f0bc)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-c2dd0271-1c04f0bc)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-00685cff-1c04f0bc)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4d18ab3c-1c04f0bc)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-7e8c4506-1c04f0bc)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b183a4e1-1c04f0bc)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-a6cb8809-1c04f0bc)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-1c04f0bc)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-1c04f0bc)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-94bb57a9-1c04f0bc)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/includes/identityprovider-deprecate.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/includes/identityprovider-deprecate.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |

<a id="412f1b63-1c04f0bc"></a>
### [api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md)
 - **Line 61, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Duplicate tab id: (http, 2).`````
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List availableProviderTypes - Microsoft Graph beta' is duplicated in: 'beta/api/identityproviderbase-list-availableprovidertypes.md(2,8), beta/api/identityprovider-list-availableprovidertypes.md(2,8) [...]

2021-03-11 09:11 UTC, opbld30 commented
Docs Build status updates of commit _[12be926](https://github.com/namkedia/microsoft-graph-docs/commits/12be9260bab4d2a3e5bf8e17aa7e5a09e52c9c43)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-412f1b63-2b3371a7)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-c2dd0271-2b3371a7)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4d18ab3c-2b3371a7)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-7e8c4506-2b3371a7)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b183a4e1-2b3371a7)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-a6cb8809-2b3371a7)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-2b3371a7)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-2b3371a7)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-94bb57a9-2b3371a7)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://git [...]

2021-03-11 09:38 UTC, opbld30 commented
Docs Build status updates of commit _[b1bf49c](https://github.com/namkedia/microsoft-graph-docs/commits/b1bf49c52580eb75727f517cf3a5fd6e13c86508)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-412f1b63-b9a2370f)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-c2dd0271-b9a2370f)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4d18ab3c-b9a2370f)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-7e8c4506-b9a2370f)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-a6cb8809-b9a2370f)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-2dc431a5-b9a2370f)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5dc3749f-b9a2370f)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api- [...]

2021-03-11 17:14 UTC, FaithOmbongi commented on api-reference/beta/api/identityproviderbase-update.md
> +|type|String|The identity provider type.<ul>For B2B scenario:<li/>Google<li/>Facebook</ul><ul>For B2C scenario:<li/>Microsoft<li/>Google<li/>Amazon<li/>LinkedIn<li/>Facebook<li/>GitHub<li/>Twitter<li
```suggestion
|type|String|The identity provider type.<br/>For B2B scenario: `Google`, `Facebook`. <br>For B2C scenario: `Microsoft`, `Google`, `Amazon`, `LinkedIn`, `Facebook`, `GitHub`, `Twitter`, `Weibo`, `QQ`, `WeChat`, `OpenIDConnect`.|
```

2021-03-11 17:14 UTC, FaithOmbongi commented on api-reference/beta/api/identityproviderbase-update.md
> +# [HTTP](#tab/http)
See comment

2021-03-11 17:14 UTC, FaithOmbongi commented on api-reference/beta/api/identityproviderbase-update.md
> +
```suggestion
```

2021-03-11 17:14 UTC, FaithOmbongi commented on api-reference/beta/api/identityproviderbase-update.md
> +# [HTTP](#tab/http)
See comment

2021-03-11 17:14 UTC, FaithOmbongi commented on api-reference/beta/api/identityproviderbase-update.md
> +
```suggestion
```

2021-03-11 17:14 UTC, FaithOmbongi commented on api-reference/beta/resources/appleidentityprovider.md
> +
Content expected here?

2021-03-11 18:26 UTC, FaithOmbongi commented on api-reference/beta/api/identityprovider-delete.md
>  ms.prod: "microsoft-identity-platform"
Change all ms.prod values to **identity-and-sign-in**.

2021-03-16 17:02 UTC, opbld32 commented
Docs Build status updates of commit _[8cdd3ac](https://github.com/namkedia/microsoft-graph-docs/commits/8cdd3ac25a56bef1a5bb67cb3ccd9dd174c38d4b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 17:08 UTC, opbld31 commented
Docs Build status updates of commit _[837d947](https://github.com/namkedia/microsoft-graph-docs/commits/837d9470b2001ef2afd807e8e6cf1b3113f8327a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 17:14 UTC, opbld33 commented
Docs Build status updates of commit _[d566ba0](https://github.com/namkedia/microsoft-graph-docs/commits/d566ba01dcec1b53db17fc9f985e064e00ee1a85)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 17:14 UTC, opbld34 commented
Docs Build status updates of commit _[b1a8d70](https://github.com/namkedia/microsoft-graph-docs/commits/b1a8d70780048407c18a5d5fd18522602372e6af)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 17:30 UTC, opbld31 commented
Docs Build status updates of commit _[c93c1ee](https://github.com/namkedia/microsoft-graph-docs/commits/c93c1ee3bce320f16d2cb5d8bb6dfbf48bdbc66a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-d6360fbf)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-d6360fbf)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-d6360fbf)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-d6360fbf)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d6360fbf)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-d6360fbf)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-d6360fbf)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-d6360fbf)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-d6360fbf)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-d6360fbf)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_m [...]

2021-03-16 17:30 UTC, opbld30 commented
Docs Build status updates of commit _[63c20c1](https://github.com/namkedia/microsoft-graph-docs/commits/63c20c1cf2ecf186e5655a1c3eb7e642d44f46a6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 17:54 UTC, opbld34 commented
Docs Build status updates of commit _[edf289a](https://github.com/namkedia/microsoft-graph-docs/commits/edf289ae7492e652bc05f584506b3da23e495b1f)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 18:01 UTC, opbld34 commented
Docs Build status updates of commit _[e7634fa](https://github.com/namkedia/microsoft-graph-docs/commits/e7634faf526260688c7c71ca974f21454acfdcf6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-98bd1740)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-98bd1740)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-98bd1740)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-98bd1740)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-98bd1740)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-98bd1740)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-98bd1740)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-98bd1740)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-98bd1740)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-98bd1740)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_m [...]

2021-03-16 18:01 UTC, opbld34 commented
Docs Build status updates of commit _[15f0b71](https://github.com/namkedia/microsoft-graph-docs/commits/15f0b71c0bf29d83b07c8d418432fca4a0764f7e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 18:06 UTC, opbld34 commented
Docs Build status updates of commit _[ef89507](https://github.com/namkedia/microsoft-graph-docs/commits/ef8950761789ba298ba58a8b69dada17ae1571af)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 18:26 UTC, opbld31 commented
Docs Build status updates of commit _[7ef476a](https://github.com/namkedia/microsoft-graph-docs/commits/7ef476af526d9683229d1cdcdb4b23fe8794229a)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 21:04 UTC, opbld34 commented
Docs Build status updates of commit _[52e0185](https://github.com/namkedia/microsoft-graph-docs/commits/52e018548919a13dda56ca248f9a7138871348dc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-17 20:34 UTC, opbld31 commented
Docs Build status updates of commit _[28efc3b](https://github.com/namkedia/microsoft-graph-docs/commits/28efc3b87f2c721879d1fd256ce9d6e2358b9694)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-6f711b7d)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-6f711b7d)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-6f711b7d)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-6f711b7d)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-6f711b7d)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6f711b7d)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-6f711b7d)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-6f711b7d)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-6f711b7d)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-6f711b7d)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-6f711b7d)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-refere [...]

2021-03-17 20:45 UTC, opbld33 commented
Docs Build status updates of commit _[5010bac](https://github.com/namkedia/microsoft-graph-docs/commits/5010bac3a23078ccce609f5054488def3f3e4a66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-a8c29756)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-a8c29756)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-a8c29756)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-a8c29756)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-a8c29756)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a8c29756)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-a8c29756)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-a8c29756)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-a8c29756)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-a8c29756)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-a8c29756)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-refere [...]

2021-03-17 20:58 UTC, opbld30 commented
Docs Build status updates of commit _[83ebfc7](https://github.com/namkedia/microsoft-graph-docs/commits/83ebfc765f04f61e02345f34b1de5f614f6d620e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-fe927c97)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-fe927c97)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-fe927c97)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-fe927c97)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-fe927c97)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-fe927c97)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-fe927c97)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-fe927c97)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-fe927c97)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-fe927c97)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-fe927c97)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-refere [...]

2021-03-17 21:58 UTC, opbld32 commented
Docs Build status updates of commit _[bc73e55](https://github.com/namkedia/microsoft-graph-docs/commits/bc73e55fb7b9e15eb722f2810e69f535912a7160)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-c9d0f809)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-c9d0f809)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-c9d0f809)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-c9d0f809)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-c9d0f809)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c9d0f809)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-c9d0f809)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-c9d0f809)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-c9d0f809)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-c9d0f809)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-c9d0f809)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-refere [...]

2021-03-17 21:59 UTC, opbld33 commented
Docs Build status updates of commit _[c194a90](https://github.com/namkedia/microsoft-graph-docs/commits/c194a905dfd6df0f2138e12245bd61627015a392)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-a4ec94f5)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-a4ec94f5)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-a4ec94f5)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-a4ec94f5)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-a4ec94f5)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a4ec94f5)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-a4ec94f5)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-a4ec94f5)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-a4ec94f5)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-a4ec94f5)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-a4ec94f5)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-refere [...]

2021-03-18 05:19 UTC, opbld33 commented
Docs Build status updates of commit _[9263f66](https://github.com/namkedia/microsoft-graph-docs/commits/9263f669484cfcd5d751f59a2b7665d3d175f991)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-3397d702)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-3397d702)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-3397d702)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-3397d702)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-3397d702)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-3397d702)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3397d702)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-3397d702)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-3397d702)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-3397d702)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-3397d702)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-3397d702)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namked [...]

2021-03-18 05:53 UTC, opbld34 commented
Docs Build status updates of commit _[b26995c](https://github.com/namkedia/microsoft-graph-docs/commits/b26995ce3e92166fe5091409e64628e5488970b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-59f9785f)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-59f9785f)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-59f9785f)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-59f9785f)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-59f9785f)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-59f9785f)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-59f9785f)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-59f9785f)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-59f9785f)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-59f9785f)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-59f9785f)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-59f9785f)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namked [...]

2021-03-18 05:59 UTC, opbld30 commented
Docs Build status updates of commit _[52ae406](https://github.com/namkedia/microsoft-graph-docs/commits/52ae406b1fd2c565c4f5b3c3b51f520e04b93ce1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-bfff1d96)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-bfff1d96)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-bfff1d96)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-bfff1d96)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-bfff1d96)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-bfff1d96)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-bfff1d96)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-bfff1d96)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-bfff1d96)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-bfff1d96)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-bfff1d96)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-bfff1d96)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-bfff1d96)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-bfff1d96)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-r [...]

2021-03-18 09:04 UTC, opbld33 commented
Docs Build status updates of commit _[79814ac](https://github.com/namkedia/microsoft-graph-docs/commits/79814ace08d23422b1489aaf82e16e3f114d4f91)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-4429b51d)
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-4429b51d)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-4429b51d)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-4429b51d)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-4429b51d)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-4429b51d)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-4429b51d)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-4429b51d)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-4429b51d)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-4429b51d)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4429b51d)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-4429b51d)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-4429b51d)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-4429b51d)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-4429b51d)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us [...]

2021-03-18 09:19 UTC, opbld33 commented
Docs Build status updates of commit _[001312e](https://github.com/namkedia/microsoft-graph-docs/commits/001312ef36d0f8881b23861a14a49cfcac3f84fb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-7277310f)
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-7277310f)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-7277310f)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-7277310f)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-7277310f)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-7277310f)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-7277310f)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-7277310f)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-7277310f)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-7277310f)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7277310f)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-7277310f)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-7277310f)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-7277310f)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-7277310f)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us [...]

2021-03-18 09:35 UTC, opbld34 commented
Docs Build status updates of commit _[2c7640b](https://github.com/namkedia/microsoft-graph-docs/commits/2c7640bac1444fc081e258f5eceb66c08dc3151e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-799bb0468fa0579218989c08d69809b0-ed5a8dc9)
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-ed5a8dc9)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-ed5a8dc9)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-ed5a8dc9)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-ed5a8dc9)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-ed5a8dc9)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-ed5a8dc9)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-ed5a8dc9)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-ed5a8dc9)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-ed5a8dc9)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ed5a8dc9)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-ed5a8dc9)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-ed5a8dc9)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-ed5a8dc9)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-ed5a8dc9)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us [...]

2021-03-18 09:41 UTC, opbld31 commented
Docs Build status updates of commit _[bb61056](https://github.com/namkedia/microsoft-graph-docs/commits/bb6105604f971f5892ae1410355eca09c55acb4b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-31cb326c)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-31cb326c)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-31cb326c)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-31cb326c)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-31cb326c)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-31cb326c)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-31cb326c)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-31cb326c)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-31cb326c)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-31cb326c)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-31cb326c)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-31cb326c)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-31cb326c)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-31cb326c)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta& [...]

2021-03-18 09:42 UTC, opbld30 commented
Docs Build status updates of commit _[c53132a](https://github.com/namkedia/microsoft-graph-docs/commits/c53132ad574989ce02b9a49e217698f4f2ed428e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-a3aebd58)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-a3aebd58)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-a3aebd58)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-a3aebd58)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-a3aebd58)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-a3aebd58)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-a3aebd58)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-a3aebd58)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-a3aebd58)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a3aebd58)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-a3aebd58)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-a3aebd58)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-a3aebd58)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-a3aebd58)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta& [...]

2021-03-18 09:44 UTC, opbld34 commented
Docs Build status updates of commit _[00cc90b](https://github.com/namkedia/microsoft-graph-docs/commits/00cc90be95ebd10ba5b9b84ade3d1f9acdb14662)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-fdf5fef7)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-fdf5fef7)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-fdf5fef7)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-fdf5fef7)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-fdf5fef7)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-fdf5fef7)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-fdf5fef7)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-fdf5fef7)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-fdf5fef7)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-fdf5fef7)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-fdf5fef7)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-fdf5fef7)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-fdf5fef7)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-fdf5fef7)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta& [...]

2021-03-18 09:56 UTC, opbld30 commented
Docs Build status updates of commit _[0e4488e](https://github.com/namkedia/microsoft-graph-docs/commits/0e4488e31e8d048fa0fec62e903b51f5958d334d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-99974c53)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-99974c53)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-99974c53)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-99974c53)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-99974c53)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-99974c53)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-99974c53)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-99974c53)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-99974c53)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-99974c53)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-99974c53)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-99974c53)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-99974c53)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-99974c53)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta& [...]

2021-03-18 09:57 UTC, opbld34 commented
Docs Build status updates of commit _[68756e0](https://github.com/namkedia/microsoft-graph-docs/commits/68756e04c14d37dfc639b742c537b72930375339)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-72bec49839b00d4d4be39b50a1ea6157-2a287e44)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-2a287e44)
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-3e7c221607a2190d48b5811bcf587f9c-2a287e44)
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-2a287e44)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-2a287e44)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-2a287e44)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-2a287e44)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-2a287e44)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-2a287e44)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-2a287e44)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-2a287e44)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-2a287e44)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-2a287e44)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-2a287e44)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta& [...]

2021-03-18 10:25 UTC, opbld33 commented
Docs Build status updates of commit _[82c7b41](https://github.com/namkedia/microsoft-graph-docs/commits/82c7b419d8617b440f689c8a22b1ca761a3e2a3b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-b12af7ce)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-b12af7ce)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-b12af7ce)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-b12af7ce)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-b12af7ce)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-b12af7ce)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-b12af7ce)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-b12af7ce)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-b12af7ce)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-b12af7ce)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-b12af7ce)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-b12af7ce)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://g [...]

2021-03-18 19:06 UTC, opbld33 commented
Docs Build status updates of commit _[29d8ac7](https://github.com/namkedia/microsoft-graph-docs/commits/29d8ac7033f478a3209d54483e9d9d82457eacd8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-a9bbac3f)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-a9bbac3f)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-a9bbac3f)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-a9bbac3f)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-a9bbac3f)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-a9bbac3f)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a9bbac3f)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-a9bbac3f)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-a9bbac3f)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-a9bbac3f)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-a9bbac3f)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-a9bbac3f)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://g [...]

2021-03-18 21:47 UTC, davidmu1 commented on api-reference/beta/api/identityprovider-delete.md
>  # [HTTP](#tab/http)
remove line 60.

2021-03-18 21:48 UTC, davidmu1 commented on api-reference/beta/api/identityprovider-list-availableprovidertypes.md
>  # [HTTP](#tab/http)
Remove line 59

2021-03-18 21:48 UTC, davidmu1 commented on api-reference/beta/api/identityprovider-list-availableprovidertypes.md
>  ---
Remove line 70

2021-03-18 21:49 UTC, davidmu1 approved these changes

2021-03-19 05:59 UTC, opbld30 commented
Docs Build status updates of commit _[d990b99](https://github.com/namkedia/microsoft-graph-docs/commits/d990b99ea0615dd308621847bc19a2ac1f406e31)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-7b0d0a44)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-7b0d0a44)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-7b0d0a44)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-7b0d0a44)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-7b0d0a44)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-7b0d0a44)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-7b0d0a44)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-7b0d0a44)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-7b0d0a44)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-7b0d0a44)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-7b0d0a44)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-7b0d0a44)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://g [...]

2021-03-30 20:12 UTC, opbld34 commented
Docs Build status updates of commit _[f5951fe](https://github.com/namkedia/microsoft-graph-docs/commits/f5951fec274b0cc130b8da26594dea4030a3ef7d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d2c5f0fc)

<a id="d2c5f0fc"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103302012298876-11735%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9uLEhmndphRSjLOB56niiQL16dJK3Gi%2B4KPz2KI9h8s%3D&st=2021-03-30T20%3A07%3A49Z&se=2021-04-30T20%3A12%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 20:18 UTC, opbld31 commented
Docs Build status updates of commit _[eedbbe3](https://github.com/namkedia/microsoft-graph-docs/commits/eedbbe32d086228309059f36dd202e7fc0f3239d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-91333a68)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-91333a68)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-91333a68)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-91333a68)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-91333a68)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-91333a68)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-91333a68)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-91333a68)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-91333a68)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-91333a68)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-91333a68)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-91333a68)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://g [...]

2021-03-30 20:26 UTC, davidmu1 approved these changes

2021-03-30 22:06 UTC, opbld34 commented
Docs Build status updates of commit _[b43f5e5](https://github.com/namkedia/microsoft-graph-docs/commits/b43f5e5eb02f3938f405aa5fc27d7bdca43762f8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-b19a687d699022740ca177a36fe241ff-850f532b)
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ff0ac857825baf80c730ab5d005f08cd-850f532b)
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-850f532b)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-850f532b)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-850f532b)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-850f532b)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-850f532b)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-850f532b)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-850f532b)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-850f532b)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-850f532b)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-850f532b)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://g [...]

2021-03-30 22:11 UTC, opbld33 commented
Docs Build status updates of commit _[a073cdd](https://github.com/namkedia/microsoft-graph-docs/commits/a073cdd607b767c21976a3064c60dacca6da21a0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-8406f39c4f097c042f4ce2a5f89460f7-a1373bfe)
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-61ad944022ecab4bd007a481d0a477ca-a1373bfe)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-a1373bfe)
[api-reference/beta/resources/socialidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/socialidentityprovider.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/socialidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-5ec2f6de2231d3d6d215003a5fc54200-a1373bfe)
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a1373bfe)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-a1373bfe)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-a1373bfe)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-a1373bfe)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-a1373bfe)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-a1373bfe)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) [...]

2021-03-30 22:17 UTC, opbld33 commented
Docs Build status updates of commit _[ad0e783](https://github.com/namkedia/microsoft-graph-docs/commits/ad0e78300166958e307519c71cf6565e1f823715)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ea055ea7)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-ea055ea7)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-ea055ea7)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-ea055ea7)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-ea055ea7)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-ea055ea7)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-ea055ea7)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 00:45 UTC, opbld32 commented
Docs Build status updates of commit _[a1ed5af](https://github.com/namkedia/microsoft-graph-docs/commits/a1ed5afa6515fffa774b47de5fc063b19b7ae1b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3653220a)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-3653220a)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-3653220a)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-3653220a)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-3653220a)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-3653220a)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-3653220a)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 00:59 UTC, opbld33 commented
Docs Build status updates of commit _[ea64faa](https://github.com/namkedia/microsoft-graph-docs/commits/ea64faa9802108cce4462ff58127428b79ea5a2a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8c7437f8)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-8c7437f8)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-8c7437f8)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-8c7437f8)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-8c7437f8)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-8c7437f8)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-8c7437f8)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 01:19 UTC, saraswatshantanu commented
@namkedia we need to update the changelog as well

2021-03-31 01:28 UTC, opbld30 commented
Docs Build status updates of commit _[ecb8d7a](https://github.com/namkedia/microsoft-graph-docs/commits/ecb8d7a400e5c39beb57df3799a16060756f84ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9dd99981)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-9dd99981)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-9dd99981)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-9dd99981)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-9dd99981)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-9dd99981)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-9dd99981)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 01:35 UTC, opbld30 commented
Docs Build status updates of commit _[c990860](https://github.com/namkedia/microsoft-graph-docs/commits/c990860b78ec52ade9dc0d6e2cd2da0c8f9571b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f867b229)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-f867b229)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-f867b229)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-f867b229)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-f867b229)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-f867b229)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-f867b229)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 01:42 UTC, opbld30 commented
Docs Build status updates of commit _[b7abc7a](https://github.com/namkedia/microsoft-graph-docs/commits/b7abc7a3a5da13f1c20de16f2baa5e066f421c2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3a9a8ded)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-3a9a8ded)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-3a9a8ded)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-3a9a8ded)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-3a9a8ded)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-3a9a8ded)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-3a9a8ded)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 01:55 UTC, Lauragra commented on api-reference/includes/identityprovider-deprecate.md
> +> This identity provider API is deprecated and will stop returning data on March, 2023. Please use the new [Identity Provider APIs](/graph/api/resources/identityproviderbase).
Did you mean to provide a specific date in March? If not, then change "on" to a different word like "by", or "after", depending.

2021-03-31 02:04 UTC, Lauragra requested changes
Please include an update to the changelog with this PR.

2021-03-31 03:32 UTC, opbld31 commented
Docs Build status updates of commit _[aa13e02](https://github.com/namkedia/microsoft-graph-docs/commits/aa13e0237d344153dfed3ac470701b2e309e3749)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-779542b6)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-779542b6)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-779542b6)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-779542b6)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-779542b6)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-779542b6)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-779542b6)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 03:35 UTC, opbld31 commented
Docs Build status updates of commit _[98d2e8d](https://github.com/namkedia/microsoft-graph-docs/commits/98d2e8d4106f42db5f5ae1ad3875bde4caf7faf0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-cfe343a4)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-cfe343a4)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-cfe343a4)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-cfe343a4)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-cfe343a4)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-cfe343a4)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-cfe343a4)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 18:02 UTC, namkedia reviewed
> Please include an update to the changelog with this PR.

This has been added.

2021-03-31 22:26 UTC, opbld32 commented
Docs Build status updates of commit _[a7e43b0](https://github.com/namkedia/microsoft-graph-docs/commits/a7e43b01f46a5136d882212b7081d84648ad0208)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-feebb624)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-feebb624)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-feebb624)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-feebb624)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-feebb624)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-feebb624)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-feebb624)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 22:40 UTC, opbld31 commented
Docs Build status updates of commit _[bc051ab](https://github.com/namkedia/microsoft-graph-docs/commits/bc051abf970f9a51a459417f88a749273d0df0a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ff98aecc)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-ff98aecc)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-ff98aecc)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-ff98aecc)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-ff98aecc)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-ff98aecc)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-ff98aecc)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 22:47 UTC, opbld34 commented
Docs Build status updates of commit _[ac5aa6e](https://github.com/namkedia/microsoft-graph-docs/commits/ac5aa6e8b24d4b6f618ebe3f7e465787d4033b4e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-521ceddc)
[api-reference/beta/api/identityprovider-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-048f190625a08c748729866e0cacb10f-521ceddc)
[api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list-availableprovidertypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list-availableprovidertypes?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-ab1bf71fda0f30b2450076a13fb6420d-521ceddc)
[api-reference/beta/api/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-acb711d347cbd2f3a8789be33cc6980e-521ceddc)
[api-reference/beta/resources/identityproviderbase.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityproviderbase.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityproviderbase?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-9f9fb9bb55a215405c8d304e8accbd7c-521ceddc)
[api-reference/beta/resources/openidconnectidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectidentityprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-6eede1b805322496daa14f18fde579c4-521ceddc)
[api-reference/beta/resources/openidconnectprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/openidconnectprovider.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/openidconnectprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) | [Details](#user-content-4207cdf054d36a90868ef5cbca3165c6-521ceddc)
[api-reference/beta/api/identityprovider-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityprovider-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityprovider-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityprovider-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-delete.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-delete?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-get.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-get?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-list.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-list?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-post-identityproviders.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-post-identityproviders.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-post-identityproviders?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/api/identityproviderbase-update.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/api/identityproviderbase-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/identityproviderbase-update?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/appleidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/appleidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appleidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/builtinidentityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/builtinidentityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/builtinidentityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api-reference/beta/resources/identityprovider.md](https://github.com/namkedia/microsoft-graph-docs/blob/identityprovider/api-reference/beta/resources/identityprovider.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/identityprovider?view=graph-rest-beta&branch=pr-en-us-11735) (graph-rest-beta) |
[api [...]

2021-03-31 22:48 UTC, Lauragra approved these changes

2021-04-01 03:08 UTC, merged