Updated Edu Documentation Author/Ownership
microsoftgraph/microsoft-graph-docs pull request #11731
Opened 2021-02-22 17:42 UTC by mlafleur

2021-03-03 19:31 UTC, opbld30 commented
Docs Build status updates of commit _[09bf2e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/09bf2e7cf8468af3814a063c3c15e04b2dc18950)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/educationschool-list-administrativeunit.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/v1.0/api/educationschool-list-administrativeunit.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/educationschool-list-administrativeunit?view=graph-rest-1.0&branch=pr-en-us-11731) (>= graph-rest-1.0) | [Details](#user-content-7fea4194-457eec63)
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/v1.0/resources/enums.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11731) (>= graph-rest-1.0) | [Details](#user-content-3e83d71e-457eec63)
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/concepts/delta-query-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-11731) | [Details](#user-content-2447e7b4-457eec63)
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationcategory-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-72cf683c-457eec63)
[api-reference/beta/api/educationclass-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delete-members?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-87438c37-457eec63)
[api-reference/beta/api/educationclass-delete-teachers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delete-teachers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delete-teachers?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-478707cd-457eec63)
[api-reference/beta/api/educationclass-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delete?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-4176cb0d-457eec63)
[api-reference/beta/api/educationclass-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delta.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delta?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-665e5c27-457eec63)
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-get-group.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-13f990d5-457eec63)
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-2fc77b7c-457eec63)
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-ac11ba7c-457eec63)
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-categories.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-5901bf5c-457eec63)
[api-reference/beta/api/educationclass-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-members?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-58d757dc-457eec63)
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-schools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-09071394-457eec63)
[api-reference/beta/api/educationclass-list-teachers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-teachers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-teachers?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-3f5c18aa-457eec63)
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-de12c52a-457eec63)
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-category.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-075917ae-457eec63)
[api-reference/beta/api/educationclass-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-members?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-0effbdcb-457eec63)
[api-reference/beta/api/educationclass-post-teachers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-teachers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-teachers?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-66183257-457eec63)
[api-reference/beta/api/educationclass-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/education [...]

2021-03-19 20:22 UTC, opbld33 commented
Docs Build status updates of commit _[0bcef1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0bcef1d0295d36989833d4307148b32c6d56c68e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[concepts/delta-query-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/concepts/delta-query-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/delta-query-overview?branch=pr-en-us-11731) | [Details](#user-content-a7d51e634140c1da08e8a03d5580942a-68f53e24)
[api-reference/beta/api/educationcategory-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationcategory-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationcategory-get?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-e950867cdac51c7c3dfc690522b39194-68f53e24)
[api-reference/beta/api/educationclass-delete-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delete-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delete-members?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-0da171b0acc1cbc43e9c054b4e5bb10c-68f53e24)
[api-reference/beta/api/educationclass-delete-teachers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delete-teachers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delete-teachers?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-57f58a8cd7e214358926ef6dfc48911f-68f53e24)
[api-reference/beta/api/educationclass-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delete.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delete?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-b39747146ba41115beb0c680b5adda0f-68f53e24)
[api-reference/beta/api/educationclass-delta.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-delta.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-delta?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-0385954bb8b74555de4e3bdf083e6b06-68f53e24)
[api-reference/beta/api/educationclass-get-group.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-get-group.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get-group?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-ab09d010a07d4c1a16d9b4a51972868d-68f53e24)
[api-reference/beta/api/educationclass-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-get.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-get?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-97ae3a82af0097578a5e23f4fc7d8681-68f53e24)
[api-reference/beta/api/educationclass-list-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-assignments?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-bf04c86074906bc42031ccde9c7da3d1-68f53e24)
[api-reference/beta/api/educationclass-list-categories.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-categories.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-categories?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-daf1f29b457339db2443a7b01a18d2dc-68f53e24)
[api-reference/beta/api/educationclass-list-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-members?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-85f74e8770c5ed64057be078c0c019b8-68f53e24)
[api-reference/beta/api/educationclass-list-schools.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-schools.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-schools?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-5dc476b6b82463bac47e5395193a55ac-68f53e24)
[api-reference/beta/api/educationclass-list-teachers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-list-teachers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-list-teachers?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-41b485a8fcbf4a1f922715e2bb12ea74-68f53e24)
[api-reference/beta/api/educationclass-post-assignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-assignments.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-assignments?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-61b34680d3f4f97ecd9ebe645dec376a-68f53e24)
[api-reference/beta/api/educationclass-post-category.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-category.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-category?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-7bfab65502f7f59c62bc9c0f78900289-68f53e24)
[api-reference/beta/api/educationclass-post-members.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-members.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-members?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-f7b8bd4f9f6d7a33267e19d3e62acde7-68f53e24)
[api-reference/beta/api/educationclass-post-teachers.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-post-teachers.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-post-teachers?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-41040e81a448ae55fcf1ea3b4adbc589-68f53e24)
[api-reference/beta/api/educationclass-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-reference/beta/api/educationclass-update.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/educationclass-update?view=graph-rest-beta&branch=pr-en-us-11731) (graph-rest-beta) | [Details](#user-content-20a26885ee8ffe40b187a8eb9bba9903-68f53e24)
[api-reference/beta/api/educationroot-list-classes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/marcla/edu-ownership/api-referenc [...]

2021-05-04 19:49 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-06-09 16:23 UTC, lramosvea commented
Hi @mlafleur what's the status of this PR? Is it ready for review, if so please fix conflicts and add the "content review" label. Thanks.

2021-06-24 17:53 UTC, isvargasmsft requested changes
Hello @mlafleur, 

Please note we don't use the ms.author attribute to avoid exposing the alias information. 

Is there a particular reason to add this attribute?

Kind regards, 

Isaac Vargas

2021-09-01 15:00 UTC, closed without merging