radded transitive reports count
microsoftgraph/microsoft-graph-docs pull request #11849
Opened 2021-03-04 18:20 UTC by davidmu1

2021-03-04 20:11 UTC, opbld32 commented
Docs Build status updates of commit _[5c3f82e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c3f82ee6c54076697352654953aee9abd43b80c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) | [Details](#user-content-8e4f1bb3-de25b9ba)
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) | [Details](#user-content-701a9716-de25b9ba)
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) | [Details](#user-content-8fa18829-de25b9ba)
[api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/intune-shared-devicemanagementderivedcredentialsettings-get?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) | [Details](#user-content-e65a6842-de25b9ba)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="8e4f1bb3-de25b9ba"></a>
### [api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="701a9716-de25b9ba"></a>
### [api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="8fa18829-de25b9ba"></a>
### [api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="e65a6842-de25b9ba"></a>
### [api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/intune-shared-devicemanagementderivedcredentialsettings-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 72, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103042001115861-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Bt0X2rriijuISFlolkTDLj6ox6OpH7FhBZTHq2cQmCY%3D&st=2021-03-04T20%3A05%3A59Z&se=2021-04-04T20%3A10%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-05 20:31 UTC, opbld34 commented
Docs Build status updates of commit _[a6a17e6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a6a17e6b03a31d5545651feb04325ae63f9b5a56)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103052030106921-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c6ysSoRirD%2FXAfdplVfLsO2u2kXoInn3ZYLubUZv5FA%3D&st=2021-03-05T20%3A26%3A25Z&se=2021-04-05T20%3A31%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 21:28 UTC, Licantrop0 requested changes
change contextualLevel to ConsistencyLevel where indicated

2021-04-06 21:31 UTC, Licantrop0 commented on api-reference/beta/resources/orgcontact.md
> +| [Get transitiveReports count](../api/directoryobject-gettransitivereportscount.md) | [directoryObject](directoryobject.md) collection | Get the transitive reports count for an organization contact
integer

2021-04-06 21:33 UTC, Licantrop0 requested changes

2021-04-06 21:33 UTC, Licantrop0 commented on api-reference/beta/resources/user.md
> +| [Get transitiveReports count](../api/directoryobject-gettransitivereportscount.md) | [directoryObject](directoryobject.md) collection | Get the transitive reports count for a user from the transiti
```suggestion
| [Get transitiveReports count](../api/directoryobject-gettransitivereportscount.md) | integer | Get the transitive reports count for a user from the transitiveReports navigation property. |
```

2021-05-03 14:50 UTC, opbld33 commented
Docs Build status updates of commit _[4da1804](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4da18042866f62ad721f50192e2b920b935a8d45)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 16:43 UTC, Licantrop0 approved these changes

2021-05-03 17:25 UTC, opbld31 commented
Docs Build status updates of commit _[8b06987](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8b069872e6d9f332f97c50240f08bed455d64d9e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105031724089927-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1xz4wf1REKWxBLvsDwbQDmwlRg1uzlFzrhl%2FABAtmyE%3D&st=2021-05-03T17%3A20%3A10Z&se=2021-06-03T17%3A25%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 01:28 UTC, Lauragra commented on api-reference/beta/api/directoryobject-gettransitivereportscount.md
> +# Get transitiveReports count
@davidmu1 , do you have the api.md or CSDL file for this method? I can't verify that it's live in the metadata; are you sure it's ready to merge? Thanks.

2021-05-04 16:13 UTC, opbld33 commented
Docs Build status updates of commit _[4d331ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4d331ec1093897fb5fcd7a8bd3bb057bbd2199d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105041612243662-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JgGorP6rBPYriwVvUNmV%2F%2BFzKYqa54X8HXM9PFRBlmw%3D&st=2021-05-04T16%3A08%3A26Z&se=2021-06-04T16%3A13%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 21:22 UTC, opbld31 commented
Docs Build status updates of commit _[0021f45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0021f45c45b19e9973430cfb2646c70376599816)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182120361871-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Ff8WFFbGZxh3m45xlazXdUrpd1WtCMvF7T6PdILbwQE%3D&st=2021-05-18T21%3A17%3A12Z&se=2021-06-18T21%3A22%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 22:29 UTC, opbld34 commented
Docs Build status updates of commit _[0021f45](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0021f45c45b19e9973430cfb2646c70376599816)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105182227479973-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C9X1jFODZcEB7o6F6SYSu3iNlaQPDu0XSxGwPANDNDs%3D&st=2021-05-18T22%3A24%3A07Z&se=2021-06-18T22%3A29%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 13:46 UTC, wandeg commented on changelog/Microsoft.DirectoryServices.json
>            "Id": "3dc87842-0acd-4b98-89b3-a798f6bbc044",
Looks like there's an opening brace that's missing here at the beginning of this ChangeList entry

2021-05-19 16:36 UTC, opbld31 commented
Docs Build status updates of commit _[3aa83c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3aa83c8dda36ebe4329abc5245f078ea327b07d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105191635374895-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vDAiiTzF3BkR8RHKbFjIGk30KcDCZNZ%2Fd1UIyMmFHxg%3D&st=2021-05-19T16%3A31%3A53Z&se=2021-06-19T16%3A36%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-19 22:43 UTC, Lauragra commented on api-reference/beta/api/directoryobject-gettransitivereportscount.md
> +title: "Get transitiveReports count"
To conform to our file naming conventions, you'll want to have two separate files since this is a nav property on two entities: user-get-transitivereports and contacts-get-transitivereports. We don't include query parameters in the file names or the titles. You can include an Optional query parameters section where you explain that they can use the $count parameter to get the count, and you can show that in an example. Also, you'll want to update this section of the query parameters topic to list contacts: https://docs.microsoft.com/en-us/graph/query-parameters#count-parameter.

2021-05-19 22:44 UTC, Lauragra commented on api-reference/beta/resources/orgcontact.md
> +| [Get transitiveReports count](../api/directoryobject-gettransitivereportscount.md) | Integer | Get the transitive reports count for an organization contact from the transitiveReports navigation pro
Currently the method topic doesn't mention orgContacts or include an example for that.

2021-05-19 22:45 UTC, Lauragra commented on api-reference/beta/api/directoryobject-gettransitivereportscount.md
> +GET /contacts/{id}/transitiveReports/$count
Maybe what you meant for this syntax is orgContact? Please be sure to clarify, In that case no need to update the query parameters topic because it's already listed.

2021-05-19 22:46 UTC, Lauragra commented on api-reference/beta/resources/orgcontact.md
> +| [Get transitiveReports count](../api/directoryobject-gettransitivereportscount.md) | Integer | Get the transitive reports count for an organization contact from the transitiveReports navigation pro
The method name here and in the users topic would be "Get transitiveReports".

2021-05-19 22:49 UTC, Lauragra commented on api-reference/beta/toc.yml
> +        - name: Get transitive reports count
Expose under Organizational contacts as well?

2021-05-19 22:52 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> +      "ChangeList": [
This changelist entry doesn't appear to apply to the content of this PR.

2021-05-22 17:44 UTC, opbld30 commented
Docs Build status updates of commit _[06f7b5c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/06f7b5c22f3024ef8827cb4c261c4d08cf01cd2a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105221743084526-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qBezqvY%2FN4VZN8MuBcfgUJ8RkxWrh6X3KpA8D%2BKJSHY%3D&st=2021-05-22T17%3A39%3A30Z&se=2021-06-22T17%3A44%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-24 14:55 UTC, davidmu1 commented on api-reference/beta/api/directoryobject-gettransitivereportscount.md
> +title: "Get transitiveReports count"
@Lauragra - Is it really appropriate to have files named *-get-transitivereports when the response is not a transitive report, but is only the count of reports?

2021-05-27 07:07 UTC, opbld34 commented
Docs Build status updates of commit _[01e6a04](https://github.com/microsoftgraph/microsoft-graph-docs/commits/01e6a04d23d6724006c4897eff65f3786874b03f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/directoryobject-gettransitivereportscount.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/api/directoryobject-gettransitivereportscount.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/orgcontact.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/orgcontact.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/orgcontact?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/resources/user.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/resources/user.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/directoryobject-gettransitivereportscount?view=graph-rest-beta&branch=pr-en-us-11849) (graph-rest-beta) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/directoryobjectupdate1/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105270706073257-11849%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=cWunsG0uAbkY4ZG%2F%2F3GxuZvHt1oKwIUsUPAqf0Ag2I4%3D&st=2021-05-27T07%3A02%3A20Z&se=2021-06-27T07%3A07%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-04 20:16 UTC, closed without merging