New notificationContentType and notificationQueryOptions properties
microsoftgraph/microsoft-graph-docs pull request #11865
Opened 2021-03-05 11:10 UTC by Jumaodhiss

Adding the notificationContentype and notificationQueryOptions properties to the change notification API. 
For more information go to _https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/6438_ and _https://microsoftgraph.visualstudio.com/onboarding/_git/onboarding/pullrequest/6016_ respectively

2021-03-05 11:12 UTC, opbld30 commented
Docs Build status updates of commit _[2026f0c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2026f0c31795d601ca5f09ac6ad981f39a0f6532)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-bc0724a5-3ca9bbfd)
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-69825fde-3ca9bbfd)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-642cd3a0-3ca9bbfd)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-8f8d1d71-3ca9bbfd)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-a8c89eee-3ca9bbfd)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-409b84f8-3ca9bbfd)
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-25c40722-3ca9bbfd)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-a8874aa1-3ca9bbfd)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-71b0b2ed-3ca9bbfd)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-57b8827d-3ca9bbfd)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2ad28f54-3ca9bbfd)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-b393c635-3ca9bbfd)

<a id="bc0724a5-3ca9bbfd"></a>
### [api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="69825fde-3ca9bbfd"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="642cd3a0-3ca9bbfd"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-3ca9bbfd"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a8c89eee-3ca9bbfd"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="409b84f8-3ca9bbfd"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/micr [...]

2021-03-05 11:24 UTC, opbld32 commented
Docs Build status updates of commit _[73afe20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/73afe20c337b788ee5da9b7d13748f53d77dd9be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-bc0724a5-ea0ee478)
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-69825fde-ea0ee478)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-642cd3a0-ea0ee478)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-8f8d1d71-ea0ee478)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-a8c89eee-ea0ee478)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-409b84f8-ea0ee478)
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-25c40722-ea0ee478)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-a8874aa1-ea0ee478)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-71b0b2ed-ea0ee478)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-57b8827d-ea0ee478)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2ad28f54-ea0ee478)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-b393c635-ea0ee478)

<a id="bc0724a5-ea0ee478"></a>
### [api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="69825fde-ea0ee478"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="642cd3a0-ea0ee478"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-ea0ee478"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a8c89eee-ea0ee478"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="409b84f8-ea0ee478"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/micr [...]

2021-03-05 11:29 UTC, opbld34 commented
Docs Build status updates of commit _[2b7ee86](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b7ee86303b15b1cbe3cae137acb73ebe9a2073a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-bc0724a5-9b91bf8a)
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-69825fde-9b91bf8a)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-642cd3a0-9b91bf8a)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-8f8d1d71-9b91bf8a)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-a8c89eee-9b91bf8a)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-409b84f8-9b91bf8a)
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-25c40722-9b91bf8a)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-a8874aa1-9b91bf8a)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-71b0b2ed-9b91bf8a)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-57b8827d-9b91bf8a)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2ad28f54-9b91bf8a)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-b393c635-9b91bf8a)

<a id="bc0724a5-9b91bf8a"></a>
### [api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="69825fde-9b91bf8a"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="642cd3a0-9b91bf8a"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-9b91bf8a"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a8c89eee-9b91bf8a"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="409b84f8-9b91bf8a"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/micr [...]

2021-03-05 11:38 UTC, opbld34 commented
Docs Build status updates of commit _[96f6caf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96f6caff2623775add094742cd493d0bbc106c6f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-bc0724a5-5c1043f7)
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-69825fde-5c1043f7)
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-642cd3a0-5c1043f7)
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-8f8d1d71-5c1043f7)
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-a8c89eee-5c1043f7)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-409b84f8-5c1043f7)
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-25c40722-5c1043f7)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-a8874aa1-5c1043f7)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-71b0b2ed-5c1043f7)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-57b8827d-5c1043f7)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2ad28f54-5c1043f7)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-b393c635-5c1043f7)

<a id="bc0724a5-5c1043f7"></a>
### [api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="69825fde-5c1043f7"></a>
### [api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="642cd3a0-5c1043f7"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8f8d1d71-5c1043f7"></a>
### [api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="a8c89eee-5c1043f7"></a>
### [api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md)
 - **Line 2, Column 1**: **[Warning-[ms-author-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-author-missing?branch=main)]** `````Missing required attribute: 'ms.author'. Add the current author's Microsoft alias.`````

<a id="409b84f8-5c1043f7"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/micr [...]

2021-03-05 13:04 UTC, baywet requested changes
- The changelog entry is missing
- When looking at the schema, those new properties are only available in beta at the moment and not in v1.0. Is the deployment to v1.0 planned soon?
- You should probably update the concept page as well https://docs.microsoft.com/en-us/graph/webhooks

2021-03-05 15:52 UTC, Jumaodhiss commented
> * The changelog entry is missing
> * When looking at the schema, those new properties are only available in beta at the moment and not in v1.0. Is the deployment to v1.0 planned soon?
> * You should probably update the concept page as well https://docs.microsoft.com/en-us/graph/webhooks

Thanks @baywet.
>* The v1.0 is actually ready. The schema will be updated by the Engineering team. 
>*As for the changelog, @Lauragra advised that we should not include an entry. This took effect on 15th Jan 2021.
>* I will review and update the concept page. Thanks for this pointer.

2021-03-05 17:09 UTC, davidmu1 requested changes
Don't forget the changelog. For more information, see https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

2021-03-08 08:48 UTC, opbld33 commented
Docs Build status updates of commit _[c8b9e7d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c8b9e7d0d8a90cfb585e6ac0df963f03873804b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-642cd3a0-a2b485e5)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-a8874aa1-a2b485e5)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-71b0b2ed-a2b485e5)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-57b8827d-a2b485e5)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2ad28f54-a2b485e5)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-b393c635-a2b485e5)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="642cd3a0-a2b485e5"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a8874aa1-a2b485e5"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="71b0b2ed-a2b485e5"></a>
### [api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="57b8827d-a2b485e5"></a>
### [api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-re [...]

2021-03-08 08:50 UTC, Jumaodhiss commented
> Don't forget the changelog. For more information, see https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog

Hi David. I've updated the changelog as advised. Thanks

2021-03-09 22:03 UTC, davidmu1 approved these changes

2021-03-18 07:27 UTC, opbld31 commented
Docs Build status updates of commit _[0c14101](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c141016847c3d29b0ad078bc96fc616f7b5c47d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-672a8b2d)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-672a8b2d)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-672a8b2d)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-672a8b2d)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-672a8b2d)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-672a8b2d)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-672a8b2d)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-672a8b2d"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-672a8b2d"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-672a8b2d"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="af780f9f [...]

2021-03-18 07:36 UTC, opbld32 commented
Docs Build status updates of commit _[ea5ebc9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ea5ebc985ee6edb41a9bcb2065891b8389fad115)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-5bc57dd5)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-5bc57dd5)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-5bc57dd5)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-5bc57dd5)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-5bc57dd5)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-5bc57dd5)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-5bc57dd5)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-5bc57dd5"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-5bc57dd5"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-5bc57dd5"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="af780f9f [...]

2021-03-18 07:45 UTC, opbld34 commented
Docs Build status updates of commit _[4f70780](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f707807e153cc0759ffd7adbc7100ee1f9d474f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-dd725f72)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-dd725f72)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-dd725f72)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-dd725f72)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-dd725f72)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-dd725f72)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-dd725f72)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-dd725f72"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-dd725f72"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-dd725f72"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 07:51 UTC, opbld31 commented
Docs Build status updates of commit _[8fb001c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8fb001cd0c87d447d648dfefb1d05f6091c9be30)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-5ad0963b)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-5ad0963b)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-5ad0963b)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-5ad0963b)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-5ad0963b)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-5ad0963b)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-5ad0963b)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-5ad0963b"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-5ad0963b"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-5ad0963b"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="af780f9f [...]

2021-03-18 07:57 UTC, opbld34 commented
Docs Build status updates of commit _[5981804](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5981804ceb33d34f3230ce55b55b747f2ab12f1d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-6bdbe07a)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-6bdbe07a)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-6bdbe07a)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-6bdbe07a)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-6bdbe07a)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-6bdbe07a)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-6bdbe07a)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-6bdbe07a"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-6bdbe07a"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-6bdbe07a"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 08:02 UTC, opbld34 commented
Docs Build status updates of commit _[20cd7ed](https://github.com/microsoftgraph/microsoft-graph-docs/commits/20cd7ed7cd5a1257912d44157b64ebb7f7eaa99b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-3d050431)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-3d050431)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-3d050431)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-3d050431)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-3d050431)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-3d050431)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-3d050431)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-3d050431"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-3d050431"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-3d050431"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 08:05 UTC, opbld34 commented
Docs Build status updates of commit _[b833200](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b8332008dc2b22953cc7aa9f6092ae5a2d60ae90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-179f4af4)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-179f4af4)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-179f4af4)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-179f4af4)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-179f4af4)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-179f4af4)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-179f4af4)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-179f4af4"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-179f4af4"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-179f4af4"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 08:08 UTC, opbld34 commented
Docs Build status updates of commit _[d9ba34d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9ba34d186c1a2f4e4f2f51ade234011c1befaec)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-a436d54e)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-a436d54e)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-a436d54e)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-a436d54e)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-a436d54e)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-a436d54e)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-a436d54e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-a436d54e"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-a436d54e"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-a436d54e"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 08:14 UTC, opbld34 commented
Docs Build status updates of commit _[b079d28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b079d2816aa534c13b5a87d6ca048ead683d99b6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-e0e5a9b6)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-e0e5a9b6)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-e0e5a9b6)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-e0e5a9b6)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-e0e5a9b6)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-e0e5a9b6)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-e0e5a9b6)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-e0e5a9b6"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-e0e5a9b6"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-e0e5a9b6"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 08:18 UTC, opbld34 commented
Docs Build status updates of commit _[2a25cc4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2a25cc440fc75a711216d53f9efa444836b779df)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-d67dd7b0)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-d67dd7b0)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-d67dd7b0)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-d67dd7b0)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-d67dd7b0)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-d67dd7b0)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-d67dd7b0)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-d67dd7b0"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-d67dd7b0"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-d67dd7b0"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 08:32 UTC, opbld32 commented
Docs Build status updates of commit _[3406402](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3406402908c0a8757b50059fe4dc19b10688628d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-ec9d13e7)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-ec9d13e7)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-ec9d13e7)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-ec9d13e7)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-ec9d13e7)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-ec9d13e7)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-ec9d13e7)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-ec9d13e7"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-ec9d13e7"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-ec9d13e7"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 09:04 UTC, opbld32 commented
Docs Build status updates of commit _[77cf2b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/77cf2b546f88711cbd0513edd70c65aa197a0adc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-297912cc)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-297912cc)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-297912cc)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-297912cc)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-297912cc)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-297912cc)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-297912cc)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-297912cc"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-297912cc"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-297912cc"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 09:09 UTC, opbld32 commented
Docs Build status updates of commit _[80403e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/80403e5f6f6bdda16f223c42e672d6e78882a0bb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-7bd9b016)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-7bd9b016)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-7bd9b016)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-7bd9b016)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-7bd9b016)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-7bd9b016)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-7bd9b016)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-7bd9b016"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-7bd9b016"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-7bd9b016"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="af780f9f [...]

2021-03-18 09:15 UTC, opbld31 commented
Docs Build status updates of commit _[e9489ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9489eaa276847fa3ca7b1de3a2f914c1942cd2b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-d3e9ae46)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-d3e9ae46)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-d3e9ae46)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-d3e9ae46)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-d3e9ae46)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-d3e9ae46)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-d3e9ae46)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-d3e9ae46"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-d3e9ae46"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-d3e9ae46"></a>
### [api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.` [...]

2021-03-18 12:30 UTC, baywet approved these changes

2021-03-18 16:40 UTC, opbld31 commented
Docs Build status updates of commit _[4fe645b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fe645baccd9b81bda861514173b478af0a27340)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-00377967)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-00377967)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-00377967)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-00377967)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-00377967)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-00377967)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-00377967)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-00377967)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-00377967"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-00377967"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-00377967"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 16:52 UTC, opbld32 commented
Docs Build status updates of commit _[3ea1917](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3ea1917314ad8cf346c5f441f1f3056983da0d13)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-0d93b68a)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-0d93b68a)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-0d93b68a)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-0d93b68a)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-0d93b68a)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-0d93b68a)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-0d93b68a)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-0d93b68a)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-0d93b68a"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-0d93b68a"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-0d93b68a"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:07 UTC, opbld33 commented
Docs Build status updates of commit _[473b07f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/473b07f503089970a41a86c24f1c7a6aaf20ef77)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-26f12143)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-26f12143)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-26f12143)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-26f12143)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-26f12143)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-26f12143)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-26f12143)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-26f12143)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-26f12143)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-26f12143"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-26f12143"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 190**: **[Warning-link-out-of-scope]** `````File '../concepts/universal-print-webhook-notifications.md' referenced by link '../../../concepts/universal-print-webhook-notifications.md' will not be built because it is not included in build scope.`````
 - **Line 61, Column 553**: **[Warning-link-out-of-scope]** `````File '../concepts/universal-print-webhook-notifications.md' referenced by link '../../../concepts/universal-print-webhook-notifications.md' will not be built because it is not included in build scope.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-26f12143"></a>
### [api-re [...]

2021-03-18 17:12 UTC, opbld32 commented
Docs Build status updates of commit _[c282831](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c282831627b0400d721d7fa4297ac2c88683e212)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-368b04c9)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-368b04c9)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-368b04c9)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-368b04c9)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-368b04c9)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-368b04c9)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-368b04c9)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-368b04c9)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-368b04c9"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-368b04c9"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-368b04c9"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:20 UTC, opbld34 commented
Docs Build status updates of commit _[8bb942b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8bb942bcc718b282cacbd9bd199c3b1d4ee1ad2e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-95e7d943)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-95e7d943)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-95e7d943)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-95e7d943)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-95e7d943)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-95e7d943)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-95e7d943)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-95e7d943)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-95e7d943"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-95e7d943"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-95e7d943"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:25 UTC, opbld33 commented
Docs Build status updates of commit _[d52fff6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d52fff6981680c392b8c98fb225c4d43782675cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-885a0432)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-885a0432)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-885a0432)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-885a0432)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-885a0432)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-885a0432)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-885a0432)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-885a0432)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-885a0432"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-885a0432"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-885a0432"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:30 UTC, opbld33 commented
Docs Build status updates of commit _[2b11642](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b116429f13180c3543e957261e7dc97d49f2f6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-2518adab)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-2518adab)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-2518adab)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-2518adab)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-2518adab)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-2518adab)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-2518adab)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-2518adab)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-2518adab"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-2518adab"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-2518adab"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:34 UTC, opbld33 commented
Docs Build status updates of commit _[3027881](https://github.com/microsoftgraph/microsoft-graph-docs/commits/302788107783e6772197bcac0dafeea10485b95b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-83bb590a)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-83bb590a)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-83bb590a)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-83bb590a)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-83bb590a)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-83bb590a)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-83bb590a)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-83bb590a)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-83bb590a"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-83bb590a"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-83bb590a"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:38 UTC, jahsu-MSFT requested changes

2021-03-18 17:38 UTC, jahsu-MSFT commented on api-reference/beta/resources/subscription.md
> +| notificationContentType | string | Desired content-type for MS Graph change notifications for supported resource types. The default content-type is the "application/json" content-type. | Universal
This property is not specific to Universal Print

2021-03-18 17:38 UTC, jahsu-MSFT commented on api-reference/v1.0/resources/subscription.md
> +| notificationContentType | string | Desired content-type for MS Graph change notifications for supported resource types. The default content-type is the "application/json" content-type. | [Universal
This is not for universal print service

2021-03-18 17:38 UTC, jahsu-MSFT commented on api-reference/v1.0/resources/webhooks.md
> +| Cloud printing [printTaskDefinition][] | Changes when there is a valid job in the queue (JobStarted event) :<br>`/print/printtaskdefinition/{id}/tasks` <br>Changes when a print job is ready to be d
please remove this part as I already added it on the top of the file and it needs to be in alphabetical order

2021-03-18 17:40 UTC, opbld32 commented
Docs Build status updates of commit _[3c042fa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3c042fa3a1d57e786f189dd1628e571eebb2e9b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-6fbe05c1)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-6fbe05c1)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-6fbe05c1)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-6fbe05c1)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-6fbe05c1)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-6fbe05c1)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-6fbe05c1)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-6fbe05c1)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-6fbe05c1)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-6fbe05c1"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-6fbe05c1"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 189**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 17:40 UTC, Jumaodhiss commented on api-reference/v1.0/resources/webhooks.md
> +| Cloud printing [printTaskDefinition][] | Changes when there is a valid job in the queue (JobStarted event) :<br>`/print/printtaskdefinition/{id}/tasks` <br>Changes when a print job is ready to be d
Sure. Let me check

2021-03-18 17:45 UTC, opbld34 commented
Docs Build status updates of commit _[bf43fac](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf43fac27b1ba4016fccbde484a899e1b1959c1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-8683a715)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-8683a715)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-8683a715)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-8683a715)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-8683a715)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-8683a715)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-8683a715)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-8683a715)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-8683a715)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-8683a715"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-8683a715"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 189**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 17:49 UTC, opbld30 commented
Docs Build status updates of commit _[3b4b53a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3b4b53a0f4f2bf654b48ce895c3a3c9b10f71744)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-d77f47bb)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-d77f47bb)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-d77f47bb)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-d77f47bb)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-d77f47bb)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-d77f47bb)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-d77f47bb)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-d77f47bb)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-d77f47bb"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ea4ffde31d3d5508782d5a396a42b2-d77f47bb"></a>
### [api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f7ecbe9ebfe1f082f33bc66d3a219c5-d77f47bb"></a>
### [api-reference/v1.0/api/subscript [...]

2021-03-18 17:58 UTC, opbld31 commented
Docs Build status updates of commit _[bfa89a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfa89a82da8e7b59ae0ad753214bebab17ea12d4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-db7fc5aa)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-db7fc5aa)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-db7fc5aa)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-db7fc5aa)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-db7fc5aa)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-db7fc5aa)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-db7fc5aa)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-db7fc5aa)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-db7fc5aa)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-db7fc5aa"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-db7fc5aa"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 190**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 18:05 UTC, opbld34 commented
Docs Build status updates of commit _[9e7ddd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9e7ddd23633ecd6312a084f5ae895972fdb705cb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-35f07a62)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-35f07a62)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-35f07a62)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-35f07a62)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-35f07a62)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-35f07a62)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-35f07a62)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-35f07a62)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-35f07a62)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-35f07a62"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-35f07a62"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 190**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 18:25 UTC, opbld34 commented
Docs Build status updates of commit _[d5ddfa5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5ddfa577c322a205d5277e07833cfc23170b842)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-ca984b03)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-ca984b03)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-ca984b03)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-ca984b03)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-ca984b03)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-ca984b03)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-ca984b03)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-ca984b03)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-ca984b03)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-ca984b03"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-ca984b03"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 190**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 18:48 UTC, opbld34 commented
Docs Build status updates of commit _[ab0eb34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ab0eb34453625ea062d307cae7f7d5be0a7cdacc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-70a5cc09)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-70a5cc09)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-70a5cc09)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-70a5cc09)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-70a5cc09)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-70a5cc09)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-70a5cc09)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-70a5cc09)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-70a5cc09)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-70a5cc09"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-70a5cc09"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 60, Column 190**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 19:31 UTC, opbld33 commented
Docs Build status updates of commit _[9269af0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9269af0324238a736f906408949e9e57630990f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-8381a455)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-8381a455)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-8381a455)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-8381a455)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-8381a455)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-8381a455)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-8381a455)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-8381a455)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-8381a455)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-8381a455"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-8381a455"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 27, Column 137**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 52**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains l [...]

2021-03-18 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[ba23f74](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ba23f743d8168e8fc3ca57e93828ec363461b3f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-da042f10)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-da042f10)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-da042f10)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-da042f10)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-da042f10)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-da042f10)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-da042f10)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-da042f10)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-da042f10)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-da042f10"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-da042f10"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 27, Column 137**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 52**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains l [...]

2021-03-18 19:40 UTC, opbld33 commented
Docs Build status updates of commit _[b5d0e5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5d0e5b9a78b4a0c3496409ff0e3d5854f26ad66)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-4ed4c25f)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-4ed4c25f)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-4ed4c25f)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-4ed4c25f)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-4ed4c25f)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-4ed4c25f)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-4ed4c25f)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-4ed4c25f)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-4ed4c25f)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-4ed4c25f"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-4ed4c25f"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 27, Column 137**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 52**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains l [...]

2021-03-18 19:46 UTC, opbld30 commented
Docs Build status updates of commit _[5b84152](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5b841529eb20f94b7ca635c613bd56b77bc61c75)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-0de94da3)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-0de94da3)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-0de94da3)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-0de94da3)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-0de94da3)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-0de94da3)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-0de94da3)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-0de94da3)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-0de94da3)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-0de94da3"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-0de94da3"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 27, Column 137**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 28, Column 52**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains l [...]

2021-03-18 20:20 UTC, jahsu-MSFT approved these changes

2021-03-18 20:20 UTC, jahsu-MSFT commented on api-reference/beta/resources/subscription.md
> +- A [printer][] in Print Service (when a print job for the printer gets to JobFetchable state - ready to be fetched for printing). See  [Universal Print Service](https://docs.microsoft.com/en-us/grap
@Lauragra @baywet Any suggestion on this part? The usage of printer resource and printTaskDef resource is a bit different from others so we had our own change notifications page created a while back(you both reviewed it).
We are thinking to add a link to that page for both printer and printTaskDef resource so that users can find examples and more details about it.

2021-03-18 21:10 UTC, nilakhan requested changes

2021-03-18 21:10 UTC, nilakhan commented on concepts/universal-print-webhook-notifications.md
> +For details about how to retrieve a list of webhook subscriptions, see [List subscriptions](/graph/api/subscription-list?view=graph-rest-v1.0&tabs=http).
@jahsu-MSFT we can remove view=graph-rest-v1.0 altogether.
It will by go to v1.0 by default. I got comment in my PR for v1.0 documentation

2021-03-18 21:17 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +For details about how to retrieve a list of webhook subscriptions, see [List subscriptions](/graph/api/subscription-list?view=graph-rest-v1.0&tabs=http).
@Lauragra what's the recommendation here? I personally don't see an issue of being more specific.

2021-03-18 21:30 UTC, Lauragra commented on concepts/universal-print-webhook-notifications.md
> +For details about how to retrieve a list of webhook subscriptions, see [List subscriptions](/graph/api/subscription-list?view=graph-rest-v1.0&tabs=http).
The only issue would be that if there's a v2.0 in the future, this will default to v1.0 until you update it manually. When no version is specified for the link, it goes to the latest version by default.

2021-03-18 21:31 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +For details about how to retrieve a list of webhook subscriptions, see [List subscriptions](/graph/api/subscription-list?view=graph-rest-v1.0&tabs=http).
In that case, I think we should be specific here.

2021-03-18 21:36 UTC, jahsu-MSFT commented on concepts/universal-print-webhook-notifications.md
> +For details about how to retrieve a list of webhook subscriptions, see [List subscriptions](/graph/api/subscription-list?view=graph-rest-v1.0&tabs=http).
As I think even in the future, we have v2.0 version, v1.0 will still be kept, right (so that we don't break existing users)? And we might not want an auto-update to change everything to v2.0 immediately.

2021-03-18 21:38 UTC, Lauragra commented on api-reference/beta/resources/subscription.md
> +- A [printer][] in Print Service (when a print job for the printer gets to JobFetchable state - ready to be fetched for printing). See  [Universal Print Service](https://docs.microsoft.com/en-us/grap
I made some adjustments here; see what you think.

2021-03-18 21:39 UTC, opbld30 commented
Docs Build status updates of commit _[6e22907](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e2290729ce1165edf06dfb51ed8b20fc0389eb1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-e052951e)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-e052951e)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-e052951e)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-e052951e)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-e052951e)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-e052951e)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-e052951e)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-e052951e)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-e052951e)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-e052951e"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-e052951e"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 27, Column 181**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 60, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-18 21:44 UTC, davidmu1 commented on api-reference/beta/resources/subscription.md
> +- A [printer][] (when a print job for the printer gets to JobFetchable state - ready to be fetched for printing) and a [printTaskDefinition][] in Universal Print (for details, see [Subscribe to chang
```suggestion
- A [printer][] When a print job for the printer gets to JobFetchable state - ready to be fetched for printing and a [printTaskDefinition][] in Universal Print. For more information, see [Subscribe to change notifications from cloud printing APIs](https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications).
```

2021-03-18 21:46 UTC, davidmu1 approved these changes

2021-03-19 05:02 UTC, opbld31 commented
Docs Build status updates of commit _[22b86e4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22b86e44b1e37c7655407cde80dd89e50fb998f3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ea836b3a)

<a id="ea836b3a"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103190502009982-11865%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F8lWnkPZIs%2BeiuXjJKvIFLFQevbjsPIeezhXs%2BRzQAw%3D&st=2021-03-19T04%3A57%3A15Z&se=2021-04-19T05%3A02%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 05:09 UTC, nilakhan commented on concepts/universal-print-webhook-notifications.md
> +For details about how to retrieve a list of webhook subscriptions, see [List subscriptions](/graph/api/subscription-list?view=graph-rest-v1.0&tabs=http).
I agree that its good to be specific here. 
The v2.0 notifications may not have universal print.

2021-03-19 05:10 UTC, nilakhan approved these changes

2021-03-19 05:18 UTC, opbld31 commented
Docs Build status updates of commit _[b30c37c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b30c37c91b4f252d5777dc4a4aea46c27e991bee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-11cb6404)

<a id="11cb6404"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103190518276883-11865%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EPQKrUmdmoEMNOg1vw1JWFPBr1v6qmQHZZYg8SsQH3A%3D&st=2021-03-19T05%3A13%3A49Z&se=2021-04-19T05%3A18%3A49Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 05:24 UTC, opbld30 commented
Docs Build status updates of commit _[96b925e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/96b925e2da4d0d9f03698466d0859390eda88a57)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-819cf8a9)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-819cf8a9)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-819cf8a9)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-819cf8a9)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-819cf8a9)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-819cf8a9)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-819cf8a9)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-819cf8a9)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-819cf8a9)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-819cf8a9"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-819cf8a9"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 28, Column 140**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 29, Column 75**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains l [...]

2021-03-19 13:07 UTC, jahsu-MSFT commented on api-reference/beta/resources/subscription.md
> +- A [printer][] in Print Service (when a print job for the printer gets to JobFetchable state - ready to be fetched for printing). See  [Universal Print Service](https://docs.microsoft.com/en-us/grap
Thanks @Lauragra. 

@Jumaodhiss We just need to make the same changes to both beta and v1.0 versions. Everything else looks good I think.
Thanks

2021-03-19 13:12 UTC, opbld30 commented
Docs Build status updates of commit _[e136648](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1366481a99b6ee47c9f7a2be202420c0bd4051c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-946c9b6287a6e9718b114089da3d23de-79ab3608)
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-79ab3608)
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-14ea4ffde31d3d5508782d5a396a42b2-79ab3608)
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-2f7ecbe9ebfe1f082f33bc66d3a219c5-79ab3608)
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-af780f9f433ca0dd9188a3773e8d4942-79ab3608)
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-f2b5e865a9ad39404303398ec1807f50-79ab3608)
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-15fe287cbd6b25f37bf0e4854d1af40a-79ab3608)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-79ab3608)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-79ab3608)
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="946c9b6287a6e9718b114089da3d23de-79ab3608"></a>
### [api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e8b2d78ce86acda2d3af67b160da3b31-79ab3608"></a>
### [api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md)
 - **Line 28, Column 188**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 61, Column 553**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/graph/universal-print-webhook-notifications' contains  [...]

2021-03-19 13:20 UTC, jahsu-MSFT commented
@Lauragra please merge this PR in after reviewing. Thanks!

2021-03-19 16:02 UTC, Lauragra commented on api-reference/v1.0/api/subscription-delete.md
> +doc_type: resourcePageType
Restore apiPageType value.

2021-03-19 16:02 UTC, Lauragra commented on api-reference/v1.0/api/subscription-get.md
> +author: "Jumaodhiss"
Please add the missing ms.prod value, "change-notifications".

2021-03-19 16:07 UTC, Lauragra commented on api-reference/v1.0/api/subscription-list.md
>  ms.prod: ""
Add missing ms.prod value.

2021-03-19 16:08 UTC, Lauragra commented on api-reference/v1.0/api/subscription-post-subscriptions.md
>  ms.prod: ""
Global: Please add the missing value to all the topics.

2021-03-19 16:08 UTC, Lauragra commented on api-reference/v1.0/resources/subscription.md
> +- A [printer][] When a print job for the printer gets to JobFetchable state - ready to be fetched for printing and a [printTaskDefinition][] in Universal Print. For more information, see [Subscribe t
Please make the same edits here as per the beta topic.

2021-03-19 16:11 UTC, Lauragra commented on changelog/Microsoft.SubscriptionServices.json
> +    {
Do we also need to add a ChangeList item to call out that we added support for subscribing to change notifications to the printer and printTaskDefinition resources? Also, the date in the CreatedDateTime field will need to reflect the date that we merge this PR.

2021-03-19 17:14 UTC, Jumaodhiss commented on changelog/Microsoft.SubscriptionServices.json
> +    {
I will make the change on Date. Am however not sure about _"Do we also need to add a ChangeList item to call out that we added support for subscribing to change notifications to the printer and printTaskDefinition resources?"_

2021-03-19 17:33 UTC, opbld34 commented
Docs Build status updates of commit _[97e0c21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/97e0c213094a31c345317690019f197689732508)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-59800f1f)

<a id="59800f1f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103191729551798-11865%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0vH5JtETmZ8RO4sNPlU3wrT1ppxjr%2BS%2FVjLMzPq8QS8%3D&st=2021-03-19T17%3A28%3A05Z&se=2021-04-19T17%3A33%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 17:52 UTC, opbld34 commented
Docs Build status updates of commit _[7d086c5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7d086c5773dfffad80cfd6c22710ac2fbea368b7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) | [Details](#user-content-e8b2d78ce86acda2d3af67b160da3b31-09711509)
[api-reference/v1.0/resources/subscription.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/subscription.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/subscription?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) | [Details](#user-content-c4b02b78c2f6af14dfc0b3a8950f9a01-09711509)
[concepts/universal-print-webhook-notifications.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/concepts/universal-print-webhook-notifications.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/universal-print-webhook-notifications?branch=pr-en-us-11865) | [Details](#user-content-8a00d056207283e10d79e0219972da9a-09711509)
[.github/workflows/conflicting-pr-label.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/.github/workflows/conflicting-pr-label.yml) | :white_check_mark:Succeeded | |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | |
[api-reference/beta/resources/signin.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/signin.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/signin?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/beta/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/beta/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-beta&branch=pr-en-us-11865) (graph-rest-beta) |
[api-reference/v1.0/api/subscription-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-delete?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-get?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-list?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-post-subscriptions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-post-subscriptions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/api/subscription-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/api/subscription-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/subscription-update?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appliedconditionalaccesspolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/appliedconditionalaccesspolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appliedconditionalaccesspolicy?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/webhooks.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/api-reference/v1.0/resources/webhooks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/webhooks?view=graph-rest-1.0&branch=pr-en-us-11865) (>= graph-rest-1.0) |
[changelog/Microsoft.SubscriptionServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/subscriptionPropertyUpdate/changelog/Microsoft.SubscriptionServices.json) | :white_check_mark:Succeeded | |

<a id="e8b2d78ce86acda2d3af67b160da3b31-09711509"></a>
### [ [...]

2021-03-19 21:20 UTC, closed without merging

2021-03-19 21:21 UTC, opbld33 commented
Docs Build status updates of commit _[8621fec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8621fec1082f528e1020300aaffe4d50a5a4edd8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e45e9781)

<a id="e45e9781"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103192120596749-11865%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uWi0n7ukD2O0nXa5KlPoZYcFR3fpPb1ElNHv6mywu8A%3D&st=2021-03-19T21%3A16%3A15Z&se=2021-04-19T21%3A21%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>