Consent requests APIs (Promote to GA)
microsoftgraph/microsoft-graph-docs pull request #11921
Opened 2021-03-09 19:28 UTC by FaithOmbongi

2021-03-09 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[3fd36ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3fd36ce141ec70e515516bc63ee1f0fd069b1335)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) | [Details](#user-content-558a9dd9-6924781f)
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) | [Details](#user-content-08a218a0-6924781f)
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-6924781f)
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="558a9dd9-6924781f"></a>
### [api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-referen [...]

2021-03-10 08:14 UTC, opbld30 commented
Docs Build status updates of commit _[4853839](https://github.com/microsoftgraph/microsoft-graph-docs/commits/48538390c3cef57df016c6dca4abc9fd36a65cb7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-bae65087)

<a id="bae65087"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103100814121989-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=1pFtD6ZPUHndYybQ66ZHGPJ89vbJegNhxg%2BZgr4auYU%3D&st=2021-03-10T08%3A09%3A28Z&se=2021-04-10T08%3A14%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-10 08:32 UTC, opbld31 commented
Docs Build status updates of commit _[0e780a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0e780a605529fe53c58077e40453a97461e73174)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) | [Details](#user-content-1ef9a9bd-ea38d93e)
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="1ef9a9bd-ea38d93e"></a>
### [api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md)
 - **Line 6, Column 10**: **[Warning-[m [...]

2021-03-11 06:45 UTC, opbld30 commented
Docs Build status updates of commit _[a9dc614](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a9dc61407273f5fe8b54079b20a5b4a4c5d9e74b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103110644207126-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J8dYQXv3vBq2z4V%2FNAaBB%2BEeiM%2FOm0zaT [...]

2021-03-11 09:27 UTC, opbld31 commented
Docs Build status updates of commit _[523a761](https://github.com/microsoftgraph/microsoft-graph-docs/commits/523a7613bddec045f490655b7aeb1f683b9b67cb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103110925483721-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bRv89r%2BDvcTArfe%2FfJFQ4n9KbrjXFdFB9xx [...]

2021-03-11 09:43 UTC, opbld32 commented
Docs Build status updates of commit _[9d03f12](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9d03f120ea4f2a6674b1192d2dc28561c81da190)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103110942083940-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zUrF8R5mzzQhQhKp6nVaDMtJ1cymFjTgaQNwlJr [...]

2021-03-11 18:35 UTC, opbld32 commented
Docs Build status updates of commit _[90f2e1d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/90f2e1d131105dd0b8481a563a20cbcf80c1ef47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103111834293683-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GBmJ8vYAcLXGbLs8FzVaZLFK6wA2V6qwHWNq78c [...]

2021-03-12 07:51 UTC, opbld34 commented
Docs Build status updates of commit _[22a71bd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22a71bd1abae2c0845efa3448d9abe2933c59358)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d38332de)

<a id="d38332de"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103120751352556-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KAIyvA%2B6Oeim4bhuIgA9o8YgUAWN3ygHg0yR%2B9rx5Kg%3D&st=2021-03-12T07%3A46%3A54Z&se=2021-04-12T07%3A51%3A54Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 07:55 UTC, opbld30 commented
Docs Build status updates of commit _[1dcc916](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1dcc916750561e2d14789c741dc9d38ec6b7ee7e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-69404817)

<a id="69404817"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103120754451991-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GonHIXmVMmVO%2FKDJNW%2FmpRdYIqE6NMTDLOCnhikJ%2B1w%3D&st=2021-03-12T07%3A50%3A00Z&se=2021-04-12T07%3A55%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 08:01 UTC, opbld30 commented
Docs Build status updates of commit _[df614fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/df614fe3e461db0645bb3a775d3318dba98a5a6b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103120800235960-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HW4vmfniNkWDsVn%2BLwZVKqvHUuMs0dSKbaHll [...]

2021-03-12 08:03 UTC, opbld30 commented
Docs Build status updates of commit _[86ea782](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86ea782a132056be07bce7df7672afa13ffffeb4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103120802397640-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Pp8vKBr0COeLlM0QDxGxB1s1sZltDvkDUFt4jMu5m1o%3D&st=2021-03-12T07%3A58%3A53Z&se=2021-04-12T08%3A03%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external [...]

2021-03-16 06:54 UTC, opbld34 commented
Docs Build status updates of commit _[6129775](https://github.com/microsoftgraph/microsoft-graph-docs/commits/612977575672b8ae23537200ce50777e6d755bfb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103160653140281-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BqUil8d5billTEhfVXisshH7C3v1nJOkoH3krQq2SzI%3D&st=2021-03-16T06%3A49%3A41Z&se=2021-04-16T06%3A54%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external [...]

2021-03-16 07:03 UTC, opbld33 commented
Docs Build status updates of commit _[957cb21](https://github.com/microsoftgraph/microsoft-graph-docs/commits/957cb21674b3df086be0906e697ce7aff4070d14)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103160702153875-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=r%2BxPO9Jok9D9%2FW1lwvH8RZvIYVFWlr%2BTcWF7e2b7Xa0%3D&st=2021-03-16T06%3A58%3A27Z&se=2021-04-16T07%3A03%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or ex [...]

2021-03-16 16:21 UTC, davidmu1 approved these changes

2021-03-19 07:33 UTC, opbld34 commented
Docs Build status updates of commit _[1891292](https://github.com/microsoftgraph/microsoft-graph-docs/commits/18912927a1edaa8230e09506ad0e7d2e8a2d5a8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103190731554709-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DJS14rqmrxRtrXEtva2XNIULLU9jWjMLB8aO0pc [...]

2021-03-22 07:38 UTC, opbld30 commented
Docs Build status updates of commit _[dae7e32](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dae7e32ea50a018b841c76fc816a0f10a3fdf041)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103220737158498-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=zWa0E1HAqOINmGcITnVx8faj%2BkeF4NuRkfay6 [...]

2021-03-23 13:46 UTC, psignoret approved these changes

2021-03-26 13:50 UTC, psignoret requested changes

2021-03-26 14:17 UTC, opbld30 commented
Docs Build status updates of commit _[063876f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/063876f41d83d664006d2419b85129b0009b94fc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103261415558545-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=coYeCIeJ%2BG09fUpy0pq79VOum8aqO45EjMs8m [...]

2021-03-26 14:19 UTC, opbld30 commented
Docs Build status updates of commit _[1c40c31](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c40c315843d043da481f7773fa849238d76e186)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103261416422282-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jc4p8XYgJFBFm5nOWpJDYgTvo6RhGJxd2LjxI4v [...]

2021-03-26 14:21 UTC, psignoret approved these changes

2021-03-30 01:23 UTC, Lauragra commented on changelog/Microsoft.DirectoryServices.json
> -        "ChangeList": [
Why is this PR deleting these two ChangeList items?

2021-03-30 01:25 UTC, opbld32 commented
Docs Build status updates of commit _[2781e6d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2781e6dbf191acaf6c1cffc1d9d6fc4dc7ecbecd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/adminconsentrequestpolicy-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/adminconsentrequestpolicy-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/adminconsentrequestpolicy-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-update?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/appconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/appconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/appconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-filterbycurrentuser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-filterbycurrentuser?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/api/userconsentrequest-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/api/userconsentrequest-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/userconsentrequest-list?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/accessreviewreviewerscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/accessreviewreviewerscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewreviewerscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/adminconsentrequestpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/adminconsentrequestpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/adminconsentrequestpolicy?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appconsentrequestscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/appconsentrequestscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appconsentrequestscope?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approval.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approval?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/approvalstage.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/approvalstage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/approvalstage?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/azure-ad-overview.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/azure-ad-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/azure-ad-overview?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/consentrequests-root.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/consentrequests-root.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/consentrequests-root?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/userconsentrequest.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/resources/userconsentrequest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/userconsentrequest?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/adminconsentrequestpolicy-get?view=graph-rest-1.0&branch=pr-en-us-11921) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-09-consentRequestAPI-GA/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103300124071010-11921%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c33mSuUCQImnBPfH20UL%2F510g95NmNPUiubzS [...]

2021-03-30 01:27 UTC, merged