Onboarding Search Admin Documentation
microsoftgraph/microsoft-graph-docs pull request #11920
Opened 2021-03-09 17:57 UTC by zadinsmo

2021-03-09 17:58 UTC, opbld34 commented
Docs Build status updates of commit _[91987b1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/91987b173fe4c2ffeedbd65060042466a54a1813)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e5935931)

<a id="e5935931"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C9%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103091757514009-11920%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RLm40OUaJti8wf3SeGx8X1hpwrbJay26mlIJx8p5rw8%3D&st=2021-03-09T17%3A53%3A09Z&se=2021-04-09T17%3A58%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-19 05:58 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-create.md
> +Namespace: microsoft.graph
Line 11 and GLOBAL:
Based on your api.md files, your APIs are defined in a subnamespace microsoft.graph.search.
Please make sure each reference topic in your API set indicates that namespace and not microsoft.graph.
Please see more info for documenting APIs defined in a subnamespace here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103169/OData-subnamespace

2021-03-19 06:07 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-create.md
> +
Filename for "create" operation topics:
Based on your CSDL and disregarding the namespace for a moment, the filename structure should be resourcename-post-entitysetname.md. That is, acronym-post-acronyms.md.
More info on this filename pattern is here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming?anchor=microsoft-graph-file-naming-guidelines

Considering that your API is _defined in a subnamespace_:
Please make sure to prepend each filename with the subnamespace name. In your case, your API is in a subnamespace microsoft.graph.search, so the filename for this topic would be search-acronym-post-acronyms.md.
More info here: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103169/OData-subnamespace?anchor=filenames

2021-03-19 06:13 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-create.md
> +|Delegated (work or school account)| Global Administrator, Search Administrator, Search Editor |
GLOBAL:
Can you confirm the correctness of the permissions table contents? The api.md files specifies permissions SearchConfiguration.Read.All and SearchConfiguration.ReadWrite.All for delegated and applications permissions.

Also, if your APIs are using these permissions, please update permissions-reference.md to include the appropriate documentation.

2021-03-19 06:16 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-create.md
> +|description|String|A brief description of the acronym that gives users more info about the acronym and what it stands for Inherited from [searchAnswer](../resources/searchanswer.md)|
Line 47 and GLOBAL:
Please make sure your sentences are complete with the necessary punctuation. For example, in the description for line 47, you're missing a period after "...stands for", and after the end of the last sentence.
Having improper or missing punctuation gives an impression that the docs were generated and lowers customers' confidence.

2021-03-19 06:34 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-create.md
> +  "webUrl": "https://DNN",
Line 78 and GLOBAL, anywhere you have URLs as examples:

Please refer to this page to make sure you use CELA-approved URLs: https://microsoft.sharepoint.com/sites/celaweb-copyrights-trademarks-and-patents/sitepages/trademarks-fictitious-names.aspx

In general, there are very few real-looking names, addresses, email addresses, phone numbers, URLs,... we can use in docs.

2021-03-19 06:39 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-get.md
> +        "displayName": "Ryan Gregg"
Line 85:
I mentioned this issue in a comment above characterized as "GLOBAL", but I'd like to make sure you don't miss this example - please make sure you follow CELA guidance when specifying peoples' names in the docs. This string name is likely not approved.
More info: https://microsoft.sharepoint.com/sites/celaweb-copyrights-trademarks-and-patents/sitepages/trademarks-fictitious-names.aspx

2021-03-19 06:42 UTC, angelgolfer-ms commented on api-reference/beta/api/bookmark-create.md
> +|availabilityStartDateTime|DateTimeOffset|Bookmark start date to appear as a search result (Set as null for always available)|
Lines 54 and 55:
Please put "Set as null for always available" as a separate, second sentence, without the parentheses, and with a period at the end, like any sentence.

2021-03-19 06:44 UTC, angelgolfer-ms commented on api-reference/beta/resources/enums.md
> +### answerState values
Lines 1588-1594:
Is this the only enum used in your API set?
Per your api.md files, since your API set is defined in a subnamespace, please make sure to document your enums the correct way for subnamespaces. https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103159/Enums-in-subnamespaces

2021-03-19 06:47 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +Q&A are administrative answer results similar to bookmarks. Q&As allow Admins to answer the user's questions instead of just providing a link to a webpage. A Q&A has many properties which allow Admin
Line 14 and GLOBAL:
Please use "administrators" in place of "Admins".
Please note the capitalization as well - only for officially branded services and products can we use capitalized first letter for names, everything else, including feature names, should be in lower case.
More info here: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357

2021-03-19 06:48 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +Q&A are administrative answer results similar to bookmarks. Q&As allow Admins to answer the user's questions instead of just providing a link to a webpage. A Q&A has many properties which allow Admin
Line 14:
Please rephrase "This is based on microsoft.graph.search.searchAnswer" as "Inherited from searchAnswer."
Please provide a link to the search-searchanswer.md topic.
Please don't forget to end your sentences with a period!

2021-03-19 06:49 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +\
Lines 17 and 18:
Unless you explain what "main properties" and "advanced properties" mean and how the differentiation is significant, I suggest we delete these sentences.

2021-03-19 07:01 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +Q&A are administrative answer results similar to bookmarks. Q&As allow Admins to answer the user's questions instead of just providing a link to a webpage. A Q&A has many properties which allow Admin
Line 14:
Please don't start the summary description with this sentence "Q&A are administrative answer results similar to bookmarks."
FYI the first sentence in a resource topic or API topic is supposed to be a single-sentence paragraph, that provides a concise description of the purpose of that resource or API.
In this case, you rely on customers understanding what a bookmark is to provide a concise description for the purpose of qna. That's not helpful. Even when we compare at the property level, bookmark seems to have just 2 additional properties - categories and powerAppIds - when compared with qna, and that's their difference.
So, what is a qna? A customer may assume literally this represents a question and answer pair, but your properties don't indicate that's the case. Can you please form a sentence that summarizes what a qna is in your API set?

2021-03-19 07:05 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +|platforms|devicePlatformType collection|List of devices and OS able to view this Qna. Possible values are: `android`, `androidForWork`, `iOS`, `macOS`, `windowsPhone81`, `windows81AndLater`, `window
Line 42 and GLOBAL:
Please make sure enums defined in a subnamespace are documented appropriately in their subnamespace enum file. More info: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103159/Enums-in-subnamespaces?anchor=first-option%3A-in-a-general-enums-file-for-that-subnamespace

2021-03-19 07:09 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +|keywords|[answerKeyword](../resources/answerkeyword.md)|Keywords for this Qna. Properties include: keywords, reservedKeywords, and matchSimilarKeywords.|
Line 44:
Since answerKeyword is a complex type and you already documented answerkeyword.md, for consistency, please don't include the second sentence "Properties include: keywords, reservedKeywords, and matchSimilarKeywords."
When/if that type gets additional properties later on, this would be one place to maintain and may slip through the cracks too.

2021-03-19 07:16 UTC, angelgolfer-ms commented on api-reference/beta/resources/qna.md
> +|targetedVariations|[answerVariant](../resources/answerVariant.md) collection|List of Qna targeted variations. Use when you need to show different content to users based on their device, or country a
Lines 43, 44:
These are just some of the examples in this PR that can really use more informative resource and property descriptions, but please take this comment and review the descriptions for resources and other properties in your API set.
What is a targeted variation? Your first sentence should provide a concise description without repeating the same words of the property name. The second sentence is helpful, but that last term in parentheses "(Targeted Variations)" is confusing - is it supposed to refer to some concept that customers should already know?  If customers don't already know that term, please exclude it.
Also, per my comment somewhere above about capitalization, just wanted to take the chance to point out that we shouldn't capitalize "Dates" and "Groups". Please make sure to correct other instances in this PR to follow appropriate capitalization: https://styleguides.azurewebsites.net/Styleguide/Read?id=2696&topicid=25357

2021-03-19 07:18 UTC, angelgolfer-ms commented on api-reference/beta/resources/bookmark.md
> +|lastModifiedBy|[identitySet](../resources/identityset.md)|Read only. Details of the user that created or last modified the bookmark Inherited from [searchAnswer](../resources/searchanswer.md)|
Line 38 and GLOBAL:
Please move sentences like "Read only." to the end of the description. A description should start with a concise sentence describing the purpose of the property.

2021-03-19 07:19 UTC, angelgolfer-ms commented on api-reference/beta/resources/bookmark.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark|
Line 46:
Can you include how PowerApps are relevant in the context of bookmarks?
This would make the description more helpful.

2021-03-19 07:23 UTC, angelgolfer-ms commented on api-reference/beta/resources/bookmark.md
> +|webUrl|String|Bookmark URL Inherited from [searchAnswer](../resources/searchanswer.md)|
Line 37:
It would be appropriate to point out typically what purpose of the webUrl would serve. Is it "The URL of a web page that provides a search result"? Please use the appropriate wording.
It's not helpful to just form a description using the resource name and part of the property name.

2021-03-19 07:29 UTC, angelgolfer-ms commented on api-reference/beta/resources/bookmark.md
> +A bookmark is a tenant wide administrative answer to common queries in a tenant. A bookmark has many properties which allow Admins to make common resources more accessible in their organization.
Line 14:
As someone who has no prior experience with search admin capabilities, I have this question and hope your description can clarify - "tenant wide administrative answer to common queries in a tenant" sounds like "bookmarks" apply to only searches in a domain that is specific to a tenant? 
A search for common terms like "weather today" shouldn't be domain-specific, would such terms (or "questions") be out of context here?

2021-03-19 07:37 UTC, angelgolfer-ms requested changes
Hi @zadinsmo , thank you for the effort in your first Graph docs PR!
I know timeline-wise we're still early to review for API public release, but since you guys put in the effort already, I browsed through all the CSDL and api.md files, and the current topics, and commented on a few areas. I used the term "GLOBAL" to identify you should please look at the rest of the PR where I don't repeat the comment, and make appropriate fixes. 

Please note that there is no editorial service to clean up grammatical and punctuation, so each author is responsible for making their docs professional-looking to get the customer respect their APIs and their efforts so deserve :-)

Please let me know if you have questions. Offline on Teams is fine.

2021-03-20 00:09 UTC, angelgolfer-ms commented on api-reference/beta/api/acronym-create.md
> +|state|answerState|State of the acronym. Possible values are: `published`, `draft`, or `excluded`.. Possible values are: `Published`, `Draft`, `Excluded`.|
Line 53:
Note repeated sentence in the description.

2021-03-20 00:13 UTC, angelgolfer-ms commented on api-reference/beta/api/bookmark-create.md
> +|targetedVariations|[answerVariant](../resources/answerVariant.md) collection|List of bookmark targeted variations. Use when you need to show different content to users based on their device, or coun
Line 58 and GLOBAL:
Based on your api.md file, answerVariant is in a subnamespace. 
When referring to types defined in a subnamespace, in the "Type" column in a properties (or methods) table, please  fully qualify the type name and include its subnamespace.

See this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103169/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions

2021-03-20 00:16 UTC, angelgolfer-ms commented on api-reference/beta/resources/acronym.md
> +|[List acronyms](../api/acronym-list.md)|[acronym](../resources/acronym.md) collection|Get a list of the [acronym](../resources/acronym.md) objects and their properties.|
Lines 24-27, "Return type" column, and GLOBAL:
When referring to types defined in a subnamespace in specific contexts like here, please fully qualify the type name and include its subnamespace.

Just with other GLOBAL comments, I'm not pointing this out in every instance in this topic, and please identify all the instances and make appropriate fixes.

See this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103169/OData-subnamespace?anchor=fully-qualify-a-type-name-in-definitions

2021-05-04 19:49 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-06-30 00:02 UTC, jakeost-msft commented on api-reference/beta/api/acronym-create.md
> +Namespace: microsoft.graph
Updated new files to be under namespace of Microsoft.graph.search

2021-06-30 00:02 UTC, jakeost-msft commented on api-reference/beta/api/acronym-create.md
> +
Updated filenames for operations to recommended format: 
search-acronym-post-acronyms.md.

2021-06-30 00:05 UTC, jakeost-msft commented on api-reference/beta/api/acronym-create.md
> +|description|String|A brief description of the acronym that gives users more info about the acronym and what it stands for Inherited from [searchAnswer](../resources/searchanswer.md)|
Updated punctuation.

2021-06-30 00:05 UTC, jakeost-msft commented on api-reference/beta/api/acronym-create.md
> +  "webUrl": "https://DNN",
Updated fictional content based on guidance.

2021-06-30 00:05 UTC, jakeost-msft commented on api-reference/beta/api/acronym-get.md
> +        "displayName": "Ryan Gregg"
Updated with approved fictional name.

2021-06-30 00:06 UTC, jakeost-msft commented on api-reference/beta/api/bookmark-create.md
> +|availabilityStartDateTime|DateTimeOffset|Bookmark start date to appear as a search result (Set as null for always available)|
Updated.

2021-06-30 00:06 UTC, jakeost-msft commented on api-reference/beta/resources/enums.md
> +### answerState values
Updated with new enums-search.md file.

2021-06-30 00:07 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +Q&A are administrative answer results similar to bookmarks. Q&As allow Admins to answer the user's questions instead of just providing a link to a webpage. A Q&A has many properties which allow Admin
Updated admins to administrators, capitalization, inherited from, 
and summary descriptions.

2021-06-30 00:07 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +\
Removed main/advanced properties sentences.

2021-06-30 00:08 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|platforms|devicePlatformType collection|List of devices and OS able to view this Qna. Possible values are: `android`, `androidForWork`, `iOS`, `macOS`, `windowsPhone81`, `windows81AndLater`, `window
Updated with new enums-search.md file and updated corresponding properties references.

2021-06-30 00:09 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|keywords|[answerKeyword](../resources/answerkeyword.md)|Keywords for this Qna. Properties include: keywords, reservedKeywords, and matchSimilarKeywords.|
Removed "Properties include: keywords, reservedKeywords, and 
matchSimilarKeywords" from keywords properties descriptions.

2021-06-30 00:09 UTC, jakeost-msft commented on api-reference/beta/resources/qna.md
> +|targetedVariations|[answerVariant](../resources/answerVariant.md) collection|List of Qna targeted variations. Use when you need to show different content to users based on their device, or country a
Updated resource and property descriptions.

2021-06-30 00:10 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|lastModifiedBy|[identitySet](../resources/identityset.md)|Read only. Details of the user that created or last modified the bookmark Inherited from [searchAnswer](../resources/searchanswer.md)|
Updated.

2021-06-30 00:10 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|powerAppIds|String collection|PowerApp ids for this bookmark|
Added additional context for PowerApps.

2021-06-30 00:11 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +|webUrl|String|Bookmark URL Inherited from [searchAnswer](../resources/searchanswer.md)|
Clarified webUrl descriptions.

2021-06-30 00:11 UTC, jakeost-msft commented on api-reference/beta/resources/bookmark.md
> +A bookmark is a tenant wide administrative answer to common queries in a tenant. A bookmark has many properties which allow Admins to make common resources more accessible in their organization.
Added clarifying description for bookmarks, acronyms, and qnas.

2021-06-30 00:11 UTC, jakeost-msft commented on api-reference/beta/api/acronym-create.md
> +|state|answerState|State of the acronym. Possible values are: `published`, `draft`, or `excluded`.. Possible values are: `Published`, `Draft`, `Excluded`.|
Fixed.

2021-06-30 00:12 UTC, jakeost-msft commented on api-reference/beta/api/bookmark-create.md
> +|targetedVariations|[answerVariant](../resources/answerVariant.md) collection|List of bookmark targeted variations. Use when you need to show different content to users based on their device, or coun
Added subnamespaces.

2021-06-30 00:12 UTC, jakeost-msft commented on api-reference/beta/resources/acronym.md
> +|[List acronyms](../api/acronym-list.md)|[acronym](../resources/acronym.md) collection|Get a list of the [acronym](../resources/acronym.md) objects and their properties.|
Added subnamespaces.

2021-06-30 00:18 UTC, opbld32 commented
Docs Build status updates of commit _[5c8f6e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5c8f6e70611572b21c025fe9faa82c7ce8733719)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ec290348)

<a id="ec290348"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202106292358188640-11920%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rqvkHyzo0%2BMMeKOXtBdz%2F3zUhOzmztYyNhwmzC0s7NE%3D&st=2021-06-30T00%3A13%3A04Z&se=2021-07-31T00%3A18%3A04Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-30 02:31 UTC, Lauragra commented
@zadinsmo , this PR is adding 5,000 files. Please fix. You might want to create a new branch and open a new PR. Thanks.

2021-09-08 15:00 UTC, closed without merging