2021 02 10 ctapi2
microsoftgraph/microsoft-graph-docs pull request #11926
Opened 2021-03-10 05:50 UTC by swapnil1993

2021-03-10 06:13 UTC, opbld31 commented
Docs Build status updates of commit _[dda0863](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dda0863ff1e012dfd6602f32a98fae570a118863)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103100612208805-11926%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mpIwDHoKkjX3fNxyJLv%2FWB%2FBpEG11dAxwmi%2BZYdFcl8%3D&st=2021-03-10T06%3A08%3A30Z&se=2021-04-10T06%3A13%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-10 11:54 UTC, opbld34 commented
Docs Build status updates of commit _[4ad3506](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ad350684064240e97ad753606cbf72a6b78fddb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103101152574974-11926%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tsa12pFyY1zREraoJRcMGr8HnoOo9lKTE5dO9Rk4ubI%3D&st=2021-03-10T11%3A49%3A11Z&se=2021-04-10T11%3A54%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-10 11:59 UTC, opbld33 commented
Docs Build status updates of commit _[53720d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/53720d8897dfeacf24ec01f6cd6aeaeeb0afeb02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-create?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103101158121256-11926%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=osiDNam7QUF%2FZncVPxG05peXR9KMqNTizqkAYGpNfuY%3D&st=2021-03-10T11%3A54%3A22Z&se=2021-04-10T11%3A59%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 09:48 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-addcopy.md
>  [site]: ../resources/site.md
This comment is actually for the file displayed next - the POST operation topic to create a contentType resource.
According to the current CSDL on the beta endpoint, site and list each has a navigation property called columns, that's a collection of contentType resources. Is it true that you can create a contentType resource for a site, and similarly for a list?

Assuming they're both true, then you would have 2 files that create contentType, with the filenames site-post-contenttypes.md and list-post-contenttypes.md. These filenames follow the pattern parententityname-post-navigationpropertyname.md, as described in the table row for "API (create)" in this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103161/File-naming. For each of the files, you can use the topic title "Create contentType for site", "Create contentType for list".

Each of these topics should appear in the Methods table of the corresponding parent type (i.e., site resource topic and list resource topic). And both topics should also appear in the Methods table of the contentType resource topic.

2021-03-12 10:11 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-addcopy.md
>  [site]: ../resources/site.md
Technically, the similar filenaming pattern would apply for the "list" operation too:  site-list-contenttypes.md and list-list-contenttypes.md. These filenames follow the pattern parententityname-list-navigationpropertyname.md. I see that currently, the topic contentype-list.md defines the syntax for both the site and list cases.

2021-03-12 10:18 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-addcopy.md
>  [site]: ../resources/site.md
Perhaps you can confirm the supported syntax for the "create" and "list" operations, and I'll then confirm the actual files we should have.
And then I can confirm where the operations (especially the "create" and "list" operation topics) should be exposed in the TOC, for contentType and for columnDefinition.

2021-03-12 10:22 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-addcopy.md
> -<!-- { "blockType": "response" } -->
Please also update line 59, the "Response" section. It should have the correct response code and response type.

2021-03-12 10:31 UTC, angelgolfer-ms commented on api-reference/beta/resources/contentType.md
> +|[isPublished](../api/contenttype-ispublished.md)|Boolean| Checks if the [contentType](../resources/contenttype.md) is published.|
After line 25, you can insert two table rows, one for  contenttype-list-columns.md  and the other for contentype-post-columns.md.
The current stub topic generator generates Method tables for a parent resource topic, that would include the "list" and "create" topics for each nav property, if the "list" and "create" operations are supported for that nav property.

2021-03-12 10:35 UTC, angelgolfer-ms requested changes
Thanks for the quick response, @swapnil1993 .
Please take a look at my comments, and confirm what's supported (site and list?) for the "create" and "list" operations for contentType.

2021-03-12 16:21 UTC, swapnil1993 commented on api-reference/beta/api/contenttype-addcopy.md
>  [site]: ../resources/site.md
Yes both content types and columns can be created for sites and list. An existing site content type should be copied to the list contentTypes collection to create a content types in a list that is why it is modelled as "addCopy" operation instead of list-post-contenttypes. I will add a file for creating a site content type named "site-post-contenttypes" and also "site-list-contenttypes.md" and "list-list-contenttypes.md" to list content types in both sites and list.
For columns both create an list operations are supported  in both site and list so there also I will need to add the files for each of them.

2021-03-15 05:37 UTC, opbld32 commented
Docs Build status updates of commit _[ecb04d5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ecb04d56151d1f184095126736eed7413c6f677f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-e5e931da77c86a4fa611cd457dcc9727-f1c80a93)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f1c80a93)
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-427c607be25af9a827fad0753845f8c6-f1c80a93)
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-15f30c18695ca3decb0c338a1921f0b8-f1c80a93)
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-c478b2d921003def3cd6968d7f6a00e8-f1c80a93)
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-eb6bcdb83537f1be6fe0da87b0639636-f1c80a93)
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-cd7ce16a79087ec000b31e17237bd590-f1c80a93)
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-40d5231fd277051e58355936ad37b122-f1c80a93)
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-2e5bfefb174e645540cdf8e8e5affae4-f1c80a93)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="e5e931da77c86a4fa611cd457dcc9727-f1c80a93"></a>
### [api-reference/beta/resources/content [...]

2021-03-15 05:49 UTC, opbld33 commented
Docs Build status updates of commit _[f9a2df6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f9a2df63423c1082bd3b2ae7269648597ab7bd7c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-e5e931da77c86a4fa611cd457dcc9727-357b10ea)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-357b10ea)
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-427c607be25af9a827fad0753845f8c6-357b10ea)
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-15f30c18695ca3decb0c338a1921f0b8-357b10ea)
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-c478b2d921003def3cd6968d7f6a00e8-357b10ea)
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-eb6bcdb83537f1be6fe0da87b0639636-357b10ea)
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-cd7ce16a79087ec000b31e17237bd590-357b10ea)
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-40d5231fd277051e58355936ad37b122-357b10ea)
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-2e5bfefb174e645540cdf8e8e5affae4-357b10ea)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="e5e931da77c86a4fa611cd457dcc9727-357b10ea"></a>
### [api-reference/beta/resources/content [...]

2021-03-16 03:54 UTC, opbld34 commented
Docs Build status updates of commit _[139e4c4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/139e4c4b7d7be2b547c901e6386ea821c9f89712)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-e5e931da77c86a4fa611cd457dcc9727-ff47da2f)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ff47da2f)
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-427c607be25af9a827fad0753845f8c6-ff47da2f)
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-15f30c18695ca3decb0c338a1921f0b8-ff47da2f)
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-c478b2d921003def3cd6968d7f6a00e8-ff47da2f)
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-eb6bcdb83537f1be6fe0da87b0639636-ff47da2f)
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-cd7ce16a79087ec000b31e17237bd590-ff47da2f)
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-40d5231fd277051e58355936ad37b122-ff47da2f)
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-2e5bfefb174e645540cdf8e8e5affae4-ff47da2f)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="e5e931da77c86a4fa611cd457dcc9727-ff47da2f"></a>
### [api-reference/beta/resources/content [...]

2021-03-16 04:07 UTC, opbld30 commented
Docs Build status updates of commit _[1f249f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1f249f6a9c1b49a8f2d39f221979508ead41d54f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-fe55641d)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-fe55641d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/bet [...]

2021-03-16 04:16 UTC, opbld32 commented
Docs Build status updates of commit _[87f74f6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/87f74f6a88feeb27cc9a9d424e3a3ffd33739f61)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0fe41351)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-0fe41351"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/bet [...]

2021-03-16 23:03 UTC, opbld32 commented
Docs Build status updates of commit _[dd444eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dd444eba92f7034353fac184b41343e7259732e1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-17 00:58 UTC, angelgolfer-ms commented on api-reference/beta/api/site-list-contenttypes.md
> +Get the collection of [content types][contentType] in a [site][].
Line 14 and in general:
FYI when we provide a link to a type name (in this case contentType), the link text should match the name of the type. I am changing the link text from "content types" (natural language) to "contentType", and rephrasing the sentence as "Get the collection of contentType resources in a site."

2021-03-17 01:04 UTC, angelgolfer-ms commented on api-reference/beta/resources/contentType.md
> +|[Create a site contentType](../api/site-post-contenttypes.md)|[contentType](../resources/contenttype.md)|Create a new [contentType](../resources/contenttype.md) object in a [site](../resources/site.
Line 23:
FYI I am changing the first column link text as "Create contentType for a site". "create a site contentType" with 2 nouns one after another may be ambiguous for localization. In general, where possible, we try to avoid having multiple nouns together.

2021-03-17 01:17 UTC, angelgolfer-ms commented on api-reference/beta/api/site-list-columns.md
> +# List columnDefinitions in a site
Line 10 and general:
Per the [TOC and topic title](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title) topic in the CDK, the topic title for "list" operation topics is "List {navigation property name}". 
So using this topics as an example, the first part of the topic title should be "List columns..." since columns is the nav property name.
Since we have a few similar topics for listing columns, we differentiate the topic titles by appending "in a site", "in a list", "in a content type". So here, we have "List columns in a site" as topic title.

2021-03-17 01:22 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-post-columns.md
>  |:--------------------|:---------------------------------------------------------|
Line 15:
I know the description is pre-existing before this PR, but I have a question - should the description be rephrased as "Add a column, represented by a columnDefinition, to a contentType in a site or list"?

2021-03-17 01:27 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-post-columns.md
>  |:--------------------|:---------------------------------------------------------|
As noted in another comment in this PR, in general, we don't want a few nouns one after another, as this would pose some degree of ambiguity for localization. If we just take the nouns "site or list column", we should say a column in a site or list. But then you can see the problem - it's actually a (existing) content type in a site or list that's getting a new column. Is that correct?

2021-03-17 01:28 UTC, angelgolfer-ms commented on api-reference/beta/api/contenttype-post-columns.md
>  |:--------------------|:---------------------------------------------------------|
So I am going ahead to make that change in line 15, but for this one, please make sure to let me know if I interpret it incorrectly.

2021-03-17 01:46 UTC, angelgolfer-ms commented on api-reference/beta/resources/columndefinition.md
> +|[Update columnDefinition](../api/columndefinition-update.md)|[columnDefinition](../resources/columndefinition.md)|Update the properties of a [columnDefinition](../resources/columndefinition.md) obje
My next question is actually for the topic "Update columnDefinition" (columndefinition-update.md):
Line 57 of that topic currently says:
">**Note:** Only required and hidden properties can be updated."

Do we mean only the required property and the hidden property of columnDefinition can be updated?

If so, we must clarify this by bolding "required" and "hidden" in that sentence in line 57. Bolding identifies those terms as actual property names.
Otherwise, I was expecting that to mean a property in the columnDefinition resource being characterized as required, or as hidden.

Please clarify.

2021-03-17 01:59 UTC, opbld32 commented
Docs Build status updates of commit _[cd1cf33](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd1cf33b8b46d5c466f81fa8a9ad51fae5e3ae0e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3fe63d13)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft.FileServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/changelog/Microsoft.FileServices.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-3fe63d13"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/bet [...]

2021-03-17 01:59 UTC, opbld32 commented
Docs Build status updates of commit _[d19f675](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d19f675a240f47fc5798c82b89e100cebe941667)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-17 04:27 UTC, swapnil1993 commented on api-reference/beta/resources/columndefinition.md
> +|[Update columnDefinition](../api/columndefinition-update.md)|[columnDefinition](../resources/columndefinition.md)|Update the properties of a [columnDefinition](../resources/columndefinition.md) obje
Yes this means that only the required property and the hidden property of columnDefinition can be updated but is applicable to only content type columns. This file was earlier only for content type columns and I missed updating it while adding changes for site and list columns.

2021-03-17 06:07 UTC, angelgolfer-ms commented on api-reference/beta/resources/columndefinition.md
> +|[Update columnDefinition](../api/columndefinition-update.md)|[columnDefinition](../resources/columndefinition.md)|Update the properties of a [columnDefinition](../resources/columndefinition.md) obje
So does it mean for columns in a site or list, any property of columnDefinition, other than the id property, can be updated?

2021-03-18 08:08 UTC, opbld33 commented
Docs Build status updates of commit _[dba986a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dba986a2d5c3934a45b515413129846eed9a6135)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-e69d48a0)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/listitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/listitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-list-versions?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft [...]

2021-03-18 09:26 UTC, opbld32 commented
Docs Build status updates of commit _[94ff01a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94ff01ae6f49349a1c5ae18b4e29a2a4ae016661)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-0205453d)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/listitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/listitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-list-versions?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft [...]

2021-03-18 09:50 UTC, opbld33 commented
Docs Build status updates of commit _[8958f6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8958f6e309c2ba447789376c801bc55136e600ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-713f37b5)
[api-reference/beta/api/columndefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-get?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/columndefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/columndefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/columndefinition-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-addcopy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-addcopy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-addcopy?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-associatewithhubsites.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-associatewithhubsites.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-associatewithhubsites?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-delete?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/contenttype-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/contenttype-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/contenttype-update?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/list-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/list-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/list-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/listitem-list-versions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/listitem-list-versions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/listitem-list-versions?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-list-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-list-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-list-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-columns.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-columns?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/api/site-post-contenttypes.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/api/site-post-contenttypes.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/site-post-contenttypes?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/columndefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/columndefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/columndefinition?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/contentType.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/contentType.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/contenttype?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/list?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[api-reference/beta/resources/site.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-02-10-ctapi2/api-reference/beta/resources/site.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/site?view=graph-rest-beta&branch=pr-en-us-11926) (graph-rest-beta) |
[changelog/Microsoft [...]

2021-03-18 09:56 UTC, angelgolfer-ms approved these changes
@swapnil1993 , FYI I ordered the nodes under "Sites and lists" by first listing "Sites", then "Lists", and then the remaining entities in alphabetical order. This would be consistent with other existing nodes like "Users" and "Groups", under which the main entity comes first, followed by the rest in alphabetical order. I foresee we'll be adding a few more that currently are documented but not in the TOC, so this ordering would work then too.

2021-03-18 09:57 UTC, angelgolfer-ms commented
> @swapnil1993 , FYI I ordered the nodes under "Sites and lists" by first listing "Sites", then "Lists", and then the remaining entities in alphabetical order. This would be consistent with other existing nodes like "Users" and "Groups", under which the main entity comes first, followed by the rest in alphabetical order. I foresee we'll be adding a few more that currently are documented but not in the TOC, so this ordering would work then too.

BTW, someone is following up on the TOC warnings for the few Intune topics, so we can ignore those warnings for now.

2021-03-18 09:58 UTC, merged