add resource name to changelog descriptions for EM app permissions
microsoftgraph/microsoft-graph-docs pull request #11933
Opened 2021-03-10 16:12 UTC by markwahl-msft

Add the resource name to the descriptions as the changed resource name was not visible in the changelog.

2021-03-10 16:15 UTC, opbld31 commented
Docs Build status updates of commit _[1d5027c](https://github.com/markwahl-msft/microsoft-graph-docs/commits/1d5027ca9bd864913e6a320db93e89c350353cd8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-appperm-cl/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103101612586007-11933%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BUTukg8GvwVOburNUUBMpZtTUw%2F3zKuVrub%2BM9rzuAo%3D&st=2021-03-10T16%3A10%3A34Z&se=2021-04-10T16%3A15%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 06:34 UTC, angelgolfer-ms commented on changelog/Microsoft.DirectoryServices.json
>            "ChangedApiName": "accessPackage",
Please take a closer look at the section "Example: Add application permission support to operations of a resource" in this topic: https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103153/Changelog?anchor=linking-from-the-json-changelog

Please specify:
(a) ApiChange as "Permission" 
(b) ChangedApiName should be one of EntitlementManagement.ReadWrite.All or EntitlementManagement.Read.All

Since (b) should contain only one permission value at a time, and each of the 9 entities here supports an additional 2 application permissions, you will end up adding 2x9 such changeList records.
This way when the filtering feature for the changelog rolls out, it will be possible to filter for changes that have happened to each of the 2 permissions.

2021-03-12 06:35 UTC, angelgolfer-ms requested changes
@markwahl-msft , thanks for the quick response! Please take a look at my comment.

2021-05-04 19:49 UTC, jasonjoh commented
Please disregard the earlier message from msftbot. Your pull request was incorrectly flagged.

2021-07-27 03:27 UTC, CelesteDG commented
@FaithOmbongi Did you get a chance to review this?

2021-07-27 05:53 UTC, FaithOmbongi requested changes
+1 for Angela's comments.

2021-12-17 14:57 UTC, isvargasmsft commented
Hello @markwahl-msft, 

What's the status of this PR?

2022-01-05 18:42 UTC, opbld32 commented
Docs Build status updates of commit _[4078bce](https://github.com/markwahl-msft/microsoft-graph-docs/commits/4078bce83a0b12c024a0bb888f8388cae3cc4ea4)_: 

### :warning: Validation status: warnings


For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051838598955-11933%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T18%3A42%3A31Z&sr=b&sp=r&sig=umrO%2B%2FjkwYeqdxd8qkrLoA5f%2FC4pIs%2B865iwAplysvQ%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-05 19:07 UTC, opbld33 commented
Docs Build status updates of commit _[a05ca2f](https://github.com/markwahl-msft/microsoft-graph-docs/commits/a05ca2f9f75d6dd75f7f78a08e4610c77d322bc6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-appperm-cl/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201051905029075-11933%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-05T19%3A07%3A51Z&sr=b&sp=r&sig=1Bv7Af3V9I41d8QHvCSBa1u7kXQnPJb5jUCBzh765rY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-17 19:04 UTC, FaithOmbongi commented
Hi @markwahl-msft, seeing that this PR has been stuck for months. I've reset my review status and will do another review. I hope that these corrections can go live soon.

2022-01-18 16:30 UTC, opbld33 commented
Docs Build status updates of commit _[30e1676](https://github.com/markwahl-msft/microsoft-graph-docs/commits/30e1676f718e65c013a0aa4e618515b3fa3fc269)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog/Microsoft.DirectoryServices.json](https://github.com/markwahl-msft/microsoft-graph-docs/blob/mwahl-appperm-cl/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C1%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202201181627458012-11933%5Cworkflow_report.html?sv=2020-08-04&se=2022-02-18T16%3A30%3A58Z&sr=b&sp=r&sig=mpKRGCWbj6Vg13ewREdo2l7wXrkyMmcuepKurPfQDa4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-01-18 16:35 UTC, FaithOmbongi approved these changes
FYI @Lauragra—this change edits an existing changelog record, consolidating some items.

2022-01-19 03:00 UTC, merged