import api v1
microsoftgraph/microsoft-graph-docs pull request #11950
Opened 2021-03-11 20:43 UTC by bhartono

2021-03-11 20:45 UTC, opbld31 commented
Docs Build status updates of commit _[3baf8e1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3baf8e102681c6520f735f5959709f60965eef6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-13aebb72-8759e59c)
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |

<a id="13aebb72-8759e59c"></a>
### [api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md)
 - **Line 198, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C11%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103112044019113-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xR%2BcDYNv6cf3KSXIEkeUcgqWyWZA7gBW1u%2FDiGtnGnA%3D&st=2021-03-11T20%3A40%3A18Z&se=2021-04-11T20%3A45%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 17:20 UTC, opbld30 commented
Docs Build status updates of commit _[60804ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/60804aec0ca8426cdc37f9c58c9e7bf2a6725159)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-21877e84)

<a id="21877e84"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103121720365667-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GpW294QcT%2BeEhc5x55Z3U48wBxgXd3vCEQHXoeHoNsM%3D&st=2021-03-12T17%3A15%3A52Z&se=2021-04-12T17%3A20%3A52Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-12 20:42 UTC, opbld34 commented
Docs Build status updates of commit _[bd561dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd561dd277d3a7c00612f327dbcb98d85fbcf54e)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-fee69765)

<a id="fee69765"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C12%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103122042189095-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lHKZr7%2FpbG4NvNWAEnzsJq2xiO3Rb2Q%2BTzrJuOWMv74%3D&st=2021-03-12T20%3A37%3A42Z&se=2021-04-12T20%3A42%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-13 00:15 UTC, opbld31 commented
Docs Build status updates of commit _[eb73e97](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb73e972d3e79295e96620160c34e8be28f373b5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-0e57e4df)

<a id="0e57e4df"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103130015372314-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eqxSXKkXNjyuBuVvbCPU5Vc3v7yOCRuWOW8m64Yxgj4%3D&st=2021-03-13T00%3A10%3A51Z&se=2021-04-13T00%3A15%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-13 00:40 UTC, opbld30 commented
Docs Build status updates of commit _[e30fb50](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e30fb50e809b5a006b5231d2d286f49a92e210ba)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-10ac5916)

<a id="10ac5916"></a>
###
 - **[Error-[PullRequestMergeConflict](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/)]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103130039411043-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5h6XF9%2Bjd%2BRR8qBBCEIPTox3K8t1MWG3hdlum0hdtvk%3D&st=2021-03-13T00%3A35%3A09Z&se=2021-04-13T00%3A40%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-13 00:45 UTC, opbld30 commented
Docs Build status updates of commit _[fbb1edb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbb1edb61e1751b6131f3742c505e3c33f321d85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103130043069567-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=q6Ka4R4JGXlV5JM59%2BKyoikcli5LZc%2FI5qVjwCuqhH8%3D&st=2021-03-13T00%3A40%3A10Z&se=2021-04-13T00%3A45%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 22:43 UTC, opbld30 commented
Docs Build status updates of commit _[8de4e20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8de4e20815b06b4f37042213d74983e5d1f4ddd5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 22:59 UTC, opbld31 commented
Docs Build status updates of commit _[e6b66a6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e6b66a68ab1487247551419d254614a60c4d6dcd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-fabaf177)
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="6bba05b369582c2fae3390789d5198ce-fabaf177"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md)
 - **Line 215, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to [...]

2021-03-16 23:17 UTC, opbld34 commented
Docs Build status updates of commit _[51744a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/51744a21cb736d4792d34595d66e95ddfb7d5d29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-7d2c9dc2)
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="6bba05b369582c2fae3390789d5198ce-7d2c9dc2"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md)
 - **Line 215, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to [...]

2021-03-16 23:23 UTC, opbld34 commented
Docs Build status updates of commit _[4cc170b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4cc170b398c16f90b1be8576922c18484009c601)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-f7820dd3)
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="6bba05b369582c2fae3390789d5198ce-f7820dd3"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md)
 - **Line 215, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to [...]

2021-03-16 23:35 UTC, opbld31 commented
Docs Build status updates of commit _[eb8b40f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eb8b40f8409effe89ef939265b1811bff378e912)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 23:58 UTC, opbld32 commented
Docs Build status updates of commit _[9ba39c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ba39c83c9f04b7af501eea40c2562c5e8cac545)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-21da2911)
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="6bba05b369582c2fae3390789d5198ce-21da2911"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md)
 - **Line 215, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to [...]

2021-03-17 00:14 UTC, opbld33 commented
Docs Build status updates of commit _[8f6aa20](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f6aa2030404723e544f7fb59b038e77f5abc87d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-25277ffb)
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="6bba05b369582c2fae3390789d5198ce-25277ffb"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md)
 - **Line 215, Column 1**: **[Warning-[invalid-tab-group](https://review.docs.microsoft.com/en-us/new-hope/specs/conceptual/tabbed-conceptual?branch=master#feature-design)]** `````Tab group with different tab id set.`````

For more details, please refer to [...]

2021-03-18 22:58 UTC, RamjotSingh requested changes

2021-03-18 22:58 UTC, RamjotSingh commented on api-reference/v1.0/api/channel-get.md
>  ```msgraph-interactive
http

2021-03-18 22:58 UTC, RamjotSingh commented on api-reference/v1.0/api/channel-post-message.md
> +### Example 5: Import messages (text only)
Remove text only

2021-03-19 17:50 UTC, opbld32 commented
Docs Build status updates of commit _[7c2dc08](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c2dc08c17a356c858b14012a272c632b962a08d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-f8ce31fb)
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[changelog/Microsoft.Teams.Core.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/changelog/Microsoft.Teams.Core.json) | :white_check_mark:Succeeded | |

<a id="6bba05b369582c2fae3390789d5198ce-f8ce31fb"></a>
### [api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-do [...]

2021-03-19 21:19 UTC, opbld34 commented
Docs Build status updates of commit _[1a44a28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1a44a28f1158292999c9ccf882170594bc425162)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d0c1034f)

<a id="d0c1034f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C19%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103192119084549-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ntfYzNo17rbakDRwRNRuwD8K7BlusqJIocyZ08ozYpw%3D&st=2021-03-19T21%3A14%3A27Z&se=2021-04-19T21%3A19%3A27Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 02:37 UTC, RamjotSingh approved these changes

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/beta/api/channel-list.md
>  {
Have an example with more than 1 channel. Also you are reusing same channel here and below example, might confuse people, have a team with one standard and one private channel in it.

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/beta/api/channel-post-message.md
>     "replyToId":null,
Shorten the properties. Remove stuff which is null or default. Remove importance and locale too. Remove these only from request body.

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/v1.0/api/channel-completemigration.md
> +POST /teams/{teamId}/channels/{channelId}/completeMigration
Fix Id pattern

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/v1.0/api/channel-completemigration.md
> +POST https://graph.microsoft.com/v1.0/teams/57fb72d0-d811-46f4-8947-305e6072eaa5/channels/19:4b6bed8d24574f6a9e436813cb2617d8@thread.tacv2/messages
:) fix please.

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/v1.0/api/channel-list.md
>      }
Same comment as /beta docs.

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/v1.0/api/channel-post-message.md
> +   },
Same comment as /beta/

2021-03-23 02:37 UTC, RamjotSingh commented on api-reference/v1.0/resources/team.md
> +|createdDateTime|dateTimeOffset|Read only. Timestamp at which the team was created.|
This is not read only. Fix in /beta too.

2021-03-23 18:14 UTC, opbld31 commented
Docs Build status updates of commit _[799c3ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/799c3ec1960675b33bc38526ca394d01d9ce83d0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d2ad0be7)

<a id="d2ad0be7"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103231814197910-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gR%2BZnQYU0hNZpx%2FfJUI794QLVfA0ze%2Fdl8UcwKu8aAg%3D&st=2021-03-23T18%3A09%3A42Z&se=2021-04-23T18%3A14%3A42Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 18:19 UTC, opbld32 commented
Docs Build status updates of commit _[5962b68](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5962b68ea680b296d0d3fe79be8c56200288cb67)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a4001f5f)

<a id="a4001f5f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103231819072984-11950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=c6ZROQxsg%2ByHSb9b%2B7acJKoLwViAfHJzKvlKRY1gM0A%3D&st=2021-03-23T18%3A14%3A35Z&se=2021-04-23T18%3A19%3A35Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 18:50 UTC, opbld31 commented
Docs Build status updates of commit _[e9fe70b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e9fe70b50a11672f01f71ecf983866ff27b0b61d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-c8c2161a)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-c8c2161a)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-03-23 19:51 UTC, opbld34 commented
Docs Build status updates of commit _[9f3ee92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9f3ee923bec65508006bd408b927b8b5948aa6e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-176da712)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-176da712)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-03-23 20:24 UTC, opbld33 commented
Docs Build status updates of commit _[36b66e7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/36b66e708a9b9af0a8689916313d381468243421)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-e64421a7)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-e64421a7)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-03-24 00:09 UTC, Lauragra commented on api-reference/beta/api/channel-patch.md
> +>**Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
FYI, the standard boilerplate no longer includes the second sentence (it's not technically accurate). Secondly, we don't include the boilerplate text when there's no response body.

2021-03-24 00:12 UTC, opbld30 commented
Docs Build status updates of commit _[1aca5c1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1aca5c1ffe6f0cec23d6e209d8878f783f848ce8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-3fcc1d90)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-3fcc1d90)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-03-24 00:12 UTC, Lauragra commented on api-reference/v1.0/api/channel-post-messagereply.md
> +## Example 1: Create a new reply to a chatMessage
We need to have a standard H2 Examples. The numbered examples then become H3s, and the Request and Response headings are H4s. Please update.

2021-03-24 00:15 UTC, Lauragra commented on api-reference/v1.0/api/channel-post.md
> +> **Note**: Permissions marked with * use [resource-specific consent]( https://aka.ms/teams-rsc).
You have three Notes in a row here. Note that overusing the note formatting can reduce the impact of the note formatting to call attention to the reader. We generally try not to have two or more notes next to each other, in case you want to find a way to better separate the information.

2021-03-24 00:16 UTC, Lauragra commented on api-reference/v1.0/api/channel-post.md
> +# [HTTP](#tab/http)
Global: Don't include this H1; it gets added by the snippet generation.

2021-03-24 00:16 UTC, Lauragra commented on api-reference/v1.0/api/channel-post.md
> +---
When you delete the HTTP, delete this extra line too.

2021-03-24 00:19 UTC, Lauragra commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "channel-post",
The ChangedApiName should match the target. We don't use file names as values for the ChangedApiName.  Also, please make sure that the changelog reflects everything in this PR? It looks like we added two new actions to v1.0?

2021-03-24 17:56 UTC, opbld34 commented
Docs Build status updates of commit _[2d0db8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2d0db8c9866db47c8f6ab9dfb6d37415506c1df5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-f28d4c29d035830c28b4a14bc83e2489-fe2b04d2)
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-fe2b04d2)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-fe2b04d2)
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get. [...]

2021-03-24 18:01 UTC, opbld30 commented
Docs Build status updates of commit _[5540999](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5540999aa20e7370f3215cef94f4a8acdf0b22f5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-9d22138f)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-9d22138f)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-03-24 18:26 UTC, opbld32 commented
Docs Build status updates of commit _[0519497](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0519497ade4f854cb9d3c7eb3aa21f6e703b230f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-6bba05b369582c2fae3390789d5198ce-41f14f81)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-41f14f81)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/team-get.md) | :white_check_mark:Succeeded | [View](https://revie [...]

2021-03-24 18:37 UTC, opbld32 commented
Docs Build status updates of commit _[fed056b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fed056b0ebe0b148984565c0ba236816378f589a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) | [Details](#user-content-428b6a90dbb02a960c3bae224a296b4c-82f000d4)
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-82f000d4)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://re [...]

2021-03-24 18:44 UTC, opbld30 commented
Docs Build status updates of commit _[1c80eab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1c80eab52b8d3a751346b44b897d2dc66d8f72fe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-2f30670e)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-mes [...]

2021-03-24 19:46 UTC, bhartono commented on api-reference/v1.0/api/channel-post.md
> +> **Note**: Permissions marked with * use [resource-specific consent]( https://aka.ms/teams-rsc).
i have no opinion on what to do here. @nkramer asked me to add the new note for monetization.

2021-03-24 20:09 UTC, opbld30 commented
Docs Build status updates of commit _[84ffdfb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/84ffdfb661dbdf05741e6a82fad4a69efb2cb0d7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-f96fc81a)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-mes [...]

2021-03-24 20:15 UTC, bhartono commented on changelog/Microsoft.Teams.Core.json
> +          "ChangedApiName": "channel-post",
fixed. thanks for catching it!

2021-03-24 21:45 UTC, opbld32 commented
Docs Build status updates of commit _[4156fd2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4156fd2a08092f02fcd52a780bb5647aca26dba4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-a240c494)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-mes [...]

2021-03-24 21:49 UTC, opbld31 commented
Docs Build status updates of commit _[c0b672e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c0b672e990e5d55c6a0088069d921df22f4ca257)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-9463ff80)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-mes [...]

2021-03-24 21:51 UTC, opbld33 commented
Docs Build status updates of commit _[2b345ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b345ab14c0a7387ec518b401deebd0a882ca7e3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-900ee4d1)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-mes [...]

2021-03-24 22:07 UTC, opbld32 commented
Docs Build status updates of commit _[6e8903b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6e8903b7d43beb5739d0231077b971273f15dbdb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-message.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) | [Details](#user-content-5cdb5923524827ff6457b8d920556e22-638d24c6)
[api-reference/beta/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-message.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-message.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-message?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-messagereply?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/channel-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/channel-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-completemigration?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-get?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-post?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/api/team-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/api/team-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/team-update?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/beta/resources/team.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/beta/resources/team.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/team?view=graph-rest-beta&branch=pr-en-us-11950) (graph-rest-beta) |
[api-reference/v1.0/api/channel-completemigration.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-completemigration.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-completemigration?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-delete?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-get?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list-tabs.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list-tabs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list-tabs?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-list?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-patch.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-patch.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-patch?view=graph-rest-1.0&branch=pr-en-us-11950) (>= graph-rest-1.0) |
[api-reference/v1.0/api/channel-post-messagereply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/bhartono/importV1/api-reference/v1.0/api/channel-post-messagereply.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/channel-post-mes [...]

2021-03-24 22:07 UTC, Lauragra approved these changes

2021-03-24 22:20 UTC, merged