Starting with some updates - testing with Angela
microsoftgraph/microsoft-graph-docs pull request #11997
Opened 2021-03-15 21:05 UTC by isvargasmsft

You can ignore this. We are testing.

2021-03-15 21:07 UTC, opbld34 commented
Docs Build status updates of commit _[4945f5b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4945f5bfd2dad5c5769976369e008e2635459748)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C15%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103152105495455-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9uK3n%2F56h2phfUrOkd%2BqsOGPxtKImlSep3ts5LXMaCs%3D&st=2021-03-15T21%3A02%3A02Z&se=2021-04-15T21%3A07%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 00:29 UTC, opbld30 commented
Docs Build status updates of commit _[a0077da](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0077daab2ab6c314da762aa26f4e61083d8313c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103160028232121-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=MKV5IMCOokGPlC624J6u3i69c5wSYJd234t9R7V%2BsCQ%3D&st=2021-03-16T00%3A24%3A28Z&se=2021-04-16T00%3A29%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-16 01:12 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +To replace an existing item
Lines 30, 41, and 52:
Please end each of these lines with a colon (':').

2021-03-16 01:15 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +<!-- { "blockType": "request", "name": "upload-via-put", "scopes": "files.readwrite" } -->
Line 148:
Please provide a new name in this JSON statement:
"name": "upload-via-put",
API Doctor doesn't call this out (yet), but I think last week Laura brought up that these names being unique will become a requirement.

2021-03-16 01:19 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +This example uploads a new file to a Shared-With-Me folder.
Line 146 and anywhere else:
Wherever you use the string Shared with me, because this is UI text, please bold the string and use the same spelling and capitalization as the UI text. 
If for instance, the OneDrive UI text is **exactly the same** as the Excel screen shot you shared with me on Teams, then wherever you use that string in this topic, please use **Shared with Me**, capital 'S' and M' as in the Excel screen shot.

2021-03-16 01:30 UTC, angelgolfer-ms reviewed
Good job, @isvargasmsft , for your first PR in Graph!
Please see a few minor comments on fit-and-finish items.

Also, per our Teams chat, please add after line 17, in a separate paragraph, some description for the **Shared with Me** feature in OneDrive for Business, since you're referring to **Shared with Me** in subsequent content in the topic.

It might not be the most intuitive for customers where they would see that exact UI string. As we saw in OneDrive for Business, clicking **Shared** -> **Share with you** and **Share by you**, but there's no **Shared with Me** in that context.

2021-03-17 15:24 UTC, opbld31 commented
Docs Build status updates of commit _[b7c6205](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b7c62050ee079720baec536818522633a9a139df)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103171522072360-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FWxvRSl3geokDskK%2BYMObj%2BHQnHX%2B3jChNdMedn19sw%3D&st=2021-03-17T15%3A19%3A20Z&se=2021-04-17T15%3A24%3A20Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 21:38 UTC, chackman commented on api-reference/v1.0/api/driveitem-put-content.md
> +To upload a new file in a Shared With Me folder:
This pattern - PUT /drives/{drive-id}/items/{item-id}:/{filename}:/content - is not limited to "Shared with Me" items.  It _is_ the pattern that "Shared with Me" items should use, though.

I'd suggest a slight modification to the docs:

To upload a new file using the parent folder and drive ID's, such as a "Shared With Me" folder:
PUT /drives/{drive-id}/items/{item-id}:/{filename}:/content 
For "Shared with Me" items, the drive and item ID's come from the `remoteItem` facet of the `driveItem` that is shared with the user.

2021-04-07 00:34 UTC, isvargasmsft commented on api-reference/v1.0/api/driveitem-put-content.md
> +To upload a new file in a Shared With Me folder:
Hi @chackman, thank you very much for taking the time. 

Implemented your suggestions. Waiting for content review.

2021-04-07 00:34 UTC, opbld33 commented
Docs Build status updates of commit _[86342eb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/86342ebdf839fe579fb1e1fa842fdf4cde4405ea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104070033088807-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=OAPuRHjRoRzO0BLmYSwYCCcwJOYNXJhsbWACsOexrJo%3D&st=2021-04-07T00%3A29%3A29Z&se=2021-05-08T00%3A34%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 13:56 UTC, opbld31 commented
Docs Build status updates of commit _[e96ae39](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e96ae3958191c396ee361464177069b77909a478)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 14:01 UTC, opbld32 commented
Docs Build status updates of commit _[a1ebbd0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a1ebbd0917a39ce25ccbdeb325336d76d8f39a2e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104071359554897-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qW9sQxa2l%2FImJOBllx2B8AscJPwMYFG0oawp%2BG%2BYF7Q%3D&st=2021-04-07T13%3A56%3A22Z&se=2021-05-08T14%3A01%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 14:08 UTC, opbld33 commented
Docs Build status updates of commit _[3eb455f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3eb455f457c2fe05d63c4d150f92d225e541f38b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104071406491202-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eSVsZ0dwZdOwjgUeZFInwkD1Y7teUginRYpsJhm2Lmo%3D&st=2021-04-07T14%3A03%3A07Z&se=2021-05-08T14%3A08%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 16:29 UTC, opbld30 commented
Docs Build status updates of commit _[eaf015a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eaf015a52c6b41480f2afaa347ef3c8107cf98ab)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104071628058841-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=m2TqgRnF1lVSFmwIh13RGsg9qPPOMMuWQavzfbmNgXw%3D&st=2021-04-07T16%3A24%3A25Z&se=2021-05-08T16%3A29%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 17:43 UTC, chackman requested changes
Please address /me/ segment comment on Example 3.

2021-04-07 17:43 UTC, chackman commented on api-reference/v1.0/api/driveitem-put-content.md
> +PUT /me/drives/{remoteItem-driveid}/items/{remoteItem-id}:/fileC.txt:/content
Please remove the `/me/` segment from the front, since the drive at `remoteItem-driveId` may not be a drive that the user owns.

2021-04-07 19:37 UTC, opbld32 commented
Docs Build status updates of commit _[39252ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/39252adde5013b590899ef5ebaabb5d7f76784a1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 19:37 UTC, isvargasmsft commented on api-reference/v1.0/api/driveitem-put-content.md
> +PUT /me/drives/{remoteItem-driveid}/items/{remoteItem-id}:/fileC.txt:/content
Done, thank you!

2021-04-07 19:40 UTC, chackman approved these changes
Thank you!

2021-04-07 19:51 UTC, opbld30 commented
Docs Build status updates of commit _[592622f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/592622fed9d3c2c392f835665612e7f29b7bb6d1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-07 19:58 UTC, opbld32 commented
Docs Build status updates of commit _[22cca80](https://github.com/microsoftgraph/microsoft-graph-docs/commits/22cca8042be7e06b1e09121dccda51d6b3344e00)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/driveitem-put-content.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-uploadfiletosharedfolder/api-reference/v1.0/api/driveitem-put-content.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/driveitem-put-content?view=graph-rest-1.0&branch=pr-en-us-11997) (>= graph-rest-1.0) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C7%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104071955582347-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JPN48OJ%2F8dImUgeWjSJ26DuVSP489bvDt2kzywBEwHY%3D&st=2021-04-07T19%3A53%3A11Z&se=2021-05-08T19%3A58%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-12 21:42 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +You can also upload a new file to a **Shared with Me** folder. A **Shared with Me** folder is a folder that lives in someone else's drive, but they have granted you with *Can edit* access to it. Depe
Line 19:

- Please change "lives in" to "in". Figures of speech can be a localization challenge.
- Please replace "but" by "and". "But" connotates a negative or contrary behavior, in general, we avoid it when describing API behavior.

2021-04-12 21:47 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +You can also upload a new file to a **Shared with Me** folder. A **Shared with Me** folder is a folder that lives in someone else's drive, but they have granted you with *Can edit* access to it. Depe
Also line 19:
Please rephrase "Depending on the UI it can show up as **Shared with you**, **Shared with me** or **Shared**." as 
"The folder can be displayed under **Shared with you**, **Shared with me** or **Shared** in the UI."
"Show up" is also a figure of speech and for never-alive-things like a folder, that can be a challenge for loc as well.

2021-04-12 21:50 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +You can also upload a new file to a **Shared with Me** folder. A **Shared with Me** folder is a folder that lives in someone else's drive, but they have granted you with *Can edit* access to it. Depe
Please remove the /en-us segment in the http link to the support site.
A link that includes the locale-language segment used to generate a build warning. I am surprised your PR didn't get that. Can you please check with @Lauragra if this requirement has changed?

2021-04-12 21:56 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +
Line 63:
Please display the placeholders with the curly brackets, and enclose them with tick marks `. 
In general, we do want API elements or programmability elements to be displayed differently from normal text, like in line 63. This helps readability. There are conventions to it though, like bolding for Graph API element names, and enclosing in tick marks for programmability elements like OData query parameters like `$select`.

Using the same principles, please display remoteItem and driveItem appropriately, NOT with tick marks.
Please check if they are first references in the topic. Create a link if first reference, bold subsequent reference.

2021-04-12 22:00 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +### Example 2: Updating an existing file
Line 106:
Please use "Update" and not "Updating".
Titles to show how to do a task should use the infinitive without to, not a gerund.
There is a subtle difference between the two. Using a gerund is more appropriate if your content is more about conceptual descriptions for behavior and conditions, etc.

2021-04-12 22:01 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +This example uploads a new file to a **Shared with Me** folder.
Line 154:
Should we qualify what happens if a file by that name already exists? That is, the operation would replace the existing file, is that right.

2021-04-12 23:31 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
>  To upload large files see [Upload large files with an upload session](driveitem-createuploadsession.md).
Line 14:
The summary description of this topic currently says:
"The simple upload API allows you to provide the contents of a new file or update the contents of an existing file in a single API call. This method only supports files up to 4MB in size."

FYI, for consistency with other PUT operations in Graph, technically the TOC title and topic title should say "Create or replace..." rather than "Upload...". But I can relate to the choice of saying "upload" in the TOC title and topic title, to match customers' search phrase in the OneDrive context. So let's try to bridge the two approaches.

@chackman , is it correct to change the description in line 14 to the following:
"Upload by creating a new file in the specified drive (link to drive please), or if the specified file already exists, replace its contents by the provided content. 
This method takes place in a single API call, and supports files up to 4MB in size."

One point to make is, please have the second sentence in a separate paragraph. The summary description should be a single sentence that summarizes the purpose of a method. Everything else should be in a subsequent paragraph(s).

2021-04-12 23:40 UTC, angelgolfer-ms commented on api-reference/v1.0/api/driveitem-put-content.md
> +Content-Type: text/plain
Line 159:
The next comment applies to this example (and other examples in the OneDrive API): I find it would be helpful if the examples would actually show the values of what an ID to a drives segment or items segment in a query URL looks like.
I have recently tried some OneDrive API queries in Graph Explorer and I hoped this level of detail exist in examples.

2021-04-12 23:43 UTC, angelgolfer-ms requested changes
@isvargasmsft , I added a few more comments. Please take a look. I requested a change to the summary description that was pre-existing, and for that I'd hope the product team can review and confirm for my suggestion. Thanks in advance for covering that.

2021-04-13 14:43 UTC, isvargasmsft commented on api-reference/v1.0/api/driveitem-put-content.md
> +You can also upload a new file to a **Shared with Me** folder. A **Shared with Me** folder is a folder that lives in someone else's drive, but they have granted you with *Can edit* access to it. Depe
Done! Thanks!

2021-04-13 23:31 UTC, opbld31 commented
Docs Build status updates of commit _[2e80ea4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2e80ea4324875adb88fd3966bac7b1b0ef55d956)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-dea6abc5)

<a id="dea6abc5"></a>
###
 - **[Error-RuningBuildFailed]** `````Some unexpected errors happened when running build, please open a ticket in https://aka.ms/SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104132330562636-11997%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VvyHieCbr4iMLEU2unxd1CNx1SrxzaWMH6ZiGKxd%2BWY%3D&st=2021-04-13T23%3A26%3A06Z&se=2021-05-14T23%3A31%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-20 15:01 UTC, closed without merging