[Azure AD roles] Unified RBAC API - v1.0
microsoftgraph/microsoft-graph-docs pull request #12045
Opened 2021-03-19 23:59 UTC by rolyon

2021-03-20 00:00 UTC, opbld31 commented
Docs Build status updates of commit _[233de82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/233de828f3ae775a04d19aa3da025cbdc5a79196)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :x:Error | | [Details](#user-content-7ebc69e498e9e2a6366fcb156c6326be-a38d50f7)
[api-reference/v1.0/includes/snippets/objc/create-unifiedroleassignment-from-rbacapplication-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/objc/create-unifiedroleassignment-from-rbacapplication-objc-snippets.md) | :warning:Warning | | [Details](#user-content-b07e4aeac6b1a3419202da3ffe8ea045-a38d50f7)
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :warning:Warning | | [Details](#user-content-8e04cbf9bbff7f8beab455a39466cabc-a38d50f7)
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :warning:Warning | | [Details](#user-content-7a91b7fd817c5d172e75e842e024cb34-a38d50f7)
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :warning:Warning | | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-a38d50f7)

<a id="7ebc69e498e9e2a6366fcb156c6326be-a38d50f7"></a>
### [api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md)
 - **Line 145, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-built-in-role-unifiedroledefinition-csharp-snippets.md'.`````
 - **Line 149, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-built-in-role-unifiedroledefinition-javascript-snippets.md'.`````
 - **Line 153, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-built-in-role-unifiedroledefinition-objc-snippets.md'.`````
 - **Line 157, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-built-in-role-unifiedroledefinition-java-snippets.md'.`````
 - **Line 245, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-inheritsfrom-unifiedroledefinition-csharp-snippets.md'.`````
 - **Line 249, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-inheritsfrom-unifiedroledefinition-javascript-snippets.md'.`````
 - **Line 253, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-inheritsfrom-unifiedroledefinition-objc-snippets.md'.`````
 - **Line 257, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-inheritsfrom-unifiedroledefinition-java-snippets.md'.`````

<a id="b07e4aeac6b1a3419202da3ffe8ea045-a38d50f7"></a>
### [api-reference/v1.0/includes/snippets/objc/create-unifiedroleassignment-from-rbacapplication-objc-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/objc/create-unifiedroleassignment-from-rbacapplication-objc-snippets.md)
 - **Line 5, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-indented?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="8e04cbf9bbff7f8beab455a39466cabc-a38d50f7"></a>
### [api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md)
 - **Line 21, Column 3**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/rbacapplication-list-roleassignments.md'.`````

<a id="7a91b7fd817c5d172e75e842e024cb34-a38d50f7"></a>
### [api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md)
 - **Line 33, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'rbacapplicationmultiple.md'.`````

<a id="261ce6b50cb30e378f4aaccf67e4f4f0-a38d50f7"></a>
### [api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml)
 - **Line 4075, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/rbacapplication-list-roleassignments.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103192359169050-12045%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f%2F5aO6UdakA5%2FjyuOF%2Ba5qu0uTp9L6Wh4VCRWAUO0bI%3D&st=2021-03-19T23%3A55%3A28Z&se=2021-04-20T00%3A00%3A28Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-20 00:51 UTC, abhijeetsinha commented on changelog/Microsoft.DirectoryServices.json
> +        "CreatedDateTime": "2020-03-19T00:00:00Z",
@rolyon  - Fix the year, it should be 2021

2021-03-20 01:00 UTC, opbld34 commented
Docs Build status updates of commit _[2ab45c6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ab45c617b5a4d6a0993871e569f0acf2fd39413)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-7ebc69e498e9e2a6366fcb156c6326be-bb18c1a6)
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/update-unifiedrolede [...]

2021-03-20 01:14 UTC, opbld31 commented
Docs Build status updates of commit _[64df85b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64df85bf91ea5a4d414958e39d6364e86172db6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md) | :white_check_mark: [...]

2021-03-20 01:36 UTC, opbld30 commented
Docs Build status updates of commit _[e413e2b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e413e2bcf40293d033235d5601afdada2de2ff7c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md) | :white_check_mark: [...]

2021-04-05 23:15 UTC, opbld33 commented
Docs Build status updates of commit _[8d63500](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8d63500fd226808eb21a60e54457eb802eac34dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md) | :white_check_mark: [...]

2021-06-11 07:32 UTC, opbld34 commented
Docs Build status updates of commit _[d13ec70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d13ec70e90fba8642dd451a75db39fef6269f7cc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-ab7526f3)
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-7a91b7fd817c5d172e75e842e024cb34-ab7526f3)
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view [...]

2021-06-11 07:49 UTC, opbld33 commented
Docs Build status updates of commit _[900b0bf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/900b0bf6e120eac0291a59cba794fa1d1a42e58f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-261ce6b50cb30e378f4aaccf67e4f4f0-7dea7737)
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/u [...]

2021-08-17 07:43 UTC, opbld32 commented
Docs Build status updates of commit _[63895ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63895ea2c8ccc06304c3f54a84e151dad9cdb828)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md) | :white_check_mark: [...]

2021-08-17 17:25 UTC, opbld31 commented
Docs Build status updates of commit _[9ae4391](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ae43910ffbe0c47a77936495089ecb6e02af9ad)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroleassignment-over-administrativeunit-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/create-unifiedroledefinition-from-rbacapplication-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/delete-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-custom-role-unifiedroledefinition-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-roledefinitions-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/get-unifiedroleassignment-csharp-snippets.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/includes/snippets/csharp/update-unifiedroledefinition-csharp-snippets.md) | :white_check_mark: [...]

2021-08-18 01:25 UTC, Lauragra commented
@FaithOmbongi , please review and approve this PR before we merge. Thanks.

2021-08-18 07:34 UTC, FaithOmbongi commented
@Lauragra I'm on it.

2021-08-18 19:58 UTC, opbld31 commented
Docs Build status updates of commit _[67070d1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67070d1e6716e4733c8143779a65e6ef71c3ea57)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C18%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108181954358315-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=9uwggc7I7LQIdTO1HovBTdcYuQwPiKGyqxDkGa8Zurw%3D&st=2021-08-18T19%3A53%3A53Z&se=2021-09-18T19%3A58%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 13:22 UTC, FaithOmbongi requested changes
- Global: Correct ms.prod value is **directory-management**.
- I [generated stub files against the CSDL for this GA](https://github.com/microsoftgraph/microsoft-graph-docs/tree/2021-08-19-newDocs/doc-stubs/api). For areas where I've highlighted missing sections or wrong files, kindly check out the stub-generated files to confirm the correct info to put in there / correct architecture for the article /correct files to use.
- All properties tables: kindly order the properties alphabetically for easier scanning.

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +### Example 1: Create a role assignment at tenant scope
```suggestion
### Example 1: Create a role assignment with a tenant-wide scope
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +> **Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
```suggestion
> **Note:** The response object shown here might be shortened for readability. 
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +### Example 2 : Create a role assignment over an administrative unit scope
```suggestion
### Example 2 : Create a role assignment with an administrative unit scope
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +The following example assigns a principal User Admin role over an administrative unit.
```suggestion
The following example assigns a principal the User Administrator role over an administrative unit.
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +> **Note:** The response object shown here might be shortened for readability. All the properties will be returned from an actual call.
```suggestion
> **Note:** The response object shown here might be shortened for readability.
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +}
I don't think the comments are allowed in the body
```suggestion
{
    "@odata.type": "#microsoft.graph.unifiedRoleAssignment",
    "roleDefinitionId": "fe930be7-5e62-47db-91af-98c3a49a38b1",
    "principalId": "f8ca5a85-489a-49a0-b555-0a6d81e56f0d",
    "directoryScopeId": "/administrativeUnits/5d107bba-d8e2-4e13-b6ae-884be90e5d1a"
}
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appscope.md
> +The scope of a role assignment determines the set of resources for which the principal has been granted access. An app scope is a scope defined and understood by a specific application. The other typ
```suggestion
The scope of a role assignment determines the set of resources for which the principal has been granted access. An app scope is a scope defined and understood by a specific application, unlike directory scopes which are shared scopes stored in the directory and understood by multiple applications. 
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appscope.md
> +This is employed in both the single principal, single scope entity and multiple principal, multiple scope entities.
```suggestion
This may be in both the following principal and scope scenarios:
+ A single principal and a single scope
+ Multiple principals and multiple scopes.

Inherits from [entity](entity.md).
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +In the request body, supply a JSON representation of [unifiedRoleAssignment](../resources/unifiedroleassignment.md) object. The request must have either a scope defined in Azure AD, such as `director
TO-DO: Must have a table indicating the properties that can be passed in a Create object.
```suggestion
In the request body, supply a JSON representation of [unifiedRoleAssignment](../resources/unifiedroleassignment.md) object. The request must have either a scope defined in Azure Active Directory (Azure AD) specified by **directoryScopeId**, or an application-specific scope specified by the **appScopeId**. Examples of Azure AD scopes are tenant (`/`), administrative units, or applications. For more information on appScope, see [appScope](../resources/appscope.md).

The following table shows the properties that are required when you create the [unifiedRoleAssignment](../resources/unifiedroleassignment.md).
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/resources/appscope.md
> +| displayName | string | Provides the display name of the app-specific resource represented by the app scope. Provided for display purposes since appScopeId is often an immutable, non-human-readable
The description for displayName says that appScopeId is not human readable. Could we have an example in the POST operation to indicate how to configure scoped to an app instead of directory?
```suggestion
| displayName | string | Provides the display name of the app-specific resource represented by the app scope. Provided for display purposes since appScopeId is often an immutable, non-human-readable id. Read-only. |
| id | string | Identifier of an app-specific container or resource representing the scope of the assignment. Usually the immutable id of the resource. The scope of an assignment determines the set of resources for which the principal has been granted access. Required. |
| type | String | Describes the type of app-specific resource represented by the app scope. Provided for display purposes, so a user interface can convey to the user the kind of app specific resource represented by the app scope. Read-only. |
```

2021-08-20 13:22 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +
Let's have another example for scoping to an app. Left a comment in the properties table why it might be important to show this.

2021-08-20 13:22 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +          "Description": "Added the **roleManagement** resource type.",
**Global**: syntax for the description.
Propose that you add to the descriptions a _short_ summarized statement of what the resource does. Will help provide just a little context in the changelog.
```suggestion
          "Description": "Added the [roleManagement](https://docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-v1.0) resource type, methods, and relationships.",
```

2021-08-20 13:22 UTC, FaithOmbongi commented on changelog/Microsoft.DirectoryServices.json
> +        }
3 resources are missing in this changelog.

2021-08-20 17:22 UTC, opbld34 commented
Docs Build status updates of commit _[b5c7cf3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b5c7cf320428270ae12d0dc93ebb963697d77e3d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201719566018-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=y8vsKojXMHR7dCB3CcnAJBLuR96yzhwvdX0I47e%2B%2BIY%3D&st=2021-08-20T17%3A17%3A06Z&se=2021-09-20T17%3A22%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:24 UTC, opbld34 commented
Docs Build status updates of commit _[961b7f9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/961b7f940a644c30153d13e2cb04898b412cecaf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201720591522-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2BEr8lqq2Txi765FT0nv%2BxsFa3FMEAe6b0OczGdaWwlI%3D&st=2021-08-20T17%3A19%3A01Z&se=2021-09-20T17%3A24%3A01Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:25 UTC, opbld34 commented
Docs Build status updates of commit _[be89324](https://github.com/microsoftgraph/microsoft-graph-docs/commits/be893243b538a12ff5022bbdef2a3aac2471e198)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201723234220-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=bQMAztP6x6%2FZem7SMqGmJYgkbd%2FyZW5XK81K363BnAc%3D&st=2021-08-20T17%3A20%3A33Z&se=2021-09-20T17%3A25%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:27 UTC, opbld34 commented
Docs Build status updates of commit _[a196b28](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a196b28f2cd4937e7a70df5e66fa59591b49396d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201722133014-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=XHp4WmycxB94rdw41DAArYrqrdNFHBaCW0BDbgQ8SDo%3D&st=2021-08-20T17%3A22%3A07Z&se=2021-09-20T17%3A27%3A07Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:27 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-list-roledefinitions.md
> +---
@FaithOmbongi - why do you say so? rbacapplication-list can be confused with either 'list roleAssignment' or 'list roleDefinition'.
cc: @rolyon

2021-08-20 17:29 UTC, opbld32 commented
Docs Build status updates of commit _[e177a2e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e177a2ea1113bea1738028365da01ea12f21f405)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201725234596-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=4Wcp6Os%2FOGCkIuQwe8Y0pUguIXQRODYr%2Bh7EQcqT5v4%3D&st=2021-08-20T17%3A24%3A21Z&se=2021-09-20T17%3A29%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:31 UTC, opbld33 commented
Docs Build status updates of commit _[7fdeb37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7fdeb37c58a4b4a110136b4e0d8a4f02e2e83441)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201727572587-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=CWRxfw9xVfNY2US208GNOY3AtX5%2Bs3bFo18Z9jfkzGU%3D&st=2021-08-20T17%3A26%3A16Z&se=2021-09-20T17%3A31%3A16Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:32 UTC, opbld31 commented
Docs Build status updates of commit _[47cf39e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/47cf39ed32183f067d91a42fc7371cd44718c5eb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201726024876-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qxbXFyCiLTMSvZAGzUtcKyJ5YO8uCllSqhUFsH5uE00%3D&st=2021-08-20T17%3A27%3A45Z&se=2021-09-20T17%3A32%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:34 UTC, opbld30 commented
Docs Build status updates of commit _[b9de10a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b9de10ada36c5944fc88057d472cd187850281dd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201731450480-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=vY8ZdUIYcA5m07APFlooSxcAckXkbMMiNma5rLjFbNM%3D&st=2021-08-20T17%3A29%3A32Z&se=2021-09-20T17%3A34%3A32Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:36 UTC, opbld34 commented
Docs Build status updates of commit _[d253803](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d253803510ae4329e9167477ffa26d122b9d6b6e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201732478851-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JCNkq7mzVbDQPLaW%2F146tbmzKDzJirRVCPxM9DHaGo8%3D&st=2021-08-20T17%3A31%3A34Z&se=2021-09-20T17%3A36%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:51 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +
@rolyon  - Copy paste the content from this doc and add it here please - https://docs.microsoft.com/en-us/azure/active-directory/roles/assign-roles-different-scopes#assign-roles-scoped-to-an-app-registration

cc: @FaithOmbongi

2021-08-20 17:52 UTC, opbld31 commented
Docs Build status updates of commit _[b3e206b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b3e206b9276a887c559a98be3e18dab374e08a82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201751217423-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eMGuFkwbyLEW%2FFtKnROhaNr5eA0NW61V9smWBpL9xIM%3D&st=2021-08-20T17%3A47%3A52Z&se=2021-09-20T17%3A52%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:54 UTC, opbld33 commented
Docs Build status updates of commit _[f5baaaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5baaaf5b782d3e88615d0d4c9157b0bd45b8bcb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201753127688-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=uHXMwc%2Ftzdh4zSxpQGX7q5BKx8GM5XKPHWhh0df1xsc%3D&st=2021-08-20T17%3A49%3A38Z&se=2021-09-20T17%3A54%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:54 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
> +{
@FaithOmbongi - inheritsPermissionsFrom is a read-only property as of now. It cannot be set during creation of a role defintiion. It is available only for built-in roles today.
cc: @rolyon

2021-08-20 17:56 UTC, opbld31 commented
Docs Build status updates of commit _[14b0d9c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14b0d9c7afa6ef1ea11acb8450c4ebf7d97e05f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201755107133-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zmg52FN1zSviRSNS7jJDSPVcHjadIp8WExW4BJZ%2FoEg%3D&st=2021-08-20T17%3A51%3A45Z&se=2021-09-20T17%3A56%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:58 UTC, opbld33 commented
Docs Build status updates of commit _[7c930c9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7c930c921dad3c1378cf8e6317cd0e14338621c2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201755580050-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=xJHjgQ8poo23Ni3tdfGXJxuuYBCKvGqZJ61n1VmZUuY%3D&st=2021-08-20T17%3A53%3A37Z&se=2021-09-20T17%3A58%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 17:59 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
> +    "inheritsPermissionsFrom": []
@FaithOmbongi - As mentioned in my previous comment, inheritsPermissionsFrom is a read-only property. It will have a  value only for built-in roles today.
cc: @rolyon

2021-08-20 18:01 UTC, opbld30 commented
Docs Build status updates of commit _[14c9af9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14c9af9faddf69e10774ba5129c161cc4a834184)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201759497375-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2BB283U%2FffzG7KfsUNqIfoBxYLP2eMf4rCWZ%2ByEt7cy8%3D&st=2021-08-20T17%3A56%3A33Z&se=2021-09-20T18%3A01%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:03 UTC, opbld33 commented
Docs Build status updates of commit _[4e353bb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4e353bb99b2708ca57db6edd66dd9ce34ee0ff7e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201800424162-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=zqsfua4WkcfLrA9dsbQnugEd0Y5IiTuI4frwS8pKmsA%3D&st=2021-08-20T17%3A58%3A11Z&se=2021-09-20T18%3A03%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:04 UTC, abhijeetsinha commented on api-reference/v1.0/api/unifiedroledefinition-delete.md
> +Delete a [unifiedRoleDefinition](../resources/unifiedRoleDefinition.md) object.
Good suggestion. @rolyon - Please add this.

2021-08-20 18:05 UTC, opbld30 commented
Docs Build status updates of commit _[ff81218](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ff8121855c0e66bd0203a448590b08500be7c1e1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201801501880-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=%2BcIROMU4Uf5ifpw4CXE4Tf0xC2FMAtFeOpMKtSJ22iM%3D&st=2021-08-20T18%3A00%3A00Z&se=2021-09-20T18%3A05%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:06 UTC, opbld30 commented
Docs Build status updates of commit _[3643819](https://github.com/microsoftgraph/microsoft-graph-docs/commits/364381972351bc8b95cd5d6e4bf5dcc3e1b5e7e5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201803299890-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HjFXHR0EpIRfFbnQ4601yog5GnACwoq0fE2yOyXS0do%3D&st=2021-08-20T18%3A01%3A36Z&se=2021-09-20T18%3A06%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:08 UTC, opbld31 commented
Docs Build status updates of commit _[072da64](https://github.com/microsoftgraph/microsoft-graph-docs/commits/072da643892eed73f36795f38def140e456bfd63)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201806382723-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ECfHGYMrHViaNDSL8nhY967CTj%2Bi8Mgm4SwdAolYvrs%3D&st=2021-08-20T18%3A03%3A10Z&se=2021-09-20T18%3A08%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:08 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-list-roleassignments.md
> +{
Good suggestion. @rolyon - Let's cut the response and add the brevity note.

2021-08-20 18:09 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-list-roleassignments.md
> +
@rolyon - let's cut the response and add this note.

2021-08-20 18:09 UTC, opbld31 commented
Docs Build status updates of commit _[153f537](https://github.com/microsoftgraph/microsoft-graph-docs/commits/153f537b609ba5134526c124fc67afa2ef503bce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201807095304-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=gPzxunWXb3J%2BYQS2kqrZIHkqvrP03nitXOsK15o68Rw%3D&st=2021-08-20T18%3A04%3A47Z&se=2021-09-20T18%3A09%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:11 UTC, abhijeetsinha commented on api-reference/v1.0/toc.yml
> +              href: api/unifiedroleassignment-delete.md
@rolyon - Good suggestion. Let's be consistent in TOC.

2021-08-20 18:12 UTC, abhijeetsinha commented on api-reference/v1.0/toc.yml
> +        - name: Role management
@FaithOmbongi - Commented on file name above. Just rbacapplication-list.md is ambiguous because we have roleDefinition and roleAssignment flavors of it.
cc: @rolyon

2021-08-20 18:17 UTC, opbld34 commented
Docs Build status updates of commit _[253f496](https://github.com/microsoftgraph/microsoft-graph-docs/commits/253f496d8111dd8319c859ffc8afe2e252f354bb)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108201815293219-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7mqdymcqQaP1IiyAnJG3o5d8stLcvrEzZodz2RV6y6Y%3D&st=2021-08-20T18%3A12%3A02Z&se=2021-09-20T18%3A17%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-20 18:20 UTC, abhijeetsinha commented on api-reference/v1.0/resources/rolemanagement.md
> +description: "RBAC role management resource"
@FaithOmbongi - No, the suggested string is not correct. This is Unified RBAC API schema. Many different workloads like Intune, Exchange, CloudPC follow same schema. Azure AD is just one such workload. 
cc: @rolyon

2021-08-20 19:17 UTC, FaithOmbongi requested changes
- Re-reviewed @abhijeetsinha 's comments, accepted/resolved or responded for another look.
- There are still some unresolved review comments.
- Don't forget to update the ms.prod value for all docs to directory-management & the alphabetical ordering of properties.

2021-08-20 19:17 UTC, FaithOmbongi commented on api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
> +    "inheritsPermissionsFrom": []
@abhijeetsinha Got it. Also just tested the example & this property isn't returned in a create operation. So we should remove it from this payload.

2021-08-20 19:17 UTC, FaithOmbongi commented on api-reference/v1.0/resources/rolemanagement.md
> +description: "RBAC role management resource"
Got it. Should it then be _Microsoft 365 role-based ..._  or _Unified role-based ...? I see your description below says Microsoft 365.

2021-08-29 21:04 UTC, opbld31 commented
Docs Build status updates of commit _[d90f054](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d90f0540602b6bbb0dff20f65f4a37348e2dd907)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-8e04cbf9bbff7f8beab455a39466cabc-babb19b0)
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-347958fda6b961dcbf8c31359c658157-babb19b0)
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="8e04cbf9bbff7f8beab455a39466cabc-babb19b0"></a>
### [api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md)
 - **Line 18, Column 1**: **[Warning-[table-syntax-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

<a id="347958fda6b961dcbf8c31359c658157-babb19b0"></a>
### [api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md)
 - **Line 25, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/unifiedroleassignment-update.md'.`````
 - **Line 59, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple  [...]

2021-08-29 21:33 UTC, opbld34 commented
Docs Build status updates of commit _[8f4a268](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8f4a268c761d16dae9d7dd34f933347129fc89ce)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C29%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108292132268348-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=AFl9Swg9HC2z2HTAC5Q9B%2FIM%2FxqpjxL3oQqLPlGGTDc%3D&st=2021-08-29T21%3A28%3A52Z&se=2021-09-29T21%3A33%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 06:36 UTC, opbld33 commented
Docs Build status updates of commit _[7ae9438](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ae9438efe8869e745dd0f93c5b9de9fc9953b4f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108300633574451-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=MtDbFVLsI37C1RSAU9qQO%2F67tMbgC4jyWOkSUL39HKY%3D&st=2021-08-30T06%3A31%3A37Z&se=2021-09-30T06%3A36%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-30 17:20 UTC, rolyon commented on api-reference/v1.0/api/rbacapplication-list-roleassignments.md
> +{
Please review the changes I made

2021-08-30 17:22 UTC, rolyon commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +
Can you provide an example of the response?

2021-08-30 23:23 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-list-roleassignments.md
> +{
looks good

2021-08-30 23:30 UTC, abhijeetsinha commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +
Request - 
POST https://graph.microsoft.com/beta/roleManagement/directory/roleAssignments
{
    "principalId": "6b937a9d-c731-465b-a844-2d5b5368c161",
    "roleDefinitionId": "9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3",
    "directoryScopeId": "/661e1310-bd76-4795-89a7-8f3c8f855bfc"
}


Response -  - 
{
    "@odata.context": "https://graph.microsoft.com/beta/$metadata#roleManagement/directory/roleAssignments/$entity",
    "@odata.id": "https://graph.microsoft.com/v2/926d99e7-117c-4a6a-8031-0cc481e9da26/roleAssignments/kl2Jm9Msx0SdAqasLV6lw516k2sxx1tGqEQtW1NowWEQEx5mdr2VR4mnjzyPhVv8-1",
    "id": "kl2Jm9Msx0SdAqasLV6lw516k2sxx1tGqEQtW1NowWEQEx5mdr2VR4mnjzyPhVv8-1",
    "principalId": "6b937a9d-c731-465b-a844-2d5b5368c161",
    "principalOrganizationId": "926d99e7-117c-4a6a-8031-0cc481e9da26",
    "resourceScope": "/661e1310-bd76-4795-89a7-8f3c8f855bfc",
    "directoryScopeId": "/661e1310-bd76-4795-89a7-8f3c8f855bfc",
    "roleDefinitionId": "9b895d92-2cd3-44c7-9d02-a6ac2d5ea5c3"
}

2021-08-30 23:33 UTC, abhijeetsinha commented on api-reference/v1.0/api/unifiedroledefinition-update.md
> +If successful, this method returns a `200 OK` response code and an updated [unifiedRoleDefinition](../resources/unifiedroledefinition.md) object in the response body.
Confirmed. It is **204 No response**.

2021-08-30 23:34 UTC, abhijeetsinha commented on api-reference/v1.0/api/unifiedroledefinition-update.md
> +HTTP/1.1 204 OK
Yeah, it is mistake. It should **204 No response**.

2021-08-30 23:36 UTC, abhijeetsinha commented on api-reference/v1.0/resources/rbacapplication.md
> +None
Agreed. 
@rolyon - Please add roleDefinitions and roleAssignment here. Look at how beta version is documented - https://docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-beta.

Please note that beta version has a number of other relationships as well. Do not add them.

2021-08-30 23:43 UTC, abhijeetsinha commented on api-reference/v1.0/resources/rbacapplication.md
> +None
@rolyon - Add this -
{
  "roleDefinitions": [{"@odata.type": "microsoft.graph.unifiedRoleDefinition"}],
  "roleAssignments": [{"@odata.type": "microsoft.graph.unifiedRoleDefinition"}],
}

2021-08-30 23:45 UTC, abhijeetsinha commented on api-reference/v1.0/resources/rolemanagement.md
> +description: "RBAC role management resource"
@rolyon 
Yeah, we can reuse the description of the main content here.

2021-08-30 23:48 UTC, abhijeetsinha commented on api-reference/v1.0/resources/rolemanagement.md
> +None.
@rolyon - Add this - 
{
  "directory": {"@odata.type": "microsoft.graph.rbacApplication"},
}

2021-08-30 23:49 UTC, abhijeetsinha commented on api-reference/v1.0/resources/unifiedroleassignment.md
> +A unifiedRoleAssignment is used to grant access to resources. It represents a role definition assigned to a principal (typically a user) at a particular scope.
@FaithOmbongi - the principal can be a group. Assigning role to a group is in GA now. We have just highlighted the happy path case where principal is generally a user.
cc: @rolyon

2021-08-30 23:51 UTC, abhijeetsinha commented on api-reference/v1.0/resources/unifiedroledefinition.md
> +| [Delete unifiedRoleDefinition](../api/unifiedroledefinition-delete.md) | None | Delete a unifiedRoleDefinition object. |
It is - api-reference/v1.0/api/unifiedroledefinition-delete.md

2021-08-30 23:52 UTC, abhijeetsinha commented on api-reference/v1.0/resources/unifiedroledefinition.md
> +## Properties
@rolyon -good suggestion. please look into this.

2021-08-30 23:56 UTC, abhijeetsinha commented on api-reference/v1.0/resources/unifiedrolepermission.md
> +
@FaithOmbongi - Good callout. I think we declared it in our schema while designing but never actually supported this property. Let's take this as an open item. I will follow up on this feedback. Do not block the PR on this.
cc: @rolyon

2021-08-30 23:56 UTC, abhijeetsinha commented on api-reference/v1.0/resources/unifiedrolepermission.md
> +            "condition":  "@Subject.objectId Any_of @Resource.owners"
As mentioned above, we never supported such type of deny assignments, I think. I will have to follow up on this.

2021-08-31 19:32 UTC, rolyon commented on api-reference/v1.0/resources/unifiedroledefinition.md
> +## Properties
Used role definition in the description.
Alphabetized properties in table.

2021-08-31 19:34 UTC, rolyon commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +
Added these changes

2021-08-31 19:35 UTC, rolyon commented on api-reference/v1.0/api/unifiedroledefinition-update.md
> +If successful, this method returns a `200 OK` response code and an updated [unifiedRoleDefinition](../resources/unifiedroledefinition.md) object in the response body.
Changed to 204

2021-08-31 19:35 UTC, rolyon commented on api-reference/v1.0/api/unifiedroledefinition-update.md
> +HTTP/1.1 204 OK
Changed to 204

2021-08-31 19:36 UTC, rolyon commented on api-reference/v1.0/resources/rbacapplication.md
> +None
Added json

2021-08-31 19:37 UTC, rolyon commented on api-reference/v1.0/resources/rolemanagement.md
> +description: "RBAC role management resource"
Changed description to:
"Microsoft 365 role-based access control (RBAC) resource."

2021-08-31 19:49 UTC, opbld31 commented
Docs Build status updates of commit _[67711ce](https://github.com/microsoftgraph/microsoft-graph-docs/commits/67711ced783e4ca2858c11ebe023a479f4bd73da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108311947459760-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=7tBIj2QVbBvnKBhNEPHEcLQjQmaW1FnN6PqRHx9BCMc%3D&st=2021-08-31T19%3A44%3A21Z&se=2021-10-01T19%3A49%3A21Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-08-31 19:56 UTC, opbld33 commented
Docs Build status updates of commit _[0b7705f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0b7705f6837852c497238e586709af36337a6bbc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C8%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202108311954239607-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=VaK4fZAQaVSc3E725wrfbAqbkoLG%2F%2BsIdMMsvgL8tBw%3D&st=2021-08-31T19%3A51%3A23Z&se=2021-10-01T19%3A56%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 08:23 UTC, FaithOmbongi requested changes
- Proposed minor fixes
- Many of your files still have microsoft-identity-platform as the ms.prod value. All should show **directory-management** instead.
- Kindly confirm that unifiedRoleAssignment has no update operation. The API.md says otherwise.

2021-09-02 18:18 UTC, jasonjoh commented
Docs Build status updates of commit _[054b978](https://github.com/microsoftgraph/microsoft-graph-docs/commits/054b9785b93a8cc7922c6dfe5b44b60f28a3e889)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021816197033-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=ZYxX%2FH2obu6obFTt6QcsSrSDI3PiGT9TyoUXLgjk7RE%3D&st=2021-09-02T18%3A12%3A59Z&se=2021-10-03T18%3A17%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 18:44 UTC, jasonjoh commented
Docs Build status updates of commit _[e03d6aa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e03d6aa982fecf7fdc6edef03ddad9626819cb94)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021841458148-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=eCYzpVq3m%2FXRhWSepLIIs%2BS1pjrAcjsXocsId0HuUew%3D&st=2021-09-02T18%3A39%3A27Z&se=2021-10-03T18%3A44%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 18:55 UTC, jasonjoh commented
Docs Build status updates of commit _[e212b1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e212b1b1eb08515ca513e97b93e2057d15f935bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-8e04cbf9bbff7f8beab455a39466cabc-7e190a8e)
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-7a91b7fd817c5d172e75e842e024cb34-7e190a8e)
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="8e04cbf9bbff7f8beab455a39466cabc-7e190a8e"></a>
### [api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md)
 - **Line 41, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="7a91b7fd817c5d172e75e842e024cb34-7e190a8e"></a>
### [api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md)
 - **Line 44, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021853574063-12045%5Cworkflow_report.ht [...]

2021-09-02 18:57 UTC, jasonjoh commented
Docs Build status updates of commit _[e212b1b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e212b1b1eb08515ca513e97b93e2057d15f935bc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-8e04cbf9bbff7f8beab455a39466cabc-a9b12563)
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) | [Details](#user-content-7a91b7fd817c5d172e75e842e024cb34-a9b12563)
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

<a id="8e04cbf9bbff7f8beab455a39466cabc-a9b12563"></a>
### [api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md)
 - **Line 41, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

<a id="7a91b7fd817c5d172e75e842e024cb34-a9b12563"></a>
### [api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md)
 - **Line 44, Column 1**: **[Warning-[code-block-unclosed](https://review.docs.microsoft.com/help/contribute/validation-ref/code-block-unclosed?branch=main)]** `````Unclosed code block. Code blocks must begin and end with triple backticks (```).`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021854079633-12045%5Cworkflow_report.ht [...]

2021-09-02 19:14 UTC, jasonjoh commented
Docs Build status updates of commit _[8763ae1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8763ae1150382150e22bacf8a5e8caaf4212c829)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021912261172-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=hPUNtPFQKt9s5P6iFxwVYVEQLpY0IjnRm8G%2FvSJ4VN0%3D&st=2021-09-02T19%3A09%3A06Z&se=2021-10-03T19%3A14%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 19:25 UTC, jasonjoh commented
Docs Build status updates of commit _[2426492](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2426492dc6ecd43f31a491549e50bf49b798fbf6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109021923485496-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=YDLEVpPqFotFv5ZJpn%2Fu%2Bpbr9803cQgtkFvNrSPa4mE%3D&st=2021-09-02T19%3A20%3A24Z&se=2021-10-03T19%3A25%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 21:11 UTC, jasonjoh commented
Docs Build status updates of commit _[e1ac993](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1ac993d4a1eb557ff3c554e0bf9ea38e34a43f5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109022107548385-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=qUclXoifG6T8df71uHxG%2FKYRhLpvXq%2B4rnXlieKDtSg%3D&st=2021-09-02T21%3A06%3A29Z&se=2021-10-03T21%3A11%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-02 21:14 UTC, rolyon commented on api-reference/v1.0/api/rbacapplication-post-roledefinitions.md
> +
Good suggestion, we'll add in next PR

2021-09-02 21:15 UTC, rolyon commented on api-reference/v1.0/api/unifiedroledefinition-update.md
> +If successful, this method returns a `204 No response` response code and an updated [unifiedRoleDefinition](../resources/unifiedroledefinition.md) object in the response body.
Changed to 204 No Content

2021-09-02 21:15 UTC, rolyon commented on api-reference/v1.0/api/rbacapplication-post-roleassignments.md
> +The following table shows the properties that are required when you create the [unifiedRoleAssignment](../resources/unifiedroleassignment.md).
Not needed, so removed sentence

2021-09-03 11:00 UTC, jasonjoh commented
Docs Build status updates of commit _[8cbba7a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8cbba7a151f7de0a2e43c31c2884d9740aee1e4b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031058522147-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=GA%2FzQqkSfNIsGqOklVAFnjWk7gw%2BruxU00%2F%2B%2BVGRWgM%3D&st=2021-09-03T10%3A55%3A34Z&se=2021-10-04T11%3A00%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 11:13 UTC, jasonjoh commented
Docs Build status updates of commit _[13d08cb](https://github.com/microsoftgraph/microsoft-graph-docs/commits/13d08cba35cbbe442cd2a1a20acb7b09ee0ce701)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031111498483-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8mIvHWr5g8NpKS5fxv3CxbhA23r52DB3%2BkxH%2FWAq7x4%3D&st=2021-09-03T11%3A08%3A24Z&se=2021-10-04T11%3A13%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 11:18 UTC, jasonjoh commented
Docs Build status updates of commit _[2345346](https://github.com/microsoftgraph/microsoft-graph-docs/commits/234534684d45e03e675b54c4e96a6e5a308bcb3e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031117049136-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=JSejr3xT%2BOu89f7jqUUFxVjG8M1Kqiu8a7sjUjlxyY8%3D&st=2021-09-03T11%3A13%3A45Z&se=2021-10-04T11%3A18%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 11:32 UTC, jasonjoh commented
Docs Build status updates of commit _[fb6429e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fb6429e5d5fa06154d39f2da4f2ac6671fef73f9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031130054678-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=HNmt5%2Fv3tqwHcWSTTTnHUSfJ5jAUB4RZt58Qioh8xys%3D&st=2021-09-03T11%3A27%3A05Z&se=2021-10-04T11%3A32%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 11:40 UTC, jasonjoh commented
Docs Build status updates of commit _[ad262ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ad262ae6b374130bd8082e28b113258b11fee1b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031139054801-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=8dRBiztzxgudKIdp48PrGcCQcMg3xzMZ3YztgFCj5dc%3D&st=2021-09-03T11%3A35%3A29Z&se=2021-10-04T11%3A40%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 11:42 UTC, jasonjoh commented
Docs Build status updates of commit _[25bda47](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25bda47f60e63ca7db78040cb73c3ad13d4c8665)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/rbacapplication-list-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-list-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-list-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roleassignments.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roleassignments.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/rbacapplication-post-roledefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/rbacapplication-post-roledefinitions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-post-roledefinitions?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroleassignment-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroleassignment-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroleassignment-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-delete?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-get?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/api/unifiedroledefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/api/unifiedroledefinition-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/unifiedroledefinition-update?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/appscope.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/appscope.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/appscope?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rbacapplication.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rbacapplication.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rbacapplication?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/rolemanagement.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/rolemanagement.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/rolemanagement?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroleassignment.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroleassignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroleassignment?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedroledefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedroledefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedroledefinition?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/resources/unifiedrolepermission.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/resources/unifiedrolepermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/unifiedrolepermission?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/rbacapplication-list-roleassignments?view=graph-rest-1.0&branch=pr-en-us-12045) (>= graph-rest-1.0) |
[changelog/Microsoft.DirectoryServices.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/rolyon-aadroles-unified-rbac-ga/changelog/Microsoft.DirectoryServices.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C9%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202109031140164356-12045%5Cworkflow_report.html?sv=2018-03-28&sr=b&sig=QpdDK9THN1FFhAUjctCGj3%2BmgQ5syAyZNQ%2FFHfMPj9U%3D&st=2021-09-03T11%3A37%3A14Z&se=2021-10-04T11%3A42%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-09-03 11:50 UTC, FaithOmbongi approved these changes

2021-09-03 21:11 UTC, abhijeetsinha approved these changes

2021-09-03 22:29 UTC, merged