Updated online meeting attendance report
microsoftgraph/microsoft-graph-docs pull request #12062
Opened 2021-03-22 21:44 UTC by xiaofengyuem

Update the docs for new endpoint to get online meeting attendance report

2021-03-22 21:45 UTC, opbld34 commented
Docs Build status updates of commit _[5460a28](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/5460a28330cb6394ef8999436836588cbf072946)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :x:Error | | [Details](#user-content-fdaeeb752ac5095e14bb0f77c1d297c7-73b9f00b)

<a id="fdaeeb752ac5095e14bb0f77c1d297c7-73b9f00b"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 466, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/csharp/get-meetingattendancereport-csharp-snippets.md'.`````
 - **Line 470, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/javascript/get-meetingattendancereport-javascript-snippets.md'.`````
 - **Line 474, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/objc/get-meetingattendancereport-objc-snippets.md'.`````
 - **Line 478, Column 1**: **[Error-include-not-found]** `````Invalid include link: '../includes/snippets/java/get-meetingattendancereport-java-snippets.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C22%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103222144161401-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZOu8OiRaMmJ29AV%2BUlia0BnInqNaQ1aHqFl3rVCG8P0%3D&st=2021-03-22T21%3A40%3A21Z&se=2021-04-22T21%3A45%3A21Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +To get the meeting attendance report of a meeting:
```suggestion
To get the attendance report of a meeting:
```

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +### Example 6: Retrieve the meeting attendance report of a meeting
```suggestion
### Example 6: Retrieve the attendance report of a meeting
```

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +[!INCLUDE [sdk-documentation](../includes/snippets/snippets-sdk-documentation-link.md)]
Delete these too

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +The following example shows a request to download a meeting attendance report.
```suggestion
The following example shows a request to get a meeting attendance report.
```

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +- Use the `/meetingAttendanceReport` path to get an attendance report for any meeting, as shown in [example 6](#example-6-retrieve-the-meeting-attendance-report-of-a-meeting).
```suggestion
- Use the `/meetingAttendanceReport` path to get the attendance report for a scheduled meeting, as shown in [example 6](#example-6-retrieve-the-meeting-attendance-report-of-a-meeting).
```

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +>- Attendance report are only available when the meeting has concluded.
```suggestion
>- Attendance report of a scheduled meetings is only available when the meeting has concluded.
```

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
>  >- Attendee reports and recordings are only available when the live event has concluded.
```suggestion
>- Attendee report and recordings of a live event are only available when the live event has concluded.
```
I'd suggest make some updates to this line to some that it would be easier for customers to differentiate **live event attendee report** and **scheduled meeting attendance report**

2021-03-22 23:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +# [HTTP](#tab/http)
You can remove this line

2021-03-23 21:08 UTC, opbld32 commented
Docs Build status updates of commit _[81b9caf](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/81b9caffe4d322397dcbbe743b7bef0bb67e7c2d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) | [Details](#user-content-fdaeeb752ac5095e14bb0f77c1d297c7-361cc1b4)

<a id="fdaeeb752ac5095e14bb0f77c1d297c7-361cc1b4"></a>
### [api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md)
 - **Line 22, Column 109**: **[Warning-bookmark-not-found]** `````Cannot find bookmark '#example-6-retrieve-the-meeting-attendance-report-of-a-meeting' in 'beta/api/onlinemeeting-get.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103232107338758-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xkojHfZTLUtQ6yRpEKIKSO54oLkt59vH6UKBi43483I%3D&st=2021-03-23T21%3A03%3A51Z&se=2021-04-23T21%3A08%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 21:36 UTC, opbld32 commented
Docs Build status updates of commit _[12d8dc5](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/12d8dc511278bdbc33d71b06453dc6b991fc9245)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103232135071789-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=a%2BHKBc2y9INDJxZewOdRcbgI0rc8loyme0iJwnAR3YY%3D&st=2021-03-23T21%3A31%3A26Z&se=2021-04-23T21%3A36%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 21:53 UTC, frankpeng7 commented
I forgot to bring this up - you'll need to add a new doc for the new complex type `meetingAttendanceReport`. Please search and refer to `lobbyBypassSettings` or `broadcastSettings`

2021-03-23 23:50 UTC, opbld32 commented
Docs Build status updates of commit _[d5e690e](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/d5e690e7fd226ba745cbce0e9aff356301c53361)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) | [Details](#user-content-f08d9c0174890a3f4912ba767b4a6310-8109d9ba)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

<a id="f08d9c0174890a3f4912ba767b4a6310-8109d9ba"></a>
### [api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md)
 - **Line 20, Column 1**: **[Suggestion-[table-syntax-invalid](https://review.docs.microsoft.com/help/contribute/validation-ref/table-syntax-invalid?branch=main)]** `````Table syntax is invalid. Ensure your table includes a header and is surrounded by empty lines.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103232348295429-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=045RcVz13fMhEOuKjC8Q4brk7IHwNnOyhfAFYxTpb7U%3D&st=2021-03-23T23%3A45%3A19Z&se=2021-04-23T23%3A50%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-23 23:56 UTC, opbld34 commented
Docs Build status updates of commit _[a949bf8](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/a949bf81cf7c90c573093af9265fd72ab01588bd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C23%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103232354574420-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=leEm0qxMd6ISXJPIfLRkZNlBj0xkIvNvd00qSDF2hqI%3D&st=2021-03-23T23%3A51%3A11Z&se=2021-04-23T23%3A56%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-24 00:17 UTC, opbld32 commented
Docs Build status updates of commit _[ae28865](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/ae28865ad2900d3073048878dd4fedc37573264d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103240016121575-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pf595piNmwhIy3AuaUfseUjFJ8wRimYKOIyBqRpgiQ4%3D&st=2021-03-24T00%3A12%3A26Z&se=2021-04-24T00%3A17%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-24 00:28 UTC, opbld34 commented
Docs Build status updates of commit _[0b46103](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/0b461037042f2b12acf669c2ec3999ad0d6c37a1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103240027391608-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FB6WzjuJQ2UTXxuROc58E5SDzMLzrQTLno2dEgXHZGc%3D&st=2021-03-24T00%3A23%3A55Z&se=2021-04-24T00%3A28%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-24 04:23 UTC, frankpeng7 commented on api-reference/beta/resources/attendanceRecord.md
> +| role | String | Role of the attendee, such as organizer |
If this is not an enum, can you list all the possible values in description?

2021-03-24 04:23 UTC, frankpeng7 commented on api-reference/beta/resources/meetingAttendanceReport.md
> +author: "xiaofengyue"
Same as above

2021-03-24 04:23 UTC, frankpeng7 commented on api-reference/beta/resources/attendanceRecord.md
> +}
```suggestion
{
    "emailAddress": "String",
    "totalAttendanceInSeconds": "Int32",
    "role": "String(value1|value2|value3...)",
    "identity": {"@odata.type": "#microsoft.graph.identity"},
    "attendanceIntervals": [{"@odata.type": "#microsoft.graph.attendanceInterval"}]
}
```

2021-03-24 17:10 UTC, opbld31 commented
Docs Build status updates of commit _[72a589e](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/72a589e4062f8575de4f7a2966a69aed749efa0b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103241709073118-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z62YAqO5tu4N4pWMGAbINr%2FlIOT0OXeZzhQU1VUBf3o%3D&st=2021-03-24T17%3A05%3A22Z&se=2021-04-24T17%3A10%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-24 18:06 UTC, opbld34 commented
Docs Build status updates of commit _[8fc71d6](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/8fc71d6f9b606e1cf699a3248769fb57e24dfb81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103241805116123-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=z4rXySDaojR8V12l3p8QzjljrdX%2FRiCsfdAMLQC1PQY%3D&st=2021-03-24T18%3A01%3A33Z&se=2021-04-24T18%3A06%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 05:23 UTC, jsandoval-msft commented on api-reference/beta/api/onlinemeeting-get.md
>  >- Currently, attendee reports and recordings are available only to live events.
Is this still true, or are we also adding scheduled meetings as noted below? maybe update this to say "Currently recordings are only available for live events."

2021-03-25 05:26 UTC, jsandoval-msft requested changes

2021-03-25 05:26 UTC, jsandoval-msft commented on api-reference/beta/api/onlinemeeting-get.md
> +>- Attendee report and recordings of a live event are only available when the live event has concluded.
we can probably combine this content in other bullets.

2021-03-25 05:26 UTC, jsandoval-msft commented on api-reference/beta/api/onlinemeeting-get.md
> +>- Attendance report of a scheduled meeting is only available when the meeting has concluded.
recommend "Attendance report of a scheduled meeting or live event is only available when the meeting or event has concluded."

2021-03-25 17:08 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
>  >- The download link in the `302 Found` [response](#example-4-retrieve-the-attendee-report-of-a-live-event) expires in **60** seconds.
On behalf of Zheng: Does this apply to both live event attendance report and recordings?

2021-03-25 17:17 UTC, elvinyang-msft commented on api-reference/beta/api/onlinemeeting-get.md
>  >- The download link in the `302 Found` [response](#example-4-retrieve-the-attendee-report-of-a-live-event) expires in **60** seconds.
Let's say:
The download links for the live event attendee report and recordings expire in **60** seconds.

2021-03-25 23:31 UTC, opbld30 commented
Docs Build status updates of commit _[46b4480](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/46b4480d4b96e7279a28b35b4e87b2f37ab414a1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-2bdc1f3a)
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

<a id="2bdc1f3a"></a>
###
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delays. You might have content issues that were not reported. To retry validation, close and re-open your PR, or rebuild your branch via Docs Portal (requires admin permissions). If you need admin help or if you continue to see this message, file an issue via https://SiteHelp.`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103252329512889-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=D3EkOtfgi7xs70tn2A5XMoElm7JPsGUygrD87QuabAk%3D&st=2021-03-25T23%3A26%3A00Z&se=2021-04-25T23%3A31%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 23:48 UTC, xiaofengyuem commented on api-reference/beta/api/onlinemeeting-get.md
>  >- The download link in the `302 Found` [response](#example-4-retrieve-the-attendee-report-of-a-live-event) expires in **60** seconds.
updated.

2021-03-25 23:48 UTC, xiaofengyuem commented on api-reference/beta/api/onlinemeeting-get.md
> +>- Attendance report of a scheduled meeting is only available when the meeting has concluded.
thx @jsandoval-msft , updated.

2021-03-25 23:48 UTC, xiaofengyuem commented on api-reference/beta/api/onlinemeeting-get.md
>  >- Currently, attendee reports and recordings are available only to live events.
updated.

2021-03-26 18:38 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +>- The download links for the live event attendee report and recordings expire in **60** seconds.
@jsandoval-msft can we consider unify the name "attendee report" and "attendance report"?

Just one line above it's saying 
> **attendance report** of a scheduled meeting or **live event** is...

but in this line (#28) it's back to **live event attendee report**

2021-03-26 18:40 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +>- The download links for the live event attendee report and recordings expire in **60** seconds.
@jsandoval-msft can we consider unify the name "attendee report" and "attendance report"?

Just one line above it's saying

> **attendance report** of a scheduled meeting or **live event** is...

but in this line it's back to **live event attendee report**

2021-03-26 23:09 UTC, opbld32 commented
Docs Build status updates of commit _[7719bf4](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/7719bf44b14fed46ce0aa3ac102a84cf4c6fff49)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C26%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103262308062763-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yr2Cbn7zN8MrgC6PL6DylcxrcmuGs7TyAijzH1254PM%3D&st=2021-03-26T23%3A04%3A17Z&se=2021-04-26T23%3A09%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-30 18:22 UTC, zhengni-msft commented on api-reference/beta/resources/onlinemeeting.md
> +|meetingAttendanceReport | [meetingAttendanceReport](meetingAttendanceReport.md) | The attendance report of a scheduled meeting |
Can we add ". Read-only." to be consistent with other read-only properties?

2021-03-30 18:22 UTC, zhengni-msft commented on api-reference/beta/api/onlinemeeting-get.md
> +>- The download links for the live event attendee report and recordings expire in **60** seconds.
Based on the reviewed schema, attendee report should be for live event only, while attendance report is for normal meeting but not for live events. can we update the whole note section as:
- Attendance reports are available for meetings other than Live Events, and only available when the meeting has concluded. 
- Recordings and attendee reports are only available for live events, and only available when the live event has concluded. 
- The download links for the live event attendee report and recordings expire in **60** seconds.
- Only the Live Event organizer can access attendee reports and recordings.

2021-03-31 15:56 UTC, opbld33 commented
Docs Build status updates of commit _[13bc56c](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/13bc56c90650562bc01518a59e636acf42dfb9cf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103311555153432-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uqwXUAakzP9U3cz%2BJBgLFcAPFu39I7U1HPKTLKP%2Bco8%3D&st=2021-03-31T15%3A51%3A27Z&se=2021-05-01T15%3A56%3A27Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-31 17:18 UTC, frankpeng7 commented on api-reference/beta/api/onlinemeeting-get.md
> +To get the attendance report of a meeting:
On second thought, should we add the permission context for this route? Since it supports app token (for now)
```suggestion
To get the attendance report of a meeting with application permission:
```

2021-04-16 19:09 UTC, opbld30 commented
Docs Build status updates of commit _[2011dfa](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/2011dfa9509a2ff5a0e63b56407eae21e35504a3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-00989c6f)

<a id="00989c6f"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161909310581-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2M3wyItXlkaGW94XNZBOy97Ppd0lSOMnI7q96yT5i9g%3D&st=2021-04-16T19%3A04%3A51Z&se=2021-05-17T19%3A09%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 20:04 UTC, opbld30 commented
Docs Build status updates of commit _[f92d172](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/f92d172dee94cf9825d4ca8b8ee5041972a3b656)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-47d0cb76)

<a id="47d0cb76"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104162003526576-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5JgsOujSNTUMfAoJuaz%2FJplWZ6q%2FyqzJ1Pryi9235VI%3D&st=2021-04-16T19%3A59%3A08Z&se=2021-05-17T20%3A04%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 20:11 UTC, opbld31 commented
Docs Build status updates of commit _[5c6915d](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/5c6915dabce3d9aab583bfe3c4fbac771c269d6a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104162010038813-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GhiJXnoXoLbjj1JxC1%2FWDpCkEneM9NJdQPR0RdW2tY0%3D&st=2021-04-16T20%3A06%3A14Z&se=2021-05-17T20%3A11%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 20:13 UTC, frankpeng7 commented
@Lauragra this is ready for Doc reviewer to review. Can you help take a look? Thanks!

2021-04-17 01:13 UTC, opbld31 commented
Docs Build status updates of commit _[e55d2b2](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/e55d2b290ec3c2e782fd06b1c359325b7ad66ff5)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170111537990-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UeqDStlSBEk4%2FCloNROJvkxvcN3Bt1F%2Bx57khc%2F4kj0%3D&st=2021-04-17T01%3A08%3A35Z&se=2021-05-18T01%3A13%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:19 UTC, opbld31 commented
Docs Build status updates of commit _[3c02768](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/3c02768a7b53977acba08d05abf171cbb3459095)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170117484040-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WqNMLqAm1E90GBhg%2F5L87OgRPxSqGwSka2%2FqxKcyGRA%3D&st=2021-04-17T01%3A14%3A11Z&se=2021-05-18T01%3A19%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:20 UTC, opbld33 commented
Docs Build status updates of commit _[f33857f](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/f33857ffd2ffa9c7ef935e5b1e682801f5336959)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170118325678-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=mChxkHHlWbsiHryS%2FVBlHBz6LxW%2BMAqPIa3SBwrrC8I%3D&st=2021-04-17T01%3A15%3A26Z&se=2021-05-18T01%3A20%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:21 UTC, Lauragra approved these changes

2021-04-17 01:22 UTC, opbld30 commented
Docs Build status updates of commit _[298d52a](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/298d52a9991e62f3d6c3989ced4ee91e97b81376)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170118579891-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xKgM5fLdQ6BfUWPAieK2K%2BIvaMfdxXSRBsOS5bzYw58%3D&st=2021-04-17T01%3A17%3A04Z&se=2021-05-18T01%3A22%3A04Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:23 UTC, opbld32 commented
Docs Build status updates of commit _[5d3416c](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/5d3416c827c8bb1b3b5d5d2e5a1f6f0dd2470a65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170121208924-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=sPFvcdkT7DD5GmVsFaD3b%2Bfs9jBECNzz2Z6x54tnj80%3D&st=2021-04-17T01%3A18%3A25Z&se=2021-05-18T01%3A23%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:24 UTC, opbld34 commented
Docs Build status updates of commit _[5d3416c](https://github.com/xiaofengyuem/microsoft-graph-docs/commits/5d3416c827c8bb1b3b5d5d2e5a1f6f0dd2470a65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/onlinemeeting-get.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/api/onlinemeeting-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/onlinemeeting-get?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceInterval.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceInterval.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendanceinterval?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/attendanceRecord.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/attendanceRecord.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/attendancerecord?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/meetingAttendanceReport.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/meetingAttendanceReport.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/meetingattendancereport?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[api-reference/beta/resources/onlinemeeting.md](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/api-reference/beta/resources/onlinemeeting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/onlinemeeting?view=graph-rest-beta&branch=pr-en-us-12062) (graph-rest-beta) |
[changelog/Microsoft.Skype.Calling.json](https://github.com/xiaofengyuem/microsoft-graph-docs/blob/update-onlinemeeting-attendance-report/changelog/Microsoft.Skype.Calling.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104170121107392-12062%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=YMcibjEHtNfjteSXEjsNfp%2BU2dgiXcgZD1n8nOTTJdw%3D&st=2021-04-17T01%3A19%3A48Z&se=2021-05-18T01%3A24%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-17 01:27 UTC, merged