New API for AAD mobility management policies
microsoftgraph/microsoft-graph-docs pull request #12083
Opened 2021-03-24 07:04 UTC by RavennMSFT

Added new API for Mobility (MDM/MAM) policies that are configured for Windows auto-enrollment

2021-03-24 07:05 UTC, opbld34 commented
Docs Build status updates of commit _[8a67079](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8a6707942a529eb078db9e3eb0a0b529a4588fa8)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :x:Error | | [Details](#user-content-0817dce4456c16725d5333633847d38f-e9115048)

<a id="0817dce4456c16725d5333633847d38f-e9115048"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 10304, Column 15**: **[Error-yaml-syntax-error]** `````While scanning a multiline plain scalar, found invalid mapping.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103240704338429-12083%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d2VqXJiz9wWjXffoR647lbWL9a4BKlLlVrQXMQcMZvU%3D&st=2021-03-24T07%3A00%3A47Z&se=2021-04-24T07%3A05%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-24 07:12 UTC, opbld31 commented
Docs Build status updates of commit _[a32923e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a32923e2b11bcd54c5a8415793111c74d8e7a46f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accesspackageassignment-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-66353d1c)
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-list-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-post-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-66353d1c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 10304, Column 17**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'resources/mobilitymanagementpolicy.md'.`````
 - **Line 10307, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobiledevicemanagementpolicies-list.md'.`````
 - **Line 10309, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobiledevicemanagementpolicies-get.md'.`````
 - **Line 10311, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobiledevicemanagementpolicies-update.md'.`````
 - **Line 10314, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobiledevicemanagementpolicies-list-includedgroups.md'.`````
 - **Line 10316, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobiledevicemanagementpolicies-post-includedgroups.md'.`````
 - **Line 10318, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobiledevicemanagementpolicies-delete-includedgroups.md'.`````
 - **Line 10320, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobileappmanagementpolicies-list.md'.`````
 - **Line 10322, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobileappmanagementpolicies-get.md'.`````
 - **Line 10324, Column 19**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobileappmanagementpolicies-update.md'.`````
 - **Line 10327, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobileappmanagementpolicies-list-includedgroups.md'.`````
 - **Line 10329, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobileappmanagementpolicies-post-includedgroups.md'.`````
 - **Line 10331, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/mobileappmanagementpolicies-delete-includedgroups.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullR [...]

2021-03-24 07:22 UTC, opbld30 commented
Docs Build status updates of commit _[479b24c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/479b24cc909ffa574d460ad6da6ed309a77079e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-aaaecfc2)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a3b684c19ea3706f0f24676409bf58ee-aaaecfc2)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-aaaecfc2)
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ec18b4001cf2621d26a520201787d407-aaaecfc2)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-aaaecfc2)
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-515e21657c8c51e8890d54f86969b6c0-aaaecfc2)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-aaaecfc2)
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-f15e217885b84404f6c776ff0049ccf2-aaaecfc2)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-aaaecfc2)
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-bc918cee8ce5f130d990d41e1ba2ac35-aaaecfc2)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-aaaecfc2)
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-8c1d7eeff9a97762d1b0e1072c11358a-aaaecfc2)
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-6319f92283eacc491da5ecd778f43c3e-aaaecfc2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-aaaecfc2)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-aaaecfc2)
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpoli [...]

2021-03-24 16:23 UTC, opbld30 commented
Docs Build status updates of commit _[59df67c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/59df67ca005b8a1f6ebbe21a329ed4fd7e13f27a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-287ebba2)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a3b684c19ea3706f0f24676409bf58ee-287ebba2)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-287ebba2)
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ec18b4001cf2621d26a520201787d407-287ebba2)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-287ebba2)
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-515e21657c8c51e8890d54f86969b6c0-287ebba2)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-287ebba2)
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-f15e217885b84404f6c776ff0049ccf2-287ebba2)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-287ebba2)
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-bc918cee8ce5f130d990d41e1ba2ac35-287ebba2)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-287ebba2)
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-8c1d7eeff9a97762d1b0e1072c11358a-287ebba2)
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-6319f92283eacc491da5ecd778f43c3e-287ebba2)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-287ebba2)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-287ebba2)
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpoli [...]

2021-03-24 23:45 UTC, michaelrm97 requested changes
Needs update

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +Delete groups by posting to the includedGroups collection.
Should not be a post

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +|Delegated (work or school account)|Policy.Read.all, Policy.ReadWrite.all|
Should only be Policy.ReadWrite.All

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +DELETE /policies/mobilityAppManagementPolicies/{id}/includedGroups/{id}/$ref
Should be mobileAppManagementPolicies

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +|Delegated (work or school account)|Policy.Read.all, Policy.ReadWrite.all|
all should be upper case

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +    "id": "b2c4bc08-bc08-b2c4-08bc-c4b208bcc4b2",
Should this be an actual value?

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
> +GET /policies/mobilityAppManagementPolicies/{id}/includedGroups
Should be mobileAppManagementPolicies

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +GET /policies/mobilityAppManagementPolicies
Should be mobileAppManagementPolicies

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +author: "**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**"
Need to fix this

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +POST /policies/mobilityAppManagementPolicies/{id}/includedGroups/$ref
Should be mobileAppManagementPolicies

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +PATCH /policies/mobilityAppManagementPolicies/{appId}
Should be mobileAppManagementPolicies

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
> +Delete groups by posting to the includedGroups collection.
Not a post call

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +author: "**TODO: Provide Github Name. See [topic-level metadata reference](https://msgo.azurewebsites.net/add/document/guidelines/metadata.html#topic-level-metadata)**"
Needs fixing

2021-03-24 23:45 UTC, michaelrm97 commented on api-reference/beta/toc.yml
> +            items:
Should these really be nested? I think these can all be put on the same level

2021-03-24 23:45 UTC, michaelrm97 commented on doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md
> +---
Need to delete all files under doc-stubs

2021-03-24 23:45 UTC, michaelrm97 commented on changelog/Microsoft.MobilityService.json
> +                },
mobileDeviceManagementPolicies and mobileAppManagementPolicies are not resource types. Add an entry for every new method created

2021-03-25 00:19 UTC, opbld32 commented
Docs Build status updates of commit _[c9d9fb9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9d9fb93471646ced7f8e52cc972c7634fb1bc68)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-c4bfbdad)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a3b684c19ea3706f0f24676409bf58ee-c4bfbdad)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-c4bfbdad)
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ec18b4001cf2621d26a520201787d407-c4bfbdad)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-c4bfbdad)
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-515e21657c8c51e8890d54f86969b6c0-c4bfbdad)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-c4bfbdad)
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-f15e217885b84404f6c776ff0049ccf2-c4bfbdad)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-c4bfbdad)
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-bc918cee8ce5f130d990d41e1ba2ac35-c4bfbdad)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-c4bfbdad)
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-8c1d7eeff9a97762d1b0e1072c11358a-c4bfbdad)
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-6319f92283eacc491da5ecd778f43c3e-c4bfbdad)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-c4bfbdad)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-c4bfbdad)
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/doc-stubs/api/mobileappmanagementpolicies-delete-includedgroups.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpoli [...]

2021-03-25 00:26 UTC, RavennMSFT commented on changelog/Microsoft.MobilityService.json
> +                },
No they should be resources based on other changelogs

2021-03-25 00:27 UTC, RavennMSFT commented on api-reference/beta/toc.yml
> +            items:
Easier if they are nested for navigation, since the groups actions are methods that repeat under mdm and mam

2021-03-25 00:30 UTC, opbld32 commented
Docs Build status updates of commit _[e5a0d63](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e5a0d63a836514bc6086cac9f04bdde31c6b3644)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-f237fe29)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a3b684c19ea3706f0f24676409bf58ee-f237fe29)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-f237fe29)
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ec18b4001cf2621d26a520201787d407-f237fe29)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-f237fe29)
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-515e21657c8c51e8890d54f86969b6c0-f237fe29)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-f237fe29)
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-f15e217885b84404f6c776ff0049ccf2-f237fe29)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-f237fe29)
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-bc918cee8ce5f130d990d41e1ba2ac35-f237fe29)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-f237fe29)
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-8c1d7eeff9a97762d1b0e1072c11358a-f237fe29)
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-6319f92283eacc491da5ecd778f43c3e-f237fe29)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-f237fe29)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-f237fe29)
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="ef2351a914893f32148769ca850ac554-f237fe29"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 0, Column 0**: **[Warning-[h1-missing](https://review.docs.microsoft.com/help/contribu [...]

2021-03-25 00:43 UTC, opbld30 commented
Docs Build status updates of commit _[14450f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14450f867a08fcc59c562dfa857691c49f0ad41f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6bd4b40d)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-6bd4b40d)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-6bd4b40d)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-6bd4b40d)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-6bd4b40d)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-6bd4b40d)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6bd4b40d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-6bd4b40d"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?b [...]

2021-03-25 01:22 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +  "@odata.type": "Microsoft.AAD.MobilityService.group"
Should be Microsoft.graph.group

2021-03-25 01:22 UTC, michaelrm97 commented on api-reference/beta/api/mobiledevicemanagementpolicies-update.md
> +**Note:** The response object shown here might be shortened for readability.
Need to add block type comment

2021-03-25 01:23 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +      "@odata.type": "#Microsoft.AAD.MobilityService.mobilityManagementPolicy",
I think this should just be graph

2021-03-25 07:33 UTC, RavennMSFT commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +      "@odata.type": "#Microsoft.AAD.MobilityService.mobilityManagementPolicy",
can you elaborate, is it Microsoft.graph ?

2021-03-25 07:48 UTC, opbld34 commented
Docs Build status updates of commit _[d9691e0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9691e0f93deb5c5dbcec24a4415aab79973537f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8e98295e)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-8e98295e)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-8e98295e)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-8e98295e)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-8e98295e)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-8e98295e)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-8e98295e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-8e98295e"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?b [...]

2021-03-25 07:56 UTC, opbld30 commented
Docs Build status updates of commit _[28ef1ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28ef1eae377ffef567a332516b3549ec1ac3c57b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a4d488b7)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-a4d488b7)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-a4d488b7)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-a4d488b7)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-a4d488b7)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-a4d488b7)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-a4d488b7)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-a4d488b7)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a4d488b7"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-a4d488b7"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-25 18:02 UTC, opbld31 commented
Docs Build status updates of commit _[f5774f8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5774f8dbfedd4ba85fb6d8fb0001cd8fbeb9aa9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3525dc1f)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-3525dc1f)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-3525dc1f)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-3525dc1f)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-3525dc1f)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-3525dc1f)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-3525dc1f)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-3525dc1f)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-3525dc1f"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-3525dc1f"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-25 18:37 UTC, opbld31 commented
Docs Build status updates of commit _[046b2d3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/046b2d378d050247dfb797b17e02b966b46ba27c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-54969c73)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-54969c73)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-54969c73)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-54969c73)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-54969c73)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-54969c73)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-54969c73)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-54969c73)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-54969c73"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-54969c73"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-25 18:53 UTC, opbld30 commented
Docs Build status updates of commit _[820807f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/820807fb604a5ffecf648c6ae1f36338df33ba1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4f314401)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-4f314401)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-4f314401)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-4f314401)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-4f314401)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-4f314401)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-4f314401)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-4f314401)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-4f314401"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-4f314401"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-25 19:05 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
> +GET https://graph.microsoft.com/beta/policies/mobileAppManagementPolicies/{appId}/includedGroups
Make this id to be consistent with other APIs

2021-03-25 19:05 UTC, michaelrm97 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
> +  "@odata.type": "Collection(Microsoft.graph.group)"
Make this lower case

2021-03-25 20:58 UTC, opbld32 commented
Docs Build status updates of commit _[7f1681c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f1681c4bd2512d7e3087a3c9033102a72754cdc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-cb11dde0)
[]() | :warning:Warning | | [Details](#user-content-cb11dde0)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-cb11dde0)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-cb11dde0)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-cb11dde0)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-cb11dde0)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-cb11dde0)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-cb11dde0)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-cb11dde0)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-cb11dde0"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="cb11dde0"></a>
###
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delay [...]

2021-03-25 21:06 UTC, opbld30 commented
Docs Build status updates of commit _[23835b5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/23835b5008ea72aec907017f773c81f900b0265b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-9f59c987)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-9f59c987)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-9f59c987)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-9f59c987)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-9f59c987)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-9f59c987)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-9f59c987)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-9f59c987)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-9f59c987"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-9f59c987"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-26 07:32 UTC, opbld32 commented
Docs Build status updates of commit _[f31f07e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f31f07e8b4e5f4b0040d8c165147235f1ca2c85d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-a2664d5e)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-a2664d5e)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-a2664d5e)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-a2664d5e)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-a2664d5e)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-a2664d5e)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-a2664d5e)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-a2664d5e)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-a2664d5e"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-a2664d5e"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-26 07:40 UTC, opbld30 commented
Docs Build status updates of commit _[ec4e779](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ec4e779dc54aa517a460042acd280051da85c13a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4eb16019)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-4eb16019)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-4eb16019)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-4eb16019)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-4eb16019)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-4eb16019)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-4eb16019)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-4eb16019)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-4eb16019"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-4eb16019"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-26 18:12 UTC, michaelrm97 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +The following table shows the properties that are required when you update the [mobilityManagementPolicy](../resources/mobilitymanagementpolicy.md).
For a patch request, no properties are required. Only a selection of properties need to be specified for a patch request. In addition, only the url and appliesTo properties are writetable, and they are not writeable in the same request.

2021-03-26 19:07 UTC, opbld31 commented
Docs Build status updates of commit _[1d7fddf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1d7fddf47f3bef8bb93b00b40645f8c41ab165e9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-3dd48e71)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-3dd48e71)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-3dd48e71)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-3dd48e71)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-3dd48e71)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-3dd48e71)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-3dd48e71)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-3dd48e71)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-3dd48e71"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-3dd48e71"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-03-26 21:10 UTC, michaelrm97 approved these changes

2021-04-02 02:23 UTC, Lauragra commented
@RavennMSFT , this PR does not appear to have been reviewed by the Identity dev writers. I'm adding the content review label back for now. @davidmu1 or @FaithOmbongi , can you please take a look at this PR before we merge? Thanks.

2021-04-03 01:10 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +If successful, this method returns a `204 No Content` response code and a [group](../resources/group.md) object in the response body.
This is a DELETE operation so it should not return an object in the response body.

2021-04-03 01:10 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +**Note:** The response object shown here might be shortened for readability.
When there's not response body, please remove this note.

2021-04-05 00:34 UTC, RavennMSFT commented
> @RavennMSFT , this PR does not appear to have been reviewed by the Identity dev writers. I'm adding the content review label back for now. @davidmu1 or @FaithOmbongi , can you please take a look at this PR before we merge? Thanks.

@Lauragra Per my email convo with David, this has been reviewed already, that's why I removed the label

2021-04-05 00:40 UTC, opbld30 commented
Docs Build status updates of commit _[2b1b195](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b1b1954a81833fba6ac2279f73a23903748f8ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-4d6c129b)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-4d6c129b)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-4d6c129b)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-4d6c129b)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-4d6c129b)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-4d6c129b)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-4d6c129b)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-4d6c129b)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-4d6c129b"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-4d6c129b"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-05 18:44 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +
Please add the missing HTML comment here to resolve the API Doctor error.

2021-04-05 18:48 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +|Delegated (work or school account)|Policy.ReadWrite.All|
The table should have rows for Delegated (personal Microsoft account) and Application. If they are not supported, add the text 'Not supported.' in the permissions column.

2021-04-05 18:49 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +If successful, this method returns `204 No Content` response code. It does not return anything in the response body.
```suggestion
If successful, this method returns a `204 No Content` response code. It does not return anything in the response body.
```

2021-04-05 18:49 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +DELETE https://graph.microsoft.com/beta/policies/mobileAppManagementPolicies/{id}/includedGroups/{id}/$ref
The example should have real looking id values.

2021-04-05 18:49 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add the missing rows.

2021-04-05 18:51 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
If you leave the sentence as is saying that 'some' of the parameters are supported, you need to list the ones that are. If all are supported, remove 'some of'.

2021-04-05 18:51 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +GET https://graph.microsoft.com/beta/policies/mobileAppManagementPolicies/{id}
Example should show real looking ids.

2021-04-05 18:51 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +    "@odata.type": "#microsoft.graph.mobilityManagementPolicy",
The example should show real looking values.

2021-04-05 18:52 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 18:52 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Correct sentence.

2021-04-05 18:53 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
> +GET https://graph.microsoft.com/beta/policies/mobileAppManagementPolicies/{id}/includedGroups
Real looking ids.

2021-04-05 18:53 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md
> +    {
The example should a real looking result.

2021-04-05 18:53 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 18:55 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +      "id": "String (identifier)",
Change values to real response from a test tenant.

2021-04-05 18:55 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 18:56 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +|:---|:---|:---|
Should this table have values in it?

2021-04-05 18:56 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +POST https://graph.microsoft.com/beta/policies/mobileAppManagementPolicies/{id}/includedGroups/$ref
The example should have real looing id.

2021-04-05 18:56 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +  "@odata.type": "#microsoft.graph.group"
Should be a group response.

2021-04-05 18:57 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 18:58 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +|appliesTo|policyScope|Determines the groups this policy setting applies to. Possible values are: `none`, `all`, `selected` **Important:** `selected` cannot be used when specifying this property. Use
```suggestion
|appliesTo|policyScope|Determines the groups this policy setting applies to. Possible values are: `none`, `all`, `selected` .**Important:** `selected` cannot be used when specifying this property. Use [includedGroups](../api/mobileappmanagementpolicies-post-includedgroups.md) to add specific groups.|
```

2021-04-05 18:59 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +|appliesTo|policyScope|Determines the groups this policy setting applies to. Possible values are: `none`, `all`, `selected` **Important:** `selected` cannot be used when specifying this property. Use
Why are we saying that selected ois a possible value but then say that selected isn't a possible value?

2021-04-05 19:00 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +|complianceUrl|String|Compliance URL of the mobility management application|
Don't forget to add punctuation to your sentences. All of the sentences in this table are missing them.

2021-04-05 19:00 UTC, davidmu1 commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +  "complianceUrl": "String",
Real looking values.

2021-04-05 19:00 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
> +|Delegated (work or school account)|Policy.ReadWrite.All|
Add missing rows.

2021-04-05 19:01 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
> +If successful, this method returns `204 No Content` response code. It does not return anything in the response body.
```suggestion
If successful, this method returns a `204 No Content` response code. It does not return anything in the response body.
```

2021-04-05 19:01 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
> +DELETE https://graph.microsoft.com/beta/policies/mobileDeviceManagementPolicies/{id}/includedGroups/{id}/$ref
Real looking id values.

2021-04-05 19:01 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-get.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 19:01 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-get.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Which ones?

2021-04-05 19:02 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-get.md
> +GET https://graph.microsoft.com/beta/policies/mobileDeviceManagementPolicies/{id}
Real looking id values.

2021-04-05 19:02 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-get.md
> +    "id": "String (identifier)",
Real looking response values.

2021-04-05 19:02 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 19:03 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
> +This method supports some of the OData query parameters to help customize the response. For general information, see [OData query parameters](/graph/query-parameters).
Which ones?

2021-04-05 19:03 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
> +GET https://graph.microsoft.com/beta/policies/mobileDeviceManagementPolicies/{id}/includedGroups
Real looking id.

2021-04-05 19:03 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
> +      "@odata.type": "#microsoft.graph.group"
Real looking response.

2021-04-05 19:03 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 19:04 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-list.md
> +      "id": "String (identifier)",
Real looking values.

2021-04-05 19:05 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 19:05 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +|:---|:---|:---|
Shouldn't be an empty table.

2021-04-05 19:06 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +POST https://graph.microsoft.com/beta/policies/mobileDeviceManagementPolicies/{id}/includedGroups/$ref
Id example.

2021-04-05 19:06 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +   "@odata.id": "https://graph.microsoft.com/beta/groups/{id}"
real looking example.

2021-04-05 19:06 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-update.md
> +|Delegated (work or school account)|Policy.Read.All, Policy.ReadWrite.All|
Add missing rows.

2021-04-05 19:07 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-update.md
> +|appliesTo|policyScope|Determines the groups this policy setting applies to. Possible values are: `none`, `all`, `selected` **Important:** `selected` cannot be used when specifying this property. Use
Add periods.

2021-04-05 19:07 UTC, davidmu1 commented on api-reference/beta/api/mobiledevicemanagementpolicies-update.md
> +PATCH https://graph.microsoft.com/beta/policies/mobileDeviceManagementPolicies/{id}
Real examples.

2021-04-05 19:08 UTC, davidmu1 commented on api-reference/beta/resources/mobilitymanagementpolicy.md
> +description: "A mobility management policy represents an auto-enrollment policy for a mobility management application configured in Azure AD. Mobile device management or Mobile app management) "
```suggestion
description: "A mobility management policy represents an auto-enrollment policy for a mobility management application configured in Azure AD."
```

2021-04-05 19:09 UTC, davidmu1 commented on api-reference/beta/resources/mobilitymanagementpolicy.md
> +|[Get mobileDeviceManagementPolicy](../api/mobiledevicemanagementpolicies-get.md)|[mobilityManagementPolicy](../resources/mobilitymanagementpolicy.md)|Read the properties and relationships of a [mobi
```suggestion
|[Get mobileDeviceManagementPolicy](../api/mobiledevicemanagementpolicies-get.md)|[mobilityManagementPolicy](../resources/mobilitymanagementpolicy.md)|Read the properties and relationships of a [mobilityManagementPolicy](../resources/mobilitymanagementpolicy.md) object for a mobile device management application.|
```

2021-04-05 19:09 UTC, davidmu1 commented on api-reference/beta/resources/mobilitymanagementpolicy.md
> +|complianceUrl|String|Compliance URL of the mobility management application|
Add periods.

2021-04-05 19:11 UTC, davidmu1 commented on api-reference/beta/toc.yml
> +            - name: List included groups
These should not be children of the update page.

2021-04-05 19:12 UTC, davidmu1 commented on api-reference/beta/toc.yml
> +            - name: List included groups
These should not be children of the update page.

2021-04-06 01:37 UTC, RavennMSFT commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +|appliesTo|policyScope|Determines the groups this policy setting applies to. Possible values are: `none`, `all`, `selected` **Important:** `selected` cannot be used when specifying this property. Use
The field can have "Selected" as a value by way of assigning groups, but it cannot be directly assigned via API

2021-04-06 01:37 UTC, opbld33 commented
Docs Build status updates of commit _[f042b60](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f042b6009d6f93a134bf17da1614517e30b8b63f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-ca35f3d3)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-ca35f3d3)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-ca35f3d3)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-ca35f3d3)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-ca35f3d3)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-ca35f3d3)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-ca35f3d3)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-ca35f3d3)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-ca35f3d3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-ca35f3d3"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-06 01:39 UTC, opbld32 commented
Docs Build status updates of commit _[31e8335](https://github.com/microsoftgraph/microsoft-graph-docs/commits/31e8335fc19b4e02febdf7011dede803af6a9601)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-010ac46d)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-010ac46d)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-010ac46d)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-010ac46d)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-010ac46d)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-010ac46d)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-010ac46d)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-010ac46d)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-010ac46d"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-010ac46d"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-06 01:40 UTC, opbld34 commented
Docs Build status updates of commit _[7ce0295](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ce0295b6f6730b610cceceea42b9d4a86da3053)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-84130f98)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-84130f98)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-84130f98)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-84130f98)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-84130f98)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-84130f98)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-84130f98)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-84130f98)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-84130f98"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-84130f98"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-08 06:41 UTC, opbld31 commented
Docs Build status updates of commit _[b56f84c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b56f84c122686620acbd36f22e493e8e080e61b3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-1e6a20e3)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-1e6a20e3)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-1e6a20e3)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-1e6a20e3)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-1e6a20e3)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-1e6a20e3)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-1e6a20e3)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-1e6a20e3)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-1e6a20e3"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-1e6a20e3"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-08 06:46 UTC, opbld33 commented
Docs Build status updates of commit _[e1e76ec](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1e76ec5ac5c0ac757771db7ccb8e61d269ae4b3)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8637a333)
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | | [Details](#user-content-0817dce4456c16725d5333633847d38f-8637a333)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | | [Details](#user-content-ef2351a914893f32148769ca850ac554-8637a333)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-8637a333)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-8637a333)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-8637a333)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-8637a333)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-8637a333)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-8637a333)

<a id="8637a333"></a>
###
 - **[Error-IMDS-connectivity-error]** `````Could not connect to DHS due to IMDS connectivity issue. Please retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report.`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

<a id="0817dce4456c16725d5333633847d38f-8637a333"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-8637a333"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete includedGroup' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-delete-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a04afbe0e4e7358d0f1b4a472e578229-8637a333"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'List includedGroups - Microsoft Graph beta' is duplicated in: 'beta/api/mobileappmanagementpolicies-list-includedgroups.md(2,8), beta/api/mobiledevicemanagementpolicies-list-includedgroups.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'List includedGroups' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-list-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-list-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="d8c00529e97efa522f9e7aa6a40489c3-8637a333"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md)
 - **Line 2, Column 8**: **[Suggestion-[duplicate-titles](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-titles?branch=main)]** `````Title 'Add includedGroups - Microsoft Graph beta' is duplicated in: 'beta/api/mobileappmanagementpolicies-post-includedgroups.md(2,8), beta/api/mobiledevicemanagementpolicies-post-includedgroups.md(2,8)'. Titles must be unique within a docset.`````
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Add includedGroups' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-post-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-post-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="c1755c9ab99bdae176b169d0a20233d4-8637a333"></a>
### [api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete includedGroup' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-delete-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="b46f77d8ad2d2a6149d23943c1dde83e-8637a333"></a>
### [api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/mi [...]

2021-04-08 06:55 UTC, opbld33 commented
Docs Build status updates of commit _[7658a69](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7658a69b5eda38762cdc0b1d3967f35e7f75c7c8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d08cb284)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-d08cb284)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-d08cb284)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-d08cb284)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-d08cb284)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-d08cb284)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-d08cb284)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-d08cb284)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d08cb284"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-d08cb284"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-08 17:12 UTC, opbld30 commented
Docs Build status updates of commit _[c638ec1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c638ec195db931856ac35a75e6a1243f50060caa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c60731ce)

<a id="c60731ce"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104081712233591-12083%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4VT64cf8s6quEL7LOBnSOODx0TOWiQ0B19XhXmeL7Po%3D&st=2021-04-08T17%3A07%3A47Z&se=2021-05-09T17%3A12%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 19:45 UTC, opbld33 commented
Docs Build status updates of commit _[2b262e8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2b262e8c21ebd74d8fb63c96b49a55830ef183be)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-72a8c8e7)

<a id="72a8c8e7"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104081944358942-12083%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5SIkFmKYkrh7FCh8M4i5RYuJds9k%2FAUrpLw6kyklsXk%3D&st=2021-04-08T19%3A40%3A44Z&se=2021-05-09T19%3A45%3A44Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 23:58 UTC, opbld33 commented
Docs Build status updates of commit _[fec7be6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fec7be6c5be093f09736224aa3c45eb8765f4601)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-44ee769a)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-44ee769a)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-44ee769a)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-44ee769a)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-44ee769a)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-44ee769a)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-44ee769a)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-44ee769a)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-44ee769a"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-44ee769a"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-09 00:12 UTC, opbld31 commented
Docs Build status updates of commit _[714238c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/714238c9c4c1fcbf14d243abd851d8d3d0cf0c16)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-6537b5f2)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-6537b5f2)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-6537b5f2)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-6537b5f2)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-6537b5f2)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-6537b5f2)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-6537b5f2)
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-6537b5f2)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-6537b5f2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="ef2351a914893f32148769ca850ac554-6537b5f2"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1** [...]

2021-04-09 00:48 UTC, RavennMSFT commented
@davidmu1 I've made all the changes requested. Pls review

2021-04-14 01:03 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-update.md
> +**Note:** The response object shown here might be shortened for readability.
When there's no response body, please remove this note text.

2021-04-14 01:05 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md
> +
The Request and Response examples are missing the HTML comments - please add them.

2021-04-14 01:06 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +
Add the missing blockType: ignored HTML comment.

2021-04-14 01:06 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +This method supports some of the OData query parameters to help customize the response.For example -
Add a space after the period.

2021-04-14 01:08 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +**Note:** The response object shown here might be shortened for readability.
Global: Remove this note when the response does not include a response body.

2021-04-14 01:09 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md
> +Add groups by posting to the includedGroups collection.
Please update this description to be more clear. Please don't create a gerund from the HTTP verb. The description here might be something like "Add groups to be included in the mobile management policy".

2021-04-14 01:10 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-update.md
> +**Note:** The response object shown here might be shortened for readability.
Remove.

2021-04-14 01:10 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md
> +
The Request and Response examples are missing the HTML comments.

2021-04-14 01:10 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-get.md
> +
Add HTML comment.

2021-04-14 01:11 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-get.md
> +
Add HTML comment.

2021-04-14 01:11 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md
> +Get the groups from the includedGroups navigation property.
Please update the description, i.e. "Get the list of groups that are included in the mobile device management policy."

2021-04-14 01:12 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-list.md
> +This method supports some of the OData query parameters to help customize the response.For example -
Same edits here as mentioned previously.

2021-04-14 01:12 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-list.md
> +
Add HTML comment.

2021-04-14 01:13 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +Add groups by posting to the includedGroups collection.
Update the description.

2021-04-14 01:13 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +**Note:** The response object shown here might be shortened for readability.
Remove.

2021-04-14 01:14 UTC, Lauragra commented on api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md
> +
Add the missing HTML comments to the examples.

2021-04-14 01:16 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List mobile device management policies
Please remove the repetitive occurrence of "mobile device management policies" from the TOC entries for readability/scannability. We strive to keep TOC entries concise. For CRUD operations, you can just have the verbes - List, Create, Get, etc.

2021-04-19 05:30 UTC, RavennMSFT commented on api-reference/beta/toc.yml
> +          - name: List mobile device management policies
@Lauragra there are two type of policies with the same methods - mobile device management policy and mobile app management policy. So I changed it by keeping it for the first method i.e. List for each of them and removing the others

2021-04-19 05:34 UTC, opbld30 commented
Docs Build status updates of commit _[bc4bc7f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bc4bc7f37c29236e231aca3de1d5a6e6985476a8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-59a8ec52)
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-59a8ec52)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-59a8ec52)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-59a8ec52)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-59a8ec52)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-59a8ec52)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-59a8ec52)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="59a8ec52"></a>
###
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delays. You might have content issues that were not reported. To retry validation, close and re-open your PR, or rebuild your branch via Docs Portal (requires admin permissions). If you need admin help or if you continue to see this message, file an issue via https://aka.ms/SiteHelp.`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON  [...]

2021-04-19 06:11 UTC, opbld32 commented
Docs Build status updates of commit _[83b231b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/83b231b600c62ae100900ec8c55c1f04119d8800)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-e4f835f8)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-e4f835f8)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-e4f835f8)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-e4f835f8)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-e4f835f8)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-e4f835f8)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="ef2351a914893f32148769ca850ac554-e4f835f8"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete includedGroup' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-delete-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a04afbe0e4e7358d0f1b4a472e578229-e4f835f8"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/micro [...]

2021-05-04 02:49 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-get.md
> +**Note:** The response object shown here might be shortened for readability.
Global: Please format this as a Note by adding a ">" sign at the beginning of the line. This is a bug in our stub generator that has been fixed.

2021-05-04 03:00 UTC, Lauragra commented on api-reference/beta/toc.yml
> +          - name: List mobile device management policies
@RavennMSFT , are there two different resource types - mobilitymanagementpolicy, and mobileDeviceManagementPolicies? That is what the file names, and your TOC structure here, seem to suggest. Can you point me to the api.md or CSDL file associated with this PR, to help me understand?

2021-05-04 03:02 UTC, Lauragra commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +Get a list of the [mobilityManagementPolicy](../resources/mobilitymanagementpolicy.md) objects and their properties.
This description and that for mobiledevicemanagementpolicies-list appear to be identical. Can you please clarify how these two operations are different? What is each getting a list of?

2021-05-04 05:39 UTC, RavennMSFT commented on api-reference/beta/api/mobileappmanagementpolicies-list.md
> +Get a list of the [mobilityManagementPolicy](../resources/mobilitymanagementpolicy.md) objects and their properties.
@michaelrm97 FYI. Yes, they're identical as they inherent from the same entity, but one is for device mgmt apps and the other is for app mgmt apps (dont manage the whole device, but only an app)

2021-05-04 05:40 UTC, RavennMSFT commented on api-reference/beta/toc.yml
> +          - name: List mobile device management policies
https://microsoftgraph.visualstudio.com/_git/onboarding?path=%2Freviews%2F4382-MSGraph-API-for-MDM-settings%2Fapi.md&version=GBmaster. @michaelrm97 FYI

2021-05-04 05:46 UTC, opbld30 commented
Docs Build status updates of commit _[fbbf124](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fbbf124870d93b61d604f90b7a9dee376aa45fb2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-7c928787)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-7c928787)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-7c928787)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-7c928787)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-7c928787)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-7c928787)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="ef2351a914893f32148769ca850ac554-7c928787"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Suggestion-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete includedGroup' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-delete-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a04afbe0e4e7358d0f1b4a472e578229-7c928787"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/micro [...]

2021-05-10 15:34 UTC, opbld34 commented
Docs Build status updates of commit _[5f48e76](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5f48e76e495d12d711988f8a15e49d3a366a50be)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-15f65cc3)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-15f65cc3)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-15f65cc3)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-15f65cc3)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-15f65cc3)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-15f65cc3)
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-6319f92283eacc491da5ecd778f43c3e-15f65cc3)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="ef2351a914893f32148769ca850ac554-15f65cc3"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete includedGroup' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-delete-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a04afbe0e4e7358d0f1b4a472e578229-15f65cc3"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-list-includedgrou [...]

2021-05-12 18:10 UTC, davidmu1 approved these changes

2021-05-17 20:34 UTC, opbld33 commented
Docs Build status updates of commit _[d9b1849](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9b18491a4550d647a717233c643a4341a134d06)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e836300c)

<a id="e836300c"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C17%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105172034009597-12083%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5K0IsWsFYI1K%2BRk0SxiWAp74AEs7TpKAQBxVr62eJwg%3D&st=2021-05-17T20%3A29%3A17Z&se=2021-06-17T20%3A34%3A17Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-17 20:56 UTC, opbld33 commented
Docs Build status updates of commit _[5baeddf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5baeddfc010d1e309e98368de7a612b88899f078)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-ef2351a914893f32148769ca850ac554-8bd99e73)
[api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-a04afbe0e4e7358d0f1b4a472e578229-8bd99e73)
[api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-d8c00529e97efa522f9e7aa6a40489c3-8bd99e73)
[api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-c1755c9ab99bdae176b169d0a20233d4-8bd99e73)
[api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-b46f77d8ad2d2a6149d23943c1dde83e-8bd99e73)
[api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-post-includedgroups.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-post-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-06f93c552e959fcb4474f6e07879cf63-8bd99e73)
[api-reference/beta/resources/mobilitymanagementpolicy.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/mobilitymanagementpolicy.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/mobilitymanagementpolicy?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) | [Details](#user-content-6319f92283eacc491da5ecd778f43c3e-8bd99e73)
[api-reference/beta/api/mobileappmanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobileappmanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-get?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-list?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/api/mobiledevicemanagementpolicies-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobiledevicemanagementpolicies-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobiledevicemanagementpolicies-update?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/mobileappmanagementpolicies-delete-includedgroups?view=graph-rest-beta&branch=pr-en-us-12083) (graph-rest-beta) |
[changelog/Microsoft.MobilityService.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/changelog/Microsoft.MobilityService.json) | :white_check_mark:Succeeded | |

<a id="ef2351a914893f32148769ca850ac554-8bd99e73"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-16-ravennmsft-mdmpolicyapi/api-reference/beta/api/mobileappmanagementpolicies-delete-includedgroups.md)
 - **Line 10, Column 1**: **[Warning-[duplicate-h1s](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-h1s?branch=main)]** `````H1 'Delete includedGroup' is duplicated with other articles: 'beta/api/mobileappmanagementpolicies-delete-includedgroups.md(10,1), beta/api/mobiledevicemanagementpolicies-delete-includedgroups.md(10,1)'. First level headings must be unique within a docset.`````

<a id="a04afbe0e4e7358d0f1b4a472e578229-8bd99e73"></a>
### [api-reference/beta/api/mobileappmanagementpolicies-list-includedgrou [...]

2021-05-18 01:35 UTC, merged