Add new fields to pstnCallLogRow
microsoftgraph/microsoft-graph-docs pull request #12085
Opened 2021-03-24 10:24 UTC by SanderSade

Adding operator and callDurationSource to callrecords-pstncalllogrow, new pstnCallDurationSource enum to enums

2021-03-24 10:26 UTC, opbld33 commented
Docs Build status updates of commit _[35306e5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/35306e5858388b9b751811af8f2c0e9e3c41a7a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-4553ad81)
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="4b33441e61d32f646b88781171f64ffa-4553ad81"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md)
 - **Line 109, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103241024552325-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IqNfyaNURIgHlwMrS9RmcD5cprxyi%2FQ3r%2BAs1sHQFvQ%3D&st=2021-03-24T10%3A21%3A12Z&se=2021-04-24T10%3A26%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-24 16:04 UTC, stephenjust requested changes

2021-03-24 16:04 UTC, stephenjust commented on api-reference/beta/api/callrecords-callrecord-getpstncalls.md
> +			"operator": "Microsoft",
nit: indentation

2021-03-24 16:04 UTC, stephenjust commented on api-reference/beta/resources/enums.md
> +### pstnCallDurationSource values
This should go in https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/resources/enums-callrecords.md

2021-03-24 16:13 UTC, SanderSade commented on api-reference/beta/api/callrecords-callrecord-getpstncalls.md
> +			"operator": "Microsoft",
Fixed, invisible tabs from JSON copy/paste

2021-03-24 16:13 UTC, SanderSade commented on api-reference/beta/resources/enums.md
> +### pstnCallDurationSource values
Moved to enum-callrecords

2021-03-24 16:14 UTC, opbld33 commented
Docs Build status updates of commit _[321103f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/321103f5826574802a522d00fb9239030a7dc17d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-e7d1a584)
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="4b33441e61d32f646b88781171f64ffa-e7d1a584"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md)
 - **Line 109, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C24%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103241612547882-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IZYD671BDdk4KeeBDqxpC2LhpW1XMtnukQlQCTvHOMM%3D&st=2021-03-24T16%3A09%3A10Z&se=2021-04-24T16%3A14%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-25 16:14 UTC, williamlooney approved these changes

2021-03-31 02:59 UTC, angelgolfer-ms commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
Line 43:
Please end the description with a period.

2021-03-31 03:08 UTC, angelgolfer-ms commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
Line 44:
Please rephrase the first sentence as "The source of the call duration data."
The reason is three or more nouns in a row can become ambiguous and a challenge for localizers.

In general, we avoid passive voice as much as possible. Here, "will be specified" begs the question "by whom".

I suggest rephrasing the other sentences to use active voice:  "If the call uses a third-party telecommunications operator via the Operator Connect Program, the operator may provide their own call duration data. In this case, the property value is `operator`. Otherwise, the value is `microsoft`."

2021-03-31 03:11 UTC, angelgolfer-ms commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Added the [**pstnCallDurationSource**](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta#pstncalldurationsource-values) enumeration t
Line 22:
FYI in general, if we provide a link to a term (here the term is "pstnCallDurationSource"), then we don't have to bold that term. The link would be displayed the way the publishing site displays links. :-)

2021-03-31 03:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
@SanderSade , thanks for adding the properties. The next comment applies to not only what this PR added, but in general to all resource type topics, including this one.
Can you please reorder the table rows in the Properties section of this topic by alphabetical order?
Reasons:
- Customers would have to scan each row in order to find the property they need. 
- This is not a new guideline. It's one that the generators have always used. Apparently over time, authors and content reviewers haven't actively enforced this guidance in this topic.  Imagine your topic growing to a third of the group resource topic without following this :-)

2021-03-31 03:26 UTC, angelgolfer-ms requested changes
Thanks for the PR, @SanderSade ! That's a technically solid PR! My comments are for readability and editorial, please take a look.

2021-04-01 06:41 UTC, opbld34 commented
Docs Build status updates of commit _[566d566](https://github.com/microsoftgraph/microsoft-graph-docs/commits/566d566db832891c0ddbd7da54eae15c2783ada8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-07840849)
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="4b33441e61d32f646b88781171f64ffa-07840849"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104010639596857-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ELA0Ru%2FTIYEMZOs9zCxP5Q1UFQinsSqIvqFxFUadRYM%3D&st=2021-04-01T06%3A36%3A31Z&se=2021-05-02T06%3A41%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 06:48 UTC, SanderSade commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
Both recommendations applied

2021-04-01 06:48 UTC, SanderSade commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
Added

2021-04-01 06:49 UTC, opbld33 commented
Docs Build status updates of commit _[d5f8b93](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d5f8b939441facc20231937e96ef04135e6e9f84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-bd74ead9)
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="4b33441e61d32f646b88781171f64ffa-bd74ead9"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104010647556375-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C1sfiPNWfBczzMJn4a3YV6pab9nZksItznPJhdriKf0%3D&st=2021-04-01T06%3A44%3A06Z&se=2021-05-02T06%3A49%3A06Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 06:58 UTC, SanderSade commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
Thank you, @angelgolfer-ms!
 
I've sorted the table, but left the id on top - as an unique key, I think it should be always first, so the customer wouldn't have to look for the key when onboarding or reviewing. This is also a pretty much universal behavior for describing SQL tables or any other tabular data - if that is not OK, please let me know.

Also, should the response JSON be sorted to match the table?

2021-04-01 07:01 UTC, SanderSade commented on changelog/Microsoft.IC3.DataPlatform.json
> +                    "Description": "Added the [**pstnCallDurationSource**](https://docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta#pstncalldurationsource-values) enumeration t
Un-bolded the term

2021-04-01 07:02 UTC, opbld30 commented
Docs Build status updates of commit _[26c339c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/26c339ca943b77e6a8cab49718912bba6beca067)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) | [Details](#user-content-4b33441e61d32f646b88781171f64ffa-287fb43f)
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

<a id="4b33441e61d32f646b88781171f64ffa-287fb43f"></a>
### [api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md)
 - **Line 116, Column 2**: **[Suggestion-[column-header-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C1%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104010701055292-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ROXpkIeKv%2FVqDlVa8I%2BXL8N2KF%2FsLSDbV%2FbW3vvxr10%3D&st=2021-04-01T06%3A57%3A23Z&se=2021-05-02T07%3A02%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 04:21 UTC, angelgolfer-ms commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
Thanks for reordering the Properties table rows, @SanderSade .
For consistency with other resource topics and the future output of the topic generation tool, please place the row for id also in alphabetical order. 

Regarding the "response JSON" - I suppose you're referring to an example response payload? Not the "JSON representation" section, right? 
Well, for the former, I think it's ok to leave the ordering of properties in a response payload in whatever order that a customer would get, say in Graph Explorer. 
For the latter, alphabetical order is desired but not required, because the JSON representation section is technically for API Doctor, customers don't derive a whole lot of value from that section. On the other hand, desired because it would be easier for internal authors like yourself to browse and make sure you guys haven't left out any published properties in that section :-)

2021-04-02 04:44 UTC, opbld34 commented
Docs Build status updates of commit _[deec1a2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/deec1a2eab09bc50725d1bf1bebd2400662336fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104020443181501-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3BqvVFD%2BgPisvZ6aziX%2FT%2Fajt7SORLVAHKkP5qZxjEY%3D&st=2021-04-02T04%3A39%3A35Z&se=2021-05-03T04%3A44%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 04:45 UTC, opbld33 commented
Docs Build status updates of commit _[a0f21c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a0f21c0f1a739abffab6089b5795b0a8c3bcd822)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C2%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104020443396509-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=upPpc4vzWkk5pmC%2FPhR8K8Gbq6telq%2FckYOq8x9vQDQ%3D&st=2021-04-02T04%3A40%3A56Z&se=2021-05-03T04%3A45%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-02 05:42 UTC, angelgolfer-ms approved these changes
Thanks, @SanderSade , for incorporating the feedback. I replied to your questions, please take a look. 
I also fixed an issue in the enums.md file that probably was inherited from somebody else's earlier update that generated a build "suggestion". Typically, build suggestions will evolve into build warnings later on, so we proactively fix them.
Since there is only one remaining non-critical issue about ordering the id property (per your question/comment), for efficiency, I am approving this PR to reduce the back-and-forth.
After you incorporate the remaining issue with ordering the id property, please follow this [protocol](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103181/Content-workflow) to get the topic published.

2021-04-05 10:05 UTC, SanderSade commented on api-reference/beta/resources/callrecords-pstncalllogrow.md
> +|callDurationSource|pstnCallDurationSource|The call duration source. When a third-party telecommunications operator is used via the Operator Connect Program, they may provide their own call duration
I moved the id row... but really, this is something that most technical users would prefer as the first row, and possibly bolded or with the different background color.

2021-04-05 10:07 UTC, opbld30 commented
Docs Build status updates of commit _[c05840e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c05840e3a464d1d38b38d04f54bbb156183eb17b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051004245761-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=v4sZNafl1RddjEKszO%2FFKHxo%2B5wiz%2BG89zFy%2BEau35E%3D&st=2021-04-05T10%3A01%3A59Z&se=2021-05-06T10%3A06%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-08 16:38 UTC, opbld34 commented
Docs Build status updates of commit _[bf25bf6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bf25bf68d1faf958ead5cade06d212fb99a3e7f3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C8%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104081635411433-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JIF6O%2F4Jjzt3e6gA7hTyUPSfz7K71RjvBG6XJldwSbI%3D&st=2021-04-08T16%3A33%3A03Z&se=2021-05-09T16%3A38%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 01:49 UTC, opbld31 commented
Docs Build status updates of commit _[24e6184](https://github.com/microsoftgraph/microsoft-graph-docs/commits/24e618493ee2f90b41e6f57c7de377e7e1f1375b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/callrecords-callrecord-getpstncalls.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/api/callrecords-callrecord-getpstncalls.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/callrecords-callrecord-getpstncalls?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/callrecords-pstncalllogrow.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/callrecords-pstncalllogrow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/callrecords-pstncalllogrow?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums-callrecords.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums-callrecords.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums-callrecords?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[api-reference/beta/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/api-reference/beta/resources/enums.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/enums?view=graph-rest-beta&branch=pr-en-us-12085) (graph-rest-beta) |
[changelog/Microsoft.IC3.DataPlatform.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-23-sasde-new-fields-to-pstncall-log/changelog/Microsoft.IC3.DataPlatform.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C10%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104100147425512-12085%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=u%2BrSBf40ruZm6LCwusXJJ6ujQr7jpRQFeKt5d7UaW%2Fk%3D&st=2021-04-10T01%3A44%3A00Z&se=2021-05-11T01%3A49%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-10 01:55 UTC, merged