Access Review History Defintions
microsoftgraph/microsoft-graph-docs pull request #12107
Opened 2021-03-25 19:10 UTC by leherpel

Access Review History Definitions are used when requesting Azure AD review history data. The definitions contain scopes and filters for choosing which data to select. Only POST is supported in the API for creating definitions and generating secure download links. These definitions and selected data are automatically cleaned up after 29 days.

2021-03-25 19:13 UTC, opbld30 commented
Docs Build status updates of commit _[1bd5a2f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/1bd5a2f10426c6ab9c4a599d82e96a27c300f8f0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-81126875)
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-list-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-list-historydefinitions.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-post-historydefinitions.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-post-historydefinitions.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewset-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewset-update.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

<a id="81126875"></a>
###
 - **Line 0, Column 0**: **[Warning-validation-incomplete]** `````Failed to get the validation ruleset and validation was not completed. This happens when there's an issue with the service and continuing to retry the call could cause build delays. You might have content issues that were not reported. To retry validation, close and re-open your PR, or rebuild your branch via Docs Portal (requires admin permissions). If you need admin help or if you continue to see this message, file an issue via https://SiteHelp.`````
 - **Line 0, Column 0**: **[Warning-[redirected-file-not-removed](https://review.docs.microsoft.com/help/contribute/validation-ref/redirected-file-not-removed?branch=main)]** `````Redirected file 'changelog.md [redirection]' is still in the repo. After adding a file to the redirection JSON file, you must delete the original file from the repo.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C25%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103251910471959-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DD1p1Wb4fdep9PV0JIvMpyxDYHI92B7zMOnZO%2BSU5aw%3D&st=2021-03-25T19%3A08%3A10Z&se=2021-04-25T19%3A13%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-29 23:49 UTC, Lauragra commented
@leherpel , please reach out to me internally regarding this PR. Thanks.

2021-04-13 21:22 UTC, opbld30 commented
Docs Build status updates of commit _[029d5d8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/029d5d83b7060cde924cd2c231fa1a7ba0c99672)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C13%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104132121374869-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NmH4v0fk8vc%2BQ0Q8%2BI284rTZw9ZDRMN2HQAPFsVf%2Fus%3D&st=2021-04-13T21%3A17%3A54Z&se=2021-05-14T21%3A22%3A54Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 00:35 UTC, opbld34 commented
Docs Build status updates of commit _[4f41d84](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f41d84b07f37eded4adedac0132a84e85a6b543)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-delete.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140034099685-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LDK%2FWmC%2F2jHlyOsP5KNAJEKGFApUJ9rkDrn1Dw5T9ro%3D&st=2021-04-14T00%3A30%3A37Z&se=2021-05-15T00%3A35%3A37Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 00:38 UTC, opbld30 commented
Docs Build status updates of commit _[dca8abd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/dca8abd9baae12c3657022011d94ea5799fe955e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140037165819-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=X271dGK3hf0Mq6Y%2BvN7Co2IA4dzzHQsqpB6s3Daam90%3D&st=2021-04-14T00%3A33%3A36Z&se=2021-05-15T00%3A38%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 00:57 UTC, opbld32 commented
Docs Build status updates of commit _[2ed32ad](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2ed32ad6c098367af6a2a1f1ed8dcabebfc86e65)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104140056091605-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NDhjokWBM%2BkBGFrnhp%2FG86C4yi1nYlA0JtTiOMSY%2Bn8%3D&st=2021-04-14T00%3A52%3A22Z&se=2021-05-15T00%3A57%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 16:52 UTC, opbld32 commented
Docs Build status updates of commit _[6f66a23](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f66a2387c2b9b71379e53139def03382b433738)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141649494467-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=adkxTxoBhzQqqjCrcZrBo0iUSVI%2BAzfHIr4%2F8HkND7s%3D&st=2021-04-14T16%3A47%3A12Z&se=2021-05-15T16%3A52%3A12Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 16:53 UTC, opbld32 commented
Docs Build status updates of commit _[9cd10ae](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9cd10aecdaca85458324ed90379e882a56a0e222)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141650361744-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=kPXYGGgM9K5GPrpXUUAqPSEUOyU8ld8bt7PhH6Axa18%3D&st=2021-04-14T16%3A48%3A38Z&se=2021-05-15T16%3A53%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:02 UTC, opbld31 commented
Docs Build status updates of commit _[a79a41d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a79a41d9b29ddb3dd4b7ac6b15bfe039e98b5b04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141701260928-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=IPesFp7ogQFUCmo%2F%2Bz1EEaaLuZAUCjdfEHi%2BRedxPPo%3D&st=2021-04-14T16%3A57%3A47Z&se=2021-05-15T17%3A02%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:09 UTC, opbld32 commented
Docs Build status updates of commit _[d10d722](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d10d7223148d66b3519a0d1580e84f07df5e085e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141708134132-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VCi0LrQEfhjqCSMACSL7GATt2rVgNNOqCGm0KqW8PBU%3D&st=2021-04-14T17%3A04%3A38Z&se=2021-05-15T17%3A09%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:19 UTC, opbld34 commented
Docs Build status updates of commit _[61ddcb4](https://github.com/microsoftgraph/microsoft-graph-docs/commits/61ddcb4811941f0bfeb095064675b9a8d34093da)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141717567416-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7PGKu9GCBYY4cHIO7IhFXXv4HYFGAfIqhcijgWqYuZE%3D&st=2021-04-14T17%3A14%3A23Z&se=2021-05-15T17%3A19%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:23 UTC, opbld30 commented
Docs Build status updates of commit _[6060009](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6060009ec10f8a37cacfb1411c472aeed93e4a83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141722226352-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3wp5%2Bvqf%2BX061sIQDk7%2B2ebAOHVqZg4zqlsvUUoKVZE%3D&st=2021-04-14T17%3A18%3A45Z&se=2021-05-15T17%3A23%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:26 UTC, opbld33 commented
Docs Build status updates of commit _[e94249b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e94249bc76e11487c1028daf2b3d700fccd1a6d8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141724516498-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ZJpo%2BKJ9rciFE3K3StofzPxX4TOCEEJXvLmK9no3CGQ%3D&st=2021-04-14T17%3A21%3A24Z&se=2021-05-15T17%3A26%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:39 UTC, opbld34 commented
Docs Build status updates of commit _[511f12b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/511f12b6c70ff6bcbfb972c3b16f4f2ae80750ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewset.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewset.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141737338178-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K1FVSlGPjh6Jt9zXt9SdNaHZVdLYirTjdfFoEC61YDs%3D&st=2021-04-14T17%3A34%3A56Z&se=2021-05-15T17%3A39%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:41 UTC, opbld31 commented
Docs Build status updates of commit _[5e8fcdd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5e8fcdda6d9feb08612a727316ecfc5f1b6e1d3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141738471771-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dLeuyxkt8hnEpD81pFWNsg5b%2BnA%2BLFpr8GnDEfSV1Zg%3D&st=2021-04-14T17%3A36%3A29Z&se=2021-05-15T17%3A41%3A29Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-14 17:44 UTC, opbld34 commented
Docs Build status updates of commit _[5719c6e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/5719c6e05ddf1e5ee88e3a6b7544ebcdefac94cc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C14%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104141740020781-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3lk5OPEkzd2OiJaHkjTeO%2F1ygFCX9MAhj%2B0YMCvcOcY%3D&st=2021-04-14T17%3A39%3A13Z&se=2021-05-15T17%3A44%3A13Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-15 20:55 UTC, isabelleatmsft requested changes
Great job! Added some small comments. Also, one file missing: update the TOC (beta/toc.yml)

2021-04-15 20:55 UTC, isabelleatmsft commented on doc-stubs/resources/accessreviewhistorydefinition.md
> +| Include every `accessReviewScheduleDefinition` review result on individual groups (excludes definitions scoped to all Microsoft 365 groups with guest users) | /identityGovernance/accessReviews/defi
remind me - does the review history feature always exclude all groups reviews? is there any way to include those?

2021-04-15 20:55 UTC, isabelleatmsft commented on doc-stubs/resources/enums.md
> +title: "Enum values"
delete this file! its not ours :)

2021-04-16 18:53 UTC, opbld34 commented
Docs Build status updates of commit _[7f32f37](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7f32f37bc5474a2d744326f59a25a26b4cbd2809)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161851169539-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=x3jl1oC9XB5eoF6JrOuM0tKVP8KU2BJqCJQVGmKyykw%3D&st=2021-04-16T18%3A47%3A59Z&se=2021-05-17T18%3A52%3A59Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 18:54 UTC, opbld33 commented
Docs Build status updates of commit _[28c0803](https://github.com/microsoftgraph/microsoft-graph-docs/commits/28c08039914f8c1d9cb4387b1f4637fb553b8401)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161852218017-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=RUvMTJ2%2FaL%2FUd8xkmrVDcXwUcQu5ByILKwVqj30ltFA%3D&st=2021-04-16T18%3A49%3A15Z&se=2021-05-17T18%3A54%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 18:55 UTC, opbld31 commented
Docs Build status updates of commit _[7741686](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7741686a3d5fb3f4f65eb4a882438107a762c7a2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/enums.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/enums.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161853118651-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=3igogZOyy7%2BTyRh9NE6V0g43VA%2FSb1FgFAM31HXkS3I%3D&st=2021-04-16T18%3A50%3A56Z&se=2021-05-17T18%3A55%3A56Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 19:17 UTC, leherpel commented on doc-stubs/resources/accessreviewhistorydefinition.md
> +| Include every `accessReviewScheduleDefinition` review result on individual groups (excludes definitions scoped to all Microsoft 365 groups with guest users) | /identityGovernance/accessReviews/defi
Discussed offline we will update the doc for all groups when its done in 1-2 weeks.

2021-04-16 19:19 UTC, opbld32 commented
Docs Build status updates of commit _[865464b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/865464b629eda37e2533602e86a31a2b39460117)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog-stubs/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | |
[doc-stubs/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | |
[doc-stubs/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/doc-stubs/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161918036307-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2T6W%2FiX%2BUrzleyW9Jj6SwuKk8EjkWDi7zMXXGZhsnEI%3D&st=2021-04-16T19%3A14%3A41Z&se=2021-05-17T19%3A19%3A41Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 19:38 UTC, opbld33 commented
Docs Build status updates of commit _[055ef92](https://github.com/microsoftgraph/microsoft-graph-docs/commits/055ef923631da87ccd581bfa69994d3c295a35dc)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-ee865b5d)

<a id="ee865b5d"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161937425897-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Fu%2F%2BqeQTkUXj348ExnAvNUqwBRiuRf1GueqDX2nqrWg%3D&st=2021-04-16T19%3A32%3A59Z&se=2021-05-17T19%3A37%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-16 19:45 UTC, opbld31 commented
Docs Build status updates of commit _[536a523](https://github.com/microsoftgraph/microsoft-graph-docs/commits/536a52398a2fbffad98716c1d1869b7c5b19603e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5159684801f68d50e9a725ac1a34cc81-c9620052)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-c9620052)
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5159684801f68d50e9a725ac1a34cc81-c9620052"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md)
 - **Line 59, Column 16**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/accessReviewHistoryDecisionFilter.md'.`````

<a id="5b21614878c88dec0f9405349e0c21ff-c9620052"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C16%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104161943282782-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DaijQG%2F%2FWfZA1Aarg9V7OeSPmEp0r6PJpcJ8inidOKM%3D&st=2021-04-16T19%3A40%3A02Z&se=2021-05-17T19%3A45%3A02Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 07:22 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewhistorydefinition-create.md
> +author: "leherpel"
Global: Please ensure the author is in the [Microsoft Graph contacts list](https://microsoft.sharepoint.com/sites/Graph/Lists/Microsoft%20Graph%20Contacts/AllItems.aspx?CT=1606755556215&OR=OWA%2DNT&CID=798496d0%2D7bc3%2Df8db%2D49ee%2D45ab03388a04). This is the person responsible for all workload PRs and GitHub issues.

2021-04-20 08:04 UTC, FaithOmbongi requested changes

2021-04-20 08:04 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewhistorydefinition.md
> +
Move this to the CREATE API page.

2021-04-20 18:25 UTC, opbld30 commented
Docs Build status updates of commit _[14b9891](https://github.com/microsoftgraph/microsoft-graph-docs/commits/14b9891a23cf7ca2ac397a1050920fda031ff99f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-cda0e8f0)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-cda0e8f0"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201823506053-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BpeZzAYxx9oQnUU2uP8%2FEB0gHyZDEXCdzKJH%2BD3IeBs%3D&st=2021-04-20T18%3A20%3A05Z&se=2021-05-21T18%3A25%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:35 UTC, opbld30 commented
Docs Build status updates of commit _[203faaf](https://github.com/microsoftgraph/microsoft-graph-docs/commits/203faaf844b8f6a8becdd45238ceb38b607bb060)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-cbbe0aca)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-cbbe0aca"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201834232886-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ibsZ0aX9TYUXXHTSh9WezaCtqUpnH6qUmw5O6xw595k%3D&st=2021-04-20T18%3A30%3A36Z&se=2021-05-21T18%3A35%3A36Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:36 UTC, opbld33 commented
Docs Build status updates of commit _[32c8587](https://github.com/microsoftgraph/microsoft-graph-docs/commits/32c8587014906bffb7a72743a4cf8f046f3587ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-6b8e7f61)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-6b8e7f61"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201835315254-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nOp2MVj86SslT5Q1pCbHOCf9fTJ1B0DYP9Jx6XqLKRU%3D&st=2021-04-20T18%3A31%3A51Z&se=2021-05-21T18%3A36%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:38 UTC, opbld31 commented
Docs Build status updates of commit _[eea1288](https://github.com/microsoftgraph/microsoft-graph-docs/commits/eea1288fff14488087a79bfef5859c8b5367b1ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-300b433c)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-300b433c"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201836040316-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=AYacST7ls4q77%2B9tX8KNGq4I0f3Z9yUPslcz6dbOQQo%3D&st=2021-04-20T18%3A33%3A08Z&se=2021-05-21T18%3A38%3A08Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:39 UTC, opbld32 commented
Docs Build status updates of commit _[d56dada](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d56dadad560c86efcae3900844706737475e5257)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-c0aea002)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-c0aea002"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201837224252-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=vmVSd5P1oGNfI%2F6V7WwzlcIxfB9K0lyCTVYT68NKKp8%3D&st=2021-04-20T18%3A34%3A18Z&se=2021-05-21T18%3A39%3A18Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:40 UTC, opbld30 commented
Docs Build status updates of commit _[c69a150](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c69a150896d58478bdc1017f38fd32f766123dc5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-bf2ba093)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-bf2ba093"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201839196004-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ofQb9TeJSn7rsue4y8XEckl9%2FEYTrr0NEkKhTsyqUBo%3D&st=2021-04-20T18%3A35%3A38Z&se=2021-05-21T18%3A40%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-20 18:41 UTC, opbld34 commented
Docs Build status updates of commit _[aa894ea](https://github.com/microsoftgraph/microsoft-graph-docs/commits/aa894ea0036136d4449ab60265bf50f30fde3ad7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-c4ec1352)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-c4ec1352"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C20%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104201840097063-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BBg%2BmlI%2FbCljcdfP%2BQ2oDwLv1rh3GpfLTXavdyyCoCM%3D&st=2021-04-20T18%3A36%3A48Z&se=2021-05-21T18%3A41%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-26 18:27 UTC, davidmu1 commented on api-reference/beta/api/accessreviewhistorydefinition-create.md
> +The following table shows the properties accepted to create an [accessReviewHistoryDefinition](../resources/accessreviewhistorydefinition.md).
Are the properties required? If so, please change 'accepted' to 'required'.

2021-04-26 18:40 UTC, davidmu1 commented on api-reference/beta/api/accessreviewhistorydefinition-get.md
> +Retrieve an [accessReviewHistoryDefinition](../resources/accessreviewhistorydefinition.md) object by ID. This returns all properties of the access review history definition object. If the download li
```suggestion
Retrieve an [accessReviewHistoryDefinition](../resources/accessreviewhistorydefinition.md) object by its identifier. All of the properties of the access review history definition object are returned. If the download link is still valid it is returned along with the definition. If the definition is 30 days or older a 404 is returned.
```

2021-04-26 18:46 UTC, davidmu1 commented on api-reference/beta/api/accessreviewhistorydefinition-list.md
> +GET https://graph.microsoft.com/beta/identityGovernance/accessReviews/historyDefinitions?$top=100&$skip=0
The first example should be running the call without any query parameters if possible to run without them.

2021-04-26 18:47 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewhistorydefinition.md
> +description: "Represents a collection of access review history data"
```suggestion
description: "Represents a collection of access review history data."
```

2021-04-26 18:50 UTC, davidmu1 commented on api-reference/beta/resources/accessreviewhistorydefinition.md
> +An accessReviewHistoryDefinition represents a collection of access review history data and the filters used to collect that data. A accessReviewHistoryDefinition's reviewHistoryPeriodStartDateTime, r
I think the term 'filter' can be misleading because of $filter query parameter. Might be better to use 'scopes',

2021-04-27 17:56 UTC, opbld33 commented
Docs Build status updates of commit _[4a5c5c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4a5c5c8fdb93ad0dbfc3f7c0f6702d7b54ea75ff)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-ba36edf3)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-ba36edf3"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271754559247-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BjO5lMU0y1zkH%2Bc2HxC%2Fcn9bzhgj%2B%2F2mrwNUTE2RFy8%3D&st=2021-04-27T17%3A51%3A14Z&se=2021-05-28T17%3A56%3A14Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 18:02 UTC, opbld34 commented
Docs Build status updates of commit _[4f6f3c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f6f3c0e630b1e0828bec682bc1a98ed3d41fa86)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-32a10e05)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-32a10e05"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271800497518-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=EticuwLhBLVszw7%2BEzdhHHTWyva799L%2FUslO%2FpVDRtA%3D&st=2021-04-27T17%3A57%3A10Z&se=2021-05-28T18%3A02%3A10Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:11 UTC, opbld34 commented
Docs Build status updates of commit _[7e2be56](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7e2be568e3e5cb04173bea868585209f66810f18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-fa15aa41)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-fa15aa41"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271909209316-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=SwXcSi%2FjgdQPrmiwXF0%2Byo7FHLcmZXf68kmQldN99oY%3D&st=2021-04-27T19%3A06%3A23Z&se=2021-05-28T19%3A11%3A23Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:12 UTC, opbld30 commented
Docs Build status updates of commit _[478105c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/478105c6c555a7ae777fa825cda462d3c1d29233)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-8d78575b)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-8d78575b"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271911076932-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FE9SrFk%2F3IcQK5NOF7VP9ZA82QN6wo8t9L9ryjU2Qdo%3D&st=2021-04-27T19%3A07%3A45Z&se=2021-05-28T19%3A12%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:14 UTC, opbld31 commented
Docs Build status updates of commit _[62d64f1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62d64f1c441cfd2bcb8bfc6a5551ad324188c31c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-bf24b846)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-bf24b846"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271912199333-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=JALbyBoXFEGuAiFhypoe0iUJqoWXTjgQTp2EoqKTuKY%3D&st=2021-04-27T19%3A09%3A03Z&se=2021-05-28T19%3A14%3A03Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:21 UTC, opbld32 commented
Docs Build status updates of commit _[ce71753](https://github.com/microsoftgraph/microsoft-graph-docs/commits/ce7175372b9ec9d9eaa05ad8f93cb3aef8922150)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-3221cfe7)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-3221cfe7"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271920438060-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Mvd9cIWo410ufIBG6BwZ6rHy0k%2By1PFCHmOuoXgKIMQ%3D&st=2021-04-27T19%3A16%3A45Z&se=2021-05-28T19%3A21%3A45Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:26 UTC, opbld33 commented
Docs Build status updates of commit _[438aef3](https://github.com/microsoftgraph/microsoft-graph-docs/commits/438aef3261df10b6e11427edc42881132295c4e1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-f89b6789)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-f89b6789"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271925242995-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yRbJS367KTPgxhd%2Fuqnm29gqfYQhYlaXrIra5qcjyCQ%3D&st=2021-04-27T19%3A21%3A37Z&se=2021-05-28T19%3A26%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:27 UTC, leherpel commented on api-reference/beta/api/accessreviewhistorydefinition-create.md
> +author: "leherpel"
Updating to isabelleatmsft

2021-04-27 19:27 UTC, opbld31 commented
Docs Build status updates of commit _[3e0138f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3e0138f7c061c68dbae33d4e0345bdfff0ee3e6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-2e5734df)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-2e5734df"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271926009123-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VevQDZakcNSLK3jg1SsiHIJNiEphAO0xQ%2BLeDug0pc4%3D&st=2021-04-27T19%3A22%3A53Z&se=2021-05-28T19%3A27%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:30 UTC, leherpel commented on api-reference/beta/resources/accessreviewhistorydefinition.md
> +An accessReviewHistoryDefinition represents a collection of access review history data and the filters used to collect that data. A accessReviewHistoryDefinition's reviewHistoryPeriodStartDateTime, r
Changed to scopes

2021-04-27 19:31 UTC, leherpel commented on api-reference/beta/api/accessreviewhistorydefinition-create.md
> +The following table shows the properties accepted to create an [accessReviewHistoryDefinition](../resources/accessreviewhistorydefinition.md).
I changed it to required and optional because two of these are optional parameters.

2021-04-27 19:31 UTC, opbld33 commented
Docs Build status updates of commit _[a257668](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a25766841c756aee367431679af8a810660aa281)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-049b5d0e)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-049b5d0e"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271930010123-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=dAReHhVL1MMsGwNf50JTbBYS9u%2BE574Hg5vdd8lGjEo%3D&st=2021-04-27T19%3A26%3A39Z&se=2021-05-28T19%3A31%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:33 UTC, opbld34 commented
Docs Build status updates of commit _[a257668](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a25766841c756aee367431679af8a810660aa281)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-78f6481c)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-78f6481c"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271930110121-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=NC8YBKSYUnSzqp90TLdgC7PMtz%2F5o62xtb2SfPGY1I0%3D&st=2021-04-27T19%3A28%3A07Z&se=2021-05-28T19%3A33%3A07Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:36 UTC, opbld31 commented
Docs Build status updates of commit _[64e5ca9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/64e5ca9834f89a87b4939fa6767a0c7b23084f93)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-4151eb28)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-4151eb28"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271935274038-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=BcvQ2Pe2e0ZzvMG34oEiTuDGDXYZ09SHhzvaiEk4RqA%3D&st=2021-04-27T19%3A31%3A48Z&se=2021-05-28T19%3A36%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[d00121f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d00121fd4618c318a5a4368885a245fd516577b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-769db0ff)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-769db0ff"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271936184229-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Z8z5Lw1VZodF8nJyztaOPdyzyH3kpHe%2BOt7h1biG7q4%3D&st=2021-04-27T19%3A32%3A59Z&se=2021-05-28T19%3A37%3A59Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:39 UTC, opbld32 commented
Docs Build status updates of commit _[4fb14ab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4fb14ab0d34d71975c37c09b5d89cd38f1f89129)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-7785547e)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-7785547e"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271936516064-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8GFar0l9ZqCFbTVXl%2F%2B%2FZHG4BMw5bJxcI%2BFJh0BHQxs%3D&st=2021-04-27T19%3A34%3A25Z&se=2021-05-28T19%3A39%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:42 UTC, opbld34 commented
Docs Build status updates of commit _[fd98e82](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fd98e8288b64b6ee0f7390ec02fa6a6d23a18c1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-2a26fbe0)
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5b21614878c88dec0f9405349e0c21ff-2a26fbe0"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271940491544-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=pqoUtxrOkxs%2BOyFZUScM9hXLi%2BzxuHSpCtldmqleJWM%3D&st=2021-04-27T19%3A37%3A05Z&se=2021-05-28T19%3A42%3A05Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:48 UTC, opbld32 commented
Docs Build status updates of commit _[cc8ed4d](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cc8ed4d06a99abf18202311fe03a0abcb87f44ae)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5159684801f68d50e9a725ac1a34cc81-1f2dd79c)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-1f2dd79c)
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5159684801f68d50e9a725ac1a34cc81-1f2dd79c"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md)
 - **Line 62, Column 43**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorydefinition.md'.`````
 - **Line 62, Column 122**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewscope.md'.`````

<a id="5b21614878c88dec0f9405349e0c21ff-1f2dd79c"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271947091642-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=g7tBPuukpaLZyxSJgp0KdhOm%2BEExIY5%2BQplmt0%2B%2Bgts%3D&st=2021-04-27T19%3A43%3A25Z&se=2021-05-28T19%3A48%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:56 UTC, opbld33 commented
Docs Build status updates of commit _[4ae01a1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4ae01a133464937f32a06755450bb4c89940b758)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5159684801f68d50e9a725ac1a34cc81-27966df3)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-27966df3)
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5159684801f68d50e9a725ac1a34cc81-27966df3"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md)
 - **Line 62, Column 43**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorydefinition.md'.`````
 - **Line 62, Column 122**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewscope.md'.`````

<a id="5b21614878c88dec0f9405349e0c21ff-27966df3"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271955147000-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=0opzvhCrLmPuIpbau1Yhk9vIv%2FzVwSEVxa8qWqqdTJs%3D&st=2021-04-27T19%3A51%3A32Z&se=2021-05-28T19%3A56%3A32Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 19:59 UTC, opbld32 commented
Docs Build status updates of commit _[d9308b6](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d9308b64301ccaac50ff97d9528ccabda7fb852e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5159684801f68d50e9a725ac1a34cc81-783ad80b)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-783ad80b)
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5159684801f68d50e9a725ac1a34cc81-783ad80b"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md)
 - **Line 62, Column 43**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorydefinition.md'.`````
 - **Line 62, Column 122**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewscope.md'.`````

<a id="5b21614878c88dec0f9405349e0c21ff-783ad80b"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104271957357971-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QrcSemnJSeHxw%2FZAqqV9HWxowqgRvNEeR0VwGmC09bM%3D&st=2021-04-27T19%3A54%3A06Z&se=2021-05-28T19%3A59%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 20:38 UTC, opbld34 commented
Docs Build status updates of commit _[9a690ff](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9a690ff3ee59c42df4a04320698306b0838fe709)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5159684801f68d50e9a725ac1a34cc81-14ed084d)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5b21614878c88dec0f9405349e0c21ff-14ed084d)
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5159684801f68d50e9a725ac1a34cc81-14ed084d"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md)
 - **Line 62, Column 43**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorydefinition.md'.`````
 - **Line 62, Column 122**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewscope.md'.`````

<a id="5b21614878c88dec0f9405349e0c21ff-14ed084d"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md)
 - **Line 1, Column 1**: **[Warning-[title-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/title-missing?branch=main)]** `````Missing required attribute: 'title'. Add a title string to show in search engine results.`````
 - **Line 3, Column 14**: **[Warning-yaml-header-syntax-error]** `````While scanning a multi-line double-quoted scalar, found wrong indentation.`````
 - **Line 1, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272036366737-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=GoodH6u8bes%2BhtK%2BKjO5mYLUjFYTWgTFk6QhTbUQw2M%3D&st=2021-04-27T20%3A33%3A09Z&se=2021-05-28T20%3A38%3A09Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 20:42 UTC, opbld30 commented
Docs Build status updates of commit _[c9a8bef](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9a8befeb3e34e28f173b8acea6a5c854644f45d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-5159684801f68d50e9a725ac1a34cc81-1069fc47)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="5159684801f68d50e9a725ac1a34cc81-1069fc47"></a>
### [api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md)
 - **Line 62, Column 43**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewhistorydefinition.md'.`````
 - **Line 62, Column 122**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'accessreviewscope.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272041035229-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=K7NkU5eRpvXXiiyUgk%2FGpQJEftXhxA2Vt0eVHxu5Ujw%3D&st=2021-04-27T20%3A37%3A20Z&se=2021-05-28T20%3A42%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 20:59 UTC, opbld33 commented
Docs Build status updates of commit _[3471850](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3471850822aead5336e1315c11166149d02d510b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272058144852-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=7j802jeR%2BlMQikm5IdANnRaaMGU2NYQrSkhZFW6N9WI%3D&st=2021-04-27T20%3A54%3A25Z&se=2021-05-28T20%3A59%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 21:03 UTC, opbld34 commented
Docs Build status updates of commit _[0c74f05](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0c74f05995db395fb3cb98f31ea3f7a515ca4669)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272102315699-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=WjP6j6%2FG%2BFt9mBfaQZrdm%2BOm2qI%2Fzye5pBy1fhfwXoo%3D&st=2021-04-27T20%3A58%3A58Z&se=2021-05-28T21%3A03%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 21:09 UTC, opbld31 commented
Docs Build status updates of commit _[25f583b](https://github.com/microsoftgraph/microsoft-graph-docs/commits/25f583b49f6a5e7c5c47e9810a16748b81c3fb4e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272107595980-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6n3NzUF1aN2FFTkxoxhTpxFphUNy2ZvherGouA1k3Kg%3D&st=2021-04-27T21%3A04%3A14Z&se=2021-05-28T21%3A09%3A14Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 21:14 UTC, opbld34 commented
Docs Build status updates of commit _[bd0c6dd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bd0c6dd1ea1f5dcff553369e545d0640a95997db)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272113198319-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FpY0bxhZ4nSDhaFVeGIYXYbJW3Pc%2BGFfByq2ZwQBbsk%3D&st=2021-04-27T21%3A09%3A33Z&se=2021-05-28T21%3A14%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 21:22 UTC, opbld34 commented
Docs Build status updates of commit _[e1977e9](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e1977e9de67925f3b7e241c95b2b677e5ae1e426)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272121178871-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Avk%2F4ISnWy%2FFz7IciKLRfOJDue6VgQIOiRTWY562tsA%3D&st=2021-04-27T21%3A17%3A19Z&se=2021-05-28T21%3A22%3A19Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 21:31 UTC, opbld31 commented
Docs Build status updates of commit _[4f76242](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4f76242bc16198f950a9e45bfa0ba010ce1b6172)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272130400244-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=rTwIQ0SPpF6l9R6ef%2B%2B1EaeH6xkcfTnRLzFrfMaRuj4%3D&st=2021-04-27T21%3A26%3A45Z&se=2021-05-28T21%3A31%3A45Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 22:03 UTC, opbld30 commented
Docs Build status updates of commit _[3d30c1a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3d30c1a992735d3318b440990c2d69a20eb6a6d4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C27%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104272202216993-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=CdupuLRe5Z%2FB6PEhfzwfTf5L%2BvvoqLeKJ44T91ok6R4%3D&st=2021-04-27T21%3A58%3A26Z&se=2021-05-28T22%3A03%3A26Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 16:40 UTC, opbld34 commented
Docs Build status updates of commit _[505df95](https://github.com/microsoftgraph/microsoft-graph-docs/commits/505df95f82c4c76a0dfaf0f6695abda0367ad862)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2916621e)

<a id="2916621e"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104281639404577-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ihhuAqCANvEhhKjZ6cDdryyK4CK0AIpX7EX7tT7NhoE%3D&st=2021-04-28T16%3A35%3A06Z&se=2021-05-29T16%3A40%3A06Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 16:43 UTC, opbld30 commented
Docs Build status updates of commit _[6b19361](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b19361fe4e9637222cce0f3499eeace918d9c78)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8ec6b756)

<a id="8ec6b756"></a>
###
 - **[Error-PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104281642197390-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F5rKzAdBtu9JUw5N0gIXLze70mRJW4hLoFfi%2BRM35FQ%3D&st=2021-04-28T16%3A38%3A30Z&se=2021-05-29T16%3A43%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 16:49 UTC, opbld31 commented
Docs Build status updates of commit _[6250441](https://github.com/microsoftgraph/microsoft-graph-docs/commits/62504414e6aa86a7431a053cf6281fc0a1b3a5b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104281647328791-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HKtPq4bmzK%2FkBaTT2qG1eRG8n6MEguuEY%2FEwpgux7Yc%3D&st=2021-04-28T16%3A44%3A25Z&se=2021-05-29T16%3A49%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 16:53 UTC, opbld31 commented
Docs Build status updates of commit _[f5723b2](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f5723b216ec321566655c61dbf8b709324de8e8a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104281651093656-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=umlq1CzW0xOFEdP3DfwmnYEqmabcr0xh2M5lGMQ%2FRlo%3D&st=2021-04-28T16%3A48%3A30Z&se=2021-05-29T16%3A53%3A30Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 16:56 UTC, opbld33 commented
Docs Build status updates of commit _[c288ea5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c288ea5d1d33548ce021a23a4ae2c775687fa7bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C28%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104281655171193-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=HIlRKrmFp0%2FYm%2FZOQjPcOfz1z7elleXAvcYzFu4bXyQ%3D&st=2021-04-28T16%3A51%3A34Z&se=2021-05-29T16%3A56%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-28 17:10 UTC, isabelleatmsft approved these changes

2021-04-30 06:17 UTC, FaithOmbongi requested changes

2021-04-30 06:17 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewhistorydefinition-list.md
> +>If many **accessReviewHistoryDefinitions** are returned, to improve efficiency and avoid timeouts, retrieve the result set in pages, by including both the $top query parameter with a page size of at
```suggestion
>The default page size for this API is 100 accessReviewHistoryDefinitions objects. To improve efficiency and avoid timeouts due to large result sets, apply pagination using the `$skip` and `$top` query parameters. For more information, see [Paging Microsoft Graph data in your app](/graph/paging).
```

2021-04-30 06:17 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewhistorydefinition-create.md
> +| Include every `accessReviewScheduleDefinition` review result for service principals assigned to privileged role | /identityGovernance/accessReviews/definitions?$filter=contains(scope/microsoft.grap
There's a WIP PR to transform these into a conceptual article for accessReviewQueryScope. When the changes go live, we'll revisit this and link to the page.

2021-04-30 06:17 UTC, FaithOmbongi commented on api-reference/beta/api/accessreviewhistorydefinition-create.md
> +This is an example of creating an access review history definition which is scoped to access package and group reviews starting and ending on or between 01/01/2021 and 04/05/2021.
```suggestion
This is an example of creating an access review history definition scoped to access reviews on access packages and groups, running between the start date of 01/01/2021 and end date of 04/05/2021.
```

2021-04-30 21:46 UTC, opbld33 commented
Docs Build status updates of commit _[57831a8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/57831a819d10685dde0aeec8aa643fba693db8ee)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104302144142762-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=gG%2F1ebdm0QX6b%2BC0yvHgScjhxWJLGJcbFtaTgvUDWaA%3D&st=2021-04-30T21%3A41%3A28Z&se=2021-05-31T21%3A46%3A28Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-30 21:47 UTC, opbld34 commented
Docs Build status updates of commit _[b384aaa](https://github.com/microsoftgraph/microsoft-graph-docs/commits/b384aaa2898e3fa8017da42281429c0c4595fbc4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104302145383747-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qMzmhR5WKtHCC0X9AXhp7qLG9iak%2Fu0NxeIUhGkVRGA%3D&st=2021-04-30T21%3A42%3A33Z&se=2021-05-31T21%3A47%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-30 21:48 UTC, opbld31 commented
Docs Build status updates of commit _[d820a6a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d820a6a27177e3f227dc4dfccfd8065901a6833c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104302146378606-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=xC7PeUPxYV808EjWM%2Fq9Xw%2FS7ZTSpymfMu4NAFijFgI%3D&st=2021-04-30T21%3A43%3A47Z&se=2021-05-31T21%3A48%3A47Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-30 21:50 UTC, opbld32 commented
Docs Build status updates of commit _[6be7657](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6be76578ab77e6cfa65338d6eddb8a32b786be3f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C30%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104302148551288-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gmm84lYf7IhqdDCWSPiZW6YcyTT8NRtZrmVr8eNlAuA%3D&st=2021-04-30T21%3A45%3A22Z&se=2021-05-31T21%3A50%3A22Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 06:53 UTC, FaithOmbongi commented on api-reference/beta/resources/accessreviewhistorydefinition.md
> +|displayName|String|Name for the access review history data collection. Required on create.|
```suggestion
|displayName|String|Name for the access review history data collection. Required.|
```

2021-05-03 06:55 UTC, opbld31 commented
Docs Build status updates of commit _[94359b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94359b7d50703707d504504031df97ca9dba7345)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105030654229288-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BgmcUptZOxtTxDgqY%2Fb0xW29xly4ss7H419mvQ779jc%3D&st=2021-05-03T06%3A50%3A35Z&se=2021-06-03T06%3A55%3A35Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 06:57 UTC, opbld30 commented
Docs Build status updates of commit _[94359b7](https://github.com/microsoftgraph/microsoft-graph-docs/commits/94359b7d50703707d504504031df97ca9dba7345)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C3%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105030654339120-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=QCg1nrDGONQnWJFS4lJwPwt%2Fl33zY%2BkD5lnBRf0rpMs%3D&st=2021-05-03T06%3A52%3A00Z&se=2021-06-03T06%3A57%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-03 06:58 UTC, FaithOmbongi approved these changes

2021-05-04 01:06 UTC, opbld31 commented
Docs Build status updates of commit _[63c5709](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63c5709dbabe28b986ce85dea1dbe38422f18dea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040105353456-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=d63Khkfql2x%2BEhArX1LwLk3EDGFCU6ua9zy%2Bb2sy5FQ%3D&st=2021-05-04T01%3A01%3A48Z&se=2021-06-04T01%3A06%3A48Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 01:08 UTC, opbld33 commented
Docs Build status updates of commit _[63c5709](https://github.com/microsoftgraph/microsoft-graph-docs/commits/63c5709dbabe28b986ce85dea1dbe38422f18dea)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-create.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-create.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-create?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040105462405-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o03uZYz0GO7TT3dVpulAs7St4g5IGZNWEj4q14o22I0%3D&st=2021-05-04T01%3A03%3A00Z&se=2021-06-04T01%3A08%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:12 UTC, opbld31 commented
Docs Build status updates of commit _[376ae70](https://github.com/microsoftgraph/microsoft-graph-docs/commits/376ae70f8224d23b05f23a41e7f709ed2fc319d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-9b77a2a75091e101c0091265983eaca9-63c37ae3)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="9b77a2a75091e101c0091265983eaca9-63c37ae3"></a>
### [api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md)
 - **Line 22, Column 2**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040210374934-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Waik6MSQCyhGTvlV%2Fjm5EDFXAeEsUvvUnIu5tYQoO7U%3D&st=2021-05-04T02%3A07%3A31Z&se=2021-06-04T02%3A12%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:15 UTC, opbld33 commented
Docs Build status updates of commit _[3254c83](https://github.com/microsoftgraph/microsoft-graph-docs/commits/3254c83fbd7c97dd22645a45348757c151234049)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040214410236-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V79VsCBcCGkMerEnllAE4fOQiqS6XLU%2F3RTcKrFszGY%3D&st=2021-05-04T02%3A10%3A53Z&se=2021-06-04T02%3A15%3A53Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:18 UTC, Lauragra commented on api-reference/beta/api/accessreviewhistorydefinition-post.md
> +### Supported scope queries for accessReviewHistoryDefinition
I'm unclear about how this section relates to the Create operation. The Queries don't use historyDefintions in the syntax. Would it make sense to be covering this in the Optional query parameters section of the List operation topic?

2021-05-04 02:20 UTC, opbld33 commented
Docs Build status updates of commit _[0609128](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0609128274f312e78253a605735921de7507d8ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040219201852-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=s6J5d3PqYsjhH%2BQbMAb%2BvVZYVZ9rufeEItBcQP56rlA%3D&st=2021-05-04T02%3A15%3A25Z&se=2021-06-04T02%3A20%3A25Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:22 UTC, opbld31 commented
Docs Build status updates of commit _[0609128](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0609128274f312e78253a605735921de7507d8ae)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040219305686-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KbUFZOxil6yDFT9d%2FWXu6Voy0kwAIHrfOEpXTDL8rF4%3D&st=2021-05-04T02%3A17%3A31Z&se=2021-06-04T02%3A22%3A31Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:28 UTC, opbld30 commented
Docs Build status updates of commit _[70ffadc](https://github.com/microsoftgraph/microsoft-graph-docs/commits/70ffadce7faae177d401b92f1a0df36b8eac1893)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040226526722-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=FpIs6CyErUkSDdNs6Jop20nd3MZRYGn%2Bq%2B39gaakXLc%3D&st=2021-05-04T02%3A23%3A10Z&se=2021-06-04T02%3A28%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:29 UTC, opbld31 commented
Docs Build status updates of commit _[c692759](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c692759241ee4412e5c7543f189d8476512b81d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040228351810-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=baAB9lgkI1Jq0LZeMx53Iiws%2FZ9gm0cIKTmwgXoUmhE%3D&st=2021-05-04T02%3A24%3A42Z&se=2021-06-04T02%3A29%3A42Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 02:29 UTC, Lauragra commented on changelog/Microsoft.IdentityGovernance.AccessReviews.json
> +                    "Id": "854b8211-8d9a-11eb-a57c-31dcdef91872",
The IDs for all the entries within a changelist should be the same.

2021-05-04 02:30 UTC, Lauragra commented on api-reference/beta/resources/accessreviewhistorydefinition.md
> +# accessReviewHistoryDefinition resource type
Please surface this resource and its methods in the TOC.

2021-05-04 02:31 UTC, opbld30 commented
Docs Build status updates of commit _[c692759](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c692759241ee4412e5c7543f189d8476512b81d9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105040228456702-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9x3rcydk96HEtMatQo0CV3D5MP9zd2pdR4obdcDkXL0%3D&st=2021-05-04T02%3A26%3A00Z&se=2021-06-04T02%3A31%3A00Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-04 23:44 UTC, opbld30 commented
Docs Build status updates of commit _[f7b3565](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f7b35652f8f70dfc568c67368480132946308455)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-d7d70c9c)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-d7d70c9c"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/toc.yml)
 - **Line 11238, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C4%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105042342351011-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8PZs4fzE8d%2BJHwZCF6Vs%2BMmFcciBGqk2%2Bz8kNcQgjzI%3D&st=2021-05-04T23%3A39%3A00Z&se=2021-06-04T23%3A44%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 01:05 UTC, Lauragra approved these changes

2021-05-05 01:05 UTC, opbld30 commented
Docs Build status updates of commit _[bfb78c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfb78c03d660c5cf7de0c9965331ce02738f4c95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-22cdc4c2)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-22cdc4c2"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/toc.yml)
 - **Line 11238, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105050104308035-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Q7YXZPwKhQxqTBlTokiY1rb%2B%2FYSGDYiEoaUye3YUU5E%3D&st=2021-05-05T01%3A00%3A48Z&se=2021-06-05T01%3A05%3A48Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 01:07 UTC, opbld33 commented
Docs Build status updates of commit _[bfb78c0](https://github.com/microsoftgraph/microsoft-graph-docs/commits/bfb78c03d660c5cf7de0c9965331ce02738f4c95)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-85c209ca)
[api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-generatedownloaduri.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-generatedownloaduri?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-get?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-list?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/api/accessreviewhistorydefinition-post.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/api/accessreviewhistorydefinition-post.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/accessreviewhistorydefinition-post?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[api-reference/beta/resources/accessreviewhistorydefinition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/resources/accessreviewhistorydefinition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/resources/accessreviewhistorydefinition?view=graph-rest-beta&branch=pr-en-us-12107) (graph-rest-beta) |
[changelog/Microsoft.IdentityGovernance.AccessReviews.json](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/changelog/Microsoft.IdentityGovernance.AccessReviews.json) | :white_check_mark:Succeeded | |

<a id="0817dce4456c16725d5333633847d38f-85c209ca"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/2021-03-25-test/AccessReviewHistory/api-reference/beta/toc.yml)
 - **Line 11238, Column 21**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'api/accessreviewhistorydefinition-create.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202105050104428304-12107%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=J0W7uEMib6XzBitIVygv2i9xo%2FD8AhmqVxW4t1%2BsUQE%3D&st=2021-05-05T01%3A02%3A30Z&se=2021-06-05T01%3A07%3A30Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-05 01:08 UTC, merged