New doc for namedItem delete operation in beta
microsoftgraph/microsoft-graph-docs pull request #12173
Opened 2021-03-31 14:40 UTC by isvargasmsft

This is the first draft

2021-03-31 14:49 UTC, opbld32 commented
Docs Build status updates of commit _[6a3be3e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6a3be3e31aaeeb558cfd21151288ef3750c00484)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-34a1fd762cd20e9bcc280b3959b9aa00-d21440d2)

<a id="34a1fd762cd20e9bcc280b3959b9aa00-d21440d2"></a>
### [api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 16, Column 22**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/nameditem.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103311447433330-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f1HB21mPqHcYQuDDZVVQhY2hFMhJYpflMreRl2O7sDY%3D&st=2021-03-31T14%3A44%3A00Z&se=2021-05-01T14%3A49%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-31 15:03 UTC, jasonjoh requested changes

2021-03-31 15:05 UTC, jasonjoh commented
Couple of additional suggestions:

- Delete is also missing from v1. Check with the owner but I would assume it should be doc'ed there too :D.
- Don't forget to add this to [toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/main/api-reference/beta/toc.yml)
- Edit the body of your pull request to add a line `Fixes #913`. This will auto-close the GitHub issue when the PR is merged.

2021-03-31 17:59 UTC, opbld32 commented
Docs Build status updates of commit _[0306704](https://github.com/microsoftgraph/microsoft-graph-docs/commits/0306704349259871f05cb1cf7210c27cf60fcaf8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-34a1fd762cd20e9bcc280b3959b9aa00-4da67cc8)

<a id="34a1fd762cd20e9bcc280b3959b9aa00-4da67cc8"></a>
### [api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 16, Column 22**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/nameditem.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103311754502517-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Gh89Nx9h6HMR6vl5ffVEL8OaHO5ICOwipbA2GvEwjHs%3D&st=2021-03-31T17%3A54%3A51Z&se=2021-05-01T17%3A59%3A51Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-03-31 18:04 UTC, opbld30 commented
Docs Build status updates of commit _[e8c1a13](https://github.com/microsoftgraph/microsoft-graph-docs/commits/e8c1a13c6608c540530d698530758a776a0e1ffa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-34a1fd762cd20e9bcc280b3959b9aa00-a9e3f2f6)

<a id="34a1fd762cd20e9bcc280b3959b9aa00-a9e3f2f6"></a>
### [api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-missing?branch=main)]** `````Missing attribute: 'ms.prod'. If you specify 'ms.technology', you must also specify 'ms.prod'.`````
 - **Line 2, Column 1**: **[Warning-[ms-prod-or-service-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-or-service-missing?branch=main)]** `````One of the following attributes is required: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C3%5C31%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202103311759000021-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O67E%2BlbWeD6v9i54zPpfh%2FwLNjYmnx6HMonqe6zKzG4%3D&st=2021-03-31T17%3A59%3A41Z&se=2021-05-01T18%3A04%3A41Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-01 10:12 UTC, chiz-ms commented on api-reference/beta/api/nameditem-delete.md
> +title: "Delete namedItem"
It seems for add the title is "Add Named Item". Shall we align?

2021-04-01 10:13 UTC, chiz-ms commented on api-reference/beta/api/nameditem-delete.md
> +## Permisions
Seems a typo.

2021-04-01 10:17 UTC, chiz-ms commented on api-reference/beta/api/nameditem-delete.md
> +|Delegated (work or school account) | Files.ReadWrite, Sites.Read.All    |
This is interesting. We didn't notice this before. We need to double check this (I agree it doesn't look correct).

2021-04-01 10:18 UTC, chiz-ms commented on api-reference/beta/api/nameditem-delete.md
> +| Authorization  | Bearer {token}. Required. |
Please add Workbook-Session-Id similar to the add request.

2021-04-02 06:22 UTC, angelgolfer-ms commented on api-reference/beta/api/nameditem-delete.md
> +title: "Delete namedItem"
Good catch, chiz-ms!
Because the "create" method is actually an "add" action, not a usual POST operation, please change "Add Named Item" to "workbookNamedItem: add", following the [topic title guidance](https://dev.azure.com/msazure/One/_wiki/wikis/Microsoft%20Graph%20Partners/103176/ToC-and-topic-title).
Please make sure the topic title casing follows the camel case of the binding parameter (i.e., workbookNamedItem) and the method "add".

"Delete namedItem" follows the topic title guidance.

2021-04-02 06:25 UTC, angelgolfer-ms commented on api-reference/beta/api/nameditem-delete.md
> +ms.prod: ""
Please always address any build warnings, suggestions, and of course build errors, if there are any.
In this case, there are 2 warnings about the ms.prod attribute (missing value). Please fill that in.

2021-04-02 07:02 UTC, angelgolfer-ms commented on api-reference/beta/api/nameditem-delete.md
> +| Authorization  | Bearer {token}. Required. |
@isvargasmsft , when you add the Workbook-Session-Id header and its description, please make sure you use "ID" instead of "Id", in "Workbook session Id that determines if changes are persisted or not. Optional." "ID" is the proper acronym for identifier, not "Id".

It would be good if you can fix the same in the nameditem-add.md topic as well.

For

2021-04-02 07:04 UTC, angelgolfer-ms requested changes
@isvargasmsft , good job particularly this is your first PR!
Just a few comments, please take a look!

2021-04-02 11:42 UTC, chiz-ms commented on api-reference/beta/api/nameditem-delete.md
> +title: "Delete namedItem"
If that's the case probably we want to also review others? It seems current titles have various formats.

2021-04-05 16:09 UTC, opbld34 commented
Docs Build status updates of commit _[cd3fcfd](https://github.com/microsoftgraph/microsoft-graph-docs/commits/cd3fcfd409df2fcb8f13e850ba8c7173badcc504)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051607397416-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UwO6fL%2FMp1QdnNWRtFqzJvzufhCLw3JkizM0B1XzQig%3D&st=2021-04-05T16%3A04%3A15Z&se=2021-05-06T16%3A09%3A15Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 16:52 UTC, opbld33 commented
Docs Build status updates of commit _[6b4ce8c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6b4ce8ca4f5068903e421de87b4a11a0713db5b8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051650138439-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F%2BzQs03bMg7deNHQnbVdlEbeMSSEKMnlpWgj5shO%2BmM%3D&st=2021-04-05T16%3A47%3A24Z&se=2021-05-06T16%3A52%3A24Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 16:57 UTC, opbld34 commented
Docs Build status updates of commit _[4581c1c](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4581c1c9ca1fab4da249ae89a412da3ec1cedc84)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-368a6bfc)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |

<a id="739c78cc20d2aa5fd610e5019c6b9741-368a6bfc"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051655576794-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=o1CIYypqlbL2x6gUiV7AdaSi0h2vmYur95wJbZYWqlk%3D&st=2021-04-05T16%3A52%3A10Z&se=2021-05-06T16%3A57%3A10Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 17:05 UTC, opbld32 commented
Docs Build status updates of commit _[6f8280e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/6f8280eb754c2cc5f22b9333162a788701de5f1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-6a4a6516f507d3ad1b8c97607c5b5d44-c3158beb)
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-c3158beb)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |

<a id="6a4a6516f507d3ad1b8c97607c5b5d44-c3158beb"></a>
### [api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md)
 - **Line 16, Column 22**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../resources/workbooknameditem.md'.`````

<a id="739c78cc20d2aa5fd610e5019c6b9741-c3158beb"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051704266144-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=jppgHqZOcYd1frhpBTKkC0hLsWwYVm0ZqQksw5S5Rkw%3D&st=2021-04-05T17%3A00%3A39Z&se=2021-05-06T17%3A05%3A39Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 17:15 UTC, opbld30 commented
Docs Build status updates of commit _[d68c87a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d68c87a26d86b0209da01cc1c31ab4b7c8b4d714)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-d9db3631)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |

<a id="739c78cc20d2aa5fd610e5019c6b9741-d9db3631"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051713482833-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=C4peE1omCDeiiRI569L8uzztcf6BFTaQd8AH8xiLMks%3D&st=2021-04-05T17%3A10%3A11Z&se=2021-05-06T17%3A15%3A11Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 18:33 UTC, jasonjoh requested changes
- Make sure the name of the resource is consistent. (workbookNamedItem vs. namedItem)
- Be sure to add the new delete topics to their respective TOC.yml files.

2021-04-05 18:33 UTC, jasonjoh commented on api-reference/v1.0/api/nameditem-add.md
> +title: "namedItem: add"
In the beta topic it's workbookNamedItem. Which one is right?

2021-04-05 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[fc5dd4a](https://github.com/microsoftgraph/microsoft-graph-docs/commits/fc5dd4a6f101a75b0a4f10534c5eae3d4f96bd93)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-5113fdc8)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |

<a id="739c78cc20d2aa5fd610e5019c6b9741-5113fdc8"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051937328109-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lu7qFGJ4AlNOt%2Bd%2FfdMauvgYKOgb0dxUteGyZ3GpFRk%3D&st=2021-04-05T19%3A33%3A58Z&se=2021-05-06T19%3A38%3A58Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 19:41 UTC, opbld31 commented
Docs Build status updates of commit _[76ccbd1](https://github.com/microsoftgraph/microsoft-graph-docs/commits/76ccbd16dfde38ce4aa6b5dcc1566aa124225e1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/toc.yml) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-0817dce4456c16725d5333633847d38f-8d23e541)
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-8d23e541)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |

<a id="0817dce4456c16725d5333633847d38f-8d23e541"></a>
### [api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/toc.yml)
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````
 - **Line 11, Column 7**: **[Warning-yaml-duplicate-key]** `````Key 'href' is already defined, remove the duplicate key.`````

<a id="739c78cc20d2aa5fd610e5019c6b9741-8d23e541"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051939508163-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=5fr3gkgiBHC%2B9T1s9yL%2FWonc4yDkm8mlOJcDH1gmnLA%3D&st=2021-04-05T19%3A36%3A20Z&se=2021-05-06T19%3A41%3A20Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 19:51 UTC, opbld32 commented
Docs Build status updates of commit _[f634fb8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f634fb80d5f87345782c3dc42a02a98fb2b7d0ed)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-79b9fb20)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |

<a id="739c78cc20d2aa5fd610e5019c6b9741-79b9fb20"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C5%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104051950388546-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=LUubyla6E4fA6HIyY%2BAxjRS6sKypozHU6tRIjhAL5no%3D&st=2021-04-05T19%3A46%3A52Z&se=2021-05-06T19%3A51%3A52Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-05 23:45 UTC, isvargasmsft commented on api-reference/v1.0/api/nameditem-add.md
> +title: "namedItem: add"
@chiz-ms could you please clarify this?

2021-04-06 03:31 UTC, chiz-ms commented on api-reference/v1.0/api/nameditem-add.md
> +title: "namedItem: add"
v1.0 should be the same as beta, but I'm not sure whether you should write `workbookNamedItem` or `namedItem`. It looks more about documentation convention. The type is currently described in https://github.com/microsoftgraph/microsoft-graph-docs/blob/f634fb80d5f87345782c3dc42a02a98fb2b7d0ed/api-reference/v1.0/resources/nameditem.md, and you can see even in that page it is sometimes called "`NamedItem`" while in some other cases "`WorkbookNamedItem`". Whichever we call it, I would prefer names aligned across the whole Graph documentation unless there's a reason to make them different :)

2021-04-06 16:04 UTC, angelgolfer-ms commented on api-reference/beta/api/nameditem-add.md
> -title: "Add Named Item"
Please also make the update in line 10.
Here line 2 is just the metadata. It doesn't show in the published topic.

2021-04-06 16:15 UTC, opbld34 commented
Docs Build status updates of commit _[9ba62c8](https://github.com/microsoftgraph/microsoft-graph-docs/commits/9ba62c8b43c533bc450fa9c3832405255f206342)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-46563a50)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |

<a id="739c78cc20d2aa5fd610e5019c6b9741-46563a50"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061613558492-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ejzCyrTkMALU0MHdPlGurneD0%2BV0hqi19UxUHvmTOr8%3D&st=2021-04-06T16%3A10%3A17Z&se=2021-05-07T16%3A15%3A17Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 16:18 UTC, isvargasmsft commented on api-reference/v1.0/api/nameditem-add.md
> +title: "namedItem: add"
Setting this to workbookNamedItem

2021-04-06 16:19 UTC, opbld34 commented
Docs Build status updates of commit _[8074eb5](https://github.com/microsoftgraph/microsoft-graph-docs/commits/8074eb52f815185b3ab53a5ef2c12dc74b753341)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-9baeaf73)
[api-reference/beta/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/v1.0/api/nameditem-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-delete?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |
[api-reference/v1.0/toc.yml](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) |

<a id="739c78cc20d2aa5fd610e5019c6b9741-9baeaf73"></a>
### [api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md)
 - **Line 3, Column 14**: **[Suggestion-[duplicate-descriptions](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Adds a new name to the collection of the given scope using the user's locale for the formula.' is duplicated in 'v1.0/api/nameditem-add.md(3,14)', 'v1.0/api/nameditem-addformulalocal.md(3,14)'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C6%5C77e68b91-cf14-3558-43ca-0d6d735c492d%5CPullRequest%5C202104061618152113-12173%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=4uzdT5fHMxra9PDKdwF0VIcbxcjxAibBxZwLohKc%2FtA%3D&st=2021-04-06T16%3A14%3A38Z&se=2021-05-07T16%3A19%3A38Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/77e68b91-cf14-3558-43ca-0d6d735c492d?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-06 19:18 UTC, angelgolfer-ms approved these changes
Thanks for the prompt updates!

2021-04-06 19:44 UTC, isvargasmsft commented
@chiz-ms may I please have your approval to proceed further? Is there any additional changes you'd like for these particular articles?

2021-04-07 03:45 UTC, chiz-ms commented on api-reference/v1.0/api/nameditem-delete.md
> +Delete the specified [namedItem](../resources/nameditem.md) object.
Not sure whether we should use `namedItem` or `workbookNamedItem` here. And I wonder whether we should align such names across the whole Graph documentation.

2021-04-07 03:45 UTC, chiz-ms approved these changes

2021-04-08 22:26 UTC, opbld34 commented
Docs Build status updates of commit _[c9645fe](https://github.com/microsoftgraph/microsoft-graph-docs/commits/c9645fed5e76aacee0738439530dad16c3f5a4b0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-f986fb27eb8455f7aafa1208cf70b9aa-282da467)
[api-reference/beta/api/nameditem-addformulalocal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-addformulalocal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-addformulalocal?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-1813e864a2c33ec4704ffca7c8857c96-282da467)
[api-reference/beta/api/nameditem-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-get.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-9c72e0cac3da2e0d20a3a228a1db4768-282da467)
[api-reference/beta/api/nameditem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-35238428b6e6145941248d76a01487b1-282da467)
[api-reference/beta/api/nameditem-range.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-range.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-range?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-13798483bc53e4b2e6ca4ff0e14a3ecb-282da467)
[api-reference/beta/api/nameditem-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/nameditem-update.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-af45a21b9f934133184b04140374b432-282da467)
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-282da467)
[api-reference/v1.0/api/workbook-list-worksheets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/workbook-list-worksheets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-list-worksheets?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-d6d811a02465f91c23f6732701817303-282da467)
[api-reference/v1.0/api/workbook-post-tables.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/workbook-post-tables.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-post-tables?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-6ad56cff6d997e8455f70574f2c71b57-282da467)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api [...]

2021-04-08 22:35 UTC, opbld30 commented
Docs Build status updates of commit _[2fe3586](https://github.com/microsoftgraph/microsoft-graph-docs/commits/2fe3586f497c778948615986e63e4612f2fba4a2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-f986fb27eb8455f7aafa1208cf70b9aa-2c46e3c4)
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-2c46e3c4)
[api-reference/v1.0/api/workbook-list-worksheets.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/workbook-list-worksheets.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-list-worksheets?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-d6d811a02465f91c23f6732701817303-2c46e3c4)
[api-reference/v1.0/api/workbook-post-tables.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/workbook-post-tables.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-post-tables?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-6ad56cff6d997e8455f70574f2c71b57-2c46e3c4)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/ch [...]

2021-04-08 22:52 UTC, opbld32 commented
Docs Build status updates of commit _[f3f7a53](https://github.com/microsoftgraph/microsoft-graph-docs/commits/f3f7a5312ba621a222589aa880cf22eb3f9e032c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) | [Details](#user-content-f986fb27eb8455f7aafa1208cf70b9aa-85308a22)
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-85308a22)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://gi [...]

2021-04-08 22:57 UTC, opbld32 commented
Docs Build status updates of commit _[4faf283](https://github.com/microsoftgraph/microsoft-graph-docs/commits/4faf2830e98faaf657e37311f9dd1ecf9c0895fa)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-9b93fdaa)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob [...]

2021-04-08 23:02 UTC, opbld30 commented
Docs Build status updates of commit _[a7becab](https://github.com/microsoftgraph/microsoft-graph-docs/commits/a7becabc4638bdf8807ebf810406e479bcc141e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-93815a6d)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob [...]

2021-04-09 00:56 UTC, opbld30 commented
Docs Build status updates of commit _[d7fef8f](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d7fef8f8066f058fb9edabd3dace61a7bf4850fe)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-739c78cc20d2aa5fd610e5019c6b9741-ed35ef71)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob [...]

2021-04-09 02:53 UTC, opbld30 commented
Docs Build status updates of commit _[89515db](https://github.com/microsoftgraph/microsoft-graph-docs/commits/89515dba956e0cd2aec7eb9af0eba61219b5aa0b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/nameditem-addformulalocal.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-addformulalocal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-addformulalocal?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-f3f28b22645034ced3e8ca1f6377cd58-1cbaadc6)
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://github.com/microsoftgr [...]

2021-04-09 02:58 UTC, opbld34 commented
Docs Build status updates of commit _[7ce933e](https://github.com/microsoftgraph/microsoft-graph-docs/commits/7ce933eaf03e7674061fab3f0b5aa84d74097da1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlineformat-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Dele [...]

2021-04-09 12:51 UTC, opbld34 commented
Docs Build status updates of commit _[d4b2830](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d4b2830d06a2bf1f10ea63bf4aea659042cffdf0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/beta/api/chart-delete.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-delete.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-delete?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-image.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-image.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-image?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-list.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-post-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-post-series.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-post-series?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setdata.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setdata.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setdata?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-setposition.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-setposition.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-setposition?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chart-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chart-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-add.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-add?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartcollection-itemat.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartcollection-itemat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartcollection-itemat?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartdatalabels-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartdatalabels-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartdatalabels-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-clear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-clear?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfill-setsolidcolor.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfill-setsolidcolor.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfill-setsolidcolor?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartfont-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartfont-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartfont-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartgridlines-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartgridlines-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartgridlines-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-get.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-get.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-get?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlegend-update.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/beta/api/chartlegend-update.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/graph/api/chartlegend-update?view=graph-rest-beta&branch=pr-en-us-12173) (graph-rest-beta) |
[api-reference/beta/api/chartlineformat-clear.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Dele [...]

2021-04-09 15:52 UTC, opbld33 commented
Docs Build status updates of commit _[d93db34](https://github.com/microsoftgraph/microsoft-graph-docs/commits/d93db345be290eefd025b648c8e6440db810504b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/api/chart-list-series.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/chart-list-series.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chart-list-series?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-62afd246fbe0d6d54dd86c97a1a103ff-004a8e3d)
[api-reference/v1.0/api/chartpoint-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/chartpoint-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chartpoint-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-9f5298f7221caef0f0b529d19a301dbb-004a8e3d)
[api-reference/v1.0/api/chartseries-list-points.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/chartseries-list-points.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chartseries-list-points?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-ee2b4b52f61e00ea14c213f995996db1-004a8e3d)
[api-reference/v1.0/api/chartseries-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/chartseries-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/chartseries-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-a73ab8becd90b98057be3b75046ce461-004a8e3d)
[api-reference/v1.0/api/nameditem-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/nameditem-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/nameditem-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-e58cc3562dcb3b9984edc629d156101f-004a8e3d)
[api-reference/v1.0/api/rangeborder-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/rangeborder-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/rangeborder-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-066c713f0d593426d4f16e4fa3fbd6ee-004a8e3d)
[api-reference/v1.0/api/rangeformat-list-borders.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/rangeformat-list-borders.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/rangeformat-list-borders?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-7743c2bc9a3b20987078814c4633a367-004a8e3d)
[api-reference/v1.0/api/rangesort-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/rangesort-apply.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/rangesort-apply?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-1971b0acce52143804268c396e6eb287-004a8e3d)
[api-reference/v1.0/api/table-list-columns.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/table-list-columns.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-columns?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-d229ae0b7c57fea781ae3fc28269bd1c-004a8e3d)
[api-reference/v1.0/api/table-list-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/table-list-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list-rows?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-8e11a0a097cb030317e253d25b8c02e5-004a8e3d)
[api-reference/v1.0/api/table-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/table-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-634225666a89825f99d102265824019d-004a8e3d)
[api-reference/v1.0/api/table-post-rows.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/table-post-rows.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/table-post-rows?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-e082c22528d72aeb73c0952d6d11ea99-004a8e3d)
[api-reference/v1.0/api/tablecolumn-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/tablecolumn-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablecolumn-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-0b4dc476fdc62a62e4eda625aa3ec98c-004a8e3d)
[api-reference/v1.0/api/tablerow-list.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/tablerow-list.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerow-list?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-49a6fa93f13196a19d22f094d06162f9-004a8e3d)
[api-reference/v1.0/api/tablerowcollection-add.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/tablerowcollection-add.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablerowcollection-add?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-1fb299fc2442849cd4aba2d2bb924e52-004a8e3d)
[api-reference/v1.0/api/tablesort-apply.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/tablesort-apply.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/tablesort-apply?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-c488749581f4167fbfd68cf79a65eca3-004a8e3d)
[api-reference/v1.0/api/workbook-list-names.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/workbook-list-names.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-list-names?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-4d50639b378b7eba7f45793c82f39848-004a8e3d)
[api-reference/v1.0/api/workbook-list-tables.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1.0/api/workbook-list-tables.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/graph/api/workbook-list-tables?view=graph-rest-1.0&branch=pr-en-us-12173) (>= graph-rest-1.0) | [Details](#user-content-80daee3ed4f2a4cc80b94c7d938b6274-004a8e3d)
[api-reference/v1.0/api/workbook-post-tables.md](https://github.com/microsoftgraph/microsoft-graph-docs/blob/isvargasmsft-Workbooks-NamedItems-Delete/api-reference/v1 [...]

2021-06-16 15:01 UTC, closed without merging